### ISSUE TITLE
auto send upload when I select file

### ISSUE THREAD

**Issue by gmisterk** [kartik-v/bootstrap-fileinput#1002]
Hi all,

I want to trigger an upload directely after  i select a file.

Now, i need to click in "upload' button to send my file, and i am looking for a workaround to ovoid this click. 

any idea to do that ?

Regards

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Have you  [read the guidelines](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md) for issue logging?

You need to read the [plugin documentation](http://plugins.krajee.com/file-input) and the  [plugin demos](http://plugins.krajee.com/file-input/demo) before logging issues.

Your use case could be addressed through the [available plugin methods](http://plugins.krajee.com/file-input#methods) and is covered in [ajax demo example # 5](http://plugins.krajee.com/file-input-ajax-demo/5) and  [ajax demo example # 6](http://plugins.krajee.com/file-input-ajax-demo/6).

**Comment by litrozima** [comment]
I have the same problem! 

The code in "filebatchselected" event

$el1.fileinput("upload"); 

doesn't do anything. I want to upload the file without click on the upload button

**Comment by kartik-v** [comment]
Bug #1460 has been recorded. This will be resolved via that shortly.
