### ISSUE TITLE
A problem while using the  multiple Synchronous Upload mode.  

### ISSUE THREAD

**Issue by ZhangBo2016** [kartik-v/bootstrap-fileinput#1003]
hi, manito:
   I have a problem while using the  multiple Synchronous Upload mode.  

   That is : input-name which is the name attribute of my input are similar  "file_data"  or $_FILES['input-name'],  and each file's input-name is the same.  but i need input-name like "file_data[i]" ( "file_data[0]"、"file_data[1]"... ) to distinguish each file, so that those files can be resolved in server. 

   thanks for you help!

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
You need to do some reading on native HTML5 inputs and how server code handles them.

I assume you are using PHP server code or Java or similar.

Read [this webtip](http://webtips.krajee.com/read-html5-multiple-file-input-php/) on how you must configure your native file input markup to receive multiple files via PHP.
