### ISSUE TITLE
[BugRepair]Delete all uploaded file but still apear on next upload

### ISSUE THREAD

**Issue by phardye** [kartik-v/bootstrap-fileinput#1007]
on fileinput.js line 860:
I fixed this bug by chaning( line 860 )
                    self.previewCache.data.content[index] = null;
                    self.previewCache.data.config[index] = null;
                    self.previewCache.data.tags[index] = null;
to
                    self.previewCache.data.content.splice(index,1);
                    self.previewCache.data.config.splice(index,1);
                    self.previewCache.data.tags.splice(index,1);

I don't know whether it will takes any bad effect.

**Comment by kartik-v** [comment]
Yes your change will not give a correct behavior. Can you share a JS fiddle or example to see your problem?

**Comment by phardye** [comment]
hi, I am sorry I just see your reply. Here is my example: http://test.baiseyun.com/test.html

**Comment by kartik-v** [comment]
I see it working fine after I delete a file and upload another file.

Are you expecting that on refresh of the page the initial preview will show updated? If so you need to write your code accordingly to set the correct initialPreview on load.

**Comment by phardye** [comment]
no, that was not what  I mean.
I do meet the problem. Maybe is the problem with my Chrome. I will show you a gif, you can see what i have done. gif url: http://test.pisaya.com/demo.gif
That gif is very big, it is up to 2.5MB,please be patient.
If you find this problem through this gif,please let me know.
Thanks again!

**Comment by kartik-v** [comment]
Thanks. Will check and update.

**Comment by kartik-v** [comment]
It seems some problem with the code you are running on your environment. Ensure you have the updated code release from this repo.

Check the [ajax demo scenario # 7](http://plugins.krajee.com/file-input-ajax-demo/7) which is exactly similar to what you are testing and you can see that everything works fine (cross check). Closing currently. In case you find an issue in the plugin, please update and will reopen the issue.
