### ISSUE TITLE
Upload order

### ISSUE THREAD

**Issue by cazacugmihai** [kartik-v/bootstrap-fileinput#1010]
Hi,

Is there a way to upload the selected files one after the other, automatically?

I'm uploading the files using this code: 

```
uploadOptions = 
    uploadAsync: true
    ...

$input.fileinput(uploadOptions)

$input.on('filebatchselected', (event, files) =>
    $input.fileinput('upload')
)
```

and I need that the 2nd file to be uploaded only after the 1st one has received the response from the server (and so on).

Thanks!

**Comment by lamoglia** [comment]
Hi, You need to set the uploadAsync option to false.

**Comment by cazacugmihai** [comment]
Yes, but that means that all files (~ 20) are sent in a batch and this is not what I want.

**Comment by lamoglia** [comment]
No, that means that the uploads will be serialized one after another (not parallel)

**Comment by cazacugmihai** [comment]
I have just seen that there is a `maxFileCount` option that can be used also in this mode. I missed that. I though that it was designed for async only.

**Comment by cazacugmihai** [comment]
Yes, you have right. Thank you!

**Comment by Minotti** [comment]
Hello, reopening this issue. :D

I have the same problem but with a small detail when I changed uploadAsync to false.

When uploading 3 files and uploading 1 file, the process is interrupted and the remaining 2 files are not sent.

Do I have a new problem? return from the server maybe?
