### ISSUE TITLE
fileuploadederror triggered twice times if two uploaded files uploaded before

### ISSUE THREAD

**Issue by mj3018** [kartik-v/bootstrap-fileinput#1014]
upload file in a modal,first time upload two files to server,then reopen the modal,upload a invalid file,the fileuploadederror will trigger twice.

**Comment by mj3018** [comment]
if three file uploaded to server before,next time select a invalid file,the fileuploadederror will trigger three times.why this?

**Comment by mj3018** [comment]
fileInput:{
        $el:null,
        fileCounts:0,
        frameHeight:'145px',
        default_options:{
            uploadAsync: false,
            showCaption: false,
            showUpload: false,
            showCancel: false,
            showClose: false,
            showRemove: false,
            showBrowse: false,
            showUploadedThumbs: false,
            captionClass: "col-sm-6",
            allowedFileTypes: ['image'],
            allowedFileExtensions: ['jpg', 'png', 'gif'],
            maxFileSize: 10*1024,
            minFileCount: 1,
            maxFileCount: 5
        },
        display_options:{
            dropZoneTitleClass:"hide"
        },
        edit_options:{
            showPreview:true,
            showUploadedThumbs: true,
            dragClass:"hide",
            showDrag:false,
            dropZoneTitle:'drop or <a id="upload-file-button color-success" onclick="appOption.fileInput.triggerUpload()">browse<i class="fa fa-cloud-upload"></i></a>',
            removeFromPreviewOnError:true,
            overwriteInitial: false,
            elErrorContainer:'hide',
            previewSettings: {
                image: {width: "auto", height: "60px"},
                html: {width: "50px", height: "40px"},
                text: {width: "50px", height: "40px"},
                video: {width: "50px", height: "40px"},
                audio: {width: "50px", height: "40px"},
                flash: {width: "50px", height: "40px"},
                object: {width: "50px", height: "auto"},
                pdf: {width: "50px", height: "40px"},
                other: {width: "50px", height: "40px"}
            }
        },
        init:function ($el, options, editable) {
            var _this = this;
            _this.$el = $el;
            var ops;
            ops = editable ? $.extend({},_this.default_options,_this.edit_options) : $.extend({},_this.default_options,_this.display_options);
            $el.fileinput($.extend({},ops,options));

            if(editable) {
                $(".file-drop-zone").css("min-height",_this.frameHeight);
                $el.on("filedeleted",function () {
                    appOption.fileInput.fileCounts--;
                    if(appOption.fileInput.fileCounts <= 0) {
                        appOption.fileInput.destroy($el).init($el,options,editable);
                    }
                }).on("fileremoved",function () {
                    appOption.fileInput.fileCounts--;
                    if(appOption.fileInput.fileCounts <= 0) {
                        appOption.fileInput.destroy($el).init($el,options,editable);
                    }
                }).on("filebatchselected",function (event, files) {
                    if(files) appOption.fileInput.fileCounts += files.length;
                }).on("fileuploaderror",function (event, data, msg) {
                    toastr.options.timeOut = 20000;
                    toastr.error(msg);
                }).on("change",function () {
                    // _this.$el.val("");
                });
            }
        },
        triggerUpload:function () {
            this.$el.val("");
            return this.$el.trigger("click");
        },
        destroy:function ($el) {
            $el.fileinput("destroy");
            return this;
        },
        upload:function ($el) {
            $el.fileinput("upload");
            return this;
        },
        refresh:function ($el, options) {
            if(isEmpty(options)) {
                $el.fileinput("refresh");
            }else {
                $el.fileinput("refresh",options);
            }
            return this;
        },
        progressSuccess:function () {
            $(".file-input").find(".progress").html('<div class="text-center back-main color-white">success</div>');
            $(".file-preview-loading").removeClass("file-preview-loading");
            $(".file-uploading").removeClass("file-uploading");
        },
        progressFailure:function () {
            $(".file-input").find(".progress").html('<div class="text-center back-error color-white">error</div>');
            $(".file-preview-loading").removeClass("file-preview-loading");
            $(".file-uploading").removeClass("file-uploading");
        }
    },

**Comment by erick-x** [comment]
哈哈，我也遇到相同问题，跟踪发现，上传时，如果页面未刷新，则会出现每次上传的文件会再次触发fileuploaded事件。而且他们的返回时间戳相同。返回内容也相同。

**Comment by erick-x** [comment]
same question ，you can add  e.preventDefault()  to  fileuploaded  event  。Good luck to you

**Comment by mj3018** [comment]
I have added event.preventDefault() here,but i was failed.am i wrong?






At 2017-07-20 17:52:20, "erick-x" <notifications@github.com> wrote:


same question ，you can add e.preventDefault() to fileuploaded event 。Good luck to you

**Comment by rapgithub** [comment]
how do you use  $el.fileinput("refresh"); ? because I am having problems to refresh the content with ajax... see this link maybe you know what is the problem is:

here
https://github.com/kartik-v/bootstrap-fileinput/issues/1028

**Comment by kartik-v** [comment]
It seems some problem the way you are writing your code. Cross check as cannot reproduce this. 

Anyway there are some related enhancements added as well to file upload single method currently.

**Comment by rapgithub** [comment]
Any news about the problem of refreshing the images  with ajax calls properly like in my link i provided and no news about it:

https://www.dropbox.com/s/ugwhk09apy99fag/github-fileinput-issue.mov?dl=0


thanks
