### ISSUE TITLE
Show  button text changes with button functionality as Image path is coming from back-end

### ISSUE THREAD

**Issue by ashishbansal-kmc** [kartik-v/bootstrap-fileinput#1016]
i want to show image on modal as image path is coming from back-end. Since it is easy to show image but how to trigger function which shows change and remove button like after upload image(after select image ).Please suggest me function present in library file.
I have implemented this 
 $('[data-provides="fileinput]').addClass('fileinput-exists').removeClass('fileinput-new');
                $('[data-provides="fileinput]').trigger('change.bs.fileinput','click');

**Comment by kartik-v** [comment]
Follow the [preview management demos](http://plugins.krajee.com/file-preview-management-demo) to achieve your use case.
