### ISSUE TITLE
Uploading intitialpreview images as well.

### ISSUE THREAD

**Issue by xw7** [kartik-v/bootstrap-fileinput#1017]
Is it possible to upload the initial preview images as well without Ajax, I am using a form and on submit it uploads all of the photos correctly but it doesn't include the initial preview images. Is this possible or not?

**Comment by kartik-v** [comment]
Not sure I understand what you mean. This plugin is intended to upload files ONLY from the client to the server. 

Initial preview is content displayed from the server typically via your plugin init code. It is therefore part of your own application and server code to manage and handle these files.

**Comment by xw7** [comment]
Sorry, I didn't make myself clear enough.

We have the upload feature working and it uploads the images perfectly, however we have a edit feature on our items where frontend users can go in and change images.

We have managed to code the file input to pick up all images attached to each item and display them as images in the initial preview, but when we click upload it only uploads the new ones and the initial preview ones are removed even though they still display in the upload box.

I thought there may have been an easy way of re-uploading/getting their ID on the current system but if not I will manually code it so it detects the ID and stores it along with new ID's.

On the initial preview it doesn't allow us to remove any of the initial preview images when using the bin button, however new ones do.

I will take another look today and see if I can create a workaround to get it working as required for editing.

Thank you for taking the time to reply, much appreciated.
