### ISSUE TITLE
How to hide / show Remove button on file select and clear

### ISSUE THREAD

**Issue by ruchisheth** [kartik-v/bootstrap-fileinput#1018]
## Prerequisites
Hi want to hide remove button on file clear. I have set the default preview image(defaultPreviewContent)
and I am success to do the above by following code.

```
$(this).on('filecleared', function(event) {
          var fileinput_options = getFileInputOptions();

          $.extend( fileinput_options, {
            defaultPreviewContent: '<img src="'+getDefaultImage()+'" alt="Your Avatar">',
            showRemove: false,
        });
          $(this).fileinput('destroy');
          $(this).fileinput('refresh',fileinput_options);
        });
```
Now I want to show that remove button again when file is selected. I tried the below code. but want work
```
$(this).on('fileselect', function(event) {
       var fileinput_options = getFileInputOptions();
       $(this).find('.fileinput-remove.fileinput-remove-button').removeClass('hide');
       });
```
![lc settings 1](https://user-images.githubusercontent.com/20935380/28313645-442d3b24-6bd5-11e7-80c4-5e5db95d5993.png)

Here is my getFileInputOptins() function
```
function getFileInputOptions(){
  return fileinput_option = {
    showUpload: false,
    showRemove: true,
    dropZoneEnabled: false,
    browseClass: "btn btn-primary fileinput-btns",
    removeClass: "btn btn-default fileinput-btns",
    initialPreviewAsData: true,
    overwriteInitial: true,
    preferIconicPreview: true,
    previewFileIcon: '<i class="fa fa-file"></i>',
    // allowedPreviewTypes: ['image'],
    previewFileIconSettings: {
      'doc': '<i class="fa fa-file-word-o text-primary"></i>',
      'xls': '<i class="fa fa-file-excel-o text-success"></i>',
      'ppt': '<i class="fa fa-file-powerpoint-o text-danger"></i>',
      'pdf': '<i class="fa fa-file-pdf-o text-danger"></i>',
      'zip': '<i class="fa fa-file-archive-o text-muted"></i>',
      'htm': '<i class="fa fa-file-code-o text-info"></i>',
      'txt': '<i class="fa fa-file-text-o text-info"></i>',
      'mov': '<i class="fa fa-file-movie-o text-warning"></i>',
      'mp3': '<i class="fa fa-file-audio-o text-warning"></i>',
      // 'jpg': '<i class="fa fa-file-photo-o text-warning"></i>',
    },
    previewFileExtSettings: { // configure the logic for determining icon file extensions
      'doc': function(ext) {
        return ext.match(/(doc|docx)$/i);
      },
      'xls': function(ext) {
        return ext.match(/(xls|xlsx)$/i);
      },
      'ppt': function(ext) {
        return ext.match(/(ppt|pptx)$/i);
      },
      'zip': function(ext) {
        return ext.match(/(zip|rar|tar|gzip|gz|7z)$/i);
      },
      'htm': function(ext) {
        return ext.match(/(htm|html)$/i);
      },
      'txt': function(ext) {
        return ext.match(/(txt|ini|csv|java|php|js|css)$/i);
      },
      'mov': function(ext) {
        return ext.match(/(avi|mpg|mkv|mov|mp4|3gp|webm|wmv)$/i);
      },
      'mp3': function(ext) {
        return ext.match(/(mp3|wav)$/i);
      },
    },
    fileActionSettings: {
      showDrag: false,
      showZoom: true,
      showUpload: false,
      showDelete: false,
    },
  }
}
```
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Refresh method does a destroy and recreate automatically.

In case you intend on using `destroy` first... you can just recreate the fileinput widget using `$(this).fileinput(fileinput_options);`.

**Comment by kartik-v** [comment]
You should be able to use the [refresh method](http://plugins.krajee.com/file-input/plugin-methods#refresh).

```js

```
