### ISSUE TITLE
Add new files with form submission

### ISSUE THREAD

**Issue by afabri73** [kartik-v/bootstrap-fileinput#1019]
Hi,
I'm using your plugin in my submission form and it function properly...but...if a user try to select multiple image in different time (for example because images are in different folders), it lost the already selected images.
There is a way to do that?

I saw this is possible with ajax...but I need to use a form submission.
There is a trick  or a workaround?

Thanks for support
Adriano

**Comment by kartik-v** [comment]
No HTML file input is read only and cannot be manipulated by javascript to add additional files. So you cannot use the features of ajax mode with native form submission. 

You can instead do the reverse... send all of your form data as `uploadExtraData` and use ajax mode of submission.
