### ISSUE TITLE
How to get the file object after resized?

### ISSUE THREAD

**Issue by dcy** [kartik-v/bootstrap-fileinput#1020]
Hi!
```
<input id="input-25" name="input25[]" type="file" class="file-loading" v-on:change="onFileChange">

        onFileChange: function(e) {
            var file = e.target.files[0] || e.dataTransfer.files[0]
            console.log("files", file)
            this.avatar_file = file
        },
```
```onFileChange``` get the origin image, not the resized file. I want to get the resized file object then post it to server by another method([vue-resource](https://github.com/pagekit/vue-resource)).
How to get file object after resized?

**Comment by kartik-v** [comment]
Resize image file is applicable only for ajax mode of upload and will be sent only via the ajax mode and will not be stored in the input via the form submission mode. You will receive the resized files on your server `uploadUrl` action.

**Comment by dcy** [comment]
Can i get the file object like ```onFileChange's e.target.files[0]```?
```
.on('fileimageresized', function(event, previewId, index) {
            var img = _.first(document.getElementById(previewId).getElementsByTagName("img"))
        })
```
Don't know how to continue.
