### ISSUE TITLE
Avatar upload issue in Chrome

### ISSUE THREAD

**Issue by ruchisheth** [kartik-v/bootstrap-fileinput#1021]
## Prerequisites

http://plugins.krajee.com/file-avatar-upload-demo
Click on cancel in file browse dialog removes the previously selected image and set avatar in preview
**Note**:- Issue in Chrome. In Firefox it works as expected.

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Click on folder icon to select image
2. Select image to upload
3. Now again click on folder icon to select different image
4. and click cancel in file browse dialog. 

## Expected behavior and actual behavior

When I follow those steps, I see...
It removes previously selected image and set avatar.
I was expecting...
It should show the previously selected image.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is an expected behavior specific to the Chrome browser... it sets the file input to null when you click cancel in the file dialog... which will result in the file getting removed.

Read the [fileselectnone event](http://plugins.krajee.com/file-input#event-fileselectnone) which you can use for your use case to alert the user if such a thing happens.
