### ISSUE TITLE
After submit clear the preview and empty the file upload 

### ISSUE THREAD

**Issue by rapgithub** [kartik-v/bootstrap-fileinput#1022]
I am using ajax async to upload the file and fields data... after the images has been uploaded to the 
server i want to reset the form and I am having this problem:

using:

$('.upload-form').fileinput('clear');

or

$('.upload-form').fileinput('reset');

it is the same problem
in the console I can see the following error message:

TypeError: $('.upload-form').fileinput is not a function. (In '$('.upload-form').fileinput('clear')', '$('.upload-form').fileinput' is undefined)

how can I reset the form upload-form using clear or reset? if always showing me fileinput is not a function... 

I use this here and not working

}).on('filebatchuploadsuccess', function(event, data, id, index) {
    alert('filebatchuploadsuccess');
   $('.upload-form').fileinput('clear');

});

thanks for any tips to fix this problem... thanks

**Comment by kartik-v** [comment]
Refer the [guidelines comment](https://github.com/kartik-v/bootstrap-fileinput/issues/1023#issuecomment-316895042).

Please read the [documentation](http://plugins.krajee.com) to understand how to initialize the plugin or call the plugin methods and events. You should be calling and initializing the `fileinput` plugin on the native file input not the form.

**Comment by rapgithub** [comment]
Thank you i have fixed the issue using the another method but still having some issues when retrieving the image data from the database and trying to put the images again when editing in the stack of images...

My html
<input id="images" class="images" name="images[]" type="file" multiple>

Image data saved in mysql database
a:1:{i:0;s:44:"uploads/65dd0bca3c0077c1c0fabd37b5dfd855.jpg";}

After unserialized to read by javascript: 
images: ["uploads/65dd0bca3c0077c1c0fabd37b5dfd855.jpg"] 

then i am using when retrieving the data in json format:
                var obj = JSON.parse(data);

      $.each(obj.images,function(i,item){
                        alert(obj.images); //print OK the image on screen with the path
                              $('#images').fileinput('addToStack', obj.images); // does not add the file to the stack for previewing
     });


in this case when editing a record that has one or more pictures I want to be able to add this images previously saved into the database to the stack of images in the uploader again for purpose of delete of update images information..

I am using
$('#images').fileinput('addToStack', obj.images);

but does not work
any ideas which method should I do for editing?

thanks

**Comment by rapgithub** [comment]
I have found this initialPreview but it does not refresh the images inside the uploader when calling it for editing mode and update from database...

 $('#images').fileinput({   
    initialPreview: [
       obj.images
    ],
   overwriteInitial: false,
           initialPreviewAsData: true

 });
