### ISSUE TITLE
How to submit a form with fields together with the images and after the images has been uploaded remove the previews and files from the form?

### ISSUE THREAD

**Issue by rapgithub** [kartik-v/bootstrap-fileinput#1023]
I want to remove the previews and files from the file input after the images has been successfully uploaded and reset the form in complete...

I want to be able to submit also the form fields together with the uploads how can I do this without having to have two forms in the same screen?

this means I submit data to the database and after all data has been submitted i want to clear reset or remove the form so it is empty again...

how can I do that?

thanks

**Comment by kartik-v** [comment]
Please review the [guidelines for new issues or contributing](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md) to this repository.

This repo is to be used only for reporting bugs or issues with the extension.

For programming related help and queries use the comments and discussions sections on the plugin [docs](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo) pages to see if someone can help you.

You can also use the [webtips Q & A forum](http://webtips.krajee.com/questions) to post your programming related questions and queries.

**Comment by rapgithub** [comment]
thanks but i have another issue now maybe you know where the problem is:

I am dinamically updating the uploader for editing with javascript so I use refresh for updating the upload drag and drop areas with the images saved in the database like this and it works showing the images but the issue it is that when i select another record to edit the previous images stay in the drag and drop area and even if I use clear, it is like they get appended to the drag and drop area instead of be cleaned form the uploader before inserting the new editing images tha belong to another record.

My question : how can i make the initialPreview to show only the images i am calling to edit dinamically and not appending the images with the previous? clean does not work in this case...

I am using:
where obj.images is an array of images and  image.config it is the initialPreviewConfig of the images to be deleted... if i press delete...  in the format

[{"url":"delete.php","captions":"uploads/437b016f24b03e95aec14d755b0016d6.jpg","key":56},
{"url":"delete.php","captions":"uploads/437b016f24b03e95aec14d755b0016d6.jpg","key":46}]


$('#images').fileinput('refresh', {
uploadUrl: "upload.php",
uploadAsync: true,
minFileCount: 1,
maxFileCount: 5,
overwriteInitial: false,
initialPreview: obj.images,
initialPreviewAsData: true, 
initialPreviewFileType: 'image', 
initialPreviewConfig: image.config,
});


the problem is that this works for updating the uploader area dinamically when selecting the record to edit with its images but when selecting another records the images previously shown are staying in the drag and drop area like appending them instead of cleaning the drag and drop area and inserting the new images of the new record...

how to fix this behavior and edit dinamically the images the right way?
thanks
