### ISSUE TITLE
Send file and extra data from input type text

### ISSUE THREAD

**Issue by teoSalvetti** [kartik-v/bootstrap-fileinput#1024]
I want some extra information when I upload a file. I read about it, [here](https://github.com/kartik-v/bootstrap-fileinput/issues/140) for example, but I don't think is the same.

I want put 2 input type text, if I write something there, I want send these two value with the file to the server.

Is it possible?

**Comment by kartik-v** [comment]
Read docs. Send these via [`uploadExtraData`](http://plugins.krajee.com/file-input#option-uploadextradata) as an object (key value pairs).
