### ISSUE TITLE
Images saved to database, how to preview them again when editing the record having the images...? addtostack is not working is there another way to do this?

### ISSUE THREAD

**Issue by rapgithub** [kartik-v/bootstrap-fileinput#1025]
having some issues when retrieving the images data from my mysql database and trying to put the images again when editing in the stack of images of the uploader for previewing them again and edit them...

My html
<input id="images" class="images" name="images[]" type="file" multiple>

Image data saved in mysql database
a:1:{i:0;s:44:"uploads/65dd0bca3c0077c1c0fabd37b5dfd855.jpg";}

After unserialized to read by javascript: 
images: ["uploads/65dd0bca3c0077c1c0fabd37b5dfd855.jpg"] 

then i am using when retrieving the data in json format:
                var obj = JSON.parse(data);

      $.each(obj.images,function(i,item){
                        alert(obj.images); //print OK the image on screen with the path
                              $('#images').fileinput('addToStack', obj.images); // does not add the file to the stack for previewing
     });

in this case when editing a record that has one or more pictures I want to be able to add this images previously saved into the database to the stack of images in the uploader again for purpose of delete of update images information..

I am using
$('#images').fileinput('addToStack', obj.images);

but does not work
any ideas which method should I do for editing?

thanks

**Comment by rapgithub** [comment]
I have found this initialPreview but it does not refresh the images inside the uploader when calling it for editing mode and update from database...

 $('#images').fileinput({   
    initialPreview: [
       obj.images
    ],
   overwriteInitial: false,
           initialPreviewAsData: true

 });

**Comment by kartik-v** [comment]
Please follow the guidelines for issue logging as [highlighted in this comment](https://github.com/kartik-v/bootstrap-fileinput/issues/1023#issuecomment-316895042).

Do not post queries for coding and programming help here? You may do this in the comments & discussions section of the plugin documentation and demos site. Use this repo only for reporting bugs and issues or enhancements for using the plugin.

**Comment by rapgithub** [comment]
this topic is closed but the issue it is still there when editing the records with initialPreview of the images the images are shown correctly but when editing another records the drag and drop area still keeping the images of the previous edit... I am trying dynamically edit records with its images and it does not work properly.

i have tried reset or clear and not working... only refreshing the page in the browser helps... but i am using ajax and everything to save, edit and new records...

any solution for this?
thanks
