### ISSUE TITLE
Changing allowedFileTypes and maxFileSize mulitiple times

### ISSUE THREAD

**Issue by francisjohnholmes** [kartik-v/bootstrap-fileinput#1026]
I have a two fields in my form that contain the allowedFileTypes and maxFileSize that I need to allow for a selected document type.  These values are pulled from a db and updated based on the selection in a drop down list.  The js is pulling the values back correctly and the variables are populating.

The problem I have is that the values are picked up dynamically from within the form on the first selection but then do not update for further selections.   This code does not get reevaluated:

```
var fileTypes = $("#FileTypes").val();
var MaxFileSize = $("#MaxFileSize").val();
             $("#inputFile").fileinput({
                 maxFileCount: 1,
                 allowedFileExtensions: [fileTypes],
                 maxFileSize: MaxFileSize
             });
```

Any idea of a workaround?

Browsers
- [ ] Google Chrome

Operating System
- [ ] Windows

Libraries

- jQuery version: 2.1.4
- bootstrap-fileinput version: 4.3.5

**Comment by kartik-v** [comment]
You need to handle this logic in your application program code. You need to re-initialize the fileinput plugin after the `allowedFileTypes` parameter is selected in your other form input. You may use the plugin's [`destroy method`](http://plugins.krajee.com/file-input#method-destroy) to destroy the plugin and reinitialize again with new parameters.
