### ISSUE TITLE
Dynamically added images using initialpreview for edit records are not working properly using ajax! any solution?

### ISSUE THREAD

**Issue by rapgithub** [kartik-v/bootstrap-fileinput#1027]
I am using ajax to save records and edit records that contains a multiple image field to upload images and update them...

i am dynamically editing the records with ajax and I use initialpreview and initialPreviewConfig to do this and be able to delete one images uploaded and update the record.. then after

for instance i want to edit 1 record that contains 5 images saved in the database and one of the images needs to be deleted and then save the record again to the database...

in my case I have a list of records to edit on my left side of the screen (left SIDEBAR) and on the right I have the form with the fields, then when  I click over one record to edit from the sidebar i edit the record using ajax  and I can pull all info correctly from database and fill all the form fields and also the uploader with the images using initialpreview and initialPreviewConfig and this works fine... until here...

1) the first problem it is, the images in the uploader using initialpreview and initialPreviewConfig are there and I can delete just one for instance and save the record again to the database but anyway I delete one and still are 5 remaining the uploader it is telling me that there are no images to be updated or to be uploaded and i need again to upload the images even if the initialpreview of images are showing me 5 images there... 

Q: anyway to check before uploading or updating a record that the images loaded into the uploader using initialpreview and initialPreviewConfig are valid and still there when updating? I want to be able to delete the images I do not need to save the record again and update the database with the images sent...

2) the second problem it is that if I decide to edit another record using ajax and dynamically loading the information again of the fields and images saves but I click another records to edit... from the sidebar...  then the previous images of the last edit are still there maybe in the cache of the uploader this means that if the previous edited record was having 5 images and this new record i am editing now  has 6 images then it is showing me the file images of the previous record now and only one of the currently recording editing....  

how to fix this?

 i have tried to fix it clearing the uploader before adding the images using initialpreview of images and the problem it is still there...  the record editing still showing the images of the previous edited record in the uploader... 

the only way it works fine it is not using ajax and refreshing the browser and this way the images the belong to the recording editing are shown correctly but not using ajax dynamically because using ajax in this part the uploader  keeps the images of the previous record somewhere and show them all the time... 

how to fix this? any solution?
I can send my code if needed... but i am using all resources online and i have not found any solution for this two problems editing with ajax using initialpreview when editing the records saved previously in the database...

I think  initialpreview images must be updated and clear the upload when a new call to the fileinput is refreshed... but not working this way... 

i will appreciate any help and solution.
thanks a lot...

**Comment by kartik-v** [comment]
You may need to read the docs again. 

Read about [initialPreviewConfig](http://plugins.krajee.com/file-input#option-initialpreviewconfig) closely.

1. You can set a `initialPreviewConfig['key']` to uniquely identify each image file in the initial preview.
2. The  `initialPreviewConfig['url']` or the [deleteUrl](http://plugins.krajee.com/file-input#option-deleteurl)  will be the AJAX based server action that will be called when each thumbnail file is deleted.
3. The above ajax action will send back the `key` as mentioned in step 1 to identify which thumbnail file to delete on the server.

Please post other programming help and queries in the comments section of the [docs and demos](http://plugins.krajee.com/file-input).

**Comment by rapgithub** [comment]
yes I know that part you mentioned above
the problem does not comes from deleting the image via ajax but it comes when editing another record that load the images again in the uploader via ajax call and the information in the uploader is not refreshed with the new images loaded via initialPreviewConfig in this case the images shown are the ones of the previous record plus the ones of the new record.

that is the main issue... this behavior showing images of the previous record...
any ideas how to solve this?
I am not refreshing the browsing i am using all ajax to retrieve the info and load it and update it... with data fields works good but the uploader the images remain in the cache all the times even if the fileinput refresh option it is used...

Issue: images via ajax not being refreshed well when selecting another record to edit, 

Sample:
I have one record with two images i edit the record and i delete one picture..
then i go to the second record that has 3 pictures and when the images are displayed via ajax the uploader still showing that image left of the previous record in the screen and only 2 images of the 3 of the second record editing...

this means that the uploader is not refreshed properly with ajax using initialPreview or cache not cleaned after the fileinput is refreshed... 

any ideas about this issue?

**Comment by rapgithub** [comment]
the problem is here in the div:

file-drop-zone div.file-preview-thumbnails

these are not cleared when adding the new initialPreview images, so if I can rum 

$('.file-drop-zone div.file-preview-thumbnails').html(''); 

before the initialPreview images are added to the uploader it will be the solution why the  .file-preview-thumbnails are not refreshed before adding the new images ...

is there any function like filebatchinitialPreview or fileinitialPreview for initialPreview images added to the uploader? 

thanks
