### ISSUE TITLE
initialPreview images not being refreshed or cleared from the uploader drag and drop area when using ajax calls to retrieve the content 

### ISSUE THREAD

**Issue by rapgithub** [kartik-v/bootstrap-fileinput#1028]
I am not refreshing the browser and using only ajax to refresh the content of the page dynamically...
so when using initialPreview images added for editing I have the problem that the uploader preview images are not being refreshed or cleared and then the new initialPreview images call is not showing the records that belong to this records because they remain on the uploader in the drag and drop area...

the problem i guess it is here in the div block class:

'file-preview-thumbnails' not being refreshed... with the new content of images via ajax 

images are not cleared when using the new initialPreview images, so if I can run

$('.file-drop-zone div.file-preview-thumbnails').html(''); it will clear the preview-thumbnails before adding the new request ones and showing the images that belong to the record to be edited instead..
and it will be great before the initialPreview images are added to the uploader to have a function that can control this...

it will be the solution!!! because .file-preview-thumbnails are not refreshed or cleared before adding the new images with initialPreview ... in this case I am using ajax for all not refreshing the browser...

is there any function like filebatchpreinitialPreview or filepreinitialPreview i can call before initialPreview images added to the uploader?

here a link to a screen recording showing the problem:

https://www.dropbox.com/s/ugwhk09apy99fag/github-fileinput-issue.mov?dl=0

in the video you will see that dynamically I press the button edit image to show all images related to a record saved in the database and it shows one image in the 1 record, but if I click the 2 record it shows 3 images, and this is correct, but when I go back to the previous record that had 1 images uploaded it shows the image the belong to the 1 record index 1 but also shows the two images that belong to the 2 record showing images of index 2 index 3 ... this means that the preview is not clearing the index of previews in the drag and drop area when changing the record to edit... all previews with more images than the previous one are appended and not cleared to refresh the correct images that belong to a record... 

ANY TO FIX THIS BEHAVIOR?

thanks

**Comment by rapgithub** [comment]
any news about this issue ? thanks

**Comment by kartik-v** [comment]
Sorry - cannot reproduce your issue. Can you retry with the plugin's latest code and if you have an issue, please create a new issue with a proper JS Fiddle to see your case.
