### ISSUE TITLE
As for bootstrap-fileinput autoOrientImage only react at iphone or Apple image file.

### ISSUE THREAD

**Issue by sjmheaven25** [kartik-v/bootstrap-fileinput#1029]
thanks in advance.
I much appreciated your libraries, especially bootstrap-fileinput.

I'm engaging in developing image file upload feature on my website.
and I'm applying "autoOrientImage : false" in there, in order not to rotate image files in preview stage at any kind of orientated image files.

but  I've tried a lot of time, with many image files taken by several brands(iphone, samsung, sony, cannon etc.),
it only react at files made by iphone or apple cameras, other picture brand was rotated by itself.

I wonder it is meant to be like this? do you have any solution?

**Comment by kartik-v** [comment]
I understand you are trying to design your own image rotation code so it is not in scope of this plugin. If you use the `autoOrientImage` feature then the plugin does it for you automatically ... else if you need to write your own code and logic... you need to do it by parsing the EXIF data of the images. You may post your programming help related query on the comments and discussions section of the docs and demos pages. Closing this here as this repo is only for reporting bugs, issues, or enhancements for the plugin.
