### ISSUE TITLE
Can't upload images if select it one by one

### ISSUE THREAD

**Issue by giangvy1011** [kartik-v/bootstrap-fileinput#103]
My form input as: 
![krajee](https://cloud.githubusercontent.com/assets/9975901/5606667/043b33d8-946c-11e4-9c2f-7e9a5bef8767.png)

For example: 
Scenario 1: If I browse and select 2 images at once by (ctrl + select) and submit form, it uploads 2 images. 
Scenario 2: But if I browse image 1 and then browse image 2, it only uploads the last selected image?

I don't think my process.php is wrong because it works for Scenario 1. I think i miss some configuration, please help...! MANY THANKS

**Comment by kartik-v** [comment]
This is the inherent HTML native file input functionality (please read about limitations of native file inputs).  If you are using FORM based uploads - the file input will clear/reset and overwrite files selected each time you select browse - and WILL NOT REMEMBER what you previously loaded.

You would need to use plugin's feature of ajax based uploads if you want to queue files and remember your selection (refer the [ajax uploads section in demo](http://plugins.krajee.com/file-input/demo) if you need this).
