### ISSUE TITLE
refresh does not work properly together with images added using  initialPreview initialPreviewConfig 

### ISSUE THREAD

**Issue by rapgithub** [kartik-v/bootstrap-fileinput#1035]
I have concluded after many tests that refresh does not work for ajax dynamic content as expected...
it only refresh the current upload area but if I use refresh with onclick button to refresh the upload area with new content the refresh does not refresh properly... and shoes images of the previous gallery... 

adding the images using initialPreview and initialPreviewConfig... the refresh does not work properly when changing galleries:

$(".images-getmore").on('click', function() {

//ajax to load more images in other galleries     
$.ajax({ .... 
  // I assign the images dynamically to initialPreview and initialPreviewConfig
  var initialPreview = obj.images 
  var initialPreviewConfig = obj.config
});

$('#images').fileinput('refresh', {
.....//all options here for refresh
});

});

but using destroy method before refresh the images of the new gallery are displayed properly this way: I had to use $('#images').fileinput('destroy'); before refresh for this to work...

$(".images-getmore").on('click', function() {

//ajax to load more images in other galleries     
$.ajax({ .... 
  // I assign the images dynamically to initialPreview and initialPreviewConfig
  var initialPreview = obj.images 
  var initialPreviewConfig = obj.config
});

$('#images').fileinput('destroy');

$('#images').fileinput('refresh', {
.....//all options here for refresh
});

});

it will be nice if the refresh method can work for properly when using it with dynamically content of images using initialPreview and  initialPreviewConfig.... to retrieve images from db without having to use destroy... 

also another issue for this it is that when I use filepredelete function using this method of gallery navigation onclick the confirmation dialog is alerted many times and I have to click many times to delete the images of a gallery... I think that the filepredelete is cached many times when changing the galleries onclick... and then it is looping the action many times and it is a little annoying...

}).on("filepredelete", function(event, files) {
                          var abort = true;
                          if (confirm("Are you sure you want to delete this image?")) {
                            abort = false;
                          }
 return abort;

**Comment by macklus** [comment]
+1

More than 3 hours spend trying to run this... without luck :-(

I think should be so easy as:
```
$('#element').fileinput('refresh', {
    showBrowse: false,
    initialPreview: [ 'http:///mi_new_image_url/image.jpg]
});
```

**Comment by kartik-v** [comment]
Check the [docs for refresh method](http://plugins.krajee.com/file-input/plugin-methods#refresh). It does not allow refreshing initial preview. For that you need to call `destroy` method and then reinitialize plugin with complete fresh options.
