### ISSUE TITLE
{dataKey} never worked in otherActionButtons

### ISSUE THREAD

**Issue by wilsonwg** [kartik-v/bootstrap-fileinput#1038]
I had been stuck with this problem for months and still can't solve the problem.

I followed the example on the doc page. My codes:

```javascript
 var btns = '<button type="button" class="kv-cust-btn btn btn-xs btn-default" title="Download" data-key="{dataKey}">' +
            '<i class="glyphicon glyphicon-download"></i>' +
            '</button>';

$("#myFile").fileinput({
...
initialPreview: [
"http://kartik-v.github.io/bootstrap-fileinput-samples/samples/Desert.jpg",
"http://kartik-v.github.io/bootstrap-fileinput-samples/samples/Lighthouse.jpg",
                    ],
initialPreviewConfig:
     [
{caption: "Desert.jpg", size: 827000, width: "120px", url: "http://kartik-v.github.io/bootstrap-fileinput-samples/samples/Desert.jpg", key: 1},
{caption: "Lighthouse.jpg", size: 549000, width: "120px", url: "http://kartik-v.github.io/bootstrap-fileinput-samples/samples/Lighthouse.jpg", key: 2},
       ],
...
otherActionButtons: btns
        });

$('.kv-cust-btn').on('click', function() {
    var $btn = $(this), key = $btn.data('key');
    // do some actions based on the key
     console.log(key);
});
```

And I always get:
data-key=

Is this a bug or something I did wrong?

**Comment by kartik-v** [comment]
You can try to access it via `$btn.attr('data-key')` instead of `$btn.data('key')`.

Will see if I can enhance this.

**Comment by wilsonwg** [comment]
I just tried $btn.attr('data-key') but it still returns the same empty value data-key=
Maybe something related to scope. Just my guess.

**Comment by kartik-v** [comment]
Yes it seems a problem with your calling this code even before the DOM element is initialized... you need to call this code on `document.ready` event for example.

**Comment by wilsonwg** [comment]
I solved the problem!

if I use data-key="{dataKey}"

```javascript
 var btns = '<button type="button" class="kv-cust-btn btn btn-xs btn-default" title="Download" data-key="{dataKey}">' +
            '<i class="glyphicon glyphicon-download"></i>' +
            '</button>';
```
Then I get a very strange attribute code:
data-key=" data-key="2""=""
But I only put {dataKey}

```javascript
 var btns = '<button type="button" class="kv-cust-btn btn btn-xs btn-default" title="Download" "{dataKey}">' +
            '<i class="glyphicon glyphicon-download"></i>' +
            '</button>';
```

Then it renders the correct html attribute code: 
data-key="2"

So the example code on the doc page is misleading:
http://plugins.krajee.com/file-input#option-otheractionbuttons

**Comment by kartik-v** [comment]
Will correct the docs.

**Comment by wilsonwg** [comment]
I noticed that the doc got updated, the texts after the template section all appear to be red (after the datakey part). Perhaps you forgot to add a closed tag somewhere. It's a small thing, but kind of annoying when reading the doc.

**Comment by kartik-v** [comment]
Fixed.

**Comment by wilsonwg** [comment]
Great! Thank you!

**Comment by CrestApps** [comment]
I am trying to create a download button also. So I added the following to my config 

        otherActionButtons: '<button type="button" class="kv-cust-btn btn btn-xs btn-default text-muted" title="Download" {dataKey}>' +
                            '<i class="fa fa-download"></i>' +
                            '</button>',

The dataKey is replaced as expected `initialPreviewConfig.key`... but how can I also pass the download URL? When the use click on the "download" button, I want to download a the file to my local machine.

**Comment by wilsonwg** [comment]
@CrestApps : You can look my very first post and the very last few lines. You can pass your url into your scripts with the key. Ex: window.location = 'http://...donwload_url_here.../'+key; to initiate the download.  This is just one of the possible ways of doing it.
