### ISSUE TITLE
Remove button not working in  yii2-widget-fileinput, because of raise "filebeforedelete" event  

### ISSUE THREAD

**Issue by Danillaa** [kartik-v/bootstrap-fileinput#1042]
## Prerequisites

- [✓] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

## Steps to reproduce the issue

1. Try to delete uploaded image  (i use yii2-widget-fileinput)

## Expected behavior and actual behavior

I wanna delete files (i have use stash red button at preview), but nothing happens.

I found next key:
In click event we have fire filebeforedelete (self._raise('filebeforedelete', [vKey, extraData]);) https://github.com/kartik-v/bootstrap-fileinput/blob/ba837e1dac45c447d60a9fc1e80a33abb9db8afa/js/fileinput.js#L2397
 and we go to
 https://github.com/kartik-v/bootstrap-fileinput/blob/ba837e1dac45c447d60a9fc1e80a33abb9db8afa/js/fileinput.js#L1116
 where self.ajaxAborted = e.result;
 set out self.ajaxAborted to undefined and we cant achieve this condition 
https://github.com/kartik-v/bootstrap-fileinput/blob/ba837e1dac45c447d60a9fc1e80a33abb9db8afa/js/fileinput.js#L2405

## Environment

Browsers
doesn't matter

Libraries

- jQuery version: last
- bootstrap-fileinput version: last

Thx.

**Comment by Danillaa** [comment]
if initiate event filebeforedelete and return false all works perfect, but if not , deleting not working. 
Can we initiate default this event and return correct for e.result , or something else ?

**Comment by kartik-v** [comment]
This has been resolved via latest commit. Get the updated code.
