### ISSUE TITLE
Photoshop JPG upload: Error while resizing the image

### ISSUE THREAD

**Issue by EdredNew** [kartik-v/bootstrap-fileinput#1051]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Save JPG in Photoshop CS6 (quality < 9) and upload to site with bootstrap-fileinput plugin.
2. Plugin settings:
`		$("#images").fileinput({
			uploadAsync: true,
			uploadUrl: "fileinput_upload.php",
			language: 'ru', 
			purifyHtml: false, 
			allowedFileTypes: 'image', 
			allowedFileExtensions: ['jpg', 'jpeg', 'png'],
			resizeImage: true,
			maxImageWidth: 1000,
			maxImageHeight: 1000,
			resizePreference: 'height',
			uploadExtraData: function() {
				return {
					artist: $("#select_artist").val(), 
					work: $("#select_work").val(), 
					book: $("#select_book").val(), 
					uniqid: $("#uniqid").val(), 
					comment: $("#set_comment").val(), 
					full: $("#set_full").val()
				};
			},
			fileActionSettings: {
				showUpload: false,
			}
		});
`
3. Message: Error while resizing the image.
4. Examples here: https://drive.google.com/open?id=0B6yztW7xkE35YVg5LXFLMzFNSE0

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.12.4 and 3.2.1
- bootstrap-fileinput version: 4.4.3

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
I am not able to reproduce this. Can you try with the plugin latest release? Will reopen the issue if you re-confirm.
