### ISSUE TITLE
Content-Type: image/png and content is send before Content-Disposition headers. 

### ISSUE THREAD

**Issue by deveilkwok** [kartik-v/bootstrap-fileinput#1055]
I switch from  v4.3.4 to the v 4.4.1 and 4.4.2,  I found that the Content-Disposition headers except the filename was moved after the image content.   This actually caused my remote cloud storage server reject the upload. Because  it can not locate the "key" form data field requires to create the key for this file. 

Is this an issue. Is there a way to control the content-type to put at the end?   

see below example:  >>>>>>>>>>>

__**-----------------------------283531828531154
Content-Disposition: form-data; name="file"; filename="f_static_060.png"
Content-Type: image/png

PNG

....................data for the picture

-----------------------------283531828531154
Content-Disposition: form-data; name="file_id"

0
-----------------------------283531828531154
Content-Disposition: form-data; name="key"

2/13/29/media/img/5b303404b366a7f0.png
-----------------------------283531828531154
Content-Disposition: form-data; name="policy"

eyJleHBpcmF0aW9uIjoiMjAxNy0wOC0yNFQwMzo0NDoxNVoiLCJjb25kaXRpb25zIjpbWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCw2MDAwMDAwMDBdLFsic3RhcnRzLXdpdGgiLCIka2V5IiwiMlwvMTNcLzI5XC9tZWRpYVwvaW1nXC8iXV19
-----------------------------283531828531154

............and the so on.**

end of example:  <<<<<<<<<<<

for v4.3.4 

The example form data for uploading an image is like this 

-----------------------------22513664424983
Content-Disposition: form-data; name="key"

2/13/29/media/img/a950ba2257688ef2.png
-----------------------------22513664424983
Content-Disposition: form-data; name="policy"

eyJleHBpcmF0aW9uIjoiMjAxNy0wOC0yNFQwMjozMjowMVoiLCJjb25kaXRpb25zIjpbWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCw2MDAwMDAwMDBdLFsic3RhcnRzLXdpdGgiLCIka2V5IiwiMlwvMTNcLzI5XC9tZWRpYVwvaW1nXC8iXV19
-----------------------------22513664424983
Content-Disposition: form-data; name="signature"

Psl0HikKkIq6k2JKFyfJbhb9ZPY=
-----------------------------22513664424983
Content-Disposition: form-data; name="OSSAccessKeyId"

LTAIaL4knStj8PeH
-----------------------------22513664424983
Content-Disposition: form-data; name="host"

http://vry360-pano.oss-cn-shanghai.aliyuncs.com
-----------------------------22513664424983
Content-Disposition: form-data; name="file_id"

0
-----------------------------22513664424983
Content-Disposition: form-data; name="file"; filename="VR_icon.png"
Content-Type: image/png

## Steps to reproduce the issue

1. Build the fileinput object as below. 
 $("#imgUpload_1").fileinput({
        language: 'zh',
        showUpload: false,
        showRemove: true,
        showCancel: false,
        showPreview: true,
        showCaption: false,
        allowedFileExtensions: ["jpg", "png"],
        maxImageWidth: images_width,
        maxImageHeight: images_height,
        maxFileSize: upload_maxsize,
        maxFileCount: 1,
        browseClass: "btn btn-primary",
        browseLabel: "choose files",
        browseIcon: "<i class=\"icon icon-file-o\"></i> ",
        uploadUrl: up_url,
        uploadAsync: true,
        textEncoding: "UTF-8",
        layoutTemplates: {
            actions: ''
        },
        uploadExtraData: buildExtraDataImg  

buildExtraDataImg  is a JS function returns the json {key:xxxx, host: xxxx, blabla.........} 

2.   Upload an image
3.   check the http post request. 

## Expected behavior and actual behavior

When I follow those steps, I see...

The content-type is putting at the very beginning. 

I was expecting...

the image content shall be put at the end. It is not backward compatible.  

## Environment

Browsers

- [x ] Google Chrome
- [ x] Mozilla Firefox

Operating System

- [X ] Windows

Libraries

- jQuery version: jquery-1.9.1.js
- bootstrap-fileinput version: 4.4.1 and 4.4.2

**Comment by kartik-v** [comment]
Check with the latest release of the plugin and confirm.
