### ISSUE TITLE
When I use laravel-admin which integrate bootstrap-fileinput I found browser not resoponse on Google but worked on safari

### ISSUE THREAD

**Issue by alexli0707** [kartik-v/bootstrap-fileinput#1057]
Thank you for this awesome project first , but  when I use laravel-admin which integrate bootstrap-fileinput I found browser not resoponse on Google but worked on safari.

**Comment by kartik-v** [comment]
Sorry I am not sure I can help here - but please check your configuration option on laravel. The plugin does work on Google Chrome as you can cross check in the [demo pages](http://plugins.krajee.com/file-input/demo)
