### ISSUE TITLE
a point on document

### ISSUE THREAD

**Issue by hooman-pro** [kartik-v/bootstrap-fileinput#1060]
Hi thank you for your good extentions .
and sorry for my english.
when i try to have custom template by looking in : 
http://plugins.krajee.com/file-input#option-previewtemplates
when set this line:
`
image: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}">\n' +
        '   <div class="kv-file-content">' +
        '       <img src="{data}" class="kv-preview-data file-preview-image" title="{caption}" alt="{caption}" ' + STYLE_SETTING + '>\n' +
        '   </div>\n' +
        '   {footer}\n' +
        '</div>\n',
`
and set:
`
'pluginEvents' => [
                            "filebatchselected" => "function(event, files) {
                                                $('#file_upload').fileinput('upload');
                                            }",
`
it dont work well

so some hours i check all thing at last found that : "kv-preview-thumb" class should use to change id of preview after upload. that's better to change in document. like this: (set "kv-preview-thumb" class in document or adding a note.)
`image: '<div class="file-preview-frame kv-preview-thumb" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}">\n' +
        '   <div class="kv-file-content">' +
        '       <img src="{data}" class="kv-preview-data file-preview-image" title="{caption}" alt="{caption}" ' + STYLE_SETTING + '>\n' +
        '   </div>\n' +
        '   {footer}\n' +
        '</div>\n',
`

**Comment by kartik-v** [comment]
You do not need this class `kv-preview-thumb` to be added in the templates. The `file-preview-frame` is mandatory.

**Comment by kartik-v** [comment]
You do not need the class `kv-preview-thumb` to be added in the templates (that is auto managed by the plugin). The `file-preview-frame` is more mandatory for the file preview thumbnails. These are covered in the [documentation here](http://plugins.krajee.com/file-input#option-previewtemplates). In case you have a old document cache on your browser you may want to clear the browser cache and refresh the browser (or hard refresh e.g. SHIFT-F5 on Chrome on windows).
