### ISSUE TITLE
Ajax Call not happening

### ISSUE THREAD

**Issue by hitesh279** [kartik-v/bootstrap-fileinput#1061]
Hi I am trying for an ajax call and I am getting 400 error code.Below is my code. But its not at all calling service when i click submit button. 

 allowedFileTypes: ['xlsx'],
		        msgInvalidFileType: 'Invalid file "{name}". You can only select the previously downloaded file "<strong>'+vm.newFileName+'</strong>".',
		        //allowedFileExtensions: ["xlsm"],
		        browseIcon: '<i class="icon-file-plus"></i>',
		        uploadIcon: '<i class="icon-file-upload2"></i>',
		        uploadAsync : false,
		        showClose : false,
		        showUpload: true,
		        uploadClass: 'btn btn-success',
		        removeClass: 'btn btn-danger',
		        browseOnZoneClick: true,
		        autoReplace: true,
		        maxFileCount : 1,
		        validateInitialCount : true,
		        uploadUrl : someURL,
		        uploadExtraData: _.pick(vm.activeKeycat,
           ['abbr','attributes','keycatNum','mg','name','recap','totalDollarSales','totalExceptions','workgroup']),
		        removeIcon: '<i class="icon-cross3"></i>',
		        layoutTemplates: {
		            icon: '<i class="icon-file-check"></i>'
		        },
		        initialCaption: "No file selected"

**Comment by kartik-v** [comment]
You may need to test your code (both client/server) and if any javascript errors on the page. Cannot reproduce your use case. Ensure you have not set a CSS class of `file` on your input as mentioned in docs when initializing separately via javascript. Share a JS fiddle to reproduce if your issue persists and will reopen.
