### ISSUE TITLE
uploadExtraData cant return data-nnn from the input field

### ISSUE THREAD

**Issue by mikecastrodemaria** [kartik-v/bootstrap-fileinput#1067]
I try to get the data-filetype, from the input type file used to send the file to the server.

I set my input like :
```
<label class="control-label">My file</label>
<input id="filetype-3" name="filetype_3" type="file" class="file" data-filetype="3">
```
and I try use uploadExtraData (doc description) like this :

```
uploadExtraData: function() {
    return {
        userid: $("#id").val(),
        filetype: $(this).closest("input[name='t']").data('filetype'),
        tfile: 'ufile'
    };
}

```

But when the upload button is fired, $(this).closest("input[name='t']").data('filetype') is always, and definitely undefined.

Any idea ?

**Comment by beskyey** [comment]
I set it like this ,and It works
```
uploadExtraData:function(){
            return {username:$("#message1").attr("value")}
            }
```

**Comment by kartik-v** [comment]
I am not clear what is `$(this).closest("input[name='t']")`

what is the `$(this)` here... maybe it is returning the file input element depending on how you are calling it... or it will not be a valid DOM element ... not sure if that is correct.. debug your code to check what is the DOM traversal you are doing?

Am closing this ...  as this is programming related... you can post help for programming in the comments/discussions forums.
