### ISSUE TITLE
I have issue with AJAX upload mode, please help

### ISSUE THREAD

**Issue by giangvy1011** [kartik-v/bootstrap-fileinput#107]
HI, 

I tried ajax mode to upload file as per your suggestion but when i click upload button i got this error from firebug:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Because I am not an expert so please tell me in simple way to fix this problem? I have configured my uploadUrl to a php file which process upload and save files's path to mysql. I also set multiple to true and name attribute is file[]. Is there something else that i have missed?

Many thanks,
Ryan

**Comment by kartik-v** [comment]
Please read documentation. You need to send a valid JSON response from your server upload action code (even if you do not have any server data to send for advanced cases, it at least must be an empty json object e.g. `{}`).

Unfortunately will not have time to support for your individual coding case.

**Comment by giangvy1011** [comment]
HI please help me with json reponse. I have spent so much time to integrate into my existing form and it am stuck at this stage. I am just a new php learner. Hope you can help me out. Many thanks in advance

**Comment by andinieves151720** [comment]
Good day!
I just wonder if I can send my post to my php script so i can control where the uploads it should go/store. Thanks in advance!

**Comment by kartik-v** [comment]
Yes that's correct.

**Comment by andinieves151720** [comment]
Ok I got it, Thanks your input was awesome! It made my programming life more easier thanks a lot! :+1: :+1:  :+1:  :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by andinieves151720** [comment]
JSON is only for the output of ajax query for validating uploads. :)
