### ISSUE TITLE
Auto detect small screen width and auto style/auto fit preview thumbnails

### ISSUE THREAD

**Issue by matmiranda** [kartik-v/bootstrap-fileinput#1071]
Following is an example of the scenario:  http://plugins.krajee.com/file-input-ajax-demo/3

For iPhone 5 : https://s26.postimg.org/bpjwqm5p5/Inkedchrome_2017-09-04_12-56-50_LI.jpg

For Galaxy s5: https://s26.postimg.org/8itykqamx/Inkedchrome_2017-09-04_13-00-11_LI.jpg

Responsive does not work, Any solution ?

**Comment by kartik-v** [comment]
Will need some CSS optimizations... will get back on this when I get some time...

**Comment by kartik-v** [comment]
Have updated the title. New property `previewSmallSettings` will be added to configure the content style settings for small screen devices.

**Comment by kartik-v** [comment]
Resolved via [updates to release v4.4.4](https://github.com/kartik-v/bootstrap-fileinput/commit/05c2ca1631ccec305919af5bf02a5692dc960e3e).
