### ISSUE TITLE
problem loading PDFs with initialPreview

### ISSUE THREAD

**Issue by petargeorgiev123** [kartik-v/bootstrap-fileinput#1074]
I have multiples fileinputs in a page and populate the initialPreview on the load passing the files. But for PDF I am getting the initialPreview trying to load the PDF into <img tag
What can be the problem?
When selecting a PDF manually is previewing the PDF well but not in the initialPreview.

$(".fileUpload :input").each(function(){
var inputElement = $( this );
inputElement.fileinput({
showUpload: false,
showCaption: false,
fileType: "any",
previewFileIcon: "",
initialPreviewAsData: true,
initialPreview: [
inputElement.parent().parent().attr('data-url') // Here is the pdf. For example: ../../public/images/6daebfaa533798aabc7bbd410361dd1a.pdf
],
autoReplace: true,
maxFileCount: 1,
overwriteInitial: true,
});
});

**Comment by leo-ridgewood** [comment]
I have the same problem.

It seems to be ignoring the Internet Media Type contained in the Content-Type response header when loading the preview files and instead using the image template for everything. In contrast, when files are uploaded the Media Type is correctly used to determine the template.

Even if I prefetch each file to obtain the Media Type and set the corresponding filetype property in initialPreviewConfig the image template is still used. The only way I can get it to work is to set the corresponding intialPreviewConfig "type" field to the required template. Both pre-fetching the file and doing the mapping is rather tricky.

I feel I must be missing something as surely the most common use of preview would be to show arbitrary files previously uploaded?

**Comment by kartik-v** [comment]
For each file element you need to set the `type` property within `initialPreviewConfig` to automatically identify your file rendering template... check the [preview management demos](http://plugins.krajee.com/file-preview-management-demo)... for example 
```js
initialPreview: {
   'http://pdf-link',
   'http://image-link',
   'http://video-link',
},
initialPreviewConfig: {
    {type: 'pdf', 'caption': 'PDF File', size: 1000},
    {type: 'image', 'caption': 'Image File', size: 1000},
    {type: 'video', 'caption': 'Video File', size: 1000},
}
```

**Comment by leo-ridgewood** [comment]
kariik-v, I don't understand your use of the word "automatically" here.

In your example "type" is manually set to a hardcoded value based on special knowledge of what the hardcoded links were pointing to. I am trying to display a preview of arbitrary previously uploaded files.

**Comment by leo-ridgewood** [comment]
Here is what I have done to allow the preview of previously upload files. Note I have manually edited out the non-preview stuff, so it might not quite work, and also that I am not a javascript programmer, but hopefully you get the idea:

- Ajax load each image and collect the media type
- Once all media type info has been collected initialise fileinput using a hacky calls to internal methods to map media type to template name (aka type, category)

Hopefully I have missed something and there is a better way?

```
var downloadUriBase = "/Download?AttachmentKey=";

// Get the attachment keys

var $attachmentKeys = $("#AttachmentKeys");
var attachmentKeysStr = $attachmentKeys.val();
var attachmentKeys = attachmentKeysStr == "" ? [] : attachmentKeysStr.split(",");

// Get the media types by loading each attachment

var attachmentMediaTypes = {};
var ajaxes = attachmentKeys.map(function (key) {
return $.ajax({
    type: 'GET',
        url: downloadUriBase + key
    })
    .done(function (data, textStatus, jqXhr) {
        attachmentMediaTypes[key] = jqXhr.getResponseHeader("content-type");
    });
});

// Display them in the preview. Hopefully they will be in the cache

$('body').fileinput('_initTemplateDefaults'); // Required for _parseFileType to work.
$.when.apply($, ajaxes).done(function () {
    $files
        .fileinput('destroy')
        .fileinput({
            initialPreviewAsData: true,
            initialPreview: attachmentKeys.map(function (key) {
                return downloadUriBase + key;
        }),
        initialPreviewConfig: attachmentKeys.map(function (key) {
            return {
                type: $('body').fileinput('_parseFileType', attachmentMediaTypes[key], ''),
                filetype: attachmentMediaTypes[key]
           }
        })
    ;
})
```

**Comment by kartik-v** [comment]
> In your example "type" is manually set to a hardcoded value based on special knowledge of what the hardcoded links were pointing to. I am trying to display a preview of arbitrary previously uploaded files.

Since these files are already uploaded and on a server, you should be able to detect the file types via your server code, and set the right `type` automatically... for example if the file's mimetype is `application/pdf` - set the `type` to `pdf`.
