### ISSUE TITLE
How do I show the amount of files already saved (without preview) ?

### ISSUE THREAD

**Issue by matmiranda** [kartik-v/bootstrap-fileinput#1088]
In the documentation I do not see the option to disable preview.

Example: https://s26.postimg.org/s6olxo35l/Inkedchrome_2017-09-24_13-20-59_LI.jpg

How can I make it look like the image above (with button remove)?

**Comment by kartik-v** [comment]
You may want to go through the documentation and read through all plugin options.

You can set [showPreview](http://plugins.krajee.com/file-input#option-showpreview) property to `false`.

There are a couple of examples as well 
- [advanced example # 10](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-10) shows a file input without preview
- [basic example # 9](http://plugins.krajee.com/file-basic-usage-demo#basic-example-9) shows a file input rendered inside the modal dialog with [showPreview](http://plugins.krajee.com/file-input#option-showpreview) property set to `false`

**Comment by matmiranda** [comment]
Let's say she has saved image. I need to show the filename in the input and remove button. Something like:
https://s26.postimg.org/j83lhr4l5/Inked_Inkedchrome_2017-09-24_13-20-59_LI.jpg

Now since it has no image saved in the database, show something like: [advanced example # 10](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-10)

Here my code:

```
    $("#input-001").fileinput({
        uploadUrl: "/Files/_AtivConsu_Aceito_Upload_ImageUpload",
        uploadAsync: true,
        showPreview: false,
        allowedFileExtensions: ['jpg', 'png'],
        maxFileCount: 4,
        initialCaption: "1 file selected",
        elErrorContainer: '#kv-error-1'
    }).on('filebatchpreupload', function (event, data, id, index) {
        $('#kv-success-1').html('<h4>Upload Status</h4><ul></ul>').hide();
    }).on('fileuploaded', function(event, data, id, index) {
        var fname = data.files[index].name,
            out = '<li>' + 'Uploaded file # ' + (index + 1) + ' - ' + fname + ' successfully.' + '</li>';
        $('#kv-success-1 ul').append(out);
        $('#kv-success-1').fadeIn('slow');
        });
```
I want to show the input something like: "1 file selected" with remove button, after loading new page.

**Comment by matmiranda** [comment]
@kartik-v  thank you.
