### ISSUE TITLE
bootstrap 4 how to set instead of glyphicon 

### ISSUE THREAD

**Issue by maungyehtunzaw** [kartik-v/bootstrap-fileinput#1089]
in boostrap 4 glyphicon don't not support. so there use in glyphicon don't not appear icon. how to use with fontawesome these class

**Comment by kartik-v** [comment]
Read the [documentation](http://plugins.krajee.com/file-input) and [demo examples on the file input plugin page](http://plugins.krajee.com/file-input/demo) before posting issues. 

Your answer on how to use with Bootstrap 4.x is addressed in the [plugin usage section](http://plugins.krajee.com/file-input#usage).

- You can either load the glyphicons CSS separately with Bootstrap 4.x
- OR you can use the font awesome theme as described here in the [font awesome theme demo](http://plugins.krajee.com/file-theme-demo#theme-fa)
