### ISSUE TITLE
Please show me how to write a valid json response from my php upload script

### ISSUE THREAD

**Issue by giangvy1011** [kartik-v/bootstrap-fileinput#109]
HI,

I am just a new php learner and i would like to integrate this plugins to my existing form. I have written my php script which processes file upload and set it up in urlUpload. However, when i click upload button, it returns invalid jason response. I don't know how to write a valid json response in my php code because this is out of my scope at this monent. Please help me by telling how to write a simple empty object in json response to make it work?

Here is my php code:

    if(isset($_POST["submit"])){
    require("../configs/dbconnect.php");
    /*Form variable   */
    $owner = mysql_real_escape_string($_POST["owner"]);
    $title = mysql_real_escape_string($_POST["title"]);
    $description = mysql_real_escape_string($_POST["description"]);
    $city = mysql_real_escape_string($_POST["city"]);
    $brand = mysql_real_escape_string($_POST["brand"]);
    $marketprice = mysql_real_escape_string($_POST["marketprice"]);
    $price = mysql_real_escape_string($_POST["price"]);
    $phone = mysql_real_escape_string($_POST["phone"]);
    /*** the upload directory ***/
    $upload_dir= 'uploads';

    /*** numver of files to upload ***/
    $num_uploads = 5;

    /*** maximum filesize allowed in bytes ***/
    $max_file_size  = 5000000;
 
    /*** the maximum filesize from php.ini ***/
    $ini_max = str_replace('M', '', ini_get('upload_max_filesize'));
    $upload_max = $ini_max * 1024;

    /*** a message for users ***/
    $msg = 'Please select files for uploading';

    /*** an array to hold messages ***/
    $messages = array();
	$err=array();

    /*** check if a file has been submitted ***/
    if(isset($_FILES['file']['tmp_name']))
    {
        /** loop through the array of files ***/
        for($i=0; $i < count($_FILES['file']['tmp_name']);$i++)
        {
            // check if there is a file in the array
            if(!is_uploaded_file($_FILES['file']['tmp_name'][$i]))
            {
                $messages[] = 'No file uploaded';
            }
            /*** check if the file is less then the max php.ini size ***/
            //elseif($_FILES['image']['size'][$i] > $upload_max)
            //{
            //    $messages[] = "File size exceeds $upload_max php.ini limit";
            //}
            // check the file is less than the maximum file size
            elseif($_FILES['file']['size'][$i] > $max_file_size)
            {
                $messages[] = "File size exceeds $max_file_size limit";
            }
            else
            {
				//$temp = explode(".", $_FILES["file"]["name"][$i]);
				//$extension = end($temp);
				//$name[$i] = sha1(microtime()) . "." . $extension;
				$name[$i]=$_FILES["file"]["name"][$i];
                // copy the file to the specified dir 
                if(move_uploaded_file($_FILES['file']['tmp_name'][$i],$upload_dir.'/'.$name[$i]))
                {
                    /*** give praise and thanks to the php gods ***/
                    $messages[] = $name[$i].' uploaded';
					$image_path[$i]=$upload_dir.'/'.$name[$i];
                }
                else
                {
                    /*** an error message ***/
                    $messages[] = 'Uploading '.$name[$i].' Failed';
                }
            }
        }
    }
	$image_path_string=serialize($image_path);
	$sql = "INSERT INTO memberpost(owner, title, description, city, brand, marketprice, price, phone, image) VALUES ('$owner', '$title','$description','$city','$brand','$marketprice','$price','$phone', '" . $image_path_string . "')";
	$result = mysql_query($sql) or die ("Could not insert data into DB: " . mysql_error());
	 if(sizeof($messages) != 0)
    {
        foreach($messages as $err)
        {
            echo $err.'<br />';
        }
    }
    }

Many thanks

**Comment by Blackman21** [comment]
Hi,

Try this http://php.net/manual/en/function.json-encode.php article.

Br.
