### ISSUE TITLE
event fileuploaded  call getFileStack  result wrong

### ISSUE THREAD

**Issue by newcloud** [kartik-v/bootstrap-fileinput#1092]
before
-----------------------------------------
var filestack = $("#img_groups").fileinput('getFileStack');
var length = filestack.length;
console.log(length); # print 4 is ok

when
------------------------------------------

.on('fileremoved', function(event, id, index) {
	var filestack = $("#img_groups").fileinput('getFileStack');
	var length = filestack.length;
	console.log(length); # print 3 is ok
})

or when
------------------------------------------
.on('fileuploaded', function(event, previewId) {
	var filestack = $("#img_groups").fileinput('getFileStack');
	var length = filestack.length;
	console.log(length); # print 4 is wrong
})

**Comment by kartik-v** [comment]
Not sure of the exact issue. But you may check with updated release v5.0 and retry as there are various enhancements to file management and resumable uploads. 

If there is an issue that still persists please share a JS fiddle or code to reproduce and will reopen this.
