### ISSUE TITLE
Add support for previewing Office file formats

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#1097]
Uses google docs viewer. Supported only for initial preview content and for office doc content available as a public web accessible URL link.

New preview templates available as `office`.

**Comment by kartik-v** [comment]
[Demo example available here](http://plugins.krajee.com/file-preview-management-demo#preview-data) showing preview of various office file formats.

**Comment by mohannetha** [comment]
Hi Karthik,
Preview is not working for excel and word files after browsing file
can you share the configuration for both.

**Comment by kartik-v** [comment]
Excel,  word and Ms office doc preview is available and supported only for files uploaded to server and which you set via initialPreview.. You need to program and code your app accordingly. Read docs and examples to understand what is supported when.

**Comment by camilocalderont** [comment]
Hi Kartik-v,

Preview is not working for excel and word files after browsing file,  even in your demo [http://plugins.krajee.com/file-preview-management-demo#preview-data](url). I have used 5.0.4 versión.

Have you another method for show office files as Google Docs ?

**Comment by kartik-v** [comment]
Preview of office files is supported only for files accessible on internet which means they must have been uploaded and set via initialPreview. To achieve your use case you therefore need to trigger upload immediately after file browse... 
And return the uploaded data as iniitialPreview... Check ajax demos for one use case like this

**Comment by camilocalderont** [comment]
Thanks for your response, I meant that the plugin did not show the preview of office files when they were already stored on the server.

For solve I use type parameter in initialPreviewConfig to show this files with Google Docs:

`initialPreviewConfig: [
	{
		caption: "CHECK MIGRACION.ods",
		downloadUrl: "public/storage/proyectos/adjuntos/5/1/CHECK MIGRACION.ods",
		filename: "CHECK MIGRACION.ods",
		key: 1,
		size: 6052,
		type: "gdocs",
		url: "public/proyectos/formulacion/eliminarAdjuntosPasoProyecto",
		width: "120px"
	}
]`

**Comment by kartik-v** [comment]
preview of office files is done in the plugin via Microsoft Office Online View Library... 

[Check the demo where it does work fine](http://plugins.krajee.com/file-preview-management-demo#preview-data) - you may need to check if your network is blocking OFFICE viewers...

Google Docs can also be used... but you need to configure the plugin accordingly... by configuring and overriding the `office` and `gdocs` settings in [fileTypeSettings](http://plugins.krajee.com/file-input/plugin-options#fileTypeSettings)
