### ISSUE TITLE
is it possible to select multiple file in form submit?

### ISSUE THREAD

**Issue by ljdhameliya** [kartik-v/bootstrap-fileinput#1098]
i have used file input as image upload and save on form submit.
when using file input if select first time 3 file and then i need to append one more then it overwrite and in preview display 1. but in ajax upload scenario we can append new file is possible.
so my question is it is possible to append file after selected file in form submit mode?

**Comment by kartik-v** [comment]
Please follow the [guidelines](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/ISSUE_TEMPLATE.md) before creating issues in this repo. 

You should read [the documentation](http://plugins.krajee.com/file-input)... your query is addressed in the [plugin usage modes](http://plugins.krajee.com/file-input#usage-modes) as to what is possible in which mode and what is NOT Possible.

**Comment by teoSalvetti** [comment]
ok, it is not porssible using multiple file within a form.. But I also think it is very useful it, for example, if I have to attach 2 files to an entity that I'm creating, if I use a form I create the entity (save it on db) and also attach the files. If I use the ajax instead I have to create and save the entity and the open another page to upload and attach the 2 files. 

Is it not correct?

So, is it possible in somehow use the ajax upload with a form??
If not, why not develop a multiple version for the form?
