### ISSUE TITLE
Is there a way to have upload happen automatically after file is chosen?

### ISSUE THREAD

**Issue by ssuess** [kartik-v/bootstrap-fileinput#11]
I have a jquery script which runs and works fine onsubmit when the upload button is clicked, (and runs an ajaxsubmit process), but ideally I would like it to automatically submit the form once the file is chosen, doing away with the upload click completely. Is there an event that will tell me when a file has been chosen?

Thanks!

**Comment by fnicollet** [comment]
Hello @kartik-v and thanks for the great plugin,

I have a similar question but unfortunately, the solution you gave won't work in my case.

Basically, when I submit the form (with text inputs and the upload component), I won't receive the file references unless the user has clicked the "Upload" button in the preview before, which is understandable.

I would like that on "change", to manually trigger the "Upload" button, I don't want to submit the whole form when the user picks an image. I have looked at the documentation and the github issues and couldn't find something similar to what I want to do. Basically, on input "change", the file would be submitted to the uploadUrl.

Can you help please?

Thanks!
Fabien

**Comment by fnicollet** [comment]
Scrath that, the files are actually also sent if the user doesn't press the Upload button when the surrounding form is submitted (probably because you use standard file inputs)

So no question for me, this plugin is awesome :)

Fabien
