### ISSUE TITLE
Standard implementation not working. No file available for upload, on every attempt

### ISSUE THREAD

**Issue by mstahlmann** [kartik-v/bootstrap-fileinput#1101]
Here is my javascript:
$(".file-input-ajax").fileinput({
        uploadUrl: "./photo/photohandler.php", // server upload action
        uploadAsync: true,
        maxFileCount: 5,
        initialPreview: [],
        fileActionSettings: {
            removeIcon: '<i class="icon-bin"></i>',
            removeClass: 'btn btn-link btn-xs btn-icon',
            uploadIcon: '<i class="icon-upload"></i>',
            uploadClass: 'btn btn-link btn-xs btn-icon',
            zoomIcon: '<i class="icon-zoomin3"></i>',
            zoomClass: 'btn btn-link btn-xs btn-icon',
            indicatorNew: '<i class="icon-file-plus text-slate"></i>',
            indicatorSuccess: '<i class="icon-checkmark3 file-icon-large text-success"></i>',
            indicatorError: '<i class="icon-cross2 text-danger"></i>',
            indicatorLoading: '<i class="icon-spinner2 spinner text-muted"></i>',
        },
        layoutTemplates: {
            icon: '<i class="icon-file-check"></i>',
            modal: modalTemplate
        },
        initialCaption: "No file selected",
        previewZoomButtonClasses: previewZoomButtonClasses,
        previewZoomButtonIcons: previewZoomButtonIcons
    });
Attached to the following html:
<div class="form-group">
								<label class="col-lg-2 control-label text-semibold">AJAX upload:</label>
								<div class="col-lg-10">
									<input type="file" class="file-input-ajax" multiple="multiple">
									<span class="help-block">This scenario uses asynchronous/parallel uploads. Uploading itself is turned off in live preview.</span>
								</div>
							</div>

Each time I attempt to fire the plugin it says no file available for upload. My php handler is accessed, I know from the log, but it also has an empty file object. Any assistance would be greatly appreciated.

**Comment by kartik-v** [comment]
Can you share an example or JS fiddle to reproduce what you are experiencing?

**Comment by kartik-v** [comment]
Will reopen this issue once you share an example to reproduce.
