### ISSUE TITLE
How to remove thumbnail for non uploaded files? (Non Ajax)

### ISSUE THREAD

**Issue by Asinox** [kartik-v/bootstrap-fileinput#1112]
Hello, i love this plugin, but there is something that i can't figure out.

How i can add the delete button to thumbnail for non uploaded files?, i want to delete files that i don't want to upload without remove all files that are ready to upload.

The delete button is just present in files that are loaded from server.

There is a way to archieve this?

Thank you!

**Comment by kartik-v** [comment]
Please read the documentation and [the usage modes possibility](http://plugins.krajee.com/file-input#modes-compared).

It is clearly mentioned what is possible in Ajax and non Ajax (simple form) submission modes.

**Comment by Asinox** [comment]
Thanks @kartik-v for your reply, i did it before come here (read the documentation) , and i really want the ability of remove a thumbnail/file before process the upload.  I wonder why is not possible...well thanks for you amazing plugin.

**Comment by kartik-v** [comment]
> and i really want the ability of remove a thumbnail/file before process the upload.  I wonder why is not possible..

what you are asking is not supported by native HTML specifications or by browsers... you cannot edit files selected in a native file input via javascript or external code.

**Comment by kartik-v** [comment]
> and i really want the ability of remove a thumbnail/file before process the upload.  I wonder why is not possible..

what you are asking is not supported by native HTML specifications or by browsers... you cannot edit files selected in a native file input via javascript or external code.

Plugin mimcs whatever HTML5 support is available for native file inputs in the non-ajax mode.
