### ISSUE TITLE
Zoom preview not working for file control in modal 

### ISSUE THREAD

**Issue by nidsb** [kartik-v/bootstrap-fileinput#1114]

**Comment by nidsb** [comment]
I created form with file control in modal with bootstrap-fileinput plugin.When I clicked edit from data table modal display with selected file and preview icon.But on click of that icon nothing happen,It doesn't show zoom image modal

**Comment by kartik-v** [comment]
You need to write your JS code to initialize the plugin correctly via javascript (e.g. after modal show event for example). Also check the [first note in the usage section of the docs](http://plugins.krajee.com/file-input#usage)... you should not add CSS class `file` if initializing plugin via JS.
