### ISSUE TITLE
IE11 got stuck(Bootstrap File Input Demo)

### ISSUE THREAD

**Issue by hczheng** [kartik-v/bootstrap-fileinput#1120]
HI,I tried the demo:http://plugins.krajee.com/file-input-ajax-demo/8#top ,I only uploaded 5 pictures and the browser got stuck. After that I waited for a long time for the browser to recover (**IE 11 Windows 10**) .
I wonder if the plugins support IE11.

**Comment by kartik-v** [comment]
Unfortunately cannot reproduce anything specific to IE11 as everything seems to work fine with the link above on tests. 

On a generic note, for performance issues, you may need to check your client specifications, the browser settings, browser and local memory settings (it also depends on the volume and sizes of file contents being parsed in memory specific to your client - so you may need to design your app accordingly as per your client browser - e.g. hiding preview if not needed and controlling size and number of files selected etc.).
