### ISSUE TITLE
Close button on error message...

### ISSUE THREAD

**Issue by luX0r-reload** [kartik-v/bootstrap-fileinput#1123]
- [x] Google Chrome
- [x] Mozilla Firefox

Operating System
- [x] Linux

Libraries

- jQuery version: 
- bootstrap-fileinput version: 4.4.6

## Isolating the problem
Hi, thanks for your plugin.
I discovered a little bug. When I set browseOnZoneClick on true and an error upload message appears (json response), if I click on close button of the error message this disappears but a browse file window appears too.

Thanks in advance for support.

L.

**Comment by luX0r-reload** [comment]
Hi, this is for sure a bug because I found this problem appears in your demo too:

http://plugins.krajee.com/file-input-ajax-demo/12

Thanks in advance for the fix :)

**Comment by michaelashore** [comment]
Hello, I am still seeing this issue after updating to 4.5.2. I am seeing it on an AJAX file upload in the same scenario as @luX0r-reload mentions:

> To reproduce, select six files to upload (maxFileCount is five)... an error appears. Try to close error message and a browse files window is opened.

 Is the fix still WIP?

Many thanks for the great plugin.

**Comment by razorsharpshady** [comment]
I'm also facing this issue this in the ajax upload, on 5.1.3 version of this extension.

**Comment by kartik-v** [comment]
Fixed via above commit.
