### ISSUE TITLE
Can't initialize plugin in ajax callback

### ISSUE THREAD

**Issue by usernameisalreadytaken1236428934** [kartik-v/bootstrap-fileinput#1124]
## Steps to reproduce the issue

1. create minimal page with single input

```html
<input id="original" name="original[]" type="file" class="file" multiple required>
<script>
function init(){
	$("#original").fileinput({
		overwriteInitial: false,
		initialPreview: [
			"http://kartik-v.github.io/bootstrap-fileinput-samples/samples/Desert.jpg",
			"http://kartik-v.github.io/bootstrap-fileinput-samples/samples/Lighthouse.jpg"
		],
		initialPreviewAsData: true
	});
}
$.get("https://some-local-url",function(response){
	init();
});
</script>`
```
2. if you call init() in ajax callback input not fully inited(no initial files)
3. if call init() without ajax - works fine

I was expecting that plugin will have the same behavior, no matter where to initialize it

## Environment

Browsers

-  Google Chrome

Operating System

-  Windows

Libraries

- jQuery version: jquery-3.2.1.min.js / jquery-2.2.4.min.js
- bootstrap-fileinput version: v4.4.6
- bootstrap version: 3.3.7

## Isolating the problem

https://jsbin.com/qeqakekuwe/edit?html,output
you can try it here, just comment/uncomment ajax rquest

**Comment by kartik-v** [comment]
The issue is that you are adding the CSS class `file` to your input.  You should not be doing that when initializing plugin via Javascript ([read the first note in the usage section of the docs](http://plugins.krajee.com/file-input#usage)).
