### ISSUE TITLE
required=true and showPreview=false means no error displayed

### ISSUE THREAD

**Issue by kevindonahue** [kartik-v/bootstrap-fileinput#1126]
If I use the option "required" set to true, but also have option "showPreview" set to false, the required error message is never displayed.

**Comment by kartik-v** [comment]
By default error container is displayed within preview. So if you set `showPreview` to `false` you are killing both (preview and error display) by default. So its obvious why error messages are not shown.

If you are hiding the preview, but selectively want to show only errors - then set your own error container identifier within [elErrorContainer](http://plugins.krajee.com/file-input/plugin-options#elErrorContainer).

An example of how to do it is described in the [avatar upload demo](http://plugins.krajee.com/file-avatar-upload-demo#avatar-upload-1).
