### ISSUE TITLE
 Sorting / reorder not working on Chrome

### ISSUE THREAD

**Issue by HBurakKaradag** [kartik-v/bootstrap-fileinput#1128]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. http://plugins.krajee.com/file-preview-management-demo  not working on chrome.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
       62.0.3202.94
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by a6ka** [comment]
OS: Ubuntu 16.04
Chrome version:
- 61.0.3163.79, (64 bit) - Working
- 62.0.3202.75, (64 bit) - Not working

**Comment by morawskim** [comment]
Looks like related issue https://github.com/kartik-v/yii2-widget-fileinput/issues/123

**Comment by mickremy** [comment]
Hi guys, this problem seems to be on chrom v63, can someone confirm this ?

**Comment by morawskim** [comment]
I don't have any problems (currently) with sorting in chrome 63.0.3239.108. I tested http://plugins.krajee.com/file-preview-management-demo

**Comment by a6ka** [comment]
Sorting works correctly now. Chome version: 63.0.3239.132
