### ISSUE TITLE
Issue with adding and uploading file from clipboard

### ISSUE THREAD

**Issue by alexprey** [kartik-v/bootstrap-fileinput#1130]
I try to implement the way for users, when his copy-paste some file into textblock and this file should be attached to file uploader automatically. By documentation I found method `addToStack` but it's not work by proper way - it just upload file to server and don't update the UI of file uploader. I spent many time to figure out how it can be resolved by this lbrary and found the next possible _hack_

```
// Hack for upload file via Fileinput control
$fileControl.fileinput('_readFiles', [fileToUpload]);
var instance = $fileControl.data('fileinput');
instance.$container.find(".file-drop-zone ." + instance.dropZoneTitleClass).remove();
```

This approach is not good way, and it will be good if new method to library was added like a `insertFile` that can add this file to control and properly update UI of this control.

Thanks.
---------
Regards,
Alexey.

**Comment by kartik-v** [comment]
Note that browsers do not allow client script & javascript to read files on client programmatically (except if you use a file input or HTML5 drag & drop).

If you have such an approach and have an array of file blob objects that you wish to pass into the plugin and update the preview, then you can use the [`readFiles` plugin method](http://plugins.krajee.com/file-input/plugin-methods#readFiles).
