### ISSUE TITLE
createObjectUrl function missing

### ISSUE THREAD

**Issue by mauriziocingolani** [kartik-v/bootstrap-fileinput#1132]
I ran a Composer update, and after executing this update:

 - Updating kartik-v/bootstrap-fileinput dev-master (0014931 => d33b74d):  Checking out d33b74d6f5

I can no longer load a file (with both Select and D&D) in the upload field. I get this error:

Failed to execute 'createObjectURL' on 'URL'

on line 3654 of fileinput.js.

**Comment by kartik-v** [comment]
Cannot reproduce this. Please check if you are not having other javascript errors on your page AND you are not running outdated/stale assets. 

If you can reproduce this - please share a JS Fiddle to help check.

**Comment by mauriziocingolani** [comment]
I downgraded to #6dc3488 and it works again.
I'll try to set up a fiddle for you to check it out

**Comment by mauriziocingolani** [comment]
I set up this test page for you:

http://education.sidagroup.com/site/test

This is my composer.json:

```
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "2.0.13",
        "yiisoft/yii2-bootstrap": "2.0.*",
        "kartik-v/yii2-mpdf": "*",
        "kartik-v/yii2-social": "*",
        "kartik-v/yii2-widget-datepicker": "*",
        "kartik-v/yii2-widget-fileinput": "*",
        "kartik-v/yii2-widget-select2": "*",
        "kartik-v/yii2-widget-timepicker": "*"
    },
```

The extra line  "kartik-v/bootstrap-fileinput":"dev-master#6dc3488" fixes the problem.

**Comment by kartik-v** [comment]
Ok I will provide a fix to this shortly...

**Comment by kartik-v** [comment]
You can check now.

**Comment by mauriziocingolani** [comment]
Ok. The test page and everything else works just fine.
Thank you, awesome job.
Over and out
