### ISSUE TITLE
previewId is "undefined" every time

### ISSUE THREAD

**Issue by ak868308** [kartik-v/bootstrap-fileinput#1135]
Hi All
I am using batchfile upload event. Files are uploading very nice but whenever I goes to get the previewId for the current uploaded file it always says me it is undefine 
Here my plugin events

`'filebatchselected' => 'function(event, file){ console.log(file); if(file.length > 0) { $(\'#album-attachments\').fileinput(\'upload\')}}',            
            'filebatchuploadsuccess' => ' function(event, data, previewId, index) { 
                console.log(previewId);
                var res = data.response.initialPreviewConfig;
                $.each(res,function(i,v){
                    //$(previewId).find("#my-radio").val(res.key);
                });                
                 window.setTimeout(function() { $(".kv-upload-progress").addClass("hide");}, 2000);
                }'`

Actual Here I am uploading the images via AJAX in myproject/tmp directory because I have the description for each image as well as radio button to select the default image after successfull form submission I want to store that description and default status into database against each image. while I already stored the location and filename, size etc into session for further use.

Thanks

**Comment by kartik-v** [comment]
There will be no `previewId` or `index` available for events in batch uploads. Its only if you upload each file individually via the thumbnail upload button (i.e. `fileuploaded` event). You may cross check the docs (which was updated).

**Comment by a564941464** [comment]
let ffs = $(".images_upload").fileinput('getFrames');
             ffs.forEach(function(item){
                 $(item).find(".kv-file-upload").click();
                 console.log($(item).find(".kv-file-upload").attr("title"));
             });
triger the click event of the upload button for each thumbnail when selected event occur. the prewid would be reserved.
