### ISSUE TITLE
Allow proper retry of error uploads based on `retryErrorUploads` setting

### ISSUE THREAD

**Issue by jakenoble** [kartik-v/bootstrap-fileinput#1136]
I am using the `filepreupload` event  and returning an error

```
$('#input-X').on('filepreupload', function(event, data, previewId, index) {
   if(blah == 1)
      return {message: 'blah'}
});
```

This works. But the message is very cleared. If I then fix the issue so there is no error an resubmit the AJAX upload then the error is returned again and again.

Its like `filepreupload` has cached the error and refuses to then run the upload.

How can I flush the error away and have my upload run even after previously returning an error inside of `filepreupload`?

**Comment by kartik-v** [comment]
You need to write your code condition correctly so that `filepreupload` does not return the same message every time. 
```js
$('#input-X').on('filepreupload', function(event, data, previewId, index) {
   if(blah == 1) { // this condition must be dynamically changed to reflect most current state
      return {message: 'blah'}
   }
});
```

**Comment by jakenoble** [comment]
That was only a demo. Of course it changes. If I place a ‘console.log’ in there the log is only ever output once. 

Eg the code for filepreupload is only run once and further upload attempts just return the same error again and again because the code isn’t actually running.

**Comment by AlwaysOnTheWay** [comment]
i have a question. I want to use a function in filepreupload event. If return value of function is true, then execute the upload event, otherwise cancel the upload event.
