### ISSUE TITLE
Multiple file selection when using single file configuration

### ISSUE THREAD

**Issue by gael-wogenstahl** [kartik-v/bootstrap-fileinput#114]
I'm using http://demos.krajee.com/widget-details/fileinput widget as an AJAX *single* file upload field but bumped into the possibility to select multiple files before starting to upload or submitting my form.
Indeed, each time I use `Browse`, the file I select seems to be added to a queue like it would in a *multiple* file upload configuration and the field reports **n files selected** as shown in the image below.
![image](https://cloud.githubusercontent.com/assets/5624541/5641930/5ebfc974-9695-11e4-8d41-e73ff652d124.png)

Wouldn't it be better to replace the previously selected file by the new one and display only one file name in the field in a single file configuration ?

**Comment by kartik-v** [comment]
Ok I have updated to fix this. You may check now.

**Comment by gael-wogenstahl** [comment]
OK thanks ! You're doing an awesome job with those widgets.
As for using AJAX in single file upload I need it since I'm uploading heavy files and therefore using your progress bar as an indicator for the user while the classic file input without AJAX doesn't send feedback to the user until upload is finished.
