### ISSUE TITLE
Promise is undefined in IE 11

### ISSUE THREAD

**Issue by avlee** [kartik-v/bootstrap-fileinput#1140]
When delete image with ajax in IE 11 browser, there is a error happened: `Promise`  is undefined.

**Comment by vm-manocha** [comment]
**https://vega.github.io/vega/usage/#ie**

The solution to this problem is here. 

You should add polyfills that add Promise support to Internet explorer. 

[**https://github.com/stefanpenner/es6-promise**](url)

I referred this solution and my issue is resolved.

**Comment by kartik-v** [comment]
As @vm-manocha mentioned... closing this.
