### ISSUE TITLE
Display zoom for some file types

### ISSUE THREAD

**Issue by claudneto** [kartik-v/bootstrap-fileinput#1145]
## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.1.4
- bootstrap-fileinput version: 4.4.7

## Problem description

I want to show zoom button (view details) just for some file extensions. For example, txt and office files can't open modal to view preview. I want to show this modal just for images and videos. Is that possible?

**Comment by kartik-v** [comment]
Planned this for milestone release v5.0.0.

**Comment by kartik-v** [comment]
Resolved via [this major upgrade to release v5.0.0](https://github.com/kartik-v/bootstrap-fileinput/commit/d635155749059accbd68e272fdcde686f3115257) well ahead of time.

- Allow configurable file actions as a callback. 
    - The `showXXX` properties in `fileActionSettings` ca3n now be setup as a callback.
    - Can read any property from the `initialPreviewConfig` for initial preview thumbnails
- Refer resumable uploads / chunk uploads [documentation here](http://plugins.krajee.com/file-input#ajax-resumable)
- Refer [resumable uploads demos](http://plugins.krajee.com/file-resumable-uploads-demo)
- Refer [enhancements and features closed in 5.0.0 release milestone](https://github.com/kartik-v/bootstrap-fileinput/milestone/1?closed=1)
