### ISSUE TITLE
how to keep only one thumb preivew

### ISSUE THREAD

**Issue by niannianliu** [kartik-v/bootstrap-fileinput#1146]
i want only one file to be selected at one time. Now after one file is selected, when another file is selected a new thumb preview is showed. How can i keep only one thumb preview ? I mean when a new file is selected , the  thumb preview  can be refreshed with the new file instead of creating new  thumb preview. my config param is as following:
    control.fileinput({
        language: 'zh', 
        uploadUrl: uploadUrl, 
        uploadExtraData: function() {
            return extraParam;
        },
        showUpload: false,
        showRemove: true,
        dropZoneEnabled: false,
        showCaption: true,
        allowedPreviewTypes: ['image'],
        allowedFileTypes: ['image'],
        allowedFileExtensions:  ['jpg', 'png'],
        overwriteInitial: true,
        maxFileSize : 2000,       
         initialPreview: [],
        layoutTemplates: {actions:''}        
    });

I would appreciate your help.

**Comment by kartik-v** [comment]
Refer the [avatar upload demo](http://plugins.krajee.com/file-avatar-upload-demo) similar to your use case.
