### ISSUE TITLE
Something went wrong with the file upload operation. Please try again later!

### ISSUE THREAD

**Issue by exwizzard** [kartik-v/bootstrap-fileinput#1147]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Attempt to initiate upload
2. Get an error instantly

## Expected behavior and actual behavior

The code works fine on my online server, but its failing locally instantly.
Its saying "Something went wrong with the file upload operation. Please try again later!".
Is there any way to get a more descriptive error on what is going wrong?

## Environment

Browsers

- [ ] Google Chrome
- [ x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.1.1
- bootstrap-fileinput version: 4.4.6

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ x] The bug happens consistently across all tested browsers
- [ x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by mariopaisa** [comment]
> ## Prerequisites
> * [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
> * [x ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
> * [x ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
> * [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
> * [ x] I have attempted to find the simplest possible steps to reproduce the issue.
> * [ ]  I have included a failing test as a pull request (Optional).
> 
> ## Steps to reproduce the issue
> 1. Attempt to initiate upload
> 2. Get an error instantly
> 
> ## Expected behavior and actual behavior
> The code works fine on my online server, but its failing locally instantly.
> Its saying "Something went wrong with the file upload operation. Please try again later!".
> Is there any way to get a more descriptive error on what is going wrong?
> 
> ## Environment
> Browsers
> 
> * [ ]  Google Chrome
> * [ x] Mozilla Firefox
> * [ ]  Internet Explorer
> * [ ]  Safari
> 
> Operating System
> 
> * [x ] Windows
> * [ ]  Mac OS X
> * [ ]  Linux
> * [ ]  Mobile
> 
> Libraries
> 
> * jQuery version: 2.1.1
> * bootstrap-fileinput version: 4.4.6
> 
> ## Isolating the problem
> * [ ]  This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
> * [ x] The bug happens consistently across all tested browsers
> * [ x] This bug happens when using bootstrap-fileinput without other plugins
> * [ ]  I can reproduce this bug in [a jsbin](https://jsbin.com/)

Hi, @exwizzard  could you solve the problem?
