### ISSUE TITLE
missing download fa icon

### ISSUE THREAD

**Issue by ivomasterche** [kartik-v/bootstrap-fileinput#1148]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.use fa theme
2.add downloadUrl

## Expected behavior and actual behavior

When I follow those steps, I see...

The button is empty

I was expecting...

To see download icon

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Libraries

- jQuery version: 3.2.1
- bootstrap-fileinput version: 4.4.7

If i add

`downloadIcon: '<i class="fa fa-arrow-circle-down"></i>',`

to 
 
`$.fn.fileinputThemes.fa = {  fileActionSettings: { ... }}`

 it works.

**Comment by kartik-v** [comment]
There is an enhancement provided for the font awesome themes above.

But note for your use case (on overriding options) please ensure you have understood the usage right [as mentioned in this comment](https://github.com/kartik-v/bootstrap-fileinput/issues/1173#issuecomment-362787334).

You need to  [follow the FIRST HIGHLIGHTED note in the usage](http://plugins.krajee.com/file-input#usage).  

> If you are initializing the plugin separately via javascript, then DO NOT ATTACH the css class `file` to the input (as it will result in duplicate initializations and the javascript code maybe skipped).
