### ISSUE TITLE
download button doesn't work in Mozilla

### ISSUE THREAD

**Issue by ivomasterche** [kartik-v/bootstrap-fileinput#1149]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. add downloadUrl
2. use Mozilla Firefox
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
The button doesn't do anything

I was expecting...
To see the download dialogue

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

I had to add `document.body.appendChild(a);` in the fileinput.js .kv-file-download click action

**Comment by thibaultsmnt** [comment]
Hi,
I had the same problem and I found a temporary solution:
Add this to your file input config:

`layoutTemplates:{
     actionDownload: '<button type="button" class="{downloadClass}" title="{downloadTitle}"  data-caption="{caption}" onclick="window.location.href=\'{downloadUrl}\'">{downloadIcon}</button>\n',
	    		}`

It will replace the default download button by the one specified (http://plugins.krajee.com/file-input/plugin-options#layoutTemplates).
It's no good looking solution, but it seems to work for Safari, Firefox and Chrome.
