### ISSUE TITLE
Change key value after ajax

### ISSUE THREAD

**Issue by johnnytn** [kartik-v/bootstrap-fileinput#1150]
I'm using `initialPreview` and deleting some files and I'd like to know if is possible to change the **key** value of a file after I delete an other one?

I was trying to do it on **filedeleted** : 

      .on('filedeleted', function(event, key, jqXHR, data) {
                $(".kv-file-remove").attr( "data-key", "x" );
      })

 but It's just working in the view, when the data is sent to the server is just the old data.

**Comment by kartik-v** [comment]
Use the [filebeforedelete](http://plugins.krajee.com/file-input/plugin-events#filebeforedelete) or [filepredelete](http://plugins.krajee.com/file-input/plugin-events#filepredelete) event for your use case.
