### ISSUE TITLE
How to let user select a single file (image) as a 'featured' image

### ISSUE THREAD

**Issue by joetito1** [kartik-v/bootstrap-fileinput#1151]
I'm implementing this plugin as an image uploader where the user can select a single image to be the 'featured' image on our site. Could anyone point me to any documentation or examples to implement this?

**Comment by kartik-v** [comment]
Did you check a [similar example for avatar upload](http://plugins.krajee.com/file-avatar-upload-demo) on the plugin demos site?

**Comment by joetito1** [comment]
That's not quite what I'm looking for. I'd love if the user uploaded the images, saw the preview, and then could check a box next to which image would be the main photo

**Comment by kartik-v** [comment]
You would need to implement that with your own code... Most of the data of what you mention is available on your server and you need to render the html and inputs. If you are keen to still use the plugin to achieve your need,  you can read and use preview templates. You have to write your own bit of JS to achieve your use case.
