### ISSUE TITLE
Ajax sorting and deleting is messing up the JavaScript object of the file input.

### ISSUE THREAD

**Issue by AlexOlteanuCodinbit** [kartik-v/bootstrap-fileinput#1152]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue

1. Upload files using filebatchselected event.
2. Delete one or more after uploaded is completed.
3. Sort files. 

## Expected behavior and actual behavior

When I follow those steps, sometimes after deleted a file, and i want to sort the gallery, the object that is returned by the event **$('.file-loading').on('filesorted', function(event, params) { ... }** it's broken. The file that was deleted does not appear in the preview, but it is present in object, or i have files in the preview that do not appear in the object, or i have null item in object.

I need the correct object, according with the preview, to call sort method on my server. To understand better the issue i make a [video](https://www.youtube.com/watch?v=JZmKW5Se-70&feature=youtu.be) with this problem using your demo.

In my case after automatically uploaded the files, I can sort them, delete them, but if I try to delete a file and then sort them, sometimes the object is broken. I can not identify a clear scenario when this problem happens and when it does not happen.

## Environment

- [x] Yii2

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Can you check and confirm if this solves it?

**Comment by AlexOlteanuCodinbit** [comment]
Thanks for quick reply.

Unfortunately the bug still exist.

I made another [video](https://www.youtube.com/watch?v=pC7fBakZvUc&feature=youtu.be) on my local project. After delete a file the object returned by the event $('.file-loading').on('filesorted', function(event, params) { ... } it's broken.

**Comment by kartik-v** [comment]
You can check now.

**Comment by AlexOlteanuCodinbit** [comment]
Still happening. This is [video](https://youtu.be/Zb1SxFQX1CU) made after update.

I do not understand why the object is corrupted after the sorting and the removal action. 
If I just sort or just remove a file, everything it's ok, but when i do it simultaneously, the object it's broken.
