### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by YusufAkyol** [kartik-v/bootstrap-fileinput#1154]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by YusufAkyol** [comment]
Hi, 
Why I get error message when I click the upload button: SyntaxError: Unexpected token < in JSON at position 0 ? 
Thanks for your help. 
Best regards...

**Comment by YusufAkyol** [comment]
Hi,
I solved the problem... It was my mistake...
Sorry about this...
Best regards.

**Comment by cuisidong** [comment]
how do you solved?

**Comment by mhavid** [comment]
> how do you solved?

1. You must put script in file form upload
`$(document).ready(function() {
    $("#input-res-2").fileinput({
        uploadUrl: "/boomings/admin/gallery/examples/response.php",
 })
}
`
2. in file **response.php** 
- upload file with php code
- save to database with php code
- and dont forget return json format (json_encode($array_variable))
