### ISSUE TITLE
easy way to upload and download a image with extra data.

### ISSUE THREAD

**Issue by exlo89** [kartik-v/bootstrap-fileinput#1155]
Hello everybody.

I have a problem and I try to find a solution since days.
I want upload image files with a description.  You have a input field in the preview to write a text for every image. This is for the description. I have this scenario from the 7th ajax demo. There is a inputfield to change the filename.

http://plugins.krajee.com/file-input-ajax-demo/7

This works fine for me. But now if I reload the webpage I want the uploaded files with the descriptions in the preview area. 

Is there a easy way or a good solution for this? I though it is a easy thing to upload files with extra data and get all the files with inputfield and the descriptions in the preview area after a request.

Below is the most relevant code. How I can use the plugin to load the description in the description tag to show the files with the inputfield right?

```javascript
$("#PicUploadProduct").fileinput({
    previewThumbTags: {
         '{description}': ''
    },

    layoutTemplates: {
        footer: "" +
	    "<td class='file-details-cell'>" +
	        "<label>{caption}</label>" +
	        "<input name='description' class='kv-input form-control' value={description}>" +
	    "</td>" +
	        "<td class='file-actions-cell'>" +
	        "{indicator}\n{actions}" +
	    "</td>",
    },

    uploadExtraData: function() {
        var output = {}, index = 0;
        $('.kv-input:visible').each(function() {
            $element = $(this);
            output[index] = $element.val();
	    index++;
        });
	return output;
    }
});
```

**Comment by teoSalvetti** [comment]
Have you found any solution?

I have the same problem (or at least, I think so) I would like to get file name after I uploaded a file and I enter in the same page with the uploader...

**Comment by kartik-v** [comment]
You had [previewThumbTags](http://plugins.krajee.com/file-input/plugin-options#previewThumbTags).for runtime content.

For content to be loaded from server in initial preview use [initialPreviewThumbTags](http://plugins.krajee.com/file-input/plugin-options#initialPreviewThumbTags).
