### ISSUE TITLE
Custom upload function

### ISSUE THREAD

**Issue by chderen** [kartik-v/bootstrap-fileinput#1161]
Hi,

Can i use a custom upload method?

I think it's will be very useful In order to work with a different kind of API/Servers, to add a method that can get file, upload to the server and return callback with the needed information.

Thanks

**Comment by kartik-v** [comment]
You can extend the default upload behavior via the [plugin events](http://plugins.krajee.com/file-input/plugin-events) or even write your own upload routine by using the [plugin events](http://plugins.krajee.com/file-input/plugin-events) and using some of the [plugin methods](http://plugins.krajee.com/file-input/plugin-methods). Depending on your use case you can ALSO always write your own intermediate server API to read these files and upload to your distant third party server.

Can you elaborate what you mean by custom upload and what you expect to do here (appreciate if you can submit any enhancement on this via a pull request)?

**Comment by chderen** [comment]
Thanks
Can i add uploaded file to rhe stack?
I am using parseplatform.org to host and diffrend logic to upload files

**Comment by kartik-v** [comment]
The plugin has a file stack that contains only client file blobs that are pending upload - not any server uploaded files. You should be able to read server uploaded files directly via your server code - and show them on the client interface via the `initialPreview` and `initialPreviewConfig` properties of the plugin.
