### ISSUE TITLE
File name changes after file was selected

### ISSUE THREAD

**Issue by CarlosZzzz** [kartik-v/bootstrap-fileinput#1165]
Hi guys，
For example, select a file 'Moon (2).png',then this file name will changes to 'Moon _2_.png'.how to fix it?

Thanks.

**Comment by kartik-v** [comment]
You may want to search for similar other issues before posting your query - as you maybe able to find your solution.

Refer [this comment in #972](https://github.com/kartik-v/bootstrap-fileinput/issues/972#issuecomment-302383941), and #250 and #1139.

You can read about [slugCallback](http://plugins.krajee.com/file-input/plugin-options#slugCallback) in the plugin documentation.
