### ISSUE TITLE
Unable to upload images from mobile devices gallery using Ajax Upload 6

### ISSUE THREAD

**Issue by wmtoscar** [kartik-v/bootstrap-fileinput#1167]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Go to this link: http://plugins.krajee.com/file-input-ajax-demo/6
2. Try to upload an image from gallery on some of mobile devices using gallery. I am using Mi devices.
3.

## Expected behavior and actual behavior

When I follow those steps, I see an error message "You must select at least one file to upload".

I was expecting to upload a file (normal behavior)

## Environment

Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [X] Mobile

Libraries

- jQuery version: 3.2.1
- bootstrap-fileinput version: 4.4.7

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

P.S.: If my question is not relative to a issue I'd like to apologize for the mistake.

**Comment by kartik-v** [comment]
Sorry cannot reproduce your issue on mobile or Mi device. Need to check your device/browser settings or any debug logs if available to help understand where the issue is.

**Comment by wmtoscar** [comment]
I'm using Redmi 3s Prime and when I try to uploading an image on my website I am getting this error no valid data available for upload. so I tried the same thing on the mentioned demo page and there I got this message  "You must select at least one file to upload". I am facing this issue specifically on Google Chrome in my device as in my default browser it is working fine.

**Comment by kartik-v** [comment]
You need to check the device permission settings - it is not allowing your browser app (Google Chrome) to select images from your gallery.

**Comment by dennisbappert** [comment]
Happens on iOS and Android, too. Try to upload file from iOS library or try to take a picture in Chrome => "No data available for upload". It is not related to browser permissions.

**Comment by kartik-v** [comment]
Check and test a sample html with a native html file input on your device and see if you are able to upload it. Then update.
