### ISSUE TITLE
Do bootstrap-fileinput support show previews separately？

### ISSUE THREAD

**Issue by zoey0820ivy** [kartik-v/bootstrap-fileinput#1169]
i want to use this plug-in to show the pdf details ,while i use this plug-in the plug-in cannot hidden the upload and select button . all i want are that the plug-in can show details with click a formal button. so are there any methods.

**Comment by jhon100** [comment]
use layoutTemplates http://plugins.krajee.com/file-input/plugin-options#layoutTemplates
