### ISSUE TITLE
Option to set max and min image width and height?

### ISSUE THREAD

**Issue by adilsonb** [kartik-v/bootstrap-fileinput#117]
Your script is great, thank you!

There any way to set max and min image width and height? Like in maximum file upload sample in Advanced Usage?

Thanks!

**Comment by kartik-v** [comment]
Not sure I understand correct, you cannot validate the width and height of the image directly via this plugin. But you can set a width or height for the image to be displayed in the preview. For this check the [previewSettings](http://plugins.krajee.com/file-input#option-previewsettings).
