### ISSUE TITLE
我用previewFileExtSettings的时候提示我

### ISSUE THREAD

**Issue by g457165949** [kartik-v/bootstrap-fileinput#1170]
![image](https://user-images.githubusercontent.com/17248673/35432537-5f9222f8-02bb-11e8-9aa1-f940f6d88b65.png)

this is my PHP code ，->widget(FileInput::className(), [
......
 'previewFileExtSettings' => [ // configure the logic for determining icon file extensions
                            'doc' => 'function(ext) {
                                return ext.match(/(doc|docx)$/i);
                            }',

**Comment by kartik-v** [comment]
Not related to the plugin - this is more to do with Yii2 configuration and understanding Yii2 Json encoding. This is because you are wrongly setting each file-extension key configuration as a string and not a JS Function. Escape it with `yii\web\JsExpression`.
