### ISSUE TITLE
How to replace files with same filename after ajax upload? 

### ISSUE THREAD

**Issue by alexprey** [kartik-v/bootstrap-fileinput#1171]
I'm have a little confuse with ajax uploads. This issue is exists in demo.
I have a multiple fileinput that auto upload selected files to the server. And then when user try to upload file with the same name (f.ex. User upload file, then found that file have an some design error or smth like this and then fix it on local machine and try to upload it again), after it we have two thumbnails of one file, but the first thumb is out dated. How I can fix it? I already spent many time to find somehow it can be fixed, but 'm dont have any idea.

**Comment by kartik-v** [comment]
This is a application specific programming need. You need to handle such logic in your server code and program that processes the ajax upload on your server.
