### ISSUE TITLE
How to display data from initialPreviewConfig?

### ISSUE THREAD

**Issue by tidzh** [kartik-v/bootstrap-fileinput#1172]
Good day. It's been a day that I've been working on one task. How to display data in layoutTemplates. footer from the initialPreviewConfig array? I need to just torch them.
https://monosnap.com/file/8nSjLI2dljQnPgZkMZ8CP7eg01O5AG

**Comment by tidzh** [comment]
Hmmm .. But this works, but not very convenient.

`initialPreviewThumbTags: [
 {'{file_id}': '106'},
{'{file_id}': '105'},
{'{file_id}': '104'},
{'{file_id}': '103'},
{'{file_id}': '100'},
{'{file_id}': '99'},
{'{file_id}': '98'},
 ]`

**Comment by kartik-v** [comment]
Read about [initialPreviewConfig](http://plugins.krajee.com/file-input/plugin-options#initialPreviewConfig) You may want to directly use the `key` setting for each file configuration within [initialPreviewConfig](http://plugins.krajee.com/file-input/plugin-options#initialPreviewConfig) to achieve your use case above.
