### ISSUE TITLE
showRemove => false in fileActionSettings doesn't work

### ISSUE THREAD

**Issue by jhon100** [kartik-v/bootstrap-fileinput#1173]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).

I'm using ajax mode and all works fine, upload, delete, etc... However setting 'showRemove' => false in fileActionSettings doesn't work... It is still being showed.

`				'fileActionSettings' => [
					'showDrag' => false,
					'showUpload' => false,
					'showRemove' => false,
				],`

I tested other options like, showDrag, showUpload, showZoom and all works as expected (showing or hide) only showRemove is not being hide.

I'm using latest version...

**Comment by kartik-v** [comment]
Cannot reproduce your use case. Can you share a reproducible JS Fiddle?

**Comment by jhon100** [comment]
You can see it here: https://jsfiddle.net/xanzqw1t/

**Comment by kartik-v** [comment]
You can check now with the updated fix above.

BTW... it is also important [you follow the FIRST HIGHLIGHTED note in the usage](http://plugins.krajee.com/file-input#usage).  

> If you are initializing the plugin separately via javascript, then DO NOT ATTACH the css class file to the input (as it will result in duplicate initializations and the javascript code maybe skipped).

**Comment by jhon100** [comment]
Thanks @kartik-v
