### ISSUE TITLE
how can I console.log, if remove button in file input plugin is clicked

### ISSUE THREAD

**Issue by santa1993** [kartik-v/bootstrap-fileinput#1174]
I have developed a webpage with a map. On the webpage user can upload a file via file input plugin. Now I want to do something (for example remove marker)  if the remove button is clicked. 
![fileinput](https://user-images.githubusercontent.com/25269232/35625443-aea3d046-0692-11e8-8c79-d4257ccad798.PNG)

how can I access the removebutton via jquery like below?

$(".btn-info").on('click', function() {
        $('#input-id').fileinput('refresh', {previewClass:'bg-info'});
		console.log("refresh");
    });

Instead of $(".btn-info") should be the id of the remove button.....

**Comment by santa1993** [comment]
I have developed a webpage with a map. On the webpage user can upload a file via file input plugin. Now I want to do something (for example remove marker)  if the remove button is clicked. 
![fileinput](https://user-images.githubusercontent.com/25269232/35625443-aea3d046-0692-11e8-8c79-d4257ccad798.PNG)

how can I access the removebutton via jquery like below?

$(".btn-info").on('click', function() {
        $('#input-id').fileinput('refresh', {previewClass:'bg-info'});
		console.log("refresh");
    });

Instead of $(".btn-info") should be the id of the remove button.....

**Comment by kartik-v** [comment]
Use the [`fileclear` plugin event](http://plugins.krajee.com/file-input/plugin-events#fileclear).
