### ISSUE TITLE
RTL only for browse button

### ISSUE THREAD

**Issue by ntdvj** [kartik-v/bootstrap-fileinput#1175]
Hi, i want to move JUST browse button to the left and keep everything else just as it.
I try using rtl, but all position are inversed.
how to do that?
thanks

**Comment by kartik-v** [comment]
Read docs on [plugin options](http://plugins.krajee.com/file-input/plugin-options) and read about [layoutTemplates](http://plugins.krajee.com/file-input/plugin-options#option-layoutTemplates).

You need to set `layoutTemplates.main1`

**Comment by kartik-v** [comment]
An example of this is provided in [plugin advanced demo 6](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-6).
