### ISSUE TITLE
Making own serializer. Need to retrieve files with drag and drop functionality

### ISSUE THREAD

**Issue by SchalkBreed** [kartik-v/bootstrap-fileinput#1176]
I am trying to retrieve the files from a file input that's more generic. My idea is that my code should both work for this plugin and normal other file inputs. The code I use now is:
 var file_input = document.getElementById('the_id').files;

This actually works but only if you choose the files from the Browse button. It fails to get the files when you drag and drop it ontop of the component. The preview and everything shows but it seems like it does not fill the input?

Do you have a jQuery way or vanilla way of getting that files collection without using a function directly from you library?

**Comment by kartik-v** [comment]
Please go through the [plugin docs for usage modes](http://plugins.krajee.com/file-input#usage-modes) to understand what feature is possible in what mode.

For example, Drag and drop feature is only supported if you use an ajax method of uploading files via the plugin and not reading it like a native file input as you are doing.

**Comment by SchalkBreed** [comment]
The point is that I want to retrieve it natively from the plugin. I do not want to use the plugin's uploading methods.

**Comment by SchalkBreed** [comment]
I am submitting a form at all. Just need the files from the input.

**Comment by kartik-v** [comment]
As I mentioned in my comment earlier... to just get the files you can use the [getFileStack method](http://plugins.krajee.com/file-input/plugin-methods#getFileStack)... however there are many other validations and conditions possible which is programmed in the plugin (like deleting, appending files etc.) and I am not sure how you intend to use it... and develop all those.

**Comment by kartik-v** [comment]
As I mentioned in my comment earlier... to just get the files you can use the [getFileStack method](http://plugins.krajee.com/file-input/plugin-methods#getFileStack)... however there are many other validations and conditions possible which is programmed in the plugin (like deleting, appending files etc.) and I am not sure how you intend to use it... and develop all those.

> I am submitting a form at all. Just need the files from the input.
So please try to go through the [usage modes](http://plugins.krajee.com/file-input#usage-modes) as to what is possible in a form submission mode. This is restricted by HTML capability and browser support on what is supported and nothing to do with the plugin.
