### ISSUE TITLE
Option for Auto-Start Upload with Ajax

### ISSUE THREAD

**Issue by brunonetadmin** [kartik-v/bootstrap-fileinput#1177]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

When i file its selected, i need to click in the button "upload" for send the file(s). But i think its a good idea have a option to make this automaticaly, like dropzone plugin for example.

## Expected behavior and actual behavior

Expected Behavior: Auto Upload files when selected via Ajax.
Actual Behavior: Need a manual click in "upload" for send the file.

## Environment
- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 4.4.7

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by jhon100** [comment]
Did you tried this?  http://plugins.krajee.com/file-input-ajax-demo/6

**Comment by litrozima** [comment]
Hi Kartik

We tried the demo 6 example but it doesn't work as expected :(

**Comment by kartik-v** [comment]
Bug #1460 has been recorded. This will be resolved via that shortly.
