### ISSUE TITLE
[Sugestion] Option to change the default order of the file uploaded

### ISSUE THREAD

**Issue by brunonetadmin** [kartik-v/bootstrap-fileinput#1179]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Add a new file.

## Expected behavior and actual behavior

When a new file its added, it goes to the end of the list. I need it stays in the first of the list (more recent first). Something like a option : default_order = "ASC" or "DESC"

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: latest

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
You can control this in your server code.. e.g. the `uploadUrl` that processes the upload.... because the file stack is passed as an array to your `uploadUrl`. 

You can for example always read the file stack array on your server code in the reverse order (for DESC/ASC)... e.g. PHP provides [array_reverse](https://www.w3schools.com/php/func_array_reverse.asp).

**Comment by brunonetadmin** [comment]
This is possible for files that are already uploaded, but i´m talking about the new files we add. It aways start in the end of the "table", in the "explorer" template, i think this is the way you append, instead of set it to the end, a option to add in the first row of the table.

**Comment by kartik-v** [comment]
Willlook

**Comment by kartik-v** [comment]
New boolean property [reversePreviewOrder](http://plugins.krajee.com/file-input/plugin-options#reversePreviewOrder) has been added.

Refer the [reverse preview order demo as well](http://plugins.krajee.com/file-preview-management-demo#preview-reverse).
