### ISSUE TITLE
Move thumbnails preview

### ISSUE THREAD

**Issue by valix85** [kartik-v/bootstrap-fileinput#118]
hello, what can i do for move thumbnails of image preview in a specific div?
i need to separate in two different column the input button and the preview frame.

thank u
best regards

**Comment by kartik-v** [comment]
You need to [check the docs and edit various templates options](http://plugins.krajee.com/file-input#option-layouttemplates) in the plugin (e.g. `layoutTemplates.main1`, `layoutTemplates.preview` etc.)

**Comment by valix85** [comment]
i just see it but i have many difficult to understand it, it's possible an example?
