### ISSUE TITLE
The problem with adding files containing a symbol "—" in the name

### ISSUE THREAD

**Issue by VladimirLuzhin** [kartik-v/bootstrap-fileinput#1180]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
Try adding files with the names 1—.jpg('—' - i think problem with that symbol) and 1.jpg, using the explorer theme.
The same problem with names 1 — copy.jpg and 1.jpg.

## Expected behavior and actual behavior

When I follow those steps, I see only one file with random name 1.jpg or 1—.jpg

I was expecting to see two files with names 1.jpg and 1—.jpg

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 4.4.7

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-krajee-explorer-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Please read the plugin documentation and about [slugCallback](http://plugins.krajee.com/file-input/plugin-options#slugCallback) - which you need to configure to allow all such non-standard characters.
