### ISSUE TITLE
It doesn't work with Spring MVC, Bad Request error

### ISSUE THREAD

**Issue by PaolaG82** [kartik-v/bootstrap-fileinput#1182]
I'm trying to implement this plugin with Spring MVC.
But it doens't work. I always receive bad request. I already read this: [https://github.com/kartik-v/bootstrap-fileinput/issues/982](https://github.com/kartik-v/bootstrap-fileinput/issues/982), but I didn't find a solution.. 

This is my code:
```
		<div class="file-loading">
   			<input id="inpuFile" name="inpuFile" type="file" multiple="multiple"/>
		</div>
		<script>
		$(document).on('ready', function() {
		    $("#inpuFile").fileinput({
		    	 uploadAsync: false,
		        maxFileCount: 10,
		        allowedFileExtensions: ["pdf"],
		        language: "it",
		        uploadUrl: "url"
		    });
		});
		</script>

```

The header:

```
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, br
Accept-Language:it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
Connection:keep-alive
Content-Length:434279
Content-Type:multipart/form-data; boundary=----WebKitFormBoundary7fifyJwiZmHZqehx
Cookie:JSESSIONID=60A5B4D9DEE09D1E91C6BC39D8E814B8; JSESSIONID=78E9C9BB213182F96BFDE04C4D0A9C48
DNT:1
Host:localhost:8080
Origin:http://localhost:8080
Referer:http://localhost:8080/mato/20
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
X-Requested-With:XMLHttpRequest

```

the payload:

```
------WebKitFormBoundary7fifyJwiZmHZqehx
Content-Disposition: form-data; name="inpuFile"; filename="pdf.pdf"
Content-Type: application/pdf


------WebKitFormBoundary7fifyJwiZmHZqehx
Content-Disposition: form-data; name="file_id"

0
------WebKitFormBoundary7fifyJwiZmHZqehx-
```-

What am I doing wrong?

**Comment by kartik-v** [comment]
Check the [comment in #982 again](https://github.com/kartik-v/bootstrap-fileinput/issues/982#issuecomment-311882796).

Quoting part of it below:

> Secondly (the error you are getting seems some issue in your server code web request) you need to check in your framework - if you need some headers/CSRF or similar tokens to be passed as headers to the ajax request.

> Thirdly the error in your server request could also be due to a malformed JSON that is being returned. Note that for ajax mode the plugin requires [a valid JSON object to be SENT back as described in the documentation](http://plugins.krajee.com/file-input#ajax-uploads). You need to ensure you are returning a valid JSON object on the server request set in `uploadUrl`.
