### ISSUE TITLE
No error messages when showPreview is set to false

### ISSUE THREAD

**Issue by makshh** [kartik-v/bootstrap-fileinput#1185]
## Steps to reproduce the issue

1. Use default settings and set `showPreview` to false.
2. Return error from backend (I'm using PHP - `echo json_encode(array('error' => 'My custom error.'));`

## Expected behavior and actual behavior

Actual behavior: even when I set the error I see `Done.` message and success progress bar.
Expected behavior: my error message and danger progress bar.

I tested it also with `showPreview` set to true and everything is fine (error appears under the file preview), but it doesn't work without file preview.

## Environment

Doesn't really matter in that case.

## Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 4.4.8

I can't show it on JSBin for example (you need repsonse from the server).

**Comment by hillrnate** [comment]
You should look at http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-10. I was having the same problem, but there turns out to be an easy fix for this.

**Comment by kartik-v** [comment]
Yes as @hillrnate pointed out... you need to set your own [elErrorContainer](http://plugins.krajee.com/file-input/plugin-options#elErrorContainer) for the error container.

**Comment by kpsanmao** [comment]
> You should look at http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-10. I was having the same problem, but there turns out to be an easy fix for this.

Thank you!
