### ISSUE TITLE
File input seems without css

### ISSUE THREAD

**Issue by hsntngr55** [kartik-v/bootstrap-fileinput#1186]
I'm trying to solve this whole day, but still continue.. I added all css and javascript files with descripted order, but file input seems [like that. ](https://i.hizliresim.com/5DyQoz.png)

But why ? couple months ago, I used this package with 3.3.7 and it was worked as well. But now, it seems both of versions. How can I fix this ?

**Comment by decosvaldo** [comment]
I'm facing similar problem.

My input object is created with classes that do not exist in the .css file.

file-caption form-control kv-fileinput-caption icon-visible
![1](https://user-images.githubusercontent.com/33238000/36554107-f9f58d2c-17dc-11e8-8adf-afe14e116b17.jpg)

**Comment by decosvaldo** [comment]
I'm using bootstrap 4, not 4 alpha as mentioned.

**Comment by emresaracoglu** [comment]
I have the same problem. 
_Bootstrap: 3.3.7
File Input: 4.4.5_

![screenshot-2018-6-17](https://user-images.githubusercontent.com/297968/41506863-9845f60a-722e-11e8-945b-a0001aff1feb.png)

**Comment by alian954** [comment]
> 

![](https://user-images.githubusercontent.com/297968/41506863-9845f60a-722e-11e8-945b-a0001aff1feb.png)

You only need bootstrap4-glyphicons

**Comment by kartik-v** [comment]
Ensure you have the updated release of the extension and follow the plugin docs for Bootstrap 4 implementation.
