### ISSUE TITLE
maxFileCount dosent work in Ajax model when uploading one by one 

### ISSUE THREAD

**Issue by sdfarshid** [kartik-v/bootstrap-fileinput#1189]
In all ajax model of file upload when  we select file and push the upload  button or automatic upload the file , MaxFileCount dosent work, 
for example when set   maxFileCount : 3 and select  4 file at on choose the script show error but when choose one file  and uploaded that one ,  the script dosnt show any message for maxFile count and let u choose and upload another one , 
U can see this issue in 
http://plugins.krajee.com/file-input-ajax-demo/9

![image](https://user-images.githubusercontent.com/9034581/36760560-9c9860de-1c30-11e8-99ba-5b4d42f4371c.png)

**Comment by kartik-v** [comment]
[`maxFileCount`](http://plugins.krajee.com/file-input/plugin-options#maxFileCount) validation is only applicable for newly selected files via the file picker or drag drop (not for the files already uploaded).

In case you want to do something like that you need to set the [`initialPreview`](http://plugins.krajee.com/file-input/plugin-options#initialPreview) for the files already uploaded and set [`validateInitialCount`](http://plugins.krajee.com/file-input/plugin-options#validateInitialCount) property to `true`
