### ISSUE TITLE
Upload the InitiatePreview data images along with the freshly selected

### ISSUE THREAD

**Issue by irfanheritage** [kartik-v/bootstrap-fileinput#1191]
Hi, first i want to say thank you for this amazing plugin.

I have a problem, as i read in the documentation, i retrieve the saved image data in the `initiatePreview` as an URL, and it worked perfectly. But when I browse another image for addition, it just replacing the data instead of adding the data.

So my question is how to reupload the initiatePreview data along with the newly upload one? 
Here is my code:
`$("#images").fileinput({
            'theme': 'explorer-fa',
            <?php if(isset($portfolio)) {?>
            
            'uploadUrl': '<?=base_url()?>portfolio/edit/<?= $portfolio["ID"]?>',
            
            <?php } else { ?>
            
            'uploadUrl': '<?=base_url()?>portfolio/new',
            
            <?php } ?>
            uploadAsync: false,
            overwriteInitial: false,
            <?php if(isset($portfolio['images']) && !empty($portfolio['images']) && !is_null($portfolio['images'] && $portfolio['images'] !== '[]')) {?>

	        initialPreview: [<?php $imgArr = json_decode($portfolio['images']); foreach ($imgArr as $key => $value) {
	        	$img = str_replace('"', '', $value);
	        	echo '"'.str_replace('./', base_url(), $value).'"';
	        	if($value != end($imgArr)){
	        		echo ",";
	        	}
	        }?>],
	        initialPreviewConfig: [
	        	<?php foreach (json_decode($portfolio['images']) as $key => $value) {?>
	        		<?php $caption = explode("/", $value);?>
	        		{caption: '<?= end($caption)?>', url: '<?=base_url()?>portfolio/edit/<?= $portfolio["ID"]?>', uploadUrl: '<?=base_url()?>portfolio/edit/<?= $portfolio["ID"]?>', width: 'auto', key: <?= $key + 1?>},
	        	<?php }?>
	        ],
            initialPreviewAsData: true,
            <?php }?>
            append: true,
            showUpload: false,
	        showCaption: true,
	        browseClass: "btn btn-primary",	
	        maxFileCount: 10,
	        allowedFileExtensions: ["jpg", "gif", "png", "jpeg"],
	        uploadExtraData: function() {  // callback example
	            var obj = {};
				var titles 			= $('#title').val();
		        	obj['title']			= titles,
	            return obj;
	        }
        });
		$("#images").on('filebatchuploadsuccess', function(event, data) {
			$('#ajax-loader').show();
	        setTimeout(function () {
		      window.location.href = "<?= base_url('portfolio')?>";
		    }, 2000);
	    });
	});

	$('#submit').click(function(){
		$('#images').fileinput('upload');		
	});`
I hope you can understand my problem and kindly solving it. Thank you

**Comment by kartik-v** [comment]
Normally setting `overwriteInitial` to `false` should be done - but I am not sure what your FILE INPUT markup is and how you are configuring that.
