### ISSUE TITLE
Allow drag and drop for form based submission

### ISSUE THREAD

**Issue by Alexander--** [kartik-v/bootstrap-fileinput#1193]
As far as I understand, the plugin currently has two modes of operation: form submission and AJAX submission, and the former has lots of limitations:

* No drag & drop
* No image resize/editing (?)
* No image reordering (?)

On other hand, AJAX does not integrate well with `initialPreview` (or requires using separate methods from form uploads for same functionality).

This makes plugin API extremely non-intuitive. Robust, but very hard to learn.

Please remove distinction between upload modes and make unified API.

Modern browsers (including most recent Firefox) started to add support for setting values of form file inputs. On older versions it should be possible to emulate form submission via AJAX/FormData. There is no reason to keep artificial distinction between form and AJAX modes, if they work the same way. When  some AJAX endpoint isn't available, the library can instead generate an event, that can be handled by developer (for example, by modifying hidden form fields).

**Comment by kartik-v** [comment]
Unfortunately, there is still currently no standards implemented across browsers for native HTML file inputs to be manipulated via SCRIPT/JAVASCRIPT. 

Unfortunately there is nothing much that can be done rather than trying to learn and understand what the browser limitations are and program your app accordingly.

However, any enhancement if you feel can improve this is appreciated and you are free to submit a Pull Request. Will keep the issue open. Thanks.

**Comment by Alexander--** [comment]
@kartik-v

> This is a browser security feature / limitation (on how browsers handle native file inputs).

This is no longer true for modern browsers: https://stackoverflow.com/a/47522812, — `files` collection can be modified in recent versions Chrome, Firefox, Edge and Webkit-based browsers.

**Comment by kartik-v** [comment]
@Alexander I am aware of some support in newer versions - but not all browsers yet - not sure its available on IE, or the mobile browsers. Need to test it out for limitations across scenarios to be able to add it as aa generic functionality in this plugin,

**Comment by Alexander--** [comment]
@kartik-v 

I agree, that it is too early to fully rewrite the plugin. But you can check if the assignment works (possibly using same approach as [W3C test case](https://github.com/w3c/web-platform-tests/pull/6617/files)). If `files` is assignable, the library may use that to lift some limitations for form upload, otherwise proceed as usual.

**Comment by kartik-v** [comment]
Will note an enhancement and keen to get anyone submitting their enhancements/suggestions.

Even with this feature added - there will be many behavioral limitations - you cannot selectively delete files from the filelist - or necessarily append files one by one to a file list. At the best you can overwrite one set of filestack with another.

**Comment by Alexander--** [comment]
@kartik-v perhaps, but at least you may be able get DnD to work since `DataTransfer.files` [also contains a FileList](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/files).

**Comment by kartik-v** [comment]
> @kartik-v but at least you may be able get DnD to work since `DataTransfer.files` [also contains a FileList](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/files).

Yup that's what I updated earlier - we already have file selection ... with this the feature of allowing to replace a range of files with another batch of files can be done and Drag & Drop support as you mentioned will be a part of that.

**Comment by kartik-v** [comment]
Resolved via the commit above - enhancement added for drag and drop for form based submissions.
