### ISSUE TITLE
Refresh method doesn't work.

### ISSUE THREAD

**Issue by ddv88** [kartik-v/bootstrap-fileinput#1195]
After update from 4.4.0 refresh method stop working. No console errors or exceptions. 
Just this https://i.imgur.com/rCTlITy.png.
```
if ($mediaInput.length) $mediaInput.fileinput({
    language: app.fileinput.language,
    uploadUrl: "upload_media",
    initialPreviewAsData: true,
    uploadAsync: true,
    showCaption: false,
    showClose: false,
    showRemove: false,
    showUpload: true,
    fileActionSettings: {
        showZoom: false,
        showUpload: false
    },
    overwriteInitial: false,
    maxFileSize: 5000,
    maxFileCount: 20,
    allowedFileExtensions: ["jpg", "png"]
});

$mediaInput.fileinput("refresh", {
    initialPreview: [
        "/upload/05_03_18/084d5ac6e6d560bba80931198405383a.jpg",
    ],
    initialPreviewConfig: [
        {url: "delete_media", key: "51e2be642609e0ba15001f98ba3a66e1"},
    ]
});
```

**Comment by kartik-v** [comment]
Actually there is been an update since the version 4.4.x for the refresh method to not affect or change the `initialPreview` - for a specific reason. This is because the files may have been partially uploaded and the preview will get disturbed resulting in unexpected behavior. This has been noted and updated in the docs for the [refresh method](http://plugins.krajee.com/file-input/plugin-methods#refresh). 

For your use case - use the plugin's [destroy method](http://plugins.krajee.com/file-input/plugin-methods#destroy) first and reinitialize the plugin with the new options (you need to supply all options).

**Comment by nageshvn** [comment]
5.0.4 version also not working  plz recitry 

$(document).ready(function () {
	
$( "#target" ).click(function() {

$('#file-3').fileinput('destroy').fileinput({showPreview: true});

$("#file-3").fileinput('refresh', { 

  theme: 'fas',
        showUpload: true,
        showCaption: false,
        browseClass: "btn btn-primary btn-lg",
        fileType: "any",
        previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
        overwriteInitial: false,
    initialPreviewAsData: true,
          initialPreview: [
            "http://lorempixel.com/1920/1080/transport/1",
            "http://lorempixel.com/1920/1080/transport/2",
            "http://lorempixel.com/1920/1080/transport/3"
        ],
        initialPreviewConfig: [
            {caption: "transport-1.jpg", size: 329892, width: "120px", url: "{$url}", key: 1},
            {caption: "transport-2.jpg", size: 872378, width: "120px", url: "{$url}", key: 2},
            {caption: "transport-3.jpg", size: 632762, width: "120px", url: "{$url}", key: 3}
        ]
		
 });
 

alert('success');
});
       $("#file-3").fileinput({
        theme: 'fas',
        showUpload: true,
        showCaption: false,
        browseClass: "btn btn-primary btn-lg",
        fileType: "any",
        previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
        overwriteInitial: false,initialPreviewAsData: true,
          initialPreview: [
            "http://lorempixel.com/1920/1080/transport/1",
            "http://lorempixel.com/1920/1080/transport/2",
            "http://lorempixel.com/1920/1080/transport/3"
        ],
        initialPreviewConfig: [
            {caption: "transport-1.jpg", size: 329892, width: "120px", url: "{$url}", key: 1},
            {caption: "transport-2.jpg", size: 872378, width: "120px", url: "{$url}", key: 2},
            {caption: "transport-3.jpg", size: 632762, width: "120px", url: "{$url}", key: 3}
        ]
      
    });
	
	
    });
