### ISSUE TITLE
Zoom Cach

### ISSUE THREAD

**Issue by HKhedr** [kartik-v/bootstrap-fileinput#1196]
`var footerTemplate = '<div class="file-thumbnail-footer" style ="height:94px">\n' +
        '  <input id="InsertFile_AttachFile_Description" name="InsertFile.AttachFile.Description" class="form-control input-md form-control-md text-center" placeholder="write description..." />\n' +
        '   <div class="small" style="margin:15px 0 2px 0">{size}</div> {indicator}\n{actions}\n' +
        '</div>';`

when submit form I get duplicate value from input first contain user value and second empty string ''..
Happen when showZoom=true.. that duplicate content.
Can I skip  input file from duplicate content!!?

Thank you.
@kartik-v

**Comment by kartik-v** [comment]
Yes you can exclude (or write code to ignore) content inside zoom cache by parsing for container with CSS class `kv-zoom-cache` ... for example in your above code - you can write a logic to disable the inputs inside zoom cache (so that they are not submitted) with a code like this before you submit your form...

```js
$('.kv-zoom-cache input').attr('disabled', 'disabled');
```

**Comment by HKhedr** [comment]
thank you, 
`
$ele.on('filebatchselected', function (event, files) {
    $('.kv-zoom-cache input').attr('disabled', 'disabled');
});
`
work good

**Comment by shritis** [comment]
i do not need that kv-zoom-cache, what should i do to remove?

**Comment by prakashshrestha** [comment]
I have created input field name captions and submitting the form it will create same captions two times show i have duplications in captions how can we remove the duplicate values from js end.
