### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0.

### ISSUE THREAD

**Issue by specYyt** [kartik-v/bootstrap-fileinput#1199]
When i uploaded a image,the Error "SyntaxError: Unexpected token < in JSON at position 0." appears immediately. But actually,the file has uploaded to the server. Why could this happen?

**Comment by kartik-v** [comment]
Duplicate to #622 (read docs and webtips).

Also related to #1076 and #1154 (please search for all such duplicate issues before posting).

You need to send/receive right JSON format from server - else you will face the parse errors.

Your [query is answered here](http://webtips.krajee.com/question/json-syntax-error-bootstrap-fileinput/)
