### ISSUE TITLE
Uploading more files without clearing after upload causes no data to be uploaded

### ISSUE THREAD

**Issue by zebub** [kartik-v/bootstrap-fileinput#120]
1. Select files
2. Upload files
3. Select more files (withour clearing)
4. Upload new files

Second set of files does not include file data in upload.
This only seems to happen when the "upload all" button is used, not when each file is uploaded individually.

**Comment by nakarin4350** [comment]
After I upgrade to dev-master the upload button do works,but after the "second set of files" upload completed the progress bar show random value (eg 87%,90% not 100%).

**Comment by kartik-v** [comment]
The progress calculation is updated. Check and confirm.

**Comment by nakarin4350** [comment]
It works now,I really appreciate all of your works(so many good stuffs).Cheers.
