### ISSUE TITLE
browseOnZoneClick not working if uploadUrl is set

### ISSUE THREAD

**Issue by adampweb** [kartik-v/bootstrap-fileinput#1200]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. execute my code: [https://jsfiddle.net/gej3y8uq/26/](https://jsfiddle.net/gej3y8uq/26/) 
2. **uploadUrl** marked as comment: browseOnZoneClick woking correctly
3. **uploadUrl** except from comment: browseOnZoneClick not working, when click the preview(dropzone), preview as focused but nothing else happens

## Expected behavior and actual behavior

When I follow those steps, I see the preview area focused (with light-blue border) but nothing else happens :(

I was expecting open file open dialog, but...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- bootstrap-fileinput version: 4.4.7

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/): [http://jsbin.com/yupajadote/edit?html,css,js,output](http://jsbin.com/yupajadote/edit?html,css,js,output)

**Comment by kartik-v** [comment]
This is not an issue with the `uploadUrl` but an issue with the `elErrorContainer` custom setting not parsing the click correctly. A fix will be provided.
