### ISSUE TITLE
maxfilecount 

### ISSUE THREAD

**Issue by edsonvictor09** [kartik-v/bootstrap-fileinput#1202]
Hello how can i combine the maxfilecount for this 4 upload file when i upload the total amount for file is max of 30.

thanks big help.

[maxfilecount.txt](https://github.com/kartik-v/bootstrap-fileinput/files/1821163/maxfilecount.txt)

**Comment by kartik-v** [comment]
You need to do this validation and calculation in your server code and pass this configuration to the client.
