### ISSUE TITLE
initialPreview issue is not image url is provided

### ISSUE THREAD

**Issue by itajackass** [kartik-v/bootstrap-fileinput#1203]
Is there a way to show a initial avatar (uploaded before with the form), and display standard image (NO AVATAR) if avatar not exist? I uploaded an attachment to show the problem: i want POINT 2 when i've uploaded nothing yet.

My input field:

    <input type="file" id="avatar" name="avatar" data-url="<?php echo $path_to_actual_image; ?>">

    // $path_to_actual_image can be empty if logo are not set yet

I use this now:

    $("#avatar").fileinput({
      language: 'it',
	  overwriteInitial: true,
	  removeFromPreviewOnError: true,
      initialPreviewAsData: true,
		showClose: false,
		browseOnZoneClick: true,
		showCaption: false,
		browseIcon: '<i class="glyphicon glyphicon-folder-open"></i>',
		removeIcon: '<i class="glyphicon glyphicon-remove"></i>',
      initialPreview: [ function() { if ( $("#avatar").data("url") != "" ) { return $("#avatar").data("url"); } else { /*NOTHING*/ } ],
      defaultPreviewContent: '<img src="http://www.placehold.it/300x300/EFEFEF/AAAAAA&amp;text=no-avatar" alt="No avatar">',
      allowedFileExtensions: ["jpg", "jpeg", "png", "gif"],
		maxFileSize: 2000
    })

It work good... but if no avatar exist, it show me a blank block! (POINT 1 of my uploaded example attachment) I tried to change in:

 

    initialPreview: [ function() { if ( $("#avatarl").data("url") != "" )
    { return $("#avatar").val("url"); } else { return "http://www.placehold.it/300x300/EFEFEF/AAAAAA&amp;text=no-avatar"; } ] 

...In this case I see standard image for no-avatar set, but zoom button and delete button are active!! (Those has to be not activate). (referring to POINT 4 in my attachment example)

Additional info: I not upload with ajax
Attachment: https://i.stack.imgur.com/5vBiE.jpg

**Comment by kartik-v** [comment]
Easiest solution is to do this in the server code that returns the URL for the `initialPreview`.

For example on your PHP server code that returns the image url:

```php
<?php // instead of below ?>
<?php echo $path_to_actual_image; ?>">

<?php //do this ?>
<?php
if (empty($your_actual_image)) {
    echo 'http://www.placehold.it/300x300/EFEFEF/AAAAAA&amp;text=no-avatar';
   // return your default placeholder image
} else {
   echo $path_to_actual_image/$your_actual_image;
}
?>
```

**Comment by itajackass** [comment]
Sorry i don't understand where exactly i need to put your code...
After some debug i see i need to get an empty value here to work:

initialPreview: [ ]

But for example i tried:

initialPreview: [ function(){return '';}]

Doesn't work as expected and i don't know why

**Comment by itajackass** [comment]
HI, any chance to get working this line of code?

    initialPreview: [ function(){return '';}]      // output    initialPreview: [ ]

Thanks
