### ISSUE TITLE
Word Excel preview BUG, there will be a random code problem, the official network demo will also appear chaotic code

### ISSUE THREAD

**Issue by linjtest** [kartik-v/bootstrap-fileinput#1206]
Word Excel preview BUG, there will be a random code problem, the official network demo will also appear chaotic code。

**Comment by kartik-v** [comment]
Not clear with this issue or what you are trying to convey? Can you please submit issues as per the [guidelines](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md) - and share a JS Fiddle Code Snippet or similar to understand your issue.

**Comment by linjtest** [comment]
![tim 20180322123449](https://user-images.githubusercontent.com/21279486/37751594-3d9cd9c0-2dce-11e8-97ac-f7d742a8f27a.png)

**Comment by linjtest** [comment]
I'm sorry, I've been learning to use the official demo recently, about preview excel and word, which I saw in the official demo two days ago.
