### ISSUE TITLE
Problem with preview data embed pdf put in video class.

### ISSUE THREAD

**Issue by ALTELMA** [kartik-v/bootstrap-fileinput#1207]
I try to setup and read your document as I can, but still find the way to setup preview file class
for PDF. You will see screen shot below.

![selection_001](https://user-images.githubusercontent.com/4938568/37750279-baa3ac56-2dbe-11e8-8259-26d58ff0bcfe.png)

![selection_002](https://user-images.githubusercontent.com/4938568/37750443-9fcb59fa-2dbf-11e8-9c18-ab8785f6c8d4.png)

I don't understand Why embed pdf put in .fluid-width-video-wrapper class. Normally I checked on
your example for many times. If I move embed file out from video-class should be OK.

This problem cause only initial data.
Is that Bug or not?

**Comment by kartik-v** [comment]
Sorry this cannot be reproduced and seems some config and markup at your end. You can cross check in the plugin demos on how the markup is rendered.

You need to check your code on how you are rendering the content. Are you changing the markup and plugin `layoutTemplates` or `previewTemplates` - or setting initialPreview differently ... the preview markup will accordingly need to be checked/debugged.
