### ISSUE TITLE
No proview and thumb for excel?

### ISSUE THREAD

**Issue by ALTELMA** [kartik-v/bootstrap-fileinput#1208]
After I try to fix last problem. I found new problem.

![selection_003](https://user-images.githubusercontent.com/4938568/37752964-2f711f74-2dcd-11e8-8d9e-b4fae3024745.png)

https://docs.google.com/gview?url=blob:http://www.dev.example.com/ed2347ba-35d8-4b6b-b40b-39587aeab90a&embedded=true

This problem happened only before upload. 

How can I fix it?

**Comment by kartik-v** [comment]
Your url is incorrect... its `blob:http://____`  ... ensure its a publicly accessible correct url starting with `http:` for example.
