### ISSUE TITLE
docs.google.com in china unavailable

### ISSUE THREAD

**Issue by linjtest** [kartik-v/bootstrap-fileinput#1209]
I am a Chinese programmer, this is a very practical plug-in, thanks to the author's plug-in. But when it comes to office online preview, it's impossible to use it at home and seek a better solution.
![b nh7 d fhk 1e df1_v](https://user-images.githubusercontent.com/21279486/37756902-14efd992-2de6-11e8-896a-891a7ea122d1.png)

**Comment by kartik-v** [comment]
Yes the plugin uses the free Google docs viewer to view office files... If it is unavailable in your country... Then check if you have an alternative... And we can set it via your country locale

**Comment by kartik-v** [comment]
I am providing an enhancement via #1210 to use office online viewer for office docs.

**Comment by coderLinJ5945** [comment]
Thanks a million!
