### ISSUE TITLE
Server don't recieve data on body response.

### ISSUE THREAD

**Issue by josuhawagener** [kartik-v/bootstrap-fileinput#1211]
Hello, im having troubles trying to upload files to the server. I recieve the ajax call on the server but the response.body its empty. Its a blob so i try to get the data via request.body.toString(), like im doing to delete files, but gives me an undefined variable. What i am doing wrong?

	$('#input-ke-1').fileinput({
	  minFileCount: 1,
	  uploadAsync:true,
	  uploadExtraData: function (previewId, index) {
	     var arg = {"NombreFuncion": "SAVE_Adjunto","objeto":"FT_GuardarRegistro"};
	    return arg;
	  },
	  uploadUrl:"/cors/1.0/public/CallFunction",
	  language: "es",
	 maxFileCount: 50,
	 showClose:false,
	 showDrag:false,
         zoomTitle:'Detalles',
	overwriteInitial: false,
	initialPreview: imagenes,
	initialPreviewAsData: true,
	initialPreviewConfig: imagConfig,
	allowedFileExtensions: ["jpg", "gif", "mp3", "mp4", "html", "jpeg", "pdf", "png"],
	purifyHtml: true, // this by default purifies HTML data for preview			
        }).on('filepreupload', function(event, data, previewId, index) {
	var form = data.form, files = data.files, extra = data.extra,
	reader = data.reader;
	var	response = {};
	response.form = form;
	response.files = files;
	response.extra = extra;
	response.reader = reader;
        });

**Comment by gabken** [comment]
Have you solved this?

**Comment by josuhawagener** [comment]
nope :(

**Comment by gabken** [comment]
i've resoved this, code in my issue

**Comment by gabken** [comment]
`  if (formItems != null && formItems.size() > 0) {
            // 迭代表单数据
            for (FileItem item : formItems) {
                // 处理不在表单中的字段
                if (item.isFormField()) {
                	 String name = URLDecoder.decode(item.getFieldName(),"UTF-8");
                	 String value = URLDecoder.decode(item.getString(),"UTF-8");
                	 if(name.equals("pid")){pid=value;}
                	 if(name.equals("lcid")){lcid=value;}
                	 if(name.equals("filename")){filename=value;}
                	 if(name.equals("filekeyword")){filekeyword=value;}
                	 if(name.equals("filesecret")){filesecret=value;}
                	 if(name.equals("fileremark")){fileremark=value;}
                	 if(name.equals("fileclass")){fileclass=value;}
                }
              
            }`

**Comment by kartik-v** [comment]
Hi folks just treat the response to the server similar to how you would receive FILES via a native HTML FILE INPUT.
