### ISSUE TITLE
Add CSRF token to upload file using HTML 5 (data-) inside an input tag

### ISSUE THREAD

**Issue by PaolaG82** [kartik-v/bootstrap-fileinput#1214]
I'm using the plugin for a WebApp with: Bootstrap4, Thymeleaf and Spring Boot.

I would like to use the `HTML5` convenction to use that plugin, so this is the code:

```
<div class="file-loading" >
    <input id="uploadPDF" type="file" class="file" data-theme="fas" data-allowed-file-extensions='["pdf"]' 
    data-language="it" data-type="POST" th:data-upload-url="@{/path/{id}/pdf(id=${myObject.id})}"/>
</div>
```
But I enabled the **CSRF** protection with Spring Security. So when I try to upload a pdf the result is:

`Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'.`

I would like to add the CSRF token using the HTML5 convection, so something like:

`<input .... th:data-token="${_csrf.token}"...>`

In this way I can avoid to use the javascript. Is it possible?

**Comment by kartik-v** [comment]
This is more related to other plugins/JS framework use. I am not sure how your other framework (Spring) works and how it uses javascript. The most trusted way is to use a javascript based initialization and remember the dependency and sequence in which your other framework plugins initialize and code accordingly.
