### ISSUE TITLE
When returning errors via errorKeys View Details shows no info in the dialog box

### ISSUE THREAD

**Issue by russellpettway** [kartik-v/bootstrap-fileinput#1215]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Upload say 7+ files. From the server return:
 { error: "Some Error", errorKeys: [3,5,7] }

## Expected behavior and actual behavior

When I follow those steps, 
 I click on "View Details" icon for one of the failed files I see blank dialog box no textarea.

I was expecting...
When I click on "View Details" icon for one of the failed files I would expect there to be a textarea with the file info. 

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- bootstrap-fileinput version: 4.4.8

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

![image](https://user-images.githubusercontent.com/2243600/38152829-1f53fd4c-342f-11e8-9e7e-a8d5ba8fddd3.png)

![image](https://user-images.githubusercontent.com/2243600/38152841-2e313a00-342f-11e8-985c-0bd715af150a.png)

**Comment by kartik-v** [comment]
Resolved via above commit.

**Comment by russellpettway** [comment]
Awesome! thanks, great plugin BTW!!
