### ISSUE TITLE
file-input-ajax-new class not getting added to hide remove button

### ISSUE THREAD

**Issue by wowpages** [kartik-v/bootstrap-fileinput#1218]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. copied code from demo - http://plugins.krajee.com/file-avatar-upload-demo#avatar-upload-1
2. using fa instead of glyphicon
3. view test page here - https://10kcrypto.com/profile-test-1

## Expected behavior and actual behavior

When I follow those steps, I see...
The remove button shows up by default because the file-input div does not include the class "file-input-ajax-new"

I was expecting...
The remove button should not show by default, as in the demo. The demo DOES include the class "file-input-ajax-new"
<img width="190" alt="screen shot 2018-04-08 at 8 07 29 pm" src="https://user-images.githubusercontent.com/294036/38477623-8b6f5784-3b68-11e8-948f-6f77f62af23c.png">

## Environment

Browsers

- [ x] Google Chrome
- [ x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Seems some problem with the earlier plugin version used here. Kindly update to release v4.4.8.
