### ISSUE TITLE
MaxFileSize 

### ISSUE THREAD

**Issue by apunkto** [kartik-v/bootstrap-fileinput#122]
Updated from 2.8.0 to 4.1.4 today and my fileinput does not use maxFileSize setting any more or there is a problem with throwing the max-file-size error. It shows the image in the preview box even if it is bigger then 200KB I've set. 

JS Debugger shows that the following is executed:

 self.isError = throwError(msg, file, previewId, i);

But no error shows up and invalid input can be saved. It was working just great before the update. Any idea what could be the reason?

Thanks!

```php
<?= $form->field ( $kasutaja, 'image' )->widget ( FileInput::classname (), 
[ 'options' => [ 'accept' => 'image/*' ],
'pluginOptions' => [ 'allowedFileExtensions' => [ 'jpg','gif','png' ],'showCaption' => false,'showRemove' => false,'showUpload' => false,'browseClass' => 'btn btn-primary btn-block','browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ','browseLabel' => 'Select image' , 'maxFileSize'=> 200,'initialPreview'=> [$preview]] ] )?>

```

**Comment by apunkto** [comment]
Oh, it seems following javascript error also occurs:

ReferenceError: formdata is not defined
var outData = self.getOutData(formdata, {}, files);
fileinput.js (line 1242, col 24)

**Comment by kartik-v** [comment]
You have an outdated release. Upgrade to release v4.1.5.
