### ISSUE TITLE
multiple form.. I think it is very useful because:

### ISSUE THREAD

**Issue by teoSalvetti** [kartik-v/bootstrap-fileinput#1222]
ok, it is not possible using multiple file within a form.. I read it...

 But I also think it is very useful it, for example, if I have to attach 2 files to an entity that I'm creating, if I use a form I create the entity (save it on db) and also attach the files. If I use the ajax instead I have to create and save the entity and the open another page to upload and attach the 2 files.

Is it not correct?

So, is it possible in somehow use the ajax upload with a form??
If not, why not develop a multiple version for the form?

**Comment by kartik-v** [comment]
> If not, why not develop a multiple version for the form?

Because HTML-5 does not support editing a native file input via javascript
