### ISSUE TITLE
dropZoneEnabled : false not working

### ISSUE THREAD

**Issue by BertHankes** [kartik-v/bootstrap-fileinput#1224]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. dropZoneEnabled : false
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
the Drag & Drop zone   (div class file-drop-zone)

I was expecting...
to hide (disable) the zone (div class file-drop-disabled)
## Environment

Browsers

- [X ] Google Chrome
- [X ] Mozilla Firefox
- [X ] Internet Explorer
- [ ] Safari

Operating System

- [ X] Windows
- [ ] Mac OS X
- [X ] Linux
- [X ] Mobile

Libraries

- jQuery version: 2.1.3
- bootstrap-fileinput version: 448

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x ] The bug happens consistently across all tested browsers
- [x ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Cannot reproduce your issue. You may need to check your code and configuration.

Check [basic demo example 6](http://plugins.krajee.com/file-basic-usage-demo#basic-example-6) or check [basic demo example 8](http://plugins.krajee.com/file-basic-usage-demo#basic-example-8) which have `dropZoneEnabled` set to `false`.
