### ISSUE TITLE
Files not sortable after file selection is done

### ISSUE THREAD

**Issue by nwafor-austine** [kartik-v/bootstrap-fileinput#1225]
After selecting all the file I want to upload I like to sort them before uploading them but this feature is not enabled how do I go about this?

**Comment by kartik-v** [comment]
Sorting of files is only available in the plugin for `initialPreview` thumbnails (i.e. already uploaded files).

You may need to program your app accordingly if you want to use that plugin feature. For example:

- you may return the `initialPreview` via the same server response (as set in `uploadUrl`) that processes your upload as mentioned in [ajax demo 4](http://plugins.krajee.com/file-input-ajax-demo/4) and [ajax demo 5](http://plugins.krajee.com/file-input-ajax-demo/5). This will make the preview content sortable.
- you may additionally/alternatively also trigger upload immediately once user selects a file or multiple files  as mentioned in [ajax demo 6](http://plugins.krajee.com/file-input-ajax-demo/6)
