### ISSUE TITLE
showBrowse: false removes file input field

### ISSUE THREAD

**Issue by wowpages** [kartik-v/bootstrap-fileinput#1226]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. set option showBrowse to false

## Expected behavior and actual behavior

When I follow those steps, I see...
the file input field is not added, because it is included within the browse button, so a file cannot be uploaded

```<div tabindex="500" class="btn btn-primary btn-file"><i class="fa fa-folder-open"></i> <input id="avatar-1" name="avatar-1" type="file"></div>```

I was expecting...
the file input field to be added

## Environment

Browsers

- [ x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ x] The bug happens consistently across all tested browsers
- [ x] This bug happens when using bootstrap-fileinput without other plugins
- [ x] I can reproduce this bug in [a jsbin](https://jsbin.com/)
http://jsfiddle.net/dn1nkk1h/14/

**Comment by kartik-v** [comment]
Fixed via above commit.
