### ISSUE TITLE
Hide preview if file not exist

### ISSUE THREAD

**Issue by teoSalvetti** [kartik-v/bootstrap-fileinput#1227]
I would like to hide the preview if I din't upload any file... 
But I want to show the preview if I uploaded previously a file.

Is it possible?

This is my code:
```
                  $("#fileCertificato2").fileinput({
				theme: "fas",
				language: "it",
			    maxFileSize: 5000,
			    maxFileCount: 1,
			    showClose: false,
			    showCaption: false,
			    elErrorContainer: '#upload_error',
			    msgErrorClass: 'alert alert-danger text-center',
			    allowedFileExtensions: ["pdf"],
		        initialPreviewAsData: true,
		        initialPreviewDownloadUrl:UrlToDownloadFile
		        initialPreview: [
		        	UrlToDownloadFile
		        ],
		        initialPreviewConfig: [
		            {
		            	type: "pdf", 
		            }
		        ],
		        purifyHtml: true, // this by default purifies HTML data for preview
			});	
```

**Comment by kartik-v** [comment]
What you require will happen automatically if you set `dropZoneEnabled` to `false`.

**Comment by teoSalvetti** [comment]
Maybe I didn't explain it clear enough..

I'm not using the ajax version, so I'm using the plugin inside a form.. and so I don't have the dropzone..

So, can I do it inside a form=

**Comment by teoSalvetti** [comment]
@kartik-v  ok, and I'm using it as you can see above.. But the first time I open the page, I don't have any file, ok?
So I don't want to show any preview, but I'll show the preview only after I uploaded a file..
This is what I want..

**Comment by kartik-v** [comment]
You need to program your code accordingly - set `initialPreview` only when you have a FILE to display - if no file on page load do not set `initialPreview`. After upload you need to write your own code - to refresh the plugin, or refresh page (or redirect) to show the initial preview.
