### ISSUE TITLE
Feature Request - Delete files through ajax.

### ISSUE THREAD

**Issue by nakarin4350** [kartik-v/bootstrap-fileinput#123]
I think it will be great if the extension is able to delete files that have just been uploaded through ajax.Cheers.

**Comment by kartik-v** [comment]
The plugin already offers this feature - by allowing you to set the delete URLs in `initialPreviewConfig`. The `initialPreviewShowDelete` property allows you to set whether you wish to enable delete functionality (defaults to true). Check [docs](http://plugins.krajee.com/file-input).

**Comment by nakarin4350** [comment]
Sorry for my english.I mean deleting files after ajax upload(eg. click upload button),so people no need to go another page that have set  initialPreviewShowDelete=true.

**Comment by kartik-v** [comment]
If you need individual file delete button for each thumbnail you need to use the initial preview settings as mentioned.

If you just need a delete button, the developer can add his/her own button to the template to delete all files and could control its display using events after file is uploaded e.g. `fileuploaded`.

**Comment by nakarin4350** [comment]
I get it now,thanks for your time and sharing.

**Comment by bhattaxay** [comment]
Are you passing id for delete like in this way right?

 '{caption: "'.$eachimage['albummediaCaption'].'", size: '.$size.', height: "120px", url: "http://localhost/wastetalent/backend/web/index.php/albummedia/delete", key: '.$eachimage['albummediaID'].',  extra: "{id: '.$eachimage['albummediaID'].'}"},';`
