### ISSUE TITLE
CDN link doesn't exist

### ISSUE THREAD

**Issue by zunjae** [kartik-v/bootstrap-fileinput#1233]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. visit any of the links in https://github.com/kartik-v/bootstrap-fileinput#usage that contains `4.4.9`

The error I am getting is `404 Not Found`

using version 4.4.8 does work.

**Comment by kartik-v** [comment]
Latest stable release as of today 01-May-2018 is v4.4.8.

Version 4.4.9 is under development and will not be available on CDN until a stable release is tagged.

**Comment by zunjae** [comment]
Then why do you include 4.4.9 in the readme when it isn't stable nor released?

**Comment by zunjae** [comment]
It literally does NOT work

**Comment by kartik-v** [comment]
Note that I do not maintain the code maintained externally in CDN repo. It is done automatically by the CDN source pulling it from here for stable releases. I suppose you should be able to see the stable releases of the code in this repo by going to the releases section.

I only own and drive the source code in this repo and not elsewhere beyond this. Normally for developers the latest stable code is automatically installed via bower or composer package managers. Read [plugin documentation on how you install the code for your app](http://plugins.krajee.com/file-input#installation)

Read the [CHANGE LOG](https://github.com/kartik-v/bootstrap-fileinput/blob/master/CHANGE.md) for details on the releases and timelines.
