### ISSUE TITLE
Clear field on fileerror using $(this)

### ISSUE THREAD

**Issue by itajackass** [kartik-v/bootstrap-fileinput#1237]
I'd like to clear file input when a fileerror event is fired.
My inputs file are dinamically generated by a button. No id, no class and the name is generated by another script.

    $(document).ready(function(){
     $("#btn").on("click", function(e) {

      var fileInput = "<input type='file' name='randomNameGenerated'>";
      $("body").append(fileInput);
      $(fileInput).fileinput({'showPreview':false, 'showUpload':false, allowedFileExtensions: ["jpg"]}).on('fileerror', function(event, data, msg) { $(this).fileinput('clear'); $.alert(msg); });

     });
    });

It seem $(this).fileinput('clear'); doesn't work in this case.

**Comment by kartik-v** [comment]
You may need to check your code. Initializing the fileinput on the ID or name attribute or CSS selector maybe beneficial.

```js
$('#randomId').fileinput(opts); // markup:<input type="file" id="randomId">
// OR
$('input[name="randomName]').fileinput(opts); // markup: <input type="file" name="randomName">
// OR
$('.random-css').fileinput(opts); // markup: <input type="file" class="random-css">
```
