### ISSUE TITLE
Drop zone not enabled on IE 11 (due to input.files readonly)

### ISSUE THREAD

**Issue by FGIKCM** [kartik-v/bootstrap-fileinput#1242]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

https://jsbin.com/zidaxis/edit?html,js,output

## Expected behavior and actual behavior

With no modification of my code, this library stopped working with latest IE 11: the drop zone is now hidden, only the submit file part is visible.

After digging, it is because of:
```javascript
input.files = null;
```
in `canAssignFilesToInput()` function.

An error is thrown that we can't modify read-only properties in strict mode.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [X] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- bootstrap-fileinput version: 4.4.8 + @dev

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Fixed via latest commit.
