### ISSUE TITLE
How to enable the glyphicons effect?

### ISSUE THREAD

**Issue by youyiyang** [kartik-v/bootstrap-fileinput#1243]
Hi all,

i am using this great code to do a file input. Everything is OK except that the UI's CSS style is not effective. I attach the UI view to you, you can see that the glyphicons word style is not effective. i have downloaded the glyphicons from its website and put them into the folder called fonts. i will attach below code and the Eclipse IDE picture and any suggestions would be very helpful.

![css](https://user-images.githubusercontent.com/12582219/40299609-6e977e7a-5d19-11e8-81c3-320f2e9172b3.png)
![main1](https://user-images.githubusercontent.com/12582219/40299610-6ed01aa0-5d19-11e8-9457-9a2d83c951a4.png)

<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="css/fileinput.min.css" rel="stylesheet" type="text/css"/>
<script src="js/jquery-1.11.3.min.js"></script>
<script src="js/fileinput.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/zh-cn.js"></script>
<link href="css/font-awesome.css" rel="stylesheet" type="text/css"/>

**Comment by youyiyang** [comment]
`
<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta charset="UTF-8"/>
<title>web.com 图片上传服务器</title>

<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="css/fileinput.min.css" rel="stylesheet" type="text/css"/>
<script src="js/jquery-1.11.3.min.js"></script>
<script src="js/fileinput.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/zh-cn.js"></script>
<link href="css/font-awesome.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<input id="input-711" name="file" type="file" multiple class="glyphicon glyphicon-user" /><p><input type="button" text="man" id="btn1" name="btn1" class="glyphicon glyphicon-user"/></p>
<script>
$("#input-711").fileinput({
	uploadUrl: "upload.do",
	uploadAsync : true,
	maxFileCount: 1000,
	showBrowse: false,
	browseOnZoneClick: true
});
</script>
</body>
</html>
`

**Comment by youyiyang** [comment]
i dont why my code is so short?

**Comment by kartik-v** [comment]
You need to check your code and HTML markup. You need to load the CSS files for fileinput and glyphicons in the right order.

**Comment by youyiyang** [comment]
`<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta charset="UTF-8"/>
<title>web.com 图片上传服务器</title>
<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="css/fileinput.css" media="all" rel="stylesheet" type="text/css"/>
<link href="css/solid.css" rel="stylesheet" type="text/css"/>
<link href="css/font-awesome.css" rel="stylesheet" type="text/css"/>
<link href="css/all-krajee.min.css?ver=201710271504" rel="stylesheet" type="text/css"/>



<script src="js/jquery-1.11.3.min.js" type="text/javascript"></script>
<script src="js/plugins/sortable.js" type="text/javascript"></script>
<script src="js/all-krajee.min.js" type="text/javascript"></script>
<script src="js/fileinput.min.js" type="text/javascript"></script>
<script src="themes/gly/theme.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type="text/javascript"></script>

</head>
<body>
<div class="file-loading">

<input id="file" name="file" type="file" multiple />

</div>
<script>
$("#file").fileinput({
	
	uploadUrl: "upload.do",
	uploadAsync : true,
	maxFileCount: 1000,
	showBrowse: false,
	browseOnZoneClick: true
});
</script>
</body>
</html>`

**Comment by youyiyang** [comment]
above is the html code that i wrote. And would u please suggest that which parts are wrong?
And now the UI is like below picture:

**Comment by youyiyang** [comment]
![default](https://user-images.githubusercontent.com/12582219/40475716-d3de724a-5f74-11e8-9f03-5328179309e2.png)
