### ISSUE TITLE
security issue while using composer

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [kartik-v/bootstrap-fileinput#1244]
Getting the following security issue while using composer.

`[Composer\Repository\RepositorySecurityException]                                                                                                                                                        
  The contents of http://packagist.org/p/provider-2017%24e49576dcbe2f5e29558d3643a993b533eab5a630c99bcffaf2feab4ba313ecd8.json do not match its signature. This should indicate a man-in-the-middle attac  
  k. Try running composer again and report this if you think it is a mistake.  `

Thanks,

**Comment by youyiyang** [comment]
Try to do below actions and this may help you to solve your problem:
https://stackoverflow.com/questions/18977581/composer-update-man-in-the-middle-attack-error

**Comment by kartik-v** [comment]
Not sure I can reproduce. Let know if anything to be done in this repo and will reopen it.
