### ISSUE TITLE
Preview of document is blank on IE

### ISSUE THREAD

**Issue by llj-A** [kartik-v/bootstrap-fileinput#1245]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ *] Internet Explorer

Operating System

- [ ] Windows

Libraries

- jQuery version:
- bootstrap-fileinput version: v4.4.1

the PDF document can uploaded successfully,but the IE browser Prompt error(Adobe PDF document: Access denied)
the Preview image in IE (src="blob:754277D7-72B4-4041-BA09-2F5EA3A3AA46") 
the Preview image in chrome (src="blob:http://10.82.0.101:8085/754277D7-72B4-4041-BA09-2F5EA3A3AA46")

**Comment by kartik-v** [comment]
On IE - you need PDF reader browser plugin to view PDF files.
