### ISSUE TITLE
in laravel admin i got delete button while previewing but deleting the single image other images not saved in the database

### ISSUE THREAD

**Issue by periyakannan** [kartik-v/bootstrap-fileinput#1246]
## Prerequisites

i having the latest  version laravel admin extension but  i got delete button while previewing but deleting the single image other images not saved in the database
 #![2018-05-25-110219_1366x768_scrot](https://user-images.githubusercontent.com/38691572/40527886-34429b60-600c-11e8-81bb-699efd05b573.png)

what have to do @kartik-v pls answer ...
## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Not sure whether I understand your issue, but it seems it some issue you are facing with deletion of image. You need to handle this in your server code (Laravel) - i.e. the `deleteUrl` which handles the delete operation.
