### ISSUE TITLE
能支持HTML5的slice切割大文件上传吗

### ISSUE THREAD

**Issue by Hzhihua** [kartik-v/bootstrap-fileinput#1249]
能支持HTML5的slice切割大文件上传吗

**Comment by kartik-v** [comment]
It is possible however requires some different bit of changes to be done both on plugin and mainly your server side code to handle file chunking or resume uploads. Feel free to add a PR if you desire.

**Comment by kartik-v** [comment]
Duplicate to #290.  Planned for release v5.0.0 milestone.
