### ISSUE TITLE
Plugin Option - rounded-0

### ISSUE THREAD

**Issue by matmiranda** [kartik-v/bootstrap-fileinput#1251]
It would be cool if you put another `rounded-0` option. Example:

```
$(document).on('ready', function() {
  $("#input_id").fileinput({
    rounded_0: true
  });
});
```

In the documentation has class `rounded-0`:

https://getbootstrap.com/docs/4.1/utilities/borders/

Make all the elements as "squares". I like the square window :)

**Comment by makshh** [comment]
These kind of things you should change in CSS, not JavaScript, eg.:

```css
.file-preview {
  border-radius: 0;
}
```

**Comment by matmiranda** [comment]
@makshh  

For input does not work, I want to put all as squares.

**Comment by kartik-v** [comment]
@matmiranda I understand where you are getting from - but I think styling must typically be done via CSS and not a good practice to do via javascript. 

There is the SCSS / SASS source code given for the bootstrap-fileinput default styles as well as theme styles.

I recommend, the simplest way to handle this for your use case is to just create your own theme CSS and/or JS and use the theme CSS file to override.

This way you can toggle styles at your will in your application by just setting the `theme` property. Check the [Explorer FA 5 theme](http://plugins.krajee.com/file-krajee-explorer-fas-demo) provided with the plugin for instance - you can override styles in a similar theme way.

For example you create a theme `flat` and then override the relevant styles this way (the plugin will append the `theme-flat` CSS class to the main container for you to override all element styles this way:

```js
.theme-flat .file-preview {
    border-radius: 0;
}
.theme-flat .btn {
    border-radius: 0;
}
```

This way just set the `theme` property in the plugin to `flat` and load the theme file after `fileinput.css` and you are done.
