### ISSUE TITLE
PDF Preview on iPad

### ISSUE THREAD

**Issue by oadam** [kartik-v/bootstrap-fileinput#1254]
Hi and thanks a lot for this plugin !
I'm having an issue when previewing pdfs on ipads

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Navigate to http://plugins.krajee.com/file-basic-usage-demo with an ipad
2. Select a pdf and check the preview
3. See that the preview is not scrollable and has a weird aspect ratio

This is a well known issue with pdf embedding on ipad (https://stackoverflow.com/questions/15854537/make-embedded-pdf-scrollable-in-ipad/).

Seems like the easiest workaround would be using https://mozilla.github.io/pdf.js/ when previewing on ipad.

What do you think ?

**Comment by kartik-v** [comment]
Am open to suggestions. Feel free to add a PR if you wish.

**Comment by oadam** [comment]
Since this is a major annoyance for my company, we'd be ready to sponsor this development.
@kartik-v Is this something you (or someone you know) would be open to ?

**Comment by oadam** [comment]
an alternative would be opening a bounty on https://www.bountysource.com/

**Comment by kartik-v** [comment]
Thanks - I have enabled *bountysource* 
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/59622417-pdf-preview-on-ipad?utm_campaign=plugin&utm_content=tracker%2F638288&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F638288&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by denim2x** [comment]
I've started some work [here](https://github.com/denim2x/bootstrap-fileinput/tree/pdf.js)

**Comment by kartik-v** [comment]
Thanks @denim2x I had started this aas well and will be posting a fix soon.

**Comment by kartik-v** [comment]
This has been fixed via the commit 7ee4578. The following are the new properties available in the plugin (refer the updated plugin docs and demos):

### New plugin options

- [usePdfRenderer](http://plugins.krajee.com/file-input/plugin-options#usePdfRenderer) - check how it can be enabled only for iOS devices
- [pdfRendererUrl](http://plugins.krajee.com/file-input/plugin-options#pdfRendererUrl) 
- [pdfRendererTemplate](http://plugins.krajee.com/file-input/plugin-options#pdfRendererTemplate) 

### Updated demo for PDF rendering

- [PDF Preview Demo](http://plugins.krajee.com/file-preview-management-demo#preview-pdf)
