### ISSUE TITLE
Base64 PDF Files freezing computer

### ISSUE THREAD

**Issue by paguii** [kartik-v/bootstrap-fileinput#1255]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Get Base64 pdf files add to an array.
2. Set this array to be the the initialPreview.
3. This starts to freeze my computer and takes like 30 minuts to go back to normal.
4. The bigger the file, the problem comes faster.

Hypothesis:
The browser start to preview all the pdf files, it may taking too much memory or the overloading the processor? 
![captura de tela de 2018-06-14 11-43-04](https://user-images.githubusercontent.com/18687395/41419334-24c77f2c-6fc8-11e8-834a-131404030b58.png)

My code:

function documentoTransportadoraA(id){
	if (($('#loading').data('bs.modal') || {}).isShown){
		$('#loading').modal('toggle');
	}

	$.ajax({
		url:"/imaged/alteraranexo",
		method:'POST',
		dataType: 'json',
		data: {
			id: id,
			tipo: 't'
		}
	}).done(function(resultado){
		$('#modalDocumentos').modal({
			backdrop: 'static',
			keyboard: false}
		);

		$('#uploader').removeClass('hide');

		if (resultado.preview[0]){

			$('#arquivo').fileinput('destroy');

			$('#arquivo').fileinput({
				uploadExtraData: {
					id: id,
					tipo: 't'
				},
				uploadAsync: true,
				uploadUrl: "/imaged/anexar",
				allowedFileExtensions: ['pdf', 'jpg','bmp','png','gif','jpeg','tif','tiff', 'jif', 'jfif'],

				initialPreview: resultado.preview,
				initialPreviewConfig: resultado.previewconfig,
				initialPreviewAsData: true,

				msgSizeTooLarge: 'Arquivo "{name}" (<b>{size} KB</b>) excede o tamanho máximo de upload permitido <b>{maxSize} KB (1MB)</b>.',
			});

		}else{

			$('#arquivo').fileinput('destroy');

			$("#arquivo").fileinput({
				uploadAsync: true,
				uploadUrl: "/imaged/anexar",
				uploadExtraData: {
					id: id,
					tipo: 't'
				},
				allowedFileExtensions: ['pdf', 'jpg','bmp','png','gif','jpeg','tif','tiff', 'jif', 'jfif'],

				initialPreviewAsData: true,
				initialPreview: resultado.preview,
				initialPreviewConfig: resultado.previewconfig,

				msgSizeTooLarge: 'Arquivo "{name}" (<b>{size} KB</b>) excede o tamanho máximo de upload permitido <b>{maxSize} KB (1MB)</b>.',

				overwriteInitial: false,

				previewSettings:{
					image: {
						width: "auto",
						height: "160px"
					},
				},
				previewZoomSettings: {
					image: {
						width: "auto",
						height: "auto"
					},
				},
			});

		}
	});

}

$("#arquivo").fileinput({
	uploadAsync: false,
	uploadUrl: "/imaged/anexar",
	allowedFileExtensions: ['pdf', 'jpg','bmp','png','gif','jpeg','tif','tiff', 'jif', 'jfif'],

	overwriteInitial: false,

	previewSettings: {
		image: {
			width: "auto",
			height: "160px"
		},
	},
	previewZoomSettings: {
		image: {
			width: "auto",
			height: "auto"
		},
	},
}).on('filebatchuploadcomplete', async function(event, files, extra){
	if (($('#loading').data('bs.modal') || {}).isShown){
		$('#loading').modal('toggle');
	}

	documentoTransportadoraA(extra.id);

	await sleep(2500);
	alerta("Arquivo(s) carregado(s) com sucesso.");
});

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- bootstrap-fileinput version: 4.3.5

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
You need to program and code this in your app in the most optimal way. As you mentioned you are trying to embed base64 data in initial preview and it naturally will require resources to perform based on size of data and will be limited by browser / client memory. You may need to use a PDF link method or even contemplate hiding preview and showing icons if you have large data.
