### ISSUE TITLE
Why is the file upload progress bar not good

### ISSUE THREAD

**Issue by SeigeC** [kartik-v/bootstrap-fileinput#1256]
Why is the file upload progress bar not good？When I click upload, the progress bar will not be displayed until the file is uploaded！Please tell me why, thank you！！！

**Comment by kartik-v** [comment]
Cannot reproduce or understand your issue. Please create/share a [JS Fiddle](https://jsfiddle.net/) of your code / config to understand.

**Comment by SeigeC** [comment]
could you tell you how can the file upload progress entries take effect

**Comment by SeigeC** [comment]
<form id="input-glyform1">                             
<input name="uploadFile" type="file" id="input-gly1" multiple class="file-loading" />
</form>
$("#input-gly1").fileinput({
language: 'zh', 		             
uploadUrl:"upLoadimg",	                   
uploadExtraData:function(e){
return {'versionid':version_id};
 },
});
