### ISSUE TITLE
allowedFileExtensions not work

### ISSUE THREAD

**Issue by hamedkhorasani** [kartik-v/bootstrap-fileinput#1258]
allowedFileExtensions and maxFileSize not work when use .on("filebatchselected"),

var inputFile = $("#file-0d");

inputFile.fileinput({
var inputFile = $("#file-0d");`
inputFile.fileinput({

	uploadUrl: "/uploadFile/", // your upload server url
	uploadExtraData: function(previewId, index) {
		var data = {};
		var name = $("input[id='upload11']").attr('name');
		var deleteuploadname = $("input[id='deleteupload11']").attr('name');
		data[name] = $("input[id='upload11']").val();
		data[deleteuploadname] = $("input[id='deleteupload11']").val();
		return data;
	},
	
	theme: 'fas',
	language: 'ar',
	rtl: true,
	overwriteInitial: false,
	maxFileSize: 10000,
	showClose: false,
	showCaption: false,
	showRemove: false,
	browseIcon: '',
	removeIcon: '',
	browseLabel: 'new upload,
	removeLabel: 'remove',
	removeTitle: 'remove',
	maxFilesNum: 1,
	maxFileCount: 2,
	validateInitialCount: true,
	uploadAsync: false,
	browseOnZoneClick: true,
	//allowedFileTypes: ['image', 'video', 'flash'],
	allowedFileExtensions: ['jpg','png','gif','xls','xlsx','doc','docx', 'zip', 'rar', 'mp4'],
	slugCallback: function (filename) {
		return filename.replace('(', '_').replace(']', '_');
	},
	
	
	initialPreviewAsData: true,
	initialPreviewFileType: 'image', // image is the default and can be overridden in config below
	append: true,
	
}).on("filebatchselected", function(event, files) {
	inputFile.fileinput("upload");
});

**Comment by kartik-v** [comment]
Not able to reproduce your issue. Please check if you have the latest version of the extension and post a JS Fiddle to reproduce your issue.
