### ISSUE TITLE
"filedeleted" event doesn't work

### ISSUE THREAD

**Issue by superman00** [kartik-v/bootstrap-fileinput#1259]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.When I checked the file and showed it in the preview area, and the picture is not upload.
2.Then I click the remove button on the picture, 
3.Then it will trigger which event of fileinput

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by BaBL86** [comment]
According to code:

```
if (self.isAjaxUpload) {
                out = template.setTokens({
                    'actions': self._renderFileActions(upl, false, rem, zoom, drg, false, false, false),
```
after Ajax there is `false` instead of `key` value hardcoded to the render and button Remove doesn't work.

**Comment by BaBL86** [comment]
After some investigation, I find my problem with remove button. Don't know is this relate to this issue, but may be I help someone: the problem is in this code:
```
                content = out.initialPreview || [];
                config = out.initialPreviewConfig || [];
                tags = out.initialPreviewThumbTags || [];
```
after ajaxUpload. My backend return initialPrevieConfig as assoc array, JS converts it to Object and than there is an merge of array and object, where object disappears:
```
                self._mergeArray('initialPreview', content);
                self._mergeArray('initialPreviewConfig', config);
                self._mergeArray('initialPreviewThumbTags', tags);
```

In my case there is a fix on backend. Need to put assoc array to new one:

```
            return [
                'append' => true,
                'initialPreview' => $aiu->getPhotoAdm(),
                'initialPreviewConfig' => [[
                    'caption' => $aiu->name
                    , 'size' => $aiu->size
                    , 'url' => Url::to(['/apart-image/async-del', 'id' => $aiu->apart_id])
                    , 'key' => $aiu->id
                ]],
            ];
```
