### ISSUE TITLE
Urgent Help Needed: How to start batch upload from my own button

### ISSUE THREAD

**Issue by dalamberts** [kartik-v/bootstrap-fileinput#126]
I am hiding the upload button because I want to use another button on our form to initiate the upload process.  I search around and could not find any hints or answers.  Any help you would provide would be greatly appreciated!

**Comment by kartik-v** [comment]
You can change the templates. Check the documentation for various sections in the `layoutTemplates` property to render your own button for the upload.

**Comment by dalamberts** [comment]
I added my submit button based on what is created from the template as follows but it did not work:
<button type="button" class="btn btn-default kv-fileinput-upload fileinput-upload-button" id="submit_test">Submit</button>
Is there something else I would have to do?  Would I just call the uploadBatch function inside the plugin?  If so, how exactly would that call look?

**Comment by kartik-v** [comment]
You need to note a couple of things

- **You do not set an uploadUrl:** This means you are using a form based submission (without using ajax). If you can set this, then you pretty much have everything for your use case (but will not get the ajax upload features of progress etc.). In this case you can go ahead and submit the form (with any button anywhere) and read values from the file input if it exists or other form inputs

- **You set an uploadUrl:** This is if you are using ajax based uploads - the plugin does not directly interact with form submission in this case and submits its own ajax post request. You need to work through your design and use plugin events or others to manage your data.

**Comment by dalamberts** [comment]
$(document).on('click', '#submit_test', function(event, data) {
$('#file4').fileinput('uploadBatch');
        });

**Comment by dalamberts** [comment]
That worked for a single file but it did not work for multiple files...Any ideas?

**Comment by dalamberts** [comment]
Just sends the last file selected...

**Comment by dalamberts** [comment]
BTW, I set the uploadUrl
