### ISSUE TITLE
fileInput ajaxSettings beforesend seems not to work

### ISSUE THREAD

**Issue by grath10** [kartik-v/bootstrap-fileinput#1260]
## Steps to reproduce the issue

$("#input-file").fileinput({
            showPreview: false,
            uploadAsync: false,
            elErrorContainer: '#kartik-file-errors',
            allowedFileExtensions: ['xls', 'xlsx'],
            uploadUrl: '/system/task/uploadfile',
            maxFileCount: 1,
            ajaxSettings: {
                beforeSend: function (xhr) {
                    var token = $('#_csrf').attr('content');
                    var header = $('#_csrf_header').attr('content');
                    if (token && header) {
                        xhr.setRequestHeader(header, token);
                    }
                }
            }
        });

## Expected behavior and actual behavior
When I try to insert the break point in the beforeSend function in the option ajaxSettings, it doesn't seem to work, however, if I degrade the version to 4.3.6, it works.
Any suggestion on my option is helpful if I do not want to change the fileinput version , still want the latest version. Thx!

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox

Operating System

- [ ] Windows

Libraries

- jQuery version: 2.2.3
- bootstrap-fileinput version: v4.4.8

## Isolating the problem

- [ ] The bug happens consistently across all tested browsers

**Comment by kartik-v** [comment]
Please share a JS Fiddle to reproduce your issue and test.

**Comment by tobias-neubert** [comment]
Hi,

I have currently the same problem. I would like to add an authorization header to the upload request but don't know how. I stumbled across this issue and the ajaxSettings property (which, by the way, I could not find in the documentation) and use it like this. but it will never reach the beforeSend method:

`$("#fileInput").fileinput({
        theme: "fa",
        uploadUrl: "http://localhost:2002/admin/upload",
        hideThumbnailContent: true,
        showUpload: false,
        showUploadedThumbs: false,
        maxTotalFileCount: 5,
        allowedFileExtensions: ['csv'],
        overwriteInitial: true,
        initialPreviewAsData: false,
        maxFileSize: 10000,
        removeFromPreviewOnError: true,
        fileActionSettings: {
          showUpload: false,
          showZoom: false
        },
        ajaxSettings: {
          beforeSend: function (xhr) {
            console.log("Hallooooo");
            xhr.setRequestHeader('Authorization', 'Bearer ' + _this.$store.state.keycloak.token);
          }
        }
      })`

Please can you explain to me how I can set a header before the request is sent?
Thank you,
Tobias

**Comment by tobias-neubert** [comment]
I found the solution: It is not sufficient enough to only set the ```ajaxSettings``` properties, you have to tell the plugin additionally to merge these settings with jqueries own settings like so:

```
        mergeAjaxCallbacks: true,
        ajaxSettings: {
          beforeSend(xhr, settings) {
            console.log("Hallooooo");
            xhr.setRequestHeader('Authorization', 'Bearer ' + _this.$store.state.keycloak.token);
          }
        }
```

**Comment by kartik-v** [comment]
Yes these are documented in the plugin docs. Check [ajaxSettings](https://plugins.krajee.com/file-input/plugin-options#ajaxSettings) and [mergeAjaxCallbacks](https://plugins.krajee.com/file-input/plugin-options#mergeAjaxCallbacks). You can also set advanced settings via `mergeAjaxCallbacks` as highlighted.
