### ISSUE TITLE
get Cover Mp3 File and Set background FileInput

### ISSUE THREAD

**Issue by omd166** [kartik-v/bootstrap-fileinput#1262]
How to get Cover Sound File (MP3) when choese for upload and set backgrand Fileinput???
It looks like this address
https://soundcloud.com/upload

this in url sample get cover by jquery!!!
https://github.com/aadsm/JavaScript-ID3-Reader

but i need get cover by Fileinput

**Comment by kartik-v** [comment]
Reading mp3 tags  is not directly in scope of the plugin but you can use plugin events and use the third party library to parse additional data send this data at runtime via <code>uploadExtraData</code>.
