### ISSUE TITLE
upload() will empty filestack

### ISSUE THREAD

**Issue by nicewahson** [kartik-v/bootstrap-fileinput#1263]
Google Chrome
 Windows
- jQuery version: v2.1.4
- bootstrap-fileinput version: 4.3.6
when i handle upload() in filebatchselected handler, the filestack in the code may be empty with undefined, code is below
<pre>
self_el.fileinput({
                    language: 'zh',
                    uploadUrl: '...'
                    maxFileCount: 1
                }).on("filebatchselected", function(event, files) {
                   ...
                            self_el.fileinput("upload");
                        
                    }).fail(function(resp) {
                        self_el.fileinput("upload");
                    });

                })
</pre>

and also, i found something  on this site(http://plugins.krajee.com/file-input#usage).First, i select one image, and then click the upload button, and then i can select another 5 images, but the property maxFileCount was setted 5. I think it may be a bug.
![image](https://user-images.githubusercontent.com/15240937/42308533-6b3ed85a-8068-11e8-8744-f7932ac4f307.png)

**Comment by dkingofpa** [comment]
With regards to the maxFileCount option, that refers to the max number of files that can be uploaded at once.  Not the total number of files.

So if maxFileCount is 5, I can add 5 files, click upload, and then add another 5 files and click upload.  So far, that would be 10 total files uploaded.  I can keep adding and uploading files as long as I don't try to add more than 5 files at once.

**Comment by kartik-v** [comment]
Yes as @dkingofpa mentioned - but there is a bit of update. @nicewahson you may need to go through the docs once.

The [`maxFileCount`](http://plugins.krajee.com/file-input/plugin-options#validateInitialCount) refers to only for files selected from the client. However the plugin provides an additional property [`validateInitialCount`](http://plugins.krajee.com/file-input/plugin-options#validateInitialCount). If this is set to `true`, then the plugin will do the `maxFileCount` and `minFileCount` validation based on files already uploaded and configured within `initialPreview` and `initialPreviewConfig`. So if you need to validate files already uploaded in your max file count validation - you need to update and correctly set the `initialPreview` after upload to the number of files uploaded and set `validateInitialCount` to `true`
