### ISSUE TITLE
Allow configurable file actions as a callback

### ISSUE THREAD

**Issue by wndayday** [kartik-v/bootstrap-fileinput#1264]
I want to show the zoom button for video/and img only. And disable/hide zoom button for other file type.
How?

**Comment by kartik-v** [comment]
Resolved via [this major upgrade to release v5.0.0](https://github.com/kartik-v/bootstrap-fileinput/commit/d635155749059accbd68e272fdcde686f3115257) well ahead of time.

- Allow configurable file actions as a callback. 
    - The `showXXX` properties in `fileActionSettings` ca3n now be setup as a callback.
    - Can read any property from the `initialPreviewConfig` for initial preview thumbnails
- Refer resumable uploads / chunk uploads [documentation here](http://plugins.krajee.com/file-input#ajax-resumable)
- Refer [resumable uploads demos](http://plugins.krajee.com/file-resumable-uploads-demo)
- Refer [enhancements and features closed in 5.0.0 release milestone](https://github.com/kartik-v/bootstrap-fileinput/milestone/1?closed=1)
