### ISSUE TITLE
Set caption event

### ISSUE THREAD

**Issue by GHopperMSK** [kartik-v/bootstrap-fileinput#1265]
Hello

Yii2 view with the code:

    <?= $form->field($model, 'uploadedFile')->widget(FileInput::className(), [
        'options' => [
            'accept' => 'image/*',
            'multiple' => false
        ],
        'pluginOptions' => [
            'showPreview' => true,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => false,
            'initialCaption' => $model->logo,
            'initialPreview' => $model->logo ? [Html::img($model->getLogoUrl(), [
                    'style' => 'width: auto; height: auto; max-width: 100%; max-height: 100%'
                ]
            )] : [],
            'layoutTemplates' => [
                'caption' => "<div class='file-caption form-control {class}' tabindex='500'>\n" .
                    "    <span class='file-caption-icon'></span>\n" .
                    "    <input type='text' name='{$model->formName()}[uploadedFileName]' class='file-caption-name' />\n" .
                    '</div>',
            ],
        ],
        'pluginEvents' => [
                "fileloaded" => "function(event, file, previewId, index, reader) { console.log(file); $('INPUT.file-caption-name').get(0).value = 'test'; }",
        ],
    ]); ?>

All I want is single image with editable caption.Tell me please, where is the event, which set the caption? I would like to cut extension, replace special chars and make it lowercase. POST data only, there isn't ajax.
[Demo 7](http://plugins.krajee.com/file-input-ajax-demo/7) is great, but even there I didn't find the clue...

**Comment by kartik-v** [comment]
Just set the property [`slugCallback`](http://plugins.krajee.com/file-input/plugin-options#slugCallback) of the plugin as a JS callback to process the filename caption. Note within Yii you need to use `yii\web\JsExpression` to escape JS callback functions within `pluginOptions`.
