### ISSUE TITLE
How to upload files with android version 4.4 or higher

### ISSUE THREAD

**Issue by angelmdh** [kartik-v/bootstrap-fileinput#1266]
My project uses fileinput to upload files.
It can work on IE, chrome, IOS systems 
However, when uploading using the gallery on the android phone, it will not be uploaded.
It is necessary to use the camera to directly capture the upload to capture the image file.
I found some information and found that the mobile phone with Android version over 4.4 would have such a situation.
How do I need to modify the program?

**Comment by kartik-v** [comment]
It is more to do with Android's parsing of the HTML File Input markup and is unfortunately out of scope of this plugin. As you said it seems to be a [known issue in Android 4.4.](https://issuetracker.google.com/issues/36983532).

Refer the following SFO post to maybe help you:

 [Gallery not shown on Android HTML File Input](https://stackoverflow.com/questions/40304870/html-file-input-on-android-5-1-1-doesnt-show-gallery)

Currently closing this as it is more related to HTML native file input support in Android . If you feel there is anything that can be done within this plugin - do update to reopen.
