### ISSUE TITLE
Freeze on FireFox and IE11

### ISSUE THREAD

**Issue by nim** [kartik-v/bootstrap-fileinput#1267]
Full freeze then i open several images in resize mode.

**Comment by nim** [comment]
You can use this example http://plugins.krajee.com/file-image-management-demo#image-resize-width, but with multi file options. And select several images 5mb+.

**Comment by nim** [comment]
FireFox and IE11 freezes, does not show progress bar.

**Comment by kartik-v** [comment]
Will check when I get time. But I think this is more of designing your app correctly to optimize client side performance. 

Note that resizing of images via the plugin is done at client end and uses client/browser resources to resize which would be limited for LARGE VOLUME/LARGE SIZE files. Normally such performance intensive operations must be done on server end. To optimize your app design you need to do one of the following:

- If you are keen to use the client side resizing - to optimize for various client browsers and memory needs, you may need to configure plugin to restrict number of files using `maxFileCount` and also set the `maxFileSize` of files to allow processing in a saner maner
- Alternatively do your file resizing on the server side - do not set size limitations on the client and let files be uploaded and you handle the file resizing in batch mode (asynchronous) on your server end.
- Performance boost on clients for large number of files can also be made when you disable preview via `showPreview` set to `false` OR you use iconic previews as shown in [this demo](http://plugins.krajee.com/file-preview-management-demo#preview-iconic)

**Comment by kartik-v** [comment]
Am closing this as no fix - as this is more a configuration of the JAVASCRIPT code for your application and choosing the right plugin settings. In case you have suggestions please update to reopen.

**Comment by nim** [comment]
I need to reduce the load on the server. And on the other hand, do not limit the size of the files. Because users make photos as they are used to. You can not close it. In chrome everything works well. But in other browsers not. Do not be lazy where there are problems.

**Comment by kartik-v** [comment]
I unfortunately do not see at this stage anything which can be done for this via the plugin - other than the options which already exist to control the file size and count. 

I am open for any suggestion from you or anyone where you can suggest that this can be amazingly done through a JS code in this plugin which can control the IE11 and Firefox browser memory issues.
