### ISSUE TITLE
Single excel file upload gives error "SyntaxError: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by theTeaGreen** [kartik-v/bootstrap-fileinput#1268]
Hi Kartik

I'm having trouble finding the solution for the error "SyntaxError: Unexpected token < in JSON at position 0" which occurs on single excel file upload. My server code must be correct because it works with ordinary file input (stores the file as it's supposed to). I've followed docs and demos and couldn't find what I'm doing wrong. Here is my code:

januaryDownloadBtn = '<button type="button" id="januaryDownloadBtn" class="btn btn-xs btn-default"><i class="glyphicon glyphicon-download"></i></button>';

$('#januaryFile').fileinput({ 
    uploadAsync: false, 
    initialPreview: [@if(!empty($januaryFile))"January_final.xlsx"@endif], 
    initialPreviewConfig: [ {previewAsData: false, size: 576237, caption: "file.xls", width: "120px"}, ], 
    initialPreviewAsData: true, previewFileIcon: '<i class="fa fa-file-excel-o text-success"></i>', 
    uploadIcon: '<i class="fa fa-upload"></i>', uploadClass: 'btn btn-success', uploadUrl: "{{route('admin.upload-file', 'january')}}", 
    autoReplace: true, 
    maxFileCount: 1, 
    otherActionButtons: januaryDownloadBtn, 
    overwriteInitial: true, 
    maxFileSize: 3000, 
    removeLabel: '', 
    layoutTemplates: {actionDelete: ''}, 
    allowedFileExtensions: ["xlsx", "xls", "csv"], 
});

Code in controller method:

if($request->hasFile('tableInExcel')) {
$excelFile = new ExcelFile;
$dir = 'admin_files'.$this->getDirectorySeparator().'balancing';
$full_dir = storage_path('admin_files'.$this->getDirectorySeparator().'balancing');
$ext = request()->file('tableInExcel')->getClientOriginalExtension();

$storage = new Filesystem();
if(!$storage->exists($full_dir)) {
$storage->makeDirectory($full_dir, 0755, true);
}
$filename = tempnam($full_dir, '');
unlink($filename);
$filename = substr($filename, strrpos($filename, $this->getDirectorySeparator(), -1)+1);

$excelFile->file_name = $filename . '.' . $ext;
$excelFile->path_to_file = $dir.$this->getDirectorySeparator().$excelFile->file_name;

$fullPath = $full_dir.$this->getDirectorySeparator().$excelFile->file_name;
$storage->put($fullPath, file_get_contents($request->file('tableInExcel')));

$excelFile->save();
return "{}";
}

This same code worked for uploading pdf files in another project.. I'm wondering if there is something I'm missing that has to be add for excel files.

Also I've tested the server code with normal file input form and it worked just fine.

Thank you

**Comment by theTeaGreen** [comment]
I went through all similar issues but none of the given solutions worked for me.. I'm struggling with this for several weeks now. Please help me.

**Comment by kartik-v** [comment]
Do not compare with normal file input. 

If you want to simulate a normal file input upload - you can just use form based submission and do not set `uploadUrl` and you will receive the files. 

Since you are using ajax mode with `uploadUrl` it definitely seems some problem in JSON parsing. As highlghted in the documentation your server action as set in `uploadUrl` must return a valid JSON response. [Read the docs](http://plugins.krajee.com/file-input#ajax-uploads) what is the format of the JSON your server must return.

**Comment by theTeaGreen** [comment]
I'm not comparing this with normal file input. I just meant that my server code works with normal file input, so I assume I'm not writing the fileinput js function correctly.

I want to use this plugin and as you can see in the code above I'm returning an empty JSON object. But when I try to dd() smth in the controller method it doesn't return (print) anything, so I believe it doesn't even get to the server code (I have checked the routes and methods, they are correct). It just messes my front-end so I have to set display:none property on the div element that covers the fileinput and then I can see the following as shown on the image: 
![capture](https://user-images.githubusercontent.com/41127942/42692702-d78105e8-86ac-11e8-8ef2-d00e1b980cee.png)

I've also checked the response by inspect element, it is 200 OK. 
Can you please check if I'm doing something wrong with the configuration?

**Comment by kartik-v** [comment]
What is your input markup?

**Comment by theTeaGreen** [comment]
<input type="file" id="januaryFile" name="tableInExcel" class="file-loading">

**Comment by kartik-v** [comment]
Your server response must return valid JSON and not a string. Debug the XHR response being received on the browser console and check what is being returned and if there is any exception.

**Comment by theTeaGreen** [comment]
I've tried the exact same code (same routes, same controller method, same fileinput script and input markup) in another project and it worked. -.-
What I figured out while debugging is that my request is being redirected - status code is 302 and preview and response tabs are not showing anything. I missed this because all this time I was looking and debugging the XHR response where everything was with response code of 200. 
Yet I still don't understand where is the problem...

**Comment by kartik-v** [comment]
Yes so it is obvious you need to debug your server code, configuration and controller actions. Just test and try a simple server script that returns a empty JSON as the uploadUrl and work from therr.

**Comment by theTeaGreen** [comment]
After several days of struggle I finally found the solution. What I was missing was the token which must be sent in the request. So I did the following in my master view:

`
<meta name="csrf-token" content="{{ csrf_token() }}">
$.ajaxSetup({
           headers: {
               'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
           }
       });`
