### ISSUE TITLE
Drag & drop file in Firefox

### ISSUE THREAD

**Issue by cowpy** [kartik-v/bootstrap-fileinput#1271]
Hi，my computer is Window 10 64 bit.
I got some trouble：
Browsers -Mozilla Firefox 61.0.1 (64 bit)
When drag file to bootstrap-fileinput，the firefox will pop up a new window and auto download the same file.
 Google Chrome and  Edge seems  work well.
IE11 not work，when drag file  into it ，there's no reaction.

**Comment by kartik-v** [comment]
Be sure to read the browser support for drag and drop and functionality you are using. 

I am not sure how you have configured the plugin (ajax mode or form upload mode). There are limitations if you are using form upload mode.

**Comment by kartik-v** [comment]
Not got an update. The issue possibly is also a duplicate to #1281. Closing this. Update if any issue and will reopen it.
