### ISSUE TITLE
how can I work plugins with ASP.NET Webforms

### ISSUE THREAD

**Issue by InfoSpinto** [kartik-v/bootstrap-fileinput#1274]
I need to work the plugins, upload through an additional aspx.
but I need to return the id of the file in database.
How can i fix this?
Google Translate

**Comment by InfoSpinto** [comment]
my solutions  

 in page 

<script>
    $("#file-1").fileinput({
        theme: 'fa',
        uploadUrl: 'Upload.ashx', // you must set a valid URL here else you will get an error
        allowedFileExtensions: ['jpg', 'png', 'gif'],
        overwriteInitial: false,
        maxFileSize: 1000,
        maxFilesNum: 10,
        //allowedFileTypes: ['image', 'video', 'flash'],
        slugCallback: function (filename) {
            return filename.replace('(', '_').replace(']', '_');
        }
    }).on('fileuploaded', function (e, data) {
        console.log(data.response.numero);
    });


in Handler

clArchivo archivo=new clArchivo();
            foreach (string s in context.Request.Files)
            {
                HttpPostedFile file = context.Request.Files[s];
                string fileName = file.FileName;
                string fileExtension = file.ContentType;
                archivo = new clArchivo(HttpContext.Current.Request, HttpContext.Current, file);

            }
            //  database record update logic here  ()
            var serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            string json = serializer.Serialize(new { numero = archivo.id.ToString()});
            context.Response.Write(json);
            // context.Response.Write(archivo.id.ToString());
        }
        catch (Exception ac)
        {
            var serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            string jsonError = serializer.Serialize(new { error = "Error al subir archivos" });
            context.Response.Write(jsonError);
        }

grettings.

**Comment by kartik-v** [comment]
Thanks. Closing this.
