### ISSUE TITLE
Android's Google Chrome doesn't support pdf file's preview.

### ISSUE THREAD

**Issue by alexandernarozhnov** [kartik-v/bootstrap-fileinput#1279]
@kartik-v After you released version `4.4.9` everything works good on IOS but android's google chrome has problems with displaying of pdf-files. Maybe you know any solution for this case?

**Comment by kartik-v** [comment]
I have included an enhancement to also include android phones in addition to iOS devices by default for special pdf rendering.

You can control this anyway by setting the [`usePdfRenderer`](http://plugins.krajee.com/file-input/plugin-options#usePdfRenderer) callback property.
