### ISSUE TITLE
Prevent event filebrowse issue

### ISSUE THREAD

**Issue by itajackass** [kartik-v/bootstrap-fileinput#1282]
i'd like to prevent filebrowse to open based on a value of a input val.
I tried:
    
   $('#input-id').on('filebrowse', function(event) {
        
        var xxx = $("#input-sample").val();

        if ( xxx == 0 ) {
               event.preventDefault();
               alert("You can't select a file at this moment....");
        }

    });

But filebrowse still open. event.preventDefault() seems to working

**Comment by kartik-v** [comment]
Corrected via the above fix - retry and let know.

**Comment by lorife** [comment]
Hello, This problem is still present in the lastest version
