### ISSUE TITLE
Drag & drop does not trigger "change" event on FireFox

### ISSUE THREAD

**Issue by printempw** [kartik-v/bootstrap-fileinput#1283]
On my Firefox Developer Edition 62.0b14, drag and drop a file onto the drop zone of bootstrap-fileinput does not trigger a `change` event on the input element (the preview did change, but no `change` event triggered), but using the `Browse...` button will still trigger the event.

On Microsoft Edge 42.17134.1.0, the drop zone even does not appear, is this normal?

On my Chrome 68.0.3440.75, everything works as expected.

## Steps to reproduce the issue

1. Here I made a JSFiddle: https://jsfiddle.net/aq9Laaew/140263/
2. Open it with Firefox (on my case, version 62.0b14)
3. Drag and drop a file to the drop zone
4. No `change` event triggered on the input element

## Environment

Browsers

- [ ] Google Chrome 68.0.3440.75
- [x] Mozilla Firefox 62.0b14
- [x] Microsoft Edge 42.17134.1.0
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 4.4.9

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a JSFiddle](https://jsfiddle.net/aq9Laaew/140263/)

**Comment by kartik-v** [comment]
Related & Duplicate to #1281. Use `filebatchselected` event.

**Comment by printempw** [comment]
Oh, I forgot to check pull requests. Thanks!
