### ISSUE TITLE
when init problem in bootstrap modal 

### ISSUE THREAD

**Issue by tatalo** [kartik-v/bootstrap-fileinput#1284]
if I write 2 level page and all of them use bootstrap fileinput,the level2  will break ( like image), can I fix it?

![image](https://user-images.githubusercontent.com/1777021/43882419-2952cb82-9be2-11e8-868b-613292fe4ba8.png)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.11.2
- bootstrap-fileinput version: 3.3.5

**Comment by kartik-v** [comment]
You need to have unique id attributes for your HTML native file input.s
