### ISSUE TITLE
When using Chinese input method

### ISSUE THREAD

**Issue by hardo123** [kartik-v/bootstrap-fileinput#1289]
## Steps to reproduce the issue

****************

1.When using Chinese input method，The input box can enter text digits.But it can not be cleared.

 I hope the input box can not be entered.

*****************

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox

Operating System

- [x] Windows

Libraries

- jQuery version:3.3.1
- bootstrap-fileinput version: v4.4.8

**Comment by kartik-v** [comment]
Not clear with this issue - please share a JS Fiddle to understand what you are mentioning and to reproduce any issue.

**Comment by kartik-v** [comment]
Closing as cannot reproduce. In case you have a Fiddle - pls share to reproduce and will reopen.
