### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by genc6541** [kartik-v/bootstrap-fileinput#129]
I have only downloaded plugin and tried open my localhost. Does not work localhost? What can I do to make it work?

**Comment by kartik-v** [comment]
You need to [read plugin docs first](http://plugins.krajee.com/file-input)  as well as [usage and ajax related docs](http://plugins.krajee.com/file-input/demo). 

Once you have your plugin initialized using above you then need to create your server code right (either to read form submissions or if using ajax to return a right JSON encoded ajax response).

**Comment by genc6541** [comment]
I do not work with json. I only want to image upload. I don't know json mson

**Comment by langy1** [comment]
really... huh... and you expect the plugin author to respond to people like you... you wish to use a feature but are not interested in knowing about it... do your rhymes elsewhere rather than joking around here...
