### ISSUE TITLE
Similar to #315 but when using the readFiles method.

### ISSUE THREAD

**Issue by AJavierSanchez** [kartik-v/bootstrap-fileinput#1290]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. I've Instantiate the object like this:
$("#fileupload").fileinput({
          language : 'es',
          showUpload : true, 
          uploadUrl : someurl,
          allowedFileType : ['image'],
          allowedFileExtensions : ['jpg','jpeg','png'],
          autoOrientImage : false, 
          previewFileType : 'image',
          overwriteInitial: false,
          initialPreviewAsData: true,
          initialPreviewFileType: 'image',
          initialPreview: prefoto, //array of urls
          showCaption : true,
          dropZoneEnabled : true,
          showRemove : true,
          maxFileCount : 6,
          maxFileSize : 100000,
          browseClass : "btn btn-success",
          browseLabel : "Elegir Imagen/es",
          browseIcon : "<i class=\"fa fa-file-image-o\"></i> ",
          removeClass : 'btn btn-danger',
          removeTitle : 'Borrar Imagen',      
          removeLabel : "Borrar",
          removeIcon : "<i class=\"fa fa-trash-o\"></i> ",
          uploadClass : "btn btn-info",
          uploadLabel : "Subir",
          uploadIcon : "<i class=\"fa fa-upload\"></i> "
        });
2.  Then I create a blob array:
         for (var i=0; i<response.responseJSON[0].foto.length; i++){
            blobj.push(b64toBlob(response.responseJSON[0].foto[i],'image/jpg'));
          } 
3. Finally:
          $('#fileupload').fileinput('readFiles',blobj);

## Expected behavior and actual behavior

When I follow those steps, I see...

fileinput.js:340 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at Object.htmlEncode (fileinput.js:340)
    at readFile (fileinput.js:3819)
    at FileInput.readFiles (fileinput.js:3979)
    at HTMLInputElement.<anonymous> (fileinput.js:4247)
    at Function.each (jquery.min.js:2)
    at w.fn.init.each (jquery.min.js:2)
    at w.fn.init.$.fn.fileinput (fileinput.js:4230)
    at Object.complete (mlsigma.js:700)
    at u (jquery.min.js:2)
    at Object.fireWith (jquery.min.js:2)

I was expecting...
  to see the preview populated with images.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:  3.3.1
- bootstrap-fileinput version:  4.5.0

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

One final thing, the fileinput object is not visible by the moment I fire the readFiles method.

**Comment by kartik-v** [comment]
You are trying to use a plugin's internal method `readFiles` which reads `HTML File List` objects and not `blobs` and hence the issue you have is `file.name` and such properties are not available. 

In any case you do not seem to have the latest plugin release - you need to correct your code above and use latest plugin release.

**Comment by AJavierSanchez** [comment]
sorry, I misunderstood the manual.

![preuba](https://user-images.githubusercontent.com/42157733/44423674-181e9880-a55d-11e8-8178-ee022fd75df6.png)

**Comment by kartik-v** [comment]
Will update the docs to be clear...
