### ISSUE TITLE
How make a initialPreviewConfig,initialPreview and Url of files dynamically?

### ISSUE THREAD

**Issue by astrO1** [kartik-v/bootstrap-fileinput#1293]
Hi Katik,

First of all thanks you for the nice plugin, i'm facing a small problem that i don't know how make a good code for it.

example i have my input iniciation working fine, but when the user upload a video the preview not display like a video file i must put in **initialPreviewConfig** the type: "video" and filetype: "video/mp4" and after that show fine.

but how i will detect if the file is video type without make a destroy input everytime? 

I'm using image and video upload with you plugin. Another question is how i can put dynamically the options? In your examples always is static information like this 

`initialPreviewConfig: [
    {caption: "Business 1.jpg", size: 762980, url: "$urlD", key: 11},
    {previewAsData: false, size: 823782, caption: "Business 2.jpg", url: "$urlD", key: 13}, 
    {caption: "Lorem Ipsum.txt", type: "text", size: 1430, url: "$urlD", key: 12}, 
    {type: "pdf", size: 8000, caption: "PDF Sample.pdf", url: "$urlD", key: 14}, 
    {type: "video", size: 375000, filetype: "video/mp4", caption: "Krajee Sample.mp4", url: "$urlD", key: 15},  
]`

can you help me? thanks

**Comment by kartik-v** [comment]
You can detect file mime types to a large extent from your server code that uploads the file and return the type accordingly in `initialPreviewConfig` as the ajax response.

**Comment by kartik-v** [comment]
Am closing this issue - because it is not directly related to plugin. You can post queries on the comments & discussions section to get more programming help.
