### ISSUE TITLE
please make a way to disable drag & drop in box when using ajax uploading

### ISSUE THREAD

**Issue by armnotstrong** [kartik-v/bootstrap-fileinput#130]
I find that when using this plugin with the scenario of **Ajax uploading**, after config the `uploadUrl` ,the **drag & drop** in box will always showing up, I think it will nice to make a way to  turn it off, only show it when the file to upload is(are) selected.

**Comment by kartik-v** [comment]
How will you drag and drop if its not shown?

Anyway you can control its display by editing the templates or setting showPreview based on events.

**Comment by kartik-v** [comment]
How and where will you drag and drop files if you do not have a dropZone displayed?

If you do not need drag and drop - set `dropZoneEnabled` to `false`.

**Comment by armnotstrong** [comment]
What I mean is I like the default behavior of the drag & drop box, which is before click the `browse` button, the drag & drop box wont show up, and after I click `browse` button, It will show up so that I can add more files, or delete one. (it's the default behavior of the `input` right?), 

here is What currently things look like:
![screenshot from 2015-01-16 10 55 38](https://cloud.githubusercontent.com/assets/3839691/5770956/03a9d832-9d6f-11e4-959d-eb831dbdb9ad.png)

and this is the html:
 <div class="col-sm-6">
        <form class="form-inline col-sm-20 upload-file" action="/upload" method="post">
            <div >
                <input type="file" class="file form-control fileUpload" task-name=autoSign >
            </div>
        </form>
    </div>

    <div class="col-sm-6">
        <form class="form-inline col-sm-6 pull-right add-task" action="/api/job" method="">
            <div class="input-group">
                自动签名
                <input type="hidden" name=taskName value=autoSign>
                <input type="hidden" name="action" value="addJob">
                <button type="submit" name="action" value="addJob" class="btn btn-success">新建任务</button>
            </div>
        </form>
    </div>
    
    <div class="col-sm-6">
        <form class="form-inline col-sm-20 upload-file" action="/upload" method="post">
            <div >
                <input type="file" class="file form-control fileUpload" task-name=cat >
            </div>
        </form>
    </div>

    <div class="col-sm-6">
        <form class="form-inline col-sm-6 pull-right add-task" action="/api/job" method="">
            <div class="input-group">
                看看文件里都写了些啥
                <input type="hidden" name=taskName value=cat>
                <input type="hidden" name="action" value="addJob">
                <button type="submit" name="action" value="addJob" class="btn btn-success">新建任务</button>
            </div>
        </form>
    </div>

and here is the controlling JavaScript:

    $('.fileUpload').fileinput({
        uploadUrl:'/upload',
        showCaption:false,
        uploadExtraData: function(){
            console.log(this.$element.attr('task-name'))
            return {taskName:this.$element.attr('task-name')}
        }
    })

as you can see, I really don't like the drag & drop box attached there, It's too large. :sob:

**Comment by armnotstrong** [comment]
Sorry to bother again, I found setting `dropZoneEnabled` to `false` is just what I needed, thank you!

**Comment by kartik-v** [comment]
There are developers who need drag and drop on initialization (this is independent of whether you click Browse button or not).

As I said - If you do you need to set `dropZoneEnabled` to `false` and reenable it if needed

**Comment by thejahweh** [comment]
Is there a way to enable the DropZone without having any "uploadUrl" set? Because without any "uploadUrl" you can still drop files, but it does not show any nicely styled "drop here" box.

**Comment by kartik-v** [comment]
No. You cannot drop files and read without uploadUrl set (basically unless you use ajax upload - this will not work).

Refer #135. Its been asked by quite a few of you. You need to understand that you cannot set the value of a file input from external code. Hence dragging and dropping files into the zone will not be passed to the file input via POST to your server code.

**Comment by thejahweh** [comment]
Basically I've overwritten the submit, because I have to handle different forms with different content and only sometimes with your upload widget.

Here is my current submit handler:
```javascript
$('#divXYZ').on('submit', 'section.article form', function() {
	var $form = $(this);
	var $article = $form.closest('section.article');
	var sendAdd = $article.data();
	var fdata = new FormData(this);
	for (var key in sendAdd) {
	    if (sendAdd.hasOwnProperty(key)) {
	    	fdata.append(key, sendAdd[key]);
	    }
	}
	fdata.append('a', 'save');
	$.ajax({
		type: 'post',
		url: $form.attr('action'),
		dataType: 'json',
		data: fdata,
		processData: false,
		contentType: false
	}).done(function(data) {
		if (data.success) {
			$article.data('naid', data.object.newsID);
			$article.data('noid', data.object.id);
			$article.empty();
			$article.html(data.html);
		}
	})
	return false;
});
```

**Comment by kartik-v** [comment]
Yes as mentioned you are using AJAX and not native form submission - you cannot selectively add or delete files before form submit  unless you use ajax.
When the `uploadUrl` is set it also triggers ajax call - where you can pass additional form data using `uploadExtraData` property and track the `fileuploaded` and `fileuploaderror` events to write additional code after ajax request completion.
