### ISSUE TITLE
remove after upload, and add into existing initialpreview   

### ISSUE THREAD

**Issue by alpastar** [kartik-v/bootstrap-fileinput#1300]
ver 4.5.0,  using  ajax async upload method 

suppose  we have a  two file input in one page(html) 
one is for  local (for upload, $input_file_lc) 
and  another  one is  for server file(preview, $input_file_sv)
first,  download from server and  display that files  in  $input file_sv , 
success, now 3 photo shows up!  (in  $input file_sv) 

second  load file from local into $ input_file_lc,   5 (local)photos shows up 
then i upload 2 photos from $input_file_lc , success, 
so i have 2 photos which had uploaded, and 3 photos which is not yet uploaded (in $input_file_lc )

question 
1.
i want to remove a  file  which has uploaded  success  from $input_file_lc 
i mean from preview  and file-stack , and remove only uploaded files. 
is there  any method , or how-tos ?? ,
(in-short, remove file which has uploaded success)

2. 
i want to add a  file  which has uploaded  success  to another input file region ($input_file_sv)
which already have  initialPreviewImage .
is there  any method , or how-tos ??

read your manual throughly  and tested in several ways 
but  no success !
.
thanks  in advance   however.  
and many thanks for your amazing this plugin.

**Comment by alpastar** [comment]
// remove uploaded files ::   not-smart but working 

//-------------------------------------------------------------------------------------
$input_lc.on('fileunlock', function(event, filestack, extraData) {

 // triggered when the upload process is completed (successfully or with error). 
 // The entire widget is unlocked (enabled) and reverts to initial state. 

 // filestack: the array of selected file objects.
 // uploadExtraData: the uploadExtraData settings for the plugin (will return an empty object if not set).
//-------------------------------------------------------------------------------------
   // var fstack = filestack.filter(function(n){ return n != undefined });
   // console.log('fileunlock - ' + fstack.length);

   //  remove uploaded file (성공한 파일을  remove)
    var o_stack = $(this).fileinput('getFileStack') ;         //  file-uploaded is excluded(upload 성공한 파일은 제외된다)
    $input_lc.fileinput('destroy').fileinput(go_opt_lc);     // re-create (재 생성)
    $input_lc.fileinput('readFiles', o_stack);                    //  re-read (다시 읽어들인다)

**Comment by kartik-v** [comment]
In my opinion you need not have 2 file inputs for your use case - since the plugin offers server based preview via initialPreview.

If you need to customize and have your own preview container then you can set the [elPreviewContainer](http://plugins.krajee.com/plugin-options#option-elPreviewContainer) to point to your own custom container where you wish to render the preview and override the templates properties to render specific sections only.

**Comment by alpastar** [comment]
yes,  i'm struggling  between two-ways 
one  is  having  one input-zone ,  
but here,   pre-existing server files, uploaded files, un-uploaded-files exists mingled , 
so i am afraid that  end-users might-be confused(or not clear especially in my case)
your plugin have many option, and method for this way, 
so it is somewhat easy to implement this way. 
.
second is  to have  two separated input-zone , 
this seems  somewhat clear to end-users( i think).
file in server , file in local , 
.
so,  as far as  i concerned , i prefer second way 
but destroy,reset,clear, showUploadedThumbs.. all is not relevant to this way 

any way ,  thanks for your comment...
remaining problem is insert into pre-existing-initialPreview,,
i will try..

**Comment by alpastar** [comment]
success!!

//////  append uploaded file to preexisting preview   /////////////////

   // $input_sv.fileinput('getFileStack') => [], empty-array 
   // fileStack means file-list which is selected(from local), have no-relation with server file 
   // so uploaded file is removed from file-stack ??

    o_preview = $input_sv.fileinput('getPreview');           // current-preview 
    // be careful that prefix:'initialPreview'  is  not existing. 
  /*
   {content: Array(2), config: Array(2), tags: Array(0)}
     config: Array(2)
     0: {caption: "1", size: 0, width: "120px", url: "", key: 1}
     1: {previewAsData: false, caption: "2", size: 0, width: "120px", url: "", …}
     length: 2
     __proto__: Array(0)
     content: Array(2)
     0: ".........img/fake-male.png"
     1: "<img src='........./img/fake-male.png' class='file-preview-image' alt='Jelly Fish' title='Jelly Fish'>"
     length: 2
     __proto__: Array(0)
     tags: []
  */

   // to overcome prefix difference 
   var o_preview_curr = {} ;
   o_preview_curr.initialPreview        = o_preview.content ;
   o_preview_curr.initialPreviewConfig  = o_preview.config  ;

   // append uploaded-file(s) to current preview-list 
  // we are using  ajax-async  method , so uploaded event  put/append   each response 
  // to go_input.a_rp  which is array 
   for (var k=0; k< go_input.a_rp.length ; k++){
     o_preview_curr.initialPreview.push(go_input.a_rp[k].initialPreview);
     o_preview_curr.initialPreviewConfig.push(go_input.a_rp[k].initialPreviewConfig);
   }

   // re-make config object 
   var o_opt_new = $.extend(true,{},go_opt_sv,o_preview_curr);

   // re-create 
   $input_sv.fileinput('destroy').fileinput(o_opt_new);     // recreate
