### ISSUE TITLE
Using plug-ins to upload videos and click Modify pages can not display video properly.

### ISSUE THREAD

**Issue by 18331581824** [kartik-v/bootstrap-fileinput#1301]
## scene
   I am in the process of using. configuration parameter  ['initialPreviewFileType' => 'video'].Upload files can be displayed after completion.But click again to return to this page to show the invalid playback source.
##Solution
I change the source code of plugins.The generated video tag is also added to a src attribute. The page display is normal now.I would like to know if there is a wrong parameter configuration in my place, resulting in the video can not normally display and play?

Thank you very much for helping me solve this problem.

**Comment by kartik-v** [comment]
Duplicate to #1302
