### ISSUE TITLE
Using plug-ins to upload videos and click Modify pages can not display video properly. 

### ISSUE THREAD

**Issue by 18331581824** [kartik-v/bootstrap-fileinput#1302]
I am in the process of using. configuration parameter ['initialPreviewFileType' => 'video'].Upload files can be displayed after completion.But click again to return to this page to show the invalid playback source.
##Solution
I change the source code of plugins.The generated video tag is also added to a src attribute. The page display is normal now.I would like to know if there is a wrong parameter configuration in my place, resulting in the video can not normally display and play?
#####
tVideo = '<video src="{data}" class="kv-preview-data file-preview-video" controls' + tStyle + '>\n' +
                '<source src="{data}" type="{type}">\n' + $h.DEFAULT_PREVIEW + '\n</video>\n';
###

Thank you very much for helping me solve this problem.

##case

<?= $form->field($model, 'positive_left_video')->widget(FileInput::classname(), [
        'options' => ['multiple' => true],
        'pluginOptions' => [
            'initialPreviewFileType' => 'video',
            'previewFileType' => 'video',
            'initialPreview' => isset($model->positive_left_video) ? $model->positive_left_video : '',
            'initialPreviewConfig' => isset($p4) ? $p4 : '',
            'initialPreviewAsData' => true,
            'uploadUrl' => $urlManager->createAbsoluteUrl(['/video/training-action-video/uploads']),
            'uploadExtraData' => [
                'id' => $model->id,
                'video_name' => 'positive_left_video'
            ],
            'uploadAsync' => true,
            'maxFileCount' => 1,
            'showRemove' => true,
            'showUpload' => true,
            'browseOnZoneClick' => false,
            'showBrowse' => true,
            'fileActionSettings' => [
                'showZoom' => false,
                'showUpload' => true,
                'showRemove' => true,
            ],
        ],
        'pluginEvents' => [
            'fileuploaded' => "function (object, data) {
                $('.field-trainingactionvideo-positive_left_video .control-label').siblings().val(data.response.imageUrl)
            }",
            'error' => "function (){
                alert('error');
            }"
        ],
]);
?>

**Comment by kartik-v** [comment]
I am not clear of the issue. You mentioned you are changing the source code of the plugins. Not sure I can help since you are changing the default plugin code. Assuming you only need help or have issue with the plugin config, I suggest to create a JS Fiddle and share what your issue is and submit a new issue again.

**Comment by 18331581824** [comment]
I am using yii2 to upload a video. It is normal to upload the video when I add it. After saving, I can't display it properly when I click to modify the video. But the video link is correct.

**Comment by 18331581824** [comment]
So I used the browser tool to view and found that adding the src in the source tag to the upper level video can display it normally. So I will change the source code, is there a better solution, or is it because I am not using the right method?

**Comment by kartik-v** [comment]
You may need to read and understand how to configure the plugin properties. Go through the [plugin options docs](http://plugins.krajee.com/file-input/plugin-options] to understand the initial preview properties to display a saved server content e.g. `initialPreview`, `initialPreviewConfig`, `initialPreviewAsData` 

How a saved content is displayed depends on how you are configuring the above? Refer the [initial preview as data demo](http://plugins.krajee.com/file-preview-management-demo#preview-data).

**Comment by 18331581824** [comment]
'initialPreviewFileType' => 'video',
            'previewFileType' => 'video',
            'initialPreview' => isset($p1) ? $p1 : '',
            'initialPreviewConfig' => isset($p2) ? $p2 : '',
            'initialPreviewAsData' => true,

I have configured these parameters, the label in the browser is also the video tag, but it is a black display video invalid source, the src in the source tag can be displayed in the parent video tag.

**Comment by 18331581824** [comment]
Thank you very much. The problem has been solved.
