### ISSUE TITLE
Problem with the explorer theme using Fontawesome Icons (yii2-icons version >= 1.4.5)

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/bootstrap-fileinput#1303]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
I used your fileinput but after some updates I get strange "preview icons".
I use similar settings like your demo e.g.

    'previewFileIconSettings' => [
    'pdf' => '<i class="fa fa-file-pdf-o text-danger"></i>',
    'ppt' => '<i class="fa fa-file-powerpoint-o text-danger"></i>',
    ]

http://plugins.krajee.com/file-preview-icons-demo

The icon which is rendered in the fileinput.js in your function _previewFile is correctly rendered with

   <span class=\"file-other-icon\"><i class=\"fa fa-file-pdf-o text-danger\"></i></span>\

But i guess its because of the latest update to yii2-icons a svg is rendered as a replacement for the icon.

"Remove Font Awesome 4.x support and include load Font Awesome Free 5.x JS/SVG asset"
https://github.com/kartik-v/yii2-icons/commit/a558b5ac13f542bb7cdb82474c38c173e966ba5e

And this icon is wrong and it looks more like an error to the user.

## Expected behavior and actual behavior

This is the replacement svg which switches from ! to ? 

![grabilla g26296](https://user-images.githubusercontent.com/1777147/45942138-8a155200-bfe1-11e8-9d0b-1f61772c9f94.gif)

I was expecting...
before it was only an single image
![image](https://user-images.githubusercontent.com/1777147/45942184-b8932d00-bfe1-11e8-839d-b614aa3fda0f.png)

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 
- bootstrap-fileinput version: latest dev

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

So how can this prevented?
When i use yii2-icons version 1.4.4 it works as expected but with the current latest version v1.4.5 it doesn't.

**Comment by kartik-v** [comment]
Use `explorer-fas` theme instead of `explorer-fa` within bootstrap-fileinput if using with krajee `yii2-icons`.

**Comment by Bhoft** [comment]
Doesn't work when changing the theme.
Each Icon is automatically replaced when using yii2-icons version 1.4.5
echo '<i class="fa fa-file-pdf-o text-danger"></i>';

(I had used your theme with the custom icons "previewFileIconSettings" as in your demo)

Arghs I guess I now knew the problem.  The image in font-awesome was renamed file-pfd-o doesn't exists any more and this was only available in fa-4.7 https://fontawesome.com/v4.7.0/icon/file-pdf-o

As you have removed the 4.x support in yii2-icons i have to replace the icons with the proper v5 icon. 

I had the icon codes from your advanced demo therefore these should also be corrected.

http://plugins.krajee.com/file-krajee-explorer-demo#krajee-explorer-2

**Comment by Bhoft** [comment]
With the newer yii2-icons (FA5) the code must be like below to get the result as before.


    'previewFileIconSettings' => [
                'doc' => Icon::show('file-word', ['class' => 'text-primary', 'framework' => Icon::FAR]),
                'xls' => Icon::show('file-excel', ['class' => 'text-success', 'framework' => Icon::FAR]),
                'ppt' => Icon::show('file-powerpoint', ['class' => 'text-danger', 'framework' => Icon::FAR]),
                'pdf' => Icon::show('file-pdf', ['class' => 'text-danger', 'framework' => Icon::FAR]),
                'zip' => Icon::show('file-archive', ['class' => 'text-muted', 'framework' => Icon::FAR]),
                'htm' => Icon::show('file-code', ['class' => 'text-info', 'framework' => Icon::FAR]),
                'txt' => Icon::show('file-alt', ['class' => 'text-info', 'framework' => Icon::FAR]),
                'mov' => Icon::show('file-video', ['class' => 'text-warning', 'framework' => Icon::FAR]),
                'mp3' => Icon::show('file-audio', ['class' => 'text-warning', 'framework' => Icon::FAR]),
                'jpg' => Icon::show('file-image', ['class' => 'text-danger', 'framework' => Icon::FAR]),
                'gif' => Icon::show('file-image', ['class' => 'text-muted', 'framework' => Icon::FAR]),
                'png' => Icon::show('file-image', ['class' => 'text-primary', 'framework' => Icon::FAR]),
            ],

**Comment by kartik-v** [comment]
Yes... there is a BC breaking change - but it will be much easier to control in Yii2-Icons with code like above.

**Comment by kartik-v** [comment]
> I had the icon codes from your advanced demo therefore these should also be corrected
http://plugins.krajee.com/file-krajee-explorer-demo#krajee-explorer-2

The above is for Font Awesome 4.x theme

Use the Font Awesome 5.x theme instead as mentioned earlier via `explorer-fas` theme](http://plugins.krajee.com/file-krajee-explorer-fas-demo) i

**Comment by Bhoft** [comment]
But still in your demo  
http://plugins.krajee.com/file-krajee-explorer-fas-demo#krajee-explorer-fas-2
you have 

     
     previewFileIconSettings: { // configure your icon file extensions
        'pdf': '<i class="fa fa-file-pdf-o text-danger"></i>',

Which is wrong as the `fa-file-pdf-o` doesn't work with FA5 and only with 4.x.
Or at least is replaced with the !? svg icon as the original icon isn't found.
The correct name would be `file-pdf`with FAR.

See table here:
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes

**Comment by Bhoft** [comment]
I think it`s ok now :)

**Comment by Bhoft** [comment]
Not sure what you have done on your demo page.  http://plugins.krajee.com/file-krajee-explorer-fas-demo
It currently throws a JS error "{icons}" and nothing is rendered atm. 
But I guess you are currently changing / testing something.

**Comment by kartik-v** [comment]
Yes it is updated to include both FA 4.x & FA 5.x
