### ISSUE TITLE
fa-font not shows up

### ISSUE THREAD

**Issue by alpastar** [kartik-v/bootstrap-fileinput#1306]
windows7(64-bit), chrome 69, ver 4.5.0

$("#input_file").fileinput( { theme:"fa" ,browseOnZoneClick:true  ,uploadUrl : "https://...."  });   

upload,delete,zoom button  -> icon shows up 
.
but in zoom-modal 
  4buttons showup  but only direction-icon(second-button) show-up 
.
![0001](https://user-images.githubusercontent.com/3488601/45999867-ea8bb880-c0e1-11e8-8405-a4b5c472b36f.jpg)

**Comment by alpastar** [comment]
css/script included in html-page

//  jquery ,jqurty-ui,bootstrap4.... 

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/plugins/piexif.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/plugins/sortable.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/plugins/purify.min.js" type="text/javascript"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/css/fileinput.min.css" media="all" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/fileinput.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/locales/kr.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/themes/fa/theme.js"></script>

**Comment by kartik-v** [comment]
use theme `fas` for font awesome 5.x. The theme `fa` is for font awesome 4.x.

**Comment by alpastar** [comment]
with theme:"fas" ,  all button becomes empty !

![0002](https://user-images.githubusercontent.com/3488601/46067494-e62ed080-c1b1-11e8-8bd7-572728c16ddd.jpg)

**Comment by kartik-v** [comment]
You need to load the [font awesome 5.x CSS](https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css) on your page for fonts to be displayed.

**Comment by kartik-v** [comment]
You need to debug your app code then if you are having the right versions and releases.

You can cross check [the plugin demos page for `fas` theme](http://plugins.krajee.com/file-theme-demo#theme-fas) and see that it works fine.

**Comment by alpastar** [comment]
solved , thanks!

the problem was .../4.5.0/themes/fa/theme.js.
it should be     .../ 4.5.0/themes/fas/theme.js.
.
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/fileinput.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/locales/kr.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/themes/fas/theme.js"></script>

**Comment by HaGD** [comment]
> solved , thanks!
> 
> the problem was .../4.5.0/themes/fa/theme.js.
> it should be .../ 4.5.0/themes/fas/theme.js.
> .
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/fileinput.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/js/locales/kr.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.5.0/themes/fas/theme.js"></script>

I also had a problem, but I can see your answer. It's hard to find. XD
