### ISSUE TITLE
Selecting multiple files does not work in 4.5.1 version

### ISSUE THREAD

**Issue by brunomcuesta** [kartik-v/bootstrap-fileinput#1307]
I upgraded to version 4.5.1 and the selection of multiple files stopped working. It is replacing the existing file and does not accept the selection of more than one file. Trash icons do not appear to. I'm uploading without Ajax, putting the url in the action of the form.

My configuration:

```
<!-- Bootstrap File Upload plugin JavaScript-->
<script src="{% static 'bootstrap/js/dist/util.js' %}"></script>
<script src="{% static 'bootstrap/site/docs/4.1/assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'bootstrap-fileinput/js/plugins/purify.min.js' %}"></script>
<script src="{% static 'bootstrap-fileinput/js/plugins/piexif.min.js' %}"></script>
<script src="{% static 'bootstrap-fileinput/js/fileinput.min.js' %}"></script>
<script src="{% static 'bootstrap-fileinput/js/locales/pt-BR.js' %}"></script>
<script src="{% static 'bootstrap-fileinput/themes/fas/theme.min.js' %}"></script>

$("#inputfile").fileinput({
        language: "pt-BR",
        theme: "fas",
        uploadAsync: false,
        overwriteInitial: false,
        autoReplace: false,
        autoOrientImage: true,
        maxFileCount: 4,
        uploadIcon : "<i class='fas fa-upload'></i>",
        removeIcon : "<i class='fas fa-trash-alt'></i>",
        browseIcon : "<i class='fas fa-search-plus'></i>",
        removeClass : 'btn btn-danger',
        showUpload: false,
        purifyHtml: true,
        uploadExtraData:{'csrfmiddlewaretoken': '{{ csrf_token }}'},
        fileActionSettings: {
            showUpload: false,
        },
    });
```

**Comment by kartik-v** [comment]
Check your code.

You need to set the `multiple` attribute of the HTML File Input markup for multiple file upload to be enabled.

[Refer basic demo example # 7](http://plugins.krajee.com/file-basic-usage-demo#basic-example-7)

**Comment by brunomcuesta** [comment]
Hello!
I have `multiple` attribute in form. The upload was working, it suddenly stopped working when I updated the plugin version.

**Comment by kartik-v** [comment]
Check for errors on your code and check the browser console for errors that will guide you to what your doing wrong.

**Comment by hannanstd** [comment]
i have this problem too

**Comment by mistrjirka** [comment]
I actually cannot see  the basics working (https://plugins.krajee.com/file-basic-usage-demo#basic-example-6). You cannot upload multiple files. If you try to upload more than one file it will delete the other one

**Comment by kartik-v** [comment]
For allowing multiple files to upload set the *multiple* attribute to *true* of your input markup... This is true for any HTML native file input. Cross check HTML 5 documentation for details if unclear.

**Comment by Megh2302** [comment]
I am using v5.1.4

I have same issue. selection of multiple file at once using ctrl is working. But selection of multiple file one by one is not working. every time it overwrites the previous file.  I have multiple attribute set to true for file input.
