### ISSUE TITLE
Separate thumbnail and zoom images

### ISSUE THREAD

**Issue by computerzman** [kartik-v/bootstrap-fileinput#1321]
When I upload image I create small image (thumbnail) from the original image so ..
Is there away to Show thumbnail and when click zoom open original image...
Thanks in advance ..

**Comment by kartik-v** [comment]
Resolved via [this major upgrade to release v5.0.0](https://github.com/kartik-v/bootstrap-fileinput/commit/d635155749059accbd68e272fdcde686f3115257) well ahead of time.

- Configure `zoomData` within `initialPreviewConfig` that is different than the `initialPreview`
- Also refer resumable uploads / chunk uploads [documentation here](http://plugins.krajee.com/file-input#ajax-resumable)
- Refer [resumable uploads demos](http://plugins.krajee.com/file-resumable-uploads-demo)
- Refer [enhancements and features closed in 5.0.0 release milestone](https://github.com/kartik-v/bootstrap-fileinput/milestone/1?closed=1)
