### ISSUE TITLE
Error in IE11 Folder drag and drop.

### ISSUE THREAD

**Issue by cablegunmaster** [kartik-v/bootstrap-fileinput#1324]
OS: Windows
Browser: IE11 (not checked on IE10) but could be similar.

Reproduce:
1. Open internet explorer 11 with dropZoneEnabled true.
2. Drag a file in it. console says undefined when selecting a file on IE11.

_Proposed fix on fileinput.js_
``
    getDragDropFolders: function (items) {
            var i, item, len = items !== undefined ? items.length : 0, folders = 0;
    ....
``
A check for undefined on the var "items" should be in there. on line 1525. 
So when the undefined item is found 0 is returned.

**Comment by dkingofpa** [comment]
This is reproducible on the Krajee website when using IE11.

1. Go to [Advanced Example 11](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-11)
2. Drag and drop a file on the drop zone.

Output in the IE11 F12 Developer Tools:
```
SCRIPT5007: Unable to get property 'length' of undefined or null reference
fileinput.min.js (11,1576)
```

**Comment by dkingofpa** [comment]
Another proposed fix to avoid any issues with undefined/null/non-array value.  Since getDragDropFolders(items) is expecting an array, make sure we are passed an array and create an empty one if not.

```
getDragDropFolders: function (items) {
    if (!$.isArray(items)) {
        items = [];
    }
    ...
},
```
