### ISSUE TITLE
delete btn not work when load file input ctrl with previewConfig

### ISSUE THREAD

**Issue by andy65007** [kartik-v/bootstrap-fileinput#1327]
## Steps to reproduce the issue

1. load file input control with previewConfig
2. file ctrl set tow attributes data-max-file-count="1" and data-min-file-count="1"
3. then error occurs.
errors occur:
 _validateMinCount: function () {
            var self = this, len = self.isAjaxUpload ? self.getFileStack().length : self._inputFileCount();
            if (self.validateInitialCount && self.minFileCount > 0 && self._getFileCount(len - 1) < self.minFileCount) {  //erro in this line
                self._noFilesError({});
                return false;
            }
            return true;
        },

**Comment by kartik-v** [comment]
It is expected. You have set `minFileCount` to `1` - which means you expect at least `1` file to be there in preview the plugin will not allow you to delete the same. 

You need to set `minFileCount` to `0`.

Secondly you may want to code your app correctly. if you want users to just upload one file then do the following

- do not set `multiple` attribute of the source native file input in your html markup (this will allow only 1 file to be uploaded). 
- You can set `maxFileCount` if you need to `1`.
- You can set the `required` property of the plugin to `true` to ensure user uploads the file always,

**Comment by andy65007** [comment]
I set minFileCount to 1 means the server only need one file, but when user in editing mode, user can change the file to another one. It seems the logic in here is a little bit not clear(user can see delete button, but he/she can not click it), is it better to put checking min-file-Count action to ... when user submit the form? or just show a error message in drop area? because user can not change the file when  minFileCount is set to 1.

**Comment by kartik-v** [comment]
As I mentioned your use case needs to be configured differently and not with `minFileCount`. Check the [avatar upload demo # 1](http://plugins.krajee.com/file-avatar-upload-demo#avatar-upload-1) as an example (that example does not include the server upload script - but it will work similar for an edit scenario as the uploaded server image will be configured as part of initialPreview).
