### ISSUE TITLE
files selected message displayed in caption window increasing too slow

### ISSUE THREAD

**Issue by roarcurry** [kartik-v/bootstrap-fileinput#1328]
When I select multiple files, the selected message displayed in caption window increasing too slow.

For example, when I select 100 files, the selected message changes from "1 files selected" to "100 files selected" one by one. And it really costs a lot of time, probably dozens of seconds.

Is there any solution for this issue, so that the selected message can increase faster, or diplay the final message at once? Or just read files faster.

Thanks!

**Comment by kartik-v** [comment]
Its entirely dependent on how you are coding and programming your application. 

Note that the progress you see when you select files in this plugin is majorly dependent on whether you wish to see PREVIEW of the files or not. When preview is enabled, the file selection progress is basically the time taken to extract and read each content from each and every files selected. If you do select 100s of files (not sure why you want to do that) - it then depends on whether you wish to enable preview for them or not.

You could prevent preview of content in the thumbnails and show iconic thumbnails (as [seen in this demo](http://plugins.krajee.com/file-preview-icons-demo#custom-preview-icons-1)) - which would drastically enhance the speed and progress of files selected. However, in this case you would not see the content of the files as thumbnails.

Again depends on what you want and how you code and configure.
