### ISSUE TITLE
Asynchronous drag/drop file selection crashes Google Chrome

### ISSUE THREAD

**Issue by rdev24** [kartik-v/bootstrap-fileinput#1329]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Open Google Chrome browser and navigate to http://plugins.krajee.com/file-input-ajax-demo/1
2. Select "Browse ..."
3. Drag file from file explorer window to file input field
4. Close the file input window in any way
5. Watch Chrome crash
**This issue only occurs when selecting the very first file.  If the steps above are replicated after the first file has already been added to the file list, the issue does not occur.**

## Expected behavior and actual behavior

When I follow those steps, I see the browser crash hard.

I was expecting the file explorer window to close and the browser to be operational as it does in IE and Edge - Firefox does not allow files to be dragged/dropped from the browser's file explorer window.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: Assuming 4.4.9

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Its unfortunately a browser behavior that you need to report to Chrome development community.  All of the activities you mentioned (The file dialog opening, file selecting and dragging from that dialog) are native to the browser and controlled by the browser.

Unfortunately not something that can be done within the plugin. Workaround is to open a file explorer separately and drag and drop the file from there to Chrome.
