### ISSUE TITLE
using ajax upload and form upload

### ISSUE THREAD

**Issue by cutemonster** [kartik-v/bootstrap-fileinput#1330]
I'm using ajax upload in my form for the sorting feature only in a temp location on the server.
Then when I submit the form, is there a way to include the list of files?

From what I know, it's either ajax or form request but not both?
can you please tell me any work around?

thanks,

**Comment by kartik-v** [comment]
In ajax upload mode - you can submit additional data from other form fields via `uploadExtraData`. Read the usage of [uploadExtraData](http://plugins.krajee.com/file-input/plugin-options#uploadExtraData).
