### ISSUE TITLE
how to read back initialpreview

### ISSUE THREAD

**Issue by cutemonster** [kartik-v/bootstrap-fileinput#1331]
I need to get all the images names in a form and then submit along with a form.
how can i get all the files currently loaded?
Also, how does this plugin trigger a sort event so that the server can react and send back initialpreview?

thanks,

**Comment by kartik-v** [comment]
Read the following in the docs:

- For initialPreview sort  - use the [filesorted event](http://plugins.krajee.com/file-input/plugin-events#filesorted). This will give you all details to fire the ajax request and sort file stack on your server.
- To read thumbnails in the preview use the [getFrames method](http://plugins.krajee.com/file-input/plugin-methods#getFrames) - you can go through the examples and use the CSS filters to filter only initial preview files as mentioned in the `getFrames` method documentation
