### ISSUE TITLE
选择完一个文件后，更改本地文件路径，IE11上传成功，firefox、chrome失败，IE11为什么可以成功？

### ISSUE THREAD

**Issue by loveright** [kartik-v/bootstrap-fileinput#1338]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.IE11浏览器下选择一个文件。
2.更换该文件的存储位置，如从D盘换到E盘。
3.IE11,正常上传，Firefox、chrome可以捕获上传失败信息。
4.IE11为什么可以正常上传？

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:jquery-1.10.2
- bootstrap-fileinput version:bootstrap-fileinput v4.4.8

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Sorry this is a browser specific behavior and not anything that can be done within the plugin. You may need to report this to Microsoft/IE development team.
