### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by SteveDCronin** [kartik-v/bootstrap-fileinput#134]
1) is it possible to trigger the file upload with jquery instead of user click?  how to do this?

2) after a 'filebrowse' event how can I obtain the name of the file shown in the caption with jquery?

**Comment by kartik-v** [comment]
>is it possible to trigger the file upload with jquery instead of user click

Yes... read docs and use the `upload` method

> after a 'filebrowse' event how can I obtain the name of the file shown in the caption with jquery

A `filebrowse` event is generated when the fileinput button is clicked. You can directly read the input value and get details of the file selected.
