### ISSUE TITLE
custom placeholder 'Select file...'

### ISSUE THREAD

**Issue by karProgrammer** [kartik-v/bootstrap-fileinput#1340]
How can I customize the placeholder (select file...) ?

**Comment by kartik-v** [comment]
If you are looking at a translation for your language you can just try to [setup the `language` property](http://plugins.krajee.com/file-input/plugin-options#language)

If you just want to override this specifically - you can [set the `msgPlaceholder` property](http://plugins.krajee.com/file-input/plugin-options#msgPlaceholder).

**Comment by karProgrammer** [comment]
How can I set the msgPlaceholder property in yii2 I set it inside 'options' and 'pluginOptions' but does not work
