### ISSUE TITLE
What's the best way to upload photos or videos but not both together in one input?

### ISSUE THREAD

**Issue by DanielDanielDanielD** [kartik-v/bootstrap-fileinput#1344]

**Comment by DanielDanielDanielD** [comment]
Uploading photos and videos in one input but not both together in the same one input?

**Comment by DanielDanielDanielD** [comment]
>I've found some way to do it, but it's missing the way to identify the file..

`///////////////////////////////////////////////////////

    if ($("#kv-explorer").fileinput({ allowedFileTypes: ["image"] }) === true && $("#kv-explorer").fileinput({ allowedFileTypes: ["video"] }) === true) {
        alert("You can not upload photos and videos together");
        $("#kv-explorer").fileinput("clear");
    }
    else {
        alert("Excellent");
    }`

**Comment by DanielDanielDanielD** [comment]
Happy to share with you my solution of doing it right..

`$('#kv-explorer').on('filebatchselected', function (event, files) {`
`var compareImagesVideos = "";`
`for (i in files) {`
`compareImagesVideos += files[i].type;`
`}`
`if ((compareImagesVideos.indexOf("image") > -1) && (compareImagesVideos.indexOf("video") > -1)) {`
`alert("Together");`
`}`
`else {`
`alert("Not Together");`
`}`
`});`

**Comment by kartik-v** [comment]
Actually you can do this with just setting `allowedFileTypes` and/or `allowedFileMimeTypes`
