### ISSUE TITLE
progress bar has been 0%

### ISSUE THREAD

**Issue by ryy635387058** [kartik-v/bootstrap-fileinput#1347]
Edge browser uploading files,progress bar has been 0% .Other browsers do not have this problem.

**Comment by kartik-v** [comment]
It is a known issue with Microsoft edge... See [this SFO issue](https://stackoverflow.com/questions/43942396/ajax-file-upload-progress-upload-event-does-not-fire-in-edge-browser). The browser does not detect the XHR progress event.

**Comment by ryy635387058** [comment]
Thank you very much
