### ISSUE TITLE
How to add files from different directories

### ISSUE THREAD

**Issue by mehafi** [kartik-v/bootstrap-fileinput#135]
Hi,

I am using bootstrap-fileinput like that:

<form id="frmTest" action="/Home/Index" method="post" enctype="multipart/form-data">
...
<input id="inputDragDrop" name="inputDragDrop" type="file" class="file" multiple="multiple" >
<input type="submit"  />
</form>

I need have it it form and not use ajax, because files are only part of the post request, I mean files without the rest part of the form means nothing, and must be sent directly with them.

But, from the user perspective, how can I add two files, which lies in different directories? When I add first, and then add second, this second one replace first.
I thought that dropdown are could be a solution (user can drop successivly from different directories), but here:
http://plugins.krajee.com/file-input#option-dropzoneenabled
it's written that it could be only used with ajax.

So how can I achieve that?

thanks in advance

**Comment by kartik-v** [comment]
See related issue #103.

- **Using Form based submission:** HTML file input using form has its limitations. You can submit files only one by one (each time it overwrites the previous selection). If you can design your app around this go ahead.

- **Using ajax based upload:** Drag and drop or repeated multiple file selection is an ajax upload feature. It allows you more flexibility on the things you need. Your assumption is incorrect that you cannot send your other form values with ajax. You can also submit your other form input values by sending it with `uploadExtraData` variable. Check a [new web tip that I posted which contains a server processing example](http://webtips.krajee.com/ajax-based-file-uploads-using-fileinput-plugin/) on how you can upload files using this plugin using ajax.

**Comment by mehafi** [comment]
Thanks for your explanation.
finaly I decided to use form based submission and add "+" and "-" buttons dynamicly creating new instance of <input type='file'.. />. thanks to it when someone want to send more than one file need to add new input (or remove if not need).
