### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 7 column 1 of the JSON data

### ISSUE THREAD

**Issue by diddipoeler** [kartik-v/bootstrap-fileinput#1355]
i got this error by uploading an image.

**Comment by kartik-v** [comment]
Refer this repo for similar issues. You need to configure plugin and your server code correctly to read and write a correct JSON response.

Your query is answered in this [web tip](http://webtips.krajee.com/question/json-syntax-error-bootstrap-fileinput/)
