### ISSUE TITLE
Using v4.5.2, error loading the piexif.js library still exists

### ISSUE THREAD

**Issue by newscloud** [kartik-v/bootstrap-fileinput#1356]
Seeing this error on your demo page (http://demos.krajee.com/widget-details/fileinput#basic-usage) as well as on my attempts to use the plugin.

Using v4.5.2 

Also seeing:
 bootstrap-fileinput: "photo-attachment_1": Error loading the piexif.js library.

piexif.js shows it is loaded in source on the page from your plugin

<?= FileInput::widget([
    'model' => $model,
    'attribute' => 'attachment_1[]',
    'options' => ['multiple' => true,
    'autoOrientImage'=>false]
  ]); ?>

_Originally posted by @newscloud in https://github.com/kartik-v/bootstrap-fileinput/issues/1286#issuecomment-461568885_

**Comment by samuelexyz** [comment]
Same error for me

**Comment by kartik-v** [comment]
Sorry cannot see or reproduce this issue on the demo page as suggested. Ensure you are not running a stale cached version of the page on your browser (clear browser cache/restart and retry).
