### ISSUE TITLE
delete file with autoupload

### ISSUE THREAD

**Issue by grandgite** [kartik-v/bootstrap-fileinput#1358]
Hello,
I search here and in exemple but i don't found solution.
I have the plugin without autoupload and everything is fine. i Can upload, delete etc...

Today i try to change and to do autoupload. And with this method file are uploaded but if i click on the delete button the preview is deleted but there is no ajax send so file is not deleted in the server.

I look the exemple and i have a json response like that when i upload an image 

``[{"initialPreview":["http:\/\/monsite.test\/storage\/photos\/1550064683-plo.JPG"],"initialPreviewAsData":true,"initialPreviewConfig":[{"caption":"http:\/\/monsite.test\/storage\/photos\/1550064683-plo.JPG","width":"120px","key":175}]}]`

`
I just added initialPreviewAsData":true like in exemple on website. The delete url is directly in the form page like that 
```

<script type="text/javascript">
        var $el1 = $("#centreimage");
        $el1.fileinput({
            theme: 'fa',
            uploadUrl: "{{route('admin.auth.image.upload')}}",
            uploadAsync: false,
            resizeImage: true,
            maxImageWidth: 200,
            showUpload: false, // hide upload button
            showRemove: false, // hide remove button
            maxImageHeight: 200,
            resizePreference: 'width',
            resizeImageQuality : 0.6,

            uploadExtraData: function() {
                return {
                    _token: "{{ csrf_token() }}",
                    centreid: "{{ $centre->id }}",

                };
            },
            fileType: "any",
           overwriteInitial: false,
            initialPreviewAsData: true,
            initialPreview:
                [

                    @foreach ($photos as $photo)

                        "{{URL::to('/')}}/storage/photos/{{$photo->url}}",

                    @endforeach

            ],
            initialPreviewConfig: [
                    @foreach ($photos as $photo)
                {caption: "{{$photo->url}}", size: 576237, width: "120px", key: {{$photo->id}}  },

                @endforeach
                ],

            deleteUrl: "{{route('admin.auth.image.delete')}}",
            deleteExtraData: function () {
                return {
                    _token: "{{ csrf_token() }}",

                };
            },
        }).on("filebatchselected", function(event, files) {
            $el1.fileinput("upload");
        });


    </script>

```
DO you have idea of what i forgot please ?

**Comment by kartik-v** [comment]
You may need to check if you have updated release of the plugin code and also cross check if you have any errors on your page. Unfortunately cannot reproduce your error. If you have a reproducible demo or JS Fiddle or similar - please share to check and will reopen this issue.
