### ISSUE TITLE
throwing error when upload multiple files with property 'minFileCount' set using form submition

### ISSUE THREAD

**Issue by yudianer** [kartik-v/bootstrap-fileinput#1360]
Thank you for providing this tool for us. It is really great.
Here I want to upload 2 files at one time through form submission without ajax.
From "Usage Modes" I find it is available. But actually "You must select at least 2 files to upload" keep throwing.
Thank you very much.
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
`<form enctype="multipart/form-data">
        <div>
            <input id="input-freqd-1" name="input-fcount-1[]" multiple type="file" >
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>`

2.
`$("#input-freqd-1").fileinput({
            minFileCount:2,
            uploadAsync:false,
	    validateInitialCount: true,
	    overwriteInitial: false,
            allowedFileExtensions: ["jpg", "png", "gif"]
    });`
3. select 2 files at one time, click submit button, and I get error message:'You must select at least 2 files to upload.'

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

**Comment by kartik-v** [comment]
Sorry could not reproduce your issue. You could try updating to the latest release of the plugin and retry.

An example of [min count validation is provided here in the demo](http://plugins.krajee.com/file-count-validation-demo#min-ajax). Try selecting some file and deleting some other.

If your issue repeats, create a new issue and share a JS fiddle to reproduce. Thanks.
