### ISSUE TITLE
how to callback without uploading a file

### ISSUE THREAD

**Issue by DanteYuki** [kartik-v/bootstrap-fileinput#1361]
When i am using file-input, I came into this trouble.
I use file-input to show a person's information including photo and some basic information,
but when I'am update this information and I don't want to change this picture, So I choose
uploadExtraData. But right because I don't upload a picture , I cannot call fileuploaded this callback function. 
And when I change this person's photo, everything is quite right.
So I don't understand how can I callback when ajax request is completed without uploading a picture?

**Comment by kartik-v** [comment]
Use [filebatchuploadcomplete](http://plugins.krajee.com/file-input/plugin-events#filebatchuploadcomplete)
