### ISSUE TITLE
View Details does not work on bootstrap 3x, adds, deletes, opens thumbnail and does not view detail.

### ISSUE THREAD

**Issue by agfranca** [kartik-v/bootstrap-fileinput#1366]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by agfranca** [comment]
Modify the entries for bootstap 3.4.1

**Comment by kartik-v** [comment]
Cannot reproduce your issue? Can you share a JS Fiddle to understand what you are doing and where it maybe going wrong for you?

**Comment by agfranca** [comment]
https://jsfiddle.net/AlexandreFranca/uqxgyamf/8/



Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Kartik Visweswaran <notifications@github.com>
Enviado: Friday, March 15, 2019 12:54:55 AM
Para: kartik-v/bootstrap-fileinput
Cc: agfranca; Author
Assunto: Re: [kartik-v/bootstrap-fileinput] View Details does not work on bootstrap 3x, adds, deletes, opens thumbnail and does not view detail. (#1366)


Cannot reproduce your issue? Can you share a JS Fiddle to understand what you are doing and where it maybe going wrong for you?

**Comment by kartik-v** [comment]
You have not loaded the `bootstrap.js` for 3.4.1 version correctly. You are loading an invalid library file `bootstrap.bundle.min.js`. You need to load `bootstrap.min.js`

The `bootstrap.bundle.min.js` is available only for bootstrap 4.x.

Here is your [corrected fiddle](https://jsfiddle.net/qcsfpg51/).
