### ISSUE TITLE
ajax time out

### ISSUE THREAD

**Issue by stereo720712** [kartik-v/bootstrap-fileinput#1372]
execuse me,
I have a long upload request , but , fileInput will show internal error and server still execute for response.
Does anyone know how to set timeout for the plugin?
Thank you all.

**Comment by kartik-v** [comment]
You can set the `timeout` property within the configuration object below (_for ajax uploads only_).

- [`ajaxSettings`](http://plugins.krajee.com/file-input/plugin-options#ajaxSettings) for file uploads
- [`ajaxDeleteSettings`](http://plugins.krajee.com/file-input/plugin-options#ajaxDeleteSettings) for file deletes

**Comment by stereo720712** [comment]
Excuse me , I do not know where  to set it in file-input , can you teach me?
thank you very much .

**Comment by kartik-v** [comment]
Yes you configure above as part of the fileinput plugin options.
