### ISSUE TITLE
Get the file ID

### ISSUE THREAD

**Issue by PearLinger** [kartik-v/bootstrap-fileinput#1375]
Hello, after the upload operation, can the filebatchuploadsuccess event get the file id?

![image](https://user-images.githubusercontent.com/21024206/54740229-b0fdbb00-4bf5-11e9-8720-6d323f50720d.png)

**Comment by kartik-v** [comment]
Do not get that id to identify the thumbnail. Get the `data-fileid` attribute instead which uniquely identifies the file. This is returned via `filebatchuploadcomplete`.
