### ISSUE TITLE
Can we set initialPreview using loop for multiple images

### ISSUE THREAD

**Issue by narayandhoj** [kartik-v/bootstrap-fileinput#1376]
I am uploading multiple images, on edit I have to set any number of images in initialPreview. But I found the option to set array of images manually in initialPreview. Is there any option to set the initialPreview using some loop ?

**Comment by kartik-v** [comment]
Not clear with the query. The initialPreview and initialPreviewConfig are arrays already. You need to code your app appropriately - 

Read docs for [configuring ajax uploads](http://plugins.krajee.com/file-input#ajax-uploads) and what you can return from your server code to be read by the plugin

You can code your app accordingly as I mentioned.. options:

- you can trigger upload after files are selected return `initialPreview` and `initialPreviewConfig` via the server JSON response for the selectively uploaded files as described in [ajax demo 6](http://plugins.krajee.com/file-input-ajax-demo/6)
- you can also update initialPreview after every upload by refreshing your page to reflect the updated initialPreview that you return from your server.
