### ISSUE TITLE
Add ability to sanitize zoom cache

### ISSUE THREAD

**Issue by yadgen** [kartik-v/bootstrap-fileinput#1379]
When initialization I get duplicate value from input first contain user value and second empty string.
Happen when showZoom=true, that duplicate content.
Can I skip input file from duplicate content?

Thank you.
@kartik-v

**Comment by kartik-v** [comment]
Will look at an enhancement to ensure a better way of doing this. Currently you can loop through all inputs and skip those containing a parent having `.kv-zoom-cache` class.

**Comment by yadgen** [comment]
When I initialize, I have multiple radio. I want to select one by default. kv-zoom-cache has duplicate content.

Thank you.
@kartik-v

**Comment by kartik-v** [comment]
Recording an enhancement for this

**Comment by yadgen** [comment]
> Recording an enhancement for this

Where?

**Comment by kartik-v** [comment]
> > Recording an enhancement for this
> 
> Where?

This issue will act as an enhancement request.

**Comment by yadgen** [comment]
> > > Recording an enhancement for this
> > 
> > 
> > Where?
> 
> This issue will act as an enhancement request.

Ok, Thank you.
I found that the custom tag component will be copied to the kv-zoom-cache class.
