### ISSUE TITLE
Extra data not submitted in V5

### ISSUE THREAD

**Issue by leider** [kartik-v/bootstrap-fileinput#1381]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. create a test case using extra attributes in upload with V 4.5.3 (as "data-" params)
2. check the post data on server for the extra data
3. perform with v5 -> extra data not existing

Sorry for being very frank here. I haven't had the time yet to isolate the problem.

It shows when updating to v5.

Will try to isolate problem next month if not solved until then.

Your widget is used here: https://github.com/leider/JC-Backoffice

**Comment by kartik-v** [comment]
Thanks - could reproduce this... Have recorded a bug which will be fixed.
