### ISSUE TITLE
Better defaults for `resumableUploadOptions.chunkSize` and `progressDelay`

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#1382]
Set defaults for `progressDelay` to `0` and `resumableUploadOptions.chunkSize` to `2048 KB` i.e. (`2 MB`)

**Comment by Kwaadpepper** [comment]
Just a question, why is chunkSize value always 2097152, or a fixed value ? Should it be updated to match HTTP Content-Length ?

**Comment by kartik-v** [comment]
> Just a question, why is **chunkSize** value always 2097152 on HTTP requests ?

It is the default setting for `resumableUploadOptions.chunkSize` - of `2048 KB` (i.e. `2 MB`) ... you can override it to whatever value you want for your use case.

**Comment by Kwaadpepper** [comment]
Sorry but did not meant on ```resumableUploadOptions.chunkSize``` but on the HTTP request sent by the bootstrap-fileinput code.

**Comment by kartik-v** [comment]
I am not clear with the question. The HTTP content size will match the size of each FILE CHUNK that is being sent... which is controlled by the `resumableOptions.chunkSize` for example if a 11 MB file is being uploaded with `2048 KB` as the chunk size ... the first 5 chunks will each have a size of `2MB` or `2097152 bytes` .... and the last 6th chunk will have the remaining `1MB` as the size.

**Comment by Kwaadpepper** [comment]
This is correct, I understand this, but in practice, the last chunk upload, is sent with the parameter ```chunkSize: 2MB```, even if it is smaller.

Following your example the remaining chunk is ```1MB``` but when it is sent on HTTP, ```chunkSize``` value sent to server is ```2MB```. It should be ```1MB``` no ?

**Comment by kartik-v** [comment]
Yes... But you can directly get the blob size received on server on your server code - isn't it? If you are reading `resumableOptions.chunkSize` for doing that its wrong... it is a constant setting.

**Comment by kartik-v** [comment]
So to clarify - the `chunkSize` your receive on server is to be used by the server only to understand what is the maximum size of each chunk set in your plugin's configuration based on which you can write your server code to find missing chunks for the entire file or test a partial upload.

To get the actual chunk size of the blob you must use your server code to calculate the actual size and return the size.

**Comment by Kwaadpepper** [comment]
Ok my bad, i misunderstood that. It's just that I had no idea what usage could be done of the ```chunkSize``` ("maxChunkSize" ) sent to the server.

**Comment by kartik-v** [comment]
So to clarify again - the `chunkSize` your receive on server is to be used by the server only to understand what is the maximum size of each chunk set in your plugin's configuration based on which you can write your server code to find missing chunks for the entire file or test a partial upload.

To get the actual chunk size of the blob you must use your server code to calculate the actual size and return the size. For example in PHP the uploaded chunk size for a chunk name `chunk01` can be found by:

```php
size= $_FILES['chunk']['size'];
```

**Comment by Kwaadpepper** [comment]
Ok thank you. I was thinking also why sending this value if we can get it by inspecting the uploaded file length ?  I have my answer.
