### ISSUE TITLE
The [ .on('filepreupload', function(event, data, previewId, index)]

### ISSUE THREAD

**Issue by LuuFe** [kartik-v/bootstrap-fileinput#1384]
the param 'data', its a array ,
 like filename ; like filescount ,
How should I use data.files[0],
and how to get the real filepath ?

**Comment by kartik-v** [comment]
Its a array of file blobs that you selected.`file.name` or `file.path`

**Comment by LuuFe** [comment]
> Its a array of file blobs that you selected.`file.name` or `file.relativePath`

uhh , i am a rookie，thanks for ur reply!
