### ISSUE TITLE
resizeImage seems doesn't work

### ISSUE THREAD

**Issue by j200300** [kartik-v/bootstrap-fileinput#1385]
## Steps to reproduce the issue
Hi kartik,

I'm trying to use this plugin with option `resizeImage`.
And I try it on <a target="_blank" href="http://plugins.krajee.com/file-image-management-demo#image-resize-width">demo page</a>

When I choose a img, console shows
`f.getFile is not a function`
Same as my project shows.

And.. the img not resize as expected, 

Thanks for for any help.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 5.0.1

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-image-management-demo#image-resize-width)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by ScaleRunner** [comment]
This issue happens to me as well. I included the `piexif.js` [file](https://github.com/hMatoba/piexifjs/blob/master/piexif.js) from the github repo as well

**Comment by kartik-v** [comment]
Resolved via latest commit.
