### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by siroccosh** [kartik-v/bootstrap-fileinput#1386]
1. upload an classic xlsx file in http://plugins.krajee.com/file-input/demo and on my web sites
2. Preview is not good
2. I see this on all my new computer on Windows 10 64bits with last version of Chrome or Firefox

Do you have an idea of the problem  ? 

![image](https://user-images.githubusercontent.com/4971510/55226063-5f1bed00-5214-11e9-845c-622768ea2c0d.png)

**Comment by kartik-v** [comment]
Can you share a JS Fiddle to reproduce your issue.

Cannot unfortunately reproduce your issue at my end.

**Comment by kartik-v** [comment]
Closing this currently. In case you have a method to reproduce this please update and will reopen.
