### ISSUE TITLE
上传视频时候的可以播放的预览缩略图怎么设置

### ISSUE THREAD

**Issue by zyxyunxin** [kartik-v/bootstrap-fileinput#1388]
![111](https://user-images.githubusercontent.com/48385531/55455476-5c573880-5616-11e9-8ffa-2493565f82ce.PNG)

预览时候是空白

**Comment by kartik-v** [comment]
The video preview will happen automatically as long as the source video format is supported by HTML5 to be displayed via preview.

Refer for [HTML5 supported video file formats here](https://www.w3schools.com/html/html5_video.asp).

Also the [`maxFilePreviewSize`](http://plugins.krajee.com/file-input/plugin-options#maxFilePreviewSize) controls the size of the file that will be read into browser memory before displaying the preview - if your file size is larger than this setting - it will not be displayed for preview.
