### ISSUE TITLE
Append extra Data for every File

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/bootstrap-fileinput#140]
I have for every file a new input for the title of the file. What I need is something to put this titles for every file in the request. The problem is, that they need a key or something to recognize for which image the title is. In the upload process of the fileinput there is the line `self.uploadExtra(formdata)`, which does not give any ID or something for the recognition, so there is no way to do that with the `uploadExtraData` or `uploadExtra` function to do that. Is that even possible?

My options are:
```javascript
$input.fileinput({
uploadUrl: $form.attr('action'),
multiple: true,
uploadAsync: true,
layoutTemplates: {
	image: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}">\n' +
			'   <img src="{data}" class="file-preview-image" title="{caption}" alt="{caption}" ' + '>\n' +
			'   {footer}\n' +
			'</div>\n',
	footer: '<div class="file-thumbnail-footer">\n' +
			'    <div class="file-caption-name" style="width:{width}">{caption}</div>\n' +
			'	<input type="text" name="object[filesData][{fileindex}]"/>' +
			'</div>',
    }
});
```

**Comment by kartik-v** [comment]
You can have these as an array and json_encode and send it with extra data.

For example:
```js
titles = {'id-0': 'file-name-1', 'id-1': file-name-2'};
$input.fileinput({
     uploadExtra: {
             titles: JSON.stringify(titles)
     }
});
```
Then json_decode the `titles` on your server to read the individual file details.

**Comment by kartik-v** [comment]
The filestack is sent as an array to the server. The zero based index of each element in array, matches the data-fileindex for the preview thumbnail.

**Comment by thejahweh** [comment]
Thats true, if you send it via batch, but in my case with the async method, it is not possible that way.

It would be possible if the index of the current file would be accessible in the uploadExtraData function. Here is an ugly hack, which worked for me, but i had to copy/override the whole upload function.
```javascript
// Functions which are needed
var isEmpty = function (value, trim) {
    return value === null || value === undefined || value == []
    || value === '' || trim && $.trim(value) === '';
}, addCss = function($el, css) {
    $el.removeClass(css).addClass(css);
}
// Extend it
var fileinputExtension = {
    getExtraData: function(previewId, index) {
        var self = this, data = self.uploadExtraData;
        if (typeof(self.uploadExtraData) == "function") {
            data = self.uploadExtraData(previewId, index); // MAGIC
        }
        return data;
    },
    uploadExtra: function(fd, previewId, index) {
        var self = this, data = self.getExtraData(previewId, index); // MAGIC
        if (data.length == 0) {
            return;
        }
        $.each(data, function(key, value) {
            if (!isEmpty(key) && !isEmpty(value)) {
                fd.append(key, value);
            }
        });
    },
    upload: function(i, files) {
        ... // Some copy&paste code
        self.uploadExtra(formdata, previewId, i); // MAGIC
        ... // Some copy&paste code
    },
};
$.extend($.fn.fileinput.Constructor.prototype, fileinputExtension);
```
Then in the `uploadExtraData` function it is possible to do it like:
```javascript
uploadExtraData: function(previewId, index) {
	var obj = {}
	$form.find('#' + previewId + " input").each(function() {
		var id = $(this).data('name');
		var val = $(this).val();
		obj[id] = val;
	});
	return obj;
}
```

Another Problem is, that after the server side process, there is no way to apply data from the server like an ID to recognize it after the upload. If the `fileuploaded` event would get the response data then would that also be possible.

**Comment by kartik-v** [comment]
Will look at it as an enhancement.

**Comment by joelZC** [comment]
@

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

1. 

[1. ](

> _**### url**_

)

**Comment by joelZC** [comment]
good afternoons im programming in asp.Net mvc 6 vNext and i implementing this inputfile, but i have a problem in my AvtionResulto i return the view index but the view appears into of div with class .file-error-message and i dont know how fix, might help me please?

**Comment by joelZC** [comment]
also appear this mistake " 23.jpg: SyntaxError: Unexpected token <. "

**Comment by joelZC** [comment]
![mistake](https://cloud.githubusercontent.com/assets/11599718/12831265/fa67b3ac-cb58-11e5-843e-44da3b70c4d9.PNG)

**Comment by josemsalves** [comment]
Token expected position 0... Why?
