### ISSUE TITLE
Ajax not working

### ISSUE THREAD

**Issue by p178899** [kartik-v/bootstrap-fileinput#1401]
I read this:
https://github.com/kartik-v/bootstrap-fileinput/issues/797
but my asp classic script not working when i try to remove thumbnail from preview or upload the file. I have the error: Method not allowed.

The same script without Ajax works perfecly! I use Persist Aspupload to upload file available with Aruba hosting services.

thank for your patience :-)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is more to do with your server code that can be called via any AJAX POST or similar action. Sorry there is not much to do in this plugin. What I suggest is try to TEST your delete AJAX server action via a normal button click via AJAX and debug to resolve your issue. If you feel there is something specific to the plugin - please update and will reopen this issue.

**Comment by p178899** [comment]
Try this please:
http://www.folcom.it/demo/dbox/prova.asp
(only "delete icon" of previewed files)

Result is:
Errore HTTP 405.0 - Method Not Allowed

**Comment by kartik-v** [comment]
As I mentioned please debug that on your server side (it seems to be an issue with the POST method access control on your server environment). 

Try to test your code without any of the plugin scripts and on a plain HTML page call the DELETE URL action via ajax from a simple HTML button click and try to debug .
