### ISSUE TITLE
Preview Data Bug when Selecting Duplicates in certain way

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [kartik-v/bootstrap-fileinput#1402]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [X] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Note: I've seen this problem only with images, but I'm almost certainly that it may happen to any kind of file.

Note2: It doesn't seems to be directly related to the upload procedure, so try it out in the case that the preview will only load the image but not upload it.

1. Open the browser and select 3 files (can be more, but this is the simplest) and press OK;
2. Wait for all images to load in the preview.
3. Open the browser again, but now select 4 files in which 3 of those are the 3 you've selected before and press OK.
4. Wait for the new image to load. You'll be given error messages because of duplicates. No problem until there. (Optinally you can click on the removes of the "preview failed" objects)
5. Open the browser and now select the previous 3 images you've selected in the 1st step.

## Expected behavior and actual behavior

When I follow those steps something bad happens. In my tests, with the default theme, usually the 3 selected for the second time are added to the preview (step 5), and the "fileimageloaded" is triggered again, as if those were added (but their value/base64 is empty). 

In [this demo theme](http://plugins.krajee.com/file-krajee-explorer-demo#krajee-explorer-1) I'm not able to see the callbacks, but doing so will remove (visually) from the preview the 4th image, but it still exists in within the library structures (try removing the 3 visually left and you'll see that it doesn't show the "drag files here" message, but no previews exists [clearing works to reset]).

From my point of view, this seems a problem with the preview list of files and/or the id's of the images browsed. The expected behaviour is simply images not being included nor any callback of "fileimageloaded" happening, since no new images were added in step 5.

## Environment

Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.4.0
- bootstrap-fileinput version: 5.0.2

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/xuhazixeju/edit?html,js,console,output)

**Comment by kartik-v** [comment]
I am not able to exactly reproduce the issue?  Can you share a JS fiddle to reproduce your issue and share screenshots if any.

**Comment by Marcelo-Petrucelli** [comment]
Hello @kartik-v 

I did make a JSBin with the problem: https://jsbin.com/xuhazixeju/edit?html,js,console,output
I'll take some screenshots asap and edit this post. Thanks for the fast response.

**Comment by kartik-v** [comment]
Can you retry this with the unreleaed version 5.0.3 from dev-master of this repo. There are some updates in that version that would not show the duplicate images.

**Comment by Marcelo-Petrucelli** [comment]
I sure will. I'll let you know by tomorrow around this same time. I'll edit this post as well.
