### ISSUE TITLE
for each file preview different fileActionSetting like showRemove

### ISSUE THREAD

**Issue by tinarathod** [kartik-v/bootstrap-fileinput#1403]
Is it a way to give diffrent fileActionSetting option for each preview file.  I want to hide remove button from preview of some file  only. I have tried on config array to not to set URL for that files which I want to hide remove button. but it still shows. 

Any way to dynamic FileActionSetting for Remove, Drag etc.

**Comment by kartik-v** [comment]
Read docs.  You can control the showXXXX actions within fileActionSettings to be set up as a javascript callback function which will be dynamically executed.

**Comment by tinarathod** [comment]
......               
                 initialPreviewConfig: JSON.parse(datafile['config'].replace(/&quot;/g,'"')),
              
                fileActionSettings: {
                    showDelete: function(config){
                        if(config.type == 'pdf'){
                            return false;
                        }
                        return true;
                    }
                },
.....

This is what I have did already. but still it shows delete button on pdf files.

**Comment by tinarathod** [comment]
thank you. added on server side where I built config.
