### ISSUE TITLE
How to get ajax response on fileuploaded event when enableResumableUpload property to true

### ISSUE THREAD

**Issue by shanjiechen** [kartik-v/bootstrap-fileinput#1405]
Hi, I want use chunk file upload, How to get ajax response on fileuploaded event when enableResumableUpload property to true ? Or how to get the file url from server response after upload used to form.

The docs say like this:

> Resumable Uploads
> The additional parameters available with this event for resumable uploads are:
> 
> previewId: string, the identifier of each file's parent thumbnail div element in the preview window.
> 
> index: string, the zero-based index of the file in the file stack.
> 
> fileId: string, the unique file identifier for the selected file.

**Comment by kartik-v** [comment]
You will not get ajax response on `fileuploaded` event for resumable uploads. In case of resumable uploads there is an ajax request fired for every file chunk (not a whole file). So you need to use events like [filechunksuccess](http://plugins.krajee.com/file-input/plugin-events#filechunksuccess) to check success of a file chunk successfully uploaded. Refer the [resumable events section](http://plugins.krajee.com/file-input/plugin-events#resumable-events) for understanding various resumable upload specific events.
