### ISSUE TITLE
Possibility to use with a form validator

### ISSUE THREAD

**Issue by dgateles** [kartik-v/bootstrap-fileinput#1406]
This plugin generates a div with input characteristics but the input is on behind of that.
With a form validator, it does not work correctly.
Have an solution to use this plugin with a form validator?

**Comment by kartik-v** [comment]
What would you like to do with a form validator for the native file input? You can definitely build your own rules or implement third party validation engine anyway on the native file input if desired (but that will be only applicable for non-ajax form submission based mode).

For ajax based uploads you need to use properties within the plugin to achieve your needs (e.g. required property, minimum/maximum file count, minimum/maximum file size, allowedFileTypes etc.).
