### ISSUE TITLE
Refresh defaultPreviewContent doesn't work

### ISSUE THREAD

**Issue by itajackass** [kartik-v/bootstrap-fileinput#1408]
I'm using latest 5.0.3 and i'm try to refresh the defaultPreviewContent attribute on press button, but no images are show.

    $("#btn").on("click", function(e) {
		e.preventDefault();
		$('#avatar').fileinput('refresh', {defaultPreviewContent: '<img src="https://helpx.adobe.com/in/stock/how-to/visual-reverse-image-search/_jcr_content/main-pars/image.img.jpg/visual-reverse-image-search-v2_1000x560.jpg" alt="default">' } );
	});

**Comment by kartik-v** [comment]
Currently `refresh` does not work on refreshing initial or default preview content. You need to do a `destroy` and reinitialize for that.
