### ISSUE TITLE
external trigger

### ISSUE THREAD

**Issue by jflamman** [kartik-v/bootstrap-fileinput#141]
Hey, love your work - library almost does everything I need for my project.

But.. I would like to trigger it from an alternate source (in my case '#uploadPhoto'). 
I can only get it done with a workaround.

Add CSS: .file-input.file-input-new{display:none;}
Add JS:

        $('#uploadPhoto').on('click', function(){$('#input-4').trigger('click')});
        $('#input-id').on('filebrowse', function(event) {
            $('.file-input.file-input-new').show();
        });

It feels like such an ugly hack though - and your library is so full of options - either I'm missing something or I'm hereby submitting a feature request..
Is there a proper way to place the "browse" button no matter where - and the preview somewhere else?

I have a custom preview:

        $("#input-4").fileinput({
            showCaption: false,
            layoutTemplates : {
                preview: '<div class="file-preview panel panel-default pending">\n' +
                '    <div class="panel-heading">' +
                '    <h3 class="panel-title">' +
                '    <img class="avatar" src="/imgs/[username]-profile-20.png" width="20" height="20" alt="">' +
                '    <span class="name">[username]<span></span></span>' +
                '    </h3>' +
                '    </div>' +
                '    <div class="{dropClass}">\n' +
                '    <div class="file-preview-thumbnails panel-body">\n' +
                '    </div>\n' +
                '    <div class="clearfix"></div>' +
                '    <div class="kv-fileinput-error"></div>\n' +
                '    </div>\n' +
                '</div>',
                footer: '<div class="file-thumbnail-footer">\n' +
                '    {actions}\n' +
                '</div>',
            },
            previewSettings : {
                image: {width: "100%", height: "auto"}
            },
            //elPreviewContainer : '#timeline',
            browseIcon : '<i class="glyphicon glyphicon-camera"></i>',
            browseLabel : '',
            browseClass : ''
        });

**Comment by kartik-v** [comment]
Have you tried setting the `elPreviewContainer` to a different container identifier and try the same. You must ensure you have the content in `elPreviewContainer` defined similar to the preview layout template

**Comment by kartik-v** [comment]
Have you tried setting the `elPreviewContainer` to a different container identifier and retry? You must ensure you have the content in `elPreviewContainer` defined similar to the preview layout template.

Note `elPreviewContainer` must be a jQuery object. For example `$("#custom-container-id")`.

**Comment by jflamman** [comment]
I will try tonight, thanks for the quick response!

**Comment by jflamman** [comment]
elPreviewContainer did not achieve my goal. The behavior after defining custom HTML for the preview template in the layoutTemplates.preview option, or putting the HTML somewhere on the page and referring to it in the elPreviewContainer option seems to be identical: the "browse" button and the image preview still appear in the same place.

But... Your suggestion pointed me in the right direction and I was able to achieve what I want through the option elPreviewImage.

Recap: I want an elegant camera icon in the navigation bar that triggers a file upload. The image preview is shown in real size in the "timeline" exactly how it would look like after the upload.

Solution: I have a hidden container, id "filepreview". Inside the container - where the preview image should go is a div, id "fileInputPreview". The listener is bound  to a div in the navigation bar, id'ed "input-4".

Javascript:

        $('#input-4').on('fileloaded', function(event) {
            $('#filepreview').show();
        });

        $("#input-4").fileinput({
            showCaption: false,
            layoutTemplates : {
                preview: '<div class="file-preview-thumbnails panel-body"></div>\n'
            },
            previewSettings : {
                image: {width: "100%", height: "auto"}
            },
            elPreviewImage : '#fileInputImg',
            showUpload : false,
            showCancel : false,
            showCaption : false,
            showRemove : false,
            browseIcon : '<i class="glyphicon glyphicon-camera"></i>',
            browseLabel : '',
            browseClass : ''
        });

**Comment by Nagendra080389** [comment]
@jflamman  Can you share an example how to use elPreviewContainer as a template, I have a requirement like this: https://github.com/kartik-v/bootstrap-fileinput/issues/1427
And I think `elPreviewContainer` can help me with this. I am not able to find any example regarding this.

**Comment by gerbert92** [comment]
Hi @jflamman  I would appreciate it if you could share your experience on creating a custom preview container as you described through the **elPreviewImage** option.  I would like to see the **html** and **jquery** codes to get a grip on how you went around it. Thanks in advance..
