### ISSUE TITLE
Use fileinput without ajax

### ISSUE THREAD

**Issue by fouad1994** [kartik-v/bootstrap-fileinput#1411]
I am trying to use the plugin without ajax but with drag and drop how to enable drag and drop without ajax url or uploadAsync parameter?
All I need is dropping images in dropzone or via browse with sorting and upload images by submit the whole form not through the plugin how to do that and thank you

**Comment by kartik-v** [comment]
Please use the forums and comments section on the site for programming related help for your application. Report only plugin related bugs or enhancement requests here.

Read the docs for understanding what is possible in [form vs ajax mode of submission](http://plugins.krajee.com/file-input#modes-compared).
