### ISSUE TITLE
How could I run custom codes after every ajax request?

### ISSUE THREAD

**Issue by xtremforce** [kartik-v/bootstrap-fileinput#1412]
How could I run custom codes after every ajax request? no matter success or not.
I need to update the token from the response, is there a event for that?

**Comment by kartik-v** [comment]
Go through the plugin events documentation. Depending on your plugin configuration (whether async, sync or resumable)  - use the appropriate events ending with `complete`. For example one or more of the below:

- [filebatchuploadcomplete](http://plugins.krajee.com/file-input/plugin-events#filebatchuploadcomplete)
- [fileuploaded](http://plugins.krajee.com/file-input/plugin-events#fileuploaded)
- [filechunkcomplete](http://plugins.krajee.com/file-input/plugin-events#filechunkcomplete)
