### ISSUE TITLE
How can I disable the form after the file upload event?

### ISSUE THREAD

**Issue by credocoder** [kartik-v/bootstrap-fileinput#1414]
Did so but something it does not work
`$("#file").on('fileuploaded', function(event, previewId, index, fileId) {
    $("#file").fileinput('clear').fileinput('disable');
   //$("#file").fileinput('clear').fileinput('lock').fileinput('disable');
});`

**Comment by kartik-v** [comment]
Not clear with the query. What form??? Are you talking about disabling the input - it does work. Check [this demo for an example of using plugin methods to disable/enable and do other operations](http://plugins.krajee.com/file-plugin-methods-demo). Cross check your code and plugin config. In case you are facing any issue - please share a JS Fiddle to reproduce your issue and will reopen this issue.
