### ISSUE TITLE
 Server cannot receive values that parameter for uploadExtraData

### ISSUE THREAD

**Issue by soloves** [kartik-v/bootstrap-fileinput#1415]
Hi, great plugin. I have a question about the usage of uploadExtraData.
I see two ways, and I think they correspond to synchronous and asynchronous submissions, respectively.

First example, I guess it's for asynchronous operations. 
`uploadExtraData:fuction(priviewId,index){
     return {
          'key':'value'
     };
}`

Another one for synchronization
`uploadExtraData:{
          'key':'value'
}`

But neither of them works properly for me.
**Here is my code.**
`initCover("cover",uploadUrl);
		function initCover(ctrlName, uploadUrl) {
			var control = $('#' + ctrlName);
			control.fileinput({
				language: 'zh', 				
				uploadUrl: uploadUrl, 						
				allowedFileExtensions: ['jpg', 'gif', 'png','bmp','jpeg'],	
				minFileCount: 1,                           
				maxFileCount: 1,                           
				maxFileSize: 0,		
				minFileCount: 0,
				uploadAsync: false,
				showUpload: false,
				showPreview: false,					
				showCaption:true,                  
				browseLabel: '选择图片',                  
				enctype: 'multipart/form-data',
				uploadExtraData:function(){
					return {
					    'uploadType':'cover',
                                            'dateStamp':dateStamp,
                                        };
				},
				previewFileType: 'image',
			}).on("filebatchselected", function() {
				$("#cover").fileinput("upload");
			});
		}`
**I also tried this:**
`initCover("cover",uploadUrl);
		function initCover(ctrlName, uploadUrl) {
			var control = $('#' + ctrlName);
			control.fileinput({
				language: 'zh', 				
				uploadUrl: uploadUrl, 						
				allowedFileExtensions: ['jpg', 'gif', 'png','bmp','jpeg'],	
				minFileCount: 1,                           
				maxFileCount: 1,                           
				maxFileSize: 0,		
				minFileCount: 0,
				uploadAsync: false,
				showUpload: false,
				showPreview: false,					
				showCaption:true,                  
				browseLabel: '选择图片',                  
				enctype: 'multipart/form-data',
				uploadExtraData:{
					    'uploadType':'cover',
                                            'dateStamp':dateStamp
				},
				previewFileType: 'image',
			}).on("filebatchselected", function() {
				$("#cover").fileinput("upload");
			});
		}`

But I found that the server receives a null value.
Also I found that the request was sent without parameters.
Can you tell me how to deal with it? 
The version I use is v5.0.4

**Comment by kartik-v** [comment]
You need to debug your code. You should receive `uploadExtraData` separately as a POST request to your server action identified in `uploadUrl`.

**Comment by soloves** [comment]
> 
> 
> You need to debug your code. You should receive `uploadExtraData` key values separately as a POST request to your server action identified in `uploadUrl`.

Thank you very much!
 The problem has been resolved, possibly because the parameters **minFileCount** have been declared twice.
