### ISSUE TITLE
Empty CSV File validataion

### ISSUE THREAD

**Issue by Naveencheekoti** [kartik-v/bootstrap-fileinput#1418]
I have uploaded empty CSV file.On click of submit, It is calling ajax.How to stop ajax before calling ajax.How to show the validation message before calling the ajax method.
![EmptuploadFile](https://user-images.githubusercontent.com/23651242/58493915-99acf200-8191-11e9-8370-d916e51ce119.PNG)

**Comment by kartik-v** [comment]
@Naveencheekoti - please use this repo only for reporting plugin issues i.e. primarily bugs and enhancements. [Read Contributing Guidelines](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md)

For programming help use the comments and discussions section of the plugin demos site and check if someone else can help you.

For your use case, you can hide the default upload button by setting [showUpload](http://plugins.krajee.com/file-input/plugin-options#showUpload) to false and render your own upload or submit button. Do the necessary validation and call the plugin [`upload` method](http://plugins.krajee.com/file-input/plugin-methods#upload). 

Alternatively you can use [plugin events](http://plugins.krajee.com/file-input/plugin-events) and check events are called before the upload (read the docs closely).
