### ISSUE TITLE
PreviewIcon - return null instead of preset previewFileIcon

### ISSUE THREAD

**Issue by Jillustre96** [kartik-v/bootstrap-fileinput#1420]
I wonder if this is wrong in the fileinput plugin:
```
_getPreviewIcon: function (fname) {
    var self = this, ext, out = null;
    if (fname && fname.indexOf('.') > -1) {
        ext = fname.split('.').pop();
        if (self.previewFileIconSettings) {
            out = self.previewFileIconSettings[ext] || self.previewFileIconSettings[ext.toLowerCase()] || null;
        }
        if (self.previewFileExtSettings) {
            $.each(self.previewFileExtSettings, function (key, func) {
                if (self.previewFileIconSettings[key] && func(ext)) {
                    out = self.previewFileIconSettings[key];
                    //noinspection UnnecessaryReturnStatementJS
                    return;
                }
            });
        }
    }
    return out;
},
```

on the following line if (self.previewFileIconSettings), if true then return null if the previewFileIconSettings is not found. Why null? Should it be self.previewFileIconto use the default one?

Because I set the preferIconicPreview to true and upload a file not in the previewFileIconSettings and it give me nothing for icon. (we update the file ajax and return something in initialPreview to show the download button)

**Comment by kartik-v** [comment]
You need to set `previewFileIconSettings` as an object with the right configuration if you wish to use iconic preview (i.e. when `preferIconicPreview` is `true`).
