### ISSUE TITLE
Iphone image upload wrong rotate in preview

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/bootstrap-fileinput#1421]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Basically plugin fails to handle image orientation when photos are taken with iPhone in portrait position (tested on iPhone X).

## Expected behavior and actual behavior

When I follow those steps, I see image is rotated

I was expecting images to be in normal rotation

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by BenasPaulikas** [comment]
Keep in mind that this bug is on preview not after server upload. Is it possible to fix it ?

**Comment by kartik-v** [comment]
Please share your configuration code and a JS Fiddle if possible to reproduce?

**Comment by BenasPaulikas** [comment]
Hey ty for fast response. No need for JS Fiddle

http://demos.krajee.com/widget-details/fileinput
Ctrl + f FileInput Basic Usage	
And try to select portrait image from ios and it will be shown rotated by 90 degrees.

**Comment by virtuadream** [comment]
@kartik-v is there any follow up on this? 
portrait image gets mistakenly rotated by 90 degrees so that image orientation is not correct when photo is taken / uploaded using a iOS device (ie. an iPhone). NOTE: orientation issue does not affect Android phones, only iOS.

To reproduce the bug, go to: 
1. http://demos.krajee.com/widget-details/fileinput
2. Ctrl + f FileInput Basic Usage
3. And try to select portrait image from ios and it will be shown rotated by 90 degrees.
Thanks for looking into this.

**Comment by kartik-v** [comment]
Need to check this...

**Comment by kartik-v** [comment]
Folks - I have not got time to check this as I do not have an iOS device handy. 

Not sure why you are experiencing this. Check the [`autoOrientImage`](http://plugins.krajee.com/file-input/plugin-option#autoOrientImage) setting - it is set to a callback function which should prevent orientation of the image on iOS devices.

The [`autoOrientImage`](http://plugins.krajee.com/file-input/plugin-option#autoOrientImage) setting defaults to :

```js
function () { // applicable for JPEG images only and non ios safari
    var ua = window.navigator.userAgent, webkit = !!ua.match(/WebKit/i),
        iOS = !!ua.match(/iP(od|ad|hone)/i), iOSSafari = iOS && webkit && !ua.match(/CriOS/i);
    return !iOSSafari;
},
```

Try to debug and tweak the above setting and check on your device browser console and let know if the setting change works.
