### ISSUE TITLE
msgUploadErro && other msg.... error

### ISSUE THREAD

**Issue by Pilot1604** [kartik-v/bootstrap-fileinput#1423]
Properties msgUploadError, msgDeleteError do not change the value, I checked only these, the rest did not check

> echo FileInput::widget([
	'name'            => 'cars_photo',
	'pjaxContainerId' => $pjax_id,
	'options'         => [
		'multiple' => true,
		'accept'   => 'image/*'
	],
	'pluginOptions'   => [
		'deleteUrl'                => ...,
		'uploadUrl'                => ..,
		'initialPreviewAsData'     => true,
		'overwriteInitial'         => false,
		'fileActionSettings'       => [
			'showZoom' => false,
		],		
		'dropZoneTitle'            => 'Перетащите файлы сюда …',		
		'browseLabel'              => 'Добавить фото',
		'msgUploadError '          => 'Ошибка',
		'msgDeleteError '          => 'Ошибка',
		'allowedFileTypes'         => ['image'],
		'validateInitialCount'     => true,
		'maxFileCount'             => 4,
		'allowedFileExtensions'    => ['jpg', 'jpeg'],
		'removeFromPreviewOnError' => true,
	],
]);

**Comment by kartik-v** [comment]
Seems to work and the labels/msgs should change like the `browseLabel` you have set... can you share a JS Fiddle to reproduce your issue?

**Comment by Pilot1604** [comment]
JS I did not change anything, just connected the widget
