### ISSUE TITLE
上传文件完成之后发现上传错了，怎么删除已经上传的图片的原文件

### ISSUE THREAD

**Issue by TeYoMe** [kartik-v/bootstrap-fileinput#1424]
选择多张图片并且上传完成之后，发现其中一张图片上传错误，想把已经上传到本地的这张图片删除，我使用了 `filesuccessremove` 这个事件，但是获取的 id 是 `uploaded-1561104187406_17` 这样的，根据这个id我并不能确定我要删除的文件，请问我应该怎么办

**Comment by ouyangyi1998** [comment]
请教下这个问题怎么解决的？
