### ISSUE TITLE
How to add custom parameters and modify them according to the file.

### ISSUE THREAD

**Issue by JerryDtj** [kartik-v/bootstrap-fileinput#1426]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
When uploading files in ajax, I need to dynamically change the file name according to different files and add some other dynamic parameters.Then I added uploadExtraData, but it accepts static values and doesn't dynamically adapt parameters to different images.How can I customize parameters according to different files?
1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
You need to program your app accordingly. Use `uploadExtraData` as a callback.

Check [ajax upload example scenario # 7](http://plugins.krajee.com/file-input-ajax-demo/7) to understand how to setup additional fields and data via templates and tags.
