### ISSUE TITLE
Not able to create custom preview template via layoutTemplates

### ISSUE THREAD

**Issue by Nagendra080389** [kartik-v/bootstrap-fileinput#1427]
I am trying to implement file-input js like this;

Initial screen : 
![image](https://user-images.githubusercontent.com/6088582/60153988-96923980-9803-11e9-9f84-731c5a73bc2b.png)

And after upload it has to retail the drag drop section and create a preview panel right below the drop zone as table.  Like this 

![image](https://user-images.githubusercontent.com/6088582/60154050-cd684f80-9803-11e9-8423-f8b412d5d44e.png)

I tried using elContainer : but couldnot find any example related to this, Any idea or example how can I achieve this?

**Comment by kartik-v** [comment]
@Nagendra080389  use the File Explorer Theme..

For example check this [Krajee File Explorer FAS Theme Demo](http://plugins.krajee.com/file-krajee-explorer-fas-demo) and if you do not need thumbnail previews use the [hidden thumbnail content option](http://plugins.krajee.com/file-krajee-explorer-fas-demo#krajee-explorer-fas-3) as shown in the demos.

**Comment by Nagendra080389** [comment]
I did that thanks, but  there is no customization available for preview button.  If I click preview button I need to open the file new browser tab.

Even if I try to preventDefault or return false, the default zoom gets triggered.

  `$('#input-b6').on('filezoomshow', function (event, params) {
                event.preventDefault();
                return false;
            });`

**Comment by kartik-v** [comment]
Do not change default buttons behavior... add your own custom buttons via `otherActionButtons` and `fileActionSettings`.

Hide default buttons in thumbnails via `fileActionSettings`. For example hide default zoom button by setting showZoom to false within `fileActionSettings`.
