### ISSUE TITLE
File Input Refresh not Working 5.0.4 v

### ISSUE THREAD

**Issue by nageshvn** [kartik-v/bootstrap-fileinput#1428]
$(document).ready(function () {
	
$( "#btnClick" ).click(function() {
$('#input-3').fileinput('destroy'); 

$("#file-3").fileinput('refresh', { 

  theme: 'fas',
        showUpload: true,
        showCaption: false,
        browseClass: "btn btn-primary btn-lg",
        fileType: "any",
        previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
        overwriteInitial: false,
    initialPreviewAsData: true,
          initialPreview: [
            "http://lorempixel.com/1920/1080/transport/1",
            "http://lorempixel.com/1920/1080/transport/2",
            "http://lorempixel.com/1920/1080/transport/3"
        ],
        initialPreviewConfig: [
            {caption: "transport-1.jpg", size: 329892, width: "120px", url: "{$url}", key: 1},
            {caption: "transport-2.jpg", size: 872378, width: "120px", url: "{$url}", key: 2},
            {caption: "transport-3.jpg", size: 632762, width: "120px", url: "{$url}", key: 3}
        ]
		
 });
 

alert('success');
});
       $("#file-3").fileinput({
        theme: 'fas',
        showUpload: true,
        showCaption: false,
        browseClass: "btn btn-primary btn-lg",
        fileType: "any",
        previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
        overwriteInitial: false,initialPreviewAsData: true,
          initialPreview: [
            "http://lorempixel.com/1920/1080/transport/1",
            "http://lorempixel.com/1920/1080/transport/2",
            "http://lorempixel.com/1920/1080/transport/3"
        ],
        initialPreviewConfig: [
            {caption: "transport-1.jpg", size: 329892, width: "120px", url: "{$url}", key: 1},
            {caption: "transport-2.jpg", size: 872378, width: "120px", url: "{$url}", key: 2},
            {caption: "transport-3.jpg", size: 632762, width: "120px", url: "{$url}", key: 3}
        ]
      
    });
	
	
    });

**Comment by kartik-v** [comment]
It works fine as intended. 

Check the [file manipulation methods demo](http://plugins.krajee.com/file-plugin-methods-demo#manipulation-methods).

**Comment by nageshvn** [comment]
hi.  my conson is when i click button it will load some particular server files to input box
