### ISSUE TITLE
is this a bug ?

### ISSUE THREAD

**Issue by alpastar** [kartik-v/bootstrap-fileinput#1430]
Browsers :  Google Chrome(latest)
Operating System :  Windows-7 
Libraries :  jquery-3.1.1,   
                bootstrap-4.3.1
bootstrap-fileinput -> 5.0.3

$file.fileinput('getFilesCount') -> 1   // OK 

$file.fileinput('getFileList')     -> ERROR ($file.fileinput('getFileStack')  also ERROR)

fileinput.min.js:13 Uncaught TypeError: Cannot read property 'list' of undefined
    at i.getFileList (fileinput.min.js:13)
    at HTMLInputElement.<anonymous> (fileinput.min.js:13)
    at Function.each (jquery.min.js:2)
    at r.fn.init.each (jquery.min.js:2)
    at r.fn.init.e.fn.fileinput (fileinput.min.js:13)
    at <anonymous>:1:8
getFileList @ fileinput.min.js:13
(anonymous) @ fileinput.min.js:13
each @ jquery.min.js:2
each @ jquery.min.js:2
e.fn.fileinput @ fileinput.min.js:13
(anonymous) @ VM219:1

**Comment by kartik-v** [comment]
Yes this is fixed in #1413 as part of upcoming release v5.0.4 which will be released soon.
