### ISSUE TITLE
how to initial file uploaded in server 

### ISSUE THREAD

**Issue by mamadsolimani** [kartik-v/bootstrap-fileinput#1431]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by mamadsolimani** [comment]
how to initial file uploaded in server 
i upload file in DB with byte[]. but in edit form i can`t load file in krajee input file.

i have :
Bootstrap-3.3.7
jquery-3.2.1
bootstrap-fileinput v4.3.6

my code is 
`var imageByte = ... ;
if ( imageByte ) {
options['initialPreviewConfig.caption'] = label;
options['initialPreview'] = [ 'data:image/png;base64,' + imageByte ];
}`

that set options in inputfile.

only problem it show pic but in real file input is empty and server get anyThing

**Comment by mamadsolimani** [comment]
i think file input in initialize is empty and only show image

**Comment by mamadsolimani** [comment]
senario 1 : is a image and must user can remove.
senario 2:  is a image and must user can without change send to server.

i can`t see senarios in your examples ...

thanks

**Comment by kartik-v** [comment]
You may need to do some reading on file handling via HTML. The native HTML file input can only read and send data of files to be uploaded from client (not from any other server).

This plugin just enhances that capability to also allow preview of uploaded files from server. 

For editing your server images or files or something like that on your server - you need to write your own app code to read server data and edit or change them and send again. This is more an app programming for your use case.

**Comment by mamadsolimani** [comment]
hi kartik-v
thanks for your answer. 
but you have example for initial file and image, and must in file tag set value too

i very need an example in 2 senarios.
