### ISSUE TITLE
one question, please give me a help, thanks

### ISSUE THREAD

**Issue by jianjianxu** [kartik-v/bootstrap-fileinput#1432]
I use this code , want the file to be autouploaded:
```
.on("filebatchselected", function(event, files) {
		$(this).fileinput("upload");
	})
```
and the option allowedFileExtensions: ['jpg'] .

If the file's type is not right, like: file.exe, the error message will be : `No valid data available for upload`, but not `Invalid extension for file "{name}". Only "{extensions}" files are supported.`
So, I tried this code , I can saw the two error messages,
```
.on("filebatchselected", function(event, files) {
        var self = $(this);
	setTimeout(function(){
		self.fileinput("upload");
	},3000);
	})
```

So how to judge the error is the event `filebatchselected`? 

Please give me a help.

Thank you.

**Comment by kartik-v** [comment]
Use the error events... [read about them here](http://plugins.krajee.com/file-input/plugin-events#error-events).

e.g. [fileerror](http://plugins.krajee.com/file-input/plugin-events#fileerror) and / or [fileuploaderror](http://plugins.krajee.com/file-input/plugin-events#fileuploaderror) for your use case.

If there is an error received in those events then store the result in a flag on the page... and validate them before you trigger `fileinput('upload')` in `filebatchselected` ... use a setTimeout as you have done with appropriate delay.
