### ISSUE TITLE
question

### ISSUE THREAD

**Issue by taochengbo** [kartik-v/bootstrap-fileinput#1439]
Why multiple image uploads will request the api multiple times？
![image](https://user-images.githubusercontent.com/11847496/61501770-63f2ef80-aa03-11e9-9136-0aba0f73cd7b.png)

**Comment by taochengbo** [comment]
![image](https://user-images.githubusercontent.com/11847496/61502062-d31d1380-aa04-11e9-858d-8ddde96f69bf.png)

**Comment by kartik-v** [comment]
Read docs... Set **uploadAsync** to false
