### ISSUE TITLE
Return data after delete file

### ISSUE THREAD

**Issue by gidaban** [kartik-v/bootstrap-fileinput#1440]
Hello, first you do a great job :)

My question is,

What should be return if file has been deleted or if i will return error?

Should be a json format?

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. 
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: ^3.4.1
- bootstrap-fileinput version:  ^5.0.4

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by DigiLive** [comment]
As far as I found:
It should be a json reponse indeed.

```json
{"someKey":"No error occurred"}
```

Once a key exists with name "error", the plugin assumes deleting the file went wrong and will act upon as so.

```json
{"error":"An error occurred"}
```

Additional key-value pairs can be send in the same response. E.g.
```json
{"error":"An error occurred","errorNo":1}
```

**Comment by kartik-v** [comment]
Yes you need to send a JSON response. Read documentation of [deleteUrl](https://plugins.krajee.com/file-input/plugin-options#deleteUrl) to understand the ajax request format for sending and receiving data.
