### ISSUE TITLE
Missing module '../img/loading.gif' with webpack

### ISSUE THREAD

**Issue by angarc** [kartik-v/bootstrap-fileinput#1442]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

**Note** There was an issue about this posted back in 2017. Yet, I'm still getting this error on version 5.0.4. Also, on that issue, someone else still had that problem and no one helped him. Hopefully this will help. 

## Steps to reproduce the issue

1. `yarn add bootstrap-fileinput`
2. `import 'bootstrap-fileinput'` in index.js and `@import '~bootstrap-fileinput/scss/fileinput.scss';` in my main.scss

## Expected behavior and actual behavior

To get styling for my input when I use $('#my-file-input').fileinput();

***Actual behavior*** is a css error that disrupts my entire application. However, that has to do with webpack and the way it is setup with ruby on rails. However, I shouldn't be getting this error in the first place:

`Error: Cannot find module '../img/loading.gif'`

When I follow those steps, I get the aforementioned error in my js console. 

I was expecting styling for my file field

## Environment

ruby on rails 6.0.0.rc1
webpack

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.4.1
- bootstrap-fileinput version: "^5.0.4

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
There will be an enhancement to allow only specific files and directories for your npm import.

For your use case and issue, configure your webpack module to the right path via properties to load the img folder ... `publicPath`: '../' and `useRelativePaths: true` [as described in this SFO response](https://stackoverflow.com/questions/48475500/webpack-scss-how-to-work-with-image-paths#answers-header)
