### ISSUE TITLE
one questions, please give me a help

### ISSUE THREAD

**Issue by jianjianxu** [kartik-v/bootstrap-fileinput#1443]
1. My file's name is "This is a long file name to just check how the fileinput plugin can autosize the file caption displayed across device sizes.docx".
It is not a jpg,but a word file.
2. then i upload this file.

until now, the view is ok.

3. Then I enter the edit page. I use fileinput to load the long name file.
It shows a big pic.
```
<img src="/upload/201907/24/156393911924n.docx" class="file-preview-image kv-preview-data" title="This is a long file name to just check how the fileinput plugin can autosize the file caption displa" alt="This is a long file name to just check how the fileinput plugin can autosize the file caption displa" style="width:auto;height:60px;max-width:100%;max-height:100%;">
```

The name is too long. And the pic shows a big one.

So, how to solve this problem, thank you.

**Comment by kartik-v** [comment]
Why are you wrongly setting the MS word file as an image source type in initialPreview? Check the preview management demos... You need to set this as type *office* in your initialPreview config. By default if you do not specify the type the plugin assumes image type.
