### ISSUE TITLE
Invalid thumb frame with id: "{id}"

### ISSUE THREAD

**Issue by marcoalesan** [kartik-v/bootstrap-fileinput#1445]
Everytime i load a file my console displays `Invalid thumb frame with id: "{id}"`

This message doesn't show up with old version (downloaded few months ago) Today I uploaded to newest version and this message is driving me crazy.

¿What does it mean?
¿What can I do to get rid of it?

**Comment by lordaikins** [comment]
Hi, 

> Everytime i load a file my console displays `Invalid thumb frame with id: "{id}"`
> 
> This message doesn't show up with old version (downloaded few months ago) Today I uploaded to newest version and this message is driving me crazy.
> 
> ¿What does it mean?
> ¿What can I do to get rid of it?

I came across this plugin last week and noticed the same message in the console.
Well, what does it mean? Can't really say
What can you do to get rid of it? Just locate the `fileinput.js` and look for this `window.console.log(msg);` on approximately line `1922`. Commenting it out like this `//window.console.log(msg);` will sure stop the message from appearing on your console.

**Comment by kartik-v** [comment]
These are log messages generated by plugin to help developers. I will help create an option to hide these log messages via a separate option.

**Comment by kartik-v** [comment]
Resolved via latest commit above

**Comment by lordaikins** [comment]
Thanks man. You are the bomb!

**Comment by lordaikins** [comment]
Interestingly, I have just tested the latest commit on my localhost and the log message is still there. What is the option to hide the log message pls?

**Comment by kartik-v** [comment]
After your update... Ensure you have cleaned up web runtime assets and clean your browser cache to ensure your browser is not running stale code. It should work (cross check the plugin demos site). The option to hide logs is *showConsoleLogs*....  But even that will not work if your environment is running outdated plugin code.
