### ISSUE TITLE
PreviewId getting duplicated if we remove the file from preview window for explorer theme?

### ISSUE THREAD

**Issue by Nagendra080389** [kartik-v/bootstrap-fileinput#1447]
`$(document).ready(function () {

            $("#input-b6").fileinput({
                theme: "explorer",
                dropZoneEnabled: true,
                showDrag: false,
                validateInitialCount: true,
                maxFileCount: maxFileCountPerBatch,
                showUploadedThumbs: true,
                hideThumbnailContent: true,
                browseClass: "btn btn-primary buttonCss",
                uploadClass: "btn btn-primary buttonCss",
                removeClass: "btn btn-primary buttonCss",
                removeErrorClass: 'btn btn-primary buttonCss',
                showCaption: false,
                initialPreviewAsData: true,
                removeLabel: 'Remove Files',
                uploadLabel: 'Upload Files',
                browseLabel: 'Attach Files',
                uploadIcon: '<i class="fa fa-upload"></i>',
                fileActionSettings: {
                    uploadRetryIcon: '<i class="fa fa-upload"></i>',
                },
                maxAjaxThreads: 10,
                uploadUrl: 'null',
                uploadAsync: true,
                elPreviewContainer: '#banner_default',
                elPreviewImage: '#file-preview-thumbnails-custom',
                layoutTemplates: {
                    main2: '{preview}\n<div class="kv-upload-progress hide"></div>\n' +
                        '  <div class="input-group-btn">\n' +
                        '{browse}\n{upload}\n{remove}\n',
                    actionDelete: '<button type="button" class="kv-file-remove {removeClass} removeBtnCss" title="{removeTitle}"{dataUrl}{dataKey}>{removeIcon}</button>\n',
                    actionUpload: ' <button type="button" class="kv-file-upload {uploadClass}" title="{uploadTitle}"><i class="fa fa-upload"></i></button>\n',
                    actions: '<div class="file-actions">\n' +
                        '<div class="file-footer-buttons">\n' +
                        '<div class="dropdown">\n' +
                        '<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" ' +
                        'aria-haspopup="true" aria-expanded="false">\n' +
                        '<span class="caret"></span></button>\n' +
                        '<ul class="dropdown-menu pull-right">\n' +
                        '<li><a href="#">{upload} Upload</a></li>\n' +
                        '<li><a href="#">{delete} Remove</a></li>\n' +
                        '<li><a href="#">{zoom} Preview</a></li>\n' +
                        '</ul>\n' +
                        '</div>\n' +
                        '</div>',
                    preview: '<div class="file-preview {class}">\n' +
                        '    <div class="{dropClass}">\n' +
                        '    <div class="file-preview-thumbnails">\n' +
                        '    </div>\n' +
                        '    <div class="clearfix"></div>' +
                        '    <div class="file-preview-status text-center text-success"></div>\n' +
                        '    <div class="kv-fileinput-error"></div>\n' +
                        '    </div>\n' +
                        '</div>',
                },
            });`

Preview id if I upload 4 files :+1: 
![image](https://user-images.githubusercontent.com/6088582/62440580-6a58c980-b76e-11e9-9685-7b321d5dba14.png)

Now if i remove a file inbetween and then reupload a new file:

![image](https://user-images.githubusercontent.com/6088582/62440993-1fd84c80-b770-11e9-8182-67479ae346fb.png)

Now the data-fileIndex adn preview id gets duplicated most probably because the remove might not be refreshing the preview panel and the panel still has stale ids.

**Comment by kartik-v** [comment]
Can you check if this works fine with the latest version (v5.0.5 not yet stable) in dev-master? There are enhancements to preview identifiers in this release.
