### ISSUE TITLE
Lock upload button, while fileupload is still loading files

### ISSUE THREAD

**Issue by shikazu** [kartik-v/bootstrap-fileinput#1449]
Hey,

first of all, thanks for the nice package you are providing. I have a small problem with uploading a lot of images at once to the server. I'm using the AJAX Method and these are my settings:

`$("#file-1").fileinput({
            theme: 'fa',
            language: 'de',
            uploadUrl: '/api/v1/upload', // you must set a valid URL here else you will get an error
            uploadExtraData: {
                '_token': '{{ csrf_token() }}',
                'client_code': '{{ session()->get('clientcode') }}',
                'image_type': 'tile',
            },
            allowedFileExtensions: ['jpg', 'png', 'gif'],
            overwriteInitial: false,
            maxFileSize: 5000,
            maxFilesNum: 3000,
            allowedFileTypes: ['image'],
            maxImageWidth: 800,
            maxImageHeight: 800,
            resizePreference: 'width',
            resizeImage: true,
            autoOrientImage: true,
            validateInitialCount: true
        });`

When im choosing some images and i click on the upload button while the script is still loading images, it only uploads the images which had been loaded. The other images which are still being added to the queue are not uploaded at all. I need to cancel the upload process and start it again using the upload button, which now results in a broken progress bar. Is there any Option i'm missing? I would like to disable that upload button while the preview images are loaded (and possibly also resized in the same process) and enable it, when the queue has finished loading. Would be very nice, if someone could point me into the right direction.

Thanks in advance.

**Comment by kartik-v** [comment]
Note the behavior for the plugin default upload button is precisely like that... When upload is in progress It locks input from any other file selections ot uploads by disabling all other buttons. So not clear on the issue. Can you clarify? 

Are you rendering your own custom upload button... If so you need to handle the behavior of the custom upload button yourself.

**Comment by shikazu** [comment]
When I select images, then the UI switches immediately from Choose to Delete,Upload,Choose. Therefore i can click on Upload, while the select images task hasn't finished, it's still adding the previews to the preview list. If I click on upload, it only uploads those images, that already have been added to the preview list / queue. So in order to upload the files that have been added after i pressed the upload button, i need to cancel the upload and then start it again. But this time the progress bar is broken and flickers between 0 and 100%. So what I need is either that the UI stays on Choose until all files have been added or the UI switches and disables the upload button until all files have been added. So i dont get a splitted queue.

I hope that clears things a bit up and sorry for my complex writing style.
