### ISSUE TITLE
Bypassing maxFileCount

### ISSUE THREAD

**Issue by apilavakis** [kartik-v/bootstrap-fileinput#145]
If i drag & drop or browse select number of files bigger than maxFileCount i will correctly get the error message.

If i upload pictures and then select more i can put as many as i want without maxFileCount having any effect. 

I know i can handle it Server Side i just mention it in case it should have been handled Client Side as well

**Comment by kartik-v** [comment]
`maxFileCount` just controls how much files at a time you can select **before you upload**.  It does not track the files you have already uploaded (nor that is the objective).
