### ISSUE TITLE
The event "fileuploaded" gets the same previewId when uploading images one by one at multiple mode

### ISSUE THREAD

**Issue by gdlcf88** [kartik-v/bootstrap-fileinput#1451]
Here is the code:
![image](https://user-images.githubusercontent.com/30018771/62826365-ddd65d00-bbec-11e9-8e92-0f1510b7d623.png)

1. Add first image and upload it.
![image](https://user-images.githubusercontent.com/30018771/62826387-2aba3380-bbed-11e9-8ecc-f209f6dd18a8.png)

2. Add a new image and upload it.
![image](https://user-images.githubusercontent.com/30018771/62826407-62c17680-bbed-11e9-9c5e-36c416f35be6.png)

3. Get the same previewId and index.
![image](https://user-images.githubusercontent.com/30018771/62826411-88e71680-bbed-11e9-8be0-d7b8172939e0.png)

In this case, how can I get different previewId?

**Comment by gdlcf88** [comment]
I need a key that can tell me which which I deleted just now.

**Comment by Nagendra080389** [comment]
same issue : #1447

**Comment by kartik-v** [comment]
Can you check if this works fine with the latest version (v5.0.5 not yet stable) in dev-master? There are enhancements to preview identifiers in this release.

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/63150763-46cd3300-c03a-11e9-9aa8-2cd9974f9e86.png)
The master branch(maybe it is v5.0.5) fixed it.
