### ISSUE TITLE
There was problem in local language in chrome

### ISSUE THREAD

**Issue by zamaniyusef** [kartik-v/bootstrap-fileinput#1452]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] I use plugin with farsi language. but there was problem in chrome.
![2019-08-13](https://user-images.githubusercontent.com/5508840/62916916-8b916980-bdaf-11e9-85d6-093853ea0396.png)

**Comment by DarthSonic** [comment]
I think I have the same problem. I loaded de locale file after fileinput and added property language: "de" to options, but still get english texts.
