### ISSUE TITLE
Fileinput destroy  initializes uploads and deletes many times after that

### ISSUE THREAD

**Issue by HuGa521** [kartik-v/bootstrap-fileinput#1453]
Opening the model for the first time is normal
![image](https://user-images.githubusercontent.com/42570366/62988472-2012cf00-be77-11e9-9bd7-ce478423139b.png)

Destroy when I close, initialize when I reopen, and fire fileuploded and filedelete or filesuccessremove multiple times when I upload and delete!

![image](https://user-images.githubusercontent.com/42570366/62988614-9a435380-be77-11e9-948e-808047d517e9.png)
![image](https://user-images.githubusercontent.com/42570366/62988637-a3342500-be77-11e9-811e-aca4e24a5bab.png)

![image](https://user-images.githubusercontent.com/42570366/62988667-b7782200-be77-11e9-8481-b348ac168cdf.png)
![image](https://user-images.githubusercontent.com/42570366/62988700-d971a480-be77-11e9-969d-002f503cbf54.png)
![image](https://user-images.githubusercontent.com/42570366/62988712-e1c9df80-be77-11e9-8877-d32b4738be7f.png)
What's the problem, please

**Comment by HuGa521** [comment]
@kartik-v

**Comment by cnsniper2002** [comment]
hi, how did you solve this problem

**Comment by kartik-v** [comment]
Its probably a programming issue at your end you need to handle. If in your custom app code --- you are firing events like `fileuploaded`, `filedelete` or `filesuccessremove` - before destroy -- you need to turn off these events before calling the destroy method - else there will be multiple calls to the events in the stack.

```js
// if you are calling events like these
$('#input-id').on('fileuploaded', function(){});
// then before destroy - turn off these events
$('#input-id').off('fileuploaded');
// then call destroy
$('#input-id').fileinput('destroy');
```
