### ISSUE TITLE
Is there any support for predefined number of slots?

### ISSUE THREAD

**Issue by Steveiwonder** [kartik-v/bootstrap-fileinput#1454]
I'd like to have the ability to say there are a max or 12 images available but show empty placeholders for you to move images in to. I know the min/maxImages value is available but this doesn't pre-render empty slots.

**Comment by kartik-v** [comment]
This is not built in the plugin the way you need. However, you can achieve your use case by rendering multiple fileinput widgets which only allows one file selection and upload at a time (e.g. 12 different widgets for your use case - which will allow 12 different drag drops).
