### ISSUE TITLE
previewTemplate for unknown type is undefined

### ISSUE THREAD

**Issue by DigiLive** [kartik-v/bootstrap-fileinput#1455]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
1. Define `initialPreview` and `initialPreviewConfig`
```javascript
initialPreview = ["document.txt"];
initialPreviewConfig = [{
    "caption":"document.txt",
    "key":"document.txt",
    "type":"inode",
    "filetype":"inode/x-empty",
    "size":0,
    "downloadUrl":"myDownloadURL",
    "url":"myDeleteURL"
}];
```
2. Init the plugin
```javascript
$("#inputFile").fileinput({
    uploadUrl:                  "myUploadURL",
    enableResumableUpload:      true,
    resumableUploadOptions:     {
        testUrl: "myTestURL"
    },
    uploadExtraData:           {
        'uploadToken': 'myTokenValue', 
    },
    maxFileCount:               5,
    allowedFileTypes:           ['image', 'video'],
    allowedFileExtensions:      ['jpg', 'png', 'mp4'],
    showCancel:                 true,
    initialPreviewAsData:       true,
    initialPreview:             initialPreviewData,
    initialPreviewConfig:       getInitialPreviewConfigData,
    overwriteInitial:           false,
    fileActionSettings:         {
        showDrag: false
    },
    otherActionButtons:         selectButtonTemplate,
    theme:                      'fas',
});
```

## Expected behavior and actual behavior

No errors expected. The preview for undefined types (In this case `inode`) should be rendered as other.

Instead the following error is dumped in the console:
`TypeError: out is undefined at line 2113` and no previews are rendered.

Some research lead me to the following code where variable `template` remains undefined because `self.previewTemplates['inode']` is undefined (line 2858).
Imho when a previewTemplate is undefined, it should fallback to a default, so the previews are always rendered. (See added code).

```javascript
_getPreviewTemplate: function (t) {
    var self = this, template = self.previewTemplates[t];
    //Begin: Added so undefined previewTemplate falls back to template `other`
    if (template === undefined) {
        template = self.previewTemplates['other'];
    }
    //End: Added so undefined previewTemplate falls back to template `other`
    if ($h.isEmpty(self.customPreviewTags)) {
        return template;
    }
    return $h.replaceTags(template, self.customPreviewTags);
},
```

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: composer package dev-master f077a98 which states v5.0.5 in file comment.

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
If you want to render using `other` template -  *do not define* the `type` as `inode` then in your `initialPreview` - set the type as `other`

**Comment by DigiLive** [comment]
> 
> 
> If you want to render using `other` template - _do not define_ the `type` as `inode` then in your `initialPreview` - set the type as `other`

I know, but to me it feels like a workaround.

Now my (server) script needs to be aware of all the types which are supported by your plugin (which may change over time) to avoid the plugin from "crashing".

Imhu, my script shouldn't prevent the plugin from "crashing", the plugin needs to handle errors and exceptions (for unexpected values).
In this case: When passing a type which is unknown by the plugin, it should fallback to a default template instead of throwing a non-user friendly error and stop execution of the script.

**Comment by kartik-v** [comment]
Let me know your suggestion on enhancement needed on this from plugin end. 

Reopening this

How can the plugin know what to render for whichever errors are triggered through your server code? You have mentioned one use case above...

**Comment by DigiLive** [comment]
The plugin clearly expects certain values to operate on.
An improvement of the plugin is to catch unexpected values so the script doesn't abort. Something like an error description should be rendered in the browser or shown in the console, so the user doesn't has to guess why the plugin doesn't work.

In case of above, a template could be added to indicate the type is unknown by the plugin, but leave the functionality of the preview intact as much as possible.
My first guess is template other is sufficient.
