### ISSUE TITLE
Preview image is too wide

### ISSUE THREAD

**Issue by zhoudaohong** [kartik-v/bootstrap-fileinput#1456]
![image](https://user-images.githubusercontent.com/45937835/63662808-66aae680-c7f2-11e9-83fa-fdb0a81f6342.png)
Is there any solution？

**Comment by zhoudaohong** [comment]
![image](https://user-images.githubusercontent.com/45937835/63662830-89d59600-c7f2-11e9-99ab-c9e8440145a4.png)

**Comment by kartik-v** [comment]
Please share a JS Fiddle and the image sample to reproduce your error?
