### ISSUE TITLE
Error message when adding file: Invalid thumb frame with id

### ISSUE THREAD

**Issue by Gritmatch** [kartik-v/bootstrap-fileinput#1458]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Note that this functionality works as expected in plugin version 4.5.2. Issue happens only with higher versions.
2. uploadAsync is set to true.
3. When loading images in dropzone, following error appears (again, only in versipn higher than 4.5.2). 

![1](https://user-images.githubusercontent.com/46830254/63890462-08783200-c9b1-11e9-9097-153a27ceaebc.jpg)

4. Same error happens in demo page. 
https://plugins.krajee.com/file-krajee-explorer-demo (see basic usage)

5. I upload 2 files into the empty dropzone. They appear after upload as in the image below. If you execute following code in Chrome Console, you will get 0. This is the count of uploaded files (at least that's how 4.5.2 worked). At this point I would expect to get 2 and not 0 because files uploaded successfully.

`jQuery('#photoalbum-dropzone').fileinput('getFrames', '.file-preview-initial').length`

![2](https://user-images.githubusercontent.com/46830254/63890638-660c7e80-c9b1-11e9-9fb2-d920006f28e2.jpg)

6. Now let's add 1 more file to the dropzone. I get another error in Chrome Console

bootstrap-fileinput: "photoalbum-dropzone": Invalid thumb frame with id: "thumb-photoalbum-dropzone-0

![3](https://user-images.githubusercontent.com/46830254/63891000-26926200-c9b2-11e9-924e-ff5a4247c8c2.jpg)

7. Hit upload and here is the result. The newly uploaded file is not visible.

![4](https://user-images.githubusercontent.com/46830254/63891034-3e69e600-c9b2-11e9-89d7-142c81545c0f.jpg)

## Expected behavior and actual behavior

I expect to see newly uploaded file in the dropzone because it is returned with JSON. I can see that in Chrome console.

This is how I'm sending data from the server. I tried adding append: true (just in case) too. Did not help. True is default anyways.

$returnJson->initialPreview = [
            $url
        ];
        $returnJson->initialPreviewConfig = [
            array(
                "caption" => $filenameUI,
                "url" => "/endpoint/endpoint-$userType-delete-profilealbum-file/",
                "key" => $attach_id,
                "width" => "150px"
            )
        ];

        wp_send_json($returnJson);

Exactly same code works perfectly with version 4.5.2.

I believe the culprit may be newly introduced error (after version 4.5.2):
bootstrap-fileinput: "photoalbum-dropzone": Invalid thumb frame with id: "thumb-photoalbum-dropzone-0

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.12.4 (wordpress version)
- bootstrap-fileinput version: 5.0.5

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
https://plugins.krajee.com/file-krajee-explorer-demo
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
A lot of things have changed in v5.x.  This issue has been fixed in #1445. Suggest to use latest version and update if any error persists. You may want to ensure cleaning browser cache on the demos page so that there is no outdated code running on your environment.
