### ISSUE TITLE
Ajax Scenario: Remove not uploaded image also removes uploaded

### ISSUE THREAD

**Issue by apilavakis** [kartik-v/bootstrap-fileinput#146]
I have this scenario replicated on your example as well (http://plugins.krajee.com/file-input/demo#ajax-uploads Scenario 1)

1) I browse and select one or more images
2) I upload this images
3) Then i browse and select one more
4) I dont upload and i click on the recycle bin on the thumbnail to remove that specific image
5) Somehow all images are removed (not from the server as my Remove method is not being called)

I expected that it would only remove the one i clicked the recycle bin like it works in the case of the images not uploaded. You can remove them one by one. The ones uploaded should not have been removed.

I also noticed and i think this is the case only if you batch upload them. I think if you upload them one by one even if you then browse and select more it would remove them correctly.

If you cannot replicate we can somehow use TeamViewer and i can show you

P.S.
Is there any way to add a remove button on the thumbnail to the images you have just uploaded?

**Comment by kartik-v** [comment]
Similar to your previous query on `maxFileCount`, the plugin only validates and keeps files in memory **BEFORE THE UPLOAD TO SERVER**. Any images that have been already uploaded or sent to SERVER are entirely released from client memory. So there is no knowledge to the plugin of these files. Whatever is left is temporary left over volatile thumbnails that will be cleared before any next upload.

For referring to images that are already uploaded on your server - you must use `initialPreview` and `initialPreviewConfig` to tell the plugin where they are located and what are their settings for deleting etc - so that they can be shown on future refreshes of the page OR can be re-edited. Check the examples of `initialPreview` and `initialPreviewConfig` to achieve your use case of referring images uploaded on server.

**Comment by apilavakis** [comment]
I use initialPreview and InitialPreviewConfig after postback. How can you use it when you return back from the upload?

**Comment by apilavakis** [comment]
I am setting self.initialPreview and calling self.initPreview() inside the fnSuccess but it does not have any effect.

**Comment by apilavakis** [comment]
I think what i am trying to do is not possible. I manage to make the above to work but now i am loosing all the ones that have not yet been uploaded.

Let me know if it is not possible to stop wasting time (especially yours)

**Comment by kartik-v** [comment]
You need to refresh the page if possible... or reinitialize the plugin (e.g. use the `refresh` method by passing these options).

**Comment by apilavakis** [comment]
Refreshing will still loose the ones not uploaded right?

**Comment by kartik-v** [comment]
Yes refreshing would re-initialize the plugin. 

Depends on what is needed. Not sure about your use case... but typically you would use this plugin to usually select and upload. Giving access to uploaded files from server typically can be in other pages or processes. If you are trying to build one single screen and a complete application or an image gallery or something... you need to add your own code to achieve that. For example, after the `fileuploaded` or `filebatchuploadcomplete`, you can embed the image links from your server inside the preview container.

**Comment by kartik-v** [comment]
Yes refreshing would re-initialize the plugin. 

Depends on what is needed and how you can carefully optimize your design. Not sure about your use case... but typically you would use this plugin to usually select, preview, and then upload. Giving access to uploaded files on server or database, will usually happen separately -- and probably as well in other pages or processes. If you are trying to use this plugin to build one single screen for a complete application or an image gallery or something... you need to add your own code to achieve that. For example, after the `fileuploaded` or `filebatchuploadcomplete`, you can embed the image links/thumbnails from your server inside the preview container.
