### ISSUE TITLE
filecustomerror event stops the progress bar

### ISSUE THREAD

**Issue by Gritmatch** [kartik-v/bootstrap-fileinput#1461]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. JS fiddle to reproduce: https://jsfiddle.net/gritmatch/b3ewpyd2/
2. I have filecustomerror event that gets triggered in filebatchpreupload. In filebatchpreupload I check for number of files in dropzone, and if >3, error is triggered.
3. I add 4 files. When I click upload, I see the custom error and only 3 files start uploading, which is as expected. However, UI progress bar gets stuck giving the impression that upload is still in progress (even though all 3 files were uploaded successfully). It is waiting for file number 4.

![2019-09-02_16-21-43](https://user-images.githubusercontent.com/46830254/64132440-f118ba80-cd9d-11e9-8f1d-5ccb051a28ea.jpg)

## Expected behavior and actual behavior

I expect the custom error behave the same way as non-custom error.
For example, I add 1 file that triggers no errors and another one that is too small and should trigger error based on minFileSize setting. The error is striggered.

![2019-09-02_16-27-08](https://user-images.githubusercontent.com/46830254/64132575-c54a0480-cd9e-11e9-9b3d-5909cb842bb0.jpg)

2. I click upload and see only 1 file uploaded. The progress bar is not waiting in incomplete state, "thinking" that there is another file to upload.

![2019-09-02_16-27-28](https://user-images.githubusercontent.com/46830254/64132586-d3982080-cd9e-11e9-8fa2-0df3fa25ae4e.jpg)

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:1.12.4 (Wordpress version)
- bootstrap-fileinput version: v5.0.6 (dev version)

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Actually the `filecustomerror` event is to be used for a different use case - seems in your use case you have used some front end validation to stop upload of the extra fourth file after 3 files - however the plugin still has 4 files in the stack.

I recommend you to rather use other properties in the plugin to achieve your needs - 

1. OPTION 1: is to set `maxFileCount` to 3 and set `validateInitialCount` to `false` - the plugin will automatically do what you need for your use case
2. OPTION 2: Since you are using resumable uploads - you can set the `resumableOptions.maxThreads` property which defaults to `4` - this again is an option that the plugin will automatically manage irrespective of the number of files dragged - it will wait till the `maxThreads` blocked is free.

**Comment by Gritmatch** [comment]
Hi kartik. Thank you for your feedback on this. I am aware of maxFileCount and validateInitialCount properties. However, my use case seems to be a bit different - hence the front end hack. Perhaps there is another property that could solve it?

I want to restrict the users to only being able to upload 15 files in total (so no more than 15 files in Initial preview). And I want them to upload in batches of 3 file per upload (and not more). So there can be 5 batches of 3 files.

If I set maxFileCount to 3, users can have as many batches as they want and add more than 15 files in total. I could maybe control the total count on server-side, but it seems to be quite an overhead to constantly check S3 for # of files. Plus it is not user friendly to allow them to start upload and then fail. Client-side error is preferred.

**Comment by kartik-v** [comment]
@Gritmatch - this works as expected. Cross check the demo page for [maximum file count check special](https://plugins.krajee.com/file-count-validation-demo#max-special) to cross check and understand this.

**Comment by Gritmatch** [comment]
Hi kartik.
Great! I got it to work, using the demo. However, I still think there may be a bug with  using msgFilesTooMany and msgTotalFilesTooMany parameters. 

Your demo does not use these parameters where my JS Fiddle does use them: https://jsfiddle.net/gritmatch/r03sqo42/4/

As soon as I comment them out, I see the default error messages and functionality works fine. It is only with adding msgFilesTooMany and msgTotalFilesTooMany that functionality seems to break.
