### ISSUE TITLE
how to read file in initial data

### ISSUE THREAD

**Issue by mamadsolimani** [kartik-v/bootstrap-fileinput#1462]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by mamadsolimani** [comment]
hello Kartik,
i try for read file in initial data. i cann`t understand how read file, where i set initial data.
please write example.
Thankyou

**Comment by kartik-v** [comment]
Request to only submit issues and bugs in this repo. You can post programming related help and such queries on the Comments & Discussions sections of the pages. Suggest to go through the documentation and demos where your examples are addressed.

**Comment by mamadsolimani** [comment]
this is my code for read images:

`var inputFiles = $formId.find('input[type="file"]');
		for(index in inputFiles) {
			if ( isNumber(index) ) {
				inputFile = inputFiles[index];
				
				var dragZone = $(inputFile).parents('.file-input').find('.file-drop-zone');
				var count = dragZone.find(".file-preview-thumbnails").find(".file-live-thumbs").length
				count += dragZone.find(".file-preview-thumbnails").find(".file-initial-thumbs").length
				
				var fileName = inputFile.name;
				var fileType = $(inputFile).attr('fileType');
				
				if (count>0) {
					var files = '';
					if (fileType=='image') files = $($formId.find('.file-input')[index]).find('img');
					if (fileType=='file') files = $($formId.find('.file-input')[index]).find('embed');
					for( index in files) {
						if ( isNumber(index) ) {
							var file = files[index];
							formData.set(fileName, $(file).attr('src'));
						} else {
							break;
						}
					}
				} else {
					formData.set(fileName, '');
				}
			} else {
				break;
			}
		}`

where i set initial data, or user edit your photo (photos)

**Comment by mamadsolimani** [comment]
There is no other way. Because you can't trust input-file in html
