### ISSUE TITLE
Need to reload page after invalid file is selected.

### ISSUE THREAD

**Issue by aasiph** [kartik-v/bootstrap-fileinput#1463]
### Using bootstrap-fileinput v5.0.5

If i configure to set allowedFileExtensions and if an invalid file is selected, there is no way to remove it except only refreshing the page.
```javascript
$("#dbfile").fileinput({
            theme: 'fas',
            allowedFileExtensions: ['xml'],
            showUpload: false,
            uploadAsync: false
        });
```
Browse button and also the remove button on top right is disabled.

**Comment by frozeek** [comment]
I'm experiencing the same problem. Any updates or workarounds? It makes client validation useless. Thank you!

**Comment by frozeek** [comment]
@aasiph I was able to solve this by executing "unlock" in the "fileerror" event like this:

```   
      $("#dbfile").on("fileerror", function(evt) {
        $(evt.target).fileinput("unlock")
      });
```

**Comment by kartik-v** [comment]
Please update to the latest release on dev-master v5.0.6 (not yet tagged)... this should be resolved there.

**Comment by kartik-v** [comment]
Fixed via above commit.

**Comment by f7eco** [comment]
same problem ... fixed 

> 
> 
> @aasiph I was able to solve this by executing "unlock" in the "fileerror" event like this:
> 
> ```
>       $("#dbfile").on("fileerror", function(evt) {
>         $(evt.target).fileinput("unlock")
>       });
> ```

same problem ... fixed
