### ISSUE TITLE
Layout works, breaks, then works again

### ISSUE THREAD

**Issue by alexdresko** [kartik-v/bootstrap-fileinput#1464]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.

Well, 5.0.5, if that's master. 

- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.

I will if needed. I'm hoping someone will just know what's going on here. 

- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
Interestingly, the following steps work fine in MS Edge. It only fails in Chrome 76. 

1. User loads the page
1. Page displays the control properly.
    ![image](https://user-images.githubusercontent.com/333022/64559423-401d9d00-d314-11e9-95d2-664dfcc9ecdc.png)

1. User adds a file to be uploaded. 
1. Page layout shifts slightly. 
    ![image](https://user-images.githubusercontent.com/333022/64559438-4b70c880-d314-11e9-944a-4d83cb71de8e.png)
1. User resizes the browser, even as small as 1px
1. Page layout corrects itself
    ![image](https://user-images.githubusercontent.com/333022/64559476-63e0e300-d314-11e9-9cdc-f3bfb3f41012.png)

## Expected behavior and actual behavior

When I follow those steps, the UI works, but it doesn't look right. 

I was expecting...

I shouldn't have to resize the browser to make things look right. 

## Environment

Browsers

- [X] Google Chrome v76
- [X] Microsoft Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows 10
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.4.1
- bootstrap-fileinput version: 5.0.5
- Aurelia

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
This surprised me. The layout is broken at first, but fixes itself if I hover over the uploaded file. 

![image](https://user-images.githubusercontent.com/333022/64559977-9212f280-d315-11e9-8ba4-8962557fb88d.png)

![image](https://user-images.githubusercontent.com/333022/64559987-993a0080-d315-11e9-967b-6ce502a6d9ad.png)

![image](https://user-images.githubusercontent.com/333022/64559995-a0610e80-d315-11e9-945e-0a6c06ee52ed.png)

- [ ] The bug happens consistently across all tested browsers

Broken in Chrome. Works in Edge. 

- [X] This bug happens when using bootstrap-fileinput without other plugins

Indeed.

- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

I will if necessary.

**Comment by kartik-v** [comment]
I can see this issue on chrome - but am surprised like you. Will check when I get time... but it seems some browser specific issue.

**Comment by kartik-v** [comment]
Resolved via above commit.
