### ISSUE TITLE
fileinput('upload') fires multiple times.

### ISSUE THREAD

**Issue by ARedmanDodd** [kartik-v/bootstrap-fileinput#1470]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. JS Fiddle Provided
2. https://jsfiddle.net/mr9fa3sd/2/
3.

## Expected behavior and actual behavior
I expect that when I submit a form and reset it using jQuery the fileinput to also be cleared, however the form is not being cleared and files are being uploaded multiple times

I have provided a JS Fiddle link (https://jsfiddle.net/mr9fa3sd/2/) containing instructions of how this error is created along with what is happening.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer (im not supporting internet explorer so not tested)
- [ ] Safari (not-tested)

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version: 3.4.1
- bootstrap-fileinput version: 5.0.6

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo) Cannot check because demo's don't upload
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a jsFiddle]https://jsfiddle.net/mr9fa3sd/2/)

**Comment by kartik-v** [comment]
Note that you have configured and set `uploadUrl` which means you are using an ajax based upload mode of the plugin AND not the form based control for upload and clear. Hope you have read about [plugin usage modes](https://plugins.krajee.com/file-input#usage-modes).

Hence a reset of the form for an ajax upload mode will have no impact on the file input. You need to explicitly call the [`clear` method](https://plugins.krajee.com/plugin-methods#clear) of the plugin to clear your file input wherever you need it (for example you could call the above method on reset of the form).

**Comment by ARedmanDodd** [comment]
Thank you for getting back to me...

Im afraid I don't think I understand.

I am explicitly calling the `clear` method but the file input is still not resetting. I have updated this [fiddle](https://jsfiddle.net/ecxysa2L/1/) so now when the `submit` button is clicked, the `upload` method is called. Once the `fileuploaded` event is triggered the form is then submitted where the `$(#form).on('submit)` handler calls the fileinput `clear` method. But the fileinput does not get reset and it still operates in the same way as it did before..

It probably is just an error that I am making, but it is becoming very confusing as to why the `clear` method isn't actually clearing anything.

**Comment by ARedmanDodd** [comment]
I would also like to add that the plugin usage modes section of the documentation does not mention anywhere that you have to explicitly call the clear method to clear the form.

**Comment by kartik-v** [comment]
> I would also like to add that the plugin usage modes section of the documentation does not mention anywhere that you have to explicitly call the clear method to clear the form.

Clearing the form is not a functionality available in the plugin (nor is it related to the plugin). It is an activity that needs to be handled by each developer if needed.

Only clearing of the files in the file input is a functionality available for which you need to read the plugin methods. Operations that can be done for the file input plugin can be referred to in the [plugin methods section of the docs](https://plugins.krajee.com/file-input/plugin-methods).

For a non-ajax (form based upload scenario) - the plugin uses native HTML FILE input capability to read files - so resetting the form typically will be handled by the browser to clear all inputs including the file input.

**Comment by kartik-v** [comment]
As to your code - it is a programming bug / issue and not related to the plugin. You are calling fileuploaded event to run each time on BUTTON CLICK without turning the previous event off which is stacking up multiple calls. I have updated your fiddle to correct this and show. [Refer here](https://jsfiddle.net/jLv940wm/). Closing this.

**Comment by ARedmanDodd** [comment]
I understand.. my apologies.

And thank you so much for showing me the error in my code. I totally get it now. I thought it might have been something I was doing wrong.
