### ISSUE TITLE
Cannot read property 'push' when uploading invalid file

### ISSUE THREAD

**Issue by g-wilkinson** [kartik-v/bootstrap-fileinput#1480]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Drag a valid file (e.g. sample.jpg) which then auto uploads
![upload-1](https://user-images.githubusercontent.com/48353488/66316920-7567db80-e910-11e9-9803-4ffb65b44d6d.png)

2. Delete the valid file from the upload control.
![upload-2](https://user-images.githubusercontent.com/48353488/66316940-831d6100-e910-11e9-9ebb-74df613bd91e.png)

3. Drag an invalid file (e.g. sample.aaa) which then reports 'No valid data available for upload' as expected.
![upload-3](https://user-images.githubusercontent.com/48353488/66316963-8fa1b980-e910-11e9-8364-aa6c9f45c32f.png)

4. Delete the invalid file from the upload control.
![upload-4](https://user-images.githubusercontent.com/48353488/66316973-93cdd700-e910-11e9-8d59-4dd914e061ba.png)

5. Drag a valid file (e.g. sample.jpg).  
![upload-5](https://user-images.githubusercontent.com/48353488/66317010-a1835c80-e910-11e9-8cd8-6caa0f6d65e9.png)

The Cancel button unexpectedly appears and the following error occurs:

`````
fileinput.min.js:11 Uncaught TypeError: Cannot read property 'push' of undefined
    at Object.add (fileinput.min.js:11)
    at Object.<anonymous> (fileinput.min.js:12)
    at Function.each (jquery-1.10.2.min.js:4)
    at i._updateInitialPreview (fileinput.min.js:12)
    at fileinput.min.js:12
`````

No additional files can be added until the page is reloaded.

Plugin options are:

`````
theme: 'fas', 
overwriteInitial: 0, 
uploadAsync: 1, 
showUpload: 0, 
showRemove: 0, 
initialPreviewAsData: 1, 
initialPreviewShowDelete: 0, 
validateInitialCount: 1, 
uploadUrl: '/ajax/upload.php', 
allowedFileExtensions: [ "pdf", "png", "gif", "jpg", "doc", "docx", "odf" ],
maxFileCount: 20,

`````

## Expected behavior and actual behavior

When I follow the above steps, I expect to be able to add and remove valid and invalid files without an error occurring.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.10.2
- bootstrap-fileinput version: 5.0.6

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
I am not able to reproduce your issue - your use case is similarly configured in [ajax demo 6](https://plugins.krajee.com/file-input-ajax-demo/6) - can you test and let know if you are able to reproduce your issue?

**Comment by g-wilkinson** [comment]
I have not been able to reproduce the issue on ajax demo 6.  I have changed my settings to the match the demo and still get the same error.  I am using the following config:

`````
allowedFileExtensions: [ "pdf", "png", "gif", "jpg", "doc", "docx", "odf" ],
uploadUrl: '/ajax/upload.php',
uploadAsync: true,
showUpload: false,
showRemove: false,
overwriteInitial: false,
minFileCount: 1,
maxFileCount: 20,
initialPreviewAsData: true

`````
I have compared the Network console in Chrome dev tools and both show the same requests.

![upload-push-error-1](https://user-images.githubusercontent.com/48353488/66381815-f0350300-e9b1-11e9-912a-90ee47782f8d.png)

Any suggestions?

Thanks

**Comment by kartik-v** [comment]
Check if you are running the latest release of the plugin files from dev-master and let know.

**Comment by g-wilkinson** [comment]
I have updated the plugin files from 5.0.6 to 5.0.7 from dev-master and still get the same issue

I'm now using the non-minified files to test rather than minified files as originally so the error message is slightly different now:

`````
fileinput.js:1774 Uncaught TypeError: Cannot read property 'push' of undefined
    at Object.add (fileinput.js:1774)
    at Object.<anonymous> (fileinput.js:3125)
    at Function.each (jquery-1.10.2.min.js:4)
    at FileInput._updateInitialPreview (fileinput.js:3124)
    at fileinput.js:3172
`````

Note that steps 1 and 2 are not necessary to reproduce the issue.

**Comment by kartik-v** [comment]
You need to check the server code that returns the `initialPreview` and `initialPreviewConfig` after upload. Check the JSON format which is expected for [async ajax uploads](https://plugins.krajee.com/file-input#ajax-async)

**Comment by MaksTrader** [comment]
Greetings. I'm asking for help. I'm getting the same problem.

It only occurs when loading the first image.

Further, when reloading pages and returning initialPreview and initialPreviewConfig the error does not occur.

**Comment by kartik-v** [comment]
The reason is probably because you are sending `initialPreview` and `initialPreviewConfig` as a null via your server code. 

If you have no initial files avalable to show in initial preview then send rather an empty JSON object instead of including `initialPreview` or `initialPreviewConfig` as null within.

For example if all files are deleted - and no files available to show in initial preview ... your server code should return following 
```
// empty json object
{}
``` 

instead of following (do not send like below)
```
{
    initialPreview: null,
    initialPreviewConfig: null
```
