### ISSUE TITLE
Prevent deleting uploaded files using ajax/server uploads / initialPreviewShowDelete: false not working

### ISSUE THREAD

**Issue by g-wilkinson** [kartik-v/bootstrap-fileinput#1482]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.  initialPreviewShowDelete set to false
2.  File upload set to auto upload using filebatchselected event
3.  The "remove file" button is still displayed

![File-Upload-Hide-Delete-button-on-preview](https://user-images.githubusercontent.com/48353488/66760198-8331d980-ee99-11e9-8ac9-bf15f0756eb3.png)

## Expected behavior and actual behavior

Once a file has been uploaded we do not want the ability for end users to delete the file.

When I follow those steps, I see...
the "Remove file" button

I was expecting...
not to see the "Remove file" button

I have not been able to reproduce on the demo site as have not found an example that uses initialPreviewShowDelete but the following is similar to what we are using:
[https://plugins.krajee.com/file-input-ajax-demo/6](url)

Is my understanding of using initialPreviewShowDelete correct or is there another option to use?

Plugin options are:
`````
theme: 'fas', 
overwriteInitial: 0, 
uploadAsync: 1, 
showUpload: 0, 
showRemove: 0, 
initialPreviewAsData: 1, 
initialPreviewShowDelete: 0, 
validateInitialCount: 1, 
uploadUrl: '/ajax/upload.php', 
allowedFileExtensions: [ "pdf", "png", "gif", "jpg", "doc", "docx", "odf" ],
maxFileCount: 20,
`````

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.10.2
- bootstrap-fileinput version: 4.3.1

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by g-wilkinson** [comment]
I have updated the screen shot to indicate the issue.  i.e. the first two uploads are previews that have already been uploaded to server so we don't want the Remove button to show for these (as highlighted with the magenta box).  
The last upload/on the right has just been uploaded so is correctly showing the Remove button.

**Comment by kartik-v** [comment]
Fixed via above commit.
