### ISSUE TITLE
Json to property initialPreview

### ISSUE THREAD

**Issue by Jellfedora** [kartik-v/bootstrap-fileinput#1483]
Hello,

I am trying to use your plugin, only I can not get the initial rendering via a get call on my server.

I would like the initialPreview property to be filled with my json that I get upstream

`
<input id="input-id" type="file" class="file file-preview-image file-preview-text" data-preview-file-type="text" multiple="multiple">
`

`
var fileinput = $("#input-id").fileinput({

		initialPreview: [
			// "<img src = '" + value.url + "' style='width:213px;height:141px;' title = '" + value.name + "'>",
		],
	});

	$.get('truc/hosts/upload/' + id.value, function (data) {

		// Si erreur
		if (data === 'error') {
			$('#message-images').addClass('bg-danger text-danger text-center font-weight-bold');
			$('#message-images').text(
				'Impossible de trouver l\'identifiant de cet hôte, veuillez réessayer. Si le probléme persiste contacter l\'administrateur'
			);
			return true;
		} else {
			var test = [];
			$.each(data, function (key, value) {
				fileinput.initialPreview.push("<img src = '" + value.url + "' style='width:213px;height:141px;' title = '" + value.name + "'>")
			});
		}
	});
`

`
0: {name: "56293/small/Capture_du_2019-07-17_10-32-20.png", size: 170871, url: "/image/view/dev_bao-hosts-images/56293%2Fsmall%2FCapture_du_2019-07-17_10-32-20.png"}
1: {name: "56293/small/groupe_160_a_suppr.png", size: 55003, url: "/image/view/dev_bao-hosts-images/56293%2Fsmall%2Fgroupe_160_a_suppr.png"}
2: {name: "56293/small/groupe_160_a_suppr_2.png", size: 55652, url: "/image/view/dev_bao-hosts-images/56293%2Fsmall%2Fgroupe_160_a_suppr_2.png"}
3: {name: "56293/small/mail_ouv-ferm.png", size: 146773, url: "/image/view/dev_bao-hosts-images/56293%2Fsmall%2Fmail_ouv-ferm.png"}
4: {name: "56293/small/paysage.jpg", size: 38491, url: "/image/view/dev_bao-hosts-images/56293%2Fsmall%2Fpaysage.jpg"}
`

I do not see how to pass these images to the initialPreview property...

Thanking you for your help!`

**Comment by kartik-v** [comment]
You need to configure `initialPreview` and `initialPreviewConfig` together - [check an example demo](https://plugins.krajee.com/file-preview-management-demo#preview-data) - how you can configure it via data.
