### ISSUE TITLE
how to set the dom <div class="file-preview"> height and use overflow-y

### ISSUE THREAD

**Issue by AniFengx** [kartik-v/bootstrap-fileinput#1490]
i hope to use a fixed height on <div class="file-preview"> , and add the attribute overflow to it.
but i can't find the option in file-input.js .

**Comment by kartik-v** [comment]
Read docs about options to set or override preview settings defaults"

- [`previewSettings`](https://plugins.krajee.com/file-input/plugin-options#previewSettings)
- [`previewZoomSettings`](https://plugins.krajee.com/file-input/plugin-options#previewZoomSettings)
- [`previewSettingsSmall`](https://plugins.krajee.com/file-input/plugin-options#previewSettingsSmall)
