### ISSUE TITLE
Style error?

### ISSUE THREAD

**Issue by Jasonzhangjs** [kartik-v/bootstrap-fileinput#1493]
bootstrap-fileinput versions : 5.0.1
jquery versions:  2.1.1
bootstrap version : 3.3.6
browser : chrome Version 78.0.3904.70 (Official Build) (64-bit)

When I updated my browser, I found the problem in the picture.

![image](https://user-images.githubusercontent.com/7445375/67760703-c042c200-fa7c-11e9-942c-308d661be2b2.png)

This problem is my production environment, I didn't make any code changes.

**Comment by Jasonzhangjs** [comment]
It works in IE.

![image](https://user-images.githubusercontent.com/7445375/67761325-064c5580-fa7e-11e9-935a-d6b972ccaf71.png)

**Comment by Inogami** [comment]
Same, do you find any solution?

**Comment by Jasonzhangjs** [comment]
@Inogami I tried to modify the bootstrap.css file, It worked.
![image](https://user-images.githubusercontent.com/7445375/67912282-6e0cb880-fbc4-11e9-98bf-6f72601da819.png)
I don't think this is the best solution.

**Comment by kartik-v** [comment]
It maybe due to a bootstrap css specific styling issue on your page design or environment. You need to check that. You can also try using the other themes of the plugin like Font Awesome theme or create your own theme and override the CSS that way. Refer the theming demoa section

**Comment by Jasonzhangjs** [comment]
@Inogami When you update chrome to Version 78.0.3904.87, It's fixed.
