### ISSUE TITLE
About readFiles

### ISSUE THREAD

**Issue by Hidove** [kartik-v/bootstrap-fileinput#1498]
![image](https://user-images.githubusercontent.com/42663943/69621142-806dfb00-1079-11ea-914e-8ca1bed41210.png)

Why does this happen when I use 

` form.fileinput('readFiles', images);`

to preview pictures? How can I solve this problem?

**Comment by enretap** [comment]
He, i'am starting with fileinput plugin and i have the same problem . Please someone can help ?

**Comment by enretap** [comment]
Ok thank, I solve the problem with initialize my fileInput by setting the property "dropZoneEnabled" to  false. But Drag & Drop not work this configuration.

**Comment by enretap** [comment]
Also, files added by readFiles are not considered in form submiting. I think that only native selections are considered.

**Comment by kartik-v** [comment]
You may want to read documentation about the [plugin usage modes](https://plugins.krajee.com/file-input#usage-modes) and what is possible in form submission mode and ajax mode... Most of the methods you are trying to use will only work in ajax mode of the plugin.

**Comment by enretap** [comment]
Ok thank for answer, Now i'm using the plugin in Form Submission mode. in documentation i can understand that only native input is read. So i can use entirely some methods like "readFiles" only in Ajax Submission mode.
