### ISSUE TITLE
 Resumable upload progess bar error

### ISSUE THREAD

**Issue by swfszf** [kartik-v/bootstrap-fileinput#1499]
my options:
$("#img_file").fileinput({
            language: 'zh',
            browseOnZoneClick: true,
            enableResumableUpload: true,
            resumableUploadOptions: {
                chunkSize: 1024,
            },
            uploadAsync:true,
            uploadUrl: uploadUrl, 
            uploadExtraData: {'_token': token},
            maxFileCount: 1, 
            enctype:'multipart/form-data',
            allowedFileExtensions: ['jpg', 'jpeg', 'png', 'gif'],
            showUpload: false,
            showRemove: false,
            showBrowse: false,
            showCaption: false,
            fileType: "image",
        }).on("filebatchselected", function(event, files) {
            $(this).fileinput("upload");
        })

results：
![1574826552(1)](https://user-images.githubusercontent.com/29946120/69692100-ff137880-110b-11ea-8577-be724328e5a2.png)

**Comment by bychgh0622** [comment]
yes,when you select duplicatefile,after upload,it error

**Comment by kartik-v** [comment]
Please share JS Fiddle and steps/screenshots to reproduce your issue.

**Comment by bychgh0622** [comment]
in your demo,[Resumable Scenario # 2](https://plugins.krajee.com/file-resumable-uploads-demo#resumable-uploads-2), 
1.select many files, then select one of them again ,it show  duplicate file error 
![image](https://user-images.githubusercontent.com/30619408/70015479-6f147980-15b8-11ea-86ea-d67831feb5bd.png)
2. then ,upload , upload progess bar error,it can not done,when exist  duplicate files,like this,


![20191203104021](https://user-images.githubusercontent.com/30619408/70015821-856f0500-15b9-11ea-9747-fc8efad555a1.png)

**Comment by kartik-v** [comment]
Thanks for the report. Will check
