### ISSUE TITLE
Resumable upload, fileId parameter need to be the only one

### ISSUE THREAD

**Issue by bychgh0622** [kartik-v/bootstrap-fileinput#1500]
when use resumable upload, my server method receive uploadParams, the fileId  may be repeat,
when different person upload the same file,because in code ,you create it like this, `file.size + '_' + relativePath.replace(/\s/img, '_')`, if you use fileId to revice many chunks and save it in file, and next time ,you upload the same file,so `fileBlob` will be append to the saved file,it  error.
  to solve this problem,I do it like this , in fileInput.js :
in _chage function,I set file fileGuid prob:

```
            $.each(tfiles, function (key, file) {
                    var fileGuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                        return v.toString(16);
                    });
                file.fileGuid = fileGuid;
            });
            self.readFiles(tfiles);
```
in sendAjax function,fileId replace with file.fileGuid:

```
 self._setUploadData(fd, {
                        chunkCount: rm.chunkCount,
                        chunkIndex: index,
                        chunkSize: chunkSize,
                        chunkSizeStart: chunkSize * index,
                        fileBlob: [blob, rm.fileName],
                        //fileId: id,
                        fileId: file.fileGuid,
                        fileName: rm.fileName,
                        fileRelativePath: f.relativePath,
                        fileSize: file.size,
                        retryCount: retry
                    });

```

**Comment by bychgh0622** [comment]
why not use generateFileId()? if  I  create unique file identifier for the file,for example, guid. when file is select,it will call getFileId() four times to get fileld,but every time is different,so cause errors

**Comment by kartik-v** [comment]
You need to configure [generateFileId](https://plugins.krajee.com/file-input/plugin-options#generateFileId) if you want your own file ID generation routine. It allows you to define a JS Callback function by which you should be able to achieve your own file id generation logic.
