### ISSUE TITLE
in Resumable upload,file-caption-name show title error 

### ISSUE THREAD

**Issue by bychgh0622** [kartik-v/bootstrap-fileinput#1501]
in your demo,[Resumable Scenario # 2](https://plugins.krajee.com/file-resumable-uploads-demo#resumable-uploads-2), when upload many files,not one, then remove One of them
 ,the file-caption-name input show "_" title
![image](https://user-images.githubusercontent.com/30619408/70014884-cd405d00-15b6-11ea-9737-d3c8aaec043b.png)

**Comment by kartik-v** [comment]
Could not reproduce this.

Note that the caption is rendered by the [slugCallback](https://plugins.krajee.com/file-input/plugin-options#slugCallback) routine which removes special characters from the file name. You could override this property to allow the characters you wish to display.
