### ISSUE TITLE
offsetParent is not set -- cannot scroll viewer.js

### ISSUE THREAD

**Issue by alirayaneh** [kartik-v/bootstrap-fileinput#1503]
![image](https://user-images.githubusercontent.com/8302574/70184686-96c12a00-16fd-11ea-96d8-2ccd7291faa0.png)
hi , 
When I attach a pdf file.
This eruption is happening. And it stops other javascript code in my app
I saw this in Firefox
I've seen this problem on all sites and pages that use your script.

offsetParent is not set -- cannot scroll viewer.js:2526:13
offsetParent is not set -- cannot scroll viewer.js:2526:13

    scrollIntoView resource://pdf.js/web/viewer.js:2526
    _scrollIntoView resource://pdf.js/web/viewer.js:8753
    _scrollIntoView resource://pdf.js/web/viewer.js:8247
    scrollPageIntoView resource://pdf.js/web/viewer.js:8980
    setHash resource://pdf.js/web/viewer.js:6588
    setInitialView resource://pdf.js/web/viewer.js:1324
    load resource://pdf.js/web/viewer.js:1097

**Comment by kartik-v** [comment]
This seems to be a problem specific to Mozilla browser that is rendering the PDF. Will check and update.
