### ISSUE TITLE
Krajee Explorer Theme jpg png gif Show picture preview Other file display icon

### ISSUE THREAD

**Issue by apchenjun** [kartik-v/bootstrap-fileinput#1504]
how to jpg png gif Show picture preview Other file display icon。
At present, all the examples have not found such a mixed display.
The problem is how the initialization data handles the icon problem。
![image](https://user-images.githubusercontent.com/4964551/70223255-5f4a9000-1786-11ea-80c8-062df0a6593a.png)

**Comment by kartik-v** [comment]
Set [allowedPreviewTypes](https://plugins.krajee.com/file-input/pluginOptions#allowedPreviewTypes) to `image` or the types you want preview to be rendered - for the rest configure the icons you want to display as highlighted [in the demo](https://plugins.krajee.com/file-preview-icons-demo#custom-preview-icons-1)
