### ISSUE TITLE
Bug in the add method: content is null

### ISSUE THREAD

**Issue by lbphp** [kartik-v/bootstrap-fileinput#1505]
Hello,
in fileinput.js i get _TypeError: content is null_
 when it tries to access content.lenght while content is null.

The buggy piece of code is this:

```
                add: function (content, config, tags, append) {
                    var data = self.previewCache.data, index = content.length - 1;
                    if (!content || !content.length) {
                        return index;
                    }
```
The exception happens at the first line of the function ( var data = ..... ).
I guess you should move the "if" block up to the very start of the function ?

**Comment by kartik-v** [comment]
It seems you are using an older plugin release. Update to the latest releases - this is not an issue anymore.
