### ISSUE TITLE
New `filebatchselected` event triggered after every batch of files are selected.

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#151]

**Comment by kartik-v** [comment]
Resolved via upgrade to release v4.1.7.

**Comment by zhopy** [comment]
Can you provide a sample code on how to do auto upload with this event triggered? Thanks.

**Comment by kartik-v** [comment]
@zhopy - you may want to go through the plugin docs and demos

An example of auto upload on drag and drop after file batch selected [is shown in this demo](http://plugins.krajee.com/file-input-ajax-demo/6)

**Comment by zhopy** [comment]
Thanks for the prompt reply, your works are amazing!
