### ISSUE TITLE
getFilesCount can not get the file num which just uploaded, only can get the num will to upload 

### ISSUE THREAD

**Issue by peter-wang-wsl** [kartik-v/bootstrap-fileinput#1512]
`getFilesCount` can not get the file num which just uploaded, only can get the num will to upload in `filepreupload`. Is it a issue?

**Comment by kartik-v** [comment]
Enhancement  6bfc90d added. You can supply a boolean parameter `includeInitial` (either `true` or `false`) to the `getFilesCount` method to include initial preview files. Defaults to `false` to get only file count pending for upload.
