### ISSUE TITLE
Duplication error doesn't trigger any events

### ISSUE THREAD

**Issue by godisntheradio** [kartik-v/bootstrap-fileinput#1514]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Add images A.jpg and B.jpg
2. Try to add A.jpg again.

## Expected behavior and actual behavior

When I follow those steps, I see...

File "A.jpg" of same size "X KB" has already been selected earlier. Skipping duplicate selection.

I was expecting some event to be triggered so i can handle the error on the side of my application.

Also an unexpected behaviour related to this is when I have a file loaded through initial preview, then i upload the same file, it works, but if I try to upload the same file again, i get the error mentioned above and every other file besides the initial preview disappears.

**Comment by kartik-v** [comment]
Duplicate to #1499, #1502 and fixed via the issues.

The file duplication check has been enhanced and corrected. You may want to use this release from dev-master which will be tagged soon.

**Comment by kartik-v** [comment]
You can control the error messages for duplication check via the `msgDuplicateFile` properties. I am noting a separate enhancement for duplicate check event.

**Comment by godisntheradio** [comment]
Thanks for replying so soon. 

I discovered that my files were disappearing because somewhere i didn't have access until now was calling fileupload('reset'), so the last part of this issue can be disconsidered.

**Comment by marcelogarbin** [comment]
> Duplicate to #1499, #1502 and fixed via the issues.
> 
> The file duplication check has been enhanced and corrected. You may want to use this release from dev-master which will be tagged soon.

Do you have any idea of a release date? thank you

**Comment by kartik-v** [comment]
Fixed via (enh #1514): Enhancements to duplicate file selection.
    - New event `fileduplicateerror` will be triggered after every duplicate file detected.
    - Duplicate error container can be closed by clicking the `close` icon.
    - New property `fadeDelay` used in fade out / fade in animations of error containers.
