### ISSUE TITLE
async multiple upload has problem in previewConfig

### ISSUE THREAD

**Issue by hannanstd** [kartik-v/bootstrap-fileinput#1518]
Hi
when we use multiple upload when resumable is false and async is true, if in begining we pick some files, the first file will be appear uncompletly. for test please open below link:
https://plugins.krajee.com/file-input-ajax-demo/6
select 4 files. after upload finished, see first image doest have download button. because the config will not effect for it.

**Comment by kartik-v** [comment]
Similar to #1522 and resolved via there.
