### ISSUE TITLE
Button for add new file

### ISSUE THREAD

**Issue by Tirus91** [kartik-v/bootstrap-fileinput#1519]
It`s possible to add new button for add new files? Browse button delete files for every click on it.

**Comment by kartik-v** [comment]
You need to use ajax mode of upload for appending files to achieve the above. Read about [plugin usage modes and what is possible in each mode](https://plugins.krajee.com/file-input#usage-modes)

If you are using normal form based submission - you cannot append new files (this is a limitation of native HTML FILE INPUT).
