### ISSUE TITLE
Drag&drop file A on file B preview causes file A to open 

### ISSUE THREAD

**Issue by TristanMartinCS** [kartik-v/bootstrap-fileinput#1520]
Hello there !

My company has been using this plugin for a long time and it's pretty great and convenient. 
Recently I have discovered a bug which does not seem to depend on the version used. It involves drag&drop.

When I drag and drop my file out of the drop zone nothing "bad" happens (as expected), but when I happen to drop it on the preview of an already present file, it opens the dropped file on the same page.
I reproduced the bug on the demo plugin (https://plugins.krajee.com/file-basic-usage-demo) on Chrome as well as Firefox : 

![fileinput drag drop issue](https://user-images.githubusercontent.com/45273854/72429869-2e03ad80-3791-11ea-87ac-3f5e2dfbaca8.gif)

I wondered if it's something already planned to be fixed in the future or if this is something that basically anybody manages to live with (since I did not find any post about it). But I decided to submit it anyway so that somebody could tell me more about it.

Thanks a lot guys !

**Comment by kartik-v** [comment]
This is a browser inherent behavior for browsers like Chrome/Firefox for embedded OPEN PDF files on the browser. If you have PDF files open via the browser and you drag another PDF file on top of the open PDF - it will result in what you are seeing (browser will try to open the new PDF file). If you have any suggestions to bypass this browser internal feature - am open for suggestions - but this is not something related to this plugin or a bug in the plugin.

**Comment by TristanMartinCS** [comment]
True, I forgot to say that it only happened when I dropped on a PDF file.
Anyway, your answer is satisfactory and I guess we can consider that the issue is closed for now because I don't have any clue on how to bypass that (I tried changing my Chrome site Settings so that it downloads the file instead of displaying but that wasn't satisfactory either).

Thanks for answering so quickly !
