### ISSUE TITLE
Preview Window Does Not Appear on IE11

### ISSUE THREAD

**Issue by TorreyGarland** [kartik-v/bootstrap-fileinput#1521]
We have a file input using fileinput js on a page but it is initially hidden until the user makes an input selection from a combobox.

On Firefox and Chrome, it works great with no problems.

On IE 11, the fileinput textbox and browse button appear, but not the preview window as it does on Chrome and Filefox.  The drag and drop functionality work does not work either.

After clicking on the browse button and selecting any type of file the preview window appears, but drag and drop functionality still doesn't work.

Removing a file using the "X" in the preview windows works, but the preview window disappears.

I am behind a firewall, so I can submit a screen capture.

Any thoughts?

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.2.4
- bootstrap-fileinput version: 5.0.7
## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by TorreyGarland** [comment]
Preview does not work on Microsoft Edge either.

Also, the preview window does not work as expected on the demo page (https://plugins.krajee.com/file-basic-usage-demo#basic-example-1).

**Comment by kartik-v** [comment]
I presume you are talking about drag and drop zone in preview.  Note that It is available only in following cases
1. ajax mode for all browsers. 
2. Or in form submission mode only for selective browsers which support editing file input via javascript. 

So use one of the options above in your app to program and achieve your use case. This is not a bug.
