### ISSUE TITLE
fileActionSettings: {showRemove: false} option no longer works.

### ISSUE THREAD

**Issue by Modicrumb** [kartik-v/bootstrap-fileinput#1527]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Initialize a file input and feed the options fileActionSettings: { showRemove: false}

## Expected behavior and actual behavior

I expected the remove button on thumbnail to not show. It shows regardless.

## Environment

Browsers

- [x] Google Chrome

Haven't tested others

Operating System

- [x] Windows

Haven't tested others

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 5.0.8

## Isolating the problem

See this fiddle: https://jsfiddle.net/oakyup64/8/

**Comment by jlayt** [comment]
This is still an issue in 5.2.3!
