### ISSUE TITLE
Onchange event not fired in 5.0.1 or 5.0.9 release when using drag / drop

### ISSUE THREAD

**Issue by xantari** [kartik-v/bootstrap-fileinput#1532]
## Prerequisites

Drag/drop a file into the file input and the onchange event does not fire.

## Steps to reproduce the issue

1. Chrome.
2. Here is my initialization:

$('#input-700').fileinput('destroy'); //reset seems to not work as well, using clear instead
    //https://plugins.krajee.com/file-input/plugin-events
    $("#input-700").fileinput({
        uploadUrl: "/FileUpload/Send",
        deleteUrl: "/FileUpload/Delete",
        initialPreviewDownloadUrl: "/FileUpload/FilePreview",
        validateInitialCount: true,
        maxFileCount: 10,
        showCancel: false,
        allowedFileTypes: null,
        allowedFileExtensions: ['jpg', 'jpeg', 'png', 'pdf', 'docx', 'doc', 'pptx', 'ppt', 'xls', 'xlsx', 'key'],
        //showUpload: true,
        //uploadAsync: false,
        overwriteInitial: false,
        retryErrorUploads: false,
        removeFromPreviewOnError: true,
        showUpload: false,
        //showCancel: true,
        initialPreviewAsData: true,
        initialPreview: serverData.initialPreview,
        initialPreviewConfig: serverData.initialPreviewConfig,
        theme: 'fas',
        uploadExtraData: function () {
            var form = $('#editExpenseForm');
            var out = {};
            out['submissionDetailId'] = form.data('submissiondetailid');
            out['speakerId'] = parseInt(form.data('speakerid'));
            out['meetingCode'] = parseInt(form.data('meetingcode'));
            out['clientId'] = form.data('clientid');
            return out;
        }
    }).on('change', function (event) {
        console.log("change");
        validateReceiptAttached();
    }).on('filezoomhidden', function (event, params) {
        //console.log('File zoom hide ', params.sourceEvent, params.previewId, params.modal);
        //Patch for issue when you zoom into document and close, it removes body's modal-open and you can't scroll the window anymore
        $('body').addClass('modal-open');
    }).on('fileerror', function (event, data, msg) {
        console.log('File error', event, data, msg);
    }).on('filebatchuploadcomplete', function (event, preview, config, tags, extraData) {
        console.log('File batch upload complete', preview, config, tags, extraData);
        PostEditExpense($('#editExpenseForm'));
    }).on('filedeleted', function (e, key, jqXHR, data) {
        console.log('file deleted Key = ' + key);
    }).on('fileremoved', function (e, key, data) {
        console.log('file removed Key = ' + key);
        validateReceiptAttached();
    }).on('filebeforedelete', function (e, key, data) {
        console.log('Delete Key = ' + key);
        //console.log(data);
    }).on('filepreupload', function (e, data, previewId, index) {
        console.log('preupload');
        console.log(data);
    }).on('fileuploaded', function (e, data) {
        console.log('file uploaded');
        console.log(data);
    }).on('filecleared', function (event) {
        console.log("filecleared");
        validateReceiptAttached();
    });

## Expected behavior and actual behavior

"change" event should fire when you drag/drop file. Currently it only fires if you hit browse button.

## Environment

Chrome

Operating System

Windows

Libraries

- jQuery version: 3.4.1
- bootstrap-fileinput version: 5.0.1 and 5.0.9 tested

**Comment by kartik-v** [comment]
You are using a wrong event for your use case. The *change* event is internal to native file input. It will not fire until the browse button is used. You need to use other events like *filebatchselected*.

**Comment by xantari** [comment]
Ok, thanks!
