### ISSUE TITLE
data-fileindex is -1 on all files

### ISSUE THREAD

**Issue by Bintux** [kartik-v/bootstrap-fileinput#1535]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Download the latest version of the bootstrap-fileinput and open the included example file
2. In the first demonstration upload min. 2 files
3. Inspect the elements and check the data-fileindex. It will show "-1" for all newly added files

## Expected behavior and actual behavior
I have a older version of the fileinput (4.5.3) working and made some custom scripts to be used with the file index.
No after updating I noticed that with the version 5.0.8 on the fileloaded event the index was always 0 and the data-fileindex to be -1.
So far I could not isolate what is causing it in my code. But playing just with the freshly downloaded version I noticed that the included example/demo 1 is showing the same issue. 

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: cdn version as included in the download
- bootstrap-fileinput version: 5.0.9

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
There is a major change since resumable uploads were introduced. The `data-fileid` should be used instead of `data-fileindex` which is obsolete.

- Use method [`getFileStack`](https://plugins.krajee.com/file-input/plugin-methods#getFileStack) to get list of files in the filestack
- The above is a javascript object (associative array like) where the keys are the file ids
- The file ids can be found for each thumbnail via the `data-fileid` data attribute

**Comment by Bintux** [comment]
Ok thank you for the solution
 just FYI - when dissecting through my implementation, I noticed this behavior is occurring only after adding the option: uploadUrl . With the other options or extra libraries or themes this is not an issue.
