### ISSUE TITLE
Override default properties

### ISSUE THREAD

**Issue by AnthonyVidal** [kartik-v/bootstrap-fileinput#1538]
I have not found the Override default properties form of the fileinput.
What I am looking for is to be able to leave the common properties of the fileupload, such as browseLabel, browseIcon, uploadIcon among others, in an initialized javascript file.

I tried this, but it doesn't work
` $.extend($.fn.fileinput.defaults, {
        overwriteInitial: true,
        browseLabel: 'Adjuntar Archivo'
    });`

any ideas? Thank you.

**Comment by kartik-v** [comment]
You can directly pass properties to the fileinput plugin function which will override inbuilt defaults. You can set these as global defaults and call in your other places - e.g.

```js
var yourGlobalDefaults = { overwriteInitial: true, browseLabel: 'Adjuntar Archivo' };

var yourSettings = {}; // your plugin settings
$('#input-id').fileinput($.extend(true, yourGlobalDefaults, yourSettings));
```

**Comment by AnthonyVidal** [comment]
Thanks! @kartik-v
