### ISSUE TITLE
TypeError: e.ajax is not a function

### ISSUE THREAD

**Issue by QingFengpoor** [kartik-v/bootstrap-fileinput#1541]
## Prerequisites

- [√ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [√ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [√ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.added in html:  

```Html
<div class="file-loading">
   <input id="file" name="file" type="file" class="file-loading">
</div>
```

2. and js :

```JavaScript
function initFileInput(ctrlName,uploadUrl) {      
	 var control = $('#' + ctrlName);
	 console.log('#' + ctrlName);
	 control.fileinput({  
	     language: 'zh', //设置语言  
	     uploadUrl: uploadUrl, //上传的地址
	     enctype: 'multipart/form-data',
	 })  }
$(document).ready(function () {
	/* var path = rootPath + "/lecturer/picture/upLoad.shtml";  */
	var path = "/house/upLoad";
	console.log(path);
	initFileInput("file",path);
	
	$("#file").on("fileuploaded", function (event, data, previewId, index) {
		console.log("in fileuploaded action");
	 	console.log(data.response);
	    $("#file").val(data.response);  
	 });
});
```

3. in controller (mapping /house/upLoad):

```Java
@PostMapping("/upLoad")
	public String upLoad(@RequestParam("file")CommonsMultipartFile file)
	throws Exception{
		String path="E:/images/"+new Date().getTime()+file.getOriginalFilename();
		System.out.println(path);
		File newFile = new File(path);
		file.transferTo(newFile);
		Map<String, String> map = new HashMap<String, String>();
		map.put("pathUrl", path);
		//return "redirect:/";
		return path;
	}
```

## Expected behavior and actual behavior

When I follow those steps, and click upload, in the web console, I get this:
```
/house/upLoad addhouse:101:10
#file addhouse:92:11
TypeError: e.ajax is not a functionfileinput.min.js:12:15116
    _ajaxSubmit http://localhost:8090/js/fileinput.min.js:12
    _uploadSingle http://localhost:8090/js/fileinput.min.js:12
    upload http://localhost:8090/js/fileinput.min.js:13
    _uploadClick http://localhost:8090/js/fileinput.min.js:12
    jQuery 3
        i
        dispatch
        handle
```

I was expecting the success of upload a image with the extension of jpg.

## Environment
Browsers

- [ ] Google Chrome
- [√ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [√ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:3.5.0 slim
- bootstrap-fileinput version: 5.0.8

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [√ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is because you are not loading an incorrect required dependency -- the jQuery Lib. I see you have loaded jQuery slim - which does not have the other functions like ajaxSettings in the main jquery build.

**Comment by QingFengpoor** [comment]
Thank you, and this helps.
