### ISSUE TITLE
Multiple file upload issue

### ISSUE THREAD

**Issue by etas34** [kartik-v/bootstrap-fileinput#1542]
hello,

Firstly thanks for your great work,

i use this plugin for multiple input. i have a problem , it uploads only last files.

For example i select 2 files and after that i select 3 files so it shows 5 files on image area.
when i upload, it uploads only last 3 files.

how can i solve this problem ?

**Comment by kartik-v** [comment]
Seems you do not read docs... Please read docs. You can use plugin in either form submission mode or ajax submission mode as mentioned in docs. If you are trying to combine modes you will face errors. ... For example setting ajax upload url but reading via form submit... This will not work.

**Comment by etas34** [comment]
thank you , i realised better now
