### ISSUE TITLE
Plugin Sortable does not work with Require.js

### ISSUE THREAD

**Issue by lamro1949** [kartik-v/bootstrap-fileinput#1543]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. include require.js
2. include sortable.js
3. include fileinput.js

## Expected behavior and actual behavior

When I follow those steps, I see that scripts are enabled without errors, but sortable in fileinput doesn't work. I think problem with the __initSortable_ function, the variable _window.KvSortable_ is not defined there.
I also tested the latest version of fileinput, but nothing has changed.
## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.11.3
- bootstrap-fileinput version: 4.4.7

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Check with fixes via #1581.
