### ISSUE TITLE
Path Drag and Drop on Chrome, Edge, Safari

### ISSUE THREAD

**Issue by kainruben** [kartik-v/bootstrap-fileinput#1545]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Drag and Drop a folder on Chrome/Edge/Safari
2.  The "fileRelativePath" for each file is empy

## Expected behavior 
Each file must be have the complete path

and actual behavior
The "fileRelativePath" is empty

## Environment
Browsers

- [X ] Google Chrome
- [ ] Mozilla Firefox
- [X ] Internet Explorer
- [ X] Safari

Operating System
- [X ] Windows
- [ X] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.4.1
- bootstrap-fileinput version: 4.3.1 

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

------
To "Fix" this I have added on my libary  two lines
on _scanDroppedItems the next line before file is pushed to the files array:
file.fullPath=path+file.name;

on  sendAjax, added the new parameter:
 fullPath : f.file.fullPath,

**Comment by kainruben** [comment]
Is better modify the function getFileRelativePath returning the variable added to the file:
 return String(file.fullPath || file.relativePath || file.webkitRelativePath || $h.getFileName(file) || null);

If this is made. It is not necesary modify sendAjax

**Comment by kartik-v** [comment]
Thanks - can you share a PR for this?

**Comment by kainruben** [comment]
> 
> 
> Thanks - can you share a PR for this?

Yes, I have made the PR:
https://github.com/kartik-v/bootstrap-fileinput/pull/1546

Thanks!
