### ISSUE TITLE
Auto Upload Function only works in 'filebatchselected' event. Not working on 'change', 'fileselect' event

### ISSUE THREAD

**Issue by FrederickChan** [kartik-v/bootstrap-fileinput#1548]
I'm writing this in only as a last resort to inform you that your latest master plugin only allows

**Method:**
```$(this).fileinput('upload');``` or ```element.fileinput('upload'); ```

IF the plugin is set to multiple to true with the 'filebatchselected' event. If it is false, with the method 'fileselect', or 'change', I will need to select file 2 times before upload triggers.

This one will work, but the fileinput is forced to be multiple.
```item_photo.on('filebatchselected', function(event) { item_photo.fileinput('upload');  });```

This will only work if you browse and select the file the 2nd time.
```item_photo.on('change', function(event) { item_photo.fileinput('upload');  });```

**Comment by kartik-v** [comment]
The `change` event is internal to the native HTML file input - and not controlled by the plugin - so it will not necessarily be fired every time unless you explicitly select files via file input browse (and not via drag and drop). You need to that is why ideally use `filebatchselected` to ensure all the custom validations that are special to the plugin are done before files are selected and loaded in the preview.

**Comment by kartik-v** [comment]
I am noting an enhancement for `filebatchselected` for single file uploads (when `multiple` attribute is not set).

**Comment by kartik-v** [comment]
Fix provided. You should now have the `filebatchselected` event firing for all single and multiple file uploads.

**Comment by FrederickChan** [comment]
Thank you very much for addressing this.
