### ISSUE TITLE
How to Show Custom Success Message?

### ISSUE THREAD

**Issue by reasecret** [kartik-v/bootstrap-fileinput#1549]
I can show error message like this:
`return response()->json([
                    'error' => 'you can't upload ' .  $photoName,
                ]);`

What about success message? I've search documentation but can't find anything. Is there a way to show a custom success message?

**Comment by kartik-v** [comment]
You need to use events like [`filebatchuploadsuccess`](https://plugins.krajee.com/file-input/plugin-events#filebatchuploadsuccess) or [`fileuploaded`](https://plugins.krajee.com/file-input/plugin-events#fileuploaded) to show your custom alerts or success messages.
