### ISSUE TITLE
Multiple attachments with one or more erroneous files in between using form submission

### ISSUE THREAD

**Issue by 93ramadan** [kartik-v/bootstrap-fileinput#1554]
I am facing an issue when using multiple file upload using the normal Form Submission. The issues occurs when I set the "maximum file size" and attempt to upload 5 items; with the second items selected being over the "maximum file size". The file input is displaying the file up until the error and is not displaying/previewing the other files that have been loaded also.

## Steps to reproduce the issue and the problem

1. Create a Form Submission with a Multiple File Input
2. Set Maximum File Size as 900 KB 
3. Attempt to attach files (with one of the files being greater than 900 KB) and ensure that you selected it in between other files (i.e. from the browser, using the Ctrl button to select more than one)
4. When you click on open, it will display all the attachments you selected in the same sequences you selected them. But once it reaches the file with an error, it will display the preview, remove all files, but without updating the preview.
5. At this point, the user thinks that the files before the error occurred have been loaded because they appear in the preview, even though it says "No files selected".
![image](https://user-images.githubusercontent.com/12176398/81501304-5f742c00-92e0-11ea-80ef-a6b1b8a1c598.png)

## Desired behavior 

I know the problem occurs at this function (approx. line # 4967) where the function throws the error, and then just returns.
![image](https://user-images.githubusercontent.com/12176398/81501350-93e7e800-92e0-11ea-9e16-c34d41e932d0.png)

Ideally, I think it would be best to show the error of that specific file, and to continue with loading the other files instead of just breaking. I attempted to implement this, where it just skips the error file and then just displays a generic error rather than error bound to a file but I failed. The above commented code was my first attempt.

I then attempted to alter the throwError function to continue reading the rest of the files like it usually doing for AJAX uploads;
![image](https://user-images.githubusercontent.com/12176398/81501409-ede8ad80-92e0-11ea-8ebf-ba87f52e3e03.png)
but that also failed.

Libraries

- bootstrap-fileinput version: v5.0.8

I am not sure if this issue is to be classified as a bug, improvement or feature. 
For now, I am implementing my custom event for "fileerror" to remove reset the file input and alert an error message until I can find a solution that achieves the above. Looking forward to any feedback or ideas.

**Comment by 93ramadan** [comment]
JSFiddle Sample Code:

https://jsfiddle.net/93ramadan/y8dfh46q/

To reproduce issue:
1. Click on "Browse"
2. Select the first file less than 900 KB
3. Using Ctrl on the keyboard, select the second file greater than 900 KB
4. Using Ctrl on the keyboard, select the third file less than 900 KB
5. Click on "Open" to upload the attachments


![image](https://user-images.githubusercontent.com/12176398/81502624-ae718f80-92e7-11ea-9cb0-2a7ae759ff23.png)
You will only see the first file (less than 900 KB) and the second file (with an error) but not the third imported file.

**Comment by kartik-v** [comment]
To achieve your use case.... you need to use ajax mode of upload... This allows queuing of files and tracking errors and resuming other uploads. What you are experiencing is an intended outcome for form based upload. It is a binary outcome... Either success for all files or error for all files... There is no way to track file by file because it relies on and is limited by native HTML 5 file input capabilities... Which does not allow editing the input and select only partial files
