### ISSUE TITLE
Bootstrap Fileinput Loop - multiple fileinput in the same page

### ISSUE THREAD

**Issue by anilskalyane** [kartik-v/bootstrap-fileinput#1555]
Hi,
I try to do a dynamic fileinput loop, but I doesn't work :(

Help, please :)
Here is the HTML code:
```
<input data-fsdImageUplod="fsd-bulk-image-upload" data-route="{{ route('fsd-image-upload') }}" id="image-file" type="file" name="file" accept="image/*" data-min-file-count="1" data-fsd-images="{{isset($fsd_images_path)? $fsd_images_path:json_encode([])}}" data-sub-path="others" multiple >
```
JS Code:
```
$('[data-fsdImageUplod="fsd-bulk-image-upload"]').each(function(){
			let image_uploader_id=$(this).attr('id');
			let $subPath= $(this).attr('data-sub-path');
			let fsdImagesGetCount = function(id) {
				let cnt = $('#' + id).fileinput('getFilesCount');
				return cnt === 0 ? 'You have no files remaining.' :
					'You have ' +  cnt + ' file' + (cnt > 1 ? 's' : '') + ' remaining.';
			};
			// jQuery and Bootstrap Fileinput
			$("#"+image_uploader_id).fileinput({
				overwriteInitial: false,
				validateInitialCount: true,
				theme: 'fa',
				initialPreview: JSON.parse($("#"+image_uploader_id).attr('data-fsd-images')),
				initialPreviewAsData: true, // defaults markup  
				uploadUrl: $("#"+image_uploader_id).attr('data-route'),
				// deleteUrl: "http://localhost/file-delete.php",
				enableResumableUpload: true,
				uploadExtraData: function() {
					return {
						_token: $('meta[name="csrf-token"]').attr('content'),
						subPath: $subPath
					};
				},
				allowedFileExtensions: ['jpg', 'png', 'gif','jpeg'],
				overwriteInitial: false,
				maxFileSize:2048,
				maxFilesNum: 10,
				slugCallback: function (filename) {
					return filename.replace('(', '_').replace(']', '_');
				},
				fileActionSettings: {
					showRemove: true,
					showUpload: false,
					showZoom: true,
					showDrag: true,
				},
			}).on('filebeforedelete', function() {
				return new Promise(function(resolve, reject) {
					$.confirm({
						title: 'Confirmation!',
						content: 'Are you sure you want to delete this file?',
						type: 'red',
						buttons: {   
							ok: {
								btnClass: 'btn-primary text-white',
								keys: ['enter'],
								action: function(){
									resolve();
								}
							},
							cancel: function(){
								$.alert('File deletion was aborted! ' + fsdImagesGetCount(image_uploader_id));
							}
						}
					});
				});
			}).on('filedeleted', function() {
				setTimeout(function() {
					$.alert('File deletion was successful! ' + fsdImagesGetCount(image_uploader_id));
				}, 900);
			});
		  });
```
## Steps to reproduce the issue

1.You can internalize multiple input-file uploaded - HTML elements 

## Expected behavior and actual behavior

not able to pass the file data to the backend 

Should upload the images from all the HTML selector(fileinput) 

## Environment: Staging

Browsers: Google Chrome
Operating System: Linux

Libraries

- jQuery version: 3.2
- bootstrap-fileinput version: 5.0.8

**Comment by Kwaadpepper** [comment]
Please read the doc i think, you are making a wrong usage of this library.

You should call $.fn.fileinput once in a input Dom node:

```$('#myFileInput')..fileinput({ ... });```

In your case you should do 

```$('[data-fsdImageUplod="fsd-bulk-image-upload"]').fileinput({...});```

to display the uploader

Here are plugin methods https://plugins.krajee.com/file-input/plugin-methods
Here are plugin events    https://plugins.krajee.com/file-input/plugin-events

What you are trying to do if call fileinput on ```$("#"+image_uploader_id)```  does it exists ?
You did not provide ```<input id="{image_uploader_id}" .../>``` as html here ?

**Comment by anilskalyane** [comment]
@Kwaadpepper - Thanks for the update

Actually I want to display the multiple file input section on the same page like,
```
<input data-fsdImageUplod="fsd-bulk-image-upload" data-route="{{ route('fsd-image-upload') }}" id="image-file" type="file" name="file" accept="image/*" data-min-file-count="1" data-fsd-images="{{isset($fsd_images_path)? $fsd_images_path:json_encode([])}}" data-sub-path="others" multiple >

<input data-fsdImageUplod="fsd-bulk-image-upload" data-route="{{ route('fsd-image-upload') }}" id="image-file" type="file" name="file2" accept="image/*" data-min-file-count="1" data-fsd-images="{{isset($fsd_images_path)? $fsd_images_path:json_encode([])}}" data-sub-path="others" multiple >

<input data-fsdImageUplod="fsd-bulk-image-upload" data-route="{{ route('fsd-image-upload') }}" id="image-file" type="file" name="file3" accept="image/*" data-min-file-count="1" data-fsd-images="{{isset($fsd_images_path)? $fsd_images_path:json_encode([])}}" data-sub-path="others" multiple >
Many more - It will add Dynamicaly
```
Can you suggest how can i achieve this?

**Comment by Kwaadpepper** [comment]
In all ways you need to have **only one <input>**,  Look on the demo page 

![Capture d’écran de 2020-05-12 14-22-51](https://user-images.githubusercontent.com/6019313/81690815-1fd24f00-945c-11ea-8e15-bf6acd15742e.png)

Then to populate the ```<input multiple>```,  look at https://plugins.krajee.com/file-resumable-uploads-demo#resumable-uploads-3

you have to do something like :

        overwriteInitial: false,
        initialPreview: [
            // TEXT DATA
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut mauris ut libero fermentum feugiat eu et dui. Mauris condimentum rhoncus enim, sed semper neque vestibulum id. Nulla semper, turpis ut consequat imperdiet, enim turpis aliquet orci, eget venenatis elit sapien non ante. Aliquam neque ipsum, rhoncus id ipsum et, volutpat tincidunt augue. Maecenas dolor libero, gravida nec est at, commodo tempor massa. Sed id feugiat massa. Pellentesque at est eu ante aliquam viverra ac sed est.",
            // PDF DATA
            'https://kartik-v.github.io/bootstrap-fileinput-samples/samples/pdf-sample.pdf',
            // VIDEO DATA
            "https://kartik-v.github.io/bootstrap-fileinput-samples/samples/small.mp4"
        ],
        initialPreviewAsData: true, // defaults markup  
        initialPreviewConfig: [
            {caption: "Lorem Ipsum.txt", type: "text", size: 1430, url: "/site/file-delete", key: 12}, 
            {type: "pdf", size: 8000, caption: "PDF Sample.pdf", url: "/site/file-delete", key: 14}, 
            {type: "video", size: 375000, filetype: "video/mp4", caption: "Krajee Sample.mp4", url: "/site/file-delete", key: 15} 
        ],

So to resume this:

- use only one input to display the filemanager
- populate your images programmatically using ```initialPreview``` property

I am no expert of this library so i may not be more helpfull than that sorry.

**Comment by anilskalyane** [comment]
@Kwaadpepper - Thank you. 

I needed multiple images section with a different input file block.

does anyone have any idea?

**Comment by kartik-v** [comment]
Normally you can handle with just one file input on the page as mentioned by @Kwaadpepper and load multiple images through that. But if you still are keen to have multiple HTML file inputs on the page, then set a different unique id for each HTML file input - and you you need to initialize the plugin for every file input generated on the page after the dynamic input is rendered. You need to write the appropriate javascript for the same to ensure the HTML File Input is loaded into the DOM after which you must initialize the file input plugin. Since this is entirely programming related, I am closing the issue. You should be able to ask for programming help on the comments section of the demo pages or the webtips.krajee.com forum.
