### ISSUE TITLE
<button> instead of link <a > for upload 

### ISSUE THREAD

**Issue by mostafaSYR** [kartik-v/bootstrap-fileinput#1556]
Hey guys, I am in a serious pain here.
 I have been using bs-fileinput for a quite long time, with no issues. BUT now,

In Development, it is working just fine. On the other hand, when I deploy it, it doesn't work properly. 
 Basically, after call fileinput() on the element, we should end up, with a browse button,  to choose a file to upload, when chosen the element should have, an input field with the file inside it, a remove button, and an a tag with the uploadUrl in the href attribute. as mentioned, this is what I got in Development. 

`<a href="/projects/:id/upload_file" tabindex="500" title="Upload selected files" class="btn btn-default btn-secondary fileinput-upload fileinput-upload-button">
<i class="glyphicon glyphicon-upload"></i>  
<span class="hidden-xs">Upload</span>
</a>`

In Staging, I am getting instead of the link (a Tag), a button with a type submit, which doesnt make sense at all !!!. 
`<button type="submit" tabindex="500" title="Upload selected files" class="btn btn-default btn-secondary fileinput-upload fileinput-upload-button">
<i class="glyphicon glyphicon-upload"></i> 
 <span class="hidden-xs">Upload</span>
</button>`. 

so my question is, has anyone face this unexpected behavior before. If not, where could I see, the corresponding function creating these elements, when calling fileinput(). 

 
Some notices, which I dont think really matter, yet to be mentioned: 
- The element is in a Modal. 
- UploadUrl is a function returning the url to be used, based on some action.
- fileinput() is to be called, before opening the modal, hence UploadUrl('') is empty at first, which I tried to fill some mocked string (like 'uploadUrlToBeSetAfterSomeAction'), but with no success.

And here is the way I call fileinput().
` $("#uploadButton").fileinput({
    uploadUrl: function(previewId, index) {
      return $("#uploadButton").data("up");
    },
    showPreview: false,
    uploadExtraData: function(previewId, index){
      return {
        upload_date: $('#uploadDate').val().split('.').reverse().join(''), 
        document_type: $('#documentTypes') .val(),
        rename_file: true
      };
    }
  }).on('filebatchuploadcomplete', function(event, data) {
    location.reload();
  }).on('fileuploaderror', function(event, data, msg) {
    console.log('File upload error');
    alert(msg);
  });
`

- [ basic-usage ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ YES  ] The bug happens consistently across all tested browsers
- [ YES ] This bug happens when using bootstrap-fileinput without other plugins

**Comment by kartik-v** [comment]
Read docs about plugin usage modes. If you do not set uploadUrl ... Then the plugin uses simple HTML form mode of submission and hence the upload button will just be a form submit button. If you set uploadUrl... The upload button will trigger an ajax call to uploadUrl and use ajax mode of submission.

**Comment by mostafaSYR** [comment]
@kartik-v thanks for that. 
Actually, I was using the v5.0.4 version, which to my understanding, didn't have the possibility to set uploadUrl through a callback function. But with the newest version v5.0.9, everything is just working properly!!.
