### ISSUE TITLE
kartik file preview show but error file cannot be blank.

### ISSUE THREAD

**Issue by yogeshsharam2426** [kartik-v/bootstrap-fileinput#1560]
> When i am try to update some thing then kartik file input show file preview but when i am trying to submit it. It will showing error like file cannot be blank.

`<?= $form->field($model, 'file')->widget(FileInput::classname(), [
    'options' => ['accept' => 'image/*'],
    'pluginOptions' => [
      'previewFileType' => 'image',
      'showUpload' => false,
      'initialPreview'=> [
        '<img src="'.$model->company_logo.'" class="file-preview-image img-responsive jui-user-photo">',
      ],
      'initialCaption'=> $model->file,
    ],
  ]); ?>`

Please help me out.

![Screenshot_2020-05-14 Update Placement Details HCL](https://user-images.githubusercontent.com/65341446/81924310-93ab5d80-95fc-11ea-9b82-d6b9e3e11907.png)

**Comment by kartik-v** [comment]
Not related to the plugin and is more a yii2 programming issue. This is more your yii2 model validation rule *REQUIRED* which is firing and you need to check your code logic.

If you have an bug or enhancement to report, then please report this on yii2-widget-fileinput repo (not related to this plugin - so closing).
