### ISSUE TITLE
how to  Ajax implementation to send form data.Display the records in the table from JSON file

### ISSUE THREAD

**Issue by harsha692** [kartik-v/bootstrap-fileinput#1562]
i have created a 
![Capture](https://user-images.githubusercontent.com/63711312/82407822-ce434900-9a87-11ea-8fad-246af40dd5e9.JPG)

A) Create a form  with the following options.
         1. Text Box,
         2. TextArea with HTML formatting
         3. Input
         4. Radio
         5. Check box

how to add  Ajax implementation to send form data.Display the records in the table from JSON file

https://we.tl/t-yT4sgkhtmj
(In this there a file called form.js or form that is the base folder for it) this is link contains folder which we should add code)

**Comment by kartik-v** [comment]
Please read issue posting guidelines and use this repo to only report bugs or enhancement requests. Please post programming queries on the demo pages comments section to get help from others. You can read about [`uploadExtraData`](https://plugins.krajee.com/file-input/plugin-options#uploadExtraData) option in the plugin documentation to achieve your use case. Closing this currently.
