### ISSUE TITLE
Preview file garbled 

### ISSUE THREAD

**Issue by hongroumeng** [kartik-v/bootstrap-fileinput#1564]
Preview file garbled when selecting word and excel.

## Environment

Browsers

- [ ] Google Chrome

Operating System

- [ ] Mac OS X
<img width="362" alt="WX20200527-034001@2x" src="https://user-images.githubusercontent.com/65977610/82943186-c88bbd00-9fcb-11ea-926e-6d0ca5e615b3.png">

**Comment by kartik-v** [comment]
Cannot reproduce this - please share a JS Fiddle to reproduce and will reopen this if there is an issue.
