### ISSUE TITLE
Problem with filezoomshow in multiple inputs

### ISSUE THREAD

**Issue by Weldeasy** [kartik-v/bootstrap-fileinput#1574]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Initialize multiple inputs
`$("#id1").fileinput(options);`
`$("#id2").fileinput(options);`

2. Listen to "filezoomshow" event
`$("#id1").on("filezoomshow", function(event, params) { alert('id1') });`
`$("#id2").on("filezoomshow", function(event, params) { alert('id2') });`

3. Add some files in both inputs.

4. Click in the zoom icon of #id1 or #id2.

## Expected behavior and actual behavior

When I follow those steps, I see that both alerts show, both inputs events raised.

I was expecting that only the #id1 event.

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: v3.2.1
- bootstrap-fileinput version: v4.5.1

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/namogiv/1/edit?html,output)

**Comment by kartik-v** [comment]
Currently yes it works that way because the bootstrap MODAL DIALOG is shared by multiple plugins on the same page (bootstrap recommends not to have separate modal dialogs on same page as that would break the modal behavior). 

Will check if something can be done.

**Comment by kartik-v** [comment]
This is fixed now with the above commit.

**Comment by Weldeasy** [comment]
Thanks a Lot!
