### ISSUE TITLE
Autosubmit with the form

### ISSUE THREAD

**Issue by Ponchia** [kartik-v/bootstrap-fileinput#158]
I there!
First thanks for this awesome script!

I read in the documentation that there is the possibility to auto-submit the foto with the form.

WIth these feature the client doesn't need to click on update and I can use the same script to upload inside my database all the data from the form plus the photo?

Anyway I dind't found how to do that.

Somebody can help me? 

Thanks!

**Comment by kartik-v** [comment]
Triggering the form submit (can be done on input change event via javascript)

Most of your other requirement of populating data on your server, refreshing the page after form submit etc... should be done via your server code.

**Comment by Ponchia** [comment]
Here is my problem:
I don't submit the form at the moment.
When the user click on save I just take all the value from the form and with ajax and serialize I'll upload all on my server.

Now, serialie can't take value as image, so I'm stuck here.

Sorry if is a dumb question.

**Comment by kartik-v** [comment]
You may need to do some reading on ajax upload - you cannot receive file blobs with form serialize... and hence it may not work..

You can also try to use the ajax upload feature provided with plugin which uses HTML5 FormData to submit, and use `uploadExtraData` to submit additional information to your POST. If you wish to use this, [read docs](http://plugins.krajee.com/file-input) or view the ajax uploads section on [demo page](http://plugins.krajee.com/file-input-demo). Unfortunately cannot help with your coding details here (you may need to learn this through reading).

**Comment by Ponchia** [comment]
demo page link not valide.
I solved using formData and not serialize!
Thanks for the hard work man!

**Comment by kartik-v** [comment]
demo link typo is corrected.
