### ISSUE TITLE
If input already have file before the initialization of bootstrap-fileinput the "file-drop-zone-title" still visible

### ISSUE THREAD

**Issue by vinilaraa** [kartik-v/bootstrap-fileinput#1580]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create the input file

2. Put a file in it

3. Initialise this library on the input file

4. See "Drag & drop files here …" showing together with the file

## Expected behavior and actual behavior

When I follow those steps, I see "Drag & drop files here …" showing together with the file, however I was expecting that "Drag & drop files here …" does not show.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: v3.5.1
- bootstrap-fileinput version: v5.0.9

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This seems more of a programming to handle at your end. How are you adding file on the input before plugin init? You cannot normally add files to a native file input via JavaScript. 

You would need to trigger the change event of the file input if it already has a file after you have initialized the plugin so that it processes correctly.

**Comment by vinilaraa** [comment]
Hey, I tested your suggestion and yeah, you're right. Trigging "change" works fine in this situation.

But I still think that this is a bug, because the files are identified and the message "Drag & drop files here …" does not hide.

> How are you adding file on the input before plugin init?

Well, just adding manually before doing the initialisation of the plugin. But a practice example that I am doing and resulted in this error as well is when I copy one file input that already has a file in it and try to initialise the plugin.. this is what I am doing in  my application.

**Comment by kartik-v** [comment]
Resolved via above commit.
