### ISSUE TITLE
How can i load existing pdf files by ajax?  i can't make it...

### ISSUE THREAD

**Issue by reichertvictor** [kartik-v/bootstrap-fileinput#1586]
$('#file-es').fileinput({
            theme: 'fas',
            //theme: "explorer",
            uploadAsync: false,
            overwriteInitial: false,
            initialPreviewAsData: true,
            language: 'es',
            uploadUrl: '{{ path('estudios_upload', { 'editId': editId }) }}',      
            allowedFileExtensions: ['pdf'],
            initialPreview: getFilesPreview();
            initialPreviewConfig: getFilesPreviwerConfig(),
            preferIconicPreview: true, 
            previewFileIconSettings: { // configure your icon file extensions
                'doc': '<i class="fas fa-file-word text-primary"></i>',
                'xls': '<i class="fas fa-file-excel text-success"></i>',
                'ppt': '<i class="fas fa-file-powerpoint text-danger"></i>',
                'pdf': '<i class="fas fa-file-pdf text-danger"></i>',
                'zip': '<i class="fas fa-file-archive text-muted"></i>',
                'htm': '<i class="fas fa-file-code text-info"></i>',
                'txt': '<i class="fas fa-file-text text-info"></i>',
                'mov': '<i class="fas fa-file-video text-warning"></i>',
                'mp3': '<i class="fas fa-file-audio text-warning"></i>',
                // note for these file types below no extension determination logic
                // has been configured (the keys itself will be used as extensions)
                'jpg': '<i class="fas fa-file-image text-danger"></i>',
                'gif': '<i class="fas fa-file-image text-muted"></i>',
                'png': '<i class="fas fa-file-image text-primary"></i>'
            },
        }).on('change', function(event) {
            console.log("change");
        }).on("filebatchselected", function(event, files) {
            $('#file-es').fileinput('upload');
        });;

   function getFilesPreview() {
            var files = [];
            $.ajax({
                type: 'post',
                url: '{{ path('estudios_getuploadeds', { 'editId': editId }) }}' ,
                dataType: "json",
                success: function (data) {
                    $.each(data, function(key,value) {
                        var file = { type: value.type, size: value.size, caption:value.caption, url:value.url};
                        files.push(value.url);
                    });
                    return files;
                },
                error: function (xhr, status, err) {

                }
            })            
        }

**Comment by kartik-v** [comment]
The plugin is a file input replacement and is intended only for uploading for files that are input from client PC/devices (via native HTML file input or drag & drop). So am not clear with your query.

But if you are asking about uploading files (e.g. PDF in your case) from other sources - then you need to do that via your server code (from source X to your server). To then show those files on your server, using this plugin you can point to the server uploaded files by configuring [`initialPreview`](https://plugins.krajee.com/file-input/plugin-options#initialPreview) and [`initialPreviewConfig`](https://plugins.krajee.com/file-input/plugin-options#initialPreviewConfig). You can see the [preview management demo](https://plugins.krajee.com/file-preview-management-demo) on how you can configure preview to show uploaded files on server.
