### ISSUE TITLE
Missing file(s) information on 'fileuploaded'

### ISSUE THREAD

**Issue by derblub** [kartik-v/bootstrap-fileinput#159]
Seems like there is no information at all (like: file-name, file-size,..) on the `fileuploaded` callback.

Is there anything I'm missing?

**Comment by kartik-v** [comment]
Read the documentation and [check how you can access fileuploaded event parameters](http://plugins.krajee.com/file-input#event-fileuploaded).

**Comment by derblub** [comment]
Well, obviously I've read the documentation (I've also mentioned the event for a successfull upload on my first comment).
Your documentation is saying, data.files should have meta information, which is empty (array with 1 field: undefined) on all my file-input fields - didn't test multi file uploads.

**Comment by kartik-v** [comment]
Probably its getting reset for various other scenarios that were incorporated... will provide a fix.

**Comment by kartik-v** [comment]
You can check with the updated code now.

**Comment by derblub** [comment]
Seems like that worked, thanks!
