### ISSUE TITLE
There are some problems in removing the 'uploadurl' parameter

### ISSUE THREAD

**Issue by gml-9527** [kartik-v/bootstrap-fileinput#1596]
## Expected behavior and actual behavior

Brother, I have encountered some problems. I hope that the 'uploadurl' parameter in your plug-in will not be used, because I have my own upload method. But if this parameter is removed from the initialization method, every selected image will be replaced by the next one. This is not what I expected.

## Environment

Browsers

-  Google Chrome

Operating System

-  Windows

Libraries

- jQuery version: 2.2.3
- bootstrap-fileinput version: v5.1.1

## Code

    let images = $('#images');
    images.fileinput({
        language: 'zh',
        uploadUrl: '',
        uploadAsync: true,
        showPreview: true,
        showRemove: true,
        minFileCount: 1,
        maxFileCount: 9,
        initialPreviewFileType: 'image',
        uploadClass: 'btn btn-default uploadImage',
        elErrorContainer: '#kartik-file-errors',
        allowedFileExtensions: ['jpg', 'png', 'jpeg', 'gif'],
    });

    $('.uploadImage').click(function () {
        let files = [];
        for (let i = 0; i < document.getElementById("images").files.length; i++) {
            files[i] = document.getElementById("images").files[i];
        }
        uploadImg(files, 200, 200);
        return false;
    });

**Comment by kartik-v** [comment]
This is an expected occurence and documented in the [plugin USAGE MODES](https://plugins.krajee.com/file-input#usage-modes).

If without upload url the plugin restricts you to capability inherent to any native HTML file input (which does not allow appending files etc.). 

If using with upload url - the plugin uses a different ajax based upload approach and you would not be able to read files via the native file input in this case.
