### ISSUE TITLE
uploaded file disappear after selected duplicate file occur

### ISSUE THREAD

**Issue by weanich** [kartik-v/bootstrap-fileinput#1600]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. upload file e.g. 1.jpg and file become uploaded
2. upload file e.g. 1.jpg and error duplicate occur File "XXXX" of same size "XXX KB" has already been selected earlier. Skipping duplicate selection. and then file 1.jpg disappear from upload list
3. upload file e.g. 2.jpg and file become uploaded then browse file e.g. 3.jpg and file become not yet upload then upload file 2.jpg again then error duplicate occur but this round file 2.jpg still show in upload list

## Expected behavior and actual behavior

When I follow those steps, I see...
 in step 2. file 1.jpg disappear from upload list
but in step 3. the file still show
I was expecting...
 file should be showed in step 2. even error occur
## Environment
 
Browsers

- [x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.0.3
- bootstrap-fileinput version: 5.1.1

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

![test](https://user-images.githubusercontent.com/17219770/86868191-75467780-c0fe-11ea-8347-e4eb46c43ad2.gif)

**Comment by kartik-v** [comment]
This behavior has been enhanced and fixed via #1588 in the upcoming release v5.1.2. You can check this on the demos pages.
