### ISSUE TITLE
Translations don't work

### ISSUE THREAD

**Issue by MALDRU** [kartik-v/bootstrap-fileinput#1601]
Hi.

Perform the style and script imports as instructed in the documentation. But no translation works. Reply the error in codepen.

[https://codepen.io/MALDRU/pen/abdKLde](https://codepen.io/MALDRU/pen/abdKLde)

Thank you for your attention.

**Comment by kartik-v** [comment]
Read docs... you have a wrong spelling for `language`. Here is the correct config

```js
$("#input-44").fileinput({
  //uploadUrl: '/file-upload-batch/2',
  theme: "fas",
  language: "es",
  maxFilePreviewSize: 10240
});
```
