### ISSUE TITLE
Textarea field in layoutTemplate footer

### ISSUE THREAD

**Issue by ic-martin** [kartik-v/bootstrap-fileinput#1602]
Hi,
I tried to find a solution in the documentation but couldnt.
Im using file input as a form widget in Yii 2. 

I have an issue with the form submit and the textarea field naming for multiple files.
The textarea is added to layoutTemplate footer and it looks like this:
'<textarea name="{input_description}" class="kv-input kv-new form-control input-sm form-control-sm">{file_description}</textarea>'
It loads fine in the previews for both initial and new files, but if I set the name of the textarea field as array, e.g. "description[]" the form submits another empty value for each textarea field. I noticed that in the "explorer-fas" theme there is a hidden table row after each visible row which also holds the original or the copy of the same textarea field but it doesnt hold duplicates of input text fields, so Im guessing that thats the reason of a duplicated textarea submit. 
P.S. This doesnt happen with inputs, I just noticed it with textareas ( I didnt check other field types, maybe you can check checkboxes and other basic field types if they have the same issue ). The example of the form submit is:

'fileData' => [
        'new' => [
            'name' => [
                0 => 'test name new'
                1 => 'test name new 2'
            ]
            'description' => [
                0 => 'test description new'
                1 => ''
                2 => 'test description new 2'
                3 => ''
            ]
        ]
    ]

So in this example I have 2 new files to upload and each of them has 1 input for the name and 1 textarea for the description, but after a form submit I get that post.
Form field names are :
- input - "fileData[new][name][]" (submitted properly)
- textarea - "fileData[new][description][]" (submitted with an additional empty value)

Its a bootstrap 4 version and the composer.json is
"kartik-v/yii2-widget-fileinput": "dev-master",

Also, I saw that you have a tag for file ID {fileId} but I couldnt read it for new files. Could you give me a suggestion how to group additional file inputs in an post array for new files? to get something like (field name from the example above):
- "fileData[new][{fileId}][name]"
- "fileData[new][{fileId}][description]"

NOTE: I know I can do all that with a custom JS, but I think since its a yii2 form widget, it should be able to handle this.

Thank you in advance!

**Comment by kartik-v** [comment]
The textarea issue is fixed with above commit. 

On understanding usage for advanced inputs to be sent with each thumbnail - you can use ajax mode to read the inputs submitted and [refer an example demo here](https://plugins.krajee.com/file-input-ajax-demo/7) on how you can set `uploadExtraData` dynamically as a JS callback to understand both input data for NEW FILES as well as input data for SAVED UPLOADED files.

**Comment by ic-martin** [comment]
Thank you Kartik
