### ISSUE TITLE
how to  modify the uploadExtraData before upload file

### ISSUE THREAD

**Issue by ghostsatan** [kartik-v/bootstrap-fileinput#1609]
`
  var fileoption = {
    showUpload: true,
    uploadUrl: "http://" + window.parent.comfun.ComIp.serviceIp + '/api/projectFile/saveFileData.json',
    uploadAsync: false, //同步上传
    showPreview: true,
    dropZoneEnabled: true,
    allowedFileExtensions: ['pdf'],
    language: 'zh',
    overwriteInitial: false, //不覆盖已存在的文件
    initialPreviewAsData: false,
    //maxFileSize: 2500,
    maxFileCount: 5,
    minFileCount: 1,
    maxFileSize: 0,
    dropZoneTitle: '只能上传pdf文件',
    uploadExtraData: function () { //额外参数的关键点
        // 			return {
        // 				fileType:"2",
        // 				projectId:$("#projectId").val()
        // 			}
    },
    layoutTemplates: {
        actionUpload: "", //去掉所选择的文件中的上传按钮
        //actionDelete: "", //去掉所选择的文件中的删除按钮
        //actionZoom: "" //去掉所选择的文件中的预览按钮
    },
}
// 项目图片
function fileupload(fileparm, key) {
    var option = deepClone(fileoption)
    var name = $("#name").val();
    var unit = $("#unit").val();
    option.uploadUrl = "http://" + comfun.ComIp.serviceIp + fileparm.url
    option.allowedFileExtensions = fileparm.limit
    option.uploadExtraData = function () { //额外参数的关键点
        return {
            fileType: fileparm.fileType,
            name: name,
            unit: unit
        }
    }
    $("#" + fileparm.id).fileinput(option).on("filebatchuploadsuccess", function (event, data) {
        if (!data.response.success) {
            swal({
                title: "上传失败",
                html: true,
                text: "<div style='width:100%;word-wrap:break-word'>" + data.response.message + "</div>",
                type: "",
                confirmButtonText: "关闭"
            }, function () { })
            return;
        } else {
            swal({
                title: "上传成功",
                type: "success",
                confirmButtonText: "关闭"
            }, function () {
                Query()
                JAlertOptions.CloseTkAll();
            })
        }
    }).on("filebatchuploaderror", function (event, data, msg) {
        //alert(msg);
    }).on("filebatchselected", function (event, files) {

    });

}

`

when i init the input ,  I create  the option  

uploadExtraData include  "name" and "unit"

when finish uploading   the Data are null 

how to  modify the uploadExtraData before upload file

**Comment by mehmetalidumlu** [comment]
Hi, @ghostsatan 
Did you resolve this problem?
