### ISSUE TITLE
Help needed to show existing file from server as a link (like attachement)

### ISSUE THREAD

**Issue by gunjanvarshney** [kartik-v/bootstrap-fileinput#161]
Hi kartik,

First of all you have done an excellent job of creating this plugin. it is a life saver. with so many options available this is really matured plugin.

I had a requirement where my file input is a part of a bigger form with other fields so I not necessarily am using the upload capability that you have from the plugin. I have already tested your plugin with ajax jquery form and it works fine with other fields. where I am getting into (sort of issue) is that how should I show existing (on server) file as a link either on thumbnail or caption so that user can download it.

do you have some way already devised for this.

Thanks,
Gunjan

**Comment by kartik-v** [comment]
Check [initialPreview](http://plugins.krajee.com/file-input#option-initialpreview) and [initialPreviewConfig](http://plugins.krajee.com/file-input#option-initialpreviewconfig) properties in the documentation for your use case.. you can also separately display your server image links outside the plugin functionality.
