### ISSUE TITLE
cant get $('#' + previewId)

### ISSUE THREAD

**Issue by jianjianxu** [kartik-v/bootstrap-fileinput#1610]
This is my code, it's not working on 5.x, but is working on 4.x.
```
on('fileuploaded', function (event, data, previewId) {
//Here , I cant get the previewId obj. The length is always 0;
console.log($('#' + previewId).length);
})
```

it always print 0. So that I cant deal with the obj('#' + previewId)'s element.

**Comment by kartik-v** [comment]
The `fileuploaded` event function signature is different in 5.x - please check and read documentation.

Here is the [`fileuploaded`](https://plugins.krajee.com/file-input/plugin-events#fileuploaded) event in docs. 

```js
$('#input-id').on('fileuploaded', function(event, previewId, index, fileId) {
    console.log('File uploaded', previewId, index, fileId);
});
```
