### ISSUE TITLE
Uncaught EvalError: call to Function() blocked by CSP in parseEventCallback

### ISSUE THREAD

**Issue by kw-pr** [kartik-v/bootstrap-fileinput#1612]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Set CSP header with eval denied
2. Load the page

## Expected behavior and actual behavior

When I follow those steps, I see console error:

    Uncaught EvalError: call to Function() blocked by CSP

    parseEventCallback fileinput.js:475
    stash fileinput.js:509
    each jQuery
    stash fileinput.js:506
    _createContainer fileinput.js:4746
    _init fileinput.js:982
    FileInput fileinput.js:742
    fileinput fileinput.js:5781
    jQuery 2
    fileinput fileinput.js:5769
    js fileinput.js:61

I was expecting to see fileinput loading up and run.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap version: 4.3.1
- bootstrap-fileinput version: 5.1.2

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)
No, because I can not send header there.
But here I have an example: https://pastebin.com/9KC6yGtH

Problem was created with commit [aa99882](https://github.com/kartik-v/bootstrap-fileinput/commit/aa99882)
"Implement CSP compliance for HTML markup via templates fix #1565 fix #1571"

`Function()` is considered as [unsafe eval](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_eval_expressions) by CSP.

**Comment by Kwaadpepper** [comment]
Just made a PR to remove support for inline-script on templates. So it would only trigger unsafe inline if a user puts inline script on any template element.
