### ISSUE TITLE
maxImageHeight, maxImageWidth not working.

### ISSUE THREAD

**Issue by Ravensborn** [kartik-v/bootstrap-fileinput#1613]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

add maxImageWidth, maxImageHeight, minImageWidth, minImageHeight then try to upload an image with width and height larger than specified.

## Expected behavior and actual behavior

I was expecting to see an error displayed when selecting a file larger than specified width and height
instead I get nothing and the file normally passes validtion.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.1.3

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce thais bug in [a jsbin](https://jsbin.com/)

## My Code

```
$(document).ready(function () {
            $("#images").fileinput({
                showCaption: false,
                dropZoneEnabled: false,
                showUpload: false,
                showClose: false,
                showRemove: false,
                theme: 'fas',
                maxImageWidth: 3840,
                maxImageHeight: 2160,

                maxFileCount: 20,
                maxFileSize: {{env('CAR_IMG_UPLOAD_LIMIT')}},
                allowedFileTypes: ["image"],
                allowedFileExtensions: ["jpg", "jpeg", "png"],

                previewZoomButtonClasses: {
                    prev: 'd-none',
                    next: 'd-none',
                    toggleheader: 'btn btn-sm btn-kv btn-light',
                    fullscreen: 'btn btn-sm btn-kv btn-light',
                    borderless: 'btn btn-sm btn-kv btn-light',
                    close: 'btn btn-sm btn-kv btn-light'
                },
                layoutTemplates: {
                    actionZoom: '<button type="button" class="kv-file-zoom btn btn-light btn-sm" title="{zoomTitle}">{zoomIcon}</button>',
                }


            });
        });
```

**Comment by OnnoRokomSoftwareLtd** [comment]
Same here, resizeImage is not working.

**Comment by fabian-jg** [comment]
This issue even occurs on the demo pages. [https://plugins.krajee.com/file-image-dimensions-demo#max-image-dimensions](url)
