### ISSUE TITLE
At some point, the psd file will cause the web page to crash.

### ISSUE THREAD

**Issue by yaoqiangpersonal** [kartik-v/bootstrap-fileinput#1618]
![89F4125F-4ABF-4b07-84F0-F46B7DFD27EC](https://user-images.githubusercontent.com/32598124/90379187-f81f0280-e0ac-11ea-8081-5eb1b3ee2fe6.png)

Browsers

- Google Chrome

Operating System

- Windows

Libraries

- jQuery version:
- bootstrap-fileinput version: 5.1.2

**Comment by kartik-v** [comment]
Disable preview of such files by setting [`disabledPreviewExtensions`](https://plugins.krajee.com/file-input/plugin-options#disabledPreviewExtensions) or  [`disabledMimeTypes`](https://plugins.krajee.com/file-input/plugin-options#disabledPreviewMimeTypes)

For example you can disable the extensions by setting:

```
disabledPreviewExtensions: ['psd']
```

For example you can disable these mime types by setting

```
disabledPreviewMimeTypes: [
    'image/vnd.adobe.photoshop',
    'application/x-photoshop',
    'application/photoshop',
    'application/psd',
    'image/psd'
]
```
