### ISSUE TITLE
New property ajaxSettings to allow configuring ajax params

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#162]
A new property `ajaxSettings` will be added that will allow setting own tokens in headers or allow developers to setup advanced ajax options.

**Comment by sijo-vijayan** [comment]
Hi,

I would like to pass a Token as the http header along with this fileupload http request, Can you give me an example code for this purpose ?

I'm using this with in an angularjs application, this is currently what i have done.

	zentieraDirectives.directive('fileinput', function($rootScope) {
		return {
			restrict: 'A',
			link: function(scope, element, attrs) {
				$(element).fileinput({ 'uploadUrl' : $rootScope.STATIC_URL+'users/addPhoto', ajaxSettings : { headers: { Token: 'Bearer ' } } });
			}
		};
	});

Header value appearing in wrong place, refer the attached image

![desctop screenshot](https://cloud.githubusercontent.com/assets/7643651/14559250/ecff569e-0324-11e6-8340-0469a9d0bc1e.png)

**Comment by owenek1** [comment]
I have the same problem as @sijo-vijayan. Any update about that ?
