### ISSUE TITLE
Draggable files weight not passed on form submission

### ISSUE THREAD

**Issue by Aporie** [kartik-v/bootstrap-fileinput#1620]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Make sure showDrag option is set to true
2. Save files and reload the pages. You'll have the draggable icon on the files.
3. Reorder the files
4. Save the form
5. $_FILES['files'] returns as empty preventing any backend action to reorder the files as wished by the user.

## Expected behavior and actual behavior

When I reorder the files and save.
I should get the new weight related to each files in $_FILES['files'] so I can perform relevant backend task to save the new order.

## Environment

Not relevant.

Libraries

- jQuery version:
- bootstrap-fileinput version: 5.1.2

**Comment by Aporie** [comment]
Any news on this ?

**Comment by kartik-v** [comment]
With files submitted via FORM you can only receive the newly selected files on client in $_FILES. You cannot use $_FILES to read your server uploaded files. 

For sorting and reading files that are sorted - you need to use the [`filesorted` event](https://plugins.krajee.com/file-input/plugin-events#filesorted) and call your javascript code to directly send reordered file data to server or store it in an hidden input on the client and read via form submit.

**Comment by Aporie** [comment]
Hi @kartik-v ,

Thanks for the answer and the great work on this library, never ran into this event. It seems to do exactly what I need.
