### ISSUE TITLE
Problem with order on upload

### ISSUE THREAD

**Issue by Minotti** [kartik-v/bootstrap-fileinput#1624]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Select two or more images with differents MB.
2. uploadAsync as true
3. auto upload activated

## Expected behavior and actual behavior

When I follow those steps, I see...

The problem happens when I send several images of different sizes.

Let's assume they are 5mb, 3mb and 1mb. Naturally, the shipping order will be 1, 3, 5 MB. However, the order that appears visible to the user is 5, 3, 1.

Searching here on Github I found two Issues that would "solve" this problem. I applied what was requested and still my problem persists.

What do I need to do to upload the image selection sequence? In the example, 5mb should be done first, then 3mb and then 1mb.

I suspect it has been resolved in the past and is now not working again.

Here is my configuration:

$ el.fileinput ({
                allowedFileExtensions: ['jpg', 'png', 'gif'],
                uploadUrl: "{{route ('upload-image')}}",
                uploadAsync: true,
                deleteUrl: "{{route ('delete-image')}}",
                showUpload: false, // hide upload button
                overwriteInitial: true, // append files to initial preview
                minFileCount: 1,
                initialPreviewAsData: true,
                language: 'pt-BR',
                uploadExtraData: {'_token': "{{csrf_token ()}}", 'cliente_id': client},
                ajaxDeleteSettings: {
                    type: "POST",
                    headers: {'X-CSRF-TOKEN': "{{csrf_token ()}}"}
                }
            }). on ("filebatchselected", function (event, output) {
                $ el.fileinput ("upload");
            })
## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: 5.1.2

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

![Seleção_025](https://user-images.githubusercontent.com/17681478/92482874-1fea1d80-f1b6-11ea-83df-e2604db13711.png)
![Seleção_026](https://user-images.githubusercontent.com/17681478/92482879-2082b400-f1b6-11ea-9234-7202a581c47a.png)

**Comment by kartik-v** [comment]
This is a programming issue from your end to solve.

For your use case, you need to set `uploadAsync` to `false` if you want a sequential / synchronous upload in the SAME order as the files selected by user on the client. In this case you would receive an array of file objects on your server code and you need to handle the entire uploaded file stack on your server and return success when all done.

You are setting `uploadAsync` to `true` - this will always be asynchronous and parallel (which triggers multiple requests to the server) and whichever completes first will get done -- so handle it accordingly in your program as per your use case.

**Comment by Minotti** [comment]
Can close the ticket. I solved this with other ways.
