### ISSUE TITLE
Problem with russian filenames after upload

### ISSUE THREAD

**Issue by attentive20** [kartik-v/bootstrap-fileinput#1626]
![fileinput](https://user-images.githubusercontent.com/71190913/93004075-6cce4b00-f54c-11ea-8d23-6511756a6b02.jpg)

Hello!
I am using Laravel and encore laravel-admin for development. There is a problem with russian filenames. The preview is good. But after upload, the first word of the file name disappears. If the file is one word, only the extension is shown. Everything is normal with english names. Tried different options, nothing helps. slugCallback - as I understand it, it only applies to previews, but everything is fine with previews. The problem is exactly after uploading the file to the server. In this case, the file name in the table is correct, the link to it also contains the full name. What can be wrong?

**Comment by kartik-v** [comment]
The [`slugCallback`](https://plugins.krajee.com/file-input/plugin-options#slugCallback) controls both the file name displayed in preview as well as the filename returned to server for each file object (when using plugin in ajax submission mode).

So you need to configure `slugCallback` for your use case and try (probably return the raw file name without processing first and then filter out the special characters)...  note that if you are changing `slugCallback` you need to handle special character issues not understood by javascript and may break your code or throw errors.

**Comment by attentive20** [comment]
![fileinput2](https://user-images.githubusercontent.com/71190913/93017535-376c4080-f5d2-11ea-8a9a-edd3c3d2c44c.jpg)

Yes, the problem appears in absolutely all russian file names. More examples below.

![fileinput3](https://user-images.githubusercontent.com/71190913/93017584-8f0aac00-f5d2-11ea-8dd8-4486e209b8ca.jpg)

**Comment by attentive20** [comment]
About slugCallback. I tried to override this function in my code but it didn't work.

![fileinput4](https://user-images.githubusercontent.com/71190913/93018979-bbc3c100-f5dc-11ea-9aac-0f40b4af0a08.jpg)

Fixed this in the original file.

![fileinput5](https://user-images.githubusercontent.com/71190913/93019014-fe859900-f5dc-11ea-8f18-778bcd1137e9.jpg)

I don't know javascript, just for experimenting. For example, I did it as in the documentation. But this did not work. Original file name Список_нет_ИНН.csv. Before upload the name was shown Список-нет_ИНН.csv (replaced by one of the two characters). After upload, nothing has changed. It was the same before the correction of this function.

![fileinput6](https://user-images.githubusercontent.com/71190913/93019142-e3675900-f5dd-11ea-9725-955902b2376a.jpg)

Tried plugin version 4.5.2 and latest 5.1.3, the result is the same.

**Comment by kartik-v** [comment]
Ok from your report, this is not an upload issue or slugCallback  issue ... so you are looking at the wrong section to fix this. The upload seems to be working fine with the RIGHT filename and is uploaded to server correctly as seen.

This seems to be an issue in the uploaded data being read via `initialPreview`  and `initialPreviewConfig` - can you debug what is the `filename` and `caption` you are passing for each file and what is being detected in the JSON config for above two properties?

**Comment by attentive20** [comment]
Thanks you! The problem has been resolved. The php "basename" function does not work correctly with russian filenames. That was the reason.
