### ISSUE TITLE
How to obtain the image of "file-preview" for editing?

### ISSUE THREAD

**Issue by jheffers0n** [kartik-v/bootstrap-fileinput#163]
How to obtain the image of "file-preview" for editing?
For example: You have a button on the file-preview by clicking and get the url of the file-preview of the image to make editing

![filepreview](https://cloud.githubusercontent.com/assets/3834245/6068539/08f88888-ad64-11e4-8b39-ab4e9fd86d96.png)

**Comment by kartik-v** [comment]
The image shown on preview before upload - is a blob and not straightforward to edit. You would need to use HTML5 canvas or something to edit it. You can read the files object and retrieve the blob information using `FileReader` object.

If your image is not saved to the server - its straightforward to access it as a normal img URL.
