### ISSUE TITLE
Encrypt files before upload to server - best place to intercept them

### ISSUE THREAD

**Issue by kofarrell1076** [kartik-v/bootstrap-fileinput#1630]
I need to encrypt the selected files before uploading them and looking to see where the best place to intercept this is - assuming filebatchpreupload is it.  Can I replace the selected files with their encrypted versions or just pass the encrypted arrays to the upload? 

Looking to see what the best suggestion is
thanks

**Comment by kartik-v** [comment]
I am not clear on the use case -- but you could always set the `uploadUrl` property to a server code which will handle all this ... i.e. encrypt the client uploaded files and then saves it to the final destination..

**Comment by kofarrell1076** [comment]
E2EE encryption -  the key only exists on the client and not (and never) on the server. Any file to be uploaded to the server url needs to be pass through  the encryption first, then uploaded.

**Comment by kartik-v** [comment]
You can handle it via the plugin methods - like [`getFileStack`](https://plugins.krajee.com/file-input/plugin-methods#getFileStack) and [`getFileList`](https://plugins.krajee.com/file-input/plugin-methods#getFileList) etc... and create your own upload button that uses these methods and sends file data - but I will check if there is any enhancement that can be done here to allow processing files on client.

**Comment by kofarrell1076** [comment]
Ok you made me think about approching this a different say way and handle the upload using getFileStack instead.

Is there a definition for fileObj in this example? I'm trying to get a blob or file so I can pass to my encrypt function but need to understand what fileObj is.

thanks

var filestack = $('#input-id').fileinput('getFileStack'), fstack = [];
$.each(filestack, function(fileId, fileObj) {
    if (fileObj !== undefined) {
        fstack.push(fileObj);
    }
});

**Comment by kofarrell1076** [comment]
Quick question - Does getFilestack actually read in the files or just give you a list of what's been selected. 

I'm doing  a FileReader/readAsArrayBuffer later on and it complains that "Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'." which usually means the files have just been selected and not read.

thanks

**Comment by kartik-v** [comment]
I added an enhancement. There is a new property `preProcessUpload` - this is a function callback which you can set to send the converted/encrypted content before upload. This will work for ajax upload modes but not for resumable uploads.

Some steps to achieve your use case:

Use the `fileloaded` event to read the file content and store the encrypted file in a global object and return it via the preProcessUpload event.

```js
var encryptedFileStack = {}; // a global object to store your encrypted files
$('#input').on('fileloaded', function(e, file, previewId, fileId, reader, index) {
     encryptedFileStack[fileId] = your_encrypt_method(file, reader);  // the reader will return the filereader instance
});
$('#input').fileinput({
    preProcessUpload: function(fileId) {
        return encryptedFileStack[fileId];
    },
    // your other plugin settings    
});
```

Note the `your_encrypt_method` is a javascript method you need to write to encrypt each file content.

**Comment by kartik-v** [comment]
I added an enhancement with the above commit. There is a new property `preProcessUpload` - this is a function callback which you can set to send the converted/encrypted content before upload. This will work for ajax upload modes but not for resumable uploads.

Some steps to achieve your use case:

Use the `fileloaded` event to read the file content and store the encrypted file in a global object and return it via the preProcessUpload event.

```js
var encryptedFileStack = {}; // a global object to store your encrypted files
$('#input').on('fileloaded', function(e, file, previewId, index, reader, fileId) {
     encryptedFileStack[fileId] = your_encrypt_method(file, reader);  // reader will return the filereader object instance
});
$('#input').fileinput({
    preProcessUpload: function(fileId) {
        return encryptedFileStack[fileId];
    },
    // your other plugin settings    
});
```

Note the `your_encrypt_method` is a javascript method you need to write to encrypt each file content.

**Comment by kartik-v** [comment]
I added an enhancement with the above commit. There is a new property `preProcessUpload` - this is a function callback which you can set to send the converted/encrypted content before upload. This will work for ajax upload modes but not for resumable uploads.

Some steps to achieve your use case:

Use the `fileloaded` event to read the file content and store the encrypted file in a global object and return it via the preProcessUpload event.

```js
var encryptedFileStack = {}; // a global object to store your encrypted files
$('#input').on('fileloaded', function(e, file, previewId, fileId, index, reader) {
     encryptedFileStack[fileId] = your_encrypt_method(file, reader);  // reader will return the filereader object instance
});
$('#input').fileinput({
    preProcessUpload: function(fileId) {
        return encryptedFileStack[fileId];
    },
    // your other plugin settings    
});
```

Note the `your_encrypt_method` is a javascript method you need to write to encrypt each file content.

NOTE: That when using `preProcessUpload` the file content will be returned as NORMAL POST data and not RAW FILES data. The POST key name will match file input `name` attribute. For a multiple upload you must set the `name` attribute to array square brackets format.

**Comment by kartik-v** [comment]
I added an enhancement with the above commit to help achieve this easier. There is a new property [`preProcessUpload`](https://plugins.krajee.com/file-input/plugin-options#preProcessUpload) - this is a function callback which you can set to return the converted/encrypted content before upload. This will work for ajax upload modes but not for resumable uploads.

Some steps to achieve your use case:

Use the[`fileloaded`](https://plugins.krajee.com/file-input/plugin-events#fileloaded) event or maybe [`filebatchselected`](https://plugins.krajee.com/file-input/plugin-events#filebatchselected) event to read the file content and store the encrypted file in a global object and return it via the preProcessUpload event.

```js
var encryptedFileStack = {}; // a global object to store your encrypted files
$('#input').on('fileloaded', function(e, file, previewId, fileId, index, reader) {
    // reading via file reader - reader will return the filereader object instance if using with PREVIEW 
    // if no preview is enabled - then reader will be undefined
    encryptedFileStack[fileId] = your_encrypt_method(file, reader);     
});
$('#input').fileinput({
    preProcessUpload: function(fileId) {
        return encryptedFileStack[fileId];
    },
    // your other plugin settings    
});
```

Note the `your_encrypt_method` is a javascript method you need to write to encrypt each file content.

NOTE: That when using `preProcessUpload` the file content will be returned as NORMAL POST data and not RAW FILES data. The POST key name will match file input `name` attribute. For a multiple upload you must set the `name` attribute to array square brackets format.

**Comment by kartik-v** [comment]
I added an enhancement with the above commit to help achieve this easier. There is a new property [`preProcessUpload`](https://plugins.krajee.com/file-input/plugin-options#preProcessUpload) - this is a function callback which you can set to return the converted/encrypted content before upload. This will work for ajax upload modes but not for resumable uploads.

Some steps to achieve your use case: 

*SCENARIO 1:* You can directly process the file via your own routine at runtime just before upload by setting

```js
$('#input').fileinput({
    preProcessUpload: function(fileId, file) { // file is the selected file object 
        return your_direct_encrypt_method(file); // this is your client encryption method
    },
});
```
*SCENARIO 2:*  You can use events to read file data and encrypt at that appropriate actions. For example, you can use the [`fileloaded`](https://plugins.krajee.com/file-input/plugin-events#fileloaded) event or maybe [`filebatchselected`](https://plugins.krajee.com/file-input/plugin-events#filebatchselected) event to read the file content and store the encrypted file in a global object and return it via the preProcessUpload event.

```js
var encryptedFileStack = {}; // a global object to store your encrypted files
$('#input').on('fileloaded', function(e, file, previewId, fileId, index, reader) {
    // reading via file reader - reader will return the filereader object instance if using with PREVIEW 
    // if no preview is enabled - then reader will be undefined
    encryptedFileStack[fileId] = your_encrypt_method(file, reader);     
});
$('#input').fileinput({
    preProcessUpload: function(fileId, fileData) {
        return encryptedFileStack[fileId];
    },
    // your other plugin settings    
});
```

Note the `your_encrypt_method` is a javascript method you need to write to encrypt each file content.

NOTE: That when using `preProcessUpload` the file content will be returned as NORMAL POST data and not RAW FILES data. The POST key name will match file input `name` attribute. For a multiple upload you must set the `name` attribute to array square brackets format.

**Comment by kofarrell1076** [comment]
Excellent. We'll take a look.

Thanks for the great response.
