### ISSUE TITLE
How to hide error icon

### ISSUE THREAD

**Issue by TorreyGarland** [kartik-v/bootstrap-fileinput#1633]
How do you hide the error icon that displays on form validation.

We are using fileinput for an MVC 5 project using bootstrap and admin bsb.

Everything works perfectly, except that we do not want to display the exclamation icon after jQuery validation executes?

**Comment by kartik-v** [comment]
Not sure of what you want to achieve for your use case -- but please cross check documentation for various configurations.

The error icon in each thumbnail can be controlled via [`fileActionSettings.indicatorError`](https://plugins.krajee.com/file-input/plugin-options#fileActionSettings)

The error message icon can be controlled via [`msgValidationErrorIcon`](https://plugins.krajee.com/file-input/plugin-options#msgValidationErrorIcon)

**Comment by TorreyGarland** [comment]
Thanks, that works.
