### ISSUE TITLE
There are some problems with the method "getFileList" in the latest version

### ISSUE THREAD

**Issue by NoobLearnPrograming** [kartik-v/bootstrap-fileinput#1634]
In version 5.0.4, the file list can be obtained through '$(ele).fileinput("getFileList")', but not in 5.1.2.And,the method "getFilesCount" is correct.

**Comment by kartik-v** [comment]
Seems to work fine and not sure can reproduce your issue. Can you please share a JS Fiddle to reproduce your use case.
