### ISSUE TITLE
Problem displaying uploaded images in IE11

### ISSUE THREAD

**Issue by PingPongSet** [kartik-v/bootstrap-fileinput#1638]
There is an error displaying uploaded images in IE11 like below. 

It displays the same file two times:
![image](https://user-images.githubusercontent.com/2021414/95098938-376de500-0727-11eb-9ccb-b480d4b07236.png)

via the link below:
https://plugins.krajee.com/file-basic-usage-demo#basic-example-1

This is the original file uploaded:
![image](https://user-images.githubusercontent.com/2021414/95099290-96cbf500-0727-11eb-8b5d-cce9bd3bc520.png)

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. go to https://plugins.krajee.com/file-basic-usage-demo#basic-example-1 via IE11
2. Upload an image
3. Two images displayed

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [X] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Fixed via above commit

**Comment by PingPongSet** [comment]
@kartik-v 

When will the fix be available for download for use?
