### ISSUE TITLE
 SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by JorgeNaranjo90** [kartik-v/bootstrap-fileinput#164]
Hello!

I setting the 

        uploadUrl: 'http://localhost/mipagina/model/prueba.php',

this is correct or what data should be colocate?

 SyntaxError: Unexpected token < or

https://docs.google.com/file/d/0B2bco2o-KDzGVlVnZjNnY3dTNUU/edit?usp=drivesdk

**Comment by kartik-v** [comment]
Duplicate to #138, #129, #127.

Search and check for other similar issues before posting a new one.
