### ISSUE TITLE
change blob file before update

### ISSUE THREAD

**Issue by hannanstd** [kartik-v/bootstrap-fileinput#1641]
hi
how we can update/replace/change FileBlob before upload?

**Comment by kartik-v** [comment]
Not sure why you need that. The plugin is designed to send files selected directly to the server without modifications (except minor processing for certain file types like image files to resize). 

You can use events like [`filebatchpreupload`](https://plugins.krajee.com/file-input/plugin-events#filebatchpreupload) and or read the file blob stack via `getFileStack` method and set `uploadExtraData` to send additional data to your server code.
