### ISSUE TITLE
Filebatchpreupload abort issue when show preview is false

### ISSUE THREAD

**Issue by lorife** [kartik-v/bootstrap-fileinput#1642]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. add event:

 }).on('filebatchpreupload', function(event, data, id, index) {
  	  	
  	  return {
                message: "Upload aborted!", // upload error message
                data:{} // any other data to send that can be referred in `filecustomerror`
            };
})

2. click browse and select file
3. click upload

## Expected behavior and actual behavior

When I follow those steps, I see...

the component shows the error and disables itself. 

I was expecting...

To see the error and try again

## Environment

Browsers

- [x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 5.1.2, 5.1.3

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by lorife** [comment]
I just found out It happens when:

showPreview: false

**Comment by kartik-v** [comment]
Please share a JS Fiddle to understand your issue. Currently releasing v5.1.3 and if an enhancement is needed for this will be taken in the next release.

**Comment by lorife** [comment]
Hello, 
it was just the lines I added when I opened the issue...
Anyway I created a jsfiddle:

https://jsfiddle.net/lorife/547aorLn/4/

just select any file anche click upload

**Comment by lorife** [comment]
Hello, why is this closed?

**Comment by kartik-v** [comment]
Hi the stale bot has closed your request. Am reopening this.

**Comment by kartik-v** [comment]
Hi - it seems to work fine - you had a wrong configuration in the return message (returning an invalid variable).

Here is the [updated fiddle which works](https://jsfiddle.net/lorife/547aorLn/4/).

**Comment by kartik-v** [comment]
Confirm this. This was intended to be like that. Will check if an enhancement can be provided.

**Comment by kartik-v** [comment]
Enhanced via the fix provided.
