### ISSUE TITLE
delete right after update does not call deleteurl

### ISSUE THREAD

**Issue by lorife** [kartik-v/bootstrap-fileinput#1647]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. select a file and upload using the upload button in the preview
2. it will upload successfully and change the icon in the preview with a green confirmation
3. press the remove button in the preview. It will get removed from the preview but it will not call the delete url so it will not delete the file on the disk

## Expected behavior and actual behavior

see above point 3

## Environment

Browsers

- [ ] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

jQuery version: 3.3.1
bootstrap-fileinput version: 5.1.3

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by Lreus** [comment]
It seems that 'click' event is not handled on the remove button once the file is uploaded. May be calling 
`_initPreviewActions` after the upload process could help ?

**Comment by anandphulwani** [comment]
This is a definite bug, i have tested the following that ,

it is working on
```
4.4.5
4.5.3
5.0.0
5.0.5
5.0.6 (some js errors on load/upload)
5.0.7
5.0.8
```

and it is not working on
```
5.0.9 (some js errors on load/upload)
5.1.0
5.1.1
5.1.2
5.1.3
5.1.4
5.1.5
```
Try using 5.0.8 and see if that build works for you.

I will fork it out and check if i can resolve this on my own, and create a PR for the same.

**Comment by kartik-v** [comment]
Thanks for the report. Please share a JS Fiddle or similar to understand and reproduce this. Thanks.

**Comment by anandphulwani** [comment]
> 
> 
> Thanks for the report. Please share a JS Fiddle or similar to understand and reproduce this. Thanks.

Just did, on an older issue, i have resolved it, i have resolved it sending you a PR soon.

**Comment by anandphulwani** [comment]
@kartik-v I just checked the `filesuccessremove` event is being called properly but the `deleteUrl` is still not being called. Any suggestions where i can look into.

**Comment by anandphulwani** [comment]
> 
> 
> @kartik-v I just checked the `filesuccessremove` event is being called properly but the `deleteUrl` is still not being called. Any suggestions where i can look into.

@kartik-v So this is my observation, when i am using AJAX async upoads, from server side if i return just the url's of the file in a non associative array format, the `deleteUrl` parameter doesn't work. If i return values in the following format 

```
$config[] = [
    'key' => ........,
    'caption' => ........,
    'size' => ........,
    'downloadUrl' => ........,
];
$out = ['initialPreview' => $preview, 'initialPreviewConfig' => $config, 'initialPreviewAsData' => true];
```
The `deleteUrl` works. So according to me if the file is uploaded successfully, `deleteUrl` should work irrespective of whatever format of data is returned. Your thoughts?

**Comment by crestAT** [comment]
Sorry to resurrect this issue but I'm still not able to let files be deleted right after uploads. I use the latest release of the plugin (5.2.1) and all file manipulations work fine, files will be deleted from the server as defined in the initialPreviewConfig but not immediately after uploads.

As @anandphulwani mentioned it should work at least with a deleteUrl format according to the initialPreviewConfig but neither with this format nor with a simple string format the files will be deleted from the server right after the upload. Could you please provide an example for the deleteUrl definition or lead me to an example where I can compare it to my definitions, many thanks in advance!

By the way, I use `.on('filebeforedelete', function() { ... ` to ask the user if he really wants to delete the file so shouldn't this function also be called in the above mentioned case or am I missing something here ...

**Comment by kartik-v** [comment]
Its a simple config. Check the docs for configuring `initialPreview` and `initialPreviewConfig`.

You can check the [ajax demo example # 5](https://plugins.krajee.com/file-input-ajax-demo/5) on the plugin demos site. Try uploading 2 to 3 files and you will see `initialPreview` and `initialPreviewConfig` being returned immediately after upload - including the delete url. When you click the delete button you can check the Delete AJAX requests being fired as well.

**Comment by crestAT** [comment]
Thank you for the quick response, will check it asap!

**Comment by crestAT** [comment]
Checked your proposal and it's working perfectly, thanks a lot for your support and this great plugin!!!
