### ISSUE TITLE
Maximum Image Dimensions is not working on ff

### ISSUE THREAD

**Issue by javatlacati** [kartik-v/bootstrap-fileinput#1649]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue

1. On firefox open the documentation demos at https://plugins.krajee.com/file-image-dimensions-demo
2. in the second demo upload a file larger than 250 x 250
3. The plugin accepts it without complaining

## Expected behavior and actual behavior

When I follow those steps, there should be a validation error but there's none

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- bootstrap-fileinput version: 201909132002

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

Screenshots:

![image](https://user-images.githubusercontent.com/1063901/97819397-eab9f300-1c6d-11eb-9189-8bfb04989a36.png)

![image](https://user-images.githubusercontent.com/1063901/97819417-fa393c00-1c6d-11eb-8a57-3670b354b987.png)

![image](https://user-images.githubusercontent.com/1063901/97819443-28b71700-1c6e-11eb-97c3-a2388ff35228.png)

**Comment by FrideyAlpha** [comment]
Hi, I'm also experiencing this issue and I've fixed this by comments return statement line 4493 inside fileinput.js.

![fix bootstrap-fileinput](https://user-images.githubusercontent.com/20950458/100825359-6c2dbc80-348a-11eb-9440-0924766003bf.png)

Please test it first, it may be suitable for your use-case
I'm using version 5.1.3 of bootstrap-fileinput

**Comment by kartik-v** [comment]
@FrideyAlpha actually commenting that line would cause issues on other browsers like Chrome, Edge etc. This needs to be checked (specific to Firefox).

**Comment by FrideyAlpha** [comment]
@kartik-v yup I think this issue needs to be checked and tested in various browsers. I would prefer to use an official patch from you when it is available.

**Comment by Junisyoan** [comment]
@kartik-v I had the same problem with Chrome and Edge. And not only width and height, but also the number of files limit is also invalid

**Comment by kartik-v** [comment]
@Junisyoan  can you share a JS Fiddle to reproduce and understand your issue?

**Comment by zeejee94** [comment]
> @Junisyoan can you share a JS Fiddle to reproduce and understand your issue?

hi,im facing same problem even i tested on the your demo page same problem happened that unable to resize.

**Comment by kartik-v** [comment]
Fixed via above commit
