### ISSUE TITLE
event [fileuploaded] does not fire when setting [showPreview: false,]

### ISSUE THREAD

**Issue by reedgz** [kartik-v/bootstrap-fileinput#165]
File upload is okay but "fileuploaded" event was never fired.  Therefore I can not get response value which contains the file URL from the server.

```javascript
    $("#fileToUpload").fileinput({
        maxFileSize: 1000,
        allowedFileTypes: ['image'],
        dropZoneEnabled: false,
        showPreview: false,
        showRemove: false,
        uploadAsync: false,
        uploadUrl: "{{ upload_url }}", // your upload server url
    });

    $('#fileToUpload').on('fileuploaded', function(event, data, previewId, index) {
        // var form = data.form, files = data.files, extra = data.extra, 
        //     response = data.response, reader = data.reader;
        console.log('File uploaded triggered');
    });
```

**Comment by kartik-v** [comment]
You need to use "filebatchuploaded" event - instead read docs... this will fire for both async or sync uploads.

The "fileuploaded" event fires only 

1. if you upload each individual file using upload icon on each preview thumbnail, OR
2  when you use it with `uploadAsync` set to true... (even in this case it will fire multiple times after every file is uploaded).

The "filebatchuploaded" event however fires for both cases of ajax uploads - at the end after completion of all uploads.

**Comment by kartik-v** [comment]
You need to use **filebatchuploadcomplete** event instead. Read docs... this event will fire for both async or sync uploads.

The **fileuploaded** event fires only 

- if you upload each individual file using upload icon on each preview thumbnail, OR
- when you use it with `uploadAsync` set to true... (even in this case it will fire multiple times after every file is uploaded).

The **fileuploaded** event will thus never fire for sync uploads when `uploadAsync` is false.

The **filebatchuploadcomplete** event however fires for both cases of ajax uploads - at the end after completion of all uploads.

**Comment by reedgz** [comment]
Thanks for the super fast help!

Actually the desired event is **filebatchuploadsuccess** as it has **data.response** in callback.
