### ISSUE TITLE
generateFileId

### ISSUE THREAD

**Issue by javirojas6** [kartik-v/bootstrap-fileinput#1651]
Hi, I have used this worderful library. It works everything perfectly, but I want to customize the fileId. This library uses this function for generate fileid:

var relativePath = $h.getFileRelativePath(file);
            if (typeof generateFileId === 'function') {
                return generateFileId(file);
            }
            if (!file) {
                return null;
            }
            if (!relativePath) {
                return null;
            }
            return (file.size + '_' + encodeURIComponent(relativePath).replace(/%/g, '_'));

I want to change the fileId I make on the uploadfile php. After changing this fileId, I want to use this new fileId from on:
on('fileuploaded', function (event, previewId, index, fileId) event. this event returned the filesize + name of file and I want to catch here the fileid I have changed on upload.php. I have checked the attribute generateFileId, but I do not know how to use in my program. I add this on the properties of fileinput:
function (file) {
    if (!file) {
        return null;
    }    
    var relativePath = String(file.relativePath || file.webkitRelativePath || $h.getFileName(file) || null);
    if (!relativePath) {
        return null;
    }
    return ("1111" + '_' + encodeURIComponent(relativePath).replace(/%/g, '_'));
}
I have used "1111" instead of  the filesize. But there is no appreciate this change on the fileupload event.

Could you help me please. I would appreciate. thank you in advance.

**Comment by kartik-v** [comment]
The parameters which you will be able to parse in the `fileuploaded` event depends on whether you use ajax upload or resumable upload ... [refer the fileuploaded event in docs](https://plugins.krajee.com/file-input/plugin-events#fileuploaded) - 

assuming you are using ajax async but non resumable uploads mode -- you can get the following params in fileuploaded event:
```js
$('#input-id').on('fileuploaded', function(event, outData, previewId, index, fileId) {
    console.log('File uploaded', outData, previewId, index, fileId);
});
```

**Comment by javirojas6** [comment]
thank you very much Kartik!!    En domingo, 8 de noviembre de 2020 06:35:51 CET, Kartik Visweswaran <notifications@github.com> escribió:  
 
 


The parameters which you will be able to parse in the fileuploaded event depends on whether you use ajax upload or resumable upload ... refer the fileuploaded event in docs -

assuming you are using ajax async but non resumable uploads mode -- you can get the following params in fileuploaded event:
$('#input-id').on('fileuploaded', function(event, outData, previewId, index, fileId) {
    console.log('File uploaded', outData, previewId, index, fileId);
});
