### ISSUE TITLE
Problems displaying css in certain situations with hidden form elements

### ISSUE THREAD

**Issue by jimtalksdata** [kartik-v/bootstrap-fileinput#1654]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Load a fileinput element and disable it on page load (fileinput('disable') in an onLoad function) on a page with imports but no button element
2. Enable it via javascript
3. Attempt to upload, and buttons do not appear
4. To solve, have any button (or object with class="btn") somewhere on the page (even if hidden) (???)

(Sometimes the problem happens after a page reload?)

## Expected behavior and actual behavior

When I follow those steps, I see...

Missing zoom/etc buttons icons

I was expecting...

Buttons

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 5.0.9

Version 86.0.4240.193 (Official Build) (64-bit)

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

Broken: https://jsbin.com/politoxeyo/3/edit?html,js,output
1. Enter stuff in email field
2. Click on Browse and load a file
3. Refresh page (F5)
4. Enter stuff in email field
5. Click on Browse and load a file

Output: ![broken](https://user-images.githubusercontent.com/56103/98898284-e1e9ce00-2472-11eb-8db9-2925f39fcb5d.png)

Working: (javascript for element hiding disabled)
https://jsbin.com/hisoyot/1/edit?html,js,output

I cannot replicate this problem using a local html file.

**Comment by jimtalksdata** [comment]
I worked around this problem by adding an async function to disable the form after 100 ms.

**Comment by kartik-v** [comment]
I am not sure where the problem is. The zoom icons etc. are set by default to GLYPHICONS ... you need to load the GLYPHICON CSS library for them to be rendered. Else change to use Krajee Fontawesome 5 theme and load font awesome CSS on the page to view the zoom icons etc.
