### ISSUE TITLE
Correct error in getThumbFileId 

### ISSUE THREAD

**Issue by ehsanharani** [kartik-v/bootstrap-fileinput#1656]
## Prerequisites

- Hi
 I have installed asset files in my project. but when I use $("#input-55").fileinput(); I get this error in console log
Uncaught RangeError: Maximum call stack size exceeded
    at i._getThumbFileId (fileinput.min.js:12)

please help me .

**Comment by ashm78** [comment]
hi, the same problem.
fileinput.js:3458 Uncaught RangeError: Maximum call stack size exceeded
    at FileInput._getThumbFileId (fileinput.js:3458)

**Comment by ehsanharani** [comment]
I can solve it. 
update js files to last versions.
or you can use cdn links




```

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
           crossorigin="anonymous">
     <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput.min.css" media="all"
           rel="stylesheet" type="text/css"/>
     <!-- if using RTL (Right-To-Left) orientation, load the RTL CSS file after fileinput.css by uncommenting below -->
     <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput-rtl.min.css" media="all"
           rel="stylesheet" type="text/css">
     <!-- the font awesome icon library if using with `fas` theme (or Bootstrap 4.x). Note that default icons used in the plugin are glyphicons that are bundled only with Bootstrap 3.x. -->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
     <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
     <!-- piexif.min.js is needed for auto orienting image files OR when restoring exif data in resized images and when you
         wish to resize images before upload. This must be loaded before fileinput.min.js -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/piexif.min.js"
             type="text/javascript"></script>
     <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
         This must be loaded before fileinput.min.js -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/sortable.min.js"
             type="text/javascript"></script>
     <!-- popper.min.js below is needed if you use bootstrap 4.x (for popover and tooltips). You can also use the bootstrap js
        3.3.x versions without popper.min.js. -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
     <!-- bootstrap.min.js below is needed if you wish to zoom and preview file content in a detail modal
         dialog. bootstrap 4.x is supported. You can also use the bootstrap js 3.3.x versions. -->
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
             crossorigin="anonymous"></script>
     <!-- the main fileinput plugin file -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/fileinput.min.js"></script>
     <!-- following theme script is needed to use the Font Awesome 5.x theme (`fas`) -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/themes/fas/theme.min.js"></script>
     <!-- optionally if you need translation for your language then include the locale file as mentioned below (replace LANG.js with your language locale) -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/locales/fa.js"></script>

```

**Comment by ashm78** [comment]
Yeah.
Im updated fileinput.js to last good version 5.1.3.
5.1.4 - not working (

**Comment by dangevile** [comment]
> hi, the same problem.
> fileinput.js:3458 Uncaught RangeError: Maximum call stack size exceeded
> at FileInput._getThumbFileId (fileinput.js:3458)

hi,the same  problem .
fileinput.js:3458 Uncaught RangeError: Maximum call stack size exceeded
    at FileInput._getThumbFileId (fileinput.js:3458)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)

**Comment by ashm78** [comment]
> > hi, the same problem.
> > fileinput.js:3458 Uncaught RangeError: Maximum call stack size exceeded
> > at FileInput._getThumbFileId (fileinput.js:3458)
> 
> hi,the same problem .
> fileinput.js:3458 Uncaught RangeError: Maximum call stack size exceeded
> at FileInput._getThumbFileId (fileinput.js:3458)
> at FileInput._getThumbFileId (fileinput.js:3460)
> at FileInput._getThumbFileId (fileinput.js:3460)
> at FileInput._getThumbFileId (fileinput.js:3460)
> at FileInput._getThumbFileId (fileinput.js:3460)
> at FileInput._getThumbFileId (fileinput.js:3460)
> at FileInput._getThumbFileId (fileinput.js:3460)
> at FileInput._getThumbFileId (fileinput.js:3460)
> at FileInput._getThumbFileId (fileinput.js:3460)
> at FileInput._getThumbFileId (fileinput.js:3460)

working version: https://plugins.krajee.com/assets/8079bede/js/fileinput.min.js?ver=201909132002

**Comment by ehsanharani** [comment]
use this cdn links

`

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
           crossorigin="anonymous">
     <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput.min.css" media="all"
           rel="stylesheet" type="text/css"/>
     
     <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput-rtl.min.css" media="all"
           rel="stylesheet" type="text/css">
     
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
     <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
     
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/piexif.min.js"
             type="text/javascript"></script>
     
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/sortable.min.js"
             type="text/javascript"></script>
     
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
     
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
             crossorigin="anonymous"></script>
     
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/fileinput.min.js"></script>
     
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/themes/fas/theme.min.js"></script>
     
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/locales/fa.js"></script>

`

**Comment by kartik-v** [comment]
Fixed via latest commit.

**Comment by kartik-v** [comment]
Fixed via latest commit.
