### ISSUE TITLE
how can  I call delete api server

### ISSUE THREAD

**Issue by ehsanharani** [kartik-v/bootstrap-fileinput#1660]
- please help me.
I call my delete url server in initialPreviewConfig but  not working at all.
I debug request content but it's empty
my url is = http://test.com/media/{id}/delete
I want to pass my id's media in this url and do somthing action but do nothing.

please help me.

**Comment by kartik-v** [comment]
You need to do one of the following (check docs) --- set either 

- *OPTION 1:* Set [`deleteUrl`](https://plugins.krajee.com/file-input/plugin-options#deleteUrl) at a global level - this url will be called for all deletes as a POST Request ... but along with this URL  `key` will be passed which you set in the `initialPreviewConfig` for each file config (check demos on how key is set for initialPreviewConfig)
- *OPTION 2:* Set `url` within each config item in `intialPreviewConfig` - even to this url the `key` will be passed as a POST request.
