### ISSUE TITLE
用了bootstrap-fileinput v5.1.4之后上传成功了，但是filesuccessremove事件失效

### ISSUE THREAD

**Issue by MeetCoder-k** [kartik-v/bootstrap-fileinput#1665]
我开始用的v5.0.6版本，想实现异步上传完成后，可以点击预览图的删除按钮把 上传完成的图片预览删掉，然后调用的filesuccessremove事件成功了，但是js会报个内部错误：Uncaught TypeError: Cannot read property 'length' of null  如下图：
![image](https://user-images.githubusercontent.com/55573983/101873339-bbc66380-3bc1-11eb-8bf1-5ea889e688e7.png)

这个报错影响接下来的上传交互，比如取消按钮被置灰了什么的，但是不影响功能。为了解决这个报错，我用了v5.1.4版本的fileinput.js，然后上传什么的没问题，但是filesuccessremove事件完全无效了。请问这是咋回事

**Comment by Junisyoan** [comment]
这几个版本有点问题，用5.1.2的，作者没有修复

**Comment by kartik-v** [comment]
Please submit the issue in English - for effective understanding of your issue.

**Comment by xumoqiu** [comment]
哈哈 大兄弟 不会Chinese吗

**Comment by kartik-v** [comment]
Seems duplicate to #1679 and will be resolved through the same.

**Comment by CaptionMyCaption** [comment]
> 哈哈 大兄弟 不会Chinese吗

不用理他，他那一口中式英语，崇洋媚外
