### ISSUE TITLE
Missing FontAwesome icons 

### ISSUE THREAD

**Issue by Mathz78** [kartik-v/bootstrap-fileinput#1666]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ X ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ X ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ X ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Use FontAwesome icons instead of Bootstrap
Use this code: 

``` 
<input id="input-fa" name="input-fa[]" type="file" multiple>
                        <script>
                            $("#input-fa").fileinput({
                                theme: "fa",
                                uploadUrl: "/file-upload-batch/2",
                                language: "pt-BR"
                            });
                        </script>
```

## Expected behavior and actual behavior

When you change to FontAwesome icons, some icons will be missing.
You can see a screenshot here: https://imgur.com/a/JwglSGs

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer
- [X] Safari

Operating System

- [X] Windows
- [X] Mac OS X
- [X] Linux
- [X] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
As mentioned in [the comment](https://github.com/kartik-v/bootstrap-fileinput/pull/1667#issuecomment-773006364)
