### ISSUE TITLE
One by one uplaod with Yii2 plugin

### ISSUE THREAD

**Issue by tlgtrn** [kartik-v/bootstrap-fileinput#1668]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Yii2 File Input Widget used but problem is about JS plugin
2. `<?php echo FileInput::widget([
            'model' => $fileModel,
            'attribute' => 'pttUserBatchFile',
            'options' => [
                'multiple' => true
            ],
            'pluginOptions' => [
                'uploadUrl' => Url::to(['/custom-user/create-batch']),
                'maxAjaxThreads' => 1,
                'maxFileCount' => 5
            ]
        ]); ?>`
3. Multiple files (4-5) has selected to upload.

## Expected behavior and actual behavior

I was expecting to upload files sequentially, only single file uplaoded at a time then second file is going to start uplaoding so on.

But all files start to upload at the same time.

**Comment by kartik-v** [comment]
Hi. There are two modes in the plugin:
1. Async: In this mode all of the files are uploaded parallely
2. Sync: In this mode all of the files are uploaded sequentially

You need to set [`uploadAsync`](https://plugins.krajee.com/file-input/plugin-options#uploadAsync) to `false` within `pluginOptions` for your use case to read and upload files sequentially.
