### ISSUE TITLE
Metro4 Support

### ISSUE THREAD

**Issue by mehmetalidumlu** [kartik-v/bootstrap-fileinput#1669]
Hi,
Is it in your plans to provide support for Metro4?
Thanks...

There is Metro4 Link: https://metroui.org.ua/m4q-about.html

**Comment by kartik-v** [comment]
Hi thanks for the suggestion. The project currently is dependent on bootstrap/jquery.

But the plugin is capable of handling other themes and JS framework. I am open to an enhancement/ pull request from anyone who can help on getting this.
