### ISSUE TITLE
Disable Upload Button on Explorer Theme

### ISSUE THREAD

**Issue by mehmetalidumlu** [kartik-v/bootstrap-fileinput#1670]
Hi,
I add "showUpload:false" setting but it visible on not uploaded item on explorer theme. Has it any setting for this issue.
Thank you. 

![image](https://user-images.githubusercontent.com/15678340/103648720-58381780-4f6e-11eb-8cba-d9a1a969e213.png)

**Comment by kartik-v** [comment]
Suggest to read docs. Setting `showUpload` property to `false` just hides the larger UPLOAD button next to the BROWSE button. To hide individual thumbnail specific buttons, you need to check the [`fileActionSettings`](https://plugins.krajee.com/file-input/plugin-options#fileActionSettings) property (check the docs) and set `fileActionSettings.showUpload` to `false`.

**Comment by mehmetalidumlu** [comment]
Thank you @kartik-v, it works.
