### ISSUE TITLE
The upload button in file-footer not working.

### ISSUE THREAD

**Issue by LedahBlack** [kartik-v/bootstrap-fileinput#1671]
## Prerequisites

- [O] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [O] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [O] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [O] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [O] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Open https://plugins.krajee.com/file-input-ajax-demo/1 in new tab.
2.choose some image.
3.click the upload button in file-footer-button.

## Expected behavior and actual behavior

When I follow those steps, I see Uncaught TypeError: Cannot read property 'find' of null.

I was expecting upload the image.

## Environment

Browsers

- [O] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [O] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:3.3.1
- bootstrap-fileinput version:5.1.3

**Comment by kartik-v** [comment]
Thanks - confirm this bug. Will check and update once I find time on this.

**Comment by LedahBlack** [comment]
@kartik-v  Thanks for your hard work.
