### ISSUE TITLE
Enhancements to add support for Bootstrap v5

### ISSUE THREAD

**Issue by Gritmatch** [kartik-v/bootstrap-fileinput#1674]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Close buttons (eg. closing error message or closing file preview in Zoom view) do not work with Bootstrap v5 because  'close' class was replaced with 'btn-close' and JQuery was removed in Bootstrap v5.

## Expected behavior and actual behavior

I know bootstrap-select currently supports Bootstrap v3 and v4 only. Is there a roadmap for the transition to Bootstrap v5?

Thank you

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.1.4

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Thanks for the update... once Bootstrap 5 stable release is out - will consider this enhancement (currently Bootstrap 5.x is in beta). However I feel that even with Bootstrap 5.x the plugin will require JQUERY to run as well as run,

**Comment by Gritmatch** [comment]
Thanks for considering the enhancement! Yes, jQuery is fine, just as long as Bootstrap 5 classes are supported.

**Comment by kartik-v** [comment]
- (enh #1674): Enhancements to add support for Bootstrap v5.
    - Major release to support Bootstrap version 5.x
    - Bootstrap version is auto detected with this release if the bootstrap javascript library is loaded
    - Additional flexibility is provided to developer to override a specific bootstrap version by setting `$.fn.fileinputBsVersion`
    - There is an existing issue for MODAL dialog initialization in Bootstrap library v5.x. This [issue with is reported](https://github.com/twbs/bootstrap/issues/33840#issuecomment-833462016) at the Bootstrap 5.x library repo with a workaround.

**Comment by kartik-v** [comment]
- (enh #1674): Enhancements to add support for Bootstrap v5.
    - Major release v5.2.0 to support Bootstrap version 5.x
    - Bootstrap version is auto detected with this release if the bootstrap javascript library is loaded
    - Additional flexibility is provided to developer to override a specific bootstrap version by setting `$.fn.fileinputBsVersion`
    - There is an existing issue for MODAL dialog initialization in Bootstrap library v5.x. This [issue is reported](https://github.com/twbs/bootstrap/issues/33840#issuecomment-833462016) at the Bootstrap 5.x library repo with a workaround.
