### ISSUE TITLE
Change UploadExtraData After Select Files Before Start Upload Process

### ISSUE THREAD

**Issue by mehmetalidumlu** [kartik-v/bootstrap-fileinput#1676]
Hi,
I cant update "uploadExtraData" after user select files. I use refresh methot but it clear selected files. 
How can i update uploadExtraData after select files, before upload files.

```
$("#file-uploader", _self).fileinput({
      theme: 'explorer',
      uploadUrl: "FileUploader.ashx",
      uploadAsync: true,
      maxFileSize:0,
      multiple: true,
      fileActionSettings: { showUpload: false },
      showUpload: false
  });
```

User select files and set some value in other form.
When user save form, send  data form to server and id value returns. When id is valid then i must set `uploadExtraData:{FormID: 1}` and send images to server.

`$("#file-uploader", _self).fileinput('upload');
`

Thanks.

**Comment by kartik-v** [comment]
You may want to go through docs and check the [`uploadExtraData`](https://plugins.krajee.com/file-input/plugin-options#uploadExtraData) property. For your use case you can try setting `uploadExtraData` as a function callback which will be executed dynamically at runtime during upload.

**Comment by mehmetalidumlu** [comment]
Hi again @kartik-v ,
I look documentation for this issue an create a local project. But `uploadExtraData` runs on select file event. I must set new record id for these images. Actually what I want to do is the following: the user will enter some information into the form. ID field is yet blank in this form. Then the user will select the pictures they want to upload. When the save button is pressed in the application, the page will be locked and the form will be sent to the server, and an ID field will appear with the successful reply. The image files selected by the user will be sent to the server with this ID information. My goal is for the user not to do the two things separately. Otherwise, the user first saves the form and then saves the pictures. But this is not a suitable solution in terms of program quality. For this reason, I asked you for help. I hope I was able to convey my problem properly.

Thank you so much
