### ISSUE TITLE
Not completing upload - dupes

### ISSUE THREAD

**Issue by Fearofthedark66** [kartik-v/bootstrap-fileinput#1677]
Hi, when uploading from a mobilephone it works fine as long as I use the camera. If i select a image from my folders it uploads the files to the server and it ends upp with these filenames.

*.jpeg_0000 and *.jpev_0001

I am running on version 5.1.3 and the latest chrome for android. Upload is handled by PHP.

Any suggestions?

**Comment by kartik-v** [comment]
This seems something you need to handle either in your app or the PHP code which receives this file - because these files are being selected from the device and the plugin does not have a control on that.

**Comment by Fearofthedark66** [comment]
I am using the PHP code that was included and it works from computers but not from mobile devices.
