### ISSUE TITLE
resumableUpload error handling

### ISSUE THREAD

**Issue by pigator** [kartik-v/bootstrap-fileinput#1678]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. set up plugin for resumable upload
2. sending echo json_encode([‘error’=> ‘ERROR’]) from server
3. 

## Expected behavior and actual behavior

When I follow those steps, I see...
* fileupload stops for the whole queue,
* next file in queue is not processed
* buttons disabled
* cannot add another file
* no error message in 'elErrorContainer'
* filechunkerror event is triggered

I was expecting...
* fileupload stops for the problem file
* next file in queue is processed
* buttons ENabled
* can add another file
* error message in 'elErrorContainer'
* filechunkerror event is triggered

## Environment

Browsers

- [ ] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.1.4

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

Hi!
I managed to set up resumable upload with the fileinput plugin.
But when I send an errormessage from the server back to the client, the plugin just “hangs”, upload progress is stopped (expected), but no error message pops up (elErrorContainer is set up).
My server code is (just for testing errors):

 header(‘Content-Type: application/json’); // set json response headers
//$outData = $this->douploadChunks(); // a function to upload the bootstrap-fileinput files
$outData = [‘error’=> ‘ERROR’]; // a function to upload the bootstrap-fileinput files
echo json_encode($outData); // return json data
exit();

The json data is sent back, filechunkerror is triggered, but the error alert does not show and all the plugin buttons are disabled.
Should I manually handle this error somehow?

**Comment by aminshoukat** [comment]
I am facing the same issue
did you find any solution yet?

**Comment by aminshoukat** [comment]
@kartik-v

**Comment by pigator** [comment]
No luck yet.
I tried combinations of:

        rm.setProcessed('error');
        delete rm.chunksProcessed[id];
        fm.setProcessed(id);
        fm.removeFile(id);
        rm.upload();

But just cannot get past the first file, after getting a `filechunkerror`. It would be so nice to have a function like `processNextFile`.

If it stays so, I'll just try:

https://github.com/blueimp/jQuery-File-Upload
or
https://www.plupload.com/

**Comment by aminshoukat** [comment]
I tried this and it is working for me 
![image](https://user-images.githubusercontent.com/47177827/108624278-d3458680-7465-11eb-92a0-e325c8612570.png)

**Comment by pigator** [comment]
Now I get the error showing up and the user interface is not disabled, but I'd like to have the upload queue to continue with the next file(s)

![bs-fileupload-20210221-01](https://user-images.githubusercontent.com/56750471/108625502-8eacf180-744b-11eb-9366-ce31dd6fc0b9.png)

How can I do this?

**Comment by kartik-v** [comment]
Folks - thanks for the report. Have been strapped with time to check this. I will check this as soon as I get time. Will try to see if a fix can be provided with this release.

**Comment by kartik-v** [comment]
Folks - thanks for the report. Have been strapped with time to check this. I will check this as soon as I get time. Will try to see if a fix can be provided with this release.  Appreciate / feel free to provide any programming inputs to resolve or a pull request if required.

**Comment by kartik-v** [comment]
Hi folks tried providing an interim fix. There is a new property `resumableUploadOptions.skipErrorsAndProceed` which is set to `true` by default - which should proceed to the next upload. Will need some exhaustive testing to confirm - but its pushed on the master. Do check and let know from your end.

**Comment by kartik-v** [comment]
Hi folks provided an interim fix. There is a new property `resumableUploadOptions.skipErrorsAndProceed` which is set to `true` by default - which should proceed to the next upload. Will need some exhaustive testing to confirm - but its pushed on the master. Do check and let know from your end.

**Comment by kartik-v** [comment]
Hi folks provided an interim fix. 

- There is a new property `resumableUploadOptions.skipErrorsAndProceed` which is set to `true` by default - which should proceed to the next upload. Will need some exhaustive testing to confirm - but its pushed on the master. Do check and let know from your end if this resolves?
- There is also a new event `filemaxretries` which is raised after the maximum upload retries failed validation.

**Comment by kartik-v** [comment]
Hi folks provided an interim fix. 

- There is a new property `resumableUploadOptions.skipErrorsAndProceed` which is set to `true` by default - which should proceed to the next upload. Will need some exhaustive testing to confirm - but its pushed on the master. Do check/test from your end and let know from your end if this resolves?
- There is also a new event `filemaxretries` which is raised after the maximum upload retries failed validation.

**Comment by kartik-v** [comment]
Hi folks provided an interim fix. 

- There is a new property `resumableUploadOptions.skipErrorsAndProceed` which is set to `false` by default. Set this to `true` to proceed to the next upload after max retries error. Will need some exhaustive testing to confirm - but its pushed on the master. Do check/test from your end and let know from your end if this resolves?
- There is also a new event `filemaxretries` which is raised after the maximum upload retries failed validation.
