### ISSUE TITLE
Safari: Not getting initialized at all

### ISSUE THREAD

**Issue by derblub** [kartik-v/bootstrap-fileinput#168]
Unfortunately, on the latest Safari version (v5.1.7) for Windows, the file-input doesn't get initialized and stays on the browser-styled file-input element.

No errors in the console, though.

**Comment by kartik-v** [comment]
Check [the pre-requisities for the plugin](http://plugins.krajee.com/file-input#pre-requisites).

Safari 5.1.7 does not support File API. [Check browser support here](http://caniuse.com/#feat=fileapi).

**Comment by kartik-v** [comment]
Check and read [the pre-requisities for the plugin](http://plugins.krajee.com/file-input#pre-requisites).

Safari 5.1.7 does not support File API. [Check browser support for HTML5 FileAPI here](http://caniuse.com/#feat=fileapi).

Plugin will automatically degrade the widget to a native file input - if file api support does not exist on the browser.

**Comment by derblub** [comment]
Guess that resolves the mystery. Thanks!

**Comment by tienhoangnguyen** [comment]
Hi Kartik!
My safari version is 5.1.4 and 5.1.7.
The file-input doesn't get initialized and stays on the browser-styled file-input element.
It is not like this image (on chrome)
![1](https://cloud.githubusercontent.com/assets/15793058/15098711/d126206e-156d-11e6-9e44-e96e9e7564d9.png)
How do I fix it on safari 5.14 and 5.1.7?
thanks

**Comment by kartik-v** [comment]
[Read my earlier comment](https://github.com/kartik-v/bootstrap-fileinput/issues/168#issuecomment-74498466).
