### ISSUE TITLE
zoomCache class

### ISSUE THREAD

**Issue by skafka** [kartik-v/bootstrap-fileinput#1682]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Use the image preview template
2. Try to upload single image using the arrow in the thumnail bottom

## Expected behavior and actual behavior

When I use image preview template as documented here: https://plugins.krajee.com/file-input/plugin-options#previewTemplates 
the Detail View is not displayed. I fixed it by including (undocumented) **{zoomCache}** in the template. BUT then single file upload arrow does not work. I found the generated code for zoomCache 

`<div class="file-preview-frame krajee-default kv-preview-thumb" ...`
As I see, the element should be
`<div class="file-preview-frame krajee-default kv-zoom-thumb" ...`
(**kv-zoom-thumb** class)

When I change it (replacing the class name in the source), the upload work well.

Please, is it possible

1. change the documentation
2. change the zoomCache class properly?

Thank you

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 5.1.4

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Docs are updated. Thanks.

**Comment by skafka** [comment]
I checked version 5.1.5 and the error remains here. The problem is that when I use e.g.

```
previewTemplates: {
  image: '<div class="file-preview-frame krajee-default kv-preview-thumb" id="{previewId}" data-fileindex="{fileindex}" data-fileid="{fileid}" data-template="{template}">\n' +
   '<div class="kv-file-content">' +
   '  <img src="{data}" class="kv-preview-data file-preview-image" title="{title}" alt="{caption}" {style}/>\n' +
   '</div>\n' +
   '<button class="text-save-btn"><i class="fas fa-save"></i></button><input class="fupload-input" name="{fileid}" value="{caption}"/>' +
   '{footer}{zoomCache}' +
   '</div>\n'
}
```
I must add **{zoomCache}** to see the preview correctly. 
But single file upload operation fails, because the generated code for thumbnail zoomCache looks like:
```
<div class="kv-zoom-cache">
  <div class="file-preview-frame krajee-default kv-preview-thumb file-preview-error" id="zoom-thumb-upfiles-62519_kometa.jpg" data-fileindex="-1" data-fileid="62519_kometa.jpg" data-template="image">
<div class="kv-file-content">  
   <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD.....
```
What is wrong is the **kv-preview-thumb** class here, I think. I made quick and dirty hack in fileinput.js on row 4097 (ver. 5.1.4)

```
if (zoom) {
  // quick hack
  tmplt = tmplt.replace('kv-preview-thumb', 'kv-zoom-thumb');
  css = css.replace(' ' + $h.SORT_CSS, '');
}
```

I have also similar problems with pdf previewTemplates etc...

Thank you for help
