### ISSUE TITLE
Corrupted previewTemplate styles from cspBuffer.stash 

### ISSUE THREAD

**Issue by adhayward** [kartik-v/bootstrap-fileinput#1683]
After upgrading from v5.0.7 (I've tested on 5.0.8 and 5.1.4) I started encountering issues where the style tags on my previewTemplates were being largely removed.
I traced this back to the [cspBuffer.stash function](https://github.com/kartik-v/bootstrap-fileinput/blob/8d415a72a75a46099226f5a267810934010af675/js/fileinput.js#L477) 

The current implementation isn't very forgiving of how the style is formatted and doesn't allow for data url's to be included (I sometimes set the uploaded file as a background-image to get it to fit to an aspect ratio)

I've created a jsfiddle example to show what I mean: [https://jsfiddle.net/fuzzyexponent/tagsf9eb/](https://jsfiddle.net/fuzzyexponent/tagsf9eb/)

It uses a cut down version of the stash function - just the part that parses the style string and outputted the array it produces.
For comparison, I've also included an alternative way of doing this base on [CSSStyleDeclaration's](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration) which produces the correct value without having to parse the string at all.

I believe changing the stash function to the following should fix this and make it more reliable:
`````
            stash: function (htmlString) {
                var self = this, outerDom = $.parseHTML('<div>' + htmlString + '</div>'), $el = $(outerDom);
                $el.find('[style]').each(function (key, elem) {
                    var $elem = $(elem), id = $h.uniqId(), styles = {}, styleDeclaration = $elem[0].style;
                    
                    if (styleDeclaration && styleDeclaration.length) {
                        $(styleDeclaration).each(function() {
                            styles[this] = styleDeclaration[this]
                        })
                        self.domElementsStyles[id] = styles;
                        $elem.removeAttr('style').attr(self.CSP_ATTRIB, id);
                    }
                });
                $el.filter('*').removeAttr('style');                   // make sure all style attr are removed
                var values = Object.values ? Object.values(outerDom) : Object.keys(outerDom).map(function (itm) {
                    return outerDom[itm];
                });
                return values.flatMap(function (elem) {
                    return elem.innerHTML;
                }).join('');
            }
`````

**Comment by kartik-v** [comment]
Updated. Thanks for the report.
