### ISSUE TITLE
Overriding previewFileIcon has no effect (other icons work)

### ISSUE THREAD

**Issue by ptijul** [kartik-v/bootstrap-fileinput#1684]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Override the previewFileIcon by something

My config (extract) :
`$('.file').fileinput({
                showRemove: true,
   		browseIcon: '<i class=\"flaticon-folder\"></i>',
        	cancelIcon: '<i class=\"flaticon-bin\"></i>',
        			previewFileIcon: '<i class=\"flaticon-up-arrow\"></i>', // At least with version 5.1.4 apparently this value has no effect
                    removeIcon: '<i class=\"flaticon-ban-circle-symbol\"></i>',
        			uploadIcon: '<i class=\"flaticon-up-arrow\"></i>',      			
                    uploadClass: 'btn btn-success',
                    maxFileCount: 1                
                });`
## Expected behavior and actual behavior

When I follow those steps, I see...
In the DOM I still see : `<i class="glyphicon glyphicon-file"></i>` so my config is simply ignored. 
Whereas all other options described in the documentation are easy to be overriden...but this one seems to have no impact

I was expecting...
...I can override this by my config

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.1.4 (latest)

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This has been checked and it works fine. It seems you read usage of `previewFileIcon` wrongly. Note that `previewFileIcon` is the icon shown within each thumbnail in place of the file content if you set `preferIconicPreview` to `true`.

If you wish to change the icon shown beside the main input text box beside the FILE NAME CAPTION - you need to set the `layoutTemplates.fileIcon` property.

**Comment by ptijul** [comment]
Thanks for your reply, you're right I used the wrong property. Now it works :)
