### ISSUE TITLE
Question About Resumable Upload

### ISSUE THREAD

**Issue by nomanaadma** [kartik-v/bootstrap-fileinput#1685]
When I enable resumable upload its uploading files one by one is it possible to make 3 files upload at a time?
Also there is no retry button when resumable upload is true

**Comment by nomanaadma** [comment]
@kartik-v

**Comment by kartik-v** [comment]
Yes you can upload multiple files for a resumable upload (if you have set the `multiple` attribute to `true` for your native file input). Note that for a resumable upload - there is an internal resumable engine in the plugin which handles/manages the QUEUE and upload (it will be a sequential first in first out).
