### ISSUE TITLE
File name loosing special character

### ISSUE THREAD

**Issue by GearTheWorld** [kartik-v/bootstrap-fileinput#1686]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.upload a file with filename like MyImage #1.jpg

## Expected behavior and actual behavior

When the UI shows the preview and the filename in the input field the # is replace with _ and a space
It should keep the filename in its integrality

When I follow those steps, I see...

File name changed from MyImage #1.jpg to MyImage _ 1.jpg

I was expecting...

MyImage #1.jpg

## Environment
ASP.NET MVC (Html 5)

Browsers

- [X] Microsoft Edge Canary
- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.4.1
- bootstrap-fileinput version: 4.5.3

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

Code :

```
$('#SendAttachmentText').html('<form><input id="SendAttachment" name="SendAttachment" type="file" class="file" enctype="multipart/form-data; charset=utf-8"></form>');
$('#SendAttachmentDialog').modal('show');
$("#SendAttachment").fileinput({
    uploadUrl: '/Company/AttachFile',
    uploadExtraData: { Key: CurrentUser.ServiceIdentity, Reference: CurrentExpense.Reference, PreviousAttachment: CurrentExpense.AttachmentLink },
    language: IsFrench ? 'fr' : '_LANG_'
});

```
Screenshot :

![image](https://user-images.githubusercontent.com/8614008/109172810-2b73d580-7751-11eb-8513-9b76367c47c8.png)

**Comment by kartik-v** [comment]
Duplicate to #1317 - [read this comment](https://github.com/kartik-v/bootstrap-fileinput/issues/1317#issuecomment-430969522) - if you want special characters in your file name - override the slugCallback property.

**Comment by GearTheWorld** [comment]
I wanted to say thank you, this plugin is incredible.  Very nice job!
