### ISSUE TITLE
Resumable upload error: fix displaying errors

### ISSUE THREAD

**Issue by pigator** [kartik-v/bootstrap-fileinput#1687]
When resumableUploadOptions.skipErrorsAndProceed was true and multiple errors could occur during resumable upload, errors were discarded (reset) and only the last error would be displayed.
It would be desirable if all errors would be displayed.
Like so:
![bs-fileupload-20210226-01](https://user-images.githubusercontent.com/56750471/109361175-ccb17780-7888-11eb-9bde-685ae903ce9d.png)

**Comment by kartik-v** [comment]
Refer updates in the PR #1688
