### ISSUE TITLE
Preview file of CSV shows icon i/o file preview since v5.1.2

### ISSUE THREAD

**Issue by ptijul** [kartik-v/bootstrap-fileinput#1689]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. With version 5.1.0 +5.1.1 : preview + zoomPreview both works. Sample [here](https://jsfiddle.net/pti_jul/pLhn2zrs/14/).
2. With version 5.1.2 : preview works but not zoomPreview. Sample [here](https://jsfiddle.net/pti_jul/pLhn2zrs/15/).
3. With version 5.1.3+5.1.4 : preview + zoomPreview both does NOT work. Sample [here](https://jsfiddle.net/pti_jul/pLhn2zrs/17/).

## Expected behavior and actual behavior

When I follow those steps, I see that depending on the version used I see (or not) the preview of my CSV file and I see (or not) the zoom preview (click on the preview after file has been selected).
Note that with image files it has no issue.

I was expecting that the plugin can still show preview of CSV file which can be useful.

I notice that in the DOM the structure has changed so it might be an expected change and may be the CSV preview file is not supported anymore which then it won't be an issue but more like a request to keep it back (if possible).

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: 5.1.0 + 5.1.1 + 5.1.2 + 5.1.3 + 5.1.4

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [X] I can reproduce this bug in (see links above)

**Comment by kartik-v** [comment]
This was purposely removed for default preview - because of issues in many windows or other Operating systems where MICROSOFT EXCEL is used as a default viewer for CSV files - it parses the mime type wrongly as `application/vnd.ms-excel` instead of CSV - which the browser then skips previewing and rather results in an ugly popup dialog asking to download / open the file in EXCEL. 

I recommend to read / preview CSV files - if they can be saved as `.TXT` extension (e.g. tab separated text) - it should work.

**Comment by ptijul** [comment]
Thanks @kartik-v for your detail explanation.
