### ISSUE TITLE
Set upload url after init

### ISSUE THREAD

**Issue by skysteve** [kartik-v/bootstrap-fileinput#169]
Is is possible to set the upload URL after the view has been initialised without loosing the current file?

e.g. What I'd like to do is the following:
1) View is created (at this point I don't know the upload url since the model has no id which is part of the url)
2) Model gets an ID by saving the new model
3) Server returns an id for the model
4) Set the upload URL on the file uploader (in this case an image)
5) Save the images to the new endpoint

I can call .fileinput('reset', {uploadUrl: '....'}) but that clears out the selected file.

Hopefully that makes sense :)

**Comment by kartik-v** [comment]
Not clear why you are doing all of the above (looks a bit complicated to me). 

- If you need to save the model first before trying the file upload you can do it in one single ajax call in your server code (pass these form inputs for your model in `pluginOptions['uploadExtraData']`). Check a [PHP example](http://webtips.krajee.com/ajax-based-file-uploads-using-fileinput-plugin/) - but you can use the same concept within Yii MVC method.
- if you need to isolate your upload and model attributes saving independently - then you can go ahead with your upload and save them on your server temporary folder using some session level IDs that you can transfer to your controller action that creates or saves the model. Then based on the model saving process to move the files to respective location or delete.

**Comment by skysteve** [comment]
Thanks for the quick reply :)

I think I've sorted it now, ended up using the extra data attribute, feel free to close :)

**Comment by yedyharova** [comment]
`$.prototype.fileinput.Constructor.prototype["setUploadUrl"] = function(url) {`
                	`this.uploadUrl = url;`
`}`

`$('#fileuploader').on('filepreajax', function(event, previewId, index) {`
`$('#fileuploader').fileinput("setUploadUrl", url);`
`}`
