### ISSUE TITLE
Hi sorry for bothering I'm using yii2 kartik FileInput when I set language property to for example 'en', 'es' it is showing that language messages but newly added language (uz-cyrl) don't working

### ISSUE THREAD

**Issue by safarmurodY** [kartik-v/bootstrap-fileinput#1691]
![uz-cyrl](https://user-images.githubusercontent.com/50994066/109803839-5bd0dd80-7c43-11eb-86be-ed2e37a9a7c2.jpg)
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see that 'language' property must be set like 'uz' , 'en' or 'es' 

I was expecting to use 'uz-cyrl' language from bootstrap-fileinput/js/locales/uz-cyrl.js but when i set language property to this widget showing english messages

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: v3.5.1
- bootstrap-fileinput version:bootstrap-fileinput v5.1.6

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins

**Comment by kartik-v** [comment]
Not directly related to the plugin repo but your usage of the Yii2 widget. This however seems an environment / code issue at your end where you may be having stale Yii2 web assets and browser cache impacting your configuration - which need to be cleared. For example, this works fine on Yii2 (check screen shot below). If you have issues related to Yii2 widget - please log it in the right repo. Thanks.

![image](https://user-images.githubusercontent.com/3592619/109810455-8f196980-7c4f-11eb-81e4-e602ecf93c4a.png)
