### ISSUE TITLE
nothing in $_FILES when blob added in empty fileinput ans uploaded

### ISSUE THREAD

**Issue by SamuelBenard** [kartik-v/bootstrap-fileinput#1692]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Create an empty fileinput  then add an image then upload the content.
```javascript
        $("#f_photo").fileinput({
          uploadAsync: false,
          uploadUrl: "https://mywebsite/uptest.php",
          enableResumableUpload: true,
          showPreview: false,
          showClose: false,
          showCaption: false,
          showUpload: true,
          maxFileCount: 1,
          autoReplace: true,
          allowedFileExtensions: ["jpg", "png", "gif"],
        });
        $('#f_photo').fileinput('addToStack', resp);
        $('#f_photo').fileinput('upload');
```
the 'resp' variable is a blob from another code part

This is what is posted , we can see the file and other posted values
```
-----------------------------220275716331574757053380566394
Content-Disposition: form-data; name="fileBlob"; filename=""
Content-Type: application/octet-stream
```
But vardump($_FILES) shows 
```
array(1) { 
    ["fileBlob"]=> array(5) { 
        ["name"]=> string(0) "" 
        ["type"]=> string(0) "" 
        ["tmp_name"]=> string(0) "" 
        ["error"]=> int(4) 
        ["size"]=> int(0) 
    } 
} 
```
the posted data are not in $_FILES, everything is in $_POST

## Expected behavior and actual behavior

When I follow those steps, I get empty values in $_FILES
I was expecting correct values in $_FILES

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

Jquery 3.6.0
FileInput 5.1.4

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/)
http://jsbin.com/sugebuteda/edit?html,js,output

**Comment by kartik-v** [comment]
Yes ... this is something expected with browser - web data passing. You can only read files uploaded from client browser via $_FILES on server... any other data you passed via custom javascript can only be read via $_POST
