### ISSUE TITLE
Missing individual remove button

### ISSUE THREAD

**Issue by meduzapat** [kartik-v/bootstrap-fileinput#1696]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
POST only, not using ajax. using fas theme due to the missing icons.
1. create a file input on an html following the examples:
	```<input
	id="otherPic"
	name="otherPic[]"
	type="file"
	multiple="multiple"
	class="file"
	data-theme="fas"
	data-show-delete="true"
	data-show-upload="false"
	data-show-remove="false"
 	data-upload-stats ="false"
>```
2. open the code
3. you will see that the individual remove is not present, also the upload preview is not remove.

## Expected behavior and actual behavior

The remove button is on every preview
The upload status is not displayed.

Also, where I can find the list of data-xxx options?
## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: v3.5.1
- bootstrap-fileinput version: 5.1.5

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Individual remove button is only available when you use ajax mode or for files in initial preview.

As far as using `data-` attributes its a standard part of jquery documentation. Refer [plugin options](https://plugins.krajee.com/file-input/plugin-options). All of these can be passed as data attributes but using the right case.

- For example the plugin option `language` can be passed as data attribute `data-language`
- But the plugin option `showUpload` should be passed as data attribute `data-show-upload`  (notice the case of the plugin option attribute where the hyphens will be replaced in data attributes)

Note that using data attributes will work only for simple cases. Advanced cases where the plugin option is a function or object - may not be so easy/possible. Recommend in that case to use the plugin initialization via javascript.
