### ISSUE TITLE
Files from the first selection being removed after the second file selection

### ISSUE THREAD

**Issue by pericles-salmazzi** [kartik-v/bootstrap-fileinput#1697]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Environment

Browsers

- [x ] Google Chrome
- [x ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x ] Windows
- [ ] Mac OS X
- [ x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

I have a problem or bug or I did not know how to configure the plugin correctly.
When selecting files a second time, all files selected the first time are removed from the selection.
If I define uploadUrl: "#" the files are not removed from the selection after the second selection,
however when uploading via POST AJAX only the last file I selected is uploaded and all the others in the list are not.

I am using laravel framework but the upload is done through a post AJAX request

My settings:

$("#arquivosexplorer").fileinput({
theme: 'explorer-fas',
language: 'pt-BR',
allowedFileExtensions: extensoesPermitidas, // Formato array: ['jpg', 'png', 'jpeg', 'pdf'],
maxFileSize: tamanhoMaximo, // em KiloBytes
maxFileCount: quantidadeMaxima,
maxFileNum: quantidadeMaxima,
minFileNum: 1,
required: true,
showUpload: false,
preferIconicPreview: true, // this will force thumbnails to display icons for following file extensions
previewFileIconSettings:
{
'txt' : '',
'xml' : '',
'doc' : '',
'docx': '',
'csv' : '',
'xls' : '',
'xlsx': '',
'ppt' : '',
'pdf' : '',
'zip' : '',
'htm' : '',
'mov' : '',
'mp3' : '',
'jpg' : '',
'jpeg': '',
'gif' : '',
'png' : '',
'bmp' : ''
},
layoutTemplates: {
main1: "{preview}\n" +
"<div class="\'input-group" {class}\'="">\n" +
" <div class="\'input-group-btn\" input-group-prepend'="">\n" +
" {browse}\n" +
" {upload}\n" +
" {remove}\n" +
" </div>\n" +
" {caption}\n" +
"</div>"
}
});

**Comment by pericles-salmazzi** [comment]
Another problem encountered was that when clicking remove a file from the list, all the others are deleted. I am using version 5.1.6 of the plugin.

**Comment by anandphulwani** [comment]
This is the expected behavior

The below code works, try to work yourself around it.
```
            $(element).fileinput({
                theme: "fa",
                allowedFileExtensions: ['jpg', 'jpeg', 'png', 'gif'],
                allowedPreviewTypes: ['image'],
                maxFileSize: 5120,
                maxFileCount: 5,
                minFileCount: 1,
                fileActionSettings: {
                    showUpload: false,
                },
                browseOnZoneClick: true,
                overwriteInitial: false,
                autoReplace: false,
                autoOrientImage: true,
                showCancel: false,
                showUpload: false,
                showRemove: false,

                initialPreview: initialPreviewVar,
                initialPreviewConfig: initialPreviewConfigVar,

                uploadUrl: "/controllerX/file-store",
                uploadExtraData: function() {
                    return {
                        _token: $("input[name='_token']").val(),
                    };
                },
                uploadAsync: true, // Upload using Ajax
                deleteUrl: "/controllerX/file-delete",
                deleteExtraData: function() {
                    return {
                        _token: $("input[name='_token']").val(),
                    };
                },
                purifyHtml: true,
            })
```

**Comment by pericles-salmazzi** [comment]
Are you sure that Bootstrap file input krajee should work this way?

Should the second selection of files replace all selected files the first time?

Is it not possible to "join" the files of the first with the second selection?

**Comment by anandphulwani** [comment]
> 
> 
> Are you sure that Bootstrap file input krajee should work this way?
> 
> Should the second selection of files replace all selected files the first time?
> 
> Is it not possible to "join" the files of the first with the second selection?

As per my understanding, kartik has mentioned here
https://github.com/kartik-v/bootstrap-fileinput/issues/53#issuecomment-63483310
that  ``"Its done for a logical reason to mimic the HTML file input functionality"`` and
``"Its the inherent behavior of the HTML native file input which automatically clears the files selected whenever you click the input and cancel the file dialog."``

Although i am not sure, do explore the docs more, as far as i remember its mentioned somewhere in the docs, look for ``overwriteInitial`` as well.

I would suggest you to try the `uploadAjax` fundamental, it is much better, it allows secondary selection, i am using the same in a laravel project.

**Comment by kartik-v** [comment]
@pericles-salmazzi .... I see that you are using an ajax mode of submission with uploadUrl... So the file input should allow appending files selected each time until you have clicked upload. The comment that @anandphulwani has shared is more for native form based submission  without ajax and without uploadUrl set. 

If you do not want plugin 5o overwrite any initial preview files then you set overwriteInitial to false.

**Comment by anandphulwani** [comment]
> 
> 
> @pericles-salmazzi .... I see that you are using an ajax mode of submission with uploadUrl... So the file input should allow appending files selected each time until you have clicked upload. The comment that @anandphulwani has shared is more for native form based submission without ajax and without uploadUrl set. Just ensure that your laravel server code reads the files via uploadUrl action and not via form submit action.
> 
> If you do not want the plugin to overwrite any initial preview files then you can set overwriteInitial to false.

@kartik-v His settings doesn't include ``uploadUrl``, request to review his settings mentioned in his first post once again.

**Comment by kartik-v** [comment]
Yes true... I had checked the second code snippet with uploadUrl posted by you. Without uploadUrl the plugin functionality will be limited to a native HTML file input. Refer the plugin usage modes in docs for comparison.
