### ISSUE TITLE
Tab order is broken

### ISSUE THREAD

**Issue by anandphulwani** [kartik-v/bootstrap-fileinput#1698]
Tab order gets stuck at input box and doesn't move forward on pressing tab, attached codepen link below to check.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a form with some components which contains a file-input component as one of them.
2. Starting from the first component, use keyboard to focus around the components, by pressing tab.
3. The tab order will get stuck on the file-input component.

## Expected behavior and actual behavior

When I follow those steps, I see the focus stuck on "Select files ..." input box and pressing tab doesn't work.
I was expecting it to move forward to the remaining components in the form.

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [x] Microsoft Edge (Chromium Updated)
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 5.1.5

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a codepen](https://codepen.io/anandphulwani/pen/jOybKJZ)

**Comment by kartik-v** [comment]
Fixed and enhancements added via the commit.

- (enh #1698): Tab index ordering enhancements.
  - fix tab order breaking after file caption highlight 
  - added new property `tabIndexConfig` for configuration of tab indices for each section 
    which defaults to (null value means no tabindex property will be set for that section) 
~~~
    tabIndexConfig: {
        caption: 500,
        browse: 500,
        remove: 500,
        upload: 500,
        cancel: null,
        pause: null,
        modal: -1
    }
~~~
