### ISSUE TITLE
Unable to upload large files/videos

### ISSUE THREAD

**Issue by atroxmavenia** [kartik-v/bootstrap-fileinput#170]
I'm trying to upload a 24MB mp4 through this and am getting an empty $_POST array when I do. Images work fine in every way I've tested. I have maxFileSize set to 0, allowedFileExtensions includes mp4.

**Comment by kartik-v** [comment]
Either its an issue with your web server OR It maybe a client specific memory issue. For the client specific issue - you may try setting `showPreview` to `false` if you wish to use for uploading large files... (you will not be able to preview files on client and save a bit of client processing memory)

**Comment by nikhilbhanda** [comment]
Hi Kartik, I am trying to upload 50MB file and uploading progress bar stuck on 1 percent also it is not taking ".kar" and ".vid" files, I have aaded those files on allowed extension. showPreview is also set to false
but still no luck till now, Please help
Below is config:
 $("#input-700").fileinput({
            uploadUrl: siteroot + "Track/UploadTrackwithRewource", // server upload action
            uploadAsync: true,
            showUpload: false,
            maxFileCount: 1,
            autoReplace: true,
            showPreview :false,
            maxFileSize: 0
});
![capture](https://cloud.githubusercontent.com/assets/20472661/16868670/9a3bce7e-4a96-11e6-894c-d361087db615.JPG)

**Comment by blueprinted** [comment]
@atroxmavenia set php.ini 
post_max_size = 64M
upload_max_filesize = 64M
solve.

**Comment by nathanburgess** [comment]
@blueprinted Not solved. That wasn't the issue.
