### ISSUE TITLE
Race condition (maybe) when deleting file after file name verification in fileloaded event

### ISSUE THREAD

**Issue by rkuerbitz** [kartik-v/bootstrap-fileinput#1700]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Before actually uploading a file, I use the fileloaded event to send a AJAX request to my server to check the validity of the file names. When a filename is determinded in valid, I display a message and I use
`document.getElementById(prebiewID).getElementsByClassName("kv-file-remove")[0].dispatchEvent(new Event('click'));`
to remove the file.
2. However, sometimes (many large files) this causes trouble in some fileinput internal code: at some point within the event chain, file end up as being undefined. This is the call stack:

```
_Uncaught TypeError: file is undefined
    getFileRelativePath https://b97.planserver.pro/Scripts/fileinput.js:100
    getFileId https://b97.planserver.pro/Scripts/fileinput.js:104
    _getFileId https://b97.planserver.pro/Scripts/fileinput.js:4388
    readFile https://b97.planserver.pro/Scripts/fileinput.js:5220
    processFileLoaded https://b97.planserver.pro/Scripts/fileinput.js:5235
    setTimeout handler*processFileLoaded https://b97.planserver.pro/Scripts/fileinput.js:5232
    onload https://b97.planserver.pro/Scripts/fileinput.js:5416
    readFile https://b97.planserver.pro/Scripts/fileinput.js:5351
    processFileLoaded https://b97.planserver.pro/Scripts/fileinput.js:5235
    setTimeout handler*processFileLoaded https://b97.planserver.pro/Scripts/fileinput.js:5232
    onload https://b97.planserver.pro/Scripts/fileinput.js:5416
    readFile https://b97.planserver.pro/Scripts/fileinput.js:5351
    readFiles https://b97.planserver.pro/Scripts/fileinput.js:5445
    _change https://b97.planserver.pro/Scripts/fileinput.js:5050
    jQuery 9
    _handler https://b97.planserver.pro/Scripts/fileinput.js:2188
    _listen https://b97.planserver.pro/Scripts/fileinput.js:2486
    FileInput https://b97.planserver.pro/Scripts/fileinput.js:743
    fileinput https://b97.planserver.pro/Scripts/fileinput.js:5781
    jQuery 2
    fileinput https://b97.planserver.pro/Scripts/fileinput.js:5769_
```

## Expected behavior and actual behavior

Is there any supported method to safely remove a file from the preview list of files for upload other than using the dispatchEvent method? Any help would be appreciated.

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 
- bootstrap-fileinput version: 5.1.5

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Try using a setTimeout and with a simpler jquery --- something like this:

```js
$('#input').on('fileloaded', function() {
    setTimeout(function() {
        $('#previewId .kv-file-remove').trigger('click');
    }, 500);
});
```
