### ISSUE TITLE
About Bootstrap 5 Stable Release

### ISSUE THREAD

**Issue by arafsan** [kartik-v/bootstrap-fileinput#1703]
Greetings, As of May 5th, Bootstrap 5 stable version has been officially announced. Will you have a plan for this release?

**Comment by kartik-v** [comment]
Yes the plugin supports bootstrap 5.x as of the latest release yesterday 5.2.0. This is mentioned in this [enhancment request](https://github.com/kartik-v/bootstrap-fileinput/issues/1674#issuecomment-833576795).
