### ISSUE TITLE
CDN Down

### ISSUE THREAD

**Issue by JohnJVTK** [kartik-v/bootstrap-fileinput#1704]
Hello,

It looks like the links you provided for the 5.2.0 version throw a 404 error.
[https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.2.0/css/fileinput.min.css](url)
Same for JS files.

Thanks
John

**Comment by kartik-v** [comment]
Hi the CDJNS library is supposed to auto sync after a new release... it should happen automatically. Give it a day or two.

**Comment by kartik-v** [comment]
CDN is changed and fixed to use a more correct updated source.
