### ISSUE TITLE
possible bug in isEmpty helper function

### ISSUE THREAD

**Issue by selamar** [kartik-v/bootstrap-fileinput#1707]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. define in your HTML a <input ...... multiple /> element
2. put a breakpoint at the _change() function definition just after the var declaration
3. drag and drop a file in the drop zone
4. in the debugger examine the value of isSingleUpl variable

## Expected behavior and actual behavior

When I follow those steps, I see the value of isSingleUpl variable to be *undefined*

I was expecting it to be *false*

It turns out the isEmpty() helper function expects a 2nd parameter 'trim' that defaults to undefined and that causes the result of the function to be *undefined*. As a consequence in the console:

$h.isEmpty('')  returns true, but
$h.isEmpty('multiple') returns undefined instead of false.

I can't say if this can cause malfunctioning in the plugin but being the isEmpty function heavily used I thought maybe it could be useful resolve this issue.

## Environment

Browsers

- [x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: 5.1.3 but checked in the master branch that the function definition is just the same

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Thanks - yes the `isEmpty` helper works as intended. It is supposed to do one of the empty checks and returns `true` if empty else either `undefined` or `false`. It can be enhanced though to return a boolean value always - but it should not impact the logic of its use anyway.

**Comment by selamar** [comment]
Ok, thank you for your reply.
