### ISSUE TITLE
update same file error issue

### ISSUE THREAD

**Issue by confettidc** [kartik-v/bootstrap-fileinput#1708]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. define bootstrap file input with below config:
`
if (fhash.max_file_count == 1) {
		var filename = fhash.hidden_input_ele.val();
	//console.log("loadFileInput filename: " + filename);

	var files = [];
	files.push(filename);
} else {
	var files = JSON.parse(fhash.hidden_input_ele.val());
}

var file_input_initials = getFileUploadInitials(fhash.folder, fhash.fieldname, files);

var file_input_options = {
	language: 'en',
	theme: 'fa',
	showUpload : false,
	showBrowse: false,
	showCaption: false,
	showClose: false,
	showRemove: false,
	showDrag: false,
	downloadIcon: '<i class="icon-download"></i>',
	removeIcon: '<i class="icon-trash-empty"></i>',
	zoomIcon: '<i class="icon-zoom-in"></i>',
	allowedFileTypes: ['image'],
	allowedFileExtensions: ['jpg', 'gif', 'png'],
	maxFileSize: 2 * 1024, // in KB
	maxFileCount: fhash.max_file_count,
	browseOnZoneClick: true,
	uploadUrl: '/admin/file-uploads/template-file-input-upload',
	uploadAsync: true,
	deleteUrl: '/admin/file-uploads/template-file-input-delete',
	showUpload: false, // hide upload button
	resizeImage: true,
	maxImageWidth: fhash.max_image_width,
	maxImageHeight: fhash.max_image_height,
	validateInitialCount: true,
    overwriteInitial: false,
    initialPreviewAsData: true,
    initialPreview: file_input_initials.preview,
    initialPreviewConfig: file_input_initials.preview_config,
    uploadExtraData: {
    	'_csrfToken': '0M/UVCNSFARB2qSHFTPyyK8sfDNuQrwsyDXK/ZeLp4EegccJQ4mgibbkXxaZGptdJUbrC1HrHtjXjla4FoO8bHYqYL0x+2qiyRVOBF5xjk2qUf/E87mfs3q29j907JG+g9ZvdfgvqDxEc9I+Ztkn4A==',
    	folder: fhash.folder,
    	fieldname: fhash.fieldname
    },
    deleteExtraData: {
    	'_csrfToken': '0M/UVCNSFARB2qSHFTPyyK8sfDNuQrwsyDXK/ZeLp4EegccJQ4mgibbkXxaZGptdJUbrC1HrHtjXjla4FoO8bHYqYL0x+2qiyRVOBF5xjk2qUf/E87mfs3q29j907JG+g9ZvdfgvqDxEc9I+Ztkn4A==',
    	folder: fhash.folder,
    	fieldname: fhash.fieldname,
    	funnel_id: '60b4bb5a010a764f9c5b0f69'
    }
};
console.log(file_input_options);

var $file_el = fhash.input_ele.fileinput(file_input_options).on("filebatchselected", function(event, files) {
	$file_el.fileinput('upload');
}).on("fileuploaded", function(e, params) {
	var uploaded_filename = params.response.initialPreviewConfig[0].key;

	if (fhash.max_file_count == 1) {
		// single file
		fhash.hidden_input_ele.val(uploaded_filename);
	} else {
		console.log(fhash.hidden_input_ele.val());
		var files = JSON.parse(fhash.hidden_input_ele.val());
		if (!files) {
			files = [uploaded_filename];
		} else {
			files.push(uploaded_filename);	
		}
		fhash.hidden_input_ele.val(JSON.stringify(files));
	}
}).on('filedeleted', function(event, key, jqXHR, data) {
	// console.log(data);
	// console.log(key);
	if (fhash.max_file_count == 1) {
		// single file
		fhash.hidden_input_ele.val('');
	} else {
		var files = JSON.parse(fhash.hidden_input_ele.val());
		var file_index = files.indexOf(key);
		files.splice(file_index, 1);
		fhash.hidden_input_ele.val(JSON.stringify(files));
	}
});

$file_el.on("filepredelete", function(jqXHR) {
    var abort = true;

    if (confirm("你確定要刪除這張圖片嗎? Are you sure you want to delete this image?")) {
        abort = false;
    }
    return abort; // you can also send any data/object that you can receive on `filecustomerror` event
});

`

## Expected behavior and actual behavior

When I follow those steps, I see bootstrap fileinput failed to upload file to server when same file is uploaded after deletion

I was expecting bootstrap input can upload file to server even same file is uploaded after deletion

See below:

https://user-images.githubusercontent.com/5524183/120260837-41051800-c2c9-11eb-84f7-7db0975377f8.mp4

## Environment

Browsers

- [x ] Google Chrome
- [ x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.4.1
- bootstrap-fileinput version: 5.2.1

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by confettidc** [comment]
Hi,

Similar problem occurred in demo, please help check, thanks.


https://user-images.githubusercontent.com/5524183/120584591-d7207600-c462-11eb-9e55-07f1bd753895.mp4

**Comment by kartik-v** [comment]
Fixed via latest commit.

**Comment by kartik-v** [comment]
Fixed via latest commit.
