### ISSUE TITLE
Custom preview for large files

### ISSUE THREAD

**Issue by leader-pro** [kartik-v/bootstrap-fileinput#1711]
I am trying to upload large file but it take a while.

My options:
```
showPreview : true
previewFileIcon : "<i class='fa fa-file'></i>"
preferIconPreview: true
```

My question is why your library need to process file when enabling preview when I am setting preview file icon to custom icon, how can I preview custom icon for any type of file even if it is a large file.

**Comment by kartik-v** [comment]
To avoid plugin to process file for preview - set at least one or more of the following to control which files should be processed for preview:

- [allowedPreviewTypes](https://plugins.krajee.com/file-input/plugin-options#allowedPreviewTypes)
- [allowedPreviewMimeTypes](https://plugins.krajee.com/file-input/plugin-options#allowedPreviewMimeTypes)
- [disabledPreviewTypes](https://plugins.krajee.com/file-input/plugin-options#disabledPreviewTypes)
- [disabledPreviewMimeTypes](https://plugins.krajee.com/file-input/plugin-options#disabledPreviewMimeTypes)

In addition, you can cross check the iconic preview section of [file input preview management demo](https://plugins.krajee.com/file-preview-management-demo#preview-iconic) to see advanced configuration of files processed for preview.

**Comment by leader-pro** [comment]
Hello,
Suppose I need to upload a large video file .avi and I want to display a custom icon, how can I avoid plugin to process the file and instead preview it with the custom icon only ?
for example:
```
 previewFileIconSettings: { // configure your icon file extensions
        'avi': '<i class="fa fa-video-camera text-primary"></i>',
 }

```

I think the options in your answer does not solve the problem because I want the file to be displayed in preview area but skip only processing it.

**Comment by leader-pro** [comment]
Is there a way to skip processing all files with keeping preview enabled with default icon ?

**Comment by kartik-v** [comment]
For achieving your use case, as mentioned in the documentation, you can just set [allowedPreviewTypes](https://plugins.krajee.com/file-input/plugin-options#allowedPreviewTypes) to `false` or `null` so that no files will be processed for preview.

**Comment by leader-pro** [comment]
I put set allowedPreviewTypes to false but still processing file !!

**Comment by kartik-v** [comment]
Please share a jsFiddle to understand your issue.

**Comment by leader-pro** [comment]
I am using yii2-widget-fileinput:

```
FileInput::widget([
        'name' => 'test',
        'options' => [
            'multiple' => true,
        ],
		'pluginOptions' => [
			'allowedPreviewTypes' => false,
			'previewFileIcon' => '<i class="glyphicon glyphicon-file"></i>',
			'preferIconicPreview' => true,
			'previewFileIconSettings' => [
				'avi' => '<i class="glyphicon glyphicon-camera"></i>',
			],
		]
    ]);
```

**Comment by leader-pro** [comment]
@kartik-v , is there any solution for the problem?

**Comment by leader-pro** [comment]
> Please share a jsFiddle or example to understand your issue.

I share an example please get me a solution for the issue

**Comment by kartik-v** [comment]
Hi - I can see it works as intended - what is the issue you are facing? When you set allowedPreviewTypes to false ... no preview is shown in thumbnails --- just the file icon is shown?

**Comment by leader-pro** [comment]
> Hi - I can see it works as intended - what is the issue you are facing? When you set allowedPreviewTypes to false ... no preview is shown in thumbnails --- just the file icon is shown?

Yes, just the file icon is shown but the problem is that the plugin takes a while to display the icon if the file is large. so I want to disable processing file.

I need to disable file processing and instead display icon quickly.

**Comment by kartik-v** [comment]
Let me check and see if there can be an option to do that... reopening this.

**Comment by kartik-v** [comment]
I just cross checked that there is no processing done for files additionally except the other basic validations when you have set `allowedPreviewTypes` to `false`. The `filereader` is called for content based parsing and rendering only if the file is configured to be allowed for preview processing via `allowedPreviewTypes`. 

To test this - I did two things:
- Native HTML file input
- Bootstrap File Input with `allowedPreviewTypes` set to `false`

Most files in 50+MB work instantly. I tried then selecting very large files e.g. 2+GB file. There is a bit of lag (browser loading it into memory) --- In both cases the time taken is similar - depending on your client memory used by the browser. So I do not think this is an issue with the plugin. Feel free to post your updates. 

To test in Yii2 using a native HTML file input you can use following and cross check the times.

```php
echo \yii\helpers\Html::fileInput('test_1', '', ['multiple' => true]);
```

**Comment by kartik-v** [comment]
The other thing I found is --- selecting via the browser BROWSE dialog for very large files takes a couple of seconds or more... but if you DRAG and DROP its instant.

**Comment by leader-pro** [comment]
> The other thing I found is --- selecting via the browser BROWSE dialog for very large files takes a couple of seconds or more... but if you DRAG and DROP the same file then it is selected instantly. Probably something to do with scanning/anti-malware checks on the client itself.

I am trying to upload 2 video files (using chrome browser):
 

1. extension: avi, size: 18mb
2. extension: wmv, size: 25mb

I am using the both ways  (Drag and Drop - Browse file), and in the both the browser take about 30 seconds to display file icon and the plugin display a percentage number to determine the progress of processing.

I think the plugin always tries to read file before display the corresponding file icon.

Please help me to solve the problem.

**Comment by kartik-v** [comment]
@leader-pro  -- as mentioned earlier I have checked it works fine within the plugin as intended . Did you check comparing the results with a HTML native file input. I have tested it across sizes and it works exactly same with a native file input as well as within this plugin with `allowedPreviewTypes` set to `false`.

**Comment by leader-pro** [comment]
> @leader-pro -- as mentioned earlier I have checked and tested that it works fine within the plugin as intended . Did you check comparing the results by testing also with a HTML native file input? I have tested it across sizes and it works exactly same with a native file input as well as within this plugin with `allowedPreviewTypes` set to `false`. You may need to check what is different in your client and browser settings as well.

I am trying to put the widget alone without any additions, if I set `showPreview` to `false` the plugin displays the file name quickly in the caption, but when I set it again to `true`  the plugin takes about 30 seconds to process the file and the browser displays a message **'page unresponsive'**. I am trying the plugin on another PC with different project I found the same result.

**Comment by leader-pro** [comment]
If you want I will send you a video file to show the problem

**Comment by kartik-v** [comment]
Do the test and comparison versus a native HTML input as mentioned earlier? I have tested for 100 mb to 2000 MB files on chrome and other browsers... It behaves same and very quick for lower size and some seconds for 2000MB files...

**Comment by leader-pro** [comment]
> Did you do the test and comparison versus a native HTML input without the plugin as mentioned earlier? I have tested for 100 mb to 2000 MB files on chrome and other browsers... It behaves same and very quick for lower size files and takes some seconds for 2000MB files... Again tested this without the plugin itself and behavior is same

Yes I am testing it with native html input and I told you that the size of avi file is about 25mb.
Did you see my previous reply about file extension. I test the plugin with mp4 file no problem but with avi file wait a lot of seconds. and the mp4 is larger than avi file.

**Comment by leader-pro** [comment]
With native html input there is no problem but only the problem with your plugin when showPreview is enabled.

**Comment by kartik-v** [comment]
Hi I am not able to reproduce the problem with AVI files as well. However I see that in your plugin configuration you have the following lines which maybe causing AVI files to be parsed and read.
```js
'previewFileIconSettings' => [
    'avi' => '<i class="glyphicon glyphicon-camera"></i>',
], 
```
Please remove the above lines and let know.

For example check with below code:
```php
echo FileInput::widget([
    'name' => 'test',
    'options' => [
        'multiple' => true,
    ],
    'pluginOptions' => [
        'allowedPreviewTypes' => false,
        'previewFileIcon' => '<i class="glyphicon glyphicon-file"></i>'
    ]
]);
```

**Comment by leader-pro** [comment]
> Hi I am not able to reproduce the problem with AVI files as well. However I see that in your plugin configuration you have the following lines which maybe causing AVI files to be parsed and read.
> 
> ```js
> 'previewFileIconSettings' => [
>     'avi' => '<i class="glyphicon glyphicon-camera"></i>',
> ], 
> ```
> 
> Please remove the above lines and let know.
> 
> For example check with below code:
> 
> ```
> echo FileInput::widget([
>     'name' => 'test',
>     'options' => [
>         'multiple' => true,
>     ],
>     'pluginOptions' => [
>         'allowedPreviewTypes' => false,
>         'previewFileIcon' => '<i class="glyphicon glyphicon-file"></i>'
>     ]
> ]);
> ```

Same problem!

**Comment by leader-pro** [comment]
You can download avi file for test from [here ](https://file-examples.com/index.php/sample-video-files/sample-avi-files-download/)
