### ISSUE TITLE
Paste Clipboard Image to File Input

### ISSUE THREAD

**Issue by kikonen** [kartik-v/bootstrap-fileinput#1713]
Q: What about supporting paste of clipboard Image to file Input?

Aka.
https://stackoverflow.com/questions/50427513/html-paste-clipboard-image-to-file-input

**Comment by kartik-v** [comment]
Enhancements added to allow pasting of files from clipboard. Allows you to select the file caption section of the widget and paste your files (or images from clipboard). New plugin method `paste` also has been added.

**Comment by kikonen** [comment]
*very* much thank you for this
