### ISSUE TITLE
Possibility to select the same file twice with Ajax Upload

### ISSUE THREAD

**Issue by NilsHuhta** [kartik-v/bootstrap-fileinput#1717]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [-] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Setup bootstrap-fileinput to work with Ajax Uploads (uploadUrl) 
2. Select one (or several) files
3. Reload page, after sending files or not, it doesn't matter, then files from previous visit can't be selected (they flashes and are then removed from preview list)

## Expected behavior and actual behavior

When I follow those steps, I see...

Files are removed from preview list

I was expecting...

when revisiting page, i was expecting to be able to upload same files again 

I have fixed the problem (by some Javascript debugging, and found that on row 5258 the if statement are like this

if (self.isAjaxUpload) {
      self._raise('filebatchselected', [fm.stack]);
     **if (fm.count() === 0 && !self.isError) {**
                             self.reset();
     }
} else {
                        self._raise('filebatchselected', [files]);
}

But if i comment out the if statement i get what i want, and i'm able to select and upload same file again
Maybe the statement is not correct, i think maybe the self reset would be needed when error or something else is wrong, not it resets if no error and no files....

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer
- [X] Safari

Operating System

- [X] Windows
- [X] Mac OS X
- [] Linux
- [] Mobile

Libraries

- jQuery version: 3.6
- bootstrap-fileinput version: 5.0

## Isolating the problem

- [-] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [-] I can reproduce this bug in [a jsbin](https://jsbin.com/)

![Skärmavbild 2021-06-15 kl  17 40 30](https://user-images.githubusercontent.com/57982203/122083191-ec04ee00-ce00-11eb-95b9-07a5d1fcf540.png)

**Comment by NilsHuhta** [comment]
[](url)

**Comment by kartik-v** [comment]
If page is reloaded... It is expected that the fileinput would be reset. To achieve your specific case you would need to use cache or similar in your app code to store file data and populate cached data back after page reloaded and file input is reinitialized.

**Comment by kartik-v** [comment]
I understand you want to upload the same file twice. The duplicate file checking in the plugin is done based on the File ID Generation logic which uses combination of file name and file size to generate an unique id. If both match the file is treated duplicate. You can override this behavior by overriding the setting [`generateFileId`](https://plugins.krajee.com/file-input/plugin-options#generateFileId) - this is a callback and you can append the timestamp or some random unique characters to ensure the same file can be selected multiple times. However note that you may face subsequent issues in plugin detecting the unique file in certain scenarios (like image resizing or resumable uploads) during the course of uploads.

**Comment by NilsHuhta** [comment]
OK, thanks for your reply, but still, if I reload the page after selecting a file and then reload it (before uploading it), 
say the user forgets to press start transfer, or simply do some sort of navigation error, then that file can not be selected (or it can be selected, but deleted because of that about the if statement, i select file in a empty upload page,  the user is confused not to be able to send that file ... but I try to use **generateFileId**. 

ps, it is not consistent, because sometimes you can select the same file again, sometimes not, usually you can choose if you wait 10 seconds after reload, but as I said it is not always true either ... Give it a try, i think you will se the problem....

But anyway, thanks for a super plugin, this is the first time I need to write something about it, so I'm extremely happy with it!

**Comment by NilsHuhta** [comment]
Hmm, i tried the  generateFileId , between each reload of simple upload html i changed the number (in id generation) first time _1 second time _2 (worked first time and second time, then _3 (third time) there "self.reset" kicked in, and the file didn't show up as selected in previewList.... 

my override function (just for test and manual change the number, if it would work, i wold add seconds since 1970 to instead of the number, but for test this was enough)

$("#input-b5").fileinput({
			theme: "fas",
			language: 'sv',
			uploadUrl: 'http://localhost:8080/openstore_web/OpenstoreAPI?username=nisse&passwd=nisse&action=ADD_IMAGE&timestamp=12',
			showCaption: true,
			dropZoneEnabled: true,
			generateFileId:function (file) {
							if (!file) {
									alert('file is null');
									return null;
							}
							var relativePath = String(file.relativePath || file.webkitRelativePath || null);
							if (!relativePath) {
									alert('relativePath is null');
									return null;
							}
							var fileid = file.size + **'_3'** + encodeURIComponent(relativePath).replace(/%/g, '_');
							alert(fileid)
							return (fileid);
					}
			});

**Comment by NilsHuhta** [comment]
Hmm, i tried the generateFileId , between each reload of simple upload html i changed the number (in id generation) first time _1 second time _2 (worked first time and second time, then _3 (third time) there "self.reset" kicked in, and the file didn't show up as selected in previewList....

my override function (just for test and manual change the number, if it would work, i wold add seconds since 1970 to instead of the number, but for test this was enough)

$("#input-b5").fileinput({
			theme: "fas",
			language: 'sv',
			uploadUrl: 'http://localhost:8080/myserverAPI?username=nisse&passwd=nisse&action=ADD_IMAGE',
			showCaption: true,
			dropZoneEnabled: true,
			generateFileId:function (file) {
							if (!file) {
									alert('file is null');
									return null;
							}
							var relativePath = String(file.relativePath || file.webkitRelativePath || null);
							if (!relativePath) {
									alert('relativePath is null');
									return null;
							}
							var fileid = file.size + '_3' + encodeURIComponent(relativePath).replace(/%/g, '_');
							alert(fileid)
							return (fileid);
					}
			});
