### ISSUE TITLE
zoomData load image only on zoom

### ISSUE THREAD

**Issue by Gritmatch** [kartik-v/bootstrap-fileinput#1720]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

`  'initialPreviewConfig' => [
                    [
                        'zoomData' => $zoomUrl, // separate larger zoom data
                    ]`

zoomData loads zoom image right away when dropzone loads.
The screenshot below shows 6 images loaded. 3 thumbnails and 3 large zoom images.

![image](https://user-images.githubusercontent.com/46830254/123351476-25d5a300-d52b-11eb-9f21-c4286f623b92.png)

## Expected behavior and actual behavior

I was expecting zoomData image to only load when user clicks on the zoom button. This would conserve resources. Perhaps I misunderstand the function of zoomData. Does it exist just to display different image in zoom than is displayed in preview and not necessarily to avoid loading large images, if not requested by the user?

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.2.2

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Yes zoom data is loaded on the client and stays hidden until user chooses to see zoomed view.

**Comment by kartik-v** [comment]
Will check if a potential enhancement is possible to control this

**Comment by kartik-v** [comment]
Resolved via latest enhancement above - `zoomData` will be lazy loaded on demand (when a user chooses to zoom to the specific content).
