### ISSUE TITLE
"fileselect" event doesn't work in new version of plugin

### ISSUE THREAD

**Issue by itajackass** [kartik-v/bootstrap-fileinput#1721]
I always used older version of file-input plugin.
Now after I upgraded to latest version, "fileselect" event doesn't trigger.

**Comment by lourdas** [comment]
Yes, same here. It does not seem to trigger.

**Comment by lourdas** [comment]
I just discovered that it triggers when you select a file that is not allowed by extension. When you select files that are normally allowed, it does not trigger.
