### ISSUE TITLE
Drap&drop file and verification fail

### ISSUE THREAD

**Issue by itajackass** [kartik-v/bootstrap-fileinput#1723]
I've a control check on submit that check if files are selected:

     ....
    $("body").find(".attach").each(function(index){			
		if ( $(this).val() == "" ) {
			alert("NO files selected");
			return false;
		}			
	});
      ...

It work great if I select files using "select button" of plugin. But if I use drag/drop, check fails" and I need to change code into:

      $("body").find(".attach").each(function(index){			
		if ( $(this).fileinput('getFilesCount') == 0 ) {
			alert("NO files selected");
			return false;
		}
	});

to get it working.

Bug or not?

**Comment by kartik-v** [comment]
Again check if you are wrongly combining modes as mentioned in #1724. Use ajax mode of submission to achieve your use case. If issue persists, please share a JS Fiddle to reproduce. Thanks.
