### ISSUE TITLE
Selecting files on several step, lose older during upload

### ISSUE THREAD

**Issue by itajackass** [kartik-v/bootstrap-fileinput#1724]
I've a form with input files initialized like this:

      $("body").find(".allegato_comunicazione").fileinput({
		language: 'it',
		theme: 'fas',
		uploadUrl: '#',
		removeFromPreviewOnError : true,
		overwriteInitial: false,
		maxFilesNum: 30,
		showUpload: false,
		hideThumbnailContent: true,
		fileActionSettings : {
			showZoom : false,
			showUpload : false,
		}
	}).on('fileerror', function(event, data, msg) {
		alert(msg);
	});

If I select from PC for example 2 files **at the same time**, they appears in the preview area. Then I add other 3 files **at the same time**  for example....so in the preview area now there are 5 files in total. But when I submit, only latest 3 files are uploaded. The problem appear both If I use brag/drop and "select button".

Another problem, if I use drag/drop, when I click upload, no file are uploaded!!

I don't use ajax, but I need to keep "uploadUrl: #" to enable possibility to select files in multiple step. If I remove "uploadUrl: '#',", i can't select, for example 2 files, then select other X files in another time....

**Comment by kartik-v** [comment]
Please [read docs and the usage modes of the plugin](https://plugins.krajee.com/file-input#usage-modes) to understand why this is happening. Appending files to a selection is only supported via Ajax Mode and not via the Form Submission mode. Check the [comparison of modes](https://plugins.krajee.com/file-input#modes-compared). 

To achieve your use case, you must read the file data on your server via a valid `uploadUrl` - faking the upload url to a hash and trying to read via form submit (combining modes) will not work as mentioned in the plugin. In a form submission mode - the functionality is limited to a native HTML file input (which does not allow appending files, and other features).
