### ISSUE TITLE
How to set listfile by method?

### ISSUE THREAD

**Issue by SherwinVN** [kartik-v/bootstrap-fileinput#1728]
I have list urlfile or list datafile. I want set data to control?

How can do it?
thanks!

**Comment by kartik-v** [comment]
Not clear with your query. Can you please explain the issue? The plugin is a replacement for file input and allows you to select files for upload from the client only.

**Comment by SherwinVN** [comment]
> Not clear with your query. Can you please explain the issue? The plugin is a replacement for file input and allows you to select files for upload from the client only. You can pass additional data via [`uploadExtraData`](https://plugins.krajee.com/file-input/plugin-options#uploadExtraData).

Tôi có một số vấn đề:
1. Tôi muốn gán dữ liệu cho input-file, dữ liệu là danh sách url hoặc danh sách file. 
Tôi không dùng initialPreview vì input file đã được khởi tạo và tôi không muốn tạo lại.
2. Sau khi tôi gán dữ liệu cho input-file thì người dùng có thể chọn thêm hoặc xóa bớt, và tôi sẽ phải tải lại tất cả ảnh lên server để xử lý.(Tôi không dùng uploadUrl vì tôi đang sử dụng asp.net và sử dụng UpLoad(Guid ParentId, IList<IFormFile> upload) => IFormFile chứa thuộc tính fileName còn bolb thì không có).
=> Vì phải lấy tất các các file cũ và file người dùng chọn mới, nên tôi không thể xử dụng $("#input-pd")[0].files vì nó không có dữ liệu của người dùng chọn mới.
=> vì tôi không sử dụng uploadUrl nên tôi tắt uploadUrl . Nhưng, khi tắt uploadUrl thì không hiển thị nút xóa trên xem trước.
=> Tôi có thử tạo lại input-file(destroy) và sử dụng initialPreview, khi hiển thị lên thì không thể thực hiện remove element item preview (remove all cũng không hoạt động), chỉ khi chọn 1 file mới thì mới có thể thực hiện remove item preview. 

==> Vậy tôi muốn lấy cả dữ liệu cũ và dữ liệu người dùng chọn mới để xử lý thủ công.
==> Gần như tôi không sử dụng các hàm tương tác với server mà chỉ muốn xử lý ở client. (add, remove, getlistdata...) 
Có cách nào giúp tôi hay không?

**Comment by SherwinVN** [comment]
Thanks for your answer. But it is not what I want, I will try to solve my problem in another way, maybe an extention. It is true that we cannot modify the native HTML FILE INPUT via JAVASCRIPT, but we can have another way of doing this.

Thanks again for your answer.
