### ISSUE TITLE
The files that i've uploaded were replaced

### ISSUE THREAD

**Issue by RayhanYulanda** [kartik-v/bootstrap-fileinput#1729]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

I've download the newest package and I've import the js and css but i got problem that the package replace the files that i've input not extend the exist files. Another problem is I can't remove the single file, it just can remove the entire files

## Expected behavior and actual behavior

When I follow those steps, I see files replaced
I was expecting that the files not replaced and can remove a single file.

Here is it the code
`<input id="files" name="files[]" class="file" type="file" data-theme="fas" accept="image/jpeg,image/jpg,image/png,application/pdf" required multiple>`

And this is the js
```
$("#files").fileinput({
                previewFileType: 'any',
                showRemove: true,
                showUpload : false,
                maxFileSize: 5000,
                allowedFileExtensions: ["png", "jpg", "jpeg", "pdf"],
                showClose: false,
                language: 'id',
});
```

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: jQuery v3.4.1
- bootstrap-fileinput version: bootstrap-fileinput v5.2.2

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins

**Comment by kartik-v** [comment]
Duplicate [read this comment](https://github.com/kartik-v/bootstrap-fileinput/issues/1724#issuecomment-870404902).
Also please [read docs and the usage modes of the plugin](https://plugins.krajee.com/file-input#usage-modes) to understand why this is happening. Appending files to a selection is only supported via Ajax Mode and not via the Form Submission mode. Check the [comparison of modes](https://plugins.krajee.com/file-input#modes-compared).
