### ISSUE TITLE
Send extraData when no files are attached

### ISSUE THREAD

**Issue by dalamberts** [kartik-v/bootstrap-fileinput#173]
Here is my code:
 
       $('#submit_test').on('click', function(e) {
        	$('#file4').fileinput('upload');        	
        });

Works great if file is attached, sends extraData and files.  If no files are attached OR if no files and no extraData are defined, it does nothing.

**Comment by dalamberts** [comment]
I am not getting the following exception:
![upload-no-file-no-extra-data-exception](https://cloud.githubusercontent.com/assets/3199307/6315615/4bf6e558-b9d5-11e4-96ea-a543196802fc.png)

**Comment by dalamberts** [comment]
When I submitted the form with no files and no extra data using: 
$('#file4').fileinput('upload');

**Comment by dalamberts** [comment]
Also when I submitted the form with extra data.

**Comment by kartik-v** [comment]
You can check with the updated code from dev-master.

**Comment by dalamberts** [comment]
I got another exception when I uploaded one file with extra data:
![upload-one-file-and-extra-data-exception](https://cloud.githubusercontent.com/assets/3199307/6315639/009baeb2-b9d6-11e4-82bb-b5a9d126714e.png)

**Comment by kartik-v** [comment]
Check with the latest updated code from dev-master.

**Comment by dalamberts** [comment]
Downloaded the most recent update, everything appears to be working now.  Thank you!
