### ISSUE TITLE
Plugin ignores the MIME type for files without extension especially for PDF files (PNG is displayed fine)

### ISSUE THREAD

**Issue by crestAT** [kartik-v/bootstrap-fileinput#1732]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. For unified file names I convert all names to hash values WITHOUT file extension
2. I create the appropriate initialPreviewConfig definition (especially filetype 'application/pdf' and type 'pdf')
3. If I call the page Images are displayed fine but PDFs shows 'raw' data (in thumbnail and zoom mode)
4. If I give the converted file name the extension '.pdf' it's displayed fine (in thumbnail and zoom mode)

## Expected behavior and actual behavior
file name with extension in the key
            [caption] => D0B7DBC25195FB2690EA01473E1FE42B.pdf
            [size] => 1618827
            [filetype] => application/pdf
            [type] => pdf
            [url] => pages/backend/delete_upload.php
            [key] => /mnt/UPLOADS/files/160/D0B7DBC25195FB2690EA01473E1FE42B.pdf
![image](https://user-images.githubusercontent.com/6754253/124870131-813f7080-dfc2-11eb-99dd-98d28d9daf57.png)

file name without extension:
            [caption] => EAA0F50AE1962A0E0E9C6995DA6D5D4E.pdf
            [size] => 1618827
            [filetype] => application/pdf
            [type] => pdf
            [url] => pages/backend/delete_upload.php
            [key] => /mnt/UPLOADS/files/160/EAA0F50AE1962A0E0E9C6995DA6D5D4E
![image](https://user-images.githubusercontent.com/6754253/124870315-c95e9300-dfc2-11eb-9e4b-f15b4fbd1ecc.png)

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [x] Microsoft Edge Chroium
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.4.1
- bootstrap-fileinput version: 3.3.7

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

So the question would be if it's absolutely necessary to provide the file extension to the plugin or if the initialPreviewConfig should be sufficient for the plugin to display the file correctly in thumbnail and zoom view?

Many thanks in advance!

**Comment by kartik-v** [comment]
This is more to with browser being able to detect the mime type - and display PDF using the browser embedded PDF viewer.

I suggest the easiest way to handle is do one of the following:

1. Do the check in your server code (on the mime type) and rename the file with `.PDF` extension before setting it in `initialPreview`
2. Try using the PDF.js viewer by using the [`usePdfRenderer`](https://plugins.krajee.com/file-input/plugin-options#usePdfRenderer) property and the [`pdfRendererUrl`](https://plugins.krajee.com/file-input/plugin-options#pdfRendererUrl) property - will require the PDF JS library on your web server.
