### ISSUE TITLE
how filecleared works?

### ISSUE THREAD

**Issue by cowpy** [kartik-v/bootstrap-fileinput#1733]
when select a file and not uploaded ，the 'filecleared' work correctly
but,when  uploaded file to server side and return json contains 'initialPreview initialPreviewConfig' , i found the 'filecleared'  does not remove the fileinput.initialPreviewConfig and fileinput.initialPreview ？

**Comment by kartik-v** [comment]
The event `filecleared` is triggered only when you click REMOVE on main input section to clear all files --- or when any validation error is faced in validating the file selection (in form submit or non-ajax mode) -- or for certain specific validation errors in ajax mode like max file size.
