### ISSUE TITLE
modal preview is white by ajax response

### ISSUE THREAD

**Issue by lj19950508** [kartik-v/bootstrap-fileinput#1734]
## Prerequisites

- [✔] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [✔ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [✔] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.upload with ajax  , and response  like 
![image](https://user-images.githubusercontent.com/15307901/126255437-d5c4a649-4638-4401-9fe6-450ad975984c.png),
and it can be preview by image type.  
2.  but when it zoom it,  it's blank
![image](https://user-images.githubusercontent.com/15307901/126255793-52f13841-4613-42ae-ba82-46569c4ba2f7.png)

## Expected behavior and actual behavior
1.  Can type be identified by suffixes？    just like  image can  identified  by .png
2.  why thumbnail works but modal deital doesn'twork .

when not uploaded, every work , but when uploaded and use response option, i can't preview with modal detail
 

## Environment

Browsers

- [✔ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [✔ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.2.2
- botstrap 4.4.1
## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [✔ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Which plugin version are you using?

**Comment by lj19950508** [comment]
bootstrap-fileinput-5.2.2

**Comment by kartik-v** [comment]
Not sure why - because it works fine on tests - You can cross check this with [ajax demo example #4](https://plugins.krajee.com/file-input-ajax-demo/4). 

Check your app code and client browser has stale cache loading outdated assets. Check if any other javascript errors in your app on your client browser console.

Also test with the latest code on dev-master (v5.2.3 not released yet) and confirm.

**Comment by lj19950508** [comment]
1. I found that the property **downloadUrl** causes this problem.  if i set it ,   the modal will blank. 
2.  Can I make it adaptive to previewtype without setting type

**Comment by lj19950508** [comment]
sorry   , It does not conflict with downloadurl  , it 's just sometime can be preview with modal , sometimes doesn't work

**Comment by lj19950508** [comment]
when i use batch upload button ,  it's works 
when i use simpe upload button , it doesn't work ;
![image](https://user-images.githubusercontent.com/15307901/126259423-dc47a96c-7fdc-4207-bde6-b9a734338ee1.png)

**Comment by lj19950508** [comment]
![image](https://user-images.githubusercontent.com/15307901/126259536-d0965a01-5f7e-49c7-acfe-4e8a0794b8ae.png)
 ajax demo example #4. , when i first upload with simple upload button , and it errors, but when i use batchupload button , it's ok

**Comment by lj19950508** [comment]
@kartik-v   If I don't define type, can I automatically adapt the preview file type according to the file suffix 
eg.
 .jpg  ->image
.pdf ->pdf
.txt-> text

**Comment by lj19950508** [comment]
@kartik-v   If I don't define type by response, can I automatically adapt the preview file type according to the file suffix 
eg.
 .jpg  ->image
.pdf ->pdf
.txt-> text
because if i upload txtfile and  return a pdffile  without type ,  it will preview as image
![image](https://user-images.githubusercontent.com/15307901/126270457-ada40aff-3429-42c3-8057-bc37dca9c917.png)

**Comment by lj19950508** [comment]
@kartik-v     when  i  upload  and  response **initialPreviewConfig**  without **type**  fileTypeSettings  doesn't work   ,  
i must be set  attr  **type**



this is response 
![image](https://user-images.githubusercontent.com/15307901/126273692-f39fc994-8e7c-44d1-8a9e-54749454c86a.png)

**Comment by lj19950508** [comment]
prev comments  add result  image 
![image](https://user-images.githubusercontent.com/15307901/126273842-9e891f07-5044-48ba-93a5-7778cda290d1.png)

**Comment by kartik-v** [comment]
Yes for `initialPreview` you must set the `type` in `initialPreviewConfig` for each file from server to display the right template.... else default will be `image`
