### ISSUE TITLE
Filesize is compared in KB (= 1000 Bytes) but displayed in KiB (= 1024 Bytes). 

### ISSUE THREAD

**Issue by reckert** [kartik-v/bootstrap-fileinput#1736]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue
1. Create a simple file upload form. Set the maxFileSize to 100 (KB/KiB?). Open it in your browser (even from the file system).
```
	$(document).ready(function() {
		$("#input-upload").fileinput({
			maxFileSize: 100
		});
	});
```
2. Or try it here: https://jsfiddle.net/1neawk5x/
2. Drop a file with a size of (i.e.) 101974 bytes (= 99.58 KiB = 101.97 KB)
3. Look at the file size in the preview and in the error message

## Expected behavior and actual behavior

The preview shows that the size of the file is 99.5 KB. That is identical to the value shown in Ms Windows file explorer.
The error message reports "File "xxxx" (101.97 KB) exceeds maximum allowed upload size of 100 KB.

I was expecting no error message to occur / both values to be the same. 

When a file is selected, its size is converted into KB by dividing by 1000. 
https://github.com/kartik-v/bootstrap-fileinput/blob/1a97ee0c9f17bc5cf5fd73ba7a9e50c110113f40/js/fileinput.js#L5379

This value is later compared to maxFileSize, so it can be assumed that maxFileSize holds the maximum size in KB (1000 bytes), too
https://github.com/kartik-v/bootstrap-fileinput/blob/1a97ee0c9f17bc5cf5fd73ba7a9e50c110113f40/js/fileinput.js#L5447

The default method to display the size really uses KiB (1024 bytes), though.
https://github.com/kartik-v/bootstrap-fileinput/blob/1a97ee0c9f17bc5cf5fd73ba7a9e50c110113f40/js/fileinput.js#L4139

That way, the size compared to the maxFileSize property is a different one than the one displayed to the user.

The "iB" units are not frequently used by normal users and several systems (including MS Windows file explorer) calculate in Base2 (1024 bytes) but still show  "KB", "MB", etc..
I would suggest to just change the calculation of the file size by changing 1000 to1024 in line 5379 in js/fileinput.js.

## Environment

Browsers
- [x] any, tested on Firefox Desktop and Chrome

Operating System
- [x] any, tested on MS Window

Libraries
- jQuery version: 3.6.0
- bootstrap-fileinput version: 5.2.2

## Isolating the problem
- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins

**Comment by kartik-v** [comment]
Fixed via the commit, New property `bytesToKB` has been introduced - which defaults to `1024` and is used for conversion

**Comment by kartik-v** [comment]
Fixed via the latest commit, New property `bytesToKB` has been introduced - which defaults to `1024` and is used for conversion
