### ISSUE TITLE
Integration with standard Bootstrap 3.x popover

### ISSUE THREAD

**Issue by lourdas** [kartik-v/bootstrap-fileinput#1739]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

I cannot integrate the standard popover bootstrap (v.3) with yii2-widget-fileinput. Is there an example somewhere to make popover work with the extension?

**Comment by kartik-v** [comment]
This is a question beyond the scope of this plugin - and more to do with your usage of Bootstrap 3.x library and its components. Suggest to check the Bootstrap 3.x documentation for use of its popover component.
