### ISSUE TITLE
Uncaught TypeError: self.fileManager is undefined - after second load of a modal window

### ISSUE THREAD

**Issue by strtob** [kartik-v/bootstrap-fileinput#1743]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Load fileinput as component of a form in modal window (bs4), which is opening 
2. Close the window and re-opening
3. All assets not loading caused by an js error

## Expected behavior and actual behavior

As mentioned in Steps, no js error.

## Environment

Browsers

- [x] Google Chrome
- [x ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: jQuery JavaScript Library v3.6.0
- bootstrap-fileinput version: bootstrap-fileinput v5.2.2

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

Following js error occurs after I've opened second time my modal bs4 window:

```
Uncaught TypeError: self.fileManager is undefined
    clearFileStack fp-profile:5188
    _cleanup fp-profile:743
    destroy fp-profile:5842
    fileinput fp-profile:5909
    jQuery 2
    fileinput fp-profile:5892
    <anonymous> fp-profile:602
    jQuery 14
    <anonymous> modal.js:77
    jQuery 8
    <anonymous> alert.js:154
    <anonymous> bootstrap.bundle.js:9
    <anonymous> bootstrap.bundle.js:10
```

Error is in line number 5188 in bootstrap-fileinput v5.2.2 of kartik at self.fileManager.clear()

```
clearFileStack: function () {
            var self = this;
            **self.fileManager.clear();**
            self._initResumableUpload();
            if (self.enableResumableUpload) {
                if (self.showPause === null) {
                    self.showPause = true;
                }
                if (self.showCancel === null) {
                    self.showCancel = false;
                }
```

Any helpful ideas would be very very appreciated!

Thanks a lot,
Tobi

**Comment by strtob** [comment]
I should mentioned that I use this great extensions within yii2

**Comment by kartik-v** [comment]
If you are trying to render the fileinput dynamically inside a modal dialog via ajax at runtime - you need to reinitialize the plugin correctly for every second load of the modal - else it will not work correctly. You may need to cross check your javascript code for this or use `renderAjax` for some cases within yii2.
