### ISSUE TITLE
How to set the max length of a file name

### ISSUE THREAD

**Issue by crestAT** [kartik-v/bootstrap-fileinput#1746]
Hello, this is not an issue but a question!
I checked the documentation for an option to set the maximum length of a file name but didn't find one.
The reason was because I noticed that for very long file names (> 225 chars) the caption was ellipsized therefore I thought that there is an option to set the maximum file names length...  ?
Thanks in advance!

**Comment by kartik-v** [comment]
This is just a CSS styling (overflow ellipsis) to display long file names within the container (so that text does not overflow). The long filename is still displayed as a title on hover. You can override the CSS styles if you need for your use case by using themes.
