### ISSUE TITLE
Setting fileActionSettings.showRemove to false does not remove action Delete icon

### ISSUE THREAD

**Issue by jlayt** [kartik-v/bootstrap-fileinput#1747]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Configure fileinput with fileActionSettings: {showRemove: false} 

## Expected behavior and actual behavior

When I follow those steps, I see...

The Remove Action button on each file

I was expecting...

The Remove Action button to be removed

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [X] Safari

Operating System

- [X] Windows
- [X] Mac OS X
- [X] Linux
- [X] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.2.3

## Isolating the problem

- [] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/)

See fiddle https://jsfiddle.net/13czj05t/ from previous bug report https://github.com/kartik-v/bootstrap-fileinput/issues/1527 which was closed by bugbot.

Edit: Update fiddle to latest versions https://jsfiddle.net/qf8t9h1v/6/ not sure why theme icons don't show.

**Comment by kartik-v** [comment]
The `fileActionSettings` works only for files that are newly selected (not yet uploaded) and does not work for files in `initialPreview`.

For just hiding `showRemove` globally across all initialPreview just set the property `initialPreviewShowDelete` to `false`.

For specific thumbnails - to control display of action buttons (e.g. `showRemove` or `showDownload`) for files in initial Preview - you need to set these within `initialPreviewConfig` (will refine docs to make this clear). So for your use case you need to set the `initialPreviewConfig` correctly like:

{
initialPreviewConfig: [
   {caption: 'File1.jpg', size: '100', showRemove: false},  // hide remove button
   {caption: 'File2.jpg', size: '3430', showRemove: true},  // show remove button for this file
]
