### ISSUE TITLE
how can fetch file on load page from db

### ISSUE THREAD

**Issue by Ammar441** [kartik-v/bootstrap-fileinput#1748]
i want to fetch and display file from database after load page direct how can do this?

**Comment by b1ghacker** [comment]
I want to do this too, i don't have see a function for read from server in a callback, anyone?

**Comment by kartik-v** [comment]
This is entirely upto your server code that sets the JSON object for file input plugin and passes the file-specific links via `initialPreview` and `initialPreviewConfig`. You need to build your server code accordingly to read files from database and convert them to links/data on load.
