### ISSUE TITLE
Version 5.2.4 and 5.2.5 - problem with document.currentScript.src when running tests with karma and webpack

### ISSUE THREAD

**Issue by rjaros** [kartik-v/bootstrap-fileinput#1756]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

Libraries

- bootstrap-fileinput version: 5.2.4, 5.2.5

The change introduced in this commit - https://github.com/kartik-v/bootstrap-fileinput/commit/22ce1ed13c0b17df8dbca8c9e27cc34fd92404e7#diff-336f513b57ac7d4ac2af892a5fdc467725efd1b7c47b3eaa2ec64fbb6935f2da
makes the component fail when running tests with webpack and karma, because `document.currentScript` property is null in such environment. It would be great if some fallback could be provided (e.g. returning empty string from `getLoadingUrl()` when `currentScript` is null). I've tried to workaround the issue but without success.

Unfortunately I can't provide a simple example to reproduce the problem.

**Comment by kartik-v** [comment]
Enhancement provided. Will tag a new release later after more testing.

**Comment by rjaros** [comment]
It would be great to have new release. I have reports from users of my framework, which uses your component with webpack, they are affected by this issue not only in tests. Thank you for all your effort!

**Comment by kartik-v** [comment]
v5.2.6 has been released. 

--
_If you like the plugins help us by donating_
