### ISSUE TITLE
Muito Bonito Mas Não Funciona

### ISSUE THREAD

**Issue by cbotelho** [kartik-v/bootstrap-fileinput#1757]
Muito Bonito Mas Não Funciona! Nada, carrega os arquivos mais não faz upload, fica dizendo "voce deve selecionar pelo menos 3 arquivos" sendo que foram selecionado 3/4/5/6/7/8 arquivos e nada funcionou.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Not clear with the issue - Please file issues correctly (for only the `bootstrap-fileinput` plugin related issues) in English. 

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/kartik-v/bootstrap-fileinput/blob/93490f55f06714b1b41b820c0f405052ebdea273/.github/CONTRIBUTING.md) and [code of conduct](https://github.com/kartik-v/bootstrap-fileinput/blob/93490f55f06714b1b41b820c0f405052ebdea273/.github/CODE_OF_CONDUCT.md).
