### ISSUE TITLE
got bootstrap is not defined in fileinput.js

### ISSUE THREAD

**Issue by spo0okie** [kartik-v/bootstrap-fileinput#1758]
1. upgrade bootstrap-fileinput to 5.2.6
2. try to render page with Kartik\FileInput on it
3. get subject failure
4. downgrade bootstrap-fileinput to 5.2.4
5. it works fine!

- [x] Google Chrome
- [x] Windows
- bootstrap-fileinput version: 5.2.6

## Isolating the problem
in 5.2.4 there is "window.bootstrap" usage in code where bootstrap version is detecting (in very begining of fileinput.js)
in 5.2.6 just bootstrap itself and it looks like undefined

**Comment by quasiperfect** [comment]
hi @kartik-v this is wrong. bootstrap is not polluting window anymore and if i don't include Alert in my bootstrap js your comparison failes

**Comment by kartik-v** [comment]
Need to check if anything changed in BS lib. Irrespective.... You need the bootstrap JS Library and jquery to be loaded before the plugin JS assets. Can you check this.
