### ISSUE TITLE
The problem was previously. Cannot read property 'push' when uploading invalid file

### ISSUE THREAD

**Issue by MaksTrader** [kartik-v/bootstrap-fileinput#1759]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by MaksTrader** [comment]
Greetings. 
Faced with the same problem. Checked and tried everything. 

It only occurs when the first image is initially loaded. 

Afterwards, until the page reloads, the problem does not appear. Images are added and deleted without problem
![Screenshot_1](https://user-images.githubusercontent.com/47728504/134653853-93350bfd-c975-4814-8b34-05653e8ca11f.png)
.

**Comment by MaksTrader** [comment]
The model returns the same data for the first image as for the nex
![Screenshot_2](https://user-images.githubusercontent.com/47728504/134654098-d4f76cf1-0c3a-44eb-bf55-3e9f937e3168.png)
t.

**Comment by MaksTrader** [comment]
If you check the file download in this way, it happens in all cases, but the file is downloaded and after reloading the page is display
![Screenshot_4](https://user-images.githubusercontent.com/47728504/134654711-5a1f960e-1e4b-496a-970b-c0a3ca84047f.png)
ed

**Comment by MaksTrader** [comment]
But JSON returns empty values
![Screenshot_3](https://user-images.githubusercontent.com/47728504/134654862-bcdfded4-d87f-4aae-b8ff-15c7003ff094.png)
.

**Comment by kartik-v** [comment]
Debug your server code to check why `initialPreview` and `initialPreviewConfig` are sending null to the plugin.

**Comment by MaksTrader** [comment]
In all cases, the Response gets values from JSON.
{"initialPreviewConfig":[{"caption":"Background.png","url":"/purchased/deletefile?block=1&file=Background.png","key":"Background.png","size":1180994}],"initialPreview":["/wtwload/1/Background.png"]}

The only difference is this. 
1. When loading the first file. 
initialPreviewConfig = null

![Screenshot_5](https://user-images.githubusercontent.com/47728504/134678616-3d7059a1-5cbd-4b7b-891a-d4a42d2d913c.png)

2. When loading subsequent file with the same scripts. 
initialPreviewConfig = []
in Form Data
No thoughts.

![Screenshot_6](https://user-images.githubusercontent.com/47728504/134678856-638780f3-e802-4359-bc1f-32006228f482.png)

But. If I set overwriteInitial' => true? the problem disappears. But it is necessary to load several files with possibility of deletion without page reloading.

**Comment by MaksTrader** [comment]
Problem solved.
The tips were very helpful. 
Thank you very much.

It wasn't labeled. 
 $preview = [];
 $config = [];
