### ISSUE TITLE
Possible to upload in one file and then switch to chunks (resumable) if > specific file size?

### ISSUE THREAD

**Issue by kofarrell1076** [kartik-v/bootstrap-fileinput#1760]
So not an issue, just a question

We want to use ajax to upload a  file is say up to 30MB and over more than that use the resumable upload so we can break it into chunks on the server.

The reason - the majority of files will be less than 30MB so we keep these in one piece on the storage. Anything large which is the exception, gets chunked.

thanks

**Comment by kartik-v** [comment]
One way to achieve your use case is to set the `resumableUploadOptions.chunkSize` to `30M` for your use case and `enableResumableUpload` set to `true` - this will ensure that files <= 30 M will be uploaded in one shot -- whereas files > 30 M will be broken into multiple chunks.
