### ISSUE TITLE
file binary not found

### ISSUE THREAD

**Issue by foreverSummer1** [kartik-v/bootstrap-fileinput#1764]
i couldn't get file from server in the way of Resumable Uploads;my server written by JAVA. please Big God help me.best wishes

**Comment by foreverSummer1** [comment]
eg. i couldn't get file from client on the server

**Comment by foreverSummer1** [comment]
[fileinput.txt](https://github.com/kartik-v/bootstrap-fileinput/files/7537204/fileinput.txt)

**Comment by kartik-v** [comment]
Hi - this repo can be used to report issues and enhancements related to the plugin.

Seems this is a programming issue to manage from your end - (unfortunately this is not the right forum - suggest you to go through handling file uploads on server and building the server code accordingly). You can also check the comments section on the demos page and ask for help from others.
