### ISSUE TITLE
Failed to load css from jquery

### ISSUE THREAD

**Issue by AsmaaOUK** [kartik-v/bootstrap-fileinput#1766]
Hello! hope everyone doing great :D
I have a btn when you click on it the input will change from text to fileinput
but when i do that with js or jquery the css and js not apply on it, and if i just wrote 
`<input id="input-b1"  name="input-b1" type="file" class="file w-100" data-browse-on-zone-click="true">`
directly on my html without using jquery it showed correctly
Can someone help me?

**Comment by kartik-v** [comment]
Do not add the CSS class `file` if you are initializing the plugin via javascript.
