### ISSUE TITLE
maxAjaxThreads not limiting number of ajax calls

### ISSUE THREAD

**Issue by bravo14** [kartik-v/bootstrap-fileinput#1767]
Hi

I have set maxAjaxThreads: 3 but the plugin starts an upload for all files in the batch simultaneously.  This is resulting in timeout errors.

Plugin called using the cdn as below.
https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.2.0/js/fileinput.min.js

I was expecting it to limit the number of files it attempted simultaenously

**Comment by bravo14** [comment]
Do you have an estimated time frame on the enhancement?

**Comment by kartik-v** [comment]
The enhancement has already been done with the above commit.

**Comment by bravo14** [comment]
Sorry to sound stupid. Do I just download the latest version of the plugin?

**Comment by kartik-v** [comment]
Yes for the version from dev-master. Once a new release is tagged you should be able to pick via bower, composer, npm etc
