### ISSUE TITLE
Ajax upload issue

### ISSUE THREAD

**Issue by dndhost** [kartik-v/bootstrap-fileinput#1768]
Hi! If i send from jango initialPreview and initialPreviewConfig after success upload the green check appears for a second and is replaced by move/rearrange. at the same time, the plugin clearly considers that the download is not complete, although I see the files that have appeared on the server side and does not work out the repeated upload of the file identical to the first download.
If set initialPreview initialPreviewConfig to []. green check on board and all fine. Please, what am I doing wrong, what moment I missed. Second day I can't figure it out.

Sorry for my english.

**Comment by kartik-v** [comment]
If you want same file to be uploaded again from client - you need to ensure the file identifiers must be changed in `initialPreviewConfig` Check the [initialPreviewConfig](https://plugins.krajee.com/file-input/plugin-options#initialPreviewConfig) documentation - you can set a different unique `fileId` for  each file to ensure the plugin is able to reupload the same file.

**Comment by dndhost** [comment]
I set like this
        initialPreviewConfig = [{
            'key': filename,
            'fileId': filename,
            'caption': filename,
            'type': file_type,
            'downloadUrl': url,
            'url': 'file_delete/',
            'size': os.path.getsize(file_dir),
Drop file with filename like 1.txt, press upload,
![image](https://user-images.githubusercontent.com/95858038/145673953-35132fea-07dc-4480-9f3b-d816047ed485.png)
 try to upload second time, and upload will success again,
![image](https://user-images.githubusercontent.com/95858038/145673967-247f4326-adc2-48fc-a32d-d300296f9a6e.png)

                required: true,
                language: 'ru',
                purifyHtml: true,
                uploadUrl: "att_upload/",
                deleteUrl: "file_delete/",
                allowedFileExtensions: ['txt', 'xls', 'xlsx', 'xml', 'html', 'png'],
                uploadAsync: true,
                previewFileIcon: '<i class="fas fa-file"></i>',
                {#allowedPreviewTypes: null, // set to empty, null or false to disable preview for all types#}
                previewFileIconSettings: {
                    'docx': '<i class="fas fa-file-word text-primary"></i>',
                    'xls': '<i class="fas fa-file-excel text-success"></i>',
                    'xlsx': '<i class="fas fa-file-excel text-success"></i>',
                    'pptx': '<i class="fas fa-file-powerpoint text-danger"></i>',
                    'jpg': '<i class="fas fa-file-image text-warning"></i>',
                    'pdf': '<i class="fas fa-file-pdf text-danger"></i>',
                    'zip': '<i class="fas fa-file-archive text-muted"></i>'
                },
                overwriteInitial: false,
                showUpload: false,
                browseOnZoneClick: true,
                preferIconicPreview: true,
                minFileCount: 1,
                fileActionSettings: {
                    showZoom: false
                },

**Comment by dndhost** [comment]
I want to note that if you do not upload, then the plugin correctly reports that I am trying to add a file that is already present. And if I click to upload the first file, then no error occurs when adding or uploading second same file.

**Comment by dndhost** [comment]
I need validation, but a see this

![image](https://user-images.githubusercontent.com/95858038/145677418-fff649bc-e34b-4549-8916-3155cb03cce9.png)
![image](https://user-images.githubusercontent.com/95858038/145677433-0ffbdc54-4ece-4920-8230-ec1df4234d4f.png)

**Comment by kartik-v** [comment]
I think the best way to do this validation is on the server side and reject the upload via json with an appropriate duplicate msg which the plugin can. On your server - you can do a file checksum and compare more correctly than the current check by the plugin which just uses the filename and size autogenerate a file id to detect uploading unique files.

**Comment by dndhost** [comment]
Hello. It is very strange that if I do not set initialPreviewConfig, then the plugin can perform a uniqueness check on the file name on the client side. And if I set  initialPreviewConfig, then the plugin checks the uniqueness of the file name only before uploading to the server, and if the file has already been uploaded to the server, it immediately loses this ability, although the plugin has all the data in  initialPreviewConfig to perform this check. It is not logical, in my opinion, to upload a file to the server, which can be excluded at the client level. md5 check not need, only file name i check.

**Comment by kartik-v** [comment]
The initialPreview files are files sent from server and plugin does not validate these for reasons because these files are beyond the client control as to the logic to name, size and whether to allow duplicate or not are all server level decisions left to each developer. They can send these file list  and config or each file and validate each of them against a future file if needed for specific use cases all of which is controlled at server code level.

Open to any enhancement if you feel it can improve this... then your can open a PR. But I see there is no way for client to know what is unique within the uploaded files on server and what is not across various scenarios... It would be logical to do this validation at server side.
