### ISSUE TITLE
resizing images: maxImageWidth is compared to preview img HTMLElement width and not exif width -> portait images are resized with wrong dimensions

### ISSUE THREAD

**Issue by MarisaNat** [kartik-v/bootstrap-fileinput#1769]
## Steps to reproduce the issue

1. take photos with the same device in portrait and landscape format (best case with similar filesizes for better comparison)
2. check Exif Image Width and Exif Image Height of the images e.g. with exiftool --> should be the same for both images
2. set options as following: resizeImage: true, 
     maxImageWidth: 2000, //anything smaller than the Exif Image Width
     resizeQuality: 0.97,
     autoOrientImage: true
3. add logging for width and height in _getResizedImage function
4. upload images

## Expected behavior and actual behavior
Portrait and landscape image should have similar filesize (if they had similar filesizes before) and same width and height after resizing

But: Portrait images are bigger in filesize by a factor greater 2 and width and height ratio is the other way around as for the landscape image and as for the original Exif Image Width and Exif Image Height.

Reason:
The image width is not taken from the exif data but from the html img Element in the fileinput.
So for portraits the "shorter" edge, which is the width of the HtmlImgElement, is compared and set to maxImageWidth and therefore the "wrong" edge is set to maxImageWidth. 

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.2.6

## Isolating the problem

- [x ] The bug happens consistently across all tested browsers

**Comment by kartik-v** [comment]
Yes for width or height calculation, the plugin uses image's natural  width and height and does not use the orientation. To achieve your use case, you can set both `maxImageWidth` and `maxImageHeight` - check the [resize image auto](https://plugins.krajee.com/file-image-management-demo#image-resize-auto) scenario to resize image for your use case.
