### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by strtob** [kartik-v/bootstrap-fileinput#1770]
Hello,

About 1 month ago, dropzone has starting to put me out the following error in the console:

 Uncaught ReferenceError: require is not defined
    <anonymous> http://localhost:8080/assets/a6738235/dropzone.js:1
dropzone.js:1:25
    <anonym> http://localhost:8080/assets/a6738235/dropzone.js:1

marked is
`var $6mU8w$swchelpers = require("@swc/helpers");`

The components works well, but I can't find the error and haven't change nothing in my app. Is it possible that a new version is responsible for this error?

Best regards,
Tobi

**Comment by kartik-v** [comment]
Hi this does not seem an issue with the plugin. You may need to check your javascript code where you are calling that particular line with the code call `require("@swc/helpers")` - as that seems to be the source for the error. Try commenting blocks of your code to reach the root cause.

**Comment by strtob** [comment]
Hi Kartik,

Thank you for your help. I've thought this is part of the assets which will be loaded by the file input plugin, I have no separate dropzine file included :-/
