### ISSUE TITLE
Human readable sizes in messages like "msgSizeTooLarge"

### ISSUE THREAD

**Issue by wergio** [kartik-v/bootstrap-fileinput#1771]
messages like "msgSizeTooLarge": "File "{name}" (<b>{size} KB</b>) exceeds maximum allowed upload size of <b>{maxSize} KB</b>. Please retry your upload!"

should not force only KB size, but use _getSize() to allow more human readable sizes

this is more like an idea for an enhancement, or there is a way to force it?

PS: very cool plugin! :-)

**Comment by kartik-v** [comment]
Enhancement done via above commit.
