### ISSUE TITLE
Documentation webpage down

### ISSUE THREAD

**Issue by ARedmanDodd** [kartik-v/bootstrap-fileinput#1774]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Attempt to visit https://plugins.krajee.com/

## Expected behavior and actual behavior

When I follow those steps, I see...
The page flashes open for a split second and then a stat counter and a message explaining that an ad blocker is blocking the page is displayed despite having no ad blocker installed and having cleared all cookies.

I was expecting...
to see the documentation page.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [x] Microsoft Edge
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)
![Screenshot_13](https://user-images.githubusercontent.com/50098884/149351898-5ef64688-8ff2-460c-bfac-4b2b53b8e4a3.png)

**Comment by kartik-v** [comment]
Hi - it seems some antivirus program / adblocker / firewall/ proxy is blocking content on your client... can you check that -- because from your screenshot even the CDN CSS/JS from bootstrap assets/content are not being loaded.

Can you check from another device and network (for example your smart phone) and find out the source? Let know if anything else. Thanks.
