### ISSUE TITLE
fileuploaderror - return custom error message.

### ISSUE THREAD

**Issue by Gritmatch** [kartik-v/bootstrap-fileinput#1779]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. fileuploaderror event has message as a parameter as was added in #[559](https://github.com/kartik-v/bootstrap-fileinput/pull/559).
2. I ca see from documentation [here](https://plugins.krajee.com/file-input/plugin-events#event-manipulation) that fileuploaderror  is excluded from option to return custom message as follows:
return { message: 'You are not allowed to do that'}.
3. Setting up msgAjaxError is of no help.

## Expected behavior and actual behavior

Please see this [screenshot](https://assets-gritmatch-public.s3.amazonaws.com/fileuploaderror.png). I can get the error displayed in message parameter of the fileuploaderror. Is there any elegant way to change it and display a more user friendly error? As a last resort I can go and change the html with Java Script, but it is messy. Perhaps I did not find in the documentation something similar to return { message: 'error to display to the user'}?

## Environment

Browsers

- [X ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by Gritmatch** [comment]
I am currently using JSON key error in my server catch statements and it works for most use cases. I agree this is the best approach to display server errors.

However, this use case is different as the error happens due to server memory issues. This is a fatal error, which I can catch in PHP register_shutdown_function, but I cannot be sure at that point what exactly caused memory issues.  In short, in this case I am not able to return error key with JSON. At least I don't think I can (maybe I am wrong). As a result, user sees an ugly error message which reveals more than error message should reveal. So, I want to change it on the client end within the fileuploaderror event.

Perhaps there is a way to enable just to change the error message within fileuploaderror without aborting and locking the input (as you described above).

**Comment by kartik-v** [comment]
Noting a possible enhancement to see if there is a way to trigger a custom message for such cases.

**Comment by kartik-v** [comment]
There is a new enhancement added to achieve these scenarios and a new plugin method `showUserError` has been added along with a new plugin event `fileusererror`.

To show your own custom error - you can use the following:
```js
var $input = $('#file-input-id');
$input.on('fileuploaderror', function(event, data) {
  var userMessage = 'We could not process the upload because of a server error.';

  // to show error specific to each file pass the data as received above - the data object must contain the `fileId`
  $input.fileinput('showCustomError', [userMessage, data]);

  // to show a constant global error not specific to each file do not pass data (uncomment below)
  //  $input.fileinput('showCustomError', [userMessage, data]); 
});
```

**Comment by kartik-v** [comment]
There is a new enhancement added to achieve these scenarios and a new plugin method `showUserError` has been added along with a new plugin event `fileusererror`.

To show your own custom user error - you can use the following enhanced method `showUserError` as shown below:

```js
var $input = $('#file-input-id');
$input.on('fileuploaderror', function(event, data) {
  var userMessage = 'We could not process the upload because of a server error.';

  // to show error specific to each file pass the data as received above - pass `data` (the data object must contain the `fileId`)
  $input.fileinput('showCustomError', [userMessage, data]);

  // to show a constant global error not specific to each file do not pass `data` (uncomment below line to achieve this)
  // $input.fileinput('showCustomError', [userMessage, data]); 
});
```

**Comment by kartik-v** [comment]
There is a new enhancement added to achieve these scenarios and a new plugin method `showUserError` has been added along with a new plugin event `fileusererror`.

To show your own custom user error - you can use the following enhanced method `showUserError` as shown below:

```js
var $input = $('#file-input-id');
$input.on('fileuploaderror', function(event, data) {
  var userMessage = 'We could not process the upload because of a server error.';

  // to show error specific to each file pass the data as received above - pass `data` (the data object must contain the `fileId`)
  $input.fileinput('showUserError', [userMessage, data]);

  // to show a constant global error not specific to each file do not pass `data` (uncomment below line to achieve this)
  // $input.fileinput('showUserError', [userMessage]); 
});
```

**Comment by kartik-v** [comment]
There is a new enhancement added to achieve these scenarios and a new plugin method `showUserError` has been added along with a new plugin event `fileusererror`.

To show your own custom user error - you can use the following enhanced method `showUserError` as shown below:

```js
var $input = $('#file-input-id');
$input.on('fileuploaderror', function(event, data) {
  var userMessage = 'We could not process the upload because of a server error.';

  // to show error specific to each file pass the data as received above - pass `data` (the data object must contain the `fileId`)
  $input.fileinput('showUserError', userMessage, data);

  // to show a constant global error not specific to each file do not pass `data` (uncomment below line to achieve this)
  // $input.fileinput('showUserError', userMessage); 
});
```

**Comment by Gritmatch** [comment]
Thank you for the fix!
I am a little unsure though what is the expected behavior for the option when data is being passed. The comment states that it is to show error specific to each file. Does this mean that file name will be displayed in front of the error message? Currently it does not display.

Below is the code I use and here is the [screenshot ](https://assets-gritmatch-public.s3.amazonaws.com/fileuploaderror+event+-+message.png)of the output. I was uploading 3 files and got 1 error, which is displayed as a custom error message. There is no file specific data (such as filename) in the error. Data contains the fileId property.

```
.on('fileuploaderror', function (event, data, msg) {

            console.log(event);
            console.log(data);
            console.log(msg);

            let userMessage = 'We could not process the upload because of a server error.';

            // to show error specific to each file pass `data` as received above (the `data` object must contain the `fileId` property)
            jQuery('#profilealbum-dropzone').fileinput('showUserError', userMessage, data);

})
```
