### ISSUE TITLE
File input hangs on Precessing when selecting the same file again

### ISSUE THREAD

**Issue by ferdossi** [kartik-v/bootstrap-fileinput#1782]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Use  Advanced Example 8 file input component in the demo page https://plugins.krajee.com/file-input 
2.Select a file but don't upload
3.Select the same file again, it hangs on "Precessing..."

## Expected behavior and actual behavior

When I follow those steps, I see the precessing spinner never ending

I was expecting to have an error message saying the file is already selected

## Environment

Browsers

- [x ] Google Chrome - latest version
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: the one on https://plugins.krajee.com/file-input
- bootstrap-fileinput version: the one on https://plugins.krajee.com/file-input

## Isolating the problem

- [ x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Noting a CSS fix to be done for such an exception case.

**Comment by aghausman** [comment]
Has this been released yet?

**Comment by kartik-v** [comment]
Yes

**Comment by aghausman** [comment]
@kartik-v sorry mate I'm using 5.2.7 from npm and still having the same issue.

**Comment by kartik-v** [comment]
Hi cannot reproduce the error. Can you check if its not a local browser caching issue at your end (clean up browser cache and restart and retry).

**Comment by ferdossi** [comment]
Hi, that is what I just did, tried in incognito mode, and I can reproduce it.

**Comment by ferdossi** [comment]
Problem fixed, thanks
