### ISSUE TITLE
Validating image dimensions does not show error 

### ISSUE THREAD

**Issue by Anni-g** [kartik-v/bootstrap-fileinput#1783]
When I try to upload an image with larger or smaller dimensions than set in minImageWidth resp. minImageHeight the error container is shown but it's empty. This occurs on the plugin demos page as well (https://plugins.krajee.com/file-image-dimensions-demo)
If initial previews are present the error message gets shown twice. I tried to search fileinput.js but I'm not able to find the reason. Maybe you can help? Thank you!

**Comment by fabian-jg** [comment]
I'm experiencing the same problem.
