### ISSUE TITLE
Fix error docs to change icon

### ISSUE THREAD

**Issue by FrederickChan** [kartik-v/bootstrap-fileinput#1784]
I've been modifying my work and I realized that you had a incorrect doc after looking into fileinput.js

The problem:

https://plugins.krajee.com/file-input/plugin-options#layoutTemplates

```
   icon: '<span class="bi-file-earmark-fill kv-caption-icon"></span>',
    caption: '<input readonly class="file-caption-name form-control {class}">\n',
    btnDefault: '<button type="{type}" title="{title}" class="{css}"{status} {tabIndexConfig}>{icon}{label}</button>',
```

This part is not "icon" but "fileIcon".

According to your latest release on github, this should be changed to:

```
     layoutTemplates: {                         
                            fileIcon:  '<i class="fas fa-fish"></i>',     
```

**Comment by kartik-v** [comment]
Fixed in docs.
