### ISSUE TITLE
Add button to image viewer for rotation

### ISSUE THREAD

**Issue by gmisterk** [kartik-v/bootstrap-fileinput#1785]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by gmisterk** [comment]
Hi all,
How can i add a button to rotate image from viewer modal.
in top right corner of the modal, there are some button (fullscreen, close, etcc.)
I want to add a button to rotate image like this demo : http://jsfiddle.net/cumqod2n/

How can i do this ? any idea ?

ps:  otheractionbutton isn't good place to put this functionnaly, i prefere to change header of the modal

Regards

**Comment by gmisterk** [comment]
ok, it's solved 👍 

step 1 : add css rules in fileinput.css 

   img {
    transform-origin: top left; /* IE 10+, Firefox, etc. */
    -webkit-transform-origin: top left; /* Chrome */
    -ms-transform-origin: top left; /* IE 9 */
}
img.rotate90 {
    transform: rotate(90deg) translateY(-100%);
    -webkit-transform: rotate(90deg) translateY(-100%);
    -ms-transform: rotate(90deg) translateY(-100%);
}
img.rotate180 {
    transform: rotate(180deg) translate(-100%,-100%);
    -webkit-transform: rotate(180deg) translate(-100%,-100%);
    -ms-transform: rotate(180deg) translateX(-100%,-100%);
}
img.rotate270 {
    transform: rotate(270deg) translateX(-100%);
    -webkit-transform: rotate(270deg) translateX(-100%);
    -ms-transform: rotate(270deg) translateX(-100%);
}




line 1735 update : 
'      <div class="kv-zoom-actions">{toggleRotate}{toggleheader}{fullscreen}{borderless}{close}</div>\n' +                               


line 2847 add:  

'toggleRotate': self._getZoomButton('toggleRotate'),

line 3046 add :

self._handler($modal.find('.btn-kv-toggleRotate'), 'click', function () {                      
            angle = (angle + 90) % 360;
                                       
                    $('.file-zoom-detail').removeClass("rotate90 rotate180 rotate270");
                    $('.file-zoom-detail').addClass("rotate" + angle);
                    
                   
            });


line 6103 add: 
toggleRotate: '<i class="bi-arrow-counterclockwise"></i>',

line 6113 add:    
toggleRotate: defBtnCss1,
			
and rotation of image will work nice.

regards

**Comment by kartik-v** [comment]
New enhancement added above to include IMAGE ROTATE ICON BUTTON in thumbnail and preview. New property `rotatableFileExtensions` also available.
