### ISSUE TITLE
maxFileCount setting is not respected unless page is refreshed after the upload

### ISSUE THREAD

**Issue by Gritmatch** [kartik-v/bootstrap-fileinput#1789]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Set maxFileCount: 5 and msgTotalFilesTooMany: 'Maximum number of files is 5.',
2. Upload 1 file. Once upload is completed, refresh the page.
3. Upload another 2 files and **do not refresh the page**.
4. Upload 3 more files.

## Expected behavior and actual behavior

When I upload 3 additional files in step 4, I expect to receive error message 'Maximum number of files is 5.' Instead I see that all the files are being uploaded and the total file count after step 4 is 6 files.

Note that maxFileCount setting is triggered in step 4, if I refresh the page in step 2.

Is there a way for the plugin to respect maxFileCount setting without having to refresh the page after each upload?

## Environment

Browsers

- [ X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [X ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: 5.2.8

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
> Is there a way for the plugin to respect maxFileCount setting without having to refresh the page after each upload?

You need to do the following to achieve your use case:

1. Set `validateInitialCount` property to `true`
2. Your upload server script must return the `initialPreview` and `initialPreviewConfig` for every upload - [check ajax demo 4](https://plugins.krajee.com/file-input-ajax-demo/4) to understand this.

**Comment by Gritmatch** [comment]
Thank you for pointing that out.
I had both initialPreview and initialPreviewConfig  at some point, but then in my infinite wisdom I renamed them to follow naming convention used for other object properties. Renamed these back to initialPreview and initialPreviewConfig. Everything works as expected :)
