### ISSUE TITLE
Preview does not render content of autorenamed file

### ISSUE THREAD

**Issue by PhantomLord72** [kartik-v/bootstrap-fileinput#1793]
This is a great enhancement. however it does not work yet completely:
On the current branch (downloaded yesterday)
during initialization I've added: previewFileType: 'any'

click on browse button, choose a pdf file without extension
Effect:
![image](https://user-images.githubusercontent.com/44055542/174562601-741a9e82-8530-43cd-b4fc-d115140fdee4.png)

In the preview pane, the name of the file is updated correctly (file was ___aaaa, after is ___aaaa.pdf), but the icon is yet binary text (%PDF-1.6%????....); the file name on the footer also is not updated, maybe by design.
There is a way to update the icon with the rendered content of PDFs?

_Originally posted by @PhantomLord72 in https://github.com/kartik-v/bootstrap-fileinput/issues/1792#issuecomment-1160002277_

**Comment by kartik-v** [comment]
Hi - file mime type parsing based on contents is typically recommended to be server focused activity to ensure its more accurate. So to ideally achieve the right previews you must parse th

Having said that, this new enhancement already offers detection of many of the most probable set of mime types to be detected from the CLIENT SIDE itself. PDF also is detected for most cases as tested using this plugin - so would suggest you try and test with various files and let know (as I could not reproduce issues so far).

However, note that content previews will still not be available for all files. Note that the plugin also has a property [`maxFilePreviewSize`](https://plugins.krajee.com/file-input/plugin-options#maxFilePreviewSize). This is set by default to `25600` (`25 MB`) - so files greater than this size will not be previewed (setting this to a meaningful size will be important to ensure the right performance on your client - else it will slow down your client file selection activities if this size is increased).

**Comment by PhantomLord72** [comment]
ok, however this is te configuration:
```
$("#test-upload").fileinput({
                    theme: 'fas',
                    previewFileType: 'any',
                    autoRenameExtension: true,
                    uploadUrl: 'Upload.aspx',
                    uploadAsync: true,
                    uploadExtraData: function (previewId, index) {
                        return {
                            fileName: name,
                            fileExtension: fileExtension
                        }
                    },
                    language: 'it',
                    maxFilesNum: 1,
                    removeClass: "btn btn-primary",
                    uploadClass: "btn btn-primary",
                    showBrowse: false,
                    browseOnZoneClick: true,
                    elErrorContainer: '#errorBlock',
                    previewZoomButtonClasses: {
                        prev: 'btn btn-navigate',
                        next: 'btn btn-navigate',
                        toggleheader: 'btn btn-kv btn-default btn-outline-primary',
                        fullscreen: 'btn btn-kv btn-default btn-outline-primary',
                        borderless: 'btn btn-kv btn-default btn-outline-primary',
                        close: 'btn btn-kv btn-default btn-outline-primary'
                    }
                });
```

**Comment by PhantomLord72** [comment]
Chrome is the latest. If I rename the same file on file system, adding
".pdf", it is rendered correctly.

Il Mar 21 Giu 2022, 03:19 Kartik Visweswaran ***@***.***> ha
scritto:
