### ISSUE TITLE
Drag & drop files only! 1 folder(s) dropped were skipped

### ISSUE THREAD

**Issue by nstrain17** [kartik-v/bootstrap-fileinput#1794]
Hello

Im having an intermittent issue where users are getting a “Drag & drop files only! 1 folder(s) dropped were skipped.” error when trying to upload files via the drag and drop. Immediately after the error the user can do a refresh, re-upload the file and it works fine. So I know the error is not related to the file itself.

The plugin has been added to a c# mvc application and i have the most recent version of the plugin. I can't find any pattern to why ones are failing. The users have tried chrome and edge and still get the issue. I have checked server logs when one fails for any information but there were no errors.

I posted this question on http://webtips.krajee.com/questions as i know i don't have much information to go on and wouldn't be meeting the prerequisites for github but i haven't had any help. 

Would you be able to offer any suggestions ?

**Comment by kartik-v** [comment]
Folders drag and drop is available only with ajax uploads - with a valid `uploadUrl` - else you will get this error if you are trying to drag and drop folders for normal native FILE INPUT upload.
