### ISSUE TITLE
Office preview not available

### ISSUE THREAD

**Issue by PhantomLord72** [kartik-v/bootstrap-fileinput#1798]
Excel,  word and Ms office doc preview is available and supported only for files uploaded to server and which you set via initialPreview.. You need to program and code your app accordingly. Read docs and examples to understand what is supported when.

_Originally posted by @kartik-v in https://github.com/kartik-v/bootstrap-fileinput/issues/1097#issuecomment-495558769_

Why images and Pdf's can have a preview and office documents not?

**Comment by kartik-v** [comment]
They need a special viewer which cannot be read by javascript. The special viewers can only read public files on cloud not on local

**Comment by kartik-v** [comment]
These files above (like office etc.) need a special third party viewers and cannot be natively previewed by browser. These special viewers can only read public files on cloud not on local
