### ISSUE TITLE
Upload any DWG file

### ISSUE THREAD

**Issue by Krakozaber** [kartik-v/bootstrap-fileinput#1804]
## Steps to reproduce the issue

1. Upload any DWG file

## Expected behavior and actual behavior

```
VM82:11 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substring')
    at Object.getMimeType (<anonymous>:11:9094)
    at m (<anonymous>:11:116558)
    at <anonymous>:11:117542
```

## Environment

Browsers

- Google Chrome
- Firefox

Operating System

-  Windows

## Libraries

- kartik-v/yii2-widget-fileinput: 1.1.1
- kartik-v/bootstrap-fileinput: 5.5.0
- bootstrap: 5.1.3
- jQuery: 3.6.0

## P.S.

This is repeated on the demo page of the plugin, on all layouts. 
Everything works perfectly on Linux.

If set 'autoFileTypeParsing' => false all works

**Comment by kartik-v** [comment]
Load the plugins `buffer.min.js` and `filetype.min.js` as described in docs with release v5.5.0 & v5.5.1 to get advanced file type parsing.
