### ISSUE TITLE
File Upload Preview for HEIC files fail on Chrome

### ISSUE THREAD

**Issue by jonmchan** [kartik-v/bootstrap-fileinput#1805]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. With a fileinput with image preview enabled:
```
$("#input-id").fileinput({
      'showUpload':true, 
      'previewFileType':'images',
      'overwriteInitial': false,
      'append': true,
      maxFileCount: 50,
      maxFileSize: 15000,
      initialPreviewAsData: false,
      allowedFileTypes: ['image'],    // allow only images
      showCancel: true,
      showUpload: false,
      showRemove: false,
      fileActionSettings: {
        showDrag: false,
      },
      overwriteInitial: false,
      otherActionButtons: btns,
    });
```

3. On chrome, drags a HEIC image into the upload area.

## Expected behavior and actual behavior

When I follow those steps, I see...

4. The heic preview image does not display correctly.

![image](https://user-images.githubusercontent.com/1827190/178423037-de4fb64e-ec94-4072-bc97-243911eb81b6.png)

I was expecting...

The preview to render correctly.

## Environment

Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] Mobile

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by Krakozaber** [comment]
I suspect that the reason is the same #1804
