### ISSUE TITLE
errors in example code

### ISSUE THREAD

**Issue by Jannik44** [kartik-v/bootstrap-fileinput#1806]
Hello, i have read the documentation and copied the example code but in the server side version are errors in the php code

1 syntax error on line 75 ( this: } )
2 times undefined function (validate token, generate Thumbnail)
what can i do?
![php](https://user-images.githubusercontent.com/76906033/178506282-f1b0dd02-0d58-4866-9dd8-d68d472d63f3.png)

**Comment by kartik-v** [comment]
This is more a programming design and consideration at your end. You need to create and write the server code for your use case. Examples only focus on the core upload process from the plugin. In the examples above provided, the `validateToken` or `generateThumbnail` are methods you need to evaluate and write (for upload authentication or generating thumbnails - and if you do not need them for your use case - you can eliminate these).
