### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by Jannik44** [kartik-v/bootstrap-fileinput#1807]
Hello, after reading the documentation i dont know how to make the server side php, this wasnt talked about, the frontend doesnt seem to work too, it allows multiple fileinputs, (i set this to false) and the spinner keeps spinning no file is arriving at the server
i followed the documentary step by step but after an hour of reading i couldnt complete the php
my php code is as follows: 
<?php
header('Content-Type: application/json');
$fl = $_FILES['fl'];
?>
thats it i dont know what to do to get it working, also the example script contains errors

![file](https://user-images.githubusercontent.com/76906033/178514979-d353d9b3-8ca3-4338-b3c8-663d10ab73fb.png)

my html isnt working as expected, what am i doing wrong?

`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <title></title>

  
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css" crossorigin="anonymous">

<link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />

<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/buffer.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/filetype.min.js" type="text/javascript"></script>

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/piexif.min.js" type="text/javascript"></script>

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/sortable.min.js" type="text/javascript"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/fileinput.min.js"></script>

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/locales/de.js"></script>
</head>
<body>

<div class="w-50">
<input type="file" id="input-id" name="fl"multiple>
</div>
    <script>
    $('document').on('ready', function() {
        $("#input-id").fileinput({
            uploadUrl: "http://localhost/file-upload.php",
            enableResumableUpload: false,
            resumableUploadOptions: {
            },
            uploadExtraData: {
                //'uploadToken': 'SOME-TOKEN', // for access control / security 
            },
            maxFileCount: 1,
            allowedFileExtensions:['zip'],
            showCancel: true,
            initialPreviewAsData: true,
            overwriteInitial: false,
            theme: 'fa5',
            uploadAsync: true,
            deleteUrl: "http://localhost/file-delete.php"
        }).on('fileuploaded', function(event, previewId, index, fileId) {
            console.log('File Uploaded', 'ID: ' + fileId + ', Thumb ID: ' + previewId);
        }).on('fileuploaderror', function(event, data, msg) {
            console.log('File Upload Error', 'ID: ' + data.fileId + ', Thumb ID: ' + data.previewId);
        }).on('filebatchuploadcomplete', function(event, preview, config, tags, extraData) {
            console.log('File Batch Uploaded', preview, config, tags, extraData);
        });
    });
    </script>
<script>
$(document).ready(function() {
    // initialize with defaults
    $("#input-id").fileinput();

    // with plugin options
    $("#input-id").fileinput({'uploadUrl': '/path/to/your-upload-api', 'previewFileType': 'any'});
});
</script>

</body>
</html>
![fil](https://user-images.githubusercontent.com/76906033/178515811-3abf5211-7b5d-46b4-b485-4292df358fdd.png)
`

**Comment by hide9527** [comment]
try like this:
fileinput.js => find:  getMimeType: function (signature, contents, type) => add at the beginning: return signature === undefined && 'application/text-plain';

**Comment by hide9527** [comment]
try like this:
fileinput.js => find: getMimeType: function (signature, contents, type) => add at the beginning:`            if (signature === undefined) {
                return contents && !contents.match(
                    /[^\u0000-\u007f]/) ? 'application/text-plain' : type;
            }`

**Comment by Krakozaber** [comment]
#1804

**Comment by kartik-v** [comment]
Load the plugins `buffer.min.js` and `filetype.min.js` with release v5.5.0 & v5.5.1 to get advanced file type parsing.
