### ISSUE TITLE
Sass Invalid Parent Selector npmjs release

### ISSUE THREAD

**Issue by Banner-Keith** [kartik-v/bootstrap-fileinput#1808]
This is a pretty simple one so I'll keep it short. 

We ran into an issue with sass.

Looks like it's already been fixed in #1802 

In our workflow we consume the sass directly rather than the css as we do some overrides.

Will there be a 5.5.1 release to push that change out?

**Comment by kartik-v** [comment]
Thanks for the update. This will be released soon.

**Comment by kartik-v** [comment]
This is done.
