### ISSUE TITLE
Processing bug with CDN and local files

### ISSUE THREAD

**Issue by EnzoRimapa** [kartik-v/bootstrap-fileinput#1810]
When loading some images or .txt text files I get errors like this:
int32_be is not defined,
but if I load the files locally .zip or npm everything works perfectly, why is this?

**Comment by gerayking** [comment]
I also meet same problem.

**Comment by kartik-v** [comment]
As mentioned in #1809.

With the latest release 5.5.0 and above --- for advanced mime type parsing... you need to load *buffer.min.js* and *filetype.min.js* before fileinput.js .... Refer [USAGE SECTION](https://plugins.krajee.com/file-input#usage-step-1).

```html
<!-- buffer.min.js and filetype.min.js are necessary in the order listed for advanced mime type parsing and more correct
     preview. This is a feature available since v5.5.0 and is needed if you want to ensure file mime type is parsed 
     correctly even if the local file's extension is named incorrectly. This will ensure more correct preview of the
     selected file (note: this will involve a small processing overhead in scanning of file contents locally). If you 
     do not load these scripts then the mime type parsing will largely be derived using the extension in the filename
     and some basic file content parsing signatures. -->
<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/buffer.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/filetype.min.js" type="text/javascript"></script>
```

**Comment by kartik-v** [comment]
Duplicate to #1809.

**Comment by kartik-v** [comment]
This issue is probably because you have not loaded *buffer.min.js* and *filetype.min.js* on your page (NEW feature since v5.5.0 for advanced file parsing). This is as mentioned in the [USAGE SECTION](https://plugins.krajee.com/file-input#usage-step-1). 

If its other issue as mentioned in #1809 - it needs to be verified. Currently closing this.

```js
<!-- buffer.min.js and filetype.min.js are necessary in the order listed for advanced mime type parsing and more correct
     preview. This is a feature available since v5.5.0 and is needed if you want to ensure file mime type is parsed 
     correctly even if the local file's extension is named incorrectly. This will ensure more correct preview of the
     selected file (note: this will involve a small processing overhead in scanning of file contents locally). If you 
     do not load these scripts then the mime type parsing will largely be derived using the extension in the filename
     and some basic file content parsing signatures. -->
<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/buffer.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/filetype.min.js" type="text/javascript"></script>
```

**Comment by EnzoRimapa** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" crossorigin="anonymous">
 

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css" crossorigin="anonymous">
 


 

<link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
 


 

<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
 

     <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/buffer.min.js" type="text/javascript"></script>
     <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/filetype.min.js" type="text/javascript"></script>
 

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/piexif.min.js" type="text/javascript"></script>
 

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/sortable.min.js" type="text/javascript"></script>
 

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
 

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/fileinput.min.js"></script>
 


 

<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/locales/LANG.js"></script>
</head>
<body>
    <input id="input-id" type="file" class="file" data-preview-file-type="text">

</body>
</html>`

@kartik-v this is the code used for the example copied from official documentation.

![image](https://user-images.githubusercontent.com/43084466/184673450-dd35eb3e-cdc3-4483-a1df-87b4c7f49c10.png)
error message when uploading a text file

**Comment by kartik-v** [comment]
This is showing another error now (you need to check if the files are properly loaded).

Check [this demo for advanced 11](https://plugins.krajee.com/file-advanced-usage-demo#advanced-example-11) and try to select/drag/upload your text/png files and let know. You can see that buffer.min.js and filetype.min.js are both loaded on the page.

**Comment by EnzoRimapa** [comment]
![image](https://user-images.githubusercontent.com/43084466/184687847-eb8ecd2e-ff77-4b8e-8bbb-910c9453ee80.png)

I loaded the code from advanced example 11 but it keeps throwing me this error.
As I said, the links of the libraries are those of the official page in the same order that they are found.

![image](https://user-images.githubusercontent.com/43084466/184688155-debc63a3-a63d-4ddc-be56-9435307f0417.png)

**Comment by kartik-v** [comment]
Take the latest code from the repo dev-master and retry and let know.

**Comment by owenworktest** [comment]
English is not my native language; please excuse typing errors.
----------------------------
I also meet same problem.
![image](https://user-images.githubusercontent.com/29450174/185053473-319fa669-be9a-4cb9-b3c1-6c626ac8dab5.png)
In example 1， it's not work.
https://jsfiddle.net/pznvhdko/
-----------------------------
In example 2， it's  work.
https://jsfiddle.net/s09p5dwL/
![image](https://user-images.githubusercontent.com/29450174/185053949-8a272556-c30e-4f8b-b0a4-70081b686ec3.png)

in example 2，i was not load filetype.min.js
This is my upload test file.
![螢幕擷取畫面 2022-08-15 150757](https://user-images.githubusercontent.com/29450174/185055345-fd1ae26e-fe56-43cb-96ba-55c78e49ad4d.png)
![螢幕擷取畫面 2022-08-15 151821](https://user-images.githubusercontent.com/29450174/185055351-060afba8-c148-4b86-ae10-a71b6fb8a374.png)
![螢幕擷取畫面 2022-08-15 152006](https://user-images.githubusercontent.com/29450174/185055355-fb9cbf52-28ac-4d16-849c-5cf397724796.png)

any suggestions?

**Comment by kartik-v** [comment]
I think there is a problem with an incorrect minified file (*filetype.min.js*) uploaded on CDN  -- the *filetype.js* file from CDN works fine -- check this updated fiddle ... https://jsfiddle.net/0Lvrxm12/ where I have corrected it.

I will try to get in a new version 5.5.1 on CDN soon with the updated correct *filetype.min.js* which should resolve this... Currently you can use *filetype.js* from the CDN for 5.5.0.

**Comment by owenworktest** [comment]
Thank you for the fix! 
It work!
