### ISSUE TITLE
About deleting files

### ISSUE THREAD

**Issue by Lowell-liu** [kartik-v/bootstrap-fileinput#1811]
## Steps to reproduce the issue

1. I want to delete an uploaded file, but nothing happens. I am using 'filebeforedelete'. I found that the url parameter must be passed for this event to take effect. Is it possible to cancel the verification of the url.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

Operating System

- [x] Windows

Libraries

- jQuery version:1.12
- bootstrap-fileinput version: 5.2.8

**Comment by kartik-v** [comment]
You may want to check the docs on available plugin options.

To delete a file configure [deleteUrl](https://plugins.krajee.com/file-input/plugin-options#deleteUrl) to point to your server code api/url which can delete the selected file. This property can be overridden separately also for each file thumbnail by setting `initialPreviewConfig.url` property.
