### ISSUE TITLE
Intermittent missing files on server side

### ISSUE THREAD

**Issue by ajbeaven** [kartik-v/bootstrap-fileinput#1813]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Options used when initialising fileinput

```
{
  frameClass: 'my-default',
  language: Globalize.locale().locale,
  layoutTemplates: {
    footer: ''
  },
  browseIcon: '<i class="glyphicon glyphicon-folder-open"></i>&nbsp;',
  removeIcon: '<i class="glyphicon glyphicon-trash"></i>&nbsp;',
  previewSettings: {
    image: { 'max-width': '200px', 'max-height': '150px' },
    video: { width: '50%', height: 'auto' }
  },
  showCancel: false,
  showClose: false,
  msgErrorClass: 'bootstrap-fileinput-error',
  msgValidationErrorClass: 'bootstrap-fileinput-error',
  msgValidationErrorIcon: '',
  errorCloseButton: '',
}
```

## Steps to reproduce the issue

Note: I'm using Form Submission mode.

1. Select multiple images
2. Submit form
3. Inspect files visible to server

## Expected behavior and actual behavior

When I follow those steps, occassionally it appears that I despite the preview showing 3 images, only 1 or 2 files are received by the server. Backend is .NET 6 on MVC framework.

I was expecting that any file showing in the preview would be sent through to the server. The `filesloaded` event is fired before the form is submitted and each file uploaded fires the `fileloaded` event. I've never been able to reproduce this issue at all so I'm relying on user reports and some logging I've just set up. From what I can tell, it occurs pretty frequently.

One user said this happens maybe 1 in every 5 times he attempts to upload something. That particular user clicks on the browse button and selects files rather than dragging them in. They said often when this happens it takes a bit longer than normal to complete the request, so maybe they're bigger files. I've tried to reproduce this using the same files they uploaded and everything worked fine.

This doesn't really feel like a clientside issue to be fair (particularly because no one has mentioned here that I can tell. I just wanted to get this issue out there on the off chance that a) you might know of something that could cause this and b) in case others are experiencing this.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version: 3.6.0
- bootstrap-fileinput version: 5.5.0 and also occurred on 4.5.3

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Note that in Form Submission Mode - the plugin functionality of sending files to server is LIMITED to and very similar to a NATIVE HTML file input. So you need to check both your frontend/backend code correctly on how you are reading files on the server. I assume there could be issues there (you maybe trying to read files partially - whereas native file input does not allow you to partially select or delete selected files locally and always sends selected files in one batch)

Refer the comparison of [Form Submission vs AJAX modes here](https://plugins.krajee.com/file-input#modes-compared).

Check your server code on how files are read and processed. To test and debug your issue - recommend to setup a NATIVE FILE INPUT and see if all files you select on client are being read on the server each time and then compare with the plugin usage in FORM SUBMISSION mode.

**Comment by ajbeaven** [comment]
I hear you - I just find it quite strange that it's intermittent and works most of the time. The files are received and read the standard .NET6 MVC way where it modelbinds to a List<IFormFile> to support multiple uploaded files.

So just to confirm, your control just proxies the click from the 'browse' button click to the hidden file input which opens the OS file selector. Your control's preview is then populated by extracting the selected files using the File API (e.g. FileList) right? If that's the case and it's exclusively reading from FileList, then yeah definitely sounds like a server thing. 

I'll take another look, thanks!
