### ISSUE TITLE
Selecting multiple images: ReferenceError: altId is not defined

### ISSUE THREAD

**Issue by SolidGlenn** [kartik-v/bootstrap-fileinput#1814]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Press the 'Browse button'
2. Select 2 or more images in the file pop-up
3. Submit the file pop-up

## Expected behavior and actual behavior

When I follow those steps, I see...
> One image being shown, a spinner, '1 of 3 uploaded, 33% ..." 
> An  error in the console stating altId is not defined 
```
Uncaught ReferenceError: altId is not defined
    at Object.exists (fileinput.min.js:11:20828)
    at Object.isPending (fileinput.min.js:11:21933)
    at Object.<anonymous> (fileinput.min.js:11:22037)
    at Function.each (jquery.js:391:1)
    at Object.isProcessed (fileinput.min.js:11:22001)
    at w (fileinput.min.js:13:10361)
    at fileinput.min.js:13:11735
```

I was expecting...
All files to be shown

## Environment

Browsers

- [x] Google Chrome
- [x] Brave
- [x] Edge
- [x] Mozilla Firefox
- [ ] Internet Explorer (not tested)
- [ ] Safari (not tested)

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.6.0
- bootstrap-fileinput version: 5.5.0

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Seems some issue with outdated code ... please upgrade to v5.5.1 and let know as the `altid` does not exist in current codebase to reproduce.
