### ISSUE TITLE
multiple inputs on the same page, the drag and drop updates both

### ISSUE THREAD

**Issue by codedprodotcom** [kartik-v/bootstrap-fileinput#1820]
## Steps to reproduce the issue

1. put 2 inputs on the same page
2. initialize them through javascript on load
3. drag and drop in 1

## Expected behavior and actual behavior

When I follow those steps it updates both previews and on save it actually overrides the name but doesn't actually upload

## Environment

Browsers
- [ ] Mozilla Firefox

Operating System

- [ ] Mac OS X

Libraries

- jQuery version: latest
- bootstrap-fileinput version: latest

**Comment by kartik-v** [comment]
Check your app program/code ... you need to have unique file input id attribute... check the demos pages where multiple inputs are displayed on the same page and works fine.
