### ISSUE TITLE
MP3 upload not working, shows spinning wheel, throws js errors

### ISSUE THREAD

**Issue by gb5256** [kartik-v/bootstrap-fileinput#1822]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Go the demo page of Kartik
2. Upload a MP3
3.

## Expected behavior and actual behavior

When I follow those steps, I see a spinning wheel without any preview.
Console in browser throws errors (see screenshot below).

I was expecting, seeing a file-icon as generic preview item

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/324658/195298596-ad052dee-2103-48a4-96e8-8e11fcaf4453.png">

**Comment by kartik-v** [comment]
Which demo link are you using to test this?

**Comment by gb5256** [comment]
Hi,
MP3 seems to work now. But the .tiff is still throwing errors. See below:
![image](https://user-images.githubusercontent.com/324658/195519975-123d6500-36cf-4107-a0e2-21ae70004519.jpeg)

**Comment by kartik-v** [comment]
Please share the TIFF file you are using? Unable to reproduce with TIFF FILES here.

**Comment by gb5256** [comment]
This is the file.
I had to zip it as github would not allow uploading a tiff:
[image_sample.tiff.zip](https://github.com/kartik-v/bootstrap-fileinput/files/9771686/image_sample.tiff.zip)

**Comment by kartik-v** [comment]
Fix provided with the latest dev-master update.
