### ISSUE TITLE
$modal.modal is not a function  bootstrap v5.x on show preview.

### ISSUE THREAD

**Issue by peter-fan-cn** [kartik-v/bootstrap-fileinput#1823]
https://github.com/kartik-v/bootstrap-fileinput/blob/35c29cd9fd5bc47eae5238feaabee95b2d7efe3c/js/fileinput.js#L3176

* "bootstrap-fileinput": "^5.5.1",
* "jquery": "^3.6.1"
* "bootstrap": "^5.2.2",
* "@popperjs/core": "^2.11.6",

can be changed to `$modal.show()`

```
fileinput.js:3175 Uncaught TypeError: $modal.modal is not a function
    at FileInput._showModal (fileinput.js:3175:20)
    at FileInput._zoomPreview (fileinput.js:3185:18)
    at HTMLButtonElement.<anonymous> (fileinput.js:3233:26)
    at HTMLButtonElement.dispatch (jquery.js:5430:27)
    at elemData.handle (jquery.js:5234:28)
```

**Comment by kartik-v** [comment]
You need to load bootstrap 5.x bundle JS (bootstrap.bundle.js including popper) before fileinput.js.

**Comment by peter-fan-cn** [comment]
see: https://getbootstrap.com/docs/5.2/components/modal/#methods

bootstrap v5.x no longer have the `modal` method.

**Comment by kartik-v** [comment]
The `modal` method is available and will be used if you use JQUERY.

You need to load the right assets and JS. Follow the steps to load all assets and css / js scripts required in the right order as mentioned in the [plugin usage section](https://plugins.krajee.com/file-input#usage-step-1). 

You can cross check the plugin demos and see that the modal works fine there.

**Comment by peter-fan-cn** [comment]
I am using Vite to load libraries.

load all in same file,  it not works.
app.js
```javascript
import jQuery from 'jquery';
window.jQuery = jQuery;
window.$ = jQuery;


import * as bootstrap from 'bootstrap'
window.bootstrap = bootstrap;
```
split into two files, it does work.

bootstrap.js
```javascript
// jquery
import jQuery from 'jquery';
window.jQuery = jQuery;
window.$ = jQuery;
```

app.js
```javascript
import './bootstrap';

// bootstrap js
import * as bootstrap from 'bootstrap'
window.bootstrap = bootstrap;
```

Thank you for help.
