### ISSUE TITLE
https://plugins.krajee.com/file-input/plugin-events   link error

### ISSUE THREAD

**Issue by tintucthethao** [kartik-v/bootstrap-fileinput#1839]
![Screenshot_11](https://user-images.githubusercontent.com/97772006/230784859-e48a6880-19a3-4515-9666-cb6107ca5aa4.png)

**Comment by maotou316** [comment]
+1

**Comment by kartik-v** [comment]
Thanks for the report. Site is down due to some hosting provider issues. Will check and get this back online.
