### ISSUE TITLE
Language is not loaded

### ISSUE THREAD

**Issue by ProjectLinde37** [kartik-v/bootstrap-fileinput#1841]
Problem still not seems solved in latest version

Loaded following files :
`<script type='text/javascript' src='assets/bootstrap-fileinput/5.5.3/js/plugins/buffer.min.js' ></script>
<script type='text/javascript' src='assets/bootstrap-fileinput/5.5.3/js/plugins/filetype.min.js' ></script>
<script type='text/javascript' src='assets/bootstrap-fileinput/5.5.3/js/fileinput.min.js' ></script>
<script type='text/javascript' src='assets/bootstrap-fileinput/5.5.3/themes/bs5/theme.min.js'></script>
<script type='text/javascript' src='assets/bootstrap-fileinput/5.5.3/js/locales/nl.js></script>`

And have the input configured
`$(document).ready(function() {
$('#DOCUMENT').fileinput({
language:'nl',
'showUpload': false,
'previewFileType': 'any',
// custom button icons
});
});`

**Comment by TeoMastro** [comment]
In my case, the way our company project is constructed we store the language and locale in Yii::$app->language (ex. 'el-GR' for greek). On Datepicker plugin the language value was automatically taken from the Yii::$app->language variable, but on the bootstrap-fileinput plugin I had to set the language by adding the property: 'language' => substr(Yii::$app->language, 0, 2) on the fileinput plugin properties so only the 'el' part was cosnidered as 'language' by the plugin. I hope this helps you identify and solve your problem.
