### ISSUE TITLE
showRemove:false in fileActionSettings doesn't work

### ISSUE THREAD

**Issue by bQt31** [kartik-v/bootstrap-fileinput#1844]
I've seen another thread talking about it, but I didn't find any solution and I'm pretty sure it's a bug. her is my full initialization:

> window.fileinputiser = function fileinputiser(elem){
    elem.fileinput({
        uploadUrl: elem.data('uploadurl')?elem.data('uploadurl'):'#',
        deleteUrl: elem.data('deleteurl')?elem.data('deleteurl'):'#',
        uploadExtraData: elem.data('uploadextradata')?elem.data('uploadextradata'):false,
        initialPreview: typeof initialPreview !== 'undefined' ? initialPreview : [],
        initialPreviewConfig: typeof initialPreviewConfig !== 'undefined' ? initialPreviewConfig : [],
        initialPreviewAsData: true,
        maxTotalFileCount: typeof elem.data('maxtotalfilecount') !== 'undefined' ? elem.data('maxtotalfilecount') : 0,
        maxFileCount: typeof elem.data('maxtotalfilecount') !== 'undefined' ? elem.data('maxtotalfilecount') : 0, 
        autoReplace: typeof elem.data('autoreplace') !== 'undefined' ? elem.data('autoreplace') : false,
        overwriteInitial: typeof elem.data('autoreplace') !== 'undefined' ? elem.data('autoreplace') : false,
        showUpload: false,
        showZoom: false,
        showCaption: false,
        showClose: false,
        showBrowse: typeof elem.data('showbrowse') !== 'undefined' ? JSON.parse(elem.data('showbrowse')) : false,
        showRemove: false,
        showProgress: false,
        showPause: false,
        showCancel: false,
        browseOnZoneClick: true,
        browseClass: "btn btn-primary",
        msgProcessing : "Chargement en cours",
        browseLabel: "Remplacer",
        language: 'fr',
        allowedFileTypes: elem.data('allowedfiletypes')?elem.data('allowedfiletypes'):null,
        fileActionSettings :{
            showZoom: false,
            showRotate: typeof elem.data('showrotate') !== 'undefined' ? JSON.parse(elem.data('showrotate')) : false,
            showRemove: typeof elem.data('showremove') !== 'undefined' ? JSON.parse(elem.data('showremove')) : true,
            showClose: false,
            removeIcon: "<i class='fa fa-times'></i>",
            rotateIcon: "<i class='fa fa-repeat'></i>",
            downloadIcon: '<i class="fa fa-download"></i>',
            uploadIcon: '<i class="fa fa-upload"></i>',
            uploadRetryIcon: '<i class="fa fa-upload"></i>',
        }
    });

**Comment by kartik-v** [comment]
Retry this with v 5.5.4 and let know.
