### ISSUE TITLE
is it possible to add  copy & paste

### ISSUE THREAD

**Issue by Hardcore-fs** [kartik-v/bootstrap-fileinput#1845]
Can you extend teh D&D to allow copy & paste into the same region.

sometimes,  we might want to be in a picture editor , select the picture , then use copy & paste into teh input box, instead ogf having to save the image out, then go to the file imput box to load it in.

**Comment by kartik-v** [comment]
This feature is been added. After copying files in your system - you need to highlight and paste in the filename caption input element.
