### ISSUE TITLE
Question: autocomplete on button?

### ISSUE THREAD

**Issue by goschtl** [kartik-v/bootstrap-fileinput#1847]
Hi,

i have a simple question about the autocomplete attribute in the **button-generation** function

            if (type === 'fullscreen' || type === 'borderless' || type === 'toggleheader') {
                params += ' data-toggle="button" aria-pressed="false" autocomplete="off"';
            }

Here our Screenread complains that autocomplete is not a valid attribute on the button elment.

https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js#L2881

Thanks
Christian

**Comment by kartik-v** [comment]
This attribute may not be needed for the button. Will check. Noting an enhancement.
