### ISSUE TITLE
maxFileSize does not work with file input [multiple] 

### ISSUE THREAD

**Issue by khallid-itdevtech** [kartik-v/bootstrap-fileinput#1849]
maxFileSize validation does not work when [multiple] attribute is added to file input.
maxFileSize only works with Single File not with multiple files.
I want to limit any files size to 25MB. it can be  10, 20 or N

**Comment by mrgarciamanuel** [comment]
Hi, i tried to fix your issue and i made pull request, Hope this helps. 

Hope the community approves.

**Comment by kartik-v** [comment]
Resolved via #1850.
