### ISSUE TITLE
How can i prevent clearing uploaded files?

### ISSUE THREAD

**Issue by sajjad-shirazy** [kartik-v/bootstrap-fileinput#185]
Hi Kartik,

something like "overwriteInitial: false" but "overwriteUploaded: false"

**Comment by kartik-v** [comment]
The uploaded files once uploaded are cleared from file input. 

Note that once uploaded these files will lose their original preview ids as well. So other than for display they have no meaning. Why would you want that instead of directly displaying a image link from your server?

**Comment by sajjad-shirazy** [comment]
i'm using your plugin as a gallery editor ... so i need to keep uploaded files in the gallery like initial preview items with ability to upload more items.
any idea?

**Comment by kartik-v** [comment]
I would suggest you to set `initialPreview` on `fileuploaded` or `fileuploadbatchsuccess` event and trigger `refresh` method.

**Comment by kartik-v** [comment]
I would suggest you to set `initialPreview` on `fileuploaded` or `filebatchuploadsuccess` event and trigger `refresh` method.

**Comment by kartik-v** [comment]
I would suggest you to set `initialPreview` & `initialPreviewConfig` on `fileuploaded` or `filebatchuploadsuccess` event and trigger `refresh` method of the plugin.

**Comment by kartik-v** [comment]
Track the enhancement being done in #205. With that enhancement, you can return an associative array object containing the new `initialPreview` and `initialPreviewConfig` via the events `filebatchuploadsuccess` and `filebatchuploadcomplete`.
