### ISSUE TITLE
Upload of small TIF file throws Unhandled Promise Rejection: Error: End-Of-Stream

### ISSUE THREAD

**Issue by gb5256** [kartik-v/bootstrap-fileinput#1855]
When I try to upload this file (I have zipped it, as TIF are not allowed here):
[image_sample.tiff.zip](https://github.com/kartik-v/bootstrap-fileinput/files/14208336/image_sample.tiff.zip)

Then I get the spinning wheel and a JS error for filetype.js:152
Unhandled Promise Rejection: Error: End-Of-Stream

The line 152 with the reported error is this:

class EndOfStreamError extends Error {
    constructor() {
        super(KrajeeFileTypeConfig.defaultMessages);
    }
}

**Comment by kartik-v** [comment]
Related to #1822 and fixed via the same.
