### ISSUE TITLE
5.5.3 fa6 buttons not showing

### ISSUE THREAD

**Issue by rllamocca** [kartik-v/bootstrap-fileinput#1858]
5.5.2 ok
![IMG-20240328-WA0009.jpg](https://github.com/kartik-v/bootstrap-fileinput/assets/38144149/910974ec-3f1c-4957-a1ae-ab056ad6f70e)

5.5.3 nok
![IMG-20240328-WA0010.jpg](https://github.com/kartik-v/bootstrap-fileinput/assets/38144149/ebddb3ef-02a6-4517-a0c4-631faad9fbc2)

additional
/themes/fa6/theme.css dont exists

**Comment by kartik-v** [comment]
It seems to work ok. Check if font awesome assets are loaded before on the page. There is no theme.css file in the FA6 theme. Its just the theme.js file (will be corrected in docs).

**Comment by rllamocca** [comment]
I copy and say goodbye to the thread.

From
https://plugins.krajee.com/file-theme-fa6-demo

5.5.2 OK
https://codi.link/PHNjcmlwdCBzcmM9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vanF1ZXJ5QDMuNy4xL2Rpc3QvanF1ZXJ5Lm1pbi5qcyI+PC9zY3JpcHQ+DQo8bGluayBocmVmPSJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2Jvb3RzdHJhcEA1LjMuMi9kaXN0L2Nzcy9ib290c3RyYXAubWluLmNzcyIgcmVsPSJzdHlsZXNoZWV0IiBpbnRlZ3JpdHk9InNoYTM4NC1UM2M2Q29JaTZ1THJBOVRuZU5Fb2E3UnhuYXR6amNEU0NtRzFNWHhTUjFHQXNYRVYvRHd3eWtjMk1QSzhNMkhOIiBjcm9zc29yaWdpbj0iYW5vbnltb3VzIj4gICAgDQo8c2NyaXB0IHNyYz0iaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9ib290c3RyYXBANS4zLjIvZGlzdC9qcy9ib290c3RyYXAuYnVuZGxlLm1pbi5qcyIgaW50ZWdyaXR5PSJzaGEzODQtQzZSenN5bk05a1dEck1OZVQ4N2JoOTVPR055WlBoY1ROWGoxTlc3UnVCQ3N5Ti9vMGpscGNWOFF5cTQ2Y0RmTCIgY3Jvc3NvcmlnaW49ImFub255bW91cyI+PC9zY3JpcHQ+DQo8IS0tIEZPTlQgQVdFU09NRSA2LlggVEhFTUUgKEJBU0lDKSAtLT4NCiANCjwhLS0gbG9hZCB0aGUgQ1NTIGZpbGVzIGluIHRoZSByaWdodCBvcmRlciAtLT4NCjxsaW5rIGhyZWY9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9naC9rYXJ0aWstdi9ib290c3RyYXAtZmlsZWlucHV0QDUuNS4yL2Nzcy9maWxlaW5wdXQubWluLmNzcyIgcmVsPSJzdHlsZXNoZWV0Ij4NCjxsaW5rIGhyZWY9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGZvcnRhd2Vzb21lL2ZvbnRhd2Vzb21lLWZyZWVANi4xLjEvY3NzL2FsbC5jc3MiIHJlbD0ic3R5bGVzaGVldCI+DQogDQo8IS0tIGxvYWQgdGhlIEpTIGZpbGVzIGluIHRoZSByaWdodCBvcmRlciAtLT4NCjxzY3JpcHQgc3JjPSJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvZ2gva2FydGlrLXYvYm9vdHN0cmFwLWZpbGVpbnB1dEA1LjUuMi9qcy9maWxlaW5wdXQuanMiPjwvc2NyaXB0Pg0KPHNjcmlwdCBzcmM9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9naC9rYXJ0aWstdi9ib290c3RyYXAtZmlsZWlucHV0QDUuNS4yL3RoZW1lcy9mYTYvdGhlbWUuanMiPjwvc2NyaXB0Pg0KDQo8ZGl2IGNsYXNzPSJmaWxlLWxvYWRpbmciPg0KICAgIDxpbnB1dCBpZD0iaW5wLXRoZW1lLWZhNi0xIiBuYW1lPSJpbnAtdGhlbWUtZmE2LTEiIHR5cGU9ImZpbGUiIG11bHRpcGxlIGFjY2VwdD0iaW1hZ2UiPg0KPC9kaXY+ICA=%7C%7CDQokKCIjaW5wLXRoZW1lLWZhNi0xIikuZmlsZWlucHV0KHsNCiAgICB0aGVtZTogImZhNiIsDQogICAgdXBsb2FkVXJsOiAiL2ZpbGUtdXBsb2FkLWJhdGNoLzIiLA0KICAgIGFsbG93ZWRGaWxlRXh0ZW5zaW9uczogWydqcGcnLCAncG5nJywgJ2dpZiddLA0KICAgIG92ZXJ3cml0ZUluaXRpYWw6IGZhbHNlLA0KICAgIGluaXRpYWxQcmV2aWV3QXNEYXRhOiB0cnVlLA0KICAgIG1heEZpbGVTaXplOiAxMDAwMCwNCiAgICByZW1vdmVGcm9tUHJldmlld09uRXJyb3I6IHRydWUsDQogICAgaW5pdGlhbFByZXZpZXc6IFsNCiAgICAgICAgImh0dHBzOi8vcGljc3VtLnBob3Rvcy9pZC8xMDEvMTkyMC8xMDgwIiwNCiAgICAgICAgImh0dHBzOi8vcGljc3VtLnBob3Rvcy9pZC8xMDIvMTkyMC8xMDgwIiwNCiAgICAgICAgImh0dHBzOi8vcGljc3VtLnBob3Rvcy9pZC8xMDMvMTkyMC8xMDgwIg0KICAgIF0sDQogICAgaW5pdGlhbFByZXZpZXdDb25maWc6IFsNCiAgICAgICAge2NhcHRpb246ICJwaWN0dXJlLTEuanBnIiwgZGVzY3JpcHRpb246ICI8aDU+UGljdHVyZSBPbmU8L2g1PiBUaGlzIGlzIGEgcmVwcmVzZW50YXRpdmUgcGxhY2Vob2xkZXIgZGVzY3JpcHRpb24gZm9yIHRoZSBmaXJzdCBpbWFnZS4iLCBzaXplOiAzMjk4OTIsIHdpZHRoOiAiMTIwcHgiLCB1cmw6ICIvc2l0ZS9maWxlLWRlbGV0ZSIsIGtleTogMTAxfSwNCiAgICAgICAge2NhcHRpb246ICJwaWN0dXJlLTIuanBnIiwgZGVzY3JpcHRpb246ICI8aDU+UGljdHVyZSBUd288L2g1PiBUaGlzIGlzIGEgcmVwcmVzZW50YXRpdmUgcGxhY2Vob2xkZXIgZGVzY3JpcHRpb24gZm9yIHRoZSBzZWNvbmQgaW1hZ2UuIiwgc2l6ZTogODcyMzc4LCB3aWR0aDogIjEyMHB4IiwgdXJsOiAiL3NpdGUvZmlsZS1kZWxldGUiLCBrZXk6IDEwMn0sDQogICAgICAgIHtjYXB0aW9uOiAicGljdHVyZS0zLmpwZyIsIGRlc2NyaXB0aW9uOiAiPGg1PlBpY3R1cmUgVGhyZWU8L2g1PiBUaGlzIGlzIGEgcmVwcmVzZW50YXRpdmUgcGxhY2Vob2xkZXIgZGVzY3JpcHRpb24gZm9yIHRoZSB0aGlyZCBpbWFnZS4iLCBzaXplOiA2MzI3NjIsIHdpZHRoOiAiMTIwcHgiLCB1cmw6ICIvc2l0ZS9maWxlLWRlbGV0ZSIsIGtleTogMTAzfQ0KICAgIF0sDQogICAgaW5pdGlhbFByZXZpZXdEb3dubG9hZFVybDogJ2h0dHBzOi8vcGljc3VtLnBob3Rvcy9pZC97a2V5fS8xOTIwLzEwODAnIC8vIHRoZSBrZXkgd2lsbCBiZSBkeW5hbWljYWxseSByZXBsYWNlZCAgDQp9KTs=

5.5.3 NOK
https://codi.link/PHNjcmlwdCBzcmM9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vanF1ZXJ5QDMuNy4xL2Rpc3QvanF1ZXJ5Lm1pbi5qcyI+PC9zY3JpcHQ+DQo8bGluayBocmVmPSJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2Jvb3RzdHJhcEA1LjMuMi9kaXN0L2Nzcy9ib290c3RyYXAubWluLmNzcyIgcmVsPSJzdHlsZXNoZWV0IiBpbnRlZ3JpdHk9InNoYTM4NC1UM2M2Q29JaTZ1THJBOVRuZU5Fb2E3UnhuYXR6amNEU0NtRzFNWHhTUjFHQXNYRVYvRHd3eWtjMk1QSzhNMkhOIiBjcm9zc29yaWdpbj0iYW5vbnltb3VzIj4gICAgDQo8c2NyaXB0IHNyYz0iaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9ib290c3RyYXBANS4zLjIvZGlzdC9qcy9ib290c3RyYXAuYnVuZGxlLm1pbi5qcyIgaW50ZWdyaXR5PSJzaGEzODQtQzZSenN5bk05a1dEck1OZVQ4N2JoOTVPR055WlBoY1ROWGoxTlc3UnVCQ3N5Ti9vMGpscGNWOFF5cTQ2Y0RmTCIgY3Jvc3NvcmlnaW49ImFub255bW91cyI+PC9zY3JpcHQ+DQo8IS0tIEZPTlQgQVdFU09NRSA2LlggVEhFTUUgKEJBU0lDKSAtLT4NCiANCjwhLS0gbG9hZCB0aGUgQ1NTIGZpbGVzIGluIHRoZSByaWdodCBvcmRlciAtLT4NCjxsaW5rIGhyZWY9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9naC9rYXJ0aWstdi9ib290c3RyYXAtZmlsZWlucHV0QDUuNS4zL2Nzcy9maWxlaW5wdXQubWluLmNzcyIgcmVsPSJzdHlsZXNoZWV0Ij4NCjxsaW5rIGhyZWY9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGZvcnRhd2Vzb21lL2ZvbnRhd2Vzb21lLWZyZWVANi4xLjEvY3NzL2FsbC5jc3MiIHJlbD0ic3R5bGVzaGVldCI+DQogDQo8IS0tIGxvYWQgdGhlIEpTIGZpbGVzIGluIHRoZSByaWdodCBvcmRlciAtLT4NCjxzY3JpcHQgc3JjPSJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvZ2gva2FydGlrLXYvYm9vdHN0cmFwLWZpbGVpbnB1dEA1LjUuMy9qcy9maWxlaW5wdXQuanMiPjwvc2NyaXB0Pg0KPHNjcmlwdCBzcmM9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9naC9rYXJ0aWstdi9ib290c3RyYXAtZmlsZWlucHV0QDUuNS4zL3RoZW1lcy9mYTYvdGhlbWUuanMiPjwvc2NyaXB0Pg0KDQo8ZGl2IGNsYXNzPSJmaWxlLWxvYWRpbmciPg0KICAgIDxpbnB1dCBpZD0iaW5wLXRoZW1lLWZhNi0xIiBuYW1lPSJpbnAtdGhlbWUtZmE2LTEiIHR5cGU9ImZpbGUiIG11bHRpcGxlIGFjY2VwdD0iaW1hZ2UiPg0KPC9kaXY+ICA=%7C%7CDQokKCIjaW5wLXRoZW1lLWZhNi0xIikuZmlsZWlucHV0KHsNCiAgICB0aGVtZTogImZhNiIsDQogICAgdXBsb2FkVXJsOiAiL2ZpbGUtdXBsb2FkLWJhdGNoLzIiLA0KICAgIGFsbG93ZWRGaWxlRXh0ZW5zaW9uczogWydqcGcnLCAncG5nJywgJ2dpZiddLA0KICAgIG92ZXJ3cml0ZUluaXRpYWw6IGZhbHNlLA0KICAgIGluaXRpYWxQcmV2aWV3QXNEYXRhOiB0cnVlLA0KICAgIG1heEZpbGVTaXplOiAxMDAwMCwNCiAgICByZW1vdmVGcm9tUHJldmlld09uRXJyb3I6IHRydWUsDQogICAgaW5pdGlhbFByZXZpZXc6IFsNCiAgICAgICAgImh0dHBzOi8vcGljc3VtLnBob3Rvcy9pZC8xMDEvMTkyMC8xMDgwIiwNCiAgICAgICAgImh0dHBzOi8vcGljc3VtLnBob3Rvcy9pZC8xMDIvMTkyMC8xMDgwIiwNCiAgICAgICAgImh0dHBzOi8vcGljc3VtLnBob3Rvcy9pZC8xMDMvMTkyMC8xMDgwIg0KICAgIF0sDQogICAgaW5pdGlhbFByZXZpZXdDb25maWc6IFsNCiAgICAgICAge2NhcHRpb246ICJwaWN0dXJlLTEuanBnIiwgZGVzY3JpcHRpb246ICI8aDU+UGljdHVyZSBPbmU8L2g1PiBUaGlzIGlzIGEgcmVwcmVzZW50YXRpdmUgcGxhY2Vob2xkZXIgZGVzY3JpcHRpb24gZm9yIHRoZSBmaXJzdCBpbWFnZS4iLCBzaXplOiAzMjk4OTIsIHdpZHRoOiAiMTIwcHgiLCB1cmw6ICIvc2l0ZS9maWxlLWRlbGV0ZSIsIGtleTogMTAxfSwNCiAgICAgICAge2NhcHRpb246ICJwaWN0dXJlLTIuanBnIiwgZGVzY3JpcHRpb246ICI8aDU+UGljdHVyZSBUd288L2g1PiBUaGlzIGlzIGEgcmVwcmVzZW50YXRpdmUgcGxhY2Vob2xkZXIgZGVzY3JpcHRpb24gZm9yIHRoZSBzZWNvbmQgaW1hZ2UuIiwgc2l6ZTogODcyMzc4LCB3aWR0aDogIjEyMHB4IiwgdXJsOiAiL3NpdGUvZmlsZS1kZWxldGUiLCBrZXk6IDEwMn0sDQogICAgICAgIHtjYXB0aW9uOiAicGljdHVyZS0zLmpwZyIsIGRlc2NyaXB0aW9uOiAiPGg1PlBpY3R1cmUgVGhyZWU8L2g1PiBUaGlzIGlzIGEgcmVwcmVzZW50YXRpdmUgcGxhY2Vob2xkZXIgZGVzY3JpcHRpb24gZm9yIHRoZSB0aGlyZCBpbWFnZS4iLCBzaXplOiA2MzI3NjIsIHdpZHRoOiAiMTIwcHgiLCB1cmw6ICIvc2l0ZS9maWxlLWRlbGV0ZSIsIGtleTogMTAzfQ0KICAgIF0sDQogICAgaW5pdGlhbFByZXZpZXdEb3dubG9hZFVybDogJ2h0dHBzOi8vcGljc3VtLnBob3Rvcy9pZC97a2V5fS8xOTIwLzEwODAnIC8vIHRoZSBrZXkgd2lsbCBiZSBkeW5hbWljYWxseSByZXBsYWNlZCAgDQp9KTs=

**Comment by kartik-v** [comment]
Hi - am able to see the icons fine in both the links you posted. Can you explain where is the issue?

**Comment by rllamocca** [comment]
![IMG-20240408-WA0001.jpg](https://github.com/kartik-v/bootstrap-fileinput/assets/38144149/3f1d6146-271f-48fc-a91d-5659bfe2ba9b)

![IMG-20240408-WA0002.jpg](https://github.com/kartik-v/bootstrap-fileinput/assets/38144149/7c8f3d85-6678-4c28-9ee2-60e6708ece78)

**Comment by kartik-v** [comment]
I can see that the icons in the modal dialog are not rendering - but the icons in the thumbnails are rendering fine. Will check this.

**Comment by kartik-v** [comment]
This has been fixed by the above commit. Check and let know.

**Comment by rllamocca** [comment]
5.5.4
looks good 👍
