### ISSUE TITLE
blank space on multiple upload preview

### ISSUE THREAD

**Issue by geocine** [kartik-v/bootstrap-fileinput#186]
@kartik-v  

is there a way to crop the preview images to make them the same sizes every time or at least resolve this blank space issue?

![](http://i.imgur.com/mHOMBWM.png)

**Comment by kartik-v** [comment]
It depends on the image dimensions and which you need to work with for your environment. You could try setting the `previewConfig` for each file type to set default dimensions in the preview. The default settings are to have a constant height for all images to ensure they align horizontally well while the width would be auto. Depending on your use case (you may need to adjust the height to something that should work for most cases).

**Comment by geocine** [comment]
As you can see yes the image previews on the first row have the same height (as you confirmed these have constant height)  . I wonder why there is a space on the second row those two images would still fit there. This is a screenshot from your demo page by the way.

Also I don't see a ``previewConfig`` anywhere on the documentation I just saw ``initialPreviewConfig`` . Could you give me a quick config snippet to set width preview to fixed.

**Comment by kartik-v** [comment]
Its a typo... I meant [previewSettings](http://plugins.krajee.com/file-input#option-previewsettings).
