### ISSUE TITLE
define a custom fileIcon

### ISSUE THREAD

**Issue by atmediauk** [kartik-v/bootstrap-fileinput#187]
Hello,

Just wondering if its possible to define the file icon which is displayed when a file is selected (I couldn't see an option in the docs)

Currently it sets ```glyphicon glyphicon-file kv-caption-icon``` on a span tag but I use font awesome was hoping to override this as can be done with the browse, remove and upload icons.

Many thanks

**Comment by kartik-v** [comment]
You can define your own templates in [previewTemplates](http://plugins.krajee.com/file-input#option-previewtemplates) for each file type.

**Comment by kartik-v** [comment]
The DEFAULT_PREVIEW constant variable in the templates translates to:
```html
<div class="file-preview-other">
    <i class="glyphicon glyphicon-file"></i>
</div>
```

**Comment by kartik-v** [comment]
I plan to create a configuration option for the icon -- will update.

**Comment by kartik-v** [comment]
There are two places where `glyphicon-file` are used in templates.

1. Within the file caption text prefixed before file name. You can set this using <b>layoutTemplates.icon</b> property

2. Within the preview section for an unreadable file type. You can set this using a new property added <b>previewFileIcon</b>.

**Comment by atmediauk** [comment]
Thats brilliant, thank you. WiIl have a go at this :)
