### ISSUE TITLE
Plugin localization didn't fallback to language if locale is specified

### ISSUE THREAD

**Issue by miketsoft** [kartik-v/bootstrap-fileinput#1874]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

We have a multi-language Yii2 application and use [FileInput](https://github.com/kartik-v/yii2-widget-fileinput) widget. But when the application language (locale to be more precise) `Yii::$app->language` is set, for example, to `uk-UA`, the plugin on the page is rendered with the default language (English).

While method `\kartik\base\BaseAssetBundle::addLanguage` attach to asset correct l10n file (`uk.js`), widget `\kartik\file\FileInput` register plugin with `"language": "uk-UA"`. So, variable `$.fn.fileinputLocales` has key `uk`, but the plugin requests `uk-UA` and fallbacks to `en`.

The same problem is described in [comment](https://github.com/kartik-v/bootstrap-fileinput/issues/1841#issuecomment-1759369168)

## Expected behavior and actual behavior

I was expecting, that when I set the locale for the plugin, it'll correctly fallback to the language part of the locale if possible.

## Isolating the problem

- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/dologitodo/2/edit?html,output)

**Comment by kartik-v** [comment]
Fixed via #1875
