### ISSUE TITLE
Folder input drag and drop not finding files in a folder

### ISSUE THREAD

**Issue by MarkGooding** [kartik-v/bootstrap-fileinput#1876]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Using Chrome 131.0.6778.109 with developer tools open
2. Following example on https://plugins.krajee.com/file-folder-upload-demo for folder upload using ajax
3. Upload a folder

## Expected behavior and actual behavior

When I follow those steps, the files are not added to the drag and drop preview. Chrome developer tools console reads:
Uncaught ReferenceError: i is not defined
    at a._addFilesFromSystem (fileinput.min.js?ver=202206191928:11:55410)
    at a._zoneDrop (fileinput.min.js?ver=202206191928:11:55633)
    at HTMLDivElement.i (jquery-3.7.1.min.js:2:86755)
    at HTMLDivElement.dispatch (jquery-3.7.1.min.js:2:40035)
    at v.handle (jquery-3.7.1.min.js:2:38006)

I was expecting the files to be added to the preview for upload

## Environment

Browsers

- [X] Google Chrome (131.0.6778.109)
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.7.1
- bootstrap-fileinput version: 5.5.4 & master

## Isolating the problem

- [X] This bug happens on the plugin demos page https://plugins.krajee.com/file-folder-upload-demo
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Resolved via #1877.
