### ISSUE TITLE
ajax type "DELETE" instead of "Post" possible ? for deletion

### ISSUE THREAD

**Issue by djangosdk** [kartik-v/bootstrap-fileinput#191]
Hi,
Mostly and our server uses Delete type request as per standard for deletion of files, images etc.
But as per documentation ```initialPreviewConfig```, plugin uses Post
```- `key`: _string|object_, the key that will be passed as data to the `url` via AJAX POST.```
Is there option to override Post with Delete  ?If yes then please also mention in documentation so it can help others.

Thankx great plugin

**Comment by kartik-v** [comment]
Will be handled via #191.
