### ISSUE TITLE
Ability to extend and add one's own ajax settings

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#192]
- New property `ajaxDeleteSettings` to help extend and add to delete ajax settings
- `ajaxSettings` to help extend and add upload ajax settings

**Comment by djangosdk** [comment]
https://github.com/kartik-v/bootstrap-fileinput/compare/master...djangosdk:patch-1

**Comment by djangosdk** [comment]
```ajaxDeleteSettings``` would be better approach definitely
