### ISSUE TITLE
Empty Files array ONLY on completion of single file upload (filebatchuploadcomplete event)

### ISSUE THREAD

**Issue by beningreenjam** [kartik-v/bootstrap-fileinput#193]
Hi,

I'm currently experiencing an issue where, in my filebatchuploadcomplete event handler and on completion of a batch upload of just one file, the Files variable is an empty array; whereas after completion of a batch upload of multiple files I get an array of Files objects of the successfully uploaded files.

I've switched the event type to fileuploaded, which does show all of them as expected, in both cases of singular and multiple file uploads.

        $('input[type="file"]').fileinput({
            showCaption: false,
            previewFileType: 'any',
            maxFileSize: 10240,
            uploadUrl: "/claims/make-a-claim/motor-fleet-claims/claim-online/supporting-docs/upload",
            uploadExtraData: {
                _token: $('input[name="_token"]').val()
            },
            previewFileIcon: '',
            showRemove: false,
            showUpload: false,
            browseIcon: '<span class="icb-group-icon-folder-open"></span>'
        }).on('fileloaded, filebatchselected', function() {
            $('form').find('input[type="submit"]').prop('disabled', true);
            $('input[type="file"]').fileinput('upload');
        }).on('fileuploaded', function(event, data, previewId, index) {
            console.log(event);
            console.log(data);
            console.log(previewId);
            console.log(index);
        }).on('fileselectnone, filereset, fileuploaded', function() {
            $('form').find('input[type="submit"]').prop('disabled', false);
        });

**Comment by sunnymumbai25** [comment]
How to form submission event bind with this input field and data. After manual form submission data do not bind with files input.
Please provide some reference link if possible
