### ISSUE TITLE
ExtraData

### ISSUE THREAD

**Issue by gupi** [kartik-v/bootstrap-fileinput#194]
Hi,
I'm trying to upload some extra data but I failed.

![folie02](https://cloud.githubusercontent.com/assets/10128592/6574071/08c8e516-c721-11e4-837b-68b8fa4be433.jpg)

my upload.php script receives the image but not the extra data. Even the console of firebug did not show the extra data. The whole $_POST array remains empty - I've checked this within my php script.

**Comment by kartik-v** [comment]
You may need to debug. 

Your upload extra Data format looks wrong ... it must be an object that is configured like an associative array like this
```js
uploadExtraData: {extra: '12345'}
```

**Comment by gupi** [comment]
Thanks a lot for your fast response,
I've updated my source according your suggestion and now it worked as expected.
By the way - the syntax I've used previously was extracted from your demo I've downloaded here.
