### ISSUE TITLE
How to not allow preview section removal?

### ISSUE THREAD

**Issue by fltiago** [kartik-v/bootstrap-fileinput#195]
I set a preview image with `initialPreview` and set the `overwriteInitial: true` to replace the preview image with the uploaded one.

So far so good, but if the user want to remove the uploaded image, he can do that. I want to forbidden the uploaded image to be deleted, the user could only replace for another one.

My intent is not allow a break of my layout, adding and removing the image.

By the way, really cool plugin, good work.

**Comment by kartik-v** [comment]
Related to #185.

Track the enhancement being done in #205. With that enhancement, you can return an associative array object containing the new `initialPreview` and `initialPreviewConfig` via the events `filebatchuploadsuccess` and `filebatchuploadcomplete`.

**Comment by fltiago** [comment]
Thanks.
