### ISSUE TITLE
Additional functionality

### ISSUE THREAD

**Issue by gupi** [kartik-v/bootstrap-fileinput#196]
Hi,
I wonder if there is any (simple) way to add an additional button to the file-footer-buttons-class of the file-thumbnail-footer-class.
For my application I need to have an (extra) editor button which calls a function when clicked.

**Comment by kartik-v** [comment]
You must read the documentation thoroughly.

You can do this through [otherActionButtons](http://plugins.krajee.com/file-input#option-otheractionbuttons) setting.
