### ISSUE TITLE
Direct to Amazon S3 Example?

### ISSUE THREAD

**Issue by cj** [kartik-v/bootstrap-fileinput#197]
This uploader looks awesome.  Is there a direct to Amazon S3 example anywhere?

**Comment by YairHadari** [comment]
I would like to see this implementation also.

Thanks

**Comment by kartik-v** [comment]
The plugin does provide you with methods and events to call your own APIs or webservices.

This is not currently supported out of the box directly.

Please feel free to add a PR if you want it inbuilt.

**Comment by kartik-v** [comment]
The plugin does provide you with methods and events to call your own APIs or webservices.

IMO... this should be handled via the server code that processes your files. So this is not currently supported out of the box directly. Please feel free to add a PR if you feel you want it inbuilt.

**Comment by kartik-v** [comment]
For an example check the [Amazon S3 PHP SDK](http://aws.amazon.com/sdk-for-php/).

You can include the PHP API needed to move to S3 in your  ajax uploadUrl action which processes the uploaded file and processes the move to Amazon S3.

**Comment by henriquesobral** [comment]
I Successfully made a direct upload to S3.

I used data attributes in HTML to pass the fields generated by Amazon S3 Ruby SDK `presigned_post` method to Javascript. Then, I used these attributes in `uploadExtraData` field and made some adjustments on FormData using `filepreupload` event, by removing `file_id`(or allow it in presigned_post method) and putting `file` field in last position of FormData, by removing it and setting it using `formData.set` command (need to be the last set command).

See below.

Ruby
```
@s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read', content_type_starts_with: 'image/')
```

Ruby Erb
```
<div class="upload-files" data-form-data="<%= @s3_direct_post.fields.to_json %>" data-url="<%= @s3_direct_post.url %>">
</div>
```

Javascript
```
    data = $(".upload-files").data();
    multipartParams = data.formData;

    $('.file-input').fileinput({
      uploadUrl: data.url, //received by data attributes
      uploadAsync: true,
      browseLabel: 'Procurar',
      removeLabel: 'Remover',
      browseIcon: '<i class="icon-file-plus"></i>',
      uploadIcon: '<i class="icon-file-upload2"></i>',
      removeIcon: '<i class="icon-cross3"></i>',
      browseClass: 'btn btn-primary btn-sm',
      removeClass: 'btn btn-default btn-sm',
      showPreview: false,
      //showUpload: false,
      allowedFileExtensions: ["tif", "tiff", "obj"],
      msgSelected: "{n} arquivo(s) selecionado",
      initialCaption: "Nenhum arquivo selecionado",
      uploadExtraData: multipartParams, //received by data attributes
    }).on('filepreupload', function (event, outData, previewName, index) {
      outData.form.delete('file_id');
      outData.form.delete('file');
      outData.form.set('Content-Type', outData.files[0].type);
      outData.form.set('file', outData.files[0], outData.files[0].name);
  });
```
