### ISSUE TITLE
The Browse button no longer works in Chrome on Windows

### ISSUE THREAD

**Issue by perlausten** [kartik-v/bootstrap-fileinput#198]
It has worked flawlessly but today (March 11) nothing happens when the button is clicked (tested on several computers). Can this be related to the huge Windows update yesterday?

It works perfect in Chrome on Mac.

Thanks for looking into this.

**Comment by kartik-v** [comment]
It most definitely seems to be a caching problem on your client using outdated asssets. Extension does work fine on all OS & browsers.

In general whenever you perform an upgrade - remember to clean up all your browser's cache ENTIRELY and restart - before using the extension.

**Comment by perlausten** [comment]
Ah, it was a caching issue. Doh! Thanks for your answer.
