### ISSUE TITLE
Option for setting the caption icon

### ISSUE THREAD

**Issue by rmja** [kartik-v/bootstrap-fileinput#199]
Feature request: It would be nice if you could substitute the `glyphicon-file` class as the caption icon located next to the filename in the caption input. The option could be `captionIconClass` with the default value `glyphicon-file`.

**Comment by kartik-v** [comment]
Duplicate to #187.

You can configure [previewFileIcon](http://plugins.krajee.com/file-input#option-previewfileicon).

**Comment by rmja** [comment]
That is not the icon I am talking about. This is the one:

![image](https://cloud.githubusercontent.com/assets/2112306/6620186/a2d15058-c8cf-11e4-92f7-c5d133d9adf8.png)

**Comment by kartik-v** [comment]
Check the referred issue #187 again where the file icon is used.

The caption icon can be set via **layoutTemplates.icon**. You can refer most of these settings in docs as well.

**Comment by rmja** [comment]
Hi again, sorry I missed that. I got it to work! - thanks.
