### ISSUE TITLE
uploadBatch Method not in the documentation ?

### ISSUE THREAD

**Issue by petertiny** [kartik-v/bootstrap-fileinput#200]
I've found this helpfull method in a small stackoverflow answer.
And it was the solution to upload automatically multiple files when selected.

**Comment by kartik-v** [comment]
You must use `upload` method of the plugin as highlighted in docs. 

Note `uploadBatch` method will work for selective scenarios (when you use with `uploadAsync` property set to `false`).

The `upload` method should work based on whatever scenario you have.

**Comment by kartik-v** [comment]
You must use `upload` method of the plugin as highlighted in docs. 

Note `uploadBatch` method will work only for selective scenarios (when you use with `uploadAsync` property set to `false`).

On the other hand, the `upload` method should work based on whatever scenario you have. It internally calls `uploadBatch` when `uploadAsync` is `false` else uses a loop to generate a parallel  asynchronous upload.

**Comment by kartik-v** [comment]
You must use `upload` method of the plugin as highlighted in docs. 

Note `uploadBatch` method will work only for selective scenarios (when you use with `uploadAsync` property set to `false`) - hence it is not documented.

On the other hand, the `upload` method should work based on whatever scenario you have. It internally calls `uploadBatch` when `uploadAsync` is `false` else uses a loop to generate a parallel  asynchronous upload.

Also the `upload` method prepares and resets the plugin for upload the right way before calling `uploadBatch`.
