### ISSUE TITLE
Ability to add custom validation and trigger custom error to abort upload

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#206]
This enhancement will enable you to add your additional custom validations to enhance the fileinput to be used for innumerous scenarios. It will allow an ability to return an associative object with any of the fileinput events (except the error events and the `filebatchuploadsuccess` or `filebatchuploadcomplete`) e.g. `change`, `fileselect`, `filepreupload`, `filebatchpreupload` etc.

The object can return the following keys:

- `message`: _string_, the validation error message to be displayed before upload. If this is set the plugin will automatically abort the upload whenever called and display this as an error message. You can use this property for example to read a file and perform your own custom validation.
- `data`: _object_, an optional associative array of additional data that you can pass for usage later. 

You can get this data by reading `data.response` key in the parameters for the new `filecustomerror` event. This new event will be triggered during upload, when you have triggered an abort from any of the other events. 

#### Trigger an abort from `filepreupload`
```js
$('#input').on('filepreupload', function(event, data, previewId, index, jqXHR) {
    // do your validation and return an error like below
   if (customValidationFailed) {
       return {
           message: 'You are not allowed to do that', 
           data: {key1: 'Key 1', detail1: 'Detail 1'}
       };
   }
});
```
The above abort will be triggered at time of upload for (ajax uploads) OR at form submission (for non-ajax uploads).

#### Reading additional data at abort
Trap the `filecustomerror` event
```js
$('#input').on('filecustomerror', function(event, params) {
   // params.response will contain the additional abort data passed
}
```

**Comment by kartik-v** [comment]
Resolved via upgrade to release v4.1.8.

**Comment by josepharcillas** [comment]
I'm using filebatchpreupload using ajax in Yii. Tried the below code and it aborts the upload but the upload and browse buttons was still disabled, how can I reset it?
`
$('#rfi_response_attachments').on('filebatchpreupload', function(event, data, previewId, index) {
 return {
           message: 'You are not allowed to do that', 
           data: {key1: 'Key 1', detail1: 'Detail 1'}
       };

     });
`

**Comment by o-kamalGit** [comment]
This enhancement does not work when you have `enableResumableUpload `et to **true** 
Should be specified I think.
Thanks.
