### ISSUE TITLE
Problem with ExtraData

### ISSUE THREAD

**Issue by cyrakuse** [kartik-v/bootstrap-fileinput#207]
Hi,

I've configured the plugin to send extra datas like this : 
```
uploadExtraData: {
                        the_number: myNumber
}
```

myNumber value change but only the initial value of it is sent.
myNumber initial value is 0 so the plugin always send 0.
If the value of myNumber is changed by my javascript to 99, it send 0 because it's the initial value.

So we can't send the value of a variable in extradatas.

**Comment by kartik-v** [comment]
Would suggest you to read the [documentation](http://plugins.krajee.com/file-input) for all options, events, and methods.

You can configure `uploadExtraData` also as a function callback which will allow you to get what you need for your use case. [Read this in the docs](http://plugins.krajee.com/file-input#option-uploadextradata).

**Comment by cyrakuse** [comment]
Sorry. Didn't show this possibility
