### ISSUE TITLE
Problem while dragging and dropping folder

### ISSUE THREAD

**Issue by KickassCoxa** [kartik-v/bootstrap-fileinput#208]
There is a problem while dragging & dropping a folder. When there is folder dropped into multi file box, plugin count's it and increments total file count, but however it does not show folder in the view. (I am not sure if html5 supports folder drops at all)

**Comment by kartik-v** [comment]
Drag & drop of ONLY FILES are supported and nowhere is it mentioned that folder drag & drop is supported.

Read [browser support](http://plugins.krajee.com/file-input#browser-support) in the documentation.

Plugin uses HTML5 inbuilt ability to read drag and drop of FILES without using any external installation like FLASH etc.  

HTML5 ability to read folders is not yet available across browsers. [Read this stackoverflow answer](http://stackoverflow.com/questions/3336904/can-html-5-drag-and-drop-handle-folders).

**Comment by KickassCoxa** [comment]
Anyway, while dropping a folder. Your plugin increments total count of files dropped
