### ISSUE TITLE
RE: Problem while dragging and dropping folder 

### ISSUE THREAD

**Issue by KickassCoxa** [kartik-v/bootstrap-fileinput#209]
I read answer before, but i think you did not completely understod what i ment. 

My point is, that, with your plugin. When you drop a folder. Your plugin increment total amount of files that are dropped and almost thinks it's a file. That is a problem... Especialy with website user's who don't know that folders are not allowed. But anyway, plugin at that point somehow get's rigged and bugged.

**Comment by KickassCoxa** [comment]
The problem occurs, with the last example from here: 
bootstrap-fileinput/examples/index.html

**Comment by kartik-v** [comment]
Resolved via upgrade to release v4.1.8.
