### ISSUE TITLE
Fantastic plugin.  Any plans to port it to Angular?

### ISSUE THREAD

**Issue by kliolios** [kartik-v/bootstrap-fileinput#210]

**Comment by kartik-v** [comment]
Currently strapped with time and may not be immediate. Working on the newer version 4.1.8 with more features which will be pushed soon to dev-master.

However feel free to submit a PR to accelerate this.

**Comment by kliolios** [comment]
I will give it a shot.  Thanks

**Comment by Futursky** [comment]
```javascript
App.directive('fileInput', function() {
  return {
    restrict: 'A',
    link: function(scope, element, attrs) {
      $(element).fileinput({
        'showUpload':false,
        'previewFileType':'any'
      });
    }
  };
});
```
```html
<input file-input type="file" file-model="myFile" id="fileInput" name="fileInput">
```
works for me

**Comment by kartik-v** [comment]
A good solution as recommended by @Futursky. Closing this unless someone has something better.
