### ISSUE TITLE
Get File Sizes?

### ISSUE THREAD

**Issue by idevwebs** [kartik-v/bootstrap-fileinput#214]
This is a great file upload solution. I'd like to present information to the user as to file sizes when they select files to upload. So that they know ahead if they're going to be over the limit before attempting to upload. How can I get file sizes of files that are added to the field before actually uploading? Is it possible? Please advise.

Thank you

**Comment by kartik-v** [comment]
The file sizes can be validated via the plugin using maxFileSize property.

If you want to read file size - you can use the `reader` object and the filestack passed via some relevant events like [fileloaded](http://plugins.krajee.com/file-input#event-fileloaded).

**Comment by kartik-v** [comment]
Probably may add it as an enhancement for future to display filesizes...
