### ISSUE TITLE
trigger upload on filebatchselected strange behavior

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/bootstrap-fileinput#217]
The problem occurs if someone selects two or more files. The "filebatchselected" gets triggered, but only one file gets uploaded. The state of the one uploaded file is not updated too, it stays on "not uploaded yet" but it is.
```javascript
$input.fileinput({
	uploadUrl: $form.attr('action'),
	multiple: true,
	initialPreview: init.initialPreview,
	initialPreviewConfig: init.initialPreviewConfig,
	overwriteInitial: false,
	uploadAsync: true,
}).on('filebatchselected', function($input) {
	return function(event, numFiles, label) {
		console.log(event, numFiles, label);
		$input.fileinput('upload');
	}
}($input));
```

I've got it working with the event "fileselect", then every file gets triggered and uploaded, but the last file does not update its uploaded-state too. If I set "uploadAsync: false" then every file gets uploaded and the states are updated too, but the initial ones get the uploaded state too and the remove button isn't visible anymore. If you select another file after the upload the uploaded ones getting removed and the initial ones are the same as before with the remove-button.

**Comment by kartik-v** [comment]
Note that the `multiple` property must be set at the file input attribute's level.

**Comment by kartik-v** [comment]
Note that the `multiple` property must be set at the file input attribute's level. There is no `multiple` property within the plugin function. So you must set this in your file input markup

```php
<input id ="kartik-1" type="file" multiple>
```

And remove the `multiple` property from your fileinput method and call it this way:

```
$input = $("#kartik-1");
$input.fileinput({
    <s>multiple: true</s>,  // remove this
});

**Comment by thejahweh** [comment]
My input is already `multiple`, that's not the problem.

**Comment by kartik-v** [comment]
Ok - I think probably this is to do with the FileReader object not yet completed the reading of the file content. Setting a timeout ensures this. For example the following will work better:

```php
$input = $("#input-700");
$input.fileinput({
    uploadUrl:'<your url>",
    maxFileCount: 5
}).on("filebatchselected", function(event, files) {
    console.log(files);
    setTimeout(function() {
        $input.fileinput("upload");
    }, 1500);
});');
```

Will do some check on seeing if I can improve this in anyway.

**Comment by kartik-v** [comment]
The `fileselect` event should work better because it is triggered after FileReader finishes reading the file.

**Comment by kartik-v** [comment]
Ok this is resolved with an enhancement. You can try now with a latest updated from dev-master.

A side note - your parameters for `filebatchselected` event are also incorrect... the event just returns the `filestack` object.

**Comment by kartik-v** [comment]
Check [demo scenario # 6](http://plugins.krajee.com/file-input/demo#ajax-demo-6) which shows an auto upload scenario on file drag & drop - and also additionally automatically replacing the images with files returned from ajax response as `initialPreview`.

**Comment by kartik-v** [comment]
Check [demo scenario # 6](http://plugins.krajee.com/file-input/demo#ajax-demo-6) which shows an auto upload scenario on file drag & drop - and also additionally automatically replacing the images with files returned from ajax response as `initialPreview`.

**Comment by kartik-v** [comment]
Check [demo scenario # 6](http://plugins.krajee.com/file-input/demo#ajax-demo-6) which shows an auto upload scenario on file drag & drop - and also additionally automatically replacing the images with files returned from ajax response as `initialPreview`.

**Comment by kartik-v** [comment]
Check [demo scenario # 6](http://plugins.krajee.com/file-input/demo#ajax-demo-6) which shows an auto upload scenario on file drag & drop - and also additionally automatically replacing the images with files returned from ajax response as `initialPreview`.

**Comment by thejahweh** [comment]
Thx now it works except for the problem if you upload another file after the upload, the uploaded ones are getting removed from the preview.

**Comment by kartik-v** [comment]
Yes that's expected - because once files are uploaded they do not exist on client.

The option for you is to return an `initialPreview` via ajax response as demonstrated in [demo scenario # 6](http://plugins.krajee.com/file-input/demo#ajax-demo-6) (which is an extension of demo scenario# 5)

**Comment by kartik-v** [comment]
Ok I provided an enhancement via #218 to not clear uploaded files from preview as well until the remove button is clicked.
