### ISSUE TITLE
how could I add custom input fields for each file?

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/bootstrap-fileinput#219]
I have to add a title input field for every file.

In the version 4.1.5 it was possible to extend the `renderInitFileFooter` #149, give the `title` with the `initialPreviewConfig` and replace the placeholder `{title}` in the template.

But now in version 4.1.8 it's not possible anymore because I cannot override the function. It is also not possible with the new `customLayoutTags` because I can't get the `initialPreviewConfig` or the ID of that file.

**Comment by kartik-v** [comment]
The plugin is designed in a way where you do not need to override methods. Not sure why you were overriding the `renderInitFileFooter` earlier  - but you could do that through various options as mentioned below:

For advanced custom content ... you need to edit and set your the various template sections by [reading the documentation for various plugin options](http://plugins.krajee

- Set `layoutTemplates.footer` property and pass it to the plugin to render your own custom content within.
- Use `otherActionButtons` property to add your own action buttons to the thumbnail
- Check any other sub template settings within `layoutTemplates` or `previewTemplates` and set that to set advanced custom styling for your content.

**Comment by thejahweh** [comment]
I've done that before, like this:
```javascript
layoutTemplates: {
	footer: '<div class="file-thumbnail-footer">\n' +
	'	<div class="file-caption-name">{caption}</div>\n' +
	'	<input type="text" class="form-control" name="PictureGallery[filesTitles][]" ' +
		'value="{title}" data-name="title"/>\n' +
	'	{actions}\n' +
	'</div>'
}
```
But how do I get the title of the initial files into the preview-template?

I had to override the `renderInitFileFooter` in order to replace the `{title}` placeholder with the title from the `initialPreviewConfig`.

**Comment by kartik-v** [comment]
Normally this can be done using [customLayoutTags](http://plugins.krajee.com/file-input#option-customlayouttags). You set these as key => value pairs and these will be automatically replaced in all layout templates. 

However I will note an enhancement for initialPreviewConfig data to be replaced...

**Comment by thejahweh** [comment]
With the `customLayoutTags` it is only possible to replace the tags with static variables, there is no way to get a initial config variable for the specific file.

**Comment by kartik-v** [comment]
You can set tags as a callback function as well to calculate dynamically at runtime.

However for setting tags in `initialPreviewConfig` and using it ... I will add a separate enhancement.

**Comment by kartik-v** [comment]
@thejahweh - An enhancement has been provided via #222. Its easy to configure the `previewThumbTags` and `initialPreviewThumbTags` in the new update. The [demo scenario # 7](http://plugins.krajee.com/file-input/demo#ajax-demo-7) covers an example of usage for this.

**Comment by thejahweh** [comment]
Thanks, that's just awesome! :tada:

**Comment by thejahweh** [comment]
Ok there are now two problems.
* If I return the `initialPreviewThumbTags` with the upload-script, it doesn't recognize it. Because of that it just shows `{title}` in the input after the upload.
* If the delete button is pressed after the upload, there is this error message:
```
fileinput.js:932 Uncaught TypeError: undefined is not a function
fileinput.js:932 FileInput.initPreviewDeletes.self.$preview.find.each.$.extend.success
```

**Comment by kartik-v** [comment]
Check with the updated package and test again.

**Comment by tasdemirbahadir** [comment]
Hello,

Maybe you can try "fileloaded" event to add components for each file preview. What I am doing is find the progressbar component and append some components "before" it:

                ```
jQuery('#input_photos').on('fileloaded', function(event, file, previewId, index, reader) {
			
			//Add additional text field
			var referanceComponentProgressbar = jQuery("#" + previewId).find(".file-thumbnail-footer .file-thumb-progress");
			referanceComponentProgressbar.before($('<input type="text" id="' + previewId 
					+ '_additionaltextfield" class="form-control"  >'));

			//Do not display broken images
			jQuery(".kv-preview-data.file-preview-image").error(function() {
			    this.src="static/customer/img/no_preview.jpg";
			});

		});
```

You can apply any component you want with this approach. As you can see, I am also handling broken image previews, assigning my custom thumbnail on error.

**Comment by kartik-v** [comment]
You can manage this better through templates and tags feature provided in the plugin.. rather than injecting content yourself by looking at markup...

See [ajax demo scenario 7](http://plugins.krajee.com/file-input-ajax-demo/7) for an example.

**Comment by tasdemirbahadir** [comment]
Thank you very much I will update it.

**Comment by LucaDia** [comment]
Hi, is there a way to add a button to my fileupload elements like the screenshoot shows?
Thanks.
![cattura](https://user-images.githubusercontent.com/37707347/37841806-d0928048-2ec0-11e8-8b4f-dabdef5df29d.PNG)
