### ISSUE TITLE
Nuget - old bootstap & jquery packages forced down

### ISSUE THREAD

**Issue by brianlagerman** [kartik-v/bootstrap-fileinput#220]
When I update bootstrap-fileinput, I'm getting old versions of bootstrap (3.0.0) and jQuery (1.9.0) pushed down as well, even though I already have bootstrap (3.3.2) and jQuery (1.10.2).  There should be a check to see if the minimum version is there, but fileinput should not automatically install the older versions if newer ones exist.

**Comment by kartik-v** [comment]
You need to control this using your package manager config as the plugin will not have a method to understand this.
