### ISSUE TITLE
Disable Upload Progress Bar

### ISSUE THREAD

**Issue by tttito2** [kartik-v/bootstrap-fileinput#221]
I need to disable the upload progress bar. I am uploading very small files and it is causing a "flash" on the page that I do not want. How do I go about turning it off? If I have overlooked something, I apologize.

**Comment by kartik-v** [comment]
Set [`progressClass`](http://plugins.krajee.com/file-input#option-progressclass) property to `hide`.

**Comment by dschuett** [comment]
Setting option progressClass: 'hide' doesn't seem to hide the progress bar. What am I doing wrong?

**Comment by ZG-frank** [comment]
I think it can work with $('.kv-upload-progress').hide();
And i try to set progressClass property to hide. But it cann't work. So i use js to fix it.
But why progressClass property does not work？
