### ISSUE TITLE
initialPreview for various type of files

### ISSUE THREAD

**Issue by appcia** [kartik-v/bootstrap-fileinput#233]
First of all, great plugin!

I have 2 questions:
* I am using it combined with ajax with multiple files uploading. After selecting files, auto-generated previews are awesome and I do not want to change them at all. But... after that plugin gets ajax response, previews are updated with code from back-end. But.. in that case I am forced to know in back-end what type of preview I should generate (and I need a html template there which makes back-end terribly dependent from front-end). Is there any workaround for mentioned situation?
* I want to pass values returned from ajax response to hidden input via call `target.val(pathsFromUploadedFiles)`. How to access current file previews? I didn't see such method in plugin API.

front-end configuration:

```
$('[data-file-upload]', context).each(function () {
            var input = $(this),
                config = input.data('fileUpload'),
                target = $(config.target);

            input.fileinput({
                uploadAsync: false,
                uploadUrl: config.url,
                browseClass: "btn btn-default",
                showUpload: false,
                overwriteInitial: false,
                minFileCount: config.minFileCount || 1,
                maxFileCount: config.maxFileCount || undefined
            }).on("filebatchselected", function (event, files) {
                // Trigger upload method immediately after files are selected
                input.fileinput("upload");
            });
        });
```

backend / json_encode() :
```
'initialPreview' => [
                    "<img src='http://localhost/temp/my/uploaded/image.jpg' class='file-preview-image' alt=''>"
                ],
                'initialPreviewConfig' => [
                    [
                        'caption' => $caption,
                        'url' => 'http://localhost/upload/delete',
                        'key' => $path,
                        'path' => 'temp/my/uploaded/image.jpg' // these path I'd like to transfer to hidden input
                    ],
                ],
```

**Comment by kartik-v** [comment]
>  previews are updated with code from back-end. But.. in that case I am forced to know in back-end what type of preview I should generate

- there is no way for the plugin (client code) to know anyway what is stored on your backend... its your server code which has to parse and return the content in an accessible for display on the client.

- there is no rigid template enforced by the plugin for server to return the preview ... its kept flexible for developers to show the content using their own markup as needed.
