### ISSUE TITLE
clear file input via javascript?

### ISSUE THREAD

**Issue by fantapop** [kartik-v/bootstrap-fileinput#235]
Hi,

is there anyway to clear the upload via javascript?

**Comment by kartik-v** [comment]
Read the [methods section in the documentation](http://plugins.krajee.com/file-input#methods).

You can use the [clear method of the plugin](http://plugins.krajee.com/file-input#method-clear).

**Comment by toxicsec22** [comment]
Sir i really like your plugins , I used it for about 2 months , but i have this problem is it posible i can reset/clear the input using php ?

**Comment by kartik-v** [comment]
Simple page refresh via PHP.
