### ISSUE TITLE
lock file input without disabling?

### ISSUE THREAD

**Issue by fantapop** [kartik-v/bootstrap-fileinput#236]
Hi,

I'd like to lock the input from changing without disabling the input.  The reason is because disabled inputs do not submit.  Is there a way to do this?

thanks

**Comment by kartik-v** [comment]
Isn't the answer there in your question if we think a bit... ;-) ?

You can call the disable method and then remove the disabled attribute from your file input.

```js
$("#input_id").fileinput('disable'); // disables the entire widget
$("#input_id").removeAttr('disabled'); // remove the disabled attribute for form processing
```
