### ISSUE TITLE
How the option initialPreview works?

### ISSUE THREAD

**Issue by joaquim3541** [kartik-v/bootstrap-fileinput#240]
I see documentation of 'initialPreview' and  'initialPreviewConfig', but i not understand how to make any preview using templates described in 'previewTemplates'.

Accord of 'initialPreview' (http://plugins.krajee.com/file-input#option-initialpreview) is necessary make this code to works:

// for image files
initialPreview: [
    "<img src='/images/desert.jpg' class='file-preview-image' alt='Desert' title='Desert'>",
    "<img src='/images/jellyfish.jpg' class='file-preview-image' alt='Jelly Fish' title='Jelly Fish'>",
],
 
// for text files
initialPreview: "<div class='file-preview-text' title='NOTES.txt'>" +
    "This is the sample text file content upto wrapTextLength of 250 characters" +
    "<span class='wrap-indicator' onclick='$(\"#show-detailed-text\").modal(\"show\")' title='NOTES.txt'>[…]</span>" +
    "</div>"
 
// for other files    
initialPreview: "<div class='file-preview-text'>" + 
    "<h2><i class='glyphicon glyphicon-file'></i></h2>" +
    "Filename.xlsx" + "</div>"

but how to use preview's layouts (http://plugins.krajee.com/file-input#option-previewtemplates)???

**Comment by iyoba** [comment]
I have problem a bout 'extra' not pass parameter to server.
"initialPreviewConfig":[
{
  "url":"/manage/shop/file-delete",
  "key":"3799551d7a7b80fc0_Lovelace-210x300.jpg",
  "extra":{"abc":"xxx"}
},
{
  "url":"/manage/shop/file-delete",
  "key":"1220551d7a7b81390_aerial.png",
  "extra":{"abc":"xxx"}
}
]

**Comment by kartik-v** [comment]
Related to #243. Get the updated code.

**Comment by joaquim3541** [comment]
My question is related to how to use the template initialPreview , as in the examples and the documentation is only shown as set initialPreview with a new HTML , as this link:
http://plugins.krajee.com/file-input#option-initialpreview

**Comment by kartik-v** [comment]
#243 was in response to @iyoba 

For your query on templates for initial preview please refer the [layoutTemplates](http://plugins.krajee.com/file-input#option-layouttemplates) documentation - you need to set the `footer` property.

**Comment by joaquim3541** [comment]
thanks for response,

you can give me one sample of this?

**Comment by kartik-v** [comment]
Refer a sample in [demo scenario # 7](http://plugins.krajee.com/file-input-ajax-demo/7).

**Comment by joaquim3541** [comment]
In this example , the preview images are entered using only the HTML tag . What would be the minimalist way to put other types of files , such as videos , text and images ?

**Comment by kartik-v** [comment]
Not sure I understand.. you need to similary render your own html markup for that like you do for  `<img>` tag for image preview (e.g. using using `div` for text or `object` tag or `video` tag for your other content).

**Comment by kartik-v** [comment]
Not sure I understand.. you need to similary render your own html markup for that like you do for  `<img>` tag for image preview (e.g. using `div` for text or `object` tag or `video` tag for your other content) - you need to test and figure out what style, size, or other CSS classes works for your use case 

If you want to know how the plugin shows these on previews -- and use it similarly to return from your server... you can check [the default preview templates](http://plugins.krajee.com/file-input#option-previewtemplates) - scroll down for video, text or other and return the similar markup content.

**Comment by joaquim3541** [comment]
sorry , I was not clear . 

I need a simple way to mount the various types of previews , such as videos , texts (which has the modal feature ) and other types . 

For images , as the examples show , it only takes the tag image . 

No css classes or other particularities of the plugin . What is the way I present a text for example? I only use a div with a specific css class? I copy those 5 lines that are html template layout? 

Why can not simply pass a tag as in the picture ?
