### ISSUE TITLE
Remove button under individual attachments in non ajax mode

### ISSUE THREAD

**Issue by surendiranganesan** [kartik-v/bootstrap-fileinput#242]
Hello karthik,

Thanks for the widgets.

In ajax modes both remove button and upload button is available. but in non ajax modes there is no buttons available under each and evrey attachments.

is there any way to add remove button to individual attachments so that if there is any unwanted attachments we can remove that individually instead of going to browse again to select .

Regards,

**Comment by kartik-v** [comment]
Read [docs on the usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes) and what is possible or not possible in normal form submission and ajax modes.
