### ISSUE TITLE
deleteExtraData not being sent

### ISSUE THREAD

**Issue by vercotux** [kartik-v/bootstrap-fileinput#243]
Part of the problem is in this line: https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js#L903

The variable that is being assigned should probably be **extraData** not *deleteExtraData*.

But that alone is not enough. It is simply broken.

**Comment by kartik-v** [comment]
That code is ok... If you have checked the docs... you can set the [deleteExtraData](http://plugins.krajee.com/file-input#option-deleteextradata) generically OR individually for each delete via extra setting within [initialPreviewConfig](http://plugins.krajee.com/file-input#option-initialpreviewconfig).

Will check and update on the latter.

**Comment by vercotux** [comment]
It works. Thank you & keep up the great work!
