### ISSUE TITLE
fileuploaded is not working

### ISSUE THREAD

**Issue by HaythemJ** [kartik-v/bootstrap-fileinput#246]
The fileuploaded is not working. This event handler is not executed when upload successfully. Moreover the event filebatchuploaderror is fired with status ok (200) which is strange. Below the scenario:

            $('#input-Attachement').fileinput(
            {
                uploadUrl: MyURL, // server upload action
                uploadAsync: true,
                maxFileCount: 1,
                uploadExtraData: function () {
                    return { RId: $scope.request.RId };
                },
                ///ajaxSettings is added here manually since global http interceptor is not able to intercept this request.
                ajaxSettings: { headers: { Authorization: 'Bearer ' + localStorageService.get('authorizationData').token } }
            });

            $('#input-Attachement').on('fileuploaded', function (event, data, previewId, index) {
                $('#input-Attachement').fileinput('reset');
            });

            $('#input-Attachement').on('filebatchuploadcomplete', function (event, data, previewId, index) {
                $('#input-Attachement').fileinput('reset');
            });

            $('#input-Attachement').on('filebatchuploaderror', function (event, data, previewId, index) {
                $('#input-Attachement').fileinput('reset');
            });

Both filebatchuploaderror and filebatchuploadcomplete are fired bu not the case for fileuploaded. Which is really strange since it is mentioned in the documentation that filebatchuploaderror and filebatchuploadcomplete  are fired only if we have uploadAsync: false.

**Comment by kartik-v** [comment]
- `fileuploaded` will fire only for ASYNC - and will fire for every file uploaded in the list of files
- `filebatchuploadsuccess` will fire only for SYNC (once)
- `filebatchuploaderror` and `filebatchuploadcomplete` will fire for both ASYNC and SYNC (once)

**Comment by kartik-v** [comment]
This is mentioned in docs for [filebatchuploadcomplete](http://plugins.krajee.com/file-input#event-filebatchuploadcomplete) as well.

**Comment by HaythemJ** [comment]
Yes but fileuploaded is not fired with uploadAsync: true, is that what you call ASYNC ?
Also why filebatchuploaderror is fired even if the file was uploaded successfully and and the server returns status OK (200)?

**Comment by kartik-v** [comment]
Its clear from what you are facing... you have some error in your ajax upload which you need to debug

- filebatchuploaderror will fire if you face an error in your upload (ITS an ajax ERROR outcome)... in this case `fileuploaded` or `filebatchuploadsuccess` will NOT fire

- filebatchuploadcomplete will fire irrespective of an error OR success after ajax processing.

**Comment by kartik-v** [comment]
Its clear from what you are facing... you have some error in your ajax upload which you need to debug

- `filebatchuploaderror` will fire if you face an error in your upload (basically it means an `ajaxError` is triggered OR you are returning a error output message in the json response from your server action)... in this case `fileuploaded` or `filebatchuploadsuccess` will NOT fire

- `filebatchuploadcomplete` will fire irrespective of an error OR success after completion of the ajax processing.

**Comment by HaythemJ** [comment]
I am using WebApi as backend and while debugging I am pretty sure I am returning OK(200).
Even the progress bar of bootstrap-fileinput is set to 100%. Also the event fileuploaderror is not fired.
What is really strange is how come that the event filebatchuploaderror is fired and I am getting OK(200) from server? See below screenshot
![imprime](https://cloud.githubusercontent.com/assets/9905290/7115511/327a101c-e1e1-11e4-8c73-941c7a80a346.png)

**Comment by kartik-v** [comment]
Again reiterating (if you check the docs) - the `filebatchuploaderror` will fire IF:

- you return a `error` key in your json response from the server e.g.`{error: "Failed upload"}`
- or the jquery.ajax method encounters a processing error

It will fire only if you selected the batch upload button - not to be confused with `fileuploaderror` event which fires if an error is faced after you individually press the upload icons within the thumbnail.

You may need to debug around these... as to why the conditions mentioned above are happening on your environment?

**Comment by kartik-v** [comment]
Again reiterating (if you check the docs) - the `filebatchuploaderror` will fire IF:

- you return a `error` key in your json response from the server e.g.`{error: "Failed upload"}` 
- OR you have an invalid JSON response from your server
- OR the jquery.ajax method encounters a processing error in general (does not matter when - it maybe before upload begins or after 30, 80% or after 100% - check what is happening on your ajax server action progress at each stage).

The `filebatchuploaderror` will fire only if you clicked the batch upload button - not to be confused with `fileuploaderror` event which fires if an error is faced after you individually press the upload icons within the thumbnail.

You may need to debug around these... as to why the conditions mentioned above are happening on your environment?

**Comment by kartik-v** [comment]
Closing unless you find anything to report.

**Comment by emmsdan** [comment]
I have Issues processing... it just keep showing processing...
![upload later](https://cloud.githubusercontent.com/assets/3631446/26025401/9746f5a0-37de-11e7-9b55-99eeeaa56db9.png)
