### ISSUE TITLE
Umlauts not displayed in filename

### ISSUE THREAD

**Issue by CannyDuck** [kartik-v/bootstrap-fileinput#250]
If I upload a file on the demo page with the name "Musterlöäütgang.csv" the filename is displayed without the umlauts "ö", "ä", "ü". Is it possible to handle umlauts in filenames?
![screen](https://cloud.githubusercontent.com/assets/1655493/7139766/5434b774-e2c8-11e4-99f2-acece9d79052.png)

**Comment by kartik-v** [comment]
Yes ... change the slug callback function to include the right Regexp to replace.
Basically submit a PR for the locale file for your language. Check the [Chinese Translation locale file](https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput_locale_zh.js) as an example and submit a similar one for your language.

**Comment by kartik-v** [comment]
Yes ... change the slug callback function to include the right Regexp to replace characters in your filename. Currently for English it replaces all special characters.
Basically submit a PR for the locale file for your language. Check the [Chinese Translation locale file](https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput_locale_zh.js) as an example and submit a similar one for your language.

**Comment by CannyDuck** [comment]
Why do you replace characters in the filenames with the "slugCallback". You see any security issues or what it the cause for the replacement?

**Comment by kartik-v** [comment]
You can scan the older issue logs - for the use cases where this used to throw up the javascript error while rendering of the widget.. Since the filename is parsed and rendered within the caption templates using javascript/jquery - special characters will cause parsing issues .

**Comment by kartik-v** [comment]
Have modified the default slug routine to allow umlauts... but for any other special characters in your file name one will need to override the `slugCallback` as per their use case/ or language need.

**Comment by akmalnodirov** [comment]
hi, i am new to yii2. I want to to ajax file upload like this:
This is my active form field:
     echo $form->field($model, 'photo[]')->widget(FileInput::classname(), [
            'options' => 
                [
                    'multiple' => true, 
                    'accept' => 'image/*'
                ],
            'pluginOptions' => 
                [
                    'uploadUrl' => Url::to(['/products/file-upload']),
                    'allowedFileExtensions'=>['jpg', 'gif', 'png', 'bmp'],
                    'initialPreview' => $allImage,
                    'overwriteInitial' => false,
                    'previewFileType' => 'image', 
                    'showCaption' => false,
                    'showRemove' => false,
                    'showUpload' => false,
                    'showCancel' => false,
                    'browseClass' => 'input-baby btn btn-primary btn-block',
                    'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
                    'browseLabel' =>  'Выберите файл',
                    'maxFileCount' => 20
                ]
        ])->label(false);  
and i have a controllers, one for create model, one for ajax file upload. Now how to upload multiple files when click submit button ?

**Comment by akmalnodirov** [comment]
can anyone show me an example of uploading multiple files with kartik file input using ajax upload when with active form model ? thank you
