### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by KimKJDesigns** [kartik-v/bootstrap-fileinput#256]
I cannot get anything to post utilizing even the most basic of options from the demos, for deleting files. Not sure if I'm searching for the right $_POST. Currently I'll looking for  $_POST['key'] but cannot find anything.

Which leads me to believe that something may be amiss.
```js
initialPreview: [	
   "<img src='/datafeed/uploads/5/8/95bb1ec0fc71470850e646e0a76bbd33.png' class='file-preview-image' alt='' title=''>",
],
initialPreviewConfig: [
   {
      width: '120px',
      url: '/scripts/settings.php', 
      key: 'products_image_delete', 
      extra: {
         image_delete: 'image_delete',
         file_name: '95bb1ec0fc71470850e646e0a76bbd33.png',
         image_id: '8'
      }
   }							
]
```

**Comment by kartik-v** [comment]
You may want to debug on your browser javascript console (e.g. chrome/firefox) if your delete URL `/scripts/settings.php` is getting called and what is the params passed as `$_POST` and what is the response?

**Comment by KimKJDesigns** [comment]
Using exactly your code, just changing the image location and the delete URL.
<pre>$("#file-1").fileinput({
			uploadUrl: "http://localhost/file-upload-single/1", // server upload action
			uploadAsync: true,
			minFileCount: 1,
			maxFileCount: 5,
			overwriteInitial: false,
			initialPreview: [
				"<img src='/datafeed/uploads/5/8/95bb1ec0fc71470850e646e0a76bbd33.png'>",
			],
			initialPreviewConfig: [
				{caption: "People-1.jpg", width: "120px", url: "#", key: 1},
			],
			uploadExtraData: {
				img_key: "1000",
				img_keywords: "happy, nature",
			}
		});
</pre>

Dumping the $_POST shows:
<pre>Uncaught Error: Syntax error, unrecognized expression: array(0) {
}</pre>

I'm feeling stupid that I've overlooked something but I'm successfully uploading, just cannot get this delete to POST

**Comment by kartik-v** [comment]
in `initialPreviewConfig` you must a valid `url` to point to your server action that will trigger the delete. Currently its set to `#` in the example - but you must use normally a valid delete action just like the uploadUrl.

**Comment by KimKJDesigns** [comment]
Yeah, I had this before. Changed to a file to just dump all variables.

<pre>
Uncaught Error: Syntax error, unrecognized expression: All Arraysarray(8) {
  [0]=>
  string(4) "_GET"
  [1]=>
  string(5) "_POST"
  [2]=>
  string(7) "_COOKIE"
  [3]=>
  string(6) "_FILES"
  [4]=>
  string(7) "_SERVER"
  [5]=>
  string(8) "_REQUEST"
  [6]=>
  string(4) "_ENV"
  [7]=>
  string(7) "GLOBALS"
}
_GET Arrays = NULL
_POST Arrays = NULL
_COOKIE Arrays = NULL
_FILES Arrays = NULL
_SERVER Arrays = NULL
_REQUEST Arrays = NULL
_ENV Arrays = NULL
GLOBALS Arrays = NULL
_SESSION Arrays = NULL
</pre>

**Comment by KimKJDesigns** [comment]
FOUND IT!!

Line 933

<pre>
settings = $.extend({
url: vUrl,
type: 'DELETE',     <---- This should be 'POST'
dataType: 'json',
data: $.extend({key: vKey}, extraData),
beforeSend: function (jqXHR) {
self.ajaxAborted = false;
self.raise('filepredelete', [vKey, jqXHR, extraData]);
if (self.ajaxAborted) {
qXHR.abort();
} else {
addCss($frame, 'file-uploading');
addCss($el, 'disabled');
}                            
},</pre>

**Comment by kartik-v** [comment]
It should not matter. DELETE will send data via $_POST anyway (like a POST)... this was defaulted to DELETE to make it REST compatible as per this enhancement #215.

If you need to override it you can set it within `deleteAjaxSettings`.

**Comment by KimKJDesigns** [comment]
Ok cool,

I'll have a look at that option too, so far nothing has broke and I've at least moved on to ensure the rest of my scripts are working.
