### ISSUE TITLE
MaxFileCount when showing IntialPreview of existing images

### ISSUE THREAD

**Issue by vsmelarkod** [kartik-v/bootstrap-fileinput#259]
Hi,

I am using this widget in Yii2. When I use MaxFileCount=>3, I am able to upload 3 images and if there are more, then it is showing a proper error. However in my actionUpdate, when I display existing images in the current record, I can still browse and add 3 more images. 

How do I go about solving this issue? Thanks Kartik.

**Comment by kartik-v** [comment]
You would need to handle this in your server validation and render the plugin accordingly for example if you have 3 images on server you should disable the file input and hide the upload button.

**Comment by vsmelarkod** [comment]
Thanks. I did that and it worked.
