### ISSUE TITLE
css 'fail' in invalid extension file

### ISSUE THREAD

**Issue by fabi0w** [kartik-v/bootstrap-fileinput#266]
amazing plugin, congratulations! But this css appearing superimposed when I select a different file extension:
![failcss](https://cloud.githubusercontent.com/assets/11986232/7340203/6b7bed72-ec5e-11e4-832a-29592d807cf1.jpg)

css/fileinput.min.css  * @version 4.1.9
js/fileinput.min.js  * @version 4.1.9

I'm waiting ... thanks!!

**Comment by kartik-v** [comment]
You need to check if you have some other CSS, theme, or third party javascript or plugin on your environment which is over-riding and causing the above.

For a default bootstrap CSS this works fine. For example you can check this in the [8th example in plugin demos in advanced usage section](http://plugins.krajee.com/file-input/demo#advanced-usage) - by selecting an unsupported file type (the example allows only image and video files as configured in plugin).
