### ISSUE TITLE
Hi, I Just quick checked but cant find any java codes for editing. (After uploaded)

### ISSUE THREAD

**Issue by realsby** [kartik-v/bootstrap-fileinput#267]
Hi, I cant find any java codes to add previous uploads into plugin.. for a edit page support..
I was thinking, i will insert the previous uploads and delete with ajax if user delete it.. If add new images  only new ones will submit via form.

**Comment by kartik-v** [comment]
You may try posting in discussion section on the plugin page for code/programming related help.
