### ISSUE TITLE
Need to append multiple images with remove and form submit without ajax call

### ISSUE THREAD

**Issue by mpkumar87** [kartik-v/bootstrap-fileinput#268]
Hi,

Need to append multiple images with remove icon. Also instead of ajax call to upload, need to use form submit.. Please guide me to solve my issue.

Thanks,
Premkumar

**Comment by thejahweh** [comment]
This could be combined with a Drag&Drop feature without ajax, which should be possible according this [stackoverflow answer](http://stackoverflow.com/a/26567782/1838887).

**Comment by kartik-v** [comment]
You cannot modify files selected on client side... if you are using FORM based submission. You can however simulate this from your server side code... by uploading files to server every time files are selected... and providing a delete button...

**Comment by kartik-v** [comment]
You cannot modify files selected on client side... if you are using FORM based submission. You can however simulate this from your server side code... by uploading files to server every time files are selected... and displaying the uploaded thumbnails and providing a delete button...

basically do something like this

```js
$("#file-input").on('change', function() {
    $("#file-input").closest('form').trigger('submit');
});
```

Then on form submit reinitialize the plugin with `initialPreview` and `initialPreviewConfig` to show the delete buttons.

**Comment by kartik-v** [comment]
You cannot modify files selected on client side... if you are using FORM based submission. Read the [modes of using the plugin and features possible](http://plugins.krajee.com/file-input#usage-modes).

You can however simulate this from your server side code... by uploading files to server every time files are selected... and displaying the uploaded thumbnails and providing a delete button...

basically do something like this

```js
$("#file-input").on('change', function() {
    $("#file-input").closest('form').trigger('submit');
});
```

Then on form submit redirect page to show the reinitialized plugin with `initialPreview` and `initialPreviewConfig` to show the uploaded thumbnails with delete buttons.
