### ISSUE TITLE
It's not issue, it's question

### ISSUE THREAD

**Issue by JStika** [kartik-v/bootstrap-fileinput#274]
How can I send to you my translations for Slovak and Czech languages SK_sk, CZ_cz?

**Comment by kartik-v** [comment]
You can create a Pull Request to submit your translation file (hope you are familiar with one)?

Its easy to [submit a translation file as mentioned in docs](http://plugins.krajee.com/file-input#translations).

Remember to change the `_LANG_` tag with your ISO language code.

**Comment by JStika** [comment]
I dont know how I can add new pull request

On Monday 4.5.2015 16:29, Kartik Visweswaran wrote:
>
> You can create a Pull Request to submit your translation file (hope 
> you are familiar with one)?
>
> Its easy to submit a translation file as mentioned in docs 
> <http://plugins.krajee.com/file-input#translations>.
>
> Remember to change the |_LANG_| tag with your ISO language code.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kartik-v/bootstrap-fileinput/issues/274#issuecomment-98726782>.
>

-- 

Yours sincerely - S pozdravem

Jaroslav Štika / Web Programmer
+421 09 05 52 87 68 / Jaroslav.Stika@gmail.com 
<mailto:Jaroslav.Stika@gmail.com>

Facebook <https://www.facebook.com/stika.jaroslav> Google Plus 
<https://plus.google.com/107125133523196240075> Linkedin 
<https://sk.linkedin.com/in/jaroslavstika> Skype <skype:stika-pike?chat>

My momma always said, "Life was like a box of chocolates. You never know 
what you're gonna get."
Moje máma vždycky říkala, "Život je jako bonboniéra. Nikdy nevíte, co 
dostaneš."

-- Forrest Gump

**Comment by kartik-v** [comment]
You [can check this in github docs](https://help.github.com/articles/creating-a-pull-request/).

**Comment by kartik-v** [comment]
Create a fork of this repo and you [can check about creating PR in github docs](https://help.github.com/articles/creating-a-pull-request/).

**Comment by JStika** [comment]
Create is disabled.......


On Monday 4.5.2015 17:09, Kartik Visweswaran wrote:
>
> You can check this in github docs 
> <https://help.github.com/articles/creating-a-pull-request/>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kartik-v/bootstrap-fileinput/issues/274#issuecomment-98743194>.
>

-- 

Yours sincerely - S pozdravem

Jaroslav Štika / Web Programmer
+421 09 05 52 87 68 / Jaroslav.Stika@gmail.com 
<mailto:Jaroslav.Stika@gmail.com>

Facebook <https://www.facebook.com/stika.jaroslav> Google Plus 
<https://plus.google.com/107125133523196240075> Linkedin 
<https://sk.linkedin.com/in/jaroslavstika> Skype <skype:stika-pike?chat>

My momma always said, "Life was like a box of chocolates. You never know 
what you're gonna get."
Moje máma vždycky říkala, "Život je jako bonboniéra. Nikdy nevíte, co 
dostaneš."

-- Forrest Gump

**Comment by JStika** [comment]
I'll send you, attached.
It's faster.........:)


On Monday 4.5.2015 17:10, Kartik Visweswaran wrote:
>
> Create a fork of this repo and you can check about creating PR in 
> github docs <https://help.github.com/articles/creating-a-pull-request/>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kartik-v/bootstrap-fileinput/issues/274#issuecomment-98743700>.
>

-- 

Yours sincerely - S pozdravem

Jaroslav Štika / Web Programmer
+421 09 05 52 87 68 / Jaroslav.Stika@gmail.com 
<mailto:Jaroslav.Stika@gmail.com>

Facebook <https://www.facebook.com/stika.jaroslav> Google Plus 
<https://plus.google.com/107125133523196240075> Linkedin 
<https://sk.linkedin.com/in/jaroslavstika> Skype <skype:stika-pike?chat>

My momma always said, "Life was like a box of chocolates. You never know 
what you're gonna get."
Moje máma vždycky říkala, "Život je jako bonboniéra. Nikdy nevíte, co 
dostaneš."

-- Forrest Gump

**Comment by kartik-v** [comment]
Clicking the fork button on top right of the page creates a fork.

**Comment by JStika** [comment]
Just done.

On Monday 4.5.2015 19:50, Kartik Visweswaran wrote:
>
> Clicking the fork button on top right of the page creates a fork.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kartik-v/bootstrap-fileinput/issues/274#issuecomment-98795414>.
>

-- 

Yours sincerely - S pozdravem

Jaroslav Štika / Web Programmer
+421 09 05 52 87 68 / Jaroslav.Stika@gmail.com 
<mailto:Jaroslav.Stika@gmail.com>

Facebook <https://www.facebook.com/stika.jaroslav> Google Plus 
<https://plus.google.com/107125133523196240075> Linkedin 
<https://sk.linkedin.com/in/jaroslavstika> Skype <skype:stika-pike?chat>

My momma always said, "Life was like a box of chocolates. You never know 
what you're gonna get."
Moje máma vždycky říkala, "Život je jako bonboniéra. Nikdy nevíte, co 
dostaneš."

-- Forrest Gump

**Comment by kartik-v** [comment]
Merged and updated via #275.
