### ISSUE TITLE
Change "uploadUrl" after initialization 

### ISSUE THREAD

**Issue by taraman** [kartik-v/bootstrap-fileinput#276]
Hello Krajee,

Is There any way to change an options after initialization?
I need to change the value of "uploadUrl" option depending on selected parameter

i.e:
var save = function () {
   var path = 'gallery';
   $('#fileUplaod').fileinput('refresh', { uploadUrl: '/Home/UploadFiles' + '?folderPath=' + path });
   $('#fileUplaod').fileinput('upload');
}
thanks,
Taraman

**Comment by dwsrumwq7cyey7qv** [comment]
Hello taraman,

I also experience a problem with the "refresh" function of this plugin. I am using version 4.2.1 and after the call of "contractUploader.fileinput('refresh', {browseLabel: toLabel});" no events are handled anymore. Why is it the case?

That means that the first time, the browse label gets updated correctly. But after that, no events get triggered and so, the browse label does not get changed.

Please see enclosed the important part of the code.
```
var contractUploader = $('#registration_contract_contractUpload_file').fileinput({
        [...]
    }).
    on('fileloaded', function(event, file, previewId, index, reader) {
        [...]
        changeBrowseLabel(file.name);
    }).
    on('fileerror', function(event, data) {
        [...]
        changeBrowseLabel(errorMessages.browseLabel);
    });

function changeBrowseLabel(toLabel) {
    if (!toLabel || toLabel.length === 0) {
        return;
    }

    if (contractUploader) {
        contractUploader.fileinput('refresh', {browseLabel: toLabel}); 
    }
}
```

**Comment by kartik-v** [comment]
The plugin unsets and then resets events on refresh. You therefore need to call your custom events after refresh again.

**Comment by nurmanhabib** [comment]
This issue was made by @taraman , answered a question why is the other?

@kartik-v I also have the same case, how to replace uploadUrl when after initialized without eliminating file_data?

**Comment by matmiranda** [comment]
I have the same problem, any solution?

**Comment by kartik-v** [comment]
Recording an enhancement. All URLs can be setup as a function callback which will be executed at runtime.

**Comment by radaromel** [comment]
How can i use a unc path on uploadUrl?

e.g. - uploadUrl:"\\servername\folder1\folder2"

**Comment by kartik-v** [comment]
The `uploadUrl` property should be a web accessible URL as supported by [jQuery ajax](https://api.jquery.com/jquery.ajax/).
