### ISSUE TITLE
layoutTemplates as an HTML 5 attribute

### ISSUE THREAD

**Issue by dalamberts** [kartik-v/bootstrap-fileinput#278]
I have been trying to get this work as an HTML 5 attribute but I can not find the right syntax. I would really appreciate help.  Here is my last attempt:

data-layout-templates="{actions: &quot;<div class='file-actions'>\n<div class='file-footer-buttons'>\n{delete}</div>\n<div class='clearfix'></div>\n</div>&quot;}"

Here is the working JS version:
	layoutTemplates: {
	    actions: "<div class='file-actions'>\n" +
        "    <div class='file-footer-buttons''>\n" +
        "        {delete}" +
        "    </div>\n" +
        "    <div class='clearfix'></div>\n" +
        "</div>"
		}

**Comment by kartik-v** [comment]
Some of the coding basics you may want to check you have inserted a double quote `"` inside a double quote. 

You should for example use a single quote `'` inside the double quote `"` instead.
