### ISSUE TITLE
Dropzone disappears when an HTML element is dragged into it

### ISSUE THREAD

**Issue by ycha28** [kartik-v/bootstrap-fileinput#282]
I'm finding that my dropzone disappears when you drag any HTML element into it. Is there a way to prevent this from happening? I tried listening for the "fileerror" event, but it doesn't get triggered by this behavior.

**Comment by kartik-v** [comment]
The dropzone has been designed to read dragged files and not HTML elements.

**Comment by ycha28** [comment]
I don't think this behavior is exclusive to my site. If you look at demo #6 (http://plugins.krajee.com/file-input-ajax-demo/6), you can see that dragging the red "Tips" button into the drop zone causes the drop zone to collapse.

**Comment by kartik-v** [comment]
Related to #303. Get the updated code.
