### ISSUE TITLE
Unable to hide "browse" button

### ISSUE THREAD

**Issue by vercotux** [kartik-v/bootstrap-fileinput#283]
There is no _showBrowse_ option. This is not critical, but would be convenient.

However, at the moment it is not possible to hide the browse button even by redefining the *templateLayout*. Omitting '{browse}' from *main1* or *main2* causes the fallback html file input to appear.

The use case for hiding the browse button is to eliminate all buttons and have the widget function as a read-only file preview (for example when the user has insufficient permissions to modify/add/remove/upload files).

**Comment by kartik-v** [comment]
You can set input to disabled to prevent any upload and make it readonly (or you can call the `disable` method of the plugin). 

The plugin basically is a fileinput which internally maintains the attributes and browse button is the integral part of that. You can play around with the CSS (adding a parent container CSS  and styling) to hide it if you want.
