### ISSUE TITLE
Can We Check the Dimension of Image when its Selected

### ISSUE THREAD

**Issue by irfanrulz** [kartik-v/bootstrap-fileinput#284]
hi there !

I am new to bootstrap and Jquery, i was wondering if i can restrict users to upload an image of specific dimensions likei can restrict them on file size and file Types

**Comment by kartik-v** [comment]
This is not in scope of this plugin. But you do this validation easier through your server code during upload using built-in functions or third party extensions. For example PHP has this [getimagesize](http://php.net/manual/en/function.getimagesize.php) function.

**Comment by kartik-v** [comment]
Having said that --- I may include an enhancement to handle this in future. Reopening this.

**Comment by gmansata6290** [comment]
Kartik can you show me how to give custom error for image dimension if it is not matching the criteria ?

**Comment by kartik-v** [comment]
Refer enhancement #328.
