### ISSUE TITLE
Non-english letters in file name

### ISSUE THREAD

**Issue by all2001** [kartik-v/bootstrap-fileinput#285]
Hi Kartik. Thank you for this very cool plugin - it makes our work easier.
But I have a question concerning subject issue. 
If ones selects a file which name contains russian letters - the preview doesn't show this file name, just only exctension. The same we can find out with div class form-control:
`<div class="file-caption-name" title=".xlsx">`
Not sure, but I suppose that it has the same behavior with all non-latin file names either.
Coud you check this issue or give an workaround if you please

**Comment by kartik-v** [comment]
Refer related discussion #250.
