### ISSUE TITLE
Turning off preview seems to break plugin

### ISSUE THREAD

**Issue by cokolwiekbylebylo** [kartik-v/bootstrap-fileinput#286]
I'm not sure if it's a bug, but when you set showPreview option to false, it seems the plugin stops working (there is no caption after file selection and the upload and remove buttons doesn't show up)

**Comment by kartik-v** [comment]
Not sure what you are doing.

Check the [second example in the basic usage demo page](http://plugins.krajee.com/file-input/demo#basic-usage). It shows an example of plugin working without preview.
