### ISSUE TITLE
Remove a single file

### ISSUE THREAD

**Issue by sylvaindeloux** [kartik-v/bootstrap-fileinput#288]
Hi! 

I'd like to remove a single file (not all) but I can't get this button with these options : 

    showRemove: true,
    initialPreviewShowDelete: true,
    
It just render a global delete button for remove all files at once. Did I miss something or is it an issue?
Tested with 4.2.0 and no ajax.

Thanks

**Comment by kartik-v** [comment]
Read [documentation on what is supported and what is NOT in FORM MODE and AJAX MODE](http://plugins.krajee.com/file-input#usage-modes).
