### ISSUE TITLE
Returning an object from filebatchpreupload event handler does not abort upload

### ISSUE THREAD

**Issue by ddechant** [kartik-v/bootstrap-fileinput#289]
I'm doing something along the lines of this:
```
var $attachments = $("#attachments").fileinput({
	uploadUrl: "/api/attachment",
	uploadAsync: false,
	showUpload: false,
	showCaption: false,
	maxFileSize: 10240,
	maxFileCount: 5,
	allowedFileExtensions: ["doc", "docx", "pdf", "jpg", "png", "tif", "eml", "msg", "txt", "wav", "rtf"],
	layoutTemplates: {
		actionUpload: ""
	},
	uploadExtraData: function() {
		return { id: $eventEntryCreate.id };
	}
});

$attachments.on("filebatchpreupload", function (event, data, jqXHR) {
	if (data.files.length === 0) {
		return {
			message: "NoFiles",
			data: data
		};
	}  
});
```
Which is being triggered by this:
```
$attachments.fileinput("upload");
```
The upload call still continues, even after returning the object from the filebatchpreupload event. No file data is transferred, just the uploadExtraData data. I'm trying to prevent any server calls if there aren't any files to transfer.

**Comment by kartik-v** [comment]
The plugin allows you to submit data just like a form if either files or uploadextradata is available. So this is expected. You need to mange the validation in your server code and return an error as needed.

**Comment by ddechant** [comment]
>The above abort will be triggered at time of upload for (ajax uploads) OR at form submission (for non-ajax uploads).

But the abort doesn't occur. The POST continues, regardless if the uploadExtraData is used or not.
