### ISSUE TITLE
Allow for chunk uploads

### ISSUE THREAD

**Issue by kmuchmore** [kartik-v/bootstrap-fileinput#290]
If you are wanting to upload a video that is 10 GB to the server. Sticking all of this in a single upload is not very realistic. For people dealing with large file uploads, having the ability to upload files in smaller (defined) chunk sizes would be a major enhancement. 

Good work on this awesome plugin.

**Comment by mecreant** [comment]
Available now ? Chunk files is a very good option to add this awesome plugin

**Comment by SNull** [comment]
Ohm,I need this plugin , too! Floor host, would suggest for me?!

**Comment by shabenschuss** [comment]
Any chance this is in progress? This plugin would be flawless with this feature.

**Comment by kartik-v** [comment]
Will update on this when I get a bit of time.

**Comment by rommcr** [comment]
> Will update on this when I get a bit of time.

As I understand you did not have time to implement it?

**Comment by jackttcoms** [comment]
Do you think it could be done sometime during 2019? Thanks

**Comment by kartik-v** [comment]
@jackttcoms I understand the need for this feature. It requires some significant additions to the code and unfortunately have not been able to put in time.

However, am willing to prioritize effort into this based on overall interest from across this community to finish something in 2019. Any aid provided will help me prioritize this faster internally.

**Comment by kartik-v** [comment]
Planned this for milestone release 5.0.0.

**Comment by jackttcoms** [comment]
Wooo. Can't wait.

**Comment by kartik-v** [comment]
Resolved via [this major upgrade to release v5.0.0](https://github.com/kartik-v/bootstrap-fileinput/commit/d635155749059accbd68e272fdcde686f3115257) well ahead of time.

- Refer resumable uploads / chunk uploads [documentation here](http://plugins.krajee.com/file-input#ajax-resumable)
- Refer [resumable uploads demos](http://plugins.krajee.com/file-resumable-uploads-demo)
- Refer [enhancements and features closed in 5.0.0 release milestone](https://github.com/kartik-v/bootstrap-fileinput/milestone/1?closed=1)

**Comment by jackttcoms** [comment]
@kartik-v thanks so much!!!!!! Quick question tho, is it possible to put multiple file inputs in one form and if so do you have a demo? Thanks so much!!!!!!

**Comment by kartik-v** [comment]
>  Quick question tho, is it possible to put multiple file inputs in one form
You can send other form input data via [uploadExtraData](http://plugins.krajee.com/file-input/plugin-options#uploadExtraData) which can be setup also as a callback function to send records at runtime. An example of how you can set this up is been described in [ajax demo scenario # 7](http://plugins.krajee.com/file-input-ajax-demo/7).

> moving big files from the tmp folder so can your code be customised to save the chunks in a custom directory like uploads/temp and then once done move back to uploads
This is entirely upto your server code configuration (and not dictated by the plugin) on how and where you store your files on your server. The server code example shared in docs is just an example but needs to be set and programmed correctly for your use case.

**Comment by jackttcoms** [comment]
So as in a (icon_img file input then preview_img file input and then main_file file input along with other form data) unless you know a way to make it possible to upload all the files and then get them to appear in a dropdown which you then select for each field like codecanyon. Like this gif. https://gyazo.com/82a7b5accd55e9db7134b125e4ddac77

Ah ok, great. Thanks so much. **and thanks for how fast you did this update :)**

Thanks :)
