### ISSUE TITLE
Unexpected behavior with browser back history?

### ISSUE THREAD

**Issue by pacahon** [kartik-v/bootstrap-fileinput#292]
Hello, I have following scenario:
1. Choose file 'File1.csv"
2. Send form
3. Press browser "Back" button (I have an error on new page and trying to return back)
4. On that step file input is empty (visually I can't see filename). 
How can I fix this behavior?

**Comment by kartik-v** [comment]
There's nothing the plugin can do - but you can do some tweaking in your code to always reset the form when page is loaded - so that pressing a back button does not show cached values... for example

```html
<form id="myForm">
  <input type="text" value="" name="myTextInput" />
</form>
<script type="text/javascript">
  document.getElementById("myForm").reset();
</script>
```
