### ISSUE TITLE
Re-upload Errors

### ISSUE THREAD

**Issue by kmuchmore** [kartik-v/bootstrap-fileinput#293]
If you add files into the dropzone, then click the individual upload buttons for each file, then click the main batch upload button, you will get a MultiValueDictKeyError. This is fixed by adding a minFileCount : 1.
This isn't really a bug more of a convenience issue. I think minFileCount should default to 1 to avoid having this error and not knowing why.

**Comment by kartik-v** [comment]
Not sure this can be replicated. Can you check this on the demo page. Closing the issue until there is some method to reproduce this error.
