### ISSUE TITLE
Remove class of the caption span?

### ISSUE THREAD

**Issue by Defcon0** [kartik-v/bootstrap-fileinput#294]
Hello and thanks for the great plugin,

is there any option (or should there be one) to change the <span> next to the uploaded filename, i.e <span class="glyphicon glyphicon-file kv-caption-icon"></span> like I can with all other elements like browse, remove, ...?

     <div class="input-group ">
         <div tabindex="-1" class="form-control file-caption Ha kv-fileinput-caption">
         <span class="file-caption-ellipsis" title="43917_water_rain.jpg">…</span>
         <div class="file-caption-name" title="43917_water_rain.jpg"><span class="*glyphicon glyphicon-file kv-caption-icon*"></span>43917_water_rain.jpg</div>
         </div>
         <div class="input-group-btn">
               <button type="button" title="Clear selected files" class="btn btn-default fileinput-remove fileinput-remove-button"><i class="fa fa-remove"></i></button>
               <button type="button" title="Abort ongoing upload" class="hide btn btn-default fileinput-cancel fileinput-cancel-button"><i class="glyphicon glyphicon-ban-circle"></i> Cancel</button>
               <div class="btn btn-primary btn-file"> <i class="fa fa-search"></i> <input type="file" name="files" id="ctrl_380" class="upload control-label form-control"></div>
          </div>
     </div>

Thanks in advance.

**Comment by kartik-v** [comment]
You can set `captionClass` and write your own CSS for the `span` within the caption.
