### ISSUE TITLE
Validate `overwriteInitial` correctly for ajax uploads

### ISSUE THREAD

**Issue by dalamberts** [kartik-v/bootstrap-fileinput#295]
Thank you so much for this plugin!

I have a file input defined as:
```
<input type='file' name='file4' id='file4' class='form-control'>
```

The plugin is setup as:. 
```
			$(document).ready(function() {
				$('#file4').fileinput({
					uploadUrl : 'https://my.hoodsocial.com/edit_document/118',
					uploadExtraData : function() {
						var obj = {};
						$('#add_form').find('input[type!=file], textarea, select').each(function() {
							var id = $(this).attr('name'), val = $(this).val();
							obj[id] = val;
						});
						return obj;
					},
					showUpload : false,
					showCaption : false,
					showRemove : false,
					browseClass : 'btn btn-primary',
					fileType : 'any',
					browseIcon : '',
					browseLabel : 'Select file',
					dropZoneEnabled : false,
					uploadAsync : false,
					overwriteInitial : true,
					initialPreview : ["<div class='file-preview-text'><h2><i class='glyphicon glyphicon-file'></i></h2></div>"],
					initialPreviewConfig : [{
						caption : 'millercoors2014healthfairresponsesheet.docx',
						width : '120px',
						url : '/documents/delete_file/118',
						key : 100,
						extra : {
							id : 100
						}
					}],
					layoutTemplates : {
						actions : "<div class='file-actions'><div class='file-footer-buttons'>{delete}</div><div class='clearfix'></div></div>"
					}
				});
```

It shows a file in the initialPreview and I have the overwriteInitial set to true.  I would expect that when I select a file that the content in the initial preview window would get over written but adds a second file into the preview.

Am I doing something wrong here?

**Comment by dalamberts** [comment]
If I remove both the uploadUrl and uploadExtraData, it works as expected.

**Comment by kartik-v** [comment]
This is resolved now.

**Comment by mhashimmaqbool** [comment]
After taking your latest Fileinput.js file, it leads with other Ajax upload issues, as well as Ui fixes. When I  upload a file, it shows a red caution at the bottom left corner without any error message but a title on it "Upload Error" even the file has been successfully uploaded over the server.

Other errors I found that, when upload a file it shows one red caution with one url upload hit on the server, selecting another file, show two cautions with two upload urls hit at the server. It increases as many times as the files being added in dropzone.

Following is my code which Im using to upload files:
$("#productImageUpload").fileinput({
    uploadUrl: product.uploadImageUrl,
    uploadAsync: true,
    showCaption: false,
    showRemove: false,
    showUpload: false,
    browseClass: 'btn btn-primary btn-block',
    browseIcon: '<i class="glyphicon glyphicon-camera"></i> ',
    browseLabel:  'Select Product Images',
    replaceFileInput: false,
    previewFileType: 'image',
    options : [{accept: 'image/*', multiple : true}],
    allowedFileExtensions : ['jpg', 'png','gif'],
    showClose: false,
    append: true,
    showUploadedThumbs: true,
    initialPreview: product.initialPreview,
    initialPreviewConfig : product.initialPreviewConfig,
    layoutTemplates: {
        progress: '<i class="fa fa-refresh fa-spin"></i>',
        footer: '<div class="file-thumbnail-footer">\n' +
                    '<div class="file-caption-name" style="width:{width}">{caption}</div>\n' +
                    '{progress} {actions}\n' +
                '</div>',
        actionUpload: '<button type="button" class="kv-file-upload {uploadClass}" title="{uploadTitle}">{uploadIcon}</button>\n'
    }
});


$('#productImageUpload').on('filepreupload', function(event, data, previewId, index) {
        var form = data.form, files = data.files, extra = data.extra, response = data.response, reader = data.reader;

        if(typeof previewId !== 'undefined') {
            var position = 0;
            var count = 0;

            $('.file-preview-thumbnails > div').map(function () {
                count++;
                if (this.id == previewId) {
                    position = count;
                }
            });

            form.append('position', position);
            form.append('productId', product.id);
        }
    });

    $('#productImageUpload').on('filepredelete', function(event, key, jqXHR) {
        if (!window.confirm('Do you wish to remove?')) {
            jqXHR.abort();
            event.preventDefault();
        }
    });

    if (product.isNewProduct) {
        $('#productImageUpload').on('filebatchuploadcomplete', function(event, files, extra) {
            $('.kv-upload-progress').hide();
            showGlobalMessage('Product successfully saved!', messageType.SUCCESS);
        });
    }

    $('#productImageUpload').on('filebatchselected', function(event, files) {
        if (product.id > 0) {
            $(this).fileinput("upload");
        }
    });
