### ISSUE TITLE
Deleting a selected image, removes previously uploaded images as well.

### ISSUE THREAD

**Issue by ktamashun** [kartik-v/bootstrap-fileinput#298]
You can try this on the following demo pages:
http://plugins.krajee.com/file-input-ajax-demo/3
http://plugins.krajee.com/file-input-ajax-demo/7

1. Remove the initial preview images.
2. Select an image, then upload it.
3. Select another image, but instead of uploading delete it. Now the image uploaded in step 2 is also removed.

**Comment by kartik-v** [comment]
It behaves as expected.

Note in scenario 3 for example after you have deleted all initial preview images - you only see an uploaded confirmation of the thumbnails on client. 

These are not the links to the uploaded images from server - but just volatile thumbnails on the client ... hence they will be cleaned up after every upload.

If you want to automatically replace the client thumbnails with the image links on your server check the ajax upload example 4(http://localhost:8000/yii-kvp/file-input-ajax-demo/4) or [ajax example 5](http://localhost:8000/yii-kvp/file-input-ajax-demo/5).

**Comment by kartik-v** [comment]
It behaves as expected.

Note in scenario 3 for example after you have deleted all initial preview images - you only see an uploaded confirmation of the thumbnails on client. 

These are not the links to the uploaded images from server - but just volatile thumbnails on the client ... hence they will be cleaned up after every successful upload.

If you want to automatically replace the client thumbnails with the image links on your server check the [ajax upload example 4](http://plugins.krajee.com/file-input-ajax-demo/4) or [ajax example 5](http://plugins.krajee.com/file-input-ajax-demo/5).

**Comment by kartik-v** [comment]
Refer enhancement #299 - that will help you out address this.
