### ISSUE TITLE
Enhancements for displaying uploaded file thumbnails

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#299]
Enhance the plugin to include a new property `showUploadedThumbs`. This will default to `true`. Previously uploaded thumbs were cleared when a second batch of files were selected for upload... but this can now be persistently displayed using this property.

When `showUploadedThumbs` is set to `true`, the uploaded file thumbnails will not be cleared from the client preview -- UNTIL the REMOVE or CLEAR button is explicitly pressed.

**Comment by periyakannan** [comment]
@kartik-v   while uploading multiple image with delete after submit button. deleting the single preview  image ..other images listed in preview but aftersubmit i cant get the other images.
