### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data.

### ISSUE THREAD

**Issue by abugroup** [kartik-v/bootstrap-fileinput#301]
I got this error while upload the image

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data.

< !DOCTYPE html>
< !-- release v4.2.1, copyright 2014 - 2015 Kartik Visweswaran -->
< html lang="en">
    < head>
        < meta charset="UTF-8"/>
        < title>Krajee JQuery Plugins - &copy; Kartik</title>
        < link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
        < link href="fileinput.css" media="all" rel="stylesheet" type="text/css" />
        < script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        < script src="fileinput.min.js" type="text/javascript"></script>
        < script src="fileinput_locale_LANG.js" type="text/javascript"></script>
        < script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" type="text/javascript"></script>
    < /head>
    < body>
        < div class="container kv-main">            
            < form enctype="multipart/form-data">               
                < input id="input-id" type="file" class="file" data-preview-file-type="text" >
            < /form>  
        < /div>
    < /body>
	< script>
    $("#input-id").fileinput({'showUpload':true, 'previewFileType':'any', 'uploadUrl':'http://localhost/magento/excel/image/upload/'});
	< /script>
< /html>

**Comment by kartik-v** [comment]
Duplicate to #107 and #127.
