### ISSUE TITLE
Preview data of video and audio files revoked too soon.

### ISSUE THREAD

**Issue by yarix** [kartik-v/bootstrap-fileinput#305]
a video (or audio) preview file is revoked immediately (like every other file), the problem is that the preview of video becomes buggy.
the user can start viewing the video, but once the user try to seek on the video, there is a 404 exception on the browser, and the video player can't play the video.

steps to reproduce (on version 4.2.1)
1. go to http://plugins.krajee.com/file-input/demo
2. click the 1st Browse button.
3. select a video from your computer
4. play the video on the preview 
4.1 expected: video is played.
5. move the seek bar to the end or to the start of the video
5.1 expected: video played where the seek indicator is.
5.1.1 BUG: video is not played.

from initial investigation i see that if I comment out line objUrl.revokeObjectURL(previewData), the preview works fine.
reader.onloadend = function () {
    msg = msgProgress
    .repl('{index}', i + 1).repl('{files}', numFiles)
    .repl('{percent}', 50).repl('{name}', caption);
    setTimeout(function () {
    $status.html(msg);
    //objUrl.revokeObjectURL(previewData);
}, 100);

**Comment by kartik-v** [comment]
The `revokeObjectURL` was needed to clean up client memory on browser - you will need to check the impact of commenting this - when you try to select multiple files for preview.

**Comment by kartik-v** [comment]
Have provided an enhancement you may check now.
