### ISSUE TITLE
bad russian

### ISSUE THREAD

**Issue by NewsBUZZ** [kartik-v/bootstrap-fileinput#311]
https://github.com/NewsBUZZ/bootstrap-fileinput/commit/c61ae193db99e41115a849ff4575e712ba9c4f37

**Comment by kartik-v** [comment]
You need to use the `{files}` tag which will be replaced with `fileSingle` or `filePlural` in the translation file

**Comment by NewsBUZZ** [comment]
In Russian differs ending
1 файл
2,3,4 файла
5,6,7 файлов

**Comment by kartik-v** [comment]
Ok - will use your fix then...
