### ISSUE TITLE
Can't upload multiple images

### ISSUE THREAD

**Issue by speedDeveloper** [kartik-v/bootstrap-fileinput#312]
My code looks like this:
```
$("#input").fileinput({
        minFileCount: 1,
   	maxFileCount: maxImages,
    	uploadExtraData: {
        	userId: 100,
        	userName: "Kartik"
    	}
    });
```
I also added the multiple attribute to the input.
If I want to add my second image then the first is replaced.

**Comment by kartik-v** [comment]
Use this project page only for logging issues or enhancements.

Please post help and coding support issues on the [discussion section of the plugin site](http://plugins.krajee.com/file-input#comments).

In your case above you have not provided the `uploadUrl` parameter, which is needed for ajax uploads. If you are not provided `uploadUrl`, the plugin will treat it like a normal form based upload which will not allow you to append files and other such stuff supported only in ajax uploads. Read the documentation in detail to understand what are the options available. Especially read [plugin usage of what is supported in ajax and form modes](http://plugins.krajee.com/file-input#usage-modes).
