### ISSUE TITLE
Move the upload button?

### ISSUE THREAD

**Issue by AlexioVay** [kartik-v/bootstrap-fileinput#313]
Can I move the upload button somehow so it's not inside this <input> template? I'm loading a bootstrap modal in my website script and I have a "standard-button" at the bottom right position of the modal and I want the upload button to replace that button. How could I do that?

**Comment by kartik-v** [comment]
By reading the docs as there are many options that you can do to achieve your use case.

You need to go through [plugin options](http://plugins.krajee.com/fileinput#options")

You can set `showUpload` to `false` and trigger the `upload` method. You can use the various `templates` related properties to change templates etc... many ways to do this.

**Comment by kartik-v** [comment]
By reading the docs as there are many options that you can do to achieve your use case.

You need to go through [plugin options](http://plugins.krajee.com/file-input#options)

- You can use the various `templates` related properties to change templates 
- You can set `showUpload` to `false` and trigger the `upload` method separately via another button. 

...etc... many ways to do this.
