### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by Emyleen** [kartik-v/bootstrap-fileinput#314]
Hello, I'm sorry but the language version doesn't work. I added the 2 files fileinput.js and fileinput_locale_fr.js and nothing change, buttons are always in english. 
Can you help me? 
And options doesn't work anymore, like showUpload : false, the button upload is always here...
Thank you for your help.

**Comment by kartik-v** [comment]
You need to set the language property. Read the docs for [plugin options](http://plugins.krajee.com#options).

**Comment by JessicaPuebla** [comment]
I already set the language property and included the locale, it doesn´t work.
The same issue with icons. 

$("#img-producto").fileinput({
	theme: 'fas',
        language: 'es',
});

And I also include in my file

<script src="vendor/fileinput/themes/fas/theme.js"></script>
<script src="vendor/fileinput/js/locales/es.js" type="text/javascript"></script>

Help!

**Comment by DarthSonic** [comment]
I have the same problem. Can not find any solution for months now :-(

**Comment by ProjectLinde37** [comment]
Problem still not solved

Loaded following files : 
<script type='text/javascript' src='assets/bootstrap-fileinput/5.5.3/js/fileinput.min.js' referrerpolicy='origin'></script>
<script type='text/javascript' src='assets/bootstrap-fileinput/5.5.3/themes/bs5/theme.min.js' referrerpolicy='origin'></script>
<script type='text/javascript' src='assets/bootstrap-fileinput/5.5.3/js/locales/nl.js' referrerpolicy='origin'></script>

And have the input configured
$(document).ready(function() {
    $('#DOCUMENT').fileinput({
	    language:'nl',
	    'showUpload': false,
	    'previewFileType': 'any',
	    // custom button icons
    });
});
