### ISSUE TITLE
maxFileCount 1 does not overrite the initial preview image

### ISSUE THREAD

**Issue by zach2825** [kartik-v/bootstrap-fileinput#316]
I would like to say I really like your plugin thank you for letting everyone use it.

So, if i set the maxFileCount to one and set an initial preview when I upload a new image the original image preview does not go away it stays then after I upload another image it removes the first to as expected and sets the new preview. 

Thank you in advanced.

**Comment by zach2825** [comment]
I found a figured out a workaround 

If you add .fileinput('reset') after the object is initialized.

**Comment by kartik-v** [comment]
If you want only ONE image to be uploaded - there is a simpler and better way... JUST DO NOT set `multiple` attribute of the file-input element markup - it will be treated as a single file upload each time.
