### ISSUE TITLE
ImagePreview does not change after updating form remotely

### ISSUE THREAD

**Issue by ElvinEfendi** [kartik-v/bootstrap-fileinput#317]
I have a form with some text inputs and a file input that uses this plugin for image preview and https://github.com/JangoSteve/remotipart for remote file upload. After selecting an image to upload and submitting the form if the data is not valid later it is not possible to update image preview by choosing another image.

**Comment by kartik-v** [comment]
Not sure with what and how you are doing. The demo pages have some examples of how plugin behaves after any validation error and how you can add files to preview even after an error.
