### ISSUE TITLE
Add another file after first browse

### ISSUE THREAD

**Issue by anthonybriand** [kartik-v/bootstrap-fileinput#318]
It would be interesting to add files after the first selection.

Let me explain: I click Browse, I choose one / several file once selected I realize I'm missing a file, if I want to add this file to the current selection currently I can't.

Another case, I would select files that are in different folders, it is necessary that I click Browse I select the files in the first folder, but currently can not add the files of the second folder to the selection.

**Comment by kartik-v** [comment]
The file dialog shown on clicking browse is a browser specific functionality (that you see when you use a HTML file input). So there is nothing which the plugin can do to change the browser offered feature.

There is an alternative feature which the plugin offers which is DRAG & DROP where you can select files across and drop to the file zone. This is applicable you use ajax upload of usage in the plugin (read docs for the [modes](http://plugins.krajee.com/file-input#usage-modes).
