### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by gordon-matt** [kartik-v/bootstrap-fileinput#319]
This looks like a very nice plugin, thanks for the hard work. However, I downloaded it today for testing and I cannot get the otpions to work. I just tried something very simple:

$("#Upload").fileinput({
        showUpload: false,
    });

The file input looks very beautiful now, but I cannot remove the upload button and I have tried some other options like allowedFileExtensions as well and they also don't work... is there a problem with the latest build or am I doing something stupid when passing in the options?

**Comment by kartik-v** [comment]
You may want to read the docs. It seems you have the `class = file` set on your HTML file input markup. If you set `class = file` on your input, the plugin will auto initialize.

That is why it is not registering your custom javascript init. You need to remove `class = file` if you are initializing via javascript. Check the docs and demo examples carefully.

**Comment by gordon-matt** [comment]
Thank you for such a quick response and for such an amazing file uploader. Keep up the good work!
