### ISSUE TITLE
Incorrect file "selected" count

### ISSUE THREAD

**Issue by silentwarrior** [kartik-v/bootstrap-fileinput#321]
Hello.

When I drag n drop files into the dropzone I get incorrect behavior.

If I drop 2 files, it will say exactly the same it did when I dropped 1 file (http://puu.sh/ikMEB/2de1018d75.png).
If i drop in 3 files, it will say 2 files selected (http://puu.sh/ikMCL/9ac7521b82.png).

**Comment by silentwarrior** [comment]
I was using 4.1.7, now 4.1.9 the behavior I experience is :

Sequencially added (1 by 1, drag n dropped)
One file : http://puu.sh/ikN9u/86a4674e5e.png
Two files : http://puu.sh/ikNaP/8f1e726b82.png
Three files : http://puu.sh/ikNbS/dbf70a516b.png

Multiple added (drag n drop multiple)
Two files : http://puu.sh/ikNfX/076e5096c6.png
Three files : http://puu.sh/ikNhp/fe1f152eb0.png

As you can see, the experience I get with sequencial or multiple is different.

**Comment by kartik-v** [comment]
The latest stable release is v4.2.0 and not v4.1.9. Not sure why you are working with a older version.

In addition, more other enhancements are available in upcoming v4.2.1 that you can pick from dev-master.

**Comment by silentwarrior** [comment]
Hello.

I just did a bower update and that's the version it grabbed.

Can you update the bower deployment ?

On Thursday, June 11, 2015, Kartik Visweswaran <notifications@github.com>
wrote:

> Closed #321 <https://github.com/kartik-v/bootstrap-fileinput/issues/321>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kartik-v/bootstrap-fileinput/issues/321#event-328609660>
> .
>


-- 
Regards
SilentWarrior

**Comment by silentwarrior** [comment]
Hi there,

You’ve been invited by Joao to join the Dropbox Campus Cup! Campus Cup lets you team up with your classmates to earn up to 25 GB of free Dropbox space for two years!

To earn space, just invite friends and use Dropbox to share, collaborate, and get work done.

Join Campus Cup![2]

Note that you must be a student currently enrolled at a higher education institution in order to participate. Learn more about Campus Cup.[3]

Happy Dropboxing!


 
 Work together, win together. 

____________________________________________________
If you prefer not to receive invites from Dropbox, please go here[4].
Dropbox, Inc., PO Box 77767, San Francisco, CA 94107

[1]: https://www.dropbox.com/l/zlvuMASvaT87OS3ZXbcsEw/campuscup?text=1
[2]: https://www.dropbox.com/l/ByrAHZz423el8pYCHY9oRo/campuscup?text=1
[3]: https://www.dropbox.com/l/yDK7QbZ2AwrzsVSgrL7k4h/help/9131?text=1
[4]: https://www.dropbox.com/l/o36H5Kr7ltWStm9lepewrE?text=1
