### ISSUE TITLE
When individually deleting all files, state does not update as it it was empty

### ISSUE THREAD

**Issue by silentwarrior** [kartik-v/bootstrap-fileinput#322]
When I individually delete all files, it wont go back to the empty state, and look wierd like this : http://puu.sh/ikMHO/08a63ce8c5.png

I expected it to go to this: http://puu.sh/ikMLf/a0d0329ab2.png like it does when you cancel or press the X on the top

**Comment by kartik-v** [comment]
Cannot replicate your use case. Can you check on demo site (the ajax demos) and let know if that happens?

If it happens only on your environment - ensure you have the updated code from dev-master.
