### ISSUE TITLE
Image Dimension restriction issue

### ISSUE THREAD

**Issue by gmansata6290** [kartik-v/bootstrap-fileinput#324]
Hi Kartik, Can you just show me a small example how i can restrict the user to upload the images not matching the dimension criteria or can you guide me in this ? I am new to jquery. I dont know much about jquery. I have done the coding this way ..... how to write a custom error for bootstrap file upload?

var $input = $("#file");
        $input.fileinput({
            uploadUrl: URL, // server upload action
            previewFileType: "image",
            uploadAsync: false,
            showUpload: false, // hide upload button
            showRemove: false, // hide remove button
            allowedFileExtensions: ['png'],
            maxFileCount: 1,
        }).on("filebatchselected", function (event, files) {
            // trigger upload method immediately after files are selected
            $input.fileinput("upload");
        });

        var _URL = window.URL || window.webkitURL;
        $("#file_iPhone").change(function (e) {
            var file, img;
            if ((file = this.files[0])) {
                img = new Image();
                img.onload = function () {
                    if (img.width != 480 && img.height != 248) {
                        alert("Please upload an image with dimension (width X height) as 480 X 248.")
                        return false;
                    }
                };
                img.src = _URL.createObjectURL(file);
            }
        });

**Comment by kartik-v** [comment]
Refer enhancement #328.
