### ISSUE TITLE
Drag & Drop issue

### ISSUE THREAD

**Issue by gmansata6290** [kartik-v/bootstrap-fileinput#325]
Kartik, 

if you drag & drop the file on the file input control. Then this file you cant access on the server side before uploading, on the click of a submit button. And even require validation of Html5 cant validate this properly. for this i have attached a screen shot below. please look at this.....

![image](https://cloud.githubusercontent.com/assets/12854378/8145845/047e9878-1237-11e5-98b8-a3b24d0a4ea7.png)

**Comment by kartik-v** [comment]
Please read docs. Especially the [plugin usage modes](http://plugins.krajee.com/file-input#usage-modes) as this is a question asked by many. Read the [browser support section](http://plugins.krajee.com/file-input#browser-support) to understand features supported.

Plugin can be configured to work in one of the modes:
- AJAX
- FORM SUBMISSION

Drag and drop only works for AJAX mode and it does not work with a form or use native HTML input features - so no data is sent to server on form submission.

As highlighted in docs DO not combine FORM SUBMISSION with AJAX.

**Comment by kartik-v** [comment]
Please read docs. Especially the [plugin usage modes](http://plugins.krajee.com/file-input#usage-modes) as this is a question asked by folks who are new to using the plugin. Read the [browser support section](http://plugins.krajee.com/file-input#browser-support) to understand features supported.

Plugin can be configured to work in one of the modes:
- AJAX
- FORM SUBMISSION

Drag and drop only works for AJAX mode and it does not work when configured for submission with a form or use native HTML input features - so no data is sent to server on form submission.

As highlighted in docs DO not combine FORM SUBMISSION with AJAX.
