### ISSUE TITLE
File preview plugin? Not really an issue but a question.

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/bootstrap-fileinput#331]
Hi Kartik,

Do you have a plugin for displaying file previews? Supposing a user has uploaded a file on a comment form. I now display a list of comments on a page. But I want to show a "preview" or "preview icon" of the file. For an image it would be the actual image but for a PDF it would be a PDF icon etc.

Do you have anything for this?

James.

**Comment by kartik-v** [comment]
Currently not there - probably as a new extension when I get time.
