### ISSUE TITLE
How to install version 4.2.1 using Nuget in VS 2013

### ISSUE THREAD

**Issue by gmansata6290** [kartik-v/bootstrap-fileinput#332]
how to install newer version in Visual Studio using Nuget Package Manager?

**Comment by kartik-v** [comment]
Actually the nuget package versions have not been bumped. This will happen from next release. Noting an enhancement.

**Comment by gmansata6290** [comment]
OK, No issues. I have to replace the files. That's the only solution I have.

**Comment by kartik-v** [comment]
Resolved via upgrade to [release v4.2.2](https://github.com/kartik-v/bootstrap-fileinput/commit/963ab33aad3bceebe906437382e1a5aaa05ae754).
