### ISSUE TITLE
Image upload but plugin show error

### ISSUE THREAD

**Issue by D3adkill3r** [kartik-v/bootstrap-fileinput#333]
guys, i started using this plugin but i'm with some problems. When i upload an image or many images, the upload looks like work fine, in my folder "uploads" i can see all images that i uploaded. But, the plugin give me a error as if I had not done the upload. I get two erros at the time, the first is when i set "uploadAsync: false" then i get the error "SyntaxError: Unexpected end of input.". The second is when i set "uploadAsync: true" or not set (default is true), then i get the error "imageName.jpg: [object Object]" (jpg is a example). So, i have no ideia what this is, I searched on many foruns but i found nothing like my problem. Someone can help me?

**Comment by kartik-v** [comment]
You seem to not be sending data from your server code correctly.

Before using - read the plugin [ajax upload requirements and docs](http://plugins.krajee.com/file-input#ajax-uploads) - and what your server code MUST receive and send for the plugin to recognize the successful upload.
