### ISSUE TITLE
FIlter minImageWidth and minImageHeight doesnt work

### ISSUE THREAD

**Issue by corvel** [kartik-v/bootstrap-fileinput#334]
Hi i have problem with your bundle.I have updated to 4.2.1 version so i should be able to use minImageWidth and minImageHeight. But is doesnt work at all. maxFileSize option is working fine.
Can you help me?

**Comment by kartik-v** [comment]
Check the code with example [on the demo site](http://plugins.krajee.com/file-input/demo#image-dimensions). The example has `minImageWidth` and `minImageHeight` of 50px... try to upload an image less than this width to see the error.

**Comment by corvel** [comment]
im using this code 
                if ($this.attr('data-type') === 'image') {
                    $.extend(options, {
                        fileTypeSettings: {
                            image: function(vType, vName) {
                                return (typeof vType !== 'undefined') ? vType.match('image/png|image/jpeg|image/pjpeg') : vName.match(/\.(png|jpe?g)$/i);
                            }
                        },
                        allowedFileTypes: ['image'],
                        allowedFileExtensions: ['jpg', 'png', 'jpeg'],
                        maxFileSize: 1000,
                        minImageWidth: 600,
                        minImageHeight: 400,
                    });
maxFileSize is working, but minImageWidth and minImageHeight not

**Comment by kartik-v** [comment]
Cannot unfortunately help debug your code... you would need to check what file you are testing and what is the expectation by cross checking.

As I said, crosscheck with example [on the demo site](http://plugins.krajee.com/file-input/demo#image-dimensions). The example has `minImageWidth` and `minImageHeight` of 50px... try to upload an image less than this width and test to see if you are getting the validation done by the plugin. Based on that you need to study the same and debug your code and files to understand if you are doing it correct for your use case.
