### ISSUE TITLE
Checking file checksum bevore uploading

### ISSUE THREAD

**Issue by cborchmann** [kartik-v/bootstrap-fileinput#343]
Hallo,

thanks for the nice plugin.

I use a simple md5 checksum to prevent double uploads of a file.

Is there a way to check the exisitence of the file against the md5 hashes stored in my database bevore upoading the file? 

Thanks for your help!

Christian

**Comment by kartik-v** [comment]
Validate this in your server code that processes the upload and return an error message (in the json encoded response) against each file uploaded.
