### ISSUE TITLE
HTTP 408 Request timeout after long upload

### ISSUE THREAD

**Issue by gnutix** [kartik-v/bootstrap-fileinput#344]
After a quite long upload, I've got this error as a response from the AJAX call : 
```
HTTP Error 408: The server timed out while waiting for your request
The server did not receive a complete request within a certain amount of time

If you are on a very slow network connection you might try the request again. If the problem keeps occurring the problem may be due to some incompatible browser you are using.
```

However, the request is still correctly processed in my PHP framework. Any idea why would Apache substitute the response the framework provide by a 408 ?

**Comment by kartik-v** [comment]
Cannot reproduce your case.

You may want to check if you are returning the right response from your server code. Read the plugin [ajax upload requirements and docs](http://plugins.krajee.com/file-input#ajax-uploads) - and what your server code MUST receive and send for the plugin to recognize the successful upload.

Then debug using Chrome Developer tools or Firebug (on Firefox)... to find whether you ajax request is sending or receiving the right data.
