### ISSUE TITLE
[question] Check sum of all selected files = TotalMaxFileSize

### ISSUE THREAD

**Issue by mehafi** [kartik-v/bootstrap-fileinput#345]
Is there a way to check TOTAL size of selected files ( sum of all selected files size )?
I found only maxFileSize property - but it checks size of one file only.

**Comment by kartik-v** [comment]
Size check is for each file only. You can achieve your use case to some extent by setting a fixed file limit per file via `maxFileSize` and enforcing `maxFileCount`. For example to limit total upload to 2500 MB... you can achieve it with `maxFileSize = 250` and `maxFileCount = 10`.

But for any variations and custom validations you currently need do the check on your server side and can return an ajax response to show an error message.
