### ISSUE TITLE
Opera Support

### ISSUE THREAD

**Issue by herward** [kartik-v/bootstrap-fileinput#347]
Plugin does not work in Opera as objectUrl remains undefined.
Opera does not support `441: objUrl = window.URL || window.webkitURL`.
So in my example it fails in `1770: previewData = objUrl.createObjectURL(file), fileCount = 0, j, msg, typ, chk,`.
No preview appears and no upload-buttons.
I updated Opera just a day ago to:
Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.17

Would be great if you could find a fix for line `441`.

Apart from this little issue its a great plugin! Thanks a lot.

**Comment by kartik-v** [comment]
Check [browser support for blob url here](http://caniuse.com/#feat=bloburls)... you may want to upgrade your old Opera version to a newer one. Version 9.8 is quite old... currently opera is crossed v30.

**Comment by herward** [comment]
Dear Kartik,
thanks for the info.
I thought my Opera was up-to-date because I did all the updates.
But my symbolic link pointed to opera.exe, whereas launcher.exe (in the 
same folder)
started the up-to-date version... :(
Everything is working fine.
Cheers
Herward

Am 12.07.2015 um 06:45 schrieb Kartik Visweswaran:
>
> Check browser support for blob url here 
> <http://caniuse.com/#feat=bloburls>... you may want to upgrade your 
> old Opera version to a newer one. Version 9.8 is quite old... 
> currently opera is crossed v30.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kartik-v/bootstrap-fileinput/issues/347#issuecomment-120686920>.
>


-- 
Herward Prehn
Dipl.-Ing. Maschinenbau

Wehrbergallee 55 / 24211 Schellhorn, Germany
fon       +49 (0)4342 / 7280 377
mobile    +49 (0)163 / 467 9545
