### ISSUE TITLE
Issues closing in Safari

### ISSUE THREAD

**Issue by toddaa** [kartik-v/bootstrap-fileinput#348]
I am creating the dialog like this:

var dialog = new BootstrapDialog.show({
    closable: false,
    size: BootstrapDialog.SIZE_WIDE,
    message: $("\<div>\</div>').load("newpage.php"),
    onshown: function(dialogItself){
        dialogItself.getModalBody().find('#btnBack').bind( "click", function(event) {
            dialogItself.close();
        });
    }
});
As you can see its pretty straight forward loading of another HTML page as defined in the documentation.  That part works fine.  Once the dialog is running I am setting the click event of an element inside the dialog to provide a close button functionality.  This seems to work in every browser I have tried except Safari.  When the button is pressed, and the close event fires parts seem to close, but main modal dialog remains.  Anyone ever heard of this before and know how to get around it?

**Comment by kartik-v** [comment]
Not related to the plugin... use this project repo to only log issues related to bootstrap-fileinput.

**Comment by toddaa** [comment]
My apologies.  Got my tabs mixed up and ended up putting that in the wrong repo.  Again - appologies
