### ISSUE TITLE
How to handle the custom error event ?

### ISSUE THREAD

**Issue by gmansata6290** [kartik-v/bootstrap-fileinput#349]
Hi kartik, 
As a newbie in web technologies practicing asp.net MVC. Can you guide me how should I handle the custom error event, when the file size is not matching the criteria and user tries to upload the same file even after the error occurs. I have already gone through your doc provided for the custom event and Event manipulation. But i could not get it, what steps i need to follow in the above mentioned situation.

**Comment by kartik-v** [comment]
Check [ajax scenario 9 demo](http://plugins.krajee.com/file-input-ajax-demo/9) for an example.
