### ISSUE TITLE
Event 'filebatchuploadcomplete' fires before all async uploads complete.

### ISSUE THREAD

**Issue by jaxuk** [kartik-v/bootstrap-fileinput#352]
I've been running into an issue uploading multiple items (6 images) where images will successfully upload but the preview pane may not display all of the uploaded items.

I attempted to force rebuilding the preview items on the event 'filebatchuploadcomplete' from an array of uploaded items but it seems this event sometimes fires before all of the items have been uploaded, which I suppose could be the cause of my original issue.

**Comment by kartik-v** [comment]
Not sure of your use case.

But if you are keen to refresh the preview - try using the more straightforward method. Refer [ajax demo scenario # 4](http://plugins.krajee.com/file-input-ajax-demo/4) to automatically generate the preview thumbnails by sending the `initialPreviewConfig` from your server upload response.

The same is available for synchronous upload as well in [ajax demo scenario # 5](http://plugins.krajee.com/file-input-ajax-demo/5).

**Comment by jaxuk** [comment]
Hi,

I am basically using scenario 4 with async enabled and returning the initialPreviewConfig and initialPreview on each server response. But the preview pane refreshes before all of the uploads are complete and therefore is missing some of the uploaded files. 

If the files are all very small it works, if the files are larger or take longer to upload the issue occurs. It looks like it's not waiting for all of the uploads to complete before refreshing the preview pane. 

The same is try of the 'filebatchuploadcomplete' event.

**Comment by jaxuk** [comment]
Further more to this, it only seems to be an issue when setting the option 'ajaxsettings', after removing the settings I made with this option it all works great!
