### ISSUE TITLE
Prevent deleting current photos while uploading on the second time

### ISSUE THREAD

**Issue by ido567** [kartik-v/bootstrap-fileinput#353]
When I add photos for the second time, the photos that I added on the first time disappears.
How can I make the new photo to be added to the old one?
```html
<input class="memory-image-file form-control" accept="image/*" multiple="true" name="pictures[]" type="file">
```

```javascript
$('.memory-image-file').fileinput({
    allowedFileExtensions : ['jpg', 'png'],
    showUpload: false
});
```

**Comment by kartik-v** [comment]
Before using the plugin read documentation thoroughly. Understand the [usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes) and what is possible OR NOT POSSIBLE. You are using a normal form submission mode which relies on native HTML file input features and does not offer many features. The plugin offers an ajax mode of upload which offers features but requires you to set up the uploadURL for upload in the right.
