### ISSUE TITLE
Add additional files without ajax

### ISSUE THREAD

**Issue by ajbeaven** [kartik-v/bootstrap-fileinput#355]
It would be great to have the option of adding new files to the files already selected instead of replacing them. For instance:

1. Browse -> Select 3 files -> 3 files appear
2. Browse -> Select additional file -> 4 files now show

The UI side of this is exactly the same as what occurs when you specify uploadUrl. I'm guessing you would implement this by adding an additional hidden file input (with the same html input name) each time you select a new file.

My use case of attaching multiple files to an item that is only inserted into the database on submit makes implementing this with ajax a PITA.

This feature would in effect add support for multiple file uploading in browsers that don't support multiple file uploads natively (IE9 et. al.).

**Comment by kartik-v** [comment]
This is not in scope of the plugin... it basically works on the premise to work around using HTML 5 features for fileinput and filereader and xhr for ajax. For non-ajax scenarios native file input support does include MULTIPLE file upload - but it does not allow you to edit files. Its limited to this functionality. Support for older/outdated browsers is again not in scope.

You are still free to submit an enhancement PR if you have a better thought.

**Comment by ajbeaven** [comment]
Unfortunate but I totally understand. Will consider a PR if my users complain too much ;) Thanks for your work on this repo, it's superb.
