### ISSUE TITLE
Remove file uploaded using ajax

### ISSUE THREAD

**Issue by be4code** [kartik-v/bootstrap-fileinput#359]
After uploading file using Ajax there is no possibility (am I right?) to remove file.

For example when you open http://plugins.krajee.com/file-input-ajax-demo/8 and upload file, then click "remove" there is no "filepredelete" event called.

How can I change this behavior?

**Comment by kartik-v** [comment]
It all depends on what you need and how you configure the plugin. Read documentation and cross check the various ajax upload scenarios AGAIN.

Predelete only works for a server uploaded file that is set via `initialPreviewConfig`. 

So to achieve the delete of an ajax uploaded file you must set the `initialPreview` to show the server rpreview thumbnails. 

Cross check the [ajax scenario 4](http://plugins.krajee.com/file-input-ajax-demo/4) and [ajax scenario 5](http://plugins.krajee.com/file-input-ajax-demo/5) on how you can automatically show the initial preview after ajax upload.
