### ISSUE TITLE
[QUESTION] Image in preview but user would like to replace it with a new one

### ISSUE THREAD

**Issue by rogelio-blanco** [kartik-v/bootstrap-fileinput#360]
Hi Kartik, thanks for the awesome plugin.

I had an scenario that I don't know how to implement it, basically I would like to allow users to do search and override the previewed image if they don't want to upload the previous image.   Below are the steps that explain more my scenario.
 
Steps:
* I have the plugin in a modal where the user selects the image that he would like to upload, after he selected the image, they can see it in preview. (Note: the image is in preview is not uploaded)
* Now, as a user I would like to replace that image with another one, so the user click on search image and look for a new one.
* The user gets an error because is not allowed to upload 2 images at the time.
* Once I clear the preview section, the user can select a new image to be upload.

Here is my question: Is there a way that the user can replace the previewed image with a new one without an error?  There is a property or I need to clear the preview section and then execute the search?

**Comment by kartik-v** [comment]
If you are using without ajax - the files will automatically be replaced.

If you are using with ajax - images are appended by default. The `maxFileCount` controls how much you can select at a time... you must clear the files if you wish to overwrite.

**Comment by rogelio-blanco** [comment]
Kartik, maybe it could be a good enhancement to have a property where we can set it to true and allow the replace instead of throwing the error.   Seems that this make sense when we have the requirement to upload 1 image.

**Comment by kartik-v** [comment]
Resolved via #371 and as [mentioned in this comment](https://github.com/kartik-v/bootstrap-fileinput/issues/371#issuecomment-125037383).
