### ISSUE TITLE
form submit

### ISSUE THREAD

**Issue by pengzz1987** [kartik-v/bootstrap-fileinput#361]
use fileInput plugin in form,How to achieve the submission of the form of the time to upload attachments？

**Comment by kartik-v** [comment]
You need to use it like any other native file input and read via server code (note you cannot use ajax features of the plugin if you wish to read file data via form submission).

Read some [web tips](http://webtips.krajee.com/tag/bootstrap-fileinput/) on using file input plugin with server code.
