### ISSUE TITLE
Uncaught TypeError: Cannot set property 'pt-BR' of undefined

### ISSUE THREAD

**Issue by gandarez** [kartik-v/bootstrap-fileinput#364]
When using pt-BR locale throws an error at:
```javascript
$.fn.fileinputLocales['pt-BR'] = {
```

**Comment by kartik-v** [comment]
Read docs. You must load the `fileinput_locale_pt-BR.js` after `fileinput.js` is loaded.

Check the [demo example and pre-requisites mentioned for multi language](http://plugins.krajee.com/file-input/demo#multi-language).

**Comment by gandarez** [comment]
It's not working
![image](https://cloud.githubusercontent.com/assets/782854/9094834/6e28b99e-3b8a-11e5-815a-9201bb030663.png)
![image](https://cloud.githubusercontent.com/assets/782854/9094838/737275a2-3b8a-11e5-8fa0-8321af01d817.png)

**Comment by kartik-v** [comment]
As I mentioned you must read docs and demos closely. You need to set `language` property in addition to loading your files. 

Check the [Portugese Brazilian example](http://plugins.krajee.com/file-multi-lang-demo#portugese-br-input) on the demo page to understand.

**Comment by gandarez** [comment]
Didn't work as you mentioned.

**Comment by gandarez** [comment]
After update to latest version it has fixed.
