### ISSUE TITLE
Text preview overflows the container

### ISSUE THREAD

**Issue by open-minds** [kartik-v/bootstrap-fileinput#365]
The text preview is not always correctly shrinked and overflows the container.

Here is an example of CSV file content to reproduce the issue:
```
0123456789012, 00
0123456789012, 10
0123456789012, 20
0123456789012, 30
0123456789012, 40
0123456789012, 50
0123456789012, 60
0123456789012, 70
0123456789012, 80
0123456789012, 90
0123456789012, 00
0123456789012, 10
0123456789012, 20
0123456789012, 30
0123456789012, 40
0123456789012, 50
0123456789012, 60
0123456789012, 70
0123456789012, 80
0123456789012, 90
0123456789012, 00
```

A shrink of the content based on a number of lines instead of on a number of character seems to be best suited. As an alternative, an "overflow: hidden;" on the "file-preview-text" class is working fine also.

**Comment by kartik-v** [comment]
Check #377 - will be resolved via that.
