### ISSUE TITLE
Adobe Reader cannot display file preview

### ISSUE THREAD

**Issue by Focushift** [kartik-v/bootstrap-fileinput#366]
On pdf document select, Adobe Reader "Access denied".
I'm trying to use plugin on Sharepoint 2013 portal with Bootstrap 3.
Google not helps.

**Comment by Focushift** [comment]
Some additional info
IE11, PC in windows domain

in Chrome preview works but...better it not worked, document displayed with 100% scale. it's possible to set another scale in preview?

**Comment by kartik-v** [comment]
Again as in #369 this depends on the browser's ability to show embedded PDF - and is nothing that can be controlled from plugin.

However, if you want preview to be disabled across... you can set the [allowedPreviewTypes](http://plugins.krajee.com/file-input#option-allowedpreviewtypes) property to allow only these files to be previewed.

**Comment by shokhaa** [comment]
preview does not work for those files that are on the server

**Comment by shokhaa** [comment]
preview does not work for those files that are on the server
http://backend.arabic-school.org/storage/course-media/13/5d77c62f4ab41.doc
if I change it to any other file that is on another site, it will work without problems

**Comment by shokhaa** [comment]
In short, the review does not work for those files that are on my site

**Comment by shokhaa** [comment]
sorry my bad english

**Comment by shokhaa** [comment]
but if I use this link on my localhost then the preview to work!

**Comment by shokhaa** [comment]
@kartik-v  problem only is the office file and ggdocs
