### ISSUE TITLE
Files with Russian characters are not displayed correctly

### ISSUE THREAD

**Issue by Focushift** [kartik-v/bootstrap-fileinput#367]
![screen3](https://cloud.githubusercontent.com/assets/13481939/8872405/60e9121c-3205-11e5-98b1-9a144f1dcd79.PNG)

when i select file with russian characters, in preview pane name of file displayed without russian words. 
when i check source of page, there no characters.
But sometimes selected file name shown correctly in .input-group .file-caption-name.

Russian plugin is loaded.

**Comment by kartik-v** [comment]
Duplicate to #250. Use `slugCallback` property.
