### ISSUE TITLE
More intelligent duplicate files check

### ISSUE THREAD

**Issue by Focushift** [kartik-v/bootstrap-fileinput#369]
Example:

i have files 1, 2, 3
-if i add 1 and later try to add 1 again, nothing happens
-but! if i add 1, 2, 3 files, i can add 1 or 2 file and i wil get duplicates

tested on  v4.2.5

**Comment by kartik-v** [comment]
This is dependent on the browser and its inherent behavior (will only happen if you select files by clicking browse button where you use the native file input to select). 

Anyway there is no duplicate check separately possible (or intended). it depends on browser's inherent ability to track the same filename and local location. You may try it across browsers (other than Chrome) and check the behavior. Note that file with same names does not necessarily mean its duplicate.

**Comment by Focushift** [comment]
But, files with same path and names are duplicate.

**Comment by kartik-v** [comment]
As I mentioned currently there is no special validation built for this in the plugin. The native file input itself has this check built in within certain  browsers.
