### ISSUE TITLE
Ability to replace files in the preview

### ISSUE THREAD

**Issue by rogelio-blanco** [kartik-v/bootstrap-fileinput#371]
I could find a method that allows me to clear the preview just after the user would like to change the image from the preview.   See #360

**Comment by kartik-v** [comment]
New property `autoReplace` added. [Refer docs for autoReplace](http://plugins.krajee.com/file-input#option-autoreplace).

[Refer a demo of auto replacing files](http://plugins.krajee.com/file-input/demo#auto-replace) in preview based on `autoReplace` and `maxFileCount` setting.

**Comment by rogelio-blanco** [comment]
:+1:

**Comment by rogelio-blanco** [comment]
Work as a charm. Thanks
