### ISSUE TITLE
Create new event `filepreajax`

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#372]
New event `filepreajax` that can help parse and update extra data before ajax upload. Will address and resolve both #342 and #370.

**Comment by rogelio-blanco** [comment]
Any specific date for next release

**Comment by rogelio-blanco** [comment]
Could you please add a sample including extra data in the POST?

**Comment by kartik-v** [comment]
There is no change. You can send extraData like before. An example can be referred in [ajax demo scenario # 3](http://plugins.krajee.com/file-input-ajax-demo/3)

**Comment by rogelio-blanco** [comment]
:) Excellent
