### ISSUE TITLE
Problem with file preview (namely .odt and .doc files)

### ISSUE THREAD

**Issue by andrey-bahrachev** [kartik-v/bootstrap-fileinput#375]
Hey there!
First of all, many thanks for the great plugin, but I'm facing some weird gobbledygook in the file preview block when uploading .odt and .doc files (all created in OpenOffice).

![bootstrap-file-input-issue](https://cloud.githubusercontent.com/assets/597912/8988960/f0f1c4da-370a-11e5-92e5-aa26676cd28f.png)

Win7, browser: Chrome, plugin version 4.2.5, jQuery 2.1.4. Please let me know if you need to know any other details. Thanks!

**Comment by kartik-v** [comment]
Read docs. You can configure / control what types of files are to be previewed by setting the [allowedFileTypes](http://plugins.krajee.com/file-input#option-allowedpreviewtypes) and [allowedFileMimeTypes](http://plugins.krajee.com/file-input#option-allowedpreviewmimetypes).

**Comment by andrey-bahrachev** [comment]
Ah, sorry, I just missed that one, my bad. Made it work fine now. Thanks a lot Kartik, much appreciated! Maybe it'll help someone else:)
