### ISSUE TITLE
File upload indicator problem

### ISSUE THREAD

**Issue by Focushift** [kartik-v/bootstrap-fileinput#380]
In file preview frame, when hover on hand-down icon, height of frame increasing. 
Frame on next line shifting to the right leaving empty space to the left.

**Comment by kartik-v** [comment]
Could be a case specific to your preview thumbnail. Adjust the CSS classes where needed by passing the CSS Class property to your fileinput container and overriding CSS where needed.

**Comment by Focushift** [comment]
http://plugins.krajee.com/file-preview-icons-demo
add file, see the problem
