### ISSUE TITLE
Different sizes of file preview frames

### ISSUE THREAD

**Issue by Focushift** [kartik-v/bootstrap-fileinput#381]
Frame with image preview have 207px height. With document icon 192px.
If there more than 2-3 files, its looks like AbCdEf.

**Comment by kartik-v** [comment]
Again adjust this as you need for your use case... change settings of image height in previewSettings ... where needed.

**Comment by Focushift** [comment]
http://plugins.krajee.com/file-preview-icons-demo
but its "standard" settings, tested on plugin demo

**Comment by Focushift** [comment]
Sry ... but... now problem with text file preview frame)) 249px vs 217px height

**Comment by Focushift** [comment]
Maybe for text preview better to change font size to smaller?
