### ISSUE TITLE
Max/Min ImageWidth/Height rules errors

### ISSUE THREAD

**Issue by russ-ab** [kartik-v/bootstrap-fileinput#383]
There's a way to add errors when file break the rules of maxImageWidth, maxImageHeight, minImageWidth, minImageHeight?

Example: Set maxImageWidth: 100, maxImageHeight: 100, and select a 200x200 image, a warning appears, but the image still valid.

**Comment by kartik-v** [comment]
Handle this through your custom javascript on `fileimageloaded` event that shows an alert ... without triggering an error.

**Comment by russ-ab** [comment]
I need the file become invalid, the fileimageloaded event does not show anything about the warning of dimensions.

**Comment by kartik-v** [comment]
I do not understand. You as the developer needs to write the code to validate the image dimensions (e.g. `$('img').width() > maxWidth`).

I was mentioning that the validation code could be written inside the `fileimageloaded` event for example. Read about jquery events if not clear.

**Comment by russ-ab** [comment]
Understood.

```javascript

$('input').on('fileimageloaded', function (event, previewId) {
    var msg = '';
    var img = $('#' + previewId).find('img')[0];
    if (img.naturalWidth > maxImageWidth) {
             msg += 'Invalid Width';
    }
    
    if (img.naturalHeight > maxImageHeight) {
            msg += 'Invalid Height';
    }

    console.log(msg);
}
```

Thanks!
