### ISSUE TITLE
uploadExtraData with two fields that follow

### ISSUE THREAD

**Issue by jfc298** [kartik-v/bootstrap-fileinput#384]
Hi,
I use the option "uploadExtraData" with two input fields file that follow. 
<input id="field_1">
<input id="field_2">
...
<script>
var input = $('#field_1');
	input.fileinput({
		uploadUrl:'submit_file.php',
		uploadAsync: false,
		allowedFileExtensions : ['jpg', 'png','gif','pdf'],
		uploadExtraData: function() {
		return {
				i: 1,
				j: 2
							};
						},
						}).on("filebatchselected", function(event, files) {
							input.fileinput("upload");
							});
var input = $('#field_2');
	input.fileinput({
		uploadUrl:'submit_file.php',
		uploadAsync: false,
		allowedFileExtensions : ['jpg', 'png','gif','pdf'],
		uploadExtraData: function() {
		return {
				i: 3,
				j: 4
				};
						},
						}).on("filebatchselected", function(event, files) {
							input.fileinput("upload");
				});

When I submit a file in one field (input id="field_1") , it is the parameters of the fields 2 (i=3 and j=4) that are sent to the file " submit_file.php"
What for ?
by cons , if I submit a file to the field 2 , it works very well.

It looks like the plugin take the " uploadExtradata " take the values ​​of said fields last ...

If you have a idea... thanks :)

Jeff

**Comment by kartik-v** [comment]
Not clear with query. You can set uploadExtraData as a callback function to return input values at runtime.
