### ISSUE TITLE
Uncaught TypeError: Cannot set property 'pt-BR' of undefined

### ISSUE THREAD

**Issue by gandarez** [kartik-v/bootstrap-fileinput#386]
When using pt-BR locale throws an error at:
```javascript
$.fn.fileinputLocales['pt-BR'] = {
```

![image](https://cloud.githubusercontent.com/assets/782854/9094834/6e28b99e-3b8a-11e5-815a-9201bb030663.png)
![image](https://cloud.githubusercontent.com/assets/782854/9094838/737275a2-3b8a-11e5-8fa0-8321af01d817.png)

What am I missing out?

**Comment by kartik-v** [comment]
Avoid creating duplicate issues. Duplicate to #364.

[Refer the comment](https://github.com/kartik-v/bootstrap-fileinput/issues/364#issuecomment-128117626) in that issue.
