### ISSUE TITLE
initialCaption dissapears after fileclear event has rised

### ISSUE THREAD

**Issue by xmpbob** [kartik-v/bootstrap-fileinput#387]
Good job you guys doing!
I found this plugin and it doing his job very well but there was an issue which annoys me. This issue is with **initialCaption** when it is defined. When user choose a file which rise some error and then he removes the error the **initialCaption** doesn't shows up again. I found that this must be done when or after **fileclear** event rises.
This code below resolves my issue. You can include it or make it better.
```
if (self.initialCaption.length > 0) {
	self.setCaption(self.initialCaption);
}
```
I put it in **clear** function code before
```
	self.raise('filecleared');
```
Cheers,
bob

**Comment by kartik-v** [comment]
Your use case unfortunately cannot be generalized. For example, what if user deletes the initial preview files and then tries to select another file and clicks clear. If it shows an initial caption pertaining to the old deleted file - it will be incorrect.

I think this needs a bit more thought. Will update (probably with another option for this)

**Comment by kartik-v** [comment]
This is enhanced now with the latest commit.
