### ISSUE TITLE
Unable to remove a wrong file in the upload drag&drop zone

### ISSUE THREAD

**Issue by mad4hit** [kartik-v/bootstrap-fileinput#394]
Hi thanks for this amazing plugin!!!
i've noticed a problem: if i drag an unautorized file type in the drop zone, the plugin advise me that i can't upload it but i'm unable to remove from the zone. 

The only way to remove it is by clicking the general remove button that clear the area.

Suggetions:
Enabling the remove button
Temporizing the element so it disappear after an amount of time.

![2015-08-11_163449](https://cloud.githubusercontent.com/assets/5448105/9200186/e7e573b0-4046-11e5-8005-24370eec691a.png)

**Comment by kartik-v** [comment]
This will be resolved via enhancements as discussed in #400.

**Comment by mad4hit** [comment]
Thanks!
