### ISSUE TITLE
Server initialPreview NOT getting templated.

### ISSUE THREAD

**Issue by csmcgee** [kartik-v/bootstrap-fileinput#395]
After uploading a file. I just get the image and the delete (text) inserted into the list of files. Why isn't it templating a delete icon with the site url after a successful upload? Is this not possible?

```
{
  "initialPreviewConfig": {
    "url": "http:\/\/localhost\/avatar\/delete",
    "caption": "Screenshot from 2015-08-06 10:26:43.png",
    "key": 3,
    "width": 0,
    "extra": [
      
    ]
  },
  "initialPreview": [
    "<img src='\/images\/desert.jpg' class='file-preview-image' alt='Desert' title='Desert'>{actions}"
  ],
}
```

**Comment by kartik-v** [comment]
To directly add additional buttons to each thumbnail overwrite the [layoutTemplates.actions](http://plugins.krajee.com/file-input#option-layouttemplates) template.

For additional buttons or tags to render dynamically use the below:

For setting up your own custom buttons or icons or add your own custom markup within each thumbnail you need to use [initialPreviewThumbTags](http://plugins.krajee.com/file-input#option-initialpreviewthumbtags) for initial preview or [previewThumbTags](http://plugins.krajee.com/file-input#option-previewthumbtags) for normal preview.

Note that you need to edit `layoutTemplates.footer` property to define custom codes.
