### ISSUE TITLE
event.preventDefault() doesn't work

### ISSUE THREAD

**Issue by zhangyaoxing** [kartik-v/bootstrap-fileinput#396]
didn't try all the events, just tried with `filepreajax`. sample code:

    $("#fileinput").on('filepreajax', function(event, previewId, index) {
        event.preventDefault();
    });

as to my understanding, when I invoked `preventDefault()`, ajax upload is supposed to be cancelled.  this makes sense because the point of this event is that you can upload extra info to server together with files. what if the extra info is verified to be invalid? then I need to stop the upload action and send an error message to user. currently I didn't find a way to stop the files from being uploaded.
any idea what should I do?

**Comment by zhangyaoxing** [comment]
Oh, besides I didn't find a way to pass extra data, any idea how I can do that?

**Comment by kartik-v** [comment]
You need to use events manipulation feature of the plugin to return an associative array containing `message` and `data` to abort the upload.

Check [ajax scenario 9](http://plugins.krajee.com/file-input-ajax-demo/9) for an example... it uses `filebatchpreupload` event in the example there but you could use it with other events (except a few events listed in docs).

**Comment by zhangyaoxing** [comment]
I tried it this way:

    $("#input").on('filepreajax', function(event) {
        // some verifications
        return {
            message: "there is an error!",
            data: {}
        };
    }).on('filecustomerror', function(event, params) {
        // show error message to user
    });

So the uploading seems to be stopped. however, the control is now disabled as show below:
![image](https://cloud.githubusercontent.com/assets/2239306/9219959/5bd94736-4111-11e5-8645-b375dc8e4bbb.png)
I cannot upload anything now. what did I do wrong?

**Comment by kartik-v** [comment]
> I cannot upload anything now. what did I do wrong?

You do not have the updated extension code from dev-master... the release is not tagged yet. Pick the code from master.

**Comment by zhangyaoxing** [comment]
Hmm, just tried latest code from master, it shows me the version 4.2.6, is that correct version I'm supposed to use? The issue remains the same however. Any idea what I should do to trouble shoot the issue?

**Comment by kartik-v** [comment]
Retry after clearing browser cache and restart. You can check with other events as well as mentioned in demo.

**Comment by BetaFlasher** [comment]
zhangyaoxing, I faced the same problem, but I found a simple solution which works in my case:
Just set "showPreview" option to "true", because if it is set to "false" then the upload button stays disabled. Bug?
