### ISSUE TITLE
remove image event

### ISSUE THREAD

**Issue by cazacugmihai** [kartik-v/bootstrap-fileinput#399]
Hi,

Is there an event triggered by removing an image (one image, not all of them) from a list of images? 

I checked the [docs](http://plugins.krajee.com/file-input#file-events) but none of those events are triggered after pressing "remove" button in preview panel.

Thanks,
Mihai

**Comment by kartik-v** [comment]
Refer #401 for all enhancements.

**Comment by cazacugmihai** [comment]
Thanks! It works now. :)
