### ISSUE TITLE
Could not upload multiple files with 1 unsupported file in it.

### ISSUE THREAD

**Issue by pranayboddu** [kartik-v/bootstrap-fileinput#400]
Hi,
when trying to upload multiple files with at least 1 unsupported file format in the batch, the files after the unsupported file type are not being loaded. I'm attaching a screen shot.
![multiple](https://cloud.githubusercontent.com/assets/13729677/9246640/92cc8082-41ca-11e5-8ba2-52a5c235342c.png)
The loader and the loading validation message doesn't seem to go upon pressing the remove button.

**Comment by kartik-v** [comment]
It seems there is some JS exception. You need to check your javascript console for errors.

**Comment by kartik-v** [comment]
This will be resolved via various new enhancements to file selection in preview.

**Comment by kartik-v** [comment]
Refer #401 for all enhancements.
