### ISSUE TITLE
fileinput.js:1538 Uncaught ReferenceError: keys is not defined

### ISSUE THREAD

**Issue by florinmtsc** [kartik-v/bootstrap-fileinput#403]
uploadAsync false > filebatchuploadsuccess event not reached. 

<code>fileinput.js:1538 Uncaught ReferenceError: keys is not defined</code>

**Comment by kartik-v** [comment]
Cannot reproduce your use case. Check if you have the updated code. Thiis [scenario works fine on the demo page](http://plugins.krajee.com/file-input-ajax-demo/1), which you can cross check.

If you still face the error... post a link to JS Gist or something to check.

**Comment by sosojni** [comment]
I have same problem when i set uploadAsync: false,
kartik-v, demo you linked is async and me and florinmtsc have both problem in sync mode

my view:
```
<?php
use kartik\widgets\FileInput;
use yii\helpers\Url;

echo FileInput::widget([
  'name' => 'files[]',
  'options' => ['multiple' => true],
  'pluginOptions' => [
  'uploadUrl' => Url::to(['/order/upload']),
  'uploadAsync' => false,
  ]
]); 
```
My controller:
```
public function actionUpload()
    {
        return json_encode(['errors' => 'test', 'errorkeys' => [0]]);
    }
```

am i returning something wrong? It only happens in synchronous mode and only if i press upload button that uploads whole batch, if i press upload on each file preview it's working fine.

**Comment by sosojni** [comment]
Ok i got my code up and running w/o errors after i changed:

1) my Controller to:

        return json_encode(['error' => 'test', 'errorkeys' => [0]]);
2) fileinput.js:
 from: keys = isEmpty(data) || isEmpty(data.errorkeys) ? [] : data.errorkeys;
to: var keys = isEmpty(data) || isEmpty(data.errorkeys) ? [] : data.errorkeys;

As i'm in great hurry, i dont have time to see if this breaks something somewhere else, but it does fix this problem and i get functionality i need.
