### ISSUE TITLE
Access to new loaded previewConfig by key

### ISSUE THREAD

**Issue by beerteam** [kartik-v/bootstrap-fileinput#404]
I can't access to new loaded file by key. I have "otherActionButtons" button "edit" (crop and name functional), but when i click and get key, i not understand: how i get data by key? In uploadCache data not stable, initialPreviewConfig not have my "new file data".

Thank you

**Comment by kartik-v** [comment]
As mentioned in documentation for [otherActionButtons](http://plugins.krajee.com/file-input#option-otheractionbuttons) - the `dataKey` is intended only for `initialPreviewConfig` i.e. files on server.

If you want actions on client file (not on the server)... then directly use jquery to get the image source by traversing to the button's parent.
