### ISSUE TITLE
 Customize the exception message.

### ISSUE THREAD

**Issue by pranayboddu** [kartik-v/bootstrap-fileinput#406]
Hi Kartik,

Firstly thank you for your support on the Issue #400.

Clicking on the cancel button when the file is uploading the system is displaying the exception message as "File name" : [object Object]. And upon canceling the upload the file is yet being uploaded.

![exception](https://cloud.githubusercontent.com/assets/13729677/9303607/f7f5a42c-44fc-11e5-8cb9-24532bff69f1.png)

**Comment by kartik-v** [comment]
Refer #412. Use new property `msgUploadAborted` to control message.

In addition - note that cancelling upload just initiates aborting of the ajax request. Usually for large files it will work as intended. It basically depends at what stage the user clicks cancel. If the ajax request has posted data on the server and still not complete - you can cancel it but it will have posted/uploaded files but not completed the entire transaction.
