### ISSUE TITLE
fileinput does not allow to open same file after removing in IE10

### ISSUE THREAD

**Issue by xplicit** [kartik-v/bootstrap-fileinput#407]
fileinput does not allow to select file which was previously removed in IE10.

Steps to reproduce: 
open http://plugins.krajee.com/file-basic-usage-demo use basic1 demo
press browse button and select file test.txt (zero-sized)
press remove button
press browse button and select file test.txt again

Actual result: 
The file is not shown in the fileinput control

Expected result:
File test.txt is shown in the fileinput control

It works fine in firefox browser.

**Comment by kartik-v** [comment]
Related to #410

**Comment by xplicit** [comment]
When I changed isIE function to correct one, all is working as expected
