### ISSUE TITLE
fileinput 'clear' function does not work in IE10

### ISSUE THREAD

**Issue by xplicit** [kartik-v/bootstrap-fileinput#408]
`fileinput("clear")` function does not clears input box in IE 10

Steps to reproduce: 
Create file input with multiple upload settings.
Browse and select file to upload.
call `$(elem).fileinput("clear")` function
browse and select another file to upload.

Actual result:
Two files are shown in upload control
Expected result:
Only second file should be shown in upload control.

In other browsers (firefox, chrome, IE11) it works fine.

**Comment by kartik-v** [comment]
Related to #410.
