### ISSUE TITLE
How can I dynamically set custom extra data to each asynchronous image upload request?

### ISSUE THREAD

**Issue by mhashimmaqbool** [kartik-v/bootstrap-fileinput#411]
I have a product form, user fill in the product fields and browse multiple times to select images from different locations. but on submit I only get the last image on the server to save. I know the only workaround is to post images asynchronously through ajax, but the problem is, if I post my form fields first through ajax, the server save the record into database and send newly created product id back to the ajax success method, and in that method I want to initiate fileinput asynchronous images upload process but I want to send that new product id along each image to the server, so that I can relate images to that specific product which was just saved. so the question is, How do I dynamically set custom data to each asynchronous image upload request?

**Comment by kartik-v** [comment]
Check [ajax scenario # 7](http://plugins.krajee.com/file-input-ajax-demo/7) for a close example - how data can be set for each thumbnail.

**Comment by ahkmunna** [comment]
I'm having the same issue. Didn't able to attach the newly saved product is with the ajax file upload. Can you help?
