### ISSUE TITLE
Batch upload error, when initialPreviewConfig is set in response

### ISSUE THREAD

**Issue by azizkh** [kartik-v/bootstrap-fileinput#414]
Hi kartik, I set initialPriview and initialPreviewConfig in response. Everything works fine when doing single upload. But when I tried batch upload I got following errors in console:

Uncaught TypeError: data.config.push is not a function 
previewCache.set @ fileinput.js:128
(anonymous function) @ fileinput.js:1367

**Comment by azizkh** [comment]
Please let me know if it's a bug or if it's me who is doing something wrong. Спасибо

**Comment by kartik-v** [comment]
You need to check your configuration and ensure its a right object (associative array) that you are passing. Check the [ajax scenario 3 demo](http://plugins.krajee.com/file-input-ajax-demo/3) for an example of initial preview configuration.

**Comment by azizkh** [comment]
I did check my php code and everything looks correct.
This is my php code:
$result['success'] = true;
$result['initialPreview'] = ['<img src=/images/image.jpg class="file-preview-image" >'];
$result['initialPreviewConfig'] = [['key' => 10, 'url' => \yii\helpers\Url::to('site/remove')]];
echo json_encode($result);

This is what I get in console both when I do single upload(click upload icon within the frame) and batch upload. But I get an error when uploading files by clicking upload button near browse button.
{"success":true,"initialPreview":["<img src=\/images\/desert.jpg class=\"file-preview-image\" >"],"initialPreviewConfig":[{"key":10,"url":"site\/remove"}]}
Please let me know, If I'm wrong. I'm using your plugin for one of my projects, so quick reply would be appreciated. Thanks

**Comment by temirfe** [comment]
I have the same problem
