### ISSUE TITLE
Batch upload error, when initialPreviewConfig is set in response, it's a little bug

### ISSUE THREAD

**Issue by azizkh** [kartik-v/bootstrap-fileinput#416]
Hi kartik, I looked through your source code and found that in line 132 
data.config.push(config[i]);
However, here data.config is not a array but an object. That's why I got an error. So when I changed that line to
data.config[i] = config[i];
everything worked fine for batch upload. Correct me if I'm wrong.

**Comment by azizkh** [comment]
But this is not solutions for the problem, since data.config[i] will be updated every time for new upload, which is not correct

**Comment by kartik-v** [comment]
No `initialPreviewConfig` is an array. Its an array of objects. You need to ensure the configuration is correct.

**Comment by azizkh** [comment]
I know initialPreviewConfig  is an array but data.config is not. I would not bother you if everything worked fine

**Comment by kartik-v** [comment]
Ok I will check this...

**Comment by azizkh** [comment]
Ok, thanks

**Comment by azizkh** [comment]
previewCache.add is working ok, but previewCache.set is not (batch upload)

**Comment by kartik-v** [comment]
I rechecked and the code looks ok. Hope you have the latest code from `dev-master` (v4.2.6).

The config used in `previewCache.set` must be an array (which basically will be the `initialPreviewConfig` passed).

The 2 places where  `previewCache.set` is called uses `initialPreviewConfig` which is an array.
