### ISSUE TITLE
Reordering file thumbnails

### ISSUE THREAD

**Issue by yourchoice** [kartik-v/bootstrap-fileinput#417]
I try to apply jquery sortable, but i cannot change previewId.

.on('fileuploaded', function(event, data, previewId, index) {
     $('#'+previewId).attr('id', 'rp-'+response['initialPreviewConfig'][0]['extra']['recipe_photo_id']);/maybe that not posible...
}
.........................................

Can you show an idea to can apply sortable jquery ui ?
..........................................
$('.file-preview-thumbnails').sortable({
	items: '.file-preview-frame', 
	tolerance: 'pointer', 
	placeholder: 'ui-state-highlight', 
	update: function(event, ui) {
	        $.post('/index.php?obj=...&action=sort', $('.file-preview-thumbnails').sortable('serialize'));							
	}
});

**Comment by kartik-v** [comment]
You should not be changing `previewId` (it will also break other events) - Rather it must involve reordering the index in `filestack` (matching the `data-fileindex` attribute in preview frame).

May try to include an enhancement later to reorder files when I get time or support.

**Comment by yourchoice** [comment]
yes, i resolved in another way, i added ... ['frameAttr']['data-id'] = $id; then in sortable jquery I build post_param using data('id')

**Comment by superroca** [comment]
Hello yourchoice,
Can you explain more what did yoy do to resolve it? 
If you can paste your code I would appreciate. I need reorder the thumbnails.

Thank you very much!

**Comment by dersonsena** [comment]
I couldn't sort the upload files. I'm with the basic configurations:

```
'name' => 'attachment_48[]',
'options'=>[
    'multiple' => true,
    'accept' => 'image/*'
],
'pluginEvents' => [
    'fileselect' => 'function(event, numFiles, label) { console.log(numFiles) }'
],
'pluginOptions' => [
    'uploadUrl' => Url::to(['/site/file-upload']),
    'language' => 'pt-BR',
    'previewFileType' => 'image',
    'uploadExtraData' => [...],
    'showZoom' => false,
    'resizeImage' => true,
    'maxImageWidth' => 1024,
    'maxImageHeight' => 768,
    'resizePreference' => 'width',
    'browseLabel' => '',
    'removeLabel' => '',
    'uploadLabel' => 'Enviar Todas',
    'mainClass' => 'input-group-lg',
    'removeClass' => 'btn btn-danger',
]
```
Am I doing anything wrong ?

**Comment by csthink** [comment]
@kartik-v After add image I want re-arrange the preview image ,  I have tried to use  sortable plugin ,I can re-arrange the preview image ,but when I submit , the server receive old sort image not new sort , Could you tell me how to use sortable plugin before uploaded . Thanks!
