### ISSUE TITLE
Delete link do not work without initialPreview and initialPreviewConfig arrays

### ISSUE THREAD

**Issue by mhashimmaqbool** [kartik-v/bootstrap-fileinput#419]
If I do not return initialPreview and initialPreviewConfig arrays in response from the server on images upload, then the delete button do not work, even the deleteUrl is set in the fileinput configuration.

How can I do this without the initialPreview and initialPreviewConfig arrays ??

**Comment by kartik-v** [comment]
I am not clear with the question. The delete button configuration is only intended to delete files uploaded on server - which you will configure with `initialPreview`.

**Comment by mhashimmaqbool** [comment]
In async parallel upload if I do not return initialPreview and initialPreviewConfig arrays back in response then the delete button on the image does not work, even I have defined the deleteUrl under the inputfile configuration.

**Comment by kartik-v** [comment]
The delete url is applicable ONLY FOR SERVER UPLOADED CONTENT rendered via `initialPreview`. 

What else do you expect to delete and where?

Even if you do not return `initialPreview` it needs to be configured on load for delete url to work. Refer [ajax scenario demo 3](http://plugins.krajee.com/file-input-ajax-demo/3) for an example.

**Comment by lewis-spears** [comment]
An example I can see being useful would be that I click "Upload" (the files now exist on my server / database), if the user doesn't want the image anymore, I want to remove the reference from my server / database, not just from the frontend view.

I've had to put a hack in place inside the 'filesuccessremove' event and split the new id to get the original index in order to delete the file.

**Comment by kartik-v** [comment]
@lewis-spears the way it is designed is - for displaying server uploaded files and deleting files on the server you need to pass in the `initialPreview` and `intialPreviewConfig`... you can choose to do this immediately after upload where you can return the updated `initialPreview` and `intialPreviewConfig`. Within the `intialPreviewConfig` (read the docs)... you can set options for the file key identifier, the URL to delete that will be called via ajax etc.. hope this clarifies.

**Comment by lewis-spears** [comment]
Could you provide an example on how I could do what you've suggested please?

**Comment by kartik-v** [comment]
You can go through the ajax demos. A couple of examples are mentioned in [ajax scenario 4](http://plugins.krajee.com/file-input-ajax-demo/4) and [ajax scenario 5](http://plugins.krajee.com/file-input-ajax-demo/5). Your uploadUrl server code that processes the upload can return the JSON object containing  `initialPreview` and `intialPreviewConfig`.

**Comment by shankarGdev** [comment]
Is there are way to use local file for preview (don't need file preview from server) and implement file remove (server file delete).

**Comment by connect-javed001** [comment]
I have similar kind of issue : 

When first time I came to page & delete image its sending delete request to server , But when I upload image (without refresh the page) , then server side delete route not calling anymore
