### ISSUE TITLE
File position get changed on paraller async upload

### ISSUE THREAD

**Issue by mhashimmaqbool** [kartik-v/bootstrap-fileinput#420]
If I set the initialPreview and initialPreviewConfig in response from the server on images upload then the files positions get changed in the dropzone. 

If i do not set these arrays then it works fine..

**Comment by yourchoice** [comment]
Yes, same problem on me.... maybe need set a corelations ...

**Comment by kartik-v** [comment]
You must return only ONE file in `initialPreview` for each async upload.

**Comment by yourchoice** [comment]
for ex. auto-upload 2 files async, and 2 responses for xhr:
- {"initialPreview":["<img style=\"max-width:100%; max-height:120px;\" src=\"\/upload_data\/tmp\/thumb-14406025264885-5lmk4qqfnk7q88ihal270bsut2.jpg\" class=\"file-preview-image\">"],"initialPreviewConfig":[{"caption":"14406025264885-5lmk4qqfnk7q88ihal270bsut2.jpg","width":"160px","url":"\/index.php?obj=myaccount_recipe&action=fileinput_delete","extra":{"file_name":"14406025264885-5lmk4qqfnk7q88ihal270bsut2.jpg"},"key":"thumb-14406025264885-5lmk4qqfnk7q88ihal270bsut2.jpg"}],"initialPreviewThumbTags":[{"{PHOTO_TMP}":"14406025264885-5lmk4qqfnk7q88ihal270bsut2.jpg"}],"append":true}

- {"initialPreview":["<img style=\"max-width:100%; max-height:120px;\" src=\"\/upload_data\/tmp\/thumb-14406025259417-5lmk4qqfnk7q88ihal270bsut2.jpg\" class=\"file-preview-image\">"],"initialPreviewConfig":[{"caption":"14406025259417-5lmk4qqfnk7q88ihal270bsut2.jpg","width":"160px","url":"\/index.php?obj=myaccount_recipe&action=fileinput_delete","extra":{"file_name":"14406025259417-5lmk4qqfnk7q88ihal270bsut2.jpg"},"key":"thumb-14406025259417-5lmk4qqfnk7q88ihal270bsut2.jpg"}],"initialPreviewThumbTags":[{"{PHOTO_TMP}":"14406025259417-5lmk4qqfnk7q88ihal270bsut2.jpg"}],"append":true}

What is wrong here?

**Comment by mhashimmaqbool** [comment]
Yes this is what I meant to. 

In asyn paraller upload, if I browse three images like image1.jpg, image2.jpg and image3.jpg (in a sequence) and press upload button, then 3 requests received on the server, I save the image and set initialPreview array with one file and return back as a response for each request. But now I cannot gurranttee which file will be rendered on which location, the position of the images get changed as these were initially on dropzone when browsed.
or I can say that the sequence of the images get changed like image2.jpg, image1.jpg and image3.jpg. Whereas these were initially image1.jpg, image2.jpg and image3.jpg on dropzone.

I know this is because of the image size, small size image will be uploaded first but while rendering back on the dropzone it does not maintain its position or sequence.

**Comment by kartik-v** [comment]
It should not impact at all... note that for async mode, the plugin fires a separate ajax request for each thumbnail and will replace the thumbnail with the output from the server once ajax request is complete. It should not matter which upload finishes first.

Refer [ajax demo scenario 4](http://plugins.krajee.com/file-input-ajax-demo/4) for an example

**Comment by yourchoice** [comment]
I downloaded now last dev master version, but problem still persists.
Yes, for async. the plugin fires separately ajax requests, but before "$(this).fileinput('upload');", the plugin preview the image selected. If I select 2 images: img1 and img2, these are display in order img1 and img2, but when ajax upload is done, the previewed images are replaced by uploaded files not in correct order.

Problem is that here uploaded images doesn't replace same image as initial preview. Seems that depeneds by file size (what ajax request is done firstly).

So if img2 is smaller that  img1, this will be loaded first, but instead to replace initial img2, this replace img1...

**Comment by kartik-v** [comment]
Will provide a fix for this shortly in next release.

**Comment by yourchoice** [comment]
some news regarding file position, async. uploads ?

**Comment by mhashimmaqbool** [comment]
Any idea when this bug will be fixed?

**Comment by kartik-v** [comment]
Resolved via latest release updated on `dev-master`.
