### ISSUE TITLE
The green tick do not appear on successful file upload

### ISSUE THREAD

**Issue by mhashimmaqbool** [kartik-v/bootstrap-fileinput#421]
If I set initialPreview and initialPreviewConfig in response from the server on images upload then the green tick get disappeared, however without these arrays the tick mark appear on the image

any idea ??

**Comment by kartik-v** [comment]
Read docs... Use [initialPreviewThumbTags](http://plugins.krajee.com/file-input#option-initialpreviewthumbtags) to replace these tags in the markup for initial preview.

Set the `layoutTemplates.footer` property to add custom markup tags.

Set [previewThumbTags](http://plugins.krajee.com/file-input#option-initialpreviewthumbtags) to replace these tags for normal preview (where you can set these custom tags to an empty string).
