### ISSUE TITLE
How do I send position of the images on upload

### ISSUE THREAD

**Issue by mhashimmaqbool** [kartik-v/bootstrap-fileinput#422]
How can I get the position of images when upload on the server? like if I have two images on dropzone them first image position would be one and the second image position would be two.

Actually I need this on asyn parallel upload. because async parallel upload I don't have idea which image will get uploaded first on the server so that I can get its position.

this is very important for me, need your help.

Thanks in advance

**Comment by kartik-v** [comment]
You can set `uploadExtraData` to pass additional information as a callback function. You may set the `uploadExtraData` on `fileimageloaded` or `fileloaded` events by reading and storing the `previewId`.

**Comment by kartik-v** [comment]
Refer [ajax demo scenario 7](http://plugins.krajee.com/file-input-ajax-demo/7) for an example.

**Comment by mhashimmaqbool** [comment]
This is what written in the documentation for uploadExtraData callback function
"previewId and index is only available for individual file upload via the thumbnail"

But I want to have it for Async upload. would it also work for Async upload as well?

**Comment by kartik-v** [comment]
Yes it should work for async upload as well - check and confirm... (will update the docs).

**Comment by mhashimmaqbool** [comment]
Yes it is working but the behavior of the function is not satisfied.

I put a alert statement inside the uploadExtraData callback method like:

uploadExtraData: function (previewId, index)  {
        alert(previewId);
}

but on images upload it shows multiple times 'undefined' in alert box and then correct id of the thumbnail. This case is only for one file upload, same goes for all other images.

**Comment by kartik-v** [comment]
If your query is related to #420 it will be fixed there.
