### ISSUE TITLE
Progress bar incorrectly jumps to 98% on multiple uploads

### ISSUE THREAD

**Issue by murdockcrc** [kartik-v/bootstrap-fileinput#423]
I am using this library to allow the user to upload several mp3 files. A user may select something like 7 and up to 20 files.

Oftentimes, the progress bar for this upload jumps very quickly to 98%, which is incorrect, as the uploads are no way near that level of completion. However, the spinning wheels of the individual files continue to spin. Leave it enough time, and all those spinning wheels start converting to green. Once all are green, then the progress bar updates itself to 100% and the upload process finishes.

In summary, I'd like to report this behaviour where the progress bar will jump to 98% completion very quickly, but the upload of all files combined is nowhere that level of completion.

Repro steps are hard to define with certainty, but we've seen this situation happen under these conditions:
- Use AJAX uploads
- Select 7 files for uploading, each file at least 3MB in size
- Trigger the upload of all elements via the 'fileupload' method

I can also post code on how we initialise and configure the uploader if that is deemed helpful.

Thanks.

**Comment by kartik-v** [comment]
This is resolved via enhancement #426 with further features.
