### ISSUE TITLE
Text zoom button doesn't work with jQuery in noConflict mode

### ISSUE THREAD

**Issue by open-minds** [kartik-v/bootstrap-fileinput#424]
The text zoom button uses "onclick" (X)HTML attribute to call the modal dialog, which doesn't work when jQuery is used in noConflict mode. Use of JavaScript events would be preferable.

**Comment by kartik-v** [comment]
Try [this approach](http://stackoverflow.com/questions/10258072/jquery-no-conflict-onclick-functions-multiple-frameworks) as discussed on SFO
