### ISSUE TITLE
Maybe and event when initialPreview images are loaded is useful

### ISSUE THREAD

**Issue by yourchoice** [kartik-v/bootstrap-fileinput#425]
I have a list with images in DB. 

Will be useful an event that say that all images form DB (my case: set in a json var), are loaded (displayed) ...

**Comment by kartik-v** [comment]
You can write it easily using your own jquery/javascript.

```js
$(document).on('load', function() {
    var imagesLoaded = 0;
    $('.file-preview-initial img').each(function () {
        var $img = $(this);
        $img.on('load', function() {
            imagesLoaded++;
        });
    });
   
    if (imagesLoaded = TOTAL_IMAGE_COUNT) {
         // DO WHATEVER
    }
});
```

**Comment by yourchoice** [comment]
Yes, just I suggested 2 events: imageLoad and imagesLoaded... 

Regarding case when images are from DB, I think, another good thing can be that images to not be loaded via js, like now (my case smarty foreach....):
>>>
<script>
var initialPreview = [], initialPreviewConfig = [];
{foreach $form_act.photos as $recipe_photo_id=>$recipe_photo_file}
      initialPreview.push('<img src="{$smarty.const.IMGRW_URL}recipe/sm-{$recipe_photo_file}" border="0" alt="">');
       initialPreviewConfig.push({ url: null, key: {$recipe_photo_id}, extra: { recipe_photo_id: {$recipe_photo_id}, recipe_id: {$form_act.recipe_id|default:'null'} }, frameAttr: { 'data-id' : {$recipe_photo_id} } });					
{/foreach}	
</script>
<<<
I think nicer can be that DOM of images preview to be build directly in html, and the plugin to detect if DOM already exists. If yes, use it, else build it.
 
Your plugin can be the best of all file upload plugins that exists.

Another a few suggestion for future:
- a component included for sort...
- a component included for rotate...
- preview  template with same size for images (thumbs in equal boxes) responsive (of course this can be build and now be who want)
