### ISSUE TITLE
Enhancements to asynchronous uploads when `showPreview` is `false`

### ISSUE THREAD

**Issue by zhangyaoxing** [kartik-v/bootstrap-fileinput#428]
when I set showPreview to false,
1. there's an error thrown after file being uploaded: `Uncaught ReferenceError: keys is not defined `
2. when the above issue is fixed, I find that event `fileuploaded` is not fired. seems like this event is triggered somewhere inside the show preview process.

**Comment by zhangyaoxing** [comment]
the 1st problem is fixed after merging from latest master. the 2nd persists however.

**Comment by kartik-v** [comment]
The `fileuploaded` event is only fired for `async` uploads OR individual file upload via each thumbnail.

Its not fired when `uploadAsync` is `false`.

**Comment by zhangyaoxing** [comment]
yes I do have `uploadAsync` set to `true`. so keep everything else unchanged, if I set `showPreview` to `true`, it's fired. otherwise it's not.

**Comment by kartik-v** [comment]
I see... yes it currently has the validation for preview shown only... will check and update in the next release.

**Comment by zhangyaoxing** [comment]
Thanks. Seems I can use `filebatchuploaded` as a workaround now.

**Comment by kartik-v** [comment]
Resolved via latest release updated on `dev-master`.

**Comment by kartik-v** [comment]
Check updated ajax demo [scenario 10](http://plugins.krajee.com/file-input-ajax-demo/10) and [scenario 11](http://plugins.krajee.com/file-input-ajax-demo/11) for details.
