### ISSUE TITLE
Drag and drop does not work on Microsoft Edge

### ISSUE THREAD

**Issue by ntenisOT** [kartik-v/bootstrap-fileinput#429]
First of all thanks for the great plugin.

I would like to inform you that drag-and-drop does not work on Microsoft Edge, Windows 10. 

Can we somehow fix that? 

Thanks

**Comment by kartik-v** [comment]
Seems to [be a bug in MS edge](https://connect.microsoft.com/IE/feedback/details/1544800/ms-edge-drop-files-from-explorer-to-browser-does-not-work-as-expected) - need to vote/report with MS.

**Comment by kartik-v** [comment]
Only solution I see is to currently disable this feature for EDGE users by detecting the browser.

**Comment by ntenisOT** [comment]
Yes that sounds a reasonable solution. Disable drag and drop for EDGE users.

**Comment by kartik-v** [comment]
Resolved via latest release updated on `dev-master`. Check and update.
