### ISSUE TITLE
Problem to remove wrong file dragged stil remain in 4.2.6

### ISSUE THREAD

**Issue by mad4hit** [kartik-v/bootstrap-fileinput#430]
The problem that i've reported in #394 is still present dispite the enhancements in #401 when i drag an unautorized file i need to clear the drag&drop zone for remove it.

![2015-09-01_170846](https://cloud.githubusercontent.com/assets/5448105/9607936/1fac7448-50cc-11e5-9dd2-81dad07b1889.png)

**Comment by kartik-v** [comment]
You do not seem to have got the updated code OR you need to check if you are using the right plugin code.

You may [check on the demo page - for example the image dimensions demo](http://plugins.krajee.com/file-image-dimensions-demo) and try dragging non-image files into drop zone and trash them individually.

**Comment by mad4hit** [comment]
I've downloaded the last relase (4.2.6) from bower, my site refer the right plugin version.

this is the script:
html:
 <div class="col-md-8">
        <input id="media-items-upload" type="file" multiple class="file-loading">
        <p class="Note">
            <b>Allowed Extensions</b>:
        </p>
    </div>
js:
  $("#media-items-upload").fileinput({
            uploadUrl: "/Backload/UploadHandler", // server upload action
            uploadAsync: true,
            maxFileCount: 10,
            maxFileSize: 1000000,//da portare nei settings dell'applicazione web
            //allowedFileTypes: ['image', 'video', 'audio'],
            allowedFileExtensions: ["jpg", "png", "gif"],
            //allowedPreviewTypes:false,
            uploadExtraData: function () {  // callback example
                var hiddenFolderStructure = $("#hiddenFolderStructure");
                var out = { objectContext: '', uploadContext: hiddenFolderStructure.val() };
                return out;
            }
        });


but the problem is still here....

thanks for helping!
