### ISSUE TITLE
slugCallback doesn't change uploaded filename

### ISSUE THREAD

**Issue by yglevarec** [kartik-v/bootstrap-fileinput#432]
Hi.
I use the slugCallback method to correct filename before upload.
The filename is corrected in the preview but not in the post to server.
Have an issue ?
Thanks.

**Comment by yglevarec** [comment]
slugCallback, sorry

**Comment by kartik-v** [comment]
The file posted to server is a blob and will return whatever inherent file name is. 
You can use `uploadExtraData` to send your slugged filename as additional data.

**Comment by kartik-v** [comment]
With the next release 4.2.7 - the file names will be returned slugged by default... so I am noting an enhancement.

**Comment by kartik-v** [comment]
Resolved via latest release updated on `dev-master`.
