### ISSUE TITLE
the problem of multiple upload

### ISSUE THREAD

**Issue by linqtosql** [kartik-v/bootstrap-fileinput#435]
I using the fileinput for multiple upload by setting the input attribute multiple="true",
$("input[name=images]").fileinput({
            uploadUrl: "url",
            showUpload: false,
            showCaption: false,
            showRemove: false,
            maxFileCount: 5,
            validateInitialCount: true,
            overwriteInitial: false,
            browseClass: "btn btn-primary",
            allowedFileExtensions: ["jpg", "png"]
            ]
        });
I selected two files by twice browse,then submit,but only one file accept on my server,why?

**Comment by kartik-v** [comment]
Ensure you have array naming convention for your FILE INPUT markup. [Refer this web tip](http://webtips.krajee.com/read-html5-multiple-file-input-php/).
