### ISSUE TITLE
4.2.6 delete error

### ISSUE THREAD

**Issue by cyl19910101** [kartik-v/bootstrap-fileinput#438]
Dear developer: I've got delete error after update to 4.2.6, the delete button send a 'post' request to server, while everything works fine in 4.2.5 with the same config : 
initialPreviewConfig: [
              {
                caption: fileName,
                url: '/api/v1/picture', 
                key: fileName
              }
            ]
I have something to do in the moment, sorry can't give you more debug informations. Thanks a lot for this excellent project!

**Comment by kartik-v** [comment]
Default ajax delete method is changed to POST from release v4.2.6 (it was DELETE in earlier release). You need to program accordingly or can override `ajaxDeleteSettings` to set what you need for your use case.
