### ISSUE TITLE
How to properly recreate default text preview (initial preview from server)

### ISSUE THREAD

**Issue by l7777777b** [kartik-v/bootstrap-fileinput#439]
I dont know if im doing this wrong. im using auto upload so i need to return the initialpreview to the client after successful upload. i've recreated the template for text preview on the server and this is the response for my initialpreview
```
"initialPreview":["<pre title='XXX'  style='width:160px;height:136px;' class='file-preview-text'>my text file contents<\/pre>\n<button type='button' class='btn btn-default btn-sm btn-block' title='View details: XXX.txt' onclick='$(\"#show-detailed-text\").modal(\"show\")'>\n<i class='glyphicon glyphicon-zoom-in'><\/i>\n<\/button>\n"]
```

It looks similar to the default preview, button looks good, thumbnail looks good, except i cant open the modal box, clicking at the button does nothing. i've tried option layoutTemplates -> modal -> and writing the modal templates only changing the id with "show-detailed-text" but still didnt work.

Also your simple example code previewing the text file:
```
<span class='wrap-indicator' onclick='$(\"#show-detailed-text\").modal(\"show\")' title='XXX'>[…]</span>
```
Which where i got the onclick from, for my previous initialpreview, doesnt work for me.

I havent tried making my own modal on the html page, looks that will do. but my question is, what is the proper way for recreating the text preview once the file uploaded to the server? currently my only problem is with the modal dialog. Do i need to create my own modal on html? or maybe change the layoutTemplates->modal? or maybe there's another proper way?

**Comment by kartik-v** [comment]
Yes you currently need to create your own modal dialog for showing the text content on your server.
