### ISSUE TITLE
initialPreviewShowDelete not work.

### ISSUE THREAD

**Issue by davidsarkany** [kartik-v/bootstrap-fileinput#440]
Hi.

I try remove delete button from preview but 
"initialPreviewShowDelete": false
 not work.
![image](https://cloud.githubusercontent.com/assets/9111944/9767067/9f178032-571c-11e5-80e6-16b18c1c2e0e.png)

**Comment by kartik-v** [comment]
`initialPreviewShowDelete` is applicable ONLY for thumbnails set via `initialPreview` (from server).

It will not be applicable for thumbnails selected via file input (from client).

**Comment by kartik-v** [comment]
Not sure why you want to hide delete button for thumbnails for files selected from client.

But if you still wish to hide delete button for client selected files... then set `layoutTemplates.actionDelete` to an empty string.
