### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined while upload after refresh

### ISSUE THREAD

**Issue by l7777777b** [kartik-v/bootstrap-fileinput#441]
im using auto upload scheme to upload files, max 1 file. so after upload, the file preview replaced by initialpreview and initialpreviewconfig from my server, but it's not yet saved, its still on temporary folder. and for my scenario, if the user click save, i move the file from temporary folder to permanent folder, and i must clear the preview on the fileinput since the file is no more in the temporary folder. i've tried clear and reset method but nothing happen, finally refresh button is working. the preview cleared. this is where the problem appear, after the input refreshed, i want to upload the second time, after browse and choose, the preview's broken, not using the initial preview sent from the server after upload but stuck and locked at 100% with cancel button showing. and in the console, the error on the title above appear. but the ajax upload process was running, the file was uploaded  into temporary folder, it's just the preview on the page quite messed up. i don't know what's wrong because at first it's working but after refresh it's becoming like this where there's no difference at all at the preview html before and after. this is my whole initial configuration:
```
$("#attachment").fileinput({
		uploadUrl: "uploadFileMethod",
		uploadExtraData: function() {
	        return {docnum: docnum};
	    },
	    dropZoneEnabled: false,
	    uploadAsync: false,
	    showUpload: false, 
	    showRemove: false,
	    maxFileCount: 1,
	    autoReplace: true,
	    maxFileSize: 1023,
	    cancelClass: "btn btn-xs btn-default",
		browseClass: "btn btn-xs btn-primary",
		elErrorContainer: "#attachmenterror"
	}).on('filebatchuploadsuccess', function(event, data, previewId, index) {
	    console.log('filebatchuploadsuccess');
	}).on('filebrowse', function(event) {
// test if browse file still executed
// 	    	return {
// 	            message: "browse aborted",
// 	            data:{}
// 	        };
// above codes not working too browse still triggered
		console.log("File browse triggered.");
	}).on("filebatchselected", function(event, files) {
	    // trigger upload method immediately after files are selected
	    if (!uploadFileExist){
		    $("#attachment").fileinput("upload");
		    console.log('filebatchselected&upload');
	    }else{
	    	$("#attachment").fileinput("clear");
	    }
	}).on('filesuccessremove', function(event, id) {
		console.log('filesuccessremove');
	}).on('filecleared', function(event) {
		console.log("filecleared");
	}).on('filereset', function(event) {
	    console.log("filereset");
	}).on('fileerror', function(event, data) {
		console.log("fileerror");
	}).on('fileuploaderror', function(event, data, previewId, index) {
	    console.log('File upload error');
	}).on('filebatchuploaderror', function(event, data) {
        console.log('File batch upload error');
	}).on('filedeleteerror', function(event, data) {
	    console.log('File delete error');
	});
```

**Comment by kartik-v** [comment]
Cannot seem to exactly reproduce the issue. Can you expand upon the issue you are facing by adding a few more pieces of information to your report?

- What steps can be used to reproduce the issue?
- What is the issue and what is the expected outcome?
- Are you using this with other plugins?

Though I have not looked at your scenario. As a side note, a simple form based upload can achieve your use case for ONE FILE upload and you can avoid the rigamarole of uploading to temporary folder etc.

Check the [avatar upload demo](http://plugins.krajee.com/file-avatar-upload-demo) on the plugin page. The actual server based upload can happen after form submit.

**Comment by l7777777b** [comment]
currently i must allow multiple files upload because of some requirements and same thing happening.
but i think i found the problem, i'm using your autoupload method. my upload flow is, user select file/s to upload and free to delete before saving the document, all those files stored in temporary folder and at that moment the delete button also delete files from temporary folder too. after the user saved the document, all the files moved to upload folder, and at the same screen i show the saved file right away using ajax but in another div called upload-div using your css (copied your html tag and css from thumbnail preview) and so i must clear the fileinput which i did by using refresh. but after that the problem happened, i cant use the fileinput properly if i dont delete all the uploaded files. because if i delete all the uploaded files, the preview on my upload-div will be cleared too, hence your css i used for preview will be gone and the fileinput works again.

for example there will be such element for previewing uploaded files in my page after saving document
```
<div id='upload-div'>
  <div class="file-preview-thumbnails">
    <div class="file-preview-frame">
      *file1 with delete button
    </div>
    <div class="file-preview-frame">
      *file2 with delete button
    </div>
  </div>
</div>
```
and the file input wont work properly just like my original post. (files uploaded but the thumbnail hang at uploading state with error on console log)
but if i delete all of the files so what left is just this
```
<div id='upload-div'>
</div>
```
fileinput works good.

**Comment by yoyhosoft** [comment]
Hi,
I have some issue like this
When I use multiple upload,

Normal case
1. I have 1 (or more) image in that field.
2. Select file.
3. Upload.
4. Preview last image is OK.

Error case
1. I have 1 (or more) image in that field.
**2. Delete all file.**
3. Select file.
4. Upload.
5. Preview image is gone.

So, I try to debug fileinput.js and found some issue on line 182.

```
...
set: function (id, content, config, tags, append) {
    var data = $.extend(true, {}, previewCache.data[id]), i, chk;
....

```

Event if I have some file in that field, the **previewCache.data[id]** still have some configs like **initId**
But, event if that field don't have any file, the configs in **previewCache.data[id]** are gone.

Sorry for my English.

**Comment by yoyhosoft** [comment]
It gone after this:

```
  fnSuccess = function (data, textStatus, jqXHR) {
                /** @namespace data.errorkeys */
                var outData = self._getOutData(jqXHR, data), $thumbs = self._getThumbs(), key = 0,
                    keys = isEmpty(data) || isEmpty(data.errorkeys) ? [] : data.errorkeys;
                if (isEmpty(data) || isEmpty(data.error)) {
                    console.log(previewCache.data);  **// have initId**
                    self._raise('filebatchuploadsuccess', [outData]);
                    console.log(previewCache.data); **// initId gone**
```
