### ISSUE TITLE
class='file-loading' gives no input

### ISSUE THREAD

**Issue by sanaalauddin** [kartik-v/bootstrap-fileinput#443]
If I add class as file-loading I see no file-input. however if i change the traditional file class i see it. what could be the problem? im loading the jquery.min.js file and the fileinput.min.js and css files.

**Comment by kartik-v** [comment]
Its expected that the file-loading class hides the native file input and shows a loading indicator until the plugin fully loads the advanced upload widget. You need to make sure you initialize the plugin on `document.ready` or something to ensure the plugin loads only after entire page is loaded.
