### ISSUE TITLE
Upload button not disabled after validation error when ajax method used with showPreview set to false

### ISSUE THREAD

**Issue by radmela** [kartik-v/bootstrap-fileinput#444]
As you can test in the official demo while using ajax upload in case of an validation error, upload button should be disabled however it doesn't.
http://plugins.krajee.com/file-input-ajax-demo/10

see image.

![image](https://cloud.githubusercontent.com/assets/5557123/9836769/780e2260-5a2e-11e5-99f5-f2dff8d1d745.png)

when clicked it also posts the request.

**Comment by kartik-v** [comment]
Upload button will not be disabled as it will still be available to UPLOAD files that have not faced a validation error.

**Comment by radmela** [comment]
what if it is a single file upload and maxfilecount is 1 then the upload button should be disabled. when it is not an ajax upload it is already as i mention.

**Comment by kartik-v** [comment]
To reiterate the upload button will not be disabled. If you would need to do it for a very specific use case like yours -- you can call the `disable` method after a `fileerror` event if needed. Note that as mentioned, irrespective of the upload button being shown or not -- no files will not be sent to the server if the file has a validation error.

**Comment by radmela** [comment]
if i call disable user will not be able to select a new file right? it would not be convenient.

**Comment by ashuomble5** [comment]
I found the solution how to disabled the upload button:

***My problem was to make sure user input the file name for batch process..To do that I wanted the user to force write the name of the file ***

**Here what I am trying to do is when the drag or drop performs  I am calling this javascript:**
`document.getElementById('file-1').onchange = function() {
   
            if(!$("#name").val()){
                //alert("Before uploading please type the name of files");
                document.getElementById("responseMsg").innerHTML = '<p id="responseMsg" class="text-red">Before uploading please type the title of files</p>';
                $('input[type=text]').addClass('border-red');
                document.getElementById('file-1').value = "";
                $('.fileinput-upload-button').attr('disabled', true);
            }
 };`

**And for extra security I am using this code:**
` document.getElementById('name').onkeyup = function(){

            if($("#name").val()!== ""){
                $('.fileinput-upload-button').attr('disabled', false);
                document.getElementById("responseMsg").innerHTML = '';
                $('input[type=text]').removeClass('border-red');
            }else{
                $('.fileinput-upload-button').attr('disabled', true);
                document.getElementById("responseMsg").innerHTML = '<p id="responseMsg" class="text-red">Before uploading please type the title of files</p>';
                $('input[type=text]').addClass('border-red');
            }
        };`
