### ISSUE TITLE
  class='file-loading' gives no input #443 

### ISSUE THREAD

**Issue by sanaalauddin** [kartik-v/bootstrap-fileinput#445]
In regards to my previous issue, I am initializing on document ready still the file input is not appearing. on using firebug, i see an error in the fileinput.min.js file " TypeError: e is undefined". any idea how I can solve it?

**Comment by kartik-v** [comment]
You need to check if all the relevant assets (JS and CSS) is loaded in the right order starting with jquery.js.  Cross check your dependencies with the [plugin usage docs](http://plugins.krajee.com/file-input#usage). Also ensure you rule out and remove any third party plugins or Javascript that is erroring out.
