### ISSUE TITLE
Fileinput resets on failed validation

### ISSUE THREAD

**Issue by david-hubner** [kartik-v/bootstrap-fileinput#446]
**How to simulate:**

I am using async batch AJAX upload.

uploadAsync: true,
allowedFileTypes: ['image'],
allowedFileExtensions: ['jpg', 'jpeg', 'gif', 'png'],
showUpload: false,
showRemove: false

.on('filebatchselected', function () {
  $input.fileinput('upload');
})

Preview and config is loaded via. data attributes.

So I have input with pre-populated data from initial preview config. Now, when I want to upload new file, which is bigger than allowed max size, error is triggered and whole upload area is cleared. Same result on other validation. This problem only appears on first image upload error when inicial preview is populated. If you upload one other image, thatnthe functionality and error triggers are ok and nothing is cleared.

**Expected result:**

Input will preserve preview data for files which were succesfully uploaded before and error message will appear with new disabled preview attached after last preview.

**Comment by kartik-v** [comment]
Not sure if I understand the issue.

If you do not want `initialPreview` to be cleared, then set `overwriteInitial` to `false`.

Check [ajax example demo 3](http://plugins.krajee.com/file-input-ajax-demo/3)
