### ISSUE TITLE
is there any way to make that plugin responsive

### ISSUE THREAD

**Issue by urfusion** [kartik-v/bootstrap-fileinput#447]
I am using that plugin and it is working good. Only one issue I am facing that it is not responsive.
is there any way to make it responsive?

**Comment by kartik-v** [comment]
Entirely depends on you (the developer) and how you style it for your application. The plugin offers various properties and templates to configure and your end result depends on what feature you are enabling and how you style it. For example, check the [advanced example # 3 on demo page](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-3) - the entire widget is displayed as a block button which is responsive with the preview.
