### ISSUE TITLE
Feature Request: Max concurrent uploads

### ISSUE THREAD

**Issue by tstivers1990** [kartik-v/bootstrap-fileinput#448]
I would like to see a property that allows me to set the maximum number of concurrent uploads. I don't want to limit the number of uploads my users can submit in one session, but I don't want 5-6 upload processes running at once. I would like to be able to limit it to two or three.

**Comment by kartik-v** [comment]
Did you read and try the [maxFileCount](http://plugins.krajee.com/file-input#option-maxfilecount) property. It will allow users to only upload a certain number of files each time.

If you are talking about setting something at your session level - you need to handle it through your server code.
