### ISSUE TITLE
Localization not working in 4.2

### ISSUE THREAD

**Issue by bluescreen** [kartik-v/bootstrap-fileinput#450]
The Localization does not seem to work in version 4.2. If I downgrade on 4.1 it works again.

Do i have to change something when upgrading to 4.2 and using the locales?

**Comment by kartik-v** [comment]
The localization works fine on 4.2.x - you can [cross check with the demo](http://plugins.krajee.com/file-multi-lang-demo).

**Comment by bluescreen** [comment]
Thanks i found my issue. I had to set the option key for language. This was working without before.
Maybe you should highlight that in your docs.

**Comment by kartik-v** [comment]
This is already highlighted in the docs.. make sure you go through them before any update.

and also in the [link here](http://plugins.krajee.com/file-input/demo#multi-lang) and the [demo page](http://plugins.krajee.com/file-input/demo#multi-lang).
