### ISSUE TITLE
locale does not get applied when loaded via requirejs

### ISSUE THREAD

**Issue by ImanMh** [kartik-v/bootstrap-fileinput#451]
Hi, I'm trying to load bootstrap-fileinput and a locale using requireJS. The library is find but the locale does not work when loaded via requireJS. 
Here is my require config: 
```javascript
  shim: {
    'bootstrap': {
      deps: ['jquery']
    },
    'fileinput': {
      deps: ['bootstrap']
    },
    'fileinputFa': {
      deps: ['locationpicker']
    }
  }
```
Here is what I've required:

```javascript
require([
  'fileinput',
  'fileinputFa'
], function () {
  $('.up-pic').fileinput({
      language: 'fa',
      allowedFileExtensions: ['jpg', 'png', 'gif'],
  });
});
```
And here is my network panel:

![screen shot 1394-06-31 at 12 35 54](https://cloud.githubusercontent.com/assets/4482199/10014506/88266d16-6126-11e5-9ff3-732f6df6fbb9.png)

Am I doing something wrong?

**Comment by kartik-v** [comment]
The locale js file must also be  loaded after fileinput.js on the page.

**Comment by ImanMh** [comment]
if you mean fileinput_locale_fa.js, it's loaded as you see. Are you talking about an other file?

**Comment by ImanMh** [comment]
It's funny that every 10 times I refresh the page, I get one time of locale file working correctly. It might be an issue with defining dependencies.
