### ISSUE TITLE
PDF Preview not working on Chrome version 45.x however working on version 33.X

### ISSUE THREAD

**Issue by sekharkumarroy** [kartik-v/bootstrap-fileinput#453]
Hi,
Liked your plugin. Great work. 
Having an issue to make the PDF preview work on latest chrome version(40.x or higher). I have checked with 33.x and it's working fine. 

I'm having a demo, your early help is much appreciated.   Thanks in advance.

**Comment by kartik-v** [comment]
Its more to do with browser version which does not support OBJECT EMBED.
