### ISSUE TITLE
uploadExtraData usage

### ISSUE THREAD

**Issue by oculushut** [kartik-v/bootstrap-fileinput#455]
Hi, great plugin.  I have a question about the usage of uploadExtraData.

In my code I setup the fileinput object like so:

```
     $("#fileChooser").fileinput({
            allowedFileExtensions:["obj"],
            showPreview: false,
            uploadAsync: false,
            uploadUrl: "http://abc.com:8080/upload"
        });
```

I would like to add the uploadExtraData just before upload (basically after the user has had a chance to fill in a field.

I tried this but it doe not work:

```
        $("#fileChooser").on('filepreajax', function(event, previewId, index) {
          $("#fileChooser").fileinput({
            uploadExtraData: {id: "somedata"}
          });
        });
```

I also tried this:

```
        $("#fileChooser").on('filepreajax', function(event, previewId, index) {
          $("#fileChooser").fileinput.uploadExtraData = {id: "somedata"};
          });
        });
```

How do I assign a value to "uploadExtraData" after the initial instantiation of the object?

E.g. I know the following works (I see the data I place in the body of the post to my server);

```
     $("#fileChooser").fileinput({
            allowedFileExtensions:["obj"],
            showPreview: false,
            uploadAsync: false,
            uploadUrl: "http://abc.com:8080/upload",
            uploadExtraData: {id: "somedata"}
        });
```

And I also saw this in the documentation:

```
#### filepreajax
This event is triggered before submission of the upload ajax request. You could use this event to manipulate the `uploadExtraData` before its submitted via ajax. The following additional parameters are also available specifically and only if the upload is triggered via each thumbnail upload button.
```

But there was no example to show how to manipulate the uploadExtraData property...

Any pointers very welcome!

**Comment by oculushut** [comment]
OK - found the answer you provided here https://github.com/kartik-v/bootstrap-fileinput/pull/342

=> So you need to create a callback which will be called in filrepreajax.

Thanks!

**Comment by PatrickDotStar** [comment]
Can you give a full example please? I still don't get it to work.

**Comment by oculushut** [comment]
Sure, here's an example of how I am using it:

```
        $("#objFileChooser").fileinput({
          allowedFileExtensions:["obj"],
          showPreview: false,
          uploadAsync: false,
          uploadUrl: "http:/abc.com/webserviceName",
          uploadExtraData: function (previewId, index) {
            var info = {"tags": "somestuff"};
            return info;
          }
        });
```

The key bit is the function being assigned to "uploadExtractData".  What you will find is that the stuff in "info" is in the request to the web service you are uploading to.

I have not looked at the code in this project, but it looks like the function you pass it is called and whatever you return in the function is uploaded to the server at the same time as the file you are uploading.

What I did was print out all the content that my web service received and just searched for the "somestuff" string to work out where this data ended up.

Make more sense?

Was not immediately obvious to me either...

**Comment by PatrickDotStar** [comment]
Awesome thank you so much :) It works but it's kinda confusing.

**Comment by oculushut** [comment]
Agree - I had to remind myself by looking through my own code again after you asked the question!  I guess it's the nature of open source.  I should be less lazy and paste that example into the documentation and do a pull request!  Maybe tomorrow.  Getting bit late in evening where I am at the moment...

**Comment by kartik-v** [comment]
These are mentioned in the documentation. 

- Read [uploadExtraData plugin option in docs](http://plugins.krajee.com/file-input#option-uploadextradata)

Read docs for sending data to server for ajax uploads for:

- [asynchronous upload](http://plugins.krajee.com/file-input#ajax-async)
- [synchronous upload](http://plugins.krajee.com/file-input#ajax-sync)

In addition a demo example

- [ajax example # 7](http://plugins.krajee.com/file-input-ajax-demo/7)

**Comment by oculushut** [comment]
Hello - just updated README file in pull #466.  I think that actually seeing an example of the assignment of the callback function would have clarified things greatly for me.

ajax example # 7 would have clarified things for me if I had read it.

I am also using it to upload dynamic data and I can see why this would be the main use case so I have added this info too in the README.

Awesome project by the way.  Thank you for sharing it.  Saved me a bunch of time.

**Comment by msingh025** [comment]
we can use like this 👍 
$("#file-1").fileinput({
				uploadUrl: `${contextPath}/${url}`, // you must set a valid URL here else you will get an error
				allowedFileExtensions : ['wav'],
				overwriteInitial: false,
				maxFileSize: 3000,
				maxFilesNum: 5,
				uploadExtraData: function(previewId, index){ 
				let formValue = $('#new_message').serializeArray();
				let tempData = {};
				formValue.forEach(function(v, i){
					let name = v.name+'_'+(i+1);
					tempData[name] = v.value;
				});
				console.log(tempData)
				return tempData;
				
		     },
				//allowedFileTypes: ['image', 'video', 'flash'],
				slugCallback: function(filename) {
					return filename.replace('(', '_').replace(']', '_');
				}
	        });
