### ISSUE TITLE
Getting errors about fileExt.join() not being a function.

### ISSUE THREAD

**Issue by robross0606** [kartik-v/bootstrap-fileinput#456]
fileinput.js:1763
Uncaught TypeError: fileExt.join is not a function

**Comment by robross0606** [comment]
Looks like fileExt is null.  Aren't you allowed to use "data-allowed-file-extensions"?

<form:input class="file" type="file" name="uploadedFiles[1]" path="uploadedFiles" data-show-preview="false" data-show-upload="false" data-allowed-file-extensions="[csv]" data-remove-label="&nbsp;" />

**Comment by kartik-v** [comment]
Do not see an issue in file extension validation.

However, you seem to be using an outdated version of the plugin (from the code line number you provided). Would recommend you to upgrade and confirm.

**Comment by robross0606** [comment]
I already tried that.  Same problem.  It works okay if I use the API directly but if I use the “data-*” tag it doesn’t work.

**Comment by kartik-v** [comment]
Please debug your code and [use the plugin Comments and  Discussions page](http://plugins.krajee.com/file-input#comments) to ask for help on coding or programming

The data attribute is not quoted properly. It must be
```js
data-allowed-file-extensions="['csv']" // you missed the single quotes
```

**Comment by robross0606** [comment]
I already tried that too.  It doesn’t make a difference.  Same error.

**Comment by robross0606** [comment]
It's bad form to close an issue without confirming a fix.  Please re-open since your suggestion makes zero difference on the problem.  I tried it before you even suggested it.  This is not a fix.

**Comment by kartik-v** [comment]
As I mentioned its a HTML markup and jQuery JSON parsing and markup issue and nothing to do with the plugin).

You must swap single and double quotes. 

Refer this [example on how to pass an array into jquery data attribute](http://stackoverflow.com/questions/6071618/how-to-pass-an-array-into-jquery-data-attribute). If you feel this is still an issue with the plugin - update here and I will open it.

**Comment by robross0606** [comment]
Okay, let's make this nice and clear.  Here is my current example which does not work:

<form:input class="file" type="file" name="uploadedFiles[2]" path="uploadedFiles" data-show-preview="false" data-show-upload="false" data-allowed-file-extensions='["csv"]' data-remove-label="&nbsp;" />

It makes no difference whether the quotes are one way or the other, or even if there are quotes at all.  The contents of "data-allowed-file-extensions" never makes it into the fileExt variable in fileInput.js.

**Comment by kartik-v** [comment]
Could you share an example fiddle?

**Comment by kartik-v** [comment]
You can check the [basic demo example # 7](http://plugins.krajee.com/file-basic-usage-demo#basic-example-7) where it works fine.

**Comment by varya2** [comment]
It was not working for me too. but I did
<input id="input_7" name="input7"
                           type="file" class="file"
                           data-allowed-file-extensions='[&quot;png&quot;, &quot;jpeg&quot;]'/>

Thanks Kartik :-)
