### ISSUE TITLE
Cannot Delete Files Uploaded Via AJAX

### ISSUE THREAD

**Issue by TNChalise** [kartik-v/bootstrap-fileinput#457]
### How can I setup my response so that I will be able to delete the file I have Just Uploaded ? [@kartik-v ]
I have been trying to delete files that are uploaded by ajax, but it seems this is not working for me.
The image attached here, is the response that I have sent from server upon successful upload.
- Images are rendered well, but the delete option is not working.
- I am using Yii2 wrapper of this.

![upload-response](https://cloud.githubusercontent.com/assets/4486063/10121963/b076daa0-6525-11e5-9ba2-d966c4153279.png)

## My View File is:
```php

    // Usage with ActiveForm and model
    echo $form->field($documents, 'document_path')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*', 'multiple' => true],
        'pluginOptions' => [
            'uploadUrl' => Url::to(['documents']),
            'uploadExtraData' => [
                'mysecret' => 'secret',
            ],
            'maxFileCount' => 10
        ]
    ]);

```

**Comment by kartik-v** [comment]
You may want to go through the plugin docs and demos. Most of this depends on how you design your app and when you would like to trigger delete. One way to do it is to use `initialPreviewConfig` and set the delete URL to an ajax based server action.

For example check [ajax demo 3](http://plugins.krajee.com/file-input-ajax-demo/3).

**Comment by TNChalise** [comment]
Thanks @kartik-v for the link. It seems  I have miss configured my server response. It should be something like this:
![thanks](https://cloud.githubusercontent.com/assets/4486063/10122049/433b1312-6529-11e5-9557-061f8a40eb9b.png)

**Comment by hikmat30ce** [comment]
Hi I am facing same issue, can you share the php code how to set the response?

**Comment by devilturbo** [comment]
r5gyhujik
