### ISSUE TITLE
self.upload is not a function

### ISSUE THREAD

**Issue by Oviglo** [kartik-v/bootstrap-fileinput#458]
Hi, When I click on the upload button I have this error "Uncaught TypeError: self.upload is not a function fileinput.js:754"

Can you help me to fix it please ?

**Comment by kartik-v** [comment]
It seems some problem specific to your environment and looks like some javascript errors on your app install. You must check for other third party javascript plugins causing this OR check if you have loaded the dependencies in the right order (e.g. jquery)
