### ISSUE TITLE
CSS for caption breaks when not using preview

### ISSUE THREAD

**Issue by robross0606** [kartik-v/bootstrap-fileinput#461]
The styles for caption don't work correctly when the window is small/narrow and there is no preview image.  This issue can be demonstrated on the example page:

http://plugins.krajee.com/file-basic-usage-demo#basic-example-2

Make the window narrow or use a mobile device setting and note that the CSS does not render correctly.  Ellipsis are not triggered and the content either expands outside the container or wraps to another line causing other render issues.

**Comment by kartik-v** [comment]
Cannot reproduce your issue. Which browser and OS are you testing this on?

**Comment by robross0606** [comment]
Chrome

**Comment by robross0606** [comment]
Windows 7 64-bit

**Comment by kartik-v** [comment]
It works fine. Do not see an issue.

**Comment by robross0606** [comment]
![screenshot-plugins krajee com 2015-09-28 12-46-52](https://cloud.githubusercontent.com/assets/2965467/10142180/0b41c8be-65df-11e5-80bd-da6795067d12.jpg)

**Comment by robross0606** [comment]
Here's another example:

![screenshot-localhost 8080 2015-09-28 12-48-30](https://cloud.githubusercontent.com/assets/2965467/10142209/41d4e82a-65df-11e5-831e-8b93723f38da.jpg)

**Comment by kartik-v** [comment]
You mentioned the caption (the text which displays filename). It is responsive and the text adjusts automatically to the size - do not see the overflow on the demo. 

For the buttons --- they are rendered via stock bootstrap CSS (input groups). You would need to adjust the button labels or keep iconic buttons or reduce number of buttons to fit to mobile screen.

**Comment by kartik-v** [comment]
This is an application specific styling need and your second use case as well is specific to your application.

Not sure if you read through the plugin options. There are various configuraton examples in the plugin setup to help you achieve what you want.

Some examples of various ways to achieve different styles:

- Check [basic example # 5 ](http://plugins.krajee.com/file-basic-usage-demo#basic-example-5)
- Check the [advanced example # 3](http://plugins.krajee.com/file-advanced-usage-demo)

You can for basic example # 2 
- Set `browseLabel`, `removeLabel`, and `uploadLabel` to an empty string in plugin options and see that it will always fit a mobile screen.
- You could set CSS class for various elements in the plugin options

There is nothing to be defensive here - as each developer's use case will be different and one needs to setup his/her styles as needed.

**Comment by kartik-v** [comment]
Refer #462. Enhancement has been provided to default CSS (if using input groups) - for handling auto hide of labels for small screen devices.
![image](https://cloud.githubusercontent.com/assets/3592619/10158122/7f4336c0-66ad-11e5-8a76-0081c2ceb91a.png)
