### ISSUE TITLE
filepreajax is not working correctly for me

### ISSUE THREAD

**Issue by raydawg2000** [kartik-v/bootstrap-fileinput#464]
I am using the new added callback method to updated the `uploadDataExtra` field, but it's not working for me.  The property is updated only for the next call, not the current call.  So the first time I click upload NULL is sent to my server.  If I then click upload again the id field is properly sent with 5.

    $("input[id^='file_']").fileinput({
            uploadAsync: true,
            uploadUrl: "<%= request.getContextPath() %>/upload.do",
        });
    	
    	$("input[id^='file_']").on('filepreajax', function(event, previewId, index) {
    		$(this).fileinput({
                uploadExtraData: {id: 5}
            });
    	});

Any ideas?

**Comment by kartik-v** [comment]
Set upload data as a callback function. For example it can return an hidden input value as json obj. Then use other events to change the hidden input.

**Comment by raydawg2000** [comment]
Thanks, this is what I used to get it working.  Is this what you were talking about or is there a better way?

    var uploadID = "";
    $(document).ready(function() {
    	$("input[id^='file_']").fileinput({
            uploadAsync: true,
            uploadUrl: "<%= request.getContextPath() %>/upload.do",
            uploadExtraData: function() {
            		return uploadID;
            	}
            });
    	
    	$("input[id^='file_']").on('filepreajax', function(event, previewId, index) {
    	    uploadID = {"id": $(this).attr("id")};
    	});
    });

**Comment by kartik-v** [comment]
Yes it is one of the ways to do it.
