### ISSUE TITLE
Form submitting though there are Errors 

### ISSUE THREAD

**Issue by saikiranmarripati** [kartik-v/bootstrap-fileinput#469]
The plugin is great , but i found one issue , say i have given minHeight and minWidth of images, it is giving me the error message if user has uploaded small Images but the form is submitting if user doesn't care the error message of minHeight and minWidth. It should stop user from submitting the form.

**Comment by kartik-v** [comment]
It is not in the scope of the plugin. Your form validation and submission must be handled through your own code. You can use plugin events like `filebatchuploaderror` or `fileuploaderror` to disable the form submit button.
