### ISSUE TITLE
Trying to get server response at fileuploaded event

### ISSUE THREAD

**Issue by waredesk** [kartik-v/bootstrap-fileinput#470]
I am trying to get a response from server using uploadAsync, i don't know if i misunderstood the options of the plugin. The fact is that i am trying to receive image ID after beign uploaded in order to append that id to a hidden field in my form. All my tests show data.response as undefined.

Here's the client side code

    var fileinput_822a4cd8 = {
      "uploadUrl":"\/frontend\/upload\/",
      "overwriteInitial":false,
      "uploadAsync":true,
      "browseClass":"btn btn-primary btn-block",
      "showCaption":false,
      "showRemove":false,
      "showUpload":false,
      "maxFileCount":10,
    };

    jQuery('#ad-image').fileinput(fileinput_822a4cd8);
    jQuery('#ad-image').on('fileuploaded', function(data, previewId, index) { 
      console.log(data.response); 
    });

And the server side processing just returns the id of the generated image

    header('Content-Type: application/json');
    echo json_encode(['id' => $image->id]);

Any suggestion? Thanks

**Comment by kartik-v** [comment]
You have the event parameters wrong. [Check the example in the documentation](http://plugins.krajee.com/file-input#event-fileuploaded). You skipped the first parameter `event` which is applicable for all events. 

So you must use:

```js
jQuery('#ad-image').on('fileuploaded', function(event, data, previewId, index) { 
  console.log(data.response); 
});
```
