### ISSUE TITLE
Validation problems

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/bootstrap-fileinput#471]
Firstly, wow! This extension has come a long way since I first looked at it. Originally I went with the blue imp plugin as had more features, but yours now seams to have everything I need, however running into a few problems with validation that I suspect is a bug todo with validation seeming to ignore the count of initial files - only on submit, not when selecting as it seems to work correct in that situation.

Secondly, I finally donated to your site - as much as I can afford for now. I hope many more people are doing the same to help encourage the great extensions you are providing. If I ever finish my system I can hopefully denote more :)

##### Using
```
'uploadAsync' => false,
'initialPreviewCount' => 1,
'validateInitialCount' => true,
'maxFileCount' => 1,
'minFileCount' => 1,
'initialPreviewShowDelete' => true,
```
### Variation 1s:
```
'overwriteInitial' => false,
```
#### Results:
1./ click delete on image => *You must select at least 1 file to upload* - OK'ish though Ideally if does nothing but error would expect button not to be there (might be a bit OTT though)
2./ click remove - nothing happens - if does nothing don't expect button to show
3./ click form submit - sends which is correct

The problem, can't change the image. So it appears I need overwriteIntial => true

### Variation 2s:
```
'overwriteInitial' => true,
```
#### Results:
1. same as 1s
2. click remove => init image gone. Click submit after and get => *You must select at least 1 file to upload* - which is good, and uploading an image then allows the submit to proceed i.e. validation passes.
3. Click form submit - get You must select at least 1 file to upload - which is an error since there is already the 1 initial image. Note that this happens whether the init image is still displayed or removed in step 2. I.e. validation on submit is only counting new files.

The problem, can change the image but can't keep the existing one as won't validate until another file is uploaded i.e. seems to be ignoring initialPreviewCount in validation on beforesubmit - or however it works.

## AJAX mode  (actionUpdate)
Though warned against in your docs - mixed modes - thought I would test what was relevant in ajax mode - up to the point of submit/upload, The results turned out similar to above with one minor bug noticed after clicking the delete button where the remove button would become visible.

### Variation 1a:
```
'overwriteInitial' => false,
```
#### Results:
Same as submit form mode

### Variation 2a:
```
'overwriteInitial' => true,
```
#### Results:
1. Click delete button - same as above *EXCEPT now the remove button appears* which can be clicked and removes the existing image. *Unexpected*. I can't comment as to whether validation would fail on upload or not as not tested. Submit works of course as mixed mode so validation not occurring.
2. no remove button to click - *this is inconsistent with non ajax mode*. I understand that remove is perhaps only for new files, which would likely mean it shouldn't appear also in form submit mode.
3. Click form submit - submits which is great for my situation but obviously only gets thru because validation won't be occurring at all since in the wrong mode - validation would be against the upload button which I have hidden and I would expect it to probably fail here for the same reason as in 2s3.

# Summary:
_Can't find away in form submit (actionUpdate) mode for minFiles 1 and maxFiles 1 to validate how I would expect_. I.e. the main issue seems to be centered around 'initialPreviewCount' and 'validateInitialCount' not seeming to be taken into account on form submit (perhaps upload in ajax mode but havn't tested). Note that valiation appears correct during the file selection process and works with these variables as expected - just not on submit.

I do realize not to use in mixed mode, I really just wanted to see what differences, and as far as I can tell re validation of file quantiies, I don't think there is a difference so think the same fix will probably solve both modes.

Currently I havn't yet stepped through your code to look for solution.

Just some use case info for consideration in the future.

Not quite sure how file number validation should work when delete action is designed to actually delete.
Currently I am just not deleting - just returning no error from my delete action and adding hidden input carrying what I need to delete in the eventual form submit. It seems to me that firing a request to delete on click of the delete button though suitable in situations might sometimes not be appropriate i.e. when 'initialPreviewCount' and 'validateInitialCount' come into play with minFiles and maxFiles - unless I am missing the point of these attributes (just viewing them from how they would seem to make sense in my current project).

#### An observation

It appears that perhaps I shouldn't be using model rules with this? When I have my file rules against the attribute I seem to get my normal validation errors coming thru. Commenting these out of course means I just get the one set of validation errors.

I have several ways forward i.e. can enable my previous validation and disable the min max files stuff in this extension and rely on my rules or potentially start stepping thru the plugin - thought I would raise it here first to see if I am missing something - which is often the case.

**Comment by kartik-v** [comment]
Simple setup without much complication

- Set `options['multiple']` to `false` if you WANT ONLY ONE file to be selected - rather than setting file count
- For single image view and update - check the [avatar upload example](http://plugins.krajee.com/file-avatar-upload-demo) that uses `defaultPreviewContent` instead of `initialPreview`
- For making users mandatorily select a file to upload in Yii framework - set the `required` property to `true` for the attribute in model validation rules.

**Comment by kartik-v** [comment]
Simple setup without much complication

- Set  input's `multiple` property to `false` (i.e `options['multiple']`) if you WANT ONLY ONE file to be selected - rather than setting `maxFileCount`
- For simple single image view and update using form based submission - check the [avatar upload example](http://plugins.krajee.com/file-avatar-upload-demo) that uses `defaultPreviewContent` instead of `initialPreview`. Set the `defaultPreviewContent` to your saved file (or a default image if file does not exist) - and `overwriteInitial` to `true`.
- For making users mandatorily select a file to upload in Yii framework - set the `required` property to `true` for the attribute in model validation rules.

BTW... thanks for the encouragement.

**Comment by andrewblake1** [comment]
Key point I guess is that it validates perfectly while manipulating files i.e. adding and deleting files within the widgets area, it just doesn't appear to take into account the init file count on submit - which I think is probably just a small bug.

Yip, am aware of those settings and in my blueimp version the model rules is naturally how I controlled both client and server validation (with FileValidator, skipOnEmpty false when required) - though to work with the update situation in blue imp I had extended FileValidator, and written client code to deal with maintaining correct files counts and implementing minFiles.

I am hoping to keep my hacks to minimum and looks like your plugin only lacks from the tiny issue on submit but nearly client validates min and max perfectly. Even having a minFilesCount option was surprising and impressive!

Bare in mind for the future the possibility of storing an init files deleted list that gets sent to server with post (hidden inputs) as alternative to request being activated on click of delete. This isn't really related to this issue though and I have it easily dealt with using your events and a dummy delete action - yet again this extension is impressive to such easily provide the tools to do this.

#### Less relevant background if further use case info needed
I allow businesses to define their own forms and fields within database. Am building models for these fields dynamically and file is just one of the field types. With each field type they can set up rules in a simplistic manner. Min and Max files along with allowed file types is logical for file. I add the rules dynamically. It all works fine in my blue imp version which I won't go back to now as nearly there with your awesome extension and I know that I can resolve this issue in multiple ways anyway - just looking for the path of least resistance - i.e. trying to get someone else to fix it :)

At the moment I can visualise use cases for 0, 1 or many file attributes per model (i.e. passport application form has many file attributes - photos, birth cert etc). I can see use cases for 0, 1, or n files per attribute. I can't imagine yet a use case for minFiles 3, maxFiles 4 - however I would bet my bottom dollar that some businesses will wan't to do this - based on simulating something they currently do manually. I.e. 7 photos exactly or min 3 photos maximum 6 photos of some object. Because this system is SAAS, I am building as flexibly as I can.

Am guessing once I get past this I may end up raising 1 or 2 minor things more along the longs of an overall ajax submit option (as opposed to per attribute) when many files attributes combine with other form data. Currently I have cheated and achieved ajax submit in form submit mode with pjax (pjax target container a hidden div and processing the ajax response in pjax complete similarly to how used to in my blueimp implementation) however this gives no access to progress updates - and ideally would like to use drag and drop. Have the progress in my blueimp but not the d & d. Irrelevant for now.

**Comment by kartik-v** [comment]
>  it just doesn't appear to take into account the init file count on submit - which I think is probably just a small bug.

This is not true as this depends on how you configure the plugin. You may want to read the docs. Note that `maxFileCount` or `minFileCount` validation by default does not include initial preview count., If you need that then you must set [validateInitialCount property](http://plugins.krajee.com/file-input#option-validateinitialcount) to `true`. 

For delete data manipulation you may want to [read this comment](https://github.com/kartik-v/bootstrap-fileinput/issues/472#issuecomment-148896072) in another issue.

**Comment by andrewblake1** [comment]
If you check back to the settings at the top you will see that I do have validateInitialCount as true - which works while manipulating files in the preview area. I would expect this to work on submit also - am I missing something? Sorry if my first post was long winded and perhaps made this unclear. Am often not the best at explaining things, and I certainly do have a tendency to overlook the obvious.

After midnight here, will take a closer look at the delete data manipulation tomorrow. To be honest, the way I have the delete data already is pretty simple and works so it was really only a suggestion for future consideration. Pretty much the same as I was doing blueimps i.e. maintaining a list of files to be deleted and sending with post - not sure if there can be a simpler way - all goes in a single request. If the comment above makes my code cleaner and avoids the dummy actionDelete then I will implement it.

Your events and general architecture have made this far simpler than my blue imp implementation and it is certainly very flexible and changeable.

Thanks again for your time with this.

**Comment by andrewblake1** [comment]
Close if you wish (your right anyway I know). I have coded around this now. I guess it is all fine when operating within the widgets area i.e. clicking the file inputs upload or delete - which will do for most use cases. Its just when you start to use with other form data and clicking the submit button it hits a few limitations - which I must have overlooked initially as is documented in http://plugins.krajee.com/file-count-validation-demo#min-ajax

I do understand that this is a plugin and is made to work independently from yii.validation.js, and yii validation for files by default doesn't even have the minFiles option you are providing here (personally I find required and skipOnEmpty a little obscure with file validation and would prefer just minFiles and maxFiles - null if not limited). 

###### If of any use to anyone else for this situation, my solution was:
1. disable yii's client validation and rely on this plugins for file attributes
2. run in ajax mode (dummy url) which stops this plugins validation from firing on submit so the above discussed issue of not taking into account init preview file count doesn't come into play
3. hide the upload button as I was after single synchronous submit
4. perform my own ajax submit using FormData (this also passes thru my deleted files in the manner I indicated in the link to the issue above you provided)
5. extended FileValidator to deal with minFiles so that I could double check everything ok re file numbers (modified to take into account existing, deleted, and new in the attribute)
6. dealt with the response back in client and set kv-fileinput-error div with errors from server which reports back if file num or anything else is wrong.
7. as of yet I haven't added any special client validation to my extended FileValidator as I think this plugin is doing it well and only the rare occasion when the remove button clears that this would be needed but would leave client validation duplicated the rest of the time (this plugin and yii.validation performing the same checks). If I was to add client validation for this I would probably just count the files visible in preview area and validate against minFiles and maxFiles.

The plugin is awesome - I wish markdown had a 2 thumbs up symbol.

**Comment by kartik-v** [comment]
> run in ajax mode (dummy url) which stops this plugins validation from firing on submit so the above discussed issue of not taking into account init preview file count doesn't come into play

You may run into a few issues with the approach (which is why the docs mention not to combine modes). The issue is that reading `$_FILES` via form submit may not be the same for AJAX based submit. 

Both will be same until you start appending files to a previous selection. This is because NATIVE FILE input cannot be edited or appended via javascript (and its the native file input data which you can receive via native form submit). So if you need advanced features like appending/deleting files from preview before UPLOAD - this will only work with an AJAX SUBMISSION and not via FORM SUBMISSION.

**Comment by andrewblake1** [comment]
Cheers for the heads up. I had wondered the details of that warning in the doc - I was wondering what it was about and hoped it wouldn't be too much related to browser inconsistencies. I will run some tests later and try and figure this one out.

Perhaps I can maintain a hidden field carrying removing files so that this gets posted on submit and gives me a list of file names within $_FILES to ignore perhaps? An obvious thing off hand to watch out for would be a file added, removed and added etc. Pretty much doing this already with deleted init preview (existing files).

Sorry, still haven't looked thru your plugin code as trying to work around things as opposed to forking and altering.

I may alter this comment later after investigating.

**Comment by andrewblake1** [comment]
You are correct, every time a file is added or removed from the file input it wipes the FileList. I seem to be around this now, however there were a couple of things that could be a little easier perhaps:

1. Had to turn off plugins click event on the delete button to fire my own handler as I can't find an event for delete/cancel of new files in the preview area (only the init ones).
2. Retrieved the filename as best I could from title attribute however this seems to have undergone some replacement - perhaps the slug callback? E.g. logo (2).png => log 2.png which breaks comparison when deleting/removing. Any chance you could point me in direction of the filename transformation - have only looked for a couple of minutes - slug callback perhaps?

I guess not much point posting the code, its fairly simple - basically on submit loop thru each file input, read its data-filestack, put these into FormData object and do ajax.

Maintaining filestack as data attribute on file input and append on fileloaded event, had to take over click function of delete button to remove from stack.

Is there anything you are aware of that could cause difficulty with this approach?

Would love to see more of this in the plugin but perhaps it is a rare use case.

**Comment by andrewblake1** [comment]
Just realized will probably somehow need to keep the click event on the delete button in order to activate it after my code to keep track of file count for validation.

**Comment by kartik-v** [comment]
I think if you need the various functionality that requires AJAX... you should use AJAX uploads feature instead of form submit. Using `uploadExtraData` you can send in the additional form inputs serialized and submit them (which will behave similar to form submit).

**Comment by andrewblake1** [comment]
Thats a full circle i.e. first thing I tried before submit mode :) When I previously tested that, my issue became the additional file inputs - use case in https://github.com/kartik-v/bootstrap-fileinput/issues/471#issuecomment-148837199.

The below simplified approach appears to be working - i.e. now sending files matching preview area. Can add remove, clear, add, delete etc and still sends correct files. Might muck up a little I guess if people re-use the same filenames but not concerned with things like that at this stage.

Just appending newly added files into a stack in file input data attribute. Stack will just keep growing. Check in submit that file exists in preview before appending to formData:
```
function fileloaded(event) {
    var $fileInput = $(event.currentTarget);
    var filestack = $fileInput.data('filestack') || [];
    var uploads = $fileInput[0].files;
    for (var i = 0; i < uploads.length;  i++) {
        filestack.push(uploads[i]);
    }
    $fileInput.data('filestack', filestack);
}
```
on submit:
```
$fileInputs.each(function() {
    var $input = $(this),
        $preview = $input.closest('.file-input').find('.file-preview'),
        attrib = $input.attr('name').replace(/[\[\]']+/g, ''),
        i = 0;
    $.each($input.data('filestack') || [], function() {
        if ($('[title="' + this.name + '"]', $preview).length) {
            formData.append(attrib + '[' + i++ + ']', this);
        }
    });
});
```
Also replaced slugCallback to not alter displayed file name so the compare works.

For me this is resolved (limited testing) - again though great if the plugin had this ability - deal with multiple file inputs in ajax mode (not just multiple files single input). Perhaps limited use cases though.

**Comment by andrewblake1** [comment]
Hi Kartik

Just in case you are monitoring emails and not looking at the comment - thought I would mention that I just updated the last comment.

Looked into your code, found I could access the plugins filestack directly, seems pretty simple now.

Can you see any issues with this? Is it really that simple, or am I missing something?

**Comment by kartik-v** [comment]
Yes the plugin returns the filestack and allows you to get this easily now via `getFileStack` method.

**Comment by reoxb** [comment]
This helpme! thanks 👍
