### ISSUE TITLE
Event  'filebatchuploadcomplete' - parameter file is always empty

### ISSUE THREAD

**Issue by meventi-stephan** [kartik-v/bootstrap-fileinput#473]
Thanks for this fantastic plugin. I have a problem with the event 'filebatchuploadcomplete' because the parameter 'files' is empty and I don't no why it is so. I make an ansychrounous file upload to the server (this works fine), send then a json-answer from server (see example excerpt, this work also fine) but i don't get any files in parameter "files" in client side. What is reason? Can you help me? Thanxs.

Example (Client -Event Handling):
```
    $("#<?= $id ?>").fileinput(paramsFileupload)
    .on('filebatchuploadcomplete', function(event, files, extra) {
      console.log(event);
      console.log(files);
      console.log(extra);
    });
```
Example (php Server Handling):
```
    echo json_encode([
      initialPreview => ["<img src='$file_upload_name' class='file-preview-image' alt='$file_upload_name' title='$file_upload_name'>"]
    ]);
```

**Comment by meventi-stephan** [comment]
I am using fileinput version 4.2.8 at the moment

**Comment by kartik-v** [comment]
Need to understand details.

Also can you check your use case by rather using the [filebatchuploadsuccess event](http://plugins.krajee.com/file-input#event-filebatchuploadsuccess)

**Comment by meventi-stephan** [comment]
I'm waiting for the event "filebatchuploadcomplete" to recognize that all file uploads are finished. This works fine. But i hoped that in parameter "files" all uploaded files are in it (with file paths information). How can i achieve this?

**Comment by meventi-stephan** [comment]
The parameter "files" is at the moment empty.

**Comment by meventi-stephan** [comment]
Ok. I will take the "fileuploaded"-event. Thanxs do your help.
