### ISSUE TITLE
Upload via button within each preview thumbnail skips last file for async uploads 

### ISSUE THREAD

**Issue by stepancher** [kartik-v/bootstrap-fileinput#474]
My server returns the response as in the example http://plugins.krajee.com/file-input-ajax-demo/4.
If i set in response 'append' => true  , and select to upload three images at once - third image is not sent to the server. If i set 'append' => false all work as expected. 
In your demo this error is seen, when you try to upload five images(on last image).
In version 4.2.6 this bug missing. 
Hope for your quick response ;)

**Comment by kartik-v** [comment]
Cannot seem to reproduce your use case?

The [ajax demo 4](http://plugins.krajee.com/file-input-ajax-demo/4) on the demo site seems to work fineand displays each file uploaded (as well as sending this to server) without any issues?

Hope you do not have caching issues on your browser OR the web server using outdated code?

You may test and then update this issue with an example or JSFiddle where this can be tested.

**Comment by stepancher** [comment]
it's not the operating system, browser, or my js plugins. I check it.
<a href="http://plugins.krajee.com/file-input-ajax-demo/4">ajax demo 4</a> don't work correct. To reproduce do this steps
1) Click Browse
2) Select 5 images at once
3) Click Open
4) Click shorts icons "upload file" in sequence (not Upload selected files)
5) Fifth image don't upload! (don't send data on server)

**Comment by kartik-v** [comment]
Ok that's why it was not clear. The normal Upload button works. 

There is an issue while uploading via the individual thumbnail upload buttons. Updating the issue title and will check this.

**Comment by stepancher** [comment]
it is also interesting that matters in what sequence you press the little buttons upload. Other observations I described in the first message

**Comment by kartik-v** [comment]
This is resolved - you may check and do the tests and let know (remember to clear cache from your browser/web-server before test).

**Comment by stepancher** [comment]
I can't test your fix. Use kartik-v/yii2-widget-fileinput in composer.json "kartik-v/bootstrap-fileinput": "~4.2" . When you make new release 4.2.8 ?

**Comment by kartik-v** [comment]
The new release will be tagged after more tests. You may need to change your composer.json to accept dev-master releases OR for testing overwrite the `bootstrap-fileinput` repo onto your vendor folder

**Comment by stepancher** [comment]
Change composer.json to accept dev-master, and your fix resolve this bug. I use slightly modified your widget for their needs. Based on it, made the Manager who attaches images to any model attribute. In this connection there are several ideas to upgrade this widget if you are interested
