### ISSUE TITLE
Bug in upload button not being disabled

### ISSUE THREAD

**Issue by ricksonchew** [kartik-v/bootstrap-fileinput#476]
I notice that the upload button on the ajax upload is not being disabled when file type does not meet required file extensions.

Here's an example:
```javascript       
    $('#uploadMedia').fileinput({
        allowedFileExtensions: ['jpg', 'jpeg', 'gif', 'png', 'mp4', 'avi', 'txt', 'doc', 'docx', 'mp3'],
        uploadUrl: 'http://example.com/upload',
        uploadAsync: true,
        uploadExtraData: function() {
            return {
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            };
        }
    });
```

I think the `uploadUrl: 'http://example.com'` part is causing the upload button not to be disabled when it does not meet the required file extensions because when I eliminate that line, the upload button is being disabled. Though the drag and drop functionality will not show up as well as the individual upload and delete per item.

I think it would be better if one or more items to be uploaded does not meet the required file extensions, the upload button will be disabled else the upload button will be enabled.

**Comment by kartik-v** [comment]
The upload button is not intended (as part of plugin design) to be disabled on any validation. However, any files that fail validation error will not be sent to the server. 

You can achieve this use case easily though by trapping one of the [error events](http://plugins.krajee.com/file-input#error-events) for your use case. For example:

```js
$('#input-id').on('filebatchuploaderror', function(event, data) {
     // call any validation here to disable the button or disable the entire file input
     $('#input-id').fileinput('disable'); // you can add another button to trigger clear files and enable
});
```
