### ISSUE TITLE
Add images one by one without raplacement?

### ISSUE THREAD

**Issue by DarkMerge** [kartik-v/bootstrap-fileinput#479]
When add images, for example, two times with file input dialog without saving and reload - first image replace with second. Does this plugin have this functional?

**Comment by kartik-v** [comment]
Check the [auto replace usage demo](http://plugins.krajee.com/file-auto-replace-demo)

**Comment by DarkMerge** [comment]
Thx, it's working. One question. Can it works without option 
//    	uploadUrl: "/file-upload-batch/2"

my input looks like: <input id="upload_img" type="file" name="PROP_MORE_PHOTO[]" multiple accept="image/*"> and i have no need in "uploadUrl: "/file-upload-batch/2""

**Comment by kartik-v** [comment]
No.

Appending/replacing/deleting selection of files before upload will only work with ajax mode (with uploadUrl). Read documentation [for usage modes](http://plugins.krajee.com/file-input#usage-modes).
