### ISSUE TITLE
Trigger fileloaded when showPreview is false.

### ISSUE THREAD

**Issue by coreConvention** [kartik-v/bootstrap-fileinput#48]
I am creating a Knockout binding handler for this. Adding the "file" to an observable array via the valueAccessor in a custom binding handler. I am not using showPreview. I attach to the fileloaded event like so in my bindingHandler:

```
ko.utils.registerEventHandler(element, 'fileloaded', function (event, file, previewId) {
    addFile(value, file);
});
```

However, that event does not fire when preview is not true. So I found it necessary to add a trigger to the readFiles method:

```
if (!self.showPreview) {
    setTimeout(readFile(i + 1), 1000);
    $el.trigger('fileloaded', [file, previewId, i]);
    return;
}
```

Im sure you can probably find a better way to add that trigger to your code, so I dont want to try to fork it, this was just a quick fix to do what I needed to do. Hopefully you dont mind adding this in future versions. 

Anyhow, thanks for the great work!

**Comment by krabsheva** [comment]
The line:
```
setTimeout(readFile(i + 1), 1000);
```
....has problems on at least an old version of Firefox I test with. Best to encapsulate the timeout code in a closure:
```
setTimeout(function(){readFile(i + 1)}, 1000);
```
