### ISSUE TITLE
kv-file-remove button defaults to class='disabled'

### ISSUE THREAD

**Issue by BrianMullin** [kartik-v/bootstrap-fileinput#480]
In our usage, we noticed that an unwanted `class="disabled"` attribute was present on the **kv-file-remove** button, even when the button should be and actually was enabled.

We addressed the issue by changing line 198 *(fileinput.js 4.2.7)* from:

    html += previewCache.get(id, i);
to:

    html += previewCache.get(id, i, false);

The third parameter of the `get` method is **isDisabled**, which defaults to true.

Is this the intended behavior or is passing **false** the intended design?

**Comment by kartik-v** [comment]
Good question?

Can you tell me the use case where you face this (anything from the demos) -- so that I can test and fix.

**Comment by BrianMullin** [comment]
I have finally determined the use case that was causing my error.

I was using the `deleteUrl` option and omitting the `initialPreviewConfig['url']` property, since the url value was the same for all of my `initialPreview` items.

The documentation states...

---
**deleteUrl**

*string*, the URL for deleting the image/content in the initial preview via AJAX post response. This will be overridden by the initialPreviewConfig['url'] property.

---
When omitting the `url` property in each `initialPreview` item, the 'disabled' class was added to the `kv-file-remove` buttons. However, the button did not have the `disabled='disabled'` attribute and did perform the file removal properly by utilizing the `deleteUrl` option value as a fallback.

When I replicated the `deleteUrl` setting into each `initialPreview` item as the `url` property, the remove button state is displayed properly. So, I can easily work around this issue. I misinterpreted the documentation as meaning that the `url` was optional as long as the `deleteUrl` option was specified.

Thank for creating such a great plug-in and for supporting it so well.

**Comment by HKhedr** [comment]
c# code get delete icon disable 
jsonFileResult result = new jsonFileResult()
                {
                    initialPreview = "<img src= 'File'  class='file-preview-image'>",
                    initialPreviewConfig = new string[,]
                    {
                        { "caption" , "First Image" },
                        { "url" , "/Home/Delete"},
                        { "key" , "1" },
                        { "width" , "120px" }
                    }
                };

javascript code 

            var $input = $(':file');
            $input.fileinput({
                uploadAsync: false,
                showUpload: false,
                showRemove: false,
                minFileCount: 0,
                maxFileCount: 10,
                validateInitialCount: true,
                maxFileSize: 25 * 1024,
                msgSizeTooLarge: 'File "{name}" (<b>{size} KB</b>)'
                                + 'exceeds maximum allowed upload size of <b>{25} MB</b>. '
                                + 'Please retry your upload!',
                allowedFileExtensions: ['zip', 'rar', 'tar', 'gzip', 'gz', '7z', 'png', 'jpg', 'txt', 'doc', 'docx', 'pdf'],
                uploadUrl: 'Home/UploadFiles'
            })
