### ISSUE TITLE
Problem with non-latin characters in image footer

### ISSUE THREAD

**Issue by mikbox74** [kartik-v/bootstrap-fileinput#482]
Hello!
I have this issue: all cirillic names display as empty.
![03](https://cloud.githubusercontent.com/assets/1404546/10710280/2ea39524-7a63-11e5-8a0e-13652fb45bf0.png)
When I insert an image with footer by 'initialPreview' all goes right:
![05](https://cloud.githubusercontent.com/assets/1404546/10710286/b7de2f2a-7a63-11e5-9769-b525383681ed.png)

Thank you for incredible extensions. Your work is really awesome!

**Comment by kartik-v** [comment]
Duplicate to #367 and #250. The plugin uses a default slug routine to prevent unusual characters breaking JS. You can set `slugCallback` property as a function to allow what you want for your use case.

**Comment by mikbox74** [comment]
Thank you very much!
But how can I pass the callback into Yii widget?
