### ISSUE TITLE
Validation not applying properly when more than one file field is on the form

### ISSUE THREAD

**Issue by khaldoundanaf** [kartik-v/bootstrap-fileinput#484]
First of all thanks for this great plugin.

My problem is that I have a form where I need to provide multiple file inputs within the form.

I have set each of the fields to work as a bootstrap fileinput : 

$("#input1").fileinput({
				showUpload: false,
				minFileCount: 1,
				maxFileCount: 3,
				'allowedFileExtensions' : ['xls', 'xlt','xlm', 'xlsx', 'pptx', 'doc', 'docx', 'pdf', 'txt'],
		});		
		$("#input2").fileinput({
				showUpload: false,
				minFileCount: 1,
				maxFileCount: 3,
				'allowedFileExtensions' : ['xls', 'xlt','xlm', 'xlsx', 'pptx', 'doc', 'docx', 'pdf', 'txt'],
		});

When the form submits and upon validation, only the last fileinput is presented with an error message.

How can I apply all the validation to all inputs on form and not the last one?

I guess this is because all the functions are applied within the prototype of the object and not the constructor, all the FileInput instances are referencing only the last field..

Can you provide a detailed explanation of the solution if any?

Best regards dude :)

**Comment by kartik-v** [comment]
Not clear exactly on the query. If you are running your own custom form input validations - please check your other javascript code and plugins that you are using to do this.

There should be no issue in having multiple file inputs on the same page. You can check the [demo pages](http://plugins.krajee.com/file-input/demo) and each page has numerous file inputs together on the same page without any issue.

**Comment by kartik-v** [comment]
If you need newbie help OR have generic programming queries or need programming tips - there is a new forum created for this. Please [ask a question on the forum here](http://webtips.krajee.com/questions).
