### ISSUE TITLE
"filedeleted" event doesn't work

### ISSUE THREAD

**Issue by meventi-stephan** [kartik-v/bootstrap-fileinput#485]
I'm using fileinput in asynchronous mode. After i uploaded at least one file in preview view and click the 
delete button (in the preview) the function below isn't called.
```
$('#input-id').on('filedeleted', function(event, key) {
    console.log('Key = ' + key);
});
```
Is this event used for another case?

**Comment by wallaceiam** [comment]
I seem to be having a similar problem but with filepredelete.

Have you been able to resolve this or determine why the event isn't being called?

I also am not getting any DELETE or POST calls on the server side for newly uploaded files.  Everything works file for pre-existing uploaded files - it is just new files that don't seem to be handled correctly.

```javascript
var imagesInitialPreview = [
            '<img src="860969_494176790618037_1754821881_o.jpg" class="file-preview-image" alt="860969_494176790618037_1754821881_o.jpg" title="860969_494176790618037_1754821881_o.jpg">',
            '<img src="843062_494175740618142_1021387009_o.jpg" class="file-preview-image" alt="843062_494175740618142_1021387009_o.jpg" title="843062_494175740618142_1021387009_o.jpg">',
            '<img src="859127_494176250618091_113237579_o.jpg" class="file-preview-image" alt="859127_494176250618091_113237579_o.jpg" title="859127_494176250618091_113237579_o.jpg">',
            '<img src="860543_494176047284778_554763410_o.jpg" class="file-preview-image" alt="860543_494176047284778_554763410_o.jpg" title="860543_494176047284778_554763410_o.jpg">',
        ];
        var imagesInitialPreviewConfig = [
            { caption: "860969_494176790618037_1754821881_o.jpg", width: "120px", url: '/api/image', key: "860969_494176790618037_1754821881_o.jpg" },
            { caption: "843062_494175740618142_1021387009_o.jpg", width: "120px", url: '/api/image', key: "843062_494175740618142_1021387009_o.jpg" },
            { caption: "859127_494176250618091_113237579_o.jpg", width: "120px", url: '/api/image', key: "859127_494176250618091_113237579_o.jpg" },
            { caption: "860543_494176047284778_554763410_o.jpg", width: "120px", url: '/api/image', key: "860543_494176047284778_554763410_o.jpg" },
        ];

$("#images-upload").fileinput({
    uploadUrl: '/api/image',
    deleteUrl: '/api/image',
    ajaxDeleteSettings: { method: "DELETE" },
    uploadAsync: true,
    overwriteInitial: false,
    minFileCount: 0,
    maxFileCount: 5,
    validateInitialCount: true,
    maxFileSize: 1500,
    showClose: false,
    showCaption: true,
    showRemove: true,
    minImageHeight: 200,
    maxImageHeight: 400,
    minImageWidth: 200,
    maxImageWidht: 400,
    resizeImage: true,
    resizePreference: 'height',
    previewClass: 'img-responsive',
    browseIcon: '<i class="glyphicon glyphicon-folder-open"></i> ',
    removeIcon: '<i class="glyphicon glyphicon-remove"></i> ',
    browseClass: 'mb-sm btn btn-primary',
    removeClass: 'mb-sm btn btn-danger',
    uploadClass: 'mb-sm btn btn-default',
    removeTitle: 'Cancel or reset changes',
    elErrorContainer: '#kv-avatar-errors',
    msgErrorClass: 'alert alert-block alert-danger',
    layoutTemplates: { main2: '{preview} {remove} {upload} {browse}' },
    allowedFileExtensions: ["jpg", "png"],
    allowedFileTypes: ['image'],
    msgSelected: '{n} files uploaded',
    initialPreview: imagesInitialPreview,
    initialPreviewConfig: imagesInitialPreviewConfig,
}).on('filepreupload', function (event, data) {
    $('#kv-success-box').html(data.response);
    $('#kv-success-modal').modal('show');
}).on('fileuploaded', function (event, data) {
    $('#kv-success-box').append(data.response.link);
    $('#kv-success-modal').modal('show');
}).on('filepredelete', function (event, data) {
// THIS ISN'T CALLED FOR IMAGES JUST UPLOADED
// NOR IS THERE ANY POST/DELETE REQUESTS BEING
// SENT TO THE SERVER
    $('#frmDelete-image > #id').val(data);

    var el = $('#imgDelete');
    var title = el.attr('data-title');
    var msg = el.attr('data-message');
    var dataForm = el.attr('data-form');

    $('#formConfirm')
    .find('#frm_body').html(msg)
    .end().find('#frm_title').html(title)
    .end().modal('show');

    $('#formConfirm').find('#frm_submit').attr('data-form', dataForm);
    return true; //abort
});
```

**Comment by kartik-v** [comment]
Deletion is possible and applicable for only server uploaded files displayed via initialPreview. For files on client that are not yet uploaded to server there is no  ajax action needed or to be parsed. So no delete event will fire. You need to check filecleared or similar event for such cases.

**Comment by wallaceiam** [comment]
Thanks for the reply kartik-v,

However, I don't believe that is the case - OR - I have configured something incorrectly.

Using my above settings, to reproduce the issue:
1. Click Browse, and select an image,
   Image is successfully previewed
3. Click Upload
  Image is successfully uploaded to the server
  Remove button is available from the preview and the bottom bar
4. Click Remove (either on the previewed image or the bottom bar)
  No event is fired even though

If you refresh the page, the remove button works correctly with the newly uploaded image.
I can provide screenshots if that is unclear. However, the image has been uploaded, then the Remove button still acts as Clear - which I believe is incorrect.

Again, I may have configured something above incorrectly....

**Comment by kartik-v** [comment]
> 3. Click Upload: Image is successfully uploaded to the server. Remove button is available from the preview and the bottom bar. 4. Click Remove (either on the previewed image or the bottom bar)
No event is fired even though

It is expected behavior and will not call the server delete url. As mentioned, the server delete url is only called for images displayed via `initialPreviewConfig` and not for images seen on client session during the upload.

If you want to display server uploaded files (for delete) immediately after a client upload then you can [follow the ajax scenario 4 example](http://plugins.krajee.com/file-input-ajax-demo/4). This example use case shows how you can immediately set an `initialPreview`.

**Comment by wallaceiam** [comment]
Ah Perfect! Working great now.  

Thanks for the point in the right direction
