### ISSUE TITLE
Function or variable to get the count of files which are ready to upload (Enhancement)

### ISSUE THREAD

**Issue by meventi-stephan** [kartik-v/bootstrap-fileinput#486]
It would be nice to have a function or variable to know the count of files which are in the file preview and ready to upload.

**Comment by andrewblake1** [comment]
Not my place to say, and not sure about submit mode, but this might work for you in ajax mode
```
$input.data('fileinput').filestack.length 
```
where $input is the jquery file input element

**Comment by meventi-stephan** [comment]
Thanxs.

**Comment by kartik-v** [comment]
You should use `$input.fileinput('getFileStack')`.

**Comment by meventi-stephan** [comment]
thanxs.
