### ISSUE TITLE
Potrait image no rotate

### ISSUE THREAD

**Issue by chuki2** [kartik-v/bootstrap-fileinput#491]
Wow this extension is very nice and I like it.

But the problems is, after we select the portrait image it will display as horizontal. Any solutions?

Here I attach for example

![example](https://cloud.githubusercontent.com/assets/13462282/10959977/09146ab2-83ba-11e5-8125-0ff3ba5b9b17.PNG)

**Comment by kartik-v** [comment]
Such images need a EXIF parsing library to read the orientation tag - typically you do this parsing on your server side code after upload of image (though there are some [experimental libraries to parse exif](https://github.com/exif-js/exif-js) available on JS). 

Firefox 26 supports image-orientation: from-image: images are displayed portrait or landscape, depending on EXIF data. [See this](http://sethfowler.org/blog/2013/09/13/new-in-firefox-26-css-image-orientation/)

There is also [a bug to implement this in Chrome](https://code.google.com/p/chromium/issues/detail?id=158753).

If we have it in CSS specs supported by browsers to change orientation - then it will be an easy lean universal solution.

**Comment by igorRovenki** [comment]
@kartik-v I correct understand that if our image's height > width we can rotate canvas on 90°?
in my case it's not useful to rotate image by server code(

**Comment by kartik-v** [comment]
No you do not do it based on height. You can have an EXIF parser on your server that can read the orientation and rotate the image. For example PHP provides [this exif method](http://php.net/manual/en/function.exif-read-data.php)
