### ISSUE TITLE
InitialPreview with PDF files

### ISSUE THREAD

**Issue by 1211agarcia** [kartik-v/bootstrap-fileinput#492]
How do I initialPreview with PDF files?.
As in Advanced Example 1 ( http://plugins.krajee.com/file-advanced-usage-demo ) : 
<label class="control-label">Planets and Satellites</label>
<input id="input-24" type="file" multiple=true class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-24").fileinput({
        initialPreview: [
            '<img src="/images/moon.jpg" class="file-preview-image" alt="The Moon" title="The Moon">',
            '<img src="/images/earth.jpg" class="file-preview-image" alt="The Earth" title="The Earth">'
        ],
        overwriteInitial: false,
        maxFileSize: 100,
        initialCaption: "The Moon and the Earth"
    });
});
</script>

**Comment by kartik-v** [comment]
You need to have a PDF viewer component on your browser and use EMBED options.

**Comment by petargeorgiev123** [comment]
I have multiples fileinputs in a page and populate the initialPreview on the load passing the files. But for PDF I am getting the initialPreview trying to load the PDF into <img tag 
 What can be the problem? 
When selecting a PDF manually is previewing the PDF well but not in the initialPreview. 

$(".fileUpload :input").each(function(){
        var inputElement = $( this );
        inputElement.fileinput({
            showUpload: false,
            showCaption: false,
            fileType: "any",
            previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
            initialPreviewAsData: true,
            initialPreview: [
                inputElement.parent().parent().attr('data-url')
            ],
            autoReplace: true,
            maxFileCount: 1,
            overwriteInitial: true,
        });
    });

**Comment by kartik-v** [comment]
You can pass the pdf source link and use `initialPreviewAsData` to auto render the PDF files -- check the [preview management demo](http://plugins.krajee.com/file-preview-management-demo#preview-data) for an example for various types of files.

**Comment by lordcroci** [comment]
@kartik-v Hi, Thanks a lot for everything, we are using a lot of your plugins and are awesome.
I have a problem with your file input form, I do not need an 'big' preview 'cause I need to upload only PDF files so I am wondering if there's a way to show just the namefile.. This would be useful specially if there is a way to show the preview file name in the update page allowing the user to know the OLD uploaded file before substituting it. 

Thanks a lot, 
cheers,
Loris

**Comment by kartik-v** [comment]
You can set [iconic preview](http://plugins.krajee.com/file-preview-management-demo#preview-iconic) as shown in the demos.

Alternatively you can show only file names without thumbnails in the preview without thumbnails [as seen in this demo](http://plugins.krajee.com/file-theme-demo#theme-fa-1) by setting [`hideThumbnailContent`](http://plugins.krajee.com/plugin-options#hideThumbnailContent) to `true`

**Comment by lordcroci** [comment]
Ok, I'll try with hideThumbnailContent. There another problem, when I set the preview to true, then when I try to upload a pdf an alert ('access denied') pop up. 
What can it be? Thanks
