### ISSUE TITLE
Issue with uploading ? 

### ISSUE THREAD

**Issue by wpthemes786** [kartik-v/bootstrap-fileinput#495]
Hello @kartik-v 

Very Nice Plugin :+1: 

I have issues with uploading process. 

![screenshot-localhost 2015-11-11 20-10-39](https://cloud.githubusercontent.com/assets/12461946/11094352/2da0571e-88b1-11e5-8f04-4b13d43fc28c.jpg)

This is the error that i am facing right now, and my js code is. 

![2015-11-11_2013](https://cloud.githubusercontent.com/assets/12461946/11094284/b61686dc-88b0-11e5-813f-7dacc2693967.png)

in js the upload url is point to my controller function in Codeigniter.

![2015-11-11_2014](https://cloud.githubusercontent.com/assets/12461946/11094318/e6599910-88b0-11e5-8124-526c89f7ba24.png)

This is my function.

But i am getting error which is unexpected token. i have searched your repository before raising this issue but could not find any solution. 

Kindly Help me its very urgent. 

Thanks

**Comment by kartik-v** [comment]
You may want to read the docs once. 

Your ajax server action must return a valid JSON response and it is NOT returning a valid JSON output as in your PHP code above.

This is described in the ajax uploads section on what your [ajax action server code must SEND](http://plugins.krajee.com/file-input#async-send) and what your [ajax action server code can RECEIVE](http://plugins.krajee.com/file-input#async-receive).
