### ISSUE TITLE
How to set uploadExtraData after page load.

### ISSUE THREAD

**Issue by kociletisim** [kartik-v/bootstrap-fileinput#497]
i am trying set uploadExtraData after the page load. But, its is not working. "img_key" keyfield not seen in request payload data. 
please help me.

$('#input-702').on('filepreupload', function (event, data, previewId, index) {
 data.extra={img_key:"123456" };
                    console.log('File pre upload triggered');
                });

very thanks to this wonderfull plugins.

**Comment by kartik-v** [comment]
You may want to go through the docs. You can set `uploadExtraData` as a callback function as [described here](http://plugins.krajee.com/file-input#option-uploadextradata).
