### ISSUE TITLE
Error Message is Incorrect for Preview of Large Files

### ISSUE THREAD

**Issue by NAThompson** [kartik-v/bootstrap-fileinput#498]
Take a large file and upload it with the `data-show-preview="true"` parameter set. The error message will be `File does not exist`, though the error message should be `File too large to preview`. However, with `data-show-preview="false"`, the file uploads just fine.

This issue can be replicated using <a href=http://plugins.krajee.com/file-basic-usage-demo>this example</a> in the first and second fields, with a 10GB file.

**Comment by kartik-v** [comment]
Note that reading and displaying a large file is entirely dependent on each client and browser to have the specifications to handle that. The plugin just returns any exception errors faced by the client.

It is recommended that you manage this as a developer by setting the `maxFileSize`, `maxFileCount` properties or selectively disable preview by setting `allowedPreviewTypes` or entirely disable preview via `showPreview`.

Read similar issue #500.
