### ISSUE TITLE
Long filename - file input to long

### ISSUE THREAD

**Issue by CannyDuck** [kartik-v/bootstrap-fileinput#50]
If I upload a file with a very long filename, the width of the file input container flows out of the specified width. It there a way to prevent that?

![filename-flow](https://cloud.githubusercontent.com/assets/1655493/5025018/291c09d4-6b13-11e4-9d14-2f4500b2f6c5.jpg)

**Comment by bauschri** [comment]
had a problem with long file name.
![bildschirmfoto 2015-01-31 um 11 52 46](https://cloud.githubusercontent.com/assets/1098217/5987790/bab5ac28-a93f-11e4-8d7e-ff014fb1ce70.png)

for a workaround i add the following CSS
 .file-caption-name{
    word-break: break-all;
 }
