### ISSUE TITLE
Custom initialPreviewThumbTags placeholders do not get replaced

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/bootstrap-fileinput#501]
I have some custom `initialPreviewThumbTags` which are loaded if a file is uploaded. The `title` tag placeholder gets replaced, but the other tags don't. So the problem is if it takes longer to upload the other preview tags do not get replaced and the placeholder `{specialtag}` remains there and confuses the user.

**Comment by kartik-v** [comment]
Cannot reproduce. Can you check with the latest release of the plugin and resubmit a new issue with a JS Fiddle if it persists.
