### ISSUE TITLE
Unable to ajax-delete file after ajax-upload

### ISSUE THREAD

**Issue by alexglue** [kartik-v/bootstrap-fileinput#504]
I'm using fresh version of your plugin;
Ajax upload works fine, BUT ajax-removing does not works at all: request just was not sent at all.
Im' trying to debug and call predelele event, but was not called too;

```        
       var $options = {
            uploadUrl:'/backend/ajax/file/upload',
            deleteUrl: '/backend/ajax/file/delete'
        };

        $("#input").fileinput($options);
```

Is it possible to use ajax-delete after ajax-upload at all or it's just not implemented?

**Comment by karataserkan** [comment]
+1

**Comment by alexglue** [comment]
@karataserkan BTW, I shoot this trouble with the following:

```
	public function transform(Media $media)
	{
		return [
			'id'      => (int) $media->getKey(),
			'name'    => (string) $media->name,
			'file'    => (string) $media->getUrl(),
			'initialPreview' => [
				sprintf("<img src='%s' class='file-preview-image' title='%s' alt='%2\$s' style='width: 100%%; height: 160px;'>", $media->getUrl(), $media->name)
			],
			'initialPreviewConfig' => [
				[
					'caption' => $media->name,
					'url' 	  => route('admin.ajax.media.delete', $media->id),
					'data' 	  => $media->getUrl(),
				],
			],

			'append' => true
		];
	}

```

```
//view js script:

<script type="text/javascript">
    $(document).ready(function(){

        var $img  = $('#image', '#button-file-upload');
        var $form = $('#js-add-media-form');

        var $options = {
            language: 'ru',
            allowedPreviewTypes: ["image"],
            allowedFileExtensions: ['jpg', 'gif', 'png', 'jpeg', 'swf'],
            maxFileSize: 1024,
            maxFileCount: 5,
            uploadUrl: $form.attr('action'),
            deleteUrl: '/backend/ajax/image/delete',
            deleteExtraData: {_token: $("[name='_token']").val()}
        };

        $img.fileinput($options);
    });
</script>
```

```
//view :
                <div class="form-group" id="button-file-upload">
                    {!! Form::file('image', ['id' => 'image', 'multiple' => true]); !!}
                </div>

It works fine except of this shitty hardcoded html, but i don't know how to use it without html rendering from php.

**Comment by karataserkan** [comment]
@alexglue, thank you. it solves my problem

**Comment by HKhedr** [comment]
c# code get delete icon disable 
jsonFileResult result = new jsonFileResult()
                {
                    initialPreview = "<img src= 'File'  class='file-preview-image'>",
                    initialPreviewConfig = new string[,]
                    {
                        { "caption" , "First Image" },
                        { "url" , "/Home/Delete"},
                        { "key" , "1" },
                        { "width" , "120px" }
                    }
                };

javascript code 

            var $input = $(':file');
            $input.fileinput({
                uploadAsync: false,
                showUpload: false,
                showRemove: false,
                minFileCount: 0,
                maxFileCount: 10,
                validateInitialCount: true,
                maxFileSize: 25 * 1024,
                msgSizeTooLarge: 'File "{name}" (<b>{size} KB</b>)'
                                + 'exceeds maximum allowed upload size of <b>{25} MB</b>. '
                                + 'Please retry your upload!',
                allowedFileExtensions: ['zip', 'rar', 'tar', 'gzip', 'gz', '7z', 'png', 'jpg', 'txt', 'doc', 'docx', 'pdf'],
                uploadUrl: 'Home/UploadFiles'
            })

**Comment by nasrithamer** [comment]
Hi, 
please i want to delete file after upload but the key is always sent empty
**My JS code:**
`var $el1 = $("#images");
            $("#images").fileinput({
                language: 'fr',
                theme: "fas",
                uploadUrl: '{{ urlsite }}ajax/upload.php',
                uploadAsync: false,
                showUpload: false,
                showRemove: false,
                maxImageWidth: 1080,
                resizePreference: 'height',
                resizeImage: true,
                uploadExtraData: function () {
                    return {
                        ref_client: '{{ ref_client }}'
                    };
                },
                overwriteInitial: false,
                initialPreview: [],
                initialPreviewConfig: [
                    {
                        'url': '{{ urlsite }}ajax/delete_img.php'
                    }
                ],
                initialPreviewAsData: true
            }).on("filebatchselected", function (event, files) {
                $el1.fileinput("upload");
            }).on('filebeforedelete', function (event, key, data) {
                console.log('key = ' + key);
            }).on('filebeforedelete', function () {
                var aborted = !window.confirm('Are you sure you want to delete this file?');
                if (aborted) {
                    window.alert('File deletion was aborted! ' + krajeeGetCount('file-5'));
                }
                ;
                return aborted;
            }).on('filedeleted', function () {
                setTimeout(function () {
                    window.alert('File deletion was successful! ' + krajeeGetCount('file-5'));
                }, 900);
            });`

and my file PHP for Upload is 
`echo json_encode([
            'append' => true,
            'initialPreviewConfig' => [
                'caption' => $_FILES['images']['name'],
                'size' => $_FILES['images']['size'],
                'url' => $urlsite . 'ajax/delete_img.php',
                'key' => $_POST['ref_client'] . "_" . $name
            ],
            'initialPreview' => [
                "<img src='" . $urlimg . $name . "' class='file-preview-image' title='" . $name . "' alt='" . $name . "' style='width: 100%; height: 200px;'>",
            ]
        ]);` 
but when i click delete in the other side the key is empty.. how can i do this please thank you.
