### ISSUE TITLE
Rename image after ajax upload

### ISSUE THREAD

**Issue by albertborsos** [kartik-v/bootstrap-fileinput#505]
I used your yii2 FileInput widget for image upload with ajax. Everythings works fine except this scneario:

After I upload an image, I rename it on server side. (adding a timestamp to the filename or sg like that). Then I send back the new filename in the response, but I can't submit the new filename with the form.

Do you know whats the solution?

**Comment by kartik-v** [comment]
You can read docs for understanding [how you can receive server data after ajax upload](http://plugins.krajee.com/file-input#ajax-uploads) based on async or sync mode.

For using the server data on your client and replacing inputs/preview -  follow the [advanced dynamic preview example # 4 for async](http://plugins.krajee.com/file-input-ajax-demo/4) and [example # 5 for sync](http://plugins.krajee.com/file-input-ajax-demo/5)

**Comment by kartik-v** [comment]
If you have generic programming queries or need programming tips - there is a separate special question & answer forum created. You may [ask a question on the forum here](http://webtips.krajee.com/questions).
