### ISSUE TITLE
Trying to get the "uploaded-" ID

### ISSUE THREAD

**Issue by spellfork** [kartik-v/bootstrap-fileinput#506]
I am trying to build a list of the files that have been uploaded through the plugin that I can check against when a file I have uploaded is deleted. To build this list I would like to use the preview-frame ID as some kind of index for my list (easy to use inside the "filesuccessremove" since the event exposes the element id).

The id I get when trying to use previewID is always the same ID and it seems that this is used when first creating the preview element and then swaped for a unique id starting with "uploaded-".

I might be going at this the wrong way, but I would like to save a reference to the file that I choose as well as something to identify that file with when the filesuccessremove event triggers. The reason I need to do this is because I want to show uploaded files in a summary view and due to security reasons I am not able to get the uploaded files back from the server. Since the whole app is a single page app that removes references to the file upload plugin when I change views I need a way to populate the "initial preview" with recently uploaded files so I need to keep track of files outside the plugin. Is there a way to accomplish this without me forking the project and revising the plugin for my needs.

**Comment by kartik-v** [comment]
You can store your own id in a data attribute or a hidden element within the `previewId` container - and parse it via events which share you the previewId.

**Comment by kartik-v** [comment]
Check [ajax upload demo # 7](http://plugins.krajee.com/file-input-ajax-demo/7) for an example.
