### ISSUE TITLE
wish(file-input): list style preview or smaller picture box preview

### ISSUE THREAD

**Issue by joomlaA1** [kartik-v/bootstrap-fileinput#509]
wish: 
preview like a list style or smaller smaller picture box style thanks
(also capable of multi upload, remove one by one thanks)
how this..? thanks...

**Comment by joomlaA1** [comment]
hello @kartik-v ^~^

**Comment by kartik-v** [comment]
This can be themed and styled by each developer by controlling the various templates properties in the plugin and setting their own CSS.

In case you wish this to be included in the plugin - it would be good if you can help with a Pull Request - since will not currently have time to include this.

**Comment by kartik-v** [comment]
This can be themed and styled by each developer by controlling the various templates properties in the plugin and setting their own CSS.

In case you wish this to be included in the plugin - it would be good if you can help with a Pull Request. 

Currently will not have time to include this personally - so feel free to open a PR if you wish to have this faster.

**Comment by joomlaA1** [comment]
ok thanks i edit

**Comment by joomlaA1** [comment]
"controlling the various templates properties in the plugin"

does this mean i will edit file-input.js to edit the design of the preview..?

where is it located in the file...? thanks...

**Comment by kartik-v** [comment]
I have mentioned it before. Please read the [docs and plugin options section](http://plugins.krajee.com/file-input).

e.g. [layoutTemplates](http://plugins.krajee.com/file-input#option-layouttemplates) and [previewTemplates](http://plugins.krajee.com/file-input#option-previewtemplates).

I will not be able to provide any further updates on this anymore via the repo.

**Comment by joomlaA1** [comment]
thank you for your patience... and everything...

**Comment by kartik-v** [comment]
If you need newbie help OR have generic programming queries or need programming tips - please [ask a question on the forum here](http://webtips.krajee.com/questions).

**Comment by kartik-v** [comment]
If you need newbie help OR have generic programming queries or need programming tips - please [ask a question on the forum here](http://webtips.krajee.com/questions). 

Use this repo issue tracker ONLY for raising plugin ISSUES and ENHANCEMENTS.

**Comment by joomlaA1** [comment]
thnx
