### ISSUE TITLE
resizing image before upload

### ISSUE THREAD

**Issue by joomlaA1** [kartik-v/bootstrap-fileinput#511]
hi @kartik-v

do we have this function..?

or do you have idea about this?

the low-down of things to do, or how to do this, which events, the codes...

thanks

**Comment by kartik-v** [comment]
Go through the documentation thoroughly in detail to understand plugin usage as well as the demo examples. 

Example of [image resize before upload is mentioned here](http://plugins.krajee.com/file-image-management-demo).

Use this repo only for logging issues and enhancements. For help on programming and newbie help use the discussions and comments section on the demos page.

**Comment by joomlaA1** [comment]
thanks
