### ISSUE TITLE
value of a variable reusing

### ISSUE THREAD

**Issue by kelumputha** [kartik-v/bootstrap-fileinput#513]
I have following controllers

     [HttpPost]
     public JsonResult CreateDirectory(string product_ID , string type)
     {
        .......

       return Json("OK");
     }

     [HttpPost]
     public ContentResult UploadFiles(string folderid, string foldertype)
     {
        .........
      }

and using following script I'm trying to call and pass parameters to `CreateDirectory` controller method and `UploadFiles` controller method

     var productid = "sample";

     $('#idd').click(function () {

        $.ajax({
            url: '@Url.Action("CreateDirectory", "Home")',
            data: { product_ID: $('#Product_ID').val(), type: "type1" },
            type: "POST",
            dataType: "json",            
            error: function (response) {
                alert(response.responseText);
            },
            success: function (response) {
                if (response === 'OK')
                {
                    productid = $('#Product_ID').val();
                    alert(productid)
                }
                else
                    alert("errro");
            }
        });
      });  

     $("#idd").fileinput({
        type: 'POST',
        cache: false,
        uploadUrl: '@Url.Action("UploadFiles", "Home")',
        enctype: 'multipart/form-data',
        overwriteInitial: true,
        uploadExtraData: { folderid : productid , foldertype : "type1" },            

       });

Issue:

I'm assigning new value for var `productid` in `click` JavaScript event of above script.

like this `productid = $('#Product_ID').val();`

then I try to reuse that newly assigned value for `productid` reuse/reassign in `fileinput` JavaScript event

like this `folderid : productid`

but I cannot see newly assigned value for `folderid` , when Its calling to `UploadFiles` method I can see `folderid` value is still `sample`

**Comment by kartik-v** [comment]
A bit confused with the properties you are supplying to the fileinput plugin. None of the properties you have set below like `cache`, `type`, `enctype` are available in the plugin. Hope you have read the [documentation of plugin options](http://plugins.krajee.com/file-input#options).

```js
$("#idd").fileinput({
    type: 'POST',
    cache: false,
    uploadUrl: '@Url.Action("UploadFiles", "Home")',
    enctype: 'multipart/form-data',
    overwriteInitial: true,
    uploadExtraData: { folderid : productid , foldertype : "type1" },            
   });
```

If you have extended the plugin then cannot provide help here... as you need to debug your code. There is a new [forum created for Q & A on all extensions](http://webtips.krajee.com/questions). Please post all help related queries there and use this repo only for logging plugin issue or enhancement.
