### ISSUE TITLE
feature request outer ajax

### ISSUE THREAD

**Issue by joomlaA1** [kartik-v/bootstrap-fileinput#516]
in wenzhixin bootstrap-table, they have this option:

url	data-url	String	undefined	  A  URL to request data from remote site.

they also have this:

ajax	data-ajax	Function	undefined	  A method to replace ajax call. Should implement the same API as jQuery ajax method

can we also have the second one?
thanks

**Comment by kartik-v** [comment]
Read docs. You can override the ajax settings by setting [ajaxSettings](http://plugins.krajee.com/file-input#option-ajaxsettings) for upload and [ajaxDeleteSettings](http://plugins.krajee.com/file-input#option-ajaxdeletesettings) for delete.
