### ISSUE TITLE
hello, plugin is awesome,but.......

### ISSUE THREAD

**Issue by wenqinruan** [kartik-v/bootstrap-fileinput#517]
but the README.md is　in a mess，
i just want be clear at a glance about the plugin,
and just want to find a demo website,
in the first time ,i don't pay attention to the document,
i think you should the document to other markdown file.
and just add link in the REAEDME.md

**Comment by kartik-v** [comment]
The documentation and demos are [SUPPOSED TO BE READ at this link](http://plugins.krajee.com) as mentioned.
