### ISSUE TITLE
Auto upload and validation problems

### ISSUE THREAD

**Issue by antocorso** [kartik-v/bootstrap-fileinput#519]
jq_selector.fileinput({
...,
allowedFileExtensions:['zip','jpg'],
...
}).on("filebatchselected", function(event, files) {
            // trigger upload method immediately after files are selected
            jq_selector.fileinput("upload");
        });

This doesn't validate file extension before upload!!!
Or better still, the error message appear but the file is sent to the server even if not "accepted"!!!
I think that this is a big bug for this great plugin!

**Comment by antocorso** [comment]
The problem is that I have "uploadExtraData". So, even if the file isn't valid, the extra data are sent to the server!!

**Comment by kartik-v** [comment]
Yes you need to check your plugin settings and config.

Please do a test internally and provide a JS Fiddle for testing out such cases when logging an issue.
