### ISSUE TITLE
loading files to bootstrap fileinput

### ISSUE THREAD

**Issue by kelumputha** [kartik-v/bootstrap-fileinput#520]
This is HTML file location for bootstrap input

    @ViewBag.Product_ID
    <input id="attachments" type="file" multiple="true" class="file" data-preview-file-type="text">

This is the location relevant files located

~/Content/Essential_Folder/attachments/Product_ID

this Product_ID folder can be vary. but its define once page load ,I'm getting that Product_ID folder name using ViewBag

also files in that Product_ID folder can be few or single or none, I just want to load them all

here the approaches I tried

Approach 1 :

       $("#attachments").fileinput({

        type: 'POST',
        cache: true,
        uploadUrl: '@Url.Action("UploadFiles", "Home")', // server upload action
        overwriteInitial: false,
        uploadExtraData: { foldertype: "attachments_EN" },
        minFileCount: 1,
        maxFileCount: 5,
        initialPreview: [
        "<img style='height:160px' src='~/Content/Essential_Folder/attachments'+ViewBag.Product_ID+>",

Approach 2 :

        $("#attachments").fileinput({

        type: 'POST',
        cache: true,
        uploadUrl: '@Url.Action("UploadFiles", "Home")', // server upload action
        overwriteInitial: false,
        uploadExtraData: { foldertype: "attachments_EN" },
        minFileCount: 1,
        maxFileCount: 5,
        initialPreview: [
        "<img style='height:160px' src='https/localhost/Essential_Folder/attachments'+ViewBag.Product_ID+>",

**Comment by kartik-v** [comment]
Refer this in [the Q & A forum for programming tips and help](http://webtips.krajee.com/question/loading-files-folder-bootstrap-fileinput/).
