### ISSUE TITLE
Add support for ``bootstrap-sass-official``

### ISSUE THREAD

**Issue by joaoqalves** [kartik-v/bootstrap-fileinput#523]
Hi! Would it be possible to add a new branch ``sass`` so we can replace ``bootstrap`` dependency with the ``bootstrap-sass-official`` one? I already created the branch in [my fork repository](https://github.com/joaoqalves/bootstrap-fileinput/tree/sass) but it would be nice to merge it in this one, accessible for everyone. Otherwise, every time that people are using ``bootstrap-sass-official`` then will get two bootstrap dependencies and will have to deal with dependency exclusion, etc.

**Comment by PierrickGT** [comment]
It should be ~~bootstrap-sass~~ and not ~~bootstrap-sass-official~~
Works perfectly fine for me, you can test it with my fork.
https://github.com/PierrickGT/bootstrap-fileinput

**Comment by kartik-v** [comment]
Maybe I can plan to remove `bootstrap` from bower dependency and let developers install and manage it themselves. Let know your opinions?

**Comment by PierrickGT** [comment]
Maybe a SASS branch would be a better solution in order to let developers install the version they want.

**Comment by joaoqalves** [comment]
:+1: for @PierrickGT solution
