### ISSUE TITLE
Preview the files in a folder at bootstrap-fileinput

### ISSUE THREAD

**Issue by kelumKP** [kartik-v/bootstrap-fileinput#525]
I want to preview files in folder to bootstrap-fileinput . like this example http://plugins.krajee.com/file-input-ajax-demo/3
 
this is the location that files located
                C://Users/kelum/Documents/Visual Studio 2015/Projects/rootProject/project_name/project_name /Content/Essential_Folder/attachments_AR/01/

As an example I have file call sam.png So I tried to show it like below

            initialPreview: [ “<img style=’height:160px’ src=’file:///C://Users/kelum/Documents/Visual Studio2015/Projects/rootProject/project_name/project_name/Content/Essential_Folder/attachments_AR/01/sam.png’>”]

but its not giving proper preview here.this is how it look like http://i.imgur.com/YELMG1D.jpg

**Comment by kartik-v** [comment]
Its answered in the [forum here](http://webtips.krajee.com/question/preview-files-in-a-folder-in-bootstrap-fileinput/).

For programming help and queries refer the new [webtips Q & A forum](http://webtips.krajee.com/questions).

Use this repo for logging only issues and/or enhancements for the plugin.
