### ISSUE TITLE
Problems after upgrading to 4.2.8 when using "destroy" and "clear"

### ISSUE THREAD

**Issue by hstaudacher** [kartik-v/bootstrap-fileinput#526]
I used bootstrap-fileinput 4.2.5 for a while. A file input element is used within a dialog adn every time the dialog closes a `.fileinput( "destroy" );` will be executed. Everytime the dialog will be opened a `.fileinput( {options } );` will be executed to create the new input.

With 4.2.5 this worked fine. After upgrading to 4.2.8 this stopped working. After the first "destroy" the input is disabled all the time. Also executing a "clear" does make the input empty but shows a red border around it. 

Not sure if just options have changed but this looks to me like a regression.

**Comment by kartik-v** [comment]
Cannot reproduce this. You may want to check for application or client level caching or outdated asset issues.

You may want to check these [plugin methods on the demo pages for v4.2.8](http://plugins.krajee.com/file-plugin-methods-demo) and they do work fine.,

**Comment by hstaudacher** [comment]
I'll try to come up with a small standalone example

**Comment by kartik-v** [comment]
Will open this if there is a use case provided...
