### ISSUE TITLE
UTF-8 file names

### ISSUE THREAD

**Issue by alxmoroz** [kartik-v/bootstrap-fileinput#527]
While selecting files with utf names, for ex. "Траляля-111.txt" in preview its names showed correctly, but in caption and (most important) on server became wrong: "-111.txt". E.g utf part was "dropped".

How can I fix this?

**Comment by kartik-v** [comment]
Check the [slugCallBack](http://plugins.krajee.com/file-input#option-slugcallback) property of the plugin.

**Comment by alxmoroz** [comment]
Ok. Thanks!
