### ISSUE TITLE
how can i validate if the the file is not uploaded when i click submit button in a form?

### ISSUE THREAD

**Issue by RenjithVR4** [kartik-v/bootstrap-fileinput#528]
hello kartik, your plugin is very useful. but i'm facing this problem. how can i validate the file, if i didn't click the upload button in the preview area,? and then i just click submit button of the form?
it should show an error message like "please uplaod the file". but i don't know how to do this. Please help me. hope  you understand what i meant.

**Comment by kartik-v** [comment]
If you are using form based submission mode within plugin (not ajax) you can directly check the file input value and if it is empty throw an error when form submit button is clicked.
