### ISSUE TITLE
array of <img> tags passing to `initialPreview` property

### ISSUE THREAD

**Issue by kelumKP** [kartik-v/bootstrap-fileinput#529]
In the following function’s initialPreview property I want load array of `<img>` tags . for that I’m creating
 
 `<input id=”id” type=”file” multiple=”true” class=”file”>`

      $("#id").fileinput({
           .......,
          initialPreview: getFiles(),
       });

I just created getFiles() method as follows

       function getFiles() {

       var files = [];
       $.ajax({
       type: 'GET',
       url: '@Url.Action("filesinfolder", "Home")',
       dataType: "json",
       success: function (data) {
       $.getJSON(url, function (data) {
       $.each(data, function (index, item) {
       var img = $('<img>').attr('src', item);
       files.push(img.get(0));
       console.log(files);
       })
       return files;
       })
       },
       error: function (xhr, status, err) {

       }
       })

 }
then I wrote following server side method to get files

      public JsonResult filesinfolder()
      {
       string productid;

       productid = "01";

       string salesFTPPath = "C:/Users/user/Documents/Visual Studio 2015/Projects/rootProject/project_name/project_name/Content/Essential_Folder/marketing_materials_EN/01";
       DirectoryInfo salesFTPDirectory = new DirectoryInfo(salesFTPPath);
       IEnumerable<string> files = salesFTPDirectory.GetFiles() .Where(f => f.Extension == ".xls" || f.Extension == ".xml" || f.Extension == ".jps" || f.Extension == ".jpg" || f.Extension == ".jpeg" || f.Extension == ".png" || f.Extension == ".PNG") .OrderBy(f => f.Name) .Select(f => f.Name);

      // build urls
     List<string> urls = new List<string>();
     foreach (string name in files)
     {
        urls.Add(Url.Content("~/Content/Essential_Folder/marketing_materials_EN/" + productid) + "/" + name);
     }
        return Json(urls, JsonRequestBehavior.AllowGet);
    }

But this is not preview any file in that relevant folder ,

**Comment by kartik-v** [comment]
Closing this - please ask for [generic server coding and programming help in the Q&A forum](http://webtips.krajee.com/questions) - and use this repo for only plugin specific bug reports, issues, and queries
