### ISSUE TITLE
How to upload files immediately after selecting files without clicking on the upload button

### ISSUE THREAD

**Issue by wangy09** [kartik-v/bootstrap-fileinput#532]
How to upload files immediately after selecting files without clicking on the upload button

**Comment by kartik-v** [comment]
Read the [plugin documentation](http://plugins.krajee.com/file-input) and please go through all the [plugin demos](http://plugins.krajee.com/file-input/demo) - there are various properties and config available for you to achieve this.

A similar use case to yours is covered in the [ajax uploads demo scenario # 6](http://plugins.krajee.com/file-input-ajax-demo/6).
