### ISSUE TITLE
Thai file name is problems.

### ISSUE THREAD

**Issue by clashjedsada** [kartik-v/bootstrap-fileinput#536]
Thai files name is null when submit ajax. Such as, File name is 'ทดสอบ.jpg'  after submit ajax It was ' .jpg'.

**Comment by kartik-v** [comment]
Duplicate to #367, #482, and #250. The plugin uses a default slug routine to prevent unusual characters breaking JS. You can override it with the `slugCallback` property as a function to allow what you want for your use case.

**Comment by clashjedsada** [comment]
Thank you. Very much
