### ISSUE TITLE
Auto submit on drag&drop?

### ISSUE THREAD

**Issue by Worst45** [kartik-v/bootstrap-fileinput#537]
Hello,

thanks for your great job.
Is there a way to auto-submit files when they are dropped from a drag and drop ? (Without having to click on "submit" button)

I tried with:
```
$('#filUpload').on('fileloaded', function(event, file, previewId, index, reader) {
		$('#filUpload').fileinput('upload');
    });
```
but only the first file is submitted.

**Comment by kartik-v** [comment]
You may read the docs for all the events. You can [use the filebatchselected event](http://plugins.krajee.com/file-input#event-filebatchselected).
