### ISSUE TITLE
problem on Json

### ISSUE THREAD

**Issue by pc-mon** [kartik-v/bootstrap-fileinput#538]
Hello

i hope you doing fine

i have little problem with json but i cant get where the problem from my code

Controller Code is :
    public function actionScan($act = 'upload-ajax') {
        $myfiles = \yii\web\UploadedFile::getInstanceByName('files');
        if ($myfiles !== null) {
           // $model = new WorkProductProducts();
            //$model->project_id = $_POST['project_id'];
            //$model->user_id = \yii::$app->user->getId();
            //$model->o_file_name = $myfiles->baseName . '.' . $myfiles->extension;
            $fileName = microtime(TRUE);
// $lastModel= ScnDocuments::f
            $f = md5($fileName) . '.' . $myfiles->extension;
            if ($myfiles->saveAs('uploads/' . $f)) {
                //$model->save();
            }
        }
    }

View Code Is :
 echo kartik\file\FileInput::widget([
        'name' => 'files',
        'options' => [
            'multiple' => TRUE,
            'accept' => 'image/*',
        ],
        'pluginOptions' => [
            'pluginOptions' => ['allowedFileExtensions' => ['jpg', 'gif', 'png'],],
            'uploadUrl' => \yii\helpers\Url::to(['/productproducts/scan']),
            
            'maxFileCount' => 10
        ]
    ]);
Error Message is : Web2Shot.jpg: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data.
thanks in advance

**Comment by kartik-v** [comment]
Read the plugin docs on the pre-requisites for ajax uploads and the response format expected by the plugin for ajax uploads.

Your [question is answered in this webtip](http://webtips.krajee.com/question/json-syntax-error-bootstrap-fileinput/).

**Comment by pc-mon** [comment]
its fixed thank you so much :)

**Comment by theTeaGreen** [comment]
Hi Kartik

I'm having trouble finding the solution for the error "SyntaxError: Unexpected token < in JSON at position 0" which occurs on single excel file upload.. I've followed docs and demos and couldn't find what I'm doing wrong. Here is my code:

<input type="file" id="januaryFile" name="tableInExcel" class="file-loading">
$('#januaryFile').fileinput({
    uploadAsync: false,
    initialPreview: [@if(!empty($januaryFile))"<h3 style='height:47px;'><i class='fa fa-file-excel-o text-success'></i></h3>January_final.xlsx"@endif],
    initialPreviewConfig: [
        {previewAsData: false, size: 576237, caption: "file.xls", width: "120px"},
    ],
    initialPreviewAsData: true,
    previewFileIcon: '<i class="fa fa-file-excel-o text-success"></i>',
    uploadIcon: '<i class="fa fa-upload"></i>',
    uploadClass: 'btn btn-success',
    uploadUrl: "{{route('admin.upload-file', 'january')}}",
    autoReplace: true,
    maxFileCount: 1,
    otherActionButtons: januaryDownloadBtn,
    overwriteInitial: true,
    maxFileSize: 3000,
    removeLabel: '',
    layoutTemplates: {actionDelete: ''},
    allowedFileExtensions: ["xlsx", "xls", "csv"],
});


Code in controller method:

if($request->hasFile('tableInExcel')) {
 $excelFile = new ExcelFile;
 $dir = 'admin_files'.$this->getDirectorySeparator().'balancing';
 $full_dir = storage_path('admin_files'.$this->getDirectorySeparator().'balancing');
 $ext = request()->file('tableInExcel')->getClientOriginalExtension();

 $storage = new Filesystem();
 if(!$storage->exists($full_dir)) {
 $storage->makeDirectory($full_dir, 0755, true);
 }
 $filename = tempnam($full_dir, '');
 unlink($filename);
 $filename = substr($filename, strrpos($filename, $this->getDirectorySeparator(), -1)+1);

 $excelFile->file_name = $filename . '.' . $ext;
 $excelFile->path_to_file = $dir.$this->getDirectorySeparator().$excelFile->file_name;

 $fullPath = $full_dir.$this->getDirectorySeparator().$excelFile->file_name;
 $storage->put($fullPath, file_get_contents($request->file('tableInExcel')));

 $excelFile->save();
 return "{}";
}

This same code worked for uploading pdf files in another project.. I'm wondering if there is something I'm missing that has to be add for excel files.

Thank you

**Comment by theTeaGreen** [comment]
Also I've tested the server code with normal file input form and it worked just fine.
