### ISSUE TITLE
on click jquery for upload button using file input with preview <Question not Issue>

### ISSUE THREAD

**Issue by mailofpravin** [kartik-v/bootstrap-fileinput#539]
Hi 
At runtime this is how the upload button code looks like
&lt;button type="submit" tabindex="500" title="Upload selected files" class="btn btn-default fileinput-upload fileinput-upload-button">
&lt;i class="glyphicon glyphicon-upload">&lt;/i> 
&lt;span class="hidden-xs">Upload&lt;/span>&lt;/button>

Can you please tell me how can I execute Jquery call on click of this button? I tried to execute using class .btn but it didnot work,see the code below :(((??
jQuery(".btn").click(function (e) {
// code here
}

**Comment by mailofpravin** [comment]
it is question, I am not sure it could be an issue?

**Comment by kartik-v** [comment]
You can read documentation and use the [upload method](http://plugins.krajee.com/file-input#method-upload) of the plugin to trigger an upload.

You may in future ask for general programming help and queries in [this new Q & A forum](http://webtips.krajee.com/questions).
