### ISSUE TITLE
Empty file names in previews for non-latin filenames

### ISSUE THREAD

**Issue by xumix** [kartik-v/bootstrap-fileinput#540]
subj
![2016-01-19 16 19 15 - - mozilla firefox](https://cloud.githubusercontent.com/assets/250118/12419629/68c71af6-bec8-11e5-9878-bb906d88982a.png)

**Comment by kartik-v** [comment]
Duplicate to #367, #482, #250, #536.

Anyway since many people are raising this.. the default slug callback will be enhanced via #541.
