### ISSUE TITLE
Compatibility with rails "data-remote=true"

### ISSUE THREAD

**Issue by kikonen** [kartik-v/bootstrap-fileinput#543]
I have trouble with this library when trying to use it in rails form, which I'm trying to submit asynchronously via rails jquery-ujs using "data-remote=true". It appears that if I add into for this widget, then form submit fails to go via desired route. This causes that X-CSRF-Token is not set into request and form submit fails.

I debugged issue some time, and noticed that when this trouble occurs, then it seems that request is not actually xhr request which is coming up in rails side. So it looks like this library is somehow causing undesired normal form submit instead of ajax form sending.

**Comment by kikonen** [comment]
okey, I found the problem; and it appears to be not due to this library (adding of this library into project, and appearence of bug just coincided each other), but hardcoded logic in jquery-ujs, which decides to ignore "remote" sending of form via XHR if any file input field exists (grrhhh).

=> thus closing as invalid

**Comment by JGutierrezC** [comment]
@kikonen how did you fix this? And what was causing it?

**Comment by kikonen** [comment]
Problem is yhat jquery-ujs rails automagic falls apart. Logic on jquery-ujs is hardcoded to use plain simple form encoded post, while more advanced controls, like fileinput, require multipart form post. Fix is to use explicit FormData to encode and send data. Beaware that some old browsers may not support FormData.

```javascript
...
     // NOTE KI MUST use explicit FormData logic since rails "data-remote=true" is hardcoded
      // to *NOT* work with file inputs
      $form.submit(function(ev) {
        var formData = new FormData($form[0]),
            action = $form.attr('action');

        console.debug("DIALOG EDIT SUBMIT");
        console.debug("DIALOG action: " + action);

        ev.preventDefault();

        console.debug("DIALOG", formData);

        $.ajax({
          url: action,
          method: 'post',
          dataType: 'json',
          data: formData,
          // http://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax
          contentType: false,
          processData: false
        })
          .then(function(data) {
            console.debug("DIALOG submitted");
            $dialog.remove();
          })
          .fail(function(jqXHR, textStatus, errorThrown ) {
            console.debug("DIALOG submit failed", jqXHR, textStatus, errorThrown, jqXHR.responseText);
            // NOTE KI normal message dispatch should take care of this
            //              ctx.showFailure(jqXHR.responseText);
          })
          .always(function() {
            console.debug("DIALOG submit handled");
          });

        // NOTE KI prevent double submit
        return false;
      });
...
```
