### ISSUE TITLE
不能同时上传多张图片?

### ISSUE THREAD

**Issue by kennedyzt** [kartik-v/bootstrap-fileinput#546]
如果用了'refresh',虽然选择了多张图片,但是只发送一次请求,如果不用‘refresh’就能够发送多次请求
                $('#repairBillsImg').fileinput('refresh', {
                    uploadExtraData: { flowUuid : data.object }
                });
              $('#repairBillsImg').fileinput('upload');

**Comment by kartik-v** [comment]
Not clear with the issue - please resubmit in english.
