### ISSUE TITLE
Widget blocked when minWidth/minHeight not met

### ISSUE THREAD

**Issue by stratoss** [kartik-v/bootstrap-fileinput#548]
This is linked with #535.

If one or more of the selected images fails, it is removed from the preview, but the widget is in error state and new images can not be selected. Also, the valid images after successful upload are still stuck with src blob://domain/xyz-xyz-xyz instead with http://domain/path-to/image.jpg for example, which is done if no failing images were selected.

**Comment by kartik-v** [comment]
Cannot reproduce this. 

You can check the [max dimensions demo](http://plugins.krajee.com/file-image-dimensions-demo#max-image-dimensions) and try with a set of files... after a validation error you can still select additional files.

**Comment by stratoss** [comment]
The missing part should be the automatic upload when a batch is selected. I'm doing it like:

    picturesInput.on('filebatchselected', function() {
        $.ajaxSetup({timeout: 999999999 });
        $('input[name="picturesInput"]').fileinput('upload');
    });

**Comment by kartik-v** [comment]
I presume your query was you cannot select additional files - which is not an issue as I said. 

Now I see the above code you have is for auto uploading files batch on selection. If your query is to upload files... the files that have passed validation (without error) will be uploaded. You can test with the [max dimensions demo](http://plugins.krajee.com/file-image-dimensions-demo#max-image-dimensions) and check manually.

Note in additional to `filebatchselected` You may trap the `fileerror` event if you want to do any additional validation for errors faced during upload
