### ISSUE TITLE
upload AJAX

### ISSUE THREAD

**Issue by redimongo** [kartik-v/bootstrap-fileinput#551]
Hi I am having issues with your AJAX upload.
I have no idea where the image is being uploaded or what $bdInteli means?
<code>
$nombre = $_FILES["ficheroExcel"]["name"];
  $bdInteli = $_POST['bdInteli'];
  if ( move_uploaded_file ( $_FILES["ficheroExcel"]["tmp_name"] , $nombre ) ){
  $output = array('uploaded' => 'OK' );
</code>

my javascript
<code>
$("#input-700").fileinput({
        uploadUrl: "uploadimage", // server upload action
        uploadAsync: true,
        maxFileCount: 10
    });
</code>

If there by any chance is a demo guide that would be great

**Comment by kartik-v** [comment]
Most of your query is related to server coding at the developer's end.This is similar to how you handle any file upload through a native HTML file input. For ajax uploads, the plugin requires a JSON response from server and also can sends a JSON to the server depending on the configuration. Read [about ajax uploads in plugin documentation](http://plugins.krajee.com/file-input#ajax-uploads).

You can post [generic programming queries or request for help in the Q & A forum](http://webtips.krajee.com/questions).
