### ISSUE TITLE
Problem when i upload vertical images

### ISSUE THREAD

**Issue by nevits8as** [kartik-v/bootstrap-fileinput#553]
My vertical images in the thumbnail look good when I see the result in the website appear horizontal, i used async upload and the plugins CANVAS for resize images. The images details for example: dimension 2592 x 3888 px and size 920kb

**Comment by kartik-v** [comment]
This is to do with EXIF tags in the image. [Read this comment](https://github.com/kartik-v/bootstrap-fileinput/issues/491#issuecomment-153959223).
