### ISSUE TITLE
enhancement: upload directories using webkitdirectory

### ISSUE THREAD

**Issue by akorinek** [kartik-v/bootstrap-fileinput#554]
Sometimes it's useful to upload directories with recursive files in them. This is an example:

https://jsfiddle.net/Z4Amr/107/

Microsoft Edge supports this: https://msdn.microsoft.com/en-us/library/mt574730(v=vs.85).aspx
so does Google Chrome.

**Comment by kartik-v** [comment]
This is not a consistent standard between all browsers (except majorly Chrome)... will probably see and consider an enhancement for this based on support...

**Comment by kartik-v** [comment]
Check the [demo pages for some examples of using webkitdirectory for folder upload](http://plugins.krajee.com/file-folder-upload-demo).
