### ISSUE TITLE
How to check file input is null?

### ISSUE THREAD

**Issue by clashjedsada** [kartik-v/bootstrap-fileinput#556]
How to check file input is null before submit form ?

I have to manually call  $('#inputfile').fileinput('upload'); after validation fill form.
When file input is null,I want to submit only fill form not start upload files.

I sorry if I type not understand.

**Comment by kartik-v** [comment]
Please use the [Q & A forum](http://webtips.krajee.com) for posting generic programming help and queries. Use this repo only for reporting bugs and enhancements.

You can check if the file input value `$("#input").val()` is empty for your use case.
