### ISSUE TITLE
 " 23.jpg: SyntaxError: Unexpected token <. "

### ISSUE THREAD

**Issue by joelZC** [kartik-v/bootstrap-fileinput#563]
im programming in asp.Net mvc 6 vNext and i implementing this fileinput, but i have a problem in my ActionResult i return the view index but the view appears into of div with class .file-error-message and i dont know how fix, might help me please?
![mistake](https://cloud.githubusercontent.com/assets/11599718/12849235/226bad78-cbe4-11e5-942d-b386b4aa5a66.PNG)

**Comment by kartik-v** [comment]
Please post [programming queries in the Q & A forum](http://webtips.krajee.com/questions).
