### ISSUE TITLE
Preview is shown for mime type which isn't allowed

### ISSUE THREAD

**Issue by tombevers** [kartik-v/bootstrap-fileinput#564]
Hi,

I'm encountering an issue when filtering to allow the preview to be shown only for certain mime types by using the following input file element:

`<input type="file" id="file" name="file[uploadedFile]" required="required" class="file" accept=".pdf, .png, .doc, .key, " data-initial-caption="Select a File" data-show-upload="0" data-show-remove="0" data-allowed-preview-types="object" data-allowed-preview-mime-types="image/png, image/gif, application/pdf, image/jpeg, image/pjpeg">`

I correctly can only select files with an **pdf, .png, .doc or .key (Keynote)** extension. And want to display the preview for all of them except for the Keynote files. I'm filtering with the **allowedPreviewMimeTypes** option but it seems this isn't taken into account for the Keynote files which has a application/octet-stream mime type (It displays Loading File 1 of 1... and my browser tab keeps loading and becomes unresponsive)

**Comment by kartik-v** [comment]
You have set `allowedPreviewTypes` in addition to `allowedPreviewMimeTypes` - both conditions will be evaluated and if one of them is `true` the plugin will try to read the content and preview the file...

Do not set `allowedPreviewTypes` for your use case above.

You can post queries for general programming help and tips [in this new Q & A Forum](http://webtips,krajee.com/questions) in future.

**Comment by tombevers** [comment]
Leaving out the allowedPreviewTypes doesn't solve the problem as it still try's to render the keynote file ...

<input type="file" id="file" name="file[uploadedFile]" required="required" class="file" accept=".pdf, .png, .doc, .key, " data-initial-caption="Select a File" data-show-upload="0" data-show-remove="0" data-allowed-preview-mime-types="image/png, image/gif, application/pdf, image/jpeg, image/pjpeg">

**Comment by kartik-v** [comment]
Ok to clarify it better, set it to null and do not set a value there. If you do not at all set a value to `allowedPreviewTypes` then as per the [default settings mentioned in docs](http://plugins.krajee.com/file-input#option-allowedpreviewtypes) - it defaults to all file types i.e. `['image', 'html', 'text', 'video', 'audio', 'flash', 'object']`.

instead just set `allowedPreviewTypes` to null. Check [this demo for an example](http://plugins.krajee.com/file-preview-icons-demo#custom-preview-icons-2)

**Comment by tombevers** [comment]
When using data attributes this doesn't work.

**Comment by kartik-v** [comment]
You can set it to `false` as well...
