### ISSUE TITLE
Bower "bootstrap" requirement

### ISSUE THREAD

**Issue by marvinrabe** [kartik-v/bootstrap-fileinput#568]
In my project I use the "bootstrap-sass" bundle with this library. But due the requirement from fileinput of "bootstrap" I end up with 2 bootstrap versions (the less and sass version).

Would it be possible to drop the requirement of bootstrap? Its pretty obvious to use this library alongside bootstrap. Other bootstrap specific libraries include "bootstrap" in their requirements neither (e.g. bootstrap-datepicker).

**Comment by kartik-v** [comment]
Please search for similar issue before posting. This looks duplicate to #523.

You can use `sass` branch of the repo for this.
