### ISSUE TITLE
Delete not working without initialPreview sent back

### ISSUE THREAD

**Issue by f0nt4** [kartik-v/bootstrap-fileinput#569]
Hi,

I've been working with this js now since the start of the week and I got everything working, uploading/deleting etc.
There is only one thing that bugs me.

 As you can see in my function: http://puu.sh/n5jQs/c3a0d9a5c3.png
I add initialPreview and initialPreviewConfig to the json response.
The html included in initialPreview is fine and working for images, but not for other type of documents like pdf's and txt files.

However if I only respond with the initialPreviewConfig and leave the initialPreview out, deleting of the files is not working. While I am returning the url for deletion together with the other needed data.

How can I make it so that deletion is working, but the default preview templates are used?
I don't want to be writing hundreds of lines of php to make a response for every type of file possible while the JS already has the templates.

Please help!

This is btw how i enable the js: http://puu.sh/n5kiO/7b6f0a773a.png

**Comment by rajjanorkar** [comment]
Same thing is happening for me as well. Below is my situation.
I can upload images and also can delete images. It is just last image i am not able to delete.
it says " You must select at least 1 file to upload." when i click on delete icon.

Please note i can delete all other images uploaded it is just the last one i can not delete.

**Comment by kartik-v** [comment]
Please read the plugin documentation. Most of what you need depends on how you configure the plugin with available options. For example, the alert msg that you must select at least 1 file is because you have specified minFilecount to 1 (check your config) and also check validateInitialCount.

**Comment by rajjanorkar** [comment]
Hi @kartik-v ,

Thank you i selected validateInitialCount: true, minFileCount: 0, but still it is not allowing me to delete last image loaded using initialPreview, i can delete all other images no issues there. It is just last image giving  error.

Thank you

**Comment by f0nt4** [comment]
Hi Kartik, I removed the MAXfilecount option and have removed multiple from the input field.

But whatever I do, if I dont sent initialpreview AND initialpreviewconfig back from the server, deleting is not working.
When I do sent back both it is working.
But I want the plugin to use the default templates.

I did read the documentation, all of it, but I can't find an option to only sent the initialpreview config and have deletion working.

And @rajjanorkar please open your own issue, now kartik closed mine without answering me. Your issue is not the same as mine. I am able to delete but I just want the plugin to use the default templates for the different file types.

@kartik-v could you please also check my question?

**Comment by kartik-v** [comment]
@f0nt4 your question is about preview of files from server... you need to render them similarly like you render images via your server code. This is out of scope of the plugin (as it needs to be entirely dependent on content that you render from your server) and examples are provided. While for images there is a `img` tag and you can style it as seen in examples... for other content like text you need to bring in the content similarly from your server. PDF content cannot be directly embedded from server and may need other plugins. 
You can do this before upload from the plugin because browsers natively support reading local PDF files on browser via embedded object... and hence the plugin has added this capability to the preview. But for server uploaded files you need to write your own code to get them previewed.

**Comment by f0nt4** [comment]
@kartik-v Thanks for your answer. I was hoping there was some way for the plugin to render the needed html if I just give back the link to the file.
At the moment I'm writing some stuff in php to see if that's able to determine the mime of the file and according to that give back the right html to display the file.
If I get it to work I'll sent it to you so maybe you can put it in the documentation for others.
We'll see.

Hmm, just a quick thought, wouldn't it be possible in javascript to get a file from the server and load it into a div? The file input div in this case?
Maybe we could do something like, when document is loaded, get the value from a hidden input field and show it in the div.
But maybe this would involve downloading the file from the server to the browser, and with big files, that's not something you would want.

**Comment by kartik-v** [comment]
Yes the idea is if you have an HTML content in a file on server... you can only read it via your SERVER code and instead of populating the content in a hidden field and again reading via javascript - you can directly return this markup within an embedded div via initialPreview and it will get displayed.

**Comment by f0nt4** [comment]
Ok, so I got everything working. Here's the code to the function I wrote.
You may distribute it if you would like because it might come in handy for others.
http://hastebin.com/inatibekuv.php
Please let me know what you think of it!

When I got some more time and cleaned my code I'll also write a little tutorial how I implemented the plugin to my site running Laravel 5.

**Comment by kartik-v** [comment]
Looks good (just had a glance at the code). You have taken in the default content preview templates available in the plugin and returned the same via your PHP code. Just be careful of the size of the content you are reading via `file_get_contents` and of course any access restrictions you may want to enforce to users when reading content.

**Comment by f0nt4** [comment]
Yeah, I did take in the default preview templates and it all works similar to your code in Javascript.
It checks for some filetypes and if it can't be found it will handle the file as an object.

Taken your caution in consideration I changed the function a little bit.
It now checks if the text file isn't bigger than 10MB and if it is it doesn't load it.

http://hastebin.com/evijikokov.php

The restrictions on filetypes can be done in the plugin options itself, in the formvalidation and in the upload function in php so I left it out here.

**Comment by f0nt4** [comment]
@kartik-v as promised all the code I used to make this work in my Laravel application.
It was a lot of work and I hope it might help someone when they try to accomplish the same.
http://hastebin.com/inepojabeg.html

The end result is like this:
![preview](https://i.imgur.com/Q0n9YYS.png)

**Comment by kartik-v** [comment]
Thanks for the update. Will close this issue...
