### ISSUE TITLE
RegEx for filenames

### ISSUE THREAD

**Issue by mishabroflovski** [kartik-v/bootstrap-fileinput#570]
It would be nice, to have a validation for file name with custom error message. Now, i should make this validation on server.

**Comment by kartik-v** [comment]
You already have this functionality within the plugin to write your custom validation and show an error and abort the upload. You need to use available plugin events - for example `fileloaded` or `filepreupload` for your use case. Then do your validation and return an error as described in the [events manipulation section of the documentation](http://plugins.krajee.com/file-input#event-manipulation).
