### ISSUE TITLE
Auto upload refresh problem

### ISSUE THREAD

**Issue by marioene** [kartik-v/bootstrap-fileinput#580]
Hi,
First, great plugin. I implemented with success this plugin in Laravel 5.2.

After this code:

```
uploadUrl: "{{ URL::to('ajax_UploadImage') }}", 
uploadExtraData: function() {
    return {
        id: path,
      };
}
}).on("filebatchselected", function(event, files) {
    $("#images").fileinput("upload");
});
```

I have 2 issues after auto-upload (resolving issue no 1, issue no 2 is not bother me at all):

1. After auto upload, I don't get the real files names generated with Ajax uploadUrl (method in Laravel controller). 

2. After auto upload I want to refresh plugin without inserting this code  `location.reload(true);`
and preview the files with names saved and generated from Ajax uploadUrl

**Comment by kartik-v** [comment]
You may need to run through examples in [ajax demo 5](http://plugins.krajee.com/file-input-ajax-demo/5) and [ajax demo 6](http://plugins.krajee.com/file-input-ajax-demo/6) to achieve your use case and it may not need location.reload.

Will suggest if you can use the [Q & A forum](http://webtips.krajee.com/questions) for generic programming help.
