### ISSUE TITLE
Tags in MySQL

### ISSUE THREAD

**Issue by agustinzirit** [kartik-v/bootstrap-fileinput#582]
Good afternoon, boys. Currently I am implementing this model to show the user images with tags for each photo that is in the gallery. My question is , how can I store these custom tags in my databases?

PS : I'm working with laravel 5.0 .

Thank you... :)

**Comment by kartik-v** [comment]
Please use this repo to only post bugs and enhancements related to the plugin.

You may [use the Q & A forum](http://webtips.krajee.com/questions) for getting programming help or tips.
