### ISSUE TITLE
when uploaded with ajax, how to remove it also on server side

### ISSUE THREAD

**Issue by dakanadaka** [kartik-v/bootstrap-fileinput#583]
$("#input-700").fileinput({
                                    uploadUrl: "<?php echo site_url("diseases/upload_images");?>", // server upload action
                                    uploadAsync: false,
                                    showUpload: false, // hide upload button
                                    showRemove: false, // hide remove button
                                    minFileCount: 1,
                                    maxFileCount: 5,
                                }).on("filebatchselected", function(event, files) {
                                    // trigger upload method immediately after files are selected
                                    $("#input-700").fileinput("upload");
                                }).on("filebatchuploadsuccess", function(event, data) {
                                    console.log("id: "+data.jqXHR.responseJSON.id);
                                    console.log("image: "+data.jqXHR.responseJSON.msg.upload_images);
                                });
                                $("#input-700").on("filepredelete", function(jqXHR) {
                                    var abort = true;
                                    if (confirm("Are you sure you want to delete this image?")) {
                                        abort = false;
                                    }
                                    return abort; // you can also send any data/object that you can receive on `filecustomerror` event
                                });
                                
I have made upload with ajax to server, but on the same upload, after uploaded image to server, if user decide to remove it, it removes only on frontside and not on serverside.

I found on http://plugins.krajee.com/file-input-ajax-demo/3 how to delete, already uploaded images, this could work as edit of form, but upload on serverside with ajax and then remove image on serverside? Could not find how? Can you help?

**Comment by alexandcote** [comment]
Check removeURL

**Comment by kartik-v** [comment]
The ajax demo 3 already shows how you can call a server url to delete. 

Please use this repo to only report plugin bugs and enhancements.

For getting programming help or tips you can use the [webtips Q & A forum](http://webtips.krajee.com/questions)
