### ISSUE TITLE
extra uploading data not append to FormData submitted

### ISSUE THREAD

**Issue by hawa11** [kartik-v/bootstrap-fileinput#584]
I saw the code in uploadSingle method that around raise preupload Event is:
               `self.raise('filepreupload', [outData, previewId, i]);
                $.extend(true, params, outData);
                if (self.abort(params)) {
                    jqXHR.abort();
                    self.setProgress(100);
                }`
and it's not appending my extra data to FormData(I have to use `data.form.append()` in the callback of preupload Event).
Is there something I misunderstood?

**Comment by kartik-v** [comment]
Yes you seem to have misunderstood and need to check your code.

The code snippet from the plugin you posted will only execute if you have triggered an abort yourself (i.e aborted the ajax request).

Upload extra data will be sent along with the files to your server request.
