### ISSUE TITLE
Delete php script

### ISSUE THREAD

**Issue by johnnyhello** [kartik-v/bootstrap-fileinput#585]
Hello,

I implemented initialPreview and initialPreviewConfig settings.
And im not sure how answer should look like from php delete script.

I wrote this script:

<?php

if(isset($_POST['key'])){
    unlink($_POST['key']);
    $output = ['error' => "0"];
    echo json_encode($output); 
}

?>

The file is deleted from server but i recieve error frame like this:
SyntaxError: Unexpected token j.

There is no success response.

Can you help please ?

**Comment by kartik-v** [comment]
Use this repo to only report plugin bugs and enhancements.

You can use the [webtips Q & A forum](http://webtips.krajee.com/questions) for getting programming help or tips.
