### ISSUE TITLE
how to delete a uploaded file

### ISSUE THREAD

**Issue by smalla123** [kartik-v/bootstrap-fileinput#586]
on the new page. i upload a file and get the fileID from server. next, i want to delete the file from server. how to do that ?  click the close button and write ajax request  by myself ? or bootstrap-fileinput has already implemented ? or update the preview using the fileID?

**Comment by kartik-v** [comment]
Check [ajax demo 3](http://plugins.krajee.com/file-input-ajax-demo/3) for an example. You may post programming help related queries in the [webtips Q & A forum](http://webtips.krajee.com/questions).
