### ISSUE TITLE
Plugin now working correctly in Safari Browser

### ISSUE THREAD

**Issue by NaveedMashkraft** [kartik-v/bootstrap-fileinput#587]
The plugin is not working properly in Safari browser. The loading animation is appearing but when you click on it opens the uploading popup.
![untitled-1](https://cloud.githubusercontent.com/assets/17641327/13525254/b1726158-e221-11e5-81c0-6cfe9e7b3a0e.jpg)

**Comment by kartik-v** [comment]
You need to debug your code, other plugins/JS loaded, and check for any JS errors on your browser console.

Secondly, read plugin documentation [for required browser support](http://plugins.krajee.com/file-input#browser-support).
