### ISSUE TITLE
Problem to translate script.

### ISSUE THREAD

**Issue by ADDproducciones** [kartik-v/bootstrap-fileinput#589]
when I use the script file input.**min**.js and I add the Spanish language, it does not work.

If I switch to **input.js** the translation works, but when I try to delete an image, the script returns the following error:

> You must select at least 1 file to upload.

Thanks for your time.

**Comment by kartik-v** [comment]
Cannot reproduce your use case. Hope you have read the docs.

You need to ensure that you are setting the plugin for multi-language correctly. Refer [the multi language demo](http://plugins.krajee.com/file-multi-lang-demo) for details - the demo page uses minified js.
