### ISSUE TITLE
How do I populate the InitialPreview from ajax?

### ISSUE THREAD

**Issue by SigalZ** [kartik-v/bootstrap-fileinput#591]
Hello,

I want to populate the InitialPreview files with ajax. Getting the files from the database.

I can't find anywhere how to do that.

Can you please help?

**Comment by kartik-v** [comment]
You may [cross check the plugin demos](http://plugins.krajee.com/file-input) and the [webtips forum](http://webtips.krajee.com) for some examples.

Request to use this repo only for bug reporting and/or any enhancements.

If you have general programming queries or need tips refer/submit them in the [Q & A Forum](http://webtips.krajee.com/questions).

**Comment by SigalZ** [comment]
Thank you, but I can't find any example that answer that. All the examples have hard coded InitialPreview, not populating from database.

Apologies for posting here
