### ISSUE TITLE
 pre-loaded images are lost

### ISSUE THREAD

**Issue by agustinzirit** [kartik-v/bootstrap-fileinput#593]
Good afternoon , when the images are preloaded to preview and I save, says the amount there.. but if I delete a pre-loaded image, as if all erased internally, though still less visible images N which was removed. Who can help ?

**Comment by kartik-v** [comment]
Cannot clearly understand the question but it seems like you have a server code issue here. You would need to check your server code that deletes the files and then pass the right initial preview to the plugin from the server.

If you need programming help please [post them in the Q&A forum](http://webtips.krajee.com/questions). Use this repo for only posting bugs and enhancements.

**Comment by agustinzirit** [comment]
I do not understand that closes the issue if not resolved the doubt. But thanks .
----
No entiendo por que cierra el tema si no esta resuelto la duda.  Pero bueno, gracias.
