### ISSUE TITLE
requiredfieldvalidator Problem

### ISSUE THREAD

**Issue by h-sobhy** [kartik-v/bootstrap-fileinput#594]
When use multiple or single file upload and when there is a **requiredfieldvalidator** for the file input, if file(s) selected then clicked the browse button again and canceled, the validatore become enabled. This is might be okay when it's not in the multiple file mode since the field get cleared from any value but when use multiple files (in asp.net) the **requiredfieldvalidator** never get disabled until adding another file.

From another side, If I want to get the Validator enabled when remove the file added to the multiple file mode using **"file remove icon"**, I couldn't find an event to check that there is less than one file as well as the event of the drop zone **"fileCleared"** ... I'm sure there is a way but I couldn't catch. I had to use something like the following:
    
    $(document).ready(function () {
        $(document).on('click', '.kv-file-remove', function (e) {
            checkFiles();
        });
        var $btnUpload = $('#<%= btnUpoad.ClientID%>');
        var $flImg = $('#<%= flImg.ClientID%>');
        $btnUpload.prop('disabled', true).addClass('btn-disabled');
        var $imgVal = $('#<%= rfvUploaderMainImg.ClientID%>');
        $flImg.change(function () {
            checkFiles();
        });
    });
    function checkFiles() {
        setTimeout(function () {
            var $btnUpload = $('#<%= btnUpoad.ClientID%>');
            var _val = $(".file-preview-thumbnails").children('.file-preview-frame').length;
            if (_val > 0) {
                $btnUpload.prop('disabled', false).removeClass('btn-disabled').addClass('btn-primary');
                ValidatorEnable($imgVal[0], false);

            } else {
                $btnUpload.prop('disabled', true).removeClass('btn-primary').addClass('btn-disabled');
                ValidatorEnable($imgVal[0], true);

            }
        }, 1500);
    }

**Comment by kartik-v** [comment]
Can you elaborate with a JS Fiddle on what you are trying to do?

What is the **requiredfieldvalidator** here - is it the HTML5 required validation OR your own code? If its some prebuilt validation inside your server framework - then you need to check the code accordingly...

**Comment by h-sobhy** [comment]
It's an **ASP.NET** validator. I use the file-input plugin in this page only as a preview pan only (I don't do an AJAX upload here but I use code behind and worked well) then check if not ZERO files selected and also ZERO errors displayed and if so enable the submit button but if not display the asp.net validator while the submit button still disabled. I apply this technique on many other cases and works fine logically (even when I pass fake values as variables ( errorMsgs = 0 and prevFrames that has no error class = 2 for example). 

I tried to upload to fiddle but since I'm using asp.net so it's a bit hard to do it ... **All I need is a proper accurate way** to check if files in the drop-zone are **not zero **and that there is **no errors **... 

Here is [the Fiddle ](https://fiddle.jshell.net/dr7n9do5/3/) I could send at the moment (browse for a small photo to get an error).

**Comment by h-sobhy** [comment]
@kartik-v 
I do the check on file-input change, when files in the preview delete-icon clicked,  fileselectnone and filecleared.

Thank you for the plugin by the way :)
