### ISSUE TITLE
Default value coverage problem

### ISSUE THREAD

**Issue by phpyii** [kartik-v/bootstrap-fileinput#595]
set allowedPreviewTypes = ['image', 'html', 'text', 'video', 'audio', 'flash'];

The final result is allowedPreviewTypes = ['image', 'html', 'text', 'video', 'audio', 'flash', 'object'];

Object is appended.

**Comment by phpyii** [comment]
I saw #544's problem.

**Comment by kartik-v** [comment]
No that's not correct and cannot reproduce. You may need to check your code and if you are running the updated release.

Note that `allowedFileTypes` is different from `allowedPreviewTypes`. Refer the documentation.

- An example of `allowedFileTypes` [can be referred here](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-8).
- An example of `allowedPreviewTypes` [can be referred here](http://plugins.krajee.com/file-preview-icons-demo#custom-preview-icons-3).

**Comment by kartik-v** [comment]
I think you may be right for the preview types... will update...

**Comment by jun9358** [comment]
It still occured on latest commit(d870e37aa0828241c379543f464451af121bdc57).

>set options like
`$('#files').fileinput({
  showPreview: true,
  allowedPreviewTypes: ['image']
});`

>on _previewFile(), this.allowedPreviewTypes return 
["image", "html", "text", "video", "audio", "flash", "pdf", "object"]
