### ISSUE TITLE
Problem Ajax Request inside filepreupload / wait before upload

### ISSUE THREAD

**Issue by lugaru90** [kartik-v/bootstrap-fileinput#596]
Hey,

i'm using your Yii Plugin. Nice work :) I'm trying to build the following:
1: Select Images
2: On pressing Upload, inside filepreupload an ajax call is fired, which will add Meta information to the Database
3: The ajax call returns the insertion ID, which should be added to extra Data
4: The file upload starts and a form is shown to edit the Meta information

This don't work, because javascript is async - aware of that - but can i stop and continue your upload process anyhow inside filepreupload?

Thanks!

**Comment by kartik-v** [comment]
You should not be overriding preupload to do the upload - its quite conflicting.

Use `uploadExtraData` instead to pass the parameters to the uploadUrl - it can be setup as a callback as well and your uploadUrl can be the processing action that does everything from inserting metadata to actually processing the file upload.
