### ISSUE TITLE
refresh not working

### ISSUE THREAD

**Issue by MinaGabriel** [kartik-v/bootstrap-fileinput#597]
I have a gridview, one of it's columns is to manage images for the row data. 
so every time user click manage image button, i recall the library to rebuild the fileinput based on the new option to show corresponding images for the clicked row, this works fine, the issue is if row 1 has images and row 2 doesn't, if i click manage images for row 1 it loads images fine, and if i close and open row 2 manage images-which doesn't have any images - it shows the images from row 1 initialview, i used 'refresh' and still not working. 
how do i fix this and **reset the initialview**, BTW i'm using ASP.net gridview and when i change paging it loads the new row data successfully - so partial post-backs reloads the initialview -

here is my JS code - this snippet inside ajax success function i call it ever time user click manage image as shown in the gif-: 

                   `success: function (data) {
                    $.each(data.d, function (index, value) {
                        initialPreviewArray.push("<img src='" ...............>");
                        var obj = {};
                        obj.caption = value.Url;
                        obj.width = '100px';
                        obj.key = value.ID;//TreeImageID
                        obj.url = ['<%=ResolveUrl("AjaxFileDelete.ashx")%>';]
                        obj.extra = {treeId : treeId,url: value.Url};

                        initialPreviewConfigObjArray.push(obj);

                    });
                   
                    $("#input-4").fileinput('refresh',{
                        uploadUrl: '<%=ResolveUrl("AjaxFileHandler.ashx")%>',
                        'allowedFileExtensions': ['jpg', 'png', 'gif'],
                        uploadExtraData: { uploadTo: 'categories', treeId: treeId },
                        overwriteInitial: true,
                        initialPreview: initialPreviewArray,
                        initialPreviewShowDelete: true,
                        initialPreviewConfig: initialPreviewConfigObjArray`

![2016-03-20_15-16-47](https://cloud.githubusercontent.com/assets/1890049/13906570/e79565b0-eeaf-11e5-8fc3-524e54d5a10f.gif)

**Comment by kartik-v** [comment]
You may need to check how you are initializing the plugin... it typically must not be on a generic selector (like CSS class or input name) for such a use above. Since if this is done you may be conflicting and duplicating the plugin initialization for other rows.

For an use case like above you must set an unique id for each file input and initialize the plugin separately for each file input id using the id as a selector.

**Comment by MinaGabriel** [comment]
it might be an ugly work around but i partially postback my page on every Manage Image click, to reload the library.

          $('.close, .modal-footer :button').click(function () {
                __doPostBack('', null);

            });

**Comment by abbasmhd** [comment]
faced the same problem  
looking at the `fileinput.js` codes, i found that when you use `initialPreview` to add files the class `.file-preview-initial` will be added,  `refresh` nor `clear` are able to clear it `not(.file-preview-initial)`

the only way to do it is to `destroy` and recreate the fileinput
please let me know if you found any other way

**Comment by Szymon-dziewonski** [comment]
Have same problem here it breaks preview view and reload images without upload 

var upload = $("#input-700").fileinput({
      uploadUrl: "/admin/myimageupload/news/2", // server upload action
      uploadAsync: true,
      maxFileCount: 5,
      showUpload: false
    });
  
    $('#button_submit').on('click', function (e) {
      upload.fileinput('refresh', {
        uploadUrl: "/admin/myimageupload/news/2"
      }).fileinput('upload');
      
    });

normal upload works .fileinput("upload") works too , but using refresh function breks preview and alos sens only one file to php ..

**Comment by WallenHan** [comment]
@ Szymon-dziewonski  thanks for your resolution.I just want every time reset the uploadFile.

**Comment by radcloudcorp** [comment]
In my case I solved it by appending the data-overwrite-initial="true" property to the input.
