### ISSUE TITLE
maxFileCount is not check correctly

### ISSUE THREAD

**Issue by djbuch** [kartik-v/bootstrap-fileinput#598]
Hello,

I'm using your great plugin to do both multiple file upload and single file upload in ajax asynchronus.

But I cannot manage the plugin to keep only one file when wanting to upload a single file only.

If fact I managed to do the same with you Ajax example here : http://plugins.krajee.com/file-count-validation-demo
When I select one file, click upload, then select another file and click upload, I'm able to select more that 4 files.

Have you any ideas, am I doing things the wrong way ? Many thanks for your help.

David

**Comment by kartik-v** [comment]
`maxFileCount` will validate count of files selected from only the client... it does not understand what or how much has been uploaded on server... 

To achieve and validate server uploaded file count --- you need to set `validateInitialCount` to `true` and then set `initialPreview` to a list of files that are uploaded on your server... you also may want to set `showUploadedThumbs` to `false` to prevent showing successfully uploaded thumbnails.

**Comment by edsonvictor09** [comment]
how can i maxfilecount combine this four when you upload in can be 30 max picture to be upload


<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use kartik\widgets\FileInput;

echo $form->field($model, 'filesdir')->hiddenInput(['value'=> $model->filesdir])->label(false);
echo $form->field($model, 'img')->hiddenInput(['value'=> $model->img])->label(false);
?>

<ul class="nav nav-tabs flex-column flex-md-row"" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#bedroom" role="tab">Bedroom</a>
  </li>
   <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#bathroom" role="tab">Bathroom</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#floorplan" role="tab">Floor Plan</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#others" role="tab">Other Pictures</a>
  </li>
</ul>
    <div class="tab-content">
		<div id="bedroom" class="tab-pane in active">
            <div class="row bedroom_image_row_cont" style="margin:0; margin-top: 5%;">
            <?php
	
                    echo "<div class='col-5 col-md-5'>";
                    echo $form->field($model, 'bedroom_images',[
                            'template' => '{input}',
                        ])->widget(FileInput::classname(), [					
                        'options' => ['accept' => 'image/*','multiple' => true, 'class' => 'facility_upload_btn', 'data-src' => 'bedroom_image_row_cont', 'data-error' => 'bed_image_error'],
                        'pluginOptions' => [
                        	'maxFileCount' => '',
                            'autoReplace'=> true,'validateInitialCount'=>true,'maxFileSize'=>10000,
                            'allowedFileExtensions' => ['jpg', 'jpeg', 'gif', 'png'],	
                            'resizeImage' => true,				
                            'showCaption' => false,
                            'showRemove' => false,
                            'showUpload' => true,
                            'browseClass' => 'btn btn-default btn-block btn-sm',
                            'uploadClass' => 'btn btn-default btn-block btn-sm',
                            'browseIcon' => '',
                            'browseLabel' =>  'or <span>Browse File</span>',
                            'uploadUrl' => Url::to(['dashboard/upload_unit_pics/'.$model->id]),
                            'deleteUrl' => Url::to(['dashboard/delete_unit_pic/'.$model->id]),
                            'uploadExtraData' => [
                                'tag'=>'bedroom'
                            ],	
                            'deleteExtraData' => [
                                '_csrf' => \yii::$app->request->csrfToken,
                            ],							
                            'initialPreview'=>isset($contents['initialPreview']['bedroom']) ? $contents['initialPreview']['bedroom'] : [],							
                            'initialPreviewConfig' => isset($contents['initialPreviewConfig']['bedroom']) ? $contents['initialPreviewConfig']['bedroom'] : [],						
                            'initialPreviewAsData'=>true,
                            'initialPreviewShowDelete'=> true,
							'overwriteInitial'=>true,	
							'showAjaxErrorDetails'=>true,	
							'removeFromPreviewOnError'=>true																					                            																						
                        ],									
                    ])->label('Bedroom');
                    echo "<div id='bed_image_error' style='width: 40%;
    margin: 0 auto;  margin-top: 2%;'></div>";	
                echo "</div>";
            ?>
            </div>
        </div>
        
        <div id="bathroom" class="tab-pane in">
            <div class="row bathroom_image_row_cont" style="margin:0; margin-top: 5%;">
            <?php
                echo "<div class='col-5 col-md-5'>";
                    echo $form->field($model, 'bathroom_images',[
                            'template' => '{input}',
                        ])->widget(FileInput::classname(), [					
                        'options' => ['accept' => 'image/*','multiple' => true, 'class' => 'facility_upload_btn', 'data-src' => 'bathroom_image_row_cont', 'data-error' => 'bath_image_error'],
                        'pluginOptions' => [
                            'maxFileCount' => '',
                            'validateInitialCount'=>true,
                        	'maxFileSize'=>10000,
                            'allowedFileExtensions' => ['jpg', 'jpeg', 'gif', 'png'],
                            'resizeImage' => true,
                            'showCaption' => false,
                            'showRemove' => false,
                            'showUpload' => true,
                            'browseClass' => 'btn btn-default btn-block btn-sm',
                            'uploadClass' => 'btn btn-default btn-block btn-sm',
                            'browseIcon' => '',
                            'browseLabel' =>  'or <span>Browse File</span>',
                            'uploadUrl' => Url::to(['dashboard/upload_unit_pics/'.$model->id]),
                            'deleteUrl' => Url::to(['dashboard/delete_unit_pic/'.$model->id]),
                            'uploadExtraData' => [
                                'tag'=>'bathroom'
                            ],	
                            'deleteExtraData' => [
                                '_csrf' => \yii::$app->request->csrfToken,
                            ],					
                            'initialPreview'=>isset($contents['initialPreview']['bathroom']) ? $contents['initialPreview']['bathroom'] : [],							
                            'initialPreviewConfig' => isset($contents['initialPreviewConfig']['bathroom']) ? $contents['initialPreviewConfig']['bathroom'] : [],						
                            'initialPreviewAsData'=>true,
                            'initialPreviewShowDelete'=> true,
							'overwriteInitial'=>true,	
							'showAjaxErrorDetails'=>false,	
							'removeFromPreviewOnError'=>true																					                            																						
                        ],									
                    ])->label('Bathroom');
                     echo "<div id='bath_image_error' style='width: 40%;
    margin: 0 auto;  margin-top: 2%;'></div>";	
                echo "</div>";		
            ?>
            </div>
        </div>
        <div id="floorplan" class="tab-pane in">
            <div class="row floor_image_row_cont" style="margin:0; margin-top: 5%;">
                <?php
                    echo "<div class='col-5 col-md-5'>";
                    echo $form->field($model, 'floorplan_images',[
                            'template' => '{input}',
                        ])->widget(FileInput::classname(), [					
                        'options' => ['accept' => 'image/*','multiple' => true, 'class' => 'facility_upload_btn', 'data-src' => 'floor_image_row_cont', 'data-error' => 'floor_image_error'],
                        'pluginOptions' => [
                            'maxFileCount' => '',
                            'validateInitialCount'=>true,
                        	'maxFileSize'=>10000,
                            'allowedFileExtensions' => ['jpg', 'jpeg', 'gif', 'png'],
                            'showCaption' => false,
                            'showRemove' => false,
                            'showUpload' => true,
                            'browseClass' => 'btn btn-default btn-block btn-sm',
                            'browseIcon' => '',
                            'browseLabel' =>  'or <span>Browse File</span>',
                            'uploadClass' => 'btn btn-default btn-block btn-sm',
                            'uploadUrl' => Url::to(['dashboard/upload_unit_pics/'.$model->id]),
                            'deleteUrl' => Url::to(['dashboard/delete_unit_pic/'.$model->id]),
                            'uploadExtraData' => [
                                'tag'=>'floorplan'
                            ],	
                            'deleteExtraData' => [
                                '_csrf' => \yii::$app->request->csrfToken,
                            ],					
                            'initialPreview'=>isset($contents['initialPreview']['floorplan']) ? $contents['initialPreview']['floorplan'] : [],							
                            'initialPreviewConfig' => isset($contents['initialPreviewConfig']['floorplan']) ? $contents['initialPreviewConfig']['floorplan'] : [],						
                            'initialPreviewAsData'=>true,
                            'initialPreviewShowDelete'=> true,
							'overwriteInitial'=>true,	
							'showAjaxErrorDetails'=>false,	
							'removeFromPreviewOnError'=>true																						                            																						
                        ],									
                    ])->label('Floor Plan');
                     echo "<div id='floor_image_error' style='width: 40%;
    margin: 0 auto;     margin-top: 2%;'></div>";	
                    echo "</div>";		
                ?>
                
            </div>
        </div>
        
        <div id="others" class="tab-pane in">
        <div class="row other_image_row_cont" style="margin:0; margin-top: 5%;">
            <?php						
                echo $form->field($model, 'images',[
                        'template' => '<div class="row" style="margin:0;"><div class="col-5 col-md-5">{input}</div></div>',
                    ])->widget(FileInput::classname(), [					
                    'options' => ['accept' => 'image/*','multiple' => true, 'class' => 'facility_upload_btn', 'data-src' => 'other_image_row_cont', 'data-error' => 'other_image_error'],
                    'pluginOptions' => [
                        'maxFileCount' => '',
                        'validateInitialCount'=>true,
                    	'maxFileSize'=>10000,
                        'allowedFileExtensions' => ['jpg', 'jpeg', 'gif', 'png'],
                        'showCaption' => false,
                        'showRemove' => false,
                        'showUpload' => true,
                        'browseClass' => 'btn btn-default btn-block btn-sm',
                        'browseIcon' => '',
                        'browseLabel' =>  'or <span>Browse File</span>',
                        'uploadClass' => 'btn btn-default btn-block btn-sm',
                        'uploadUrl' => Url::to(['dashboard/upload_unit_pics/'.$model->id]),
                        'deleteUrl' => Url::to(['dashboard/delete_unit_pic/'.$model->id]),
                        'uploadExtraData' => [
                            'tag' => 'others',
                        ],	
                        'deleteExtraData' => [
                            '_csrf' => \yii::$app->request->csrfToken,
                        ],							
                        'initialPreview'=>isset($contents['initialPreview']['others']) ? $contents['initialPreview']['others'] : [],							
                        'initialPreviewConfig' => isset($contents['initialPreviewConfig']['others']) ? $contents['initialPreviewConfig']['others'] : [],						
                        'initialPreviewAsData'=>true,
                        'initialPreviewShowDelete'=> true,
						'overwriteInitial'=>true,	
						'showAjaxErrorDetails'=>false,	
						'removeFromPreviewOnError'=>true																						                            																						
                    ],									
                ])->label('Other Pictures');
                echo "<div id='other_image_error' style='width: 40%;
    margin: 0 auto;     margin-top: 2%;'></div>";
                echo "</div>";
            ?>		
            </div>	
        </div>
    </div>
     <?php 
    $this->registerJs("	
        jQuery(document).ready(function ()
        {
          $.facilityunit.init.addunits({step: 2});
        })");
?>
