### ISSUE TITLE
Remove Button

### ISSUE THREAD

**Issue by Greenbald** [kartik-v/bootstrap-fileinput#599]
There is an event that is triggered when the remove button is clicked - the button that appears right after you choose an image in your file system - ? The $('file-0').change(...) is not triggered by the remove button. For me would make sense that the remove button triggers it, once that it change the input file state.

There is another way to get the remove button click event?

**Comment by kartik-v** [comment]
File input does not behave like other HTML inputs and its value cannot be manipulated via javascript nor have a change triggered via javascript.

You may need to read the plugin docs for understanding other events. For example the [fileclear event](http://plugins.krajee.com/file-input#event-fileclear) can be used for your use case.
