### ISSUE TITLE
NuGet Version Update

### ISSUE THREAD

**Issue by groblerf** [kartik-v/bootstrap-fileinput#600]
Hallo Kartik,

**Thanks for this great library that you created.**

I see that the last update to NuGet.org was in April 2015 for version 4.1.8.

Would it be possible for you to upload the latest package version 4.3.1 to the NuGet.org Gallery? Or if you do not have time I would be happy to help if you could invite me to be a co-owner on NuGet so that I can upload a newer version.

**Thanks a lot in advance!**

Kind Regards,
Francois Grobler

**Comment by kartik-v** [comment]
I personally did not maintain the first package sync to nuget... but you can let know what is to be done for doing this.

**Comment by groblerf** [comment]
Thanks Kartik.
The person that created the library in the NuGet Gallery has an API Key for the package. No uploads can be done to add versions with the same package name without the API key.
We would need to find this person and request that they invite you to be a co-owner of the package, which will link your user profile to the package.
When that is done you can upload new versions after running your nugget\build.bat fiel to create the package.

**Comment by groblerf** [comment]
I see the package was first created by: ert78gb.

**Comment by groblerf** [comment]
Hallo Kartik,
Do you have a NuGet Profile?
If not, please create a profile and post the username here.
I have sent a message to ert78gb to invite you to be a co-owner. He will need your NuGet Profile Username.
Thanks.

**Comment by kartik-v** [comment]
I just created a nuget profile with `kartikv` as the username (same as github)

**Comment by groblerf** [comment]
Thanks, I have requested him to invite you.

You can also send messages on the NuGet web site by searching for the package: bootstrap-fileinput and clicking on the "Contact Owners" link on the left. See: https://www.nuget.org/packages/bootstrap-fileinput/ for the package.

**Comment by kartik-v** [comment]
This is resolved now.

**Comment by GRMagic** [comment]
Hello Kartik, good library!
Can you update the nuget package again?
