### ISSUE TITLE
upload files with file input using c#

### ISSUE THREAD

**Issue by haithamfouad2016** [kartik-v/bootstrap-fileinput#603]
Hello Krajee

I am just start using input file and I need to know how to receive the chosen files to my server path.
I am using c# and asp.net. , I am able to view the component in the aspx but i don't know how to fetch the chosen file and store it on my server.

please if there is an example for that.

thanks
haitham

**Comment by KnightHJ** [comment]
Hey! haitham.
I use C# and meet this problem too. 
I don't know whether you have figured out how to solve this issue.
If you have, can you give me some advice?

Thanks .
Knight.

**Comment by Mattdjuret** [comment]
I used a "ashx"-file on the serverside. Hope it helps.
[http://codepedia.info/2015/06/upload-image-using-jquery-ajax-asp-net-c-sharp/](url)

**Comment by kartik-v** [comment]
Hope this is answered. Would request programming queries and coding help be posted on the [webtips Q & A forum](http://webtips.krajee.com/questions) OR use the [discussions and comments section in the plugin site by navigating to the relevant section](http://plugins.krajee.com/file-input#comments). 

Pls use this repo for posting bugs and enhancement requests
