### ISSUE TITLE
feature request: download button

### ISSUE THREAD

**Issue by akorinek** [kartik-v/bootstrap-fileinput#606]
I need to give users the ability to download files that are on the server. So I'm looking for a button similar to delete that can download the file from the server. I didn't see any option for that in the docs.

**Comment by kartik-v** [comment]
It already exists. You can set [otherActionButtons](http://plugins.krajee.com/file-input#option-otheractionbuttons) as a HTML markup to display a link button that will be rendered in the thumbnail. Within a markup you can embed `{dataKey}` that will use the `key` set within `initialPreviewConfig`.
