### ISSUE TITLE
Access Denied with IE 11

### ISSUE THREAD

**Issue by gpit-vishal** [kartik-v/bootstrap-fileinput#609]
When file is selected with browse , it pop ups "Access denied".

![ie11](https://cloud.githubusercontent.com/assets/17849674/14421837/65215fa0-fff1-11e5-81ea-4edff72984ce.JPG)

**Comment by Focushift** [comment]
You see this error because Adobe Reader plugin cannot load. Just disable pdf preview and forget about it.

**Comment by gpit-vishal** [comment]
Thank You !!! :+1:

**Comment by omarpiani** [comment]
... this is not a solution.. it's a surrender... Using PDF Architect https://www.pdfforge.org/pdfarchitect/personal something is shown.. but bad.
