### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by mishabroflovski** [kartik-v/bootstrap-fileinput#613]
Hi,
I would like to add custom actions for input items. Like delete in attached screen.
![2](https://cloud.githubusercontent.com/assets/15226014/14615568/f7c32cf4-05ae-11e6-9efc-1e456200baec.PNG)
How can i achieve this?
Thank you,

**Comment by kartik-v** [comment]
Read [plugin documentation](http://plugins.krajee.com/file-input). You need to set [otherActionButtons property](http://plugins.krajee.com/file-input#option-otheractionbuttons) to add your own custom action buttons in each thumbnail. You can also modify the default plugin generated action buttons via [fileActionSettings property](http://plugins.krajee.com/file-input#option-fileactionsettings).
