### ISSUE TITLE
Disabling submit button

### ISSUE THREAD

**Issue by honzaseda** [kartik-v/bootstrap-fileinput#617]
Hi, love your work, just have one question.

I am not using the plugin upload button, i am using my own form submit button. Now, when i want to disable that submit button on error, i am using the 'fileuploaderror' event handler and the button is disabling correctly. But how do i enable the button back when the error disappears (user removes the invalid file)?

**Comment by kartik-v** [comment]
You need to read docs and learn and use the other [available plugin events](http://plugins.krajee.com/file-input#events). For example, event for clearing the file is `fileclear` and resetting the entire input will be`filereset`
