### ISSUE TITLE
Generate initial previews with built-in methods

### ISSUE THREAD

**Issue by taylankasap** [kartik-v/bootstrap-fileinput#620]
**Feature suggestion**

Instead of writing this

```
initialPreview:` [
    '<img src='/images/desert.jpg' class='file-preview-image' alt='Desert' title='Desert'>',
],
```

we should be able to write this

```
initialPreview:` [
    '/images/desert.jpg',
],
```

so the plugin can generate preview templates based on the file type.

What do you think? Or is there already a way to do this?

**Comment by kartik-v** [comment]
The reason is you cannot control as a developer the initial preview easily. Its been kept simple and left to the developer to render the HTML markup for initial preview - so that all control of displaying the preview lies with the developer. What you mentioned above is only images -- if you take other content - it will be different (and the additional JS coding to do that may not be that trivial).

**Comment by taylankasap** [comment]
I'm just thinking DRY. It kinda bugs me to generate same template when there is already a HTML coded in the plugin itself.

What about something like this:

```
// Save the instance because previewTemplates option might be customized for each fileinput
var $finput = $('.js-fileinput').fileinput();

$finput.generatePreviewTemplate({
    file: '/images/desert.jpg',
    type: 'image',

    // Rest is from initialPreviewConfig
    caption: 'desert.jpg', 
    width: '120px', 
    url: 'http://localhost/avatar/delete',
    key: 100, 
    extra: {id: 100}
});
```

So it can generate the HTML, like it already does when there is an upload.

**Comment by kartik-v** [comment]
As I said, you only considered `image` as a type above...  try to generalize it a bit... 

For example, you may want to preview a text file, then passing the link to the text file may not help (you may not want to expose content directly as a link for security reasons).... then you would need to use your server code to return the raw HTML embeded.

Similarly for a video or other the markup on how you want to display can be different...

**Comment by kartik-v** [comment]
However I am open to ideas for improvement? I think if it can be generalized for all use cases and the developer has a control to do what he/she wants... it may be best.

**Comment by kartik-v** [comment]
As I said, you only considered `image` as a type above...  try to generalize it a bit... 

For example, you may want to preview a text file, then passing the link to the text file may not help. The client cannot read from a server text file as easily as during the first scenario of upload from client, unless the server renders or passes the content to the client.

Similarly for a video or other the markup on how you want to display can be different... 

However I am open to ideas for improvement. I think if it can be generalized for all use cases and the developer has a control to do what he/she wants... it may be the best option.

**Comment by taylankasap** [comment]
I don't get what you mean. If the developer is trying to display preview of a file in the server, then the server must already serve the content of the file. I'm just writing 'image' as example, I don't see why other types won't work.

Also if the developer wants to display different markup than the previewTemplate then they can still use the initialPreview option. Am I wrong?

**Comment by kartik-v** [comment]
This will need a bit of code rewrite. I will update with an enhancement.

**Comment by kartik-v** [comment]
This will be covered in enhancements in #634, #635, and #636 with various new features.
