### ISSUE TITLE
Files, that was added on server side disappear when new file loaded

### ISSUE THREAD

**Issue by ktsv** [kartik-v/bootstrap-fileinput#621]
Hi, I have an issue with this widget - once I uploaded files and reloaded widget, my server side code generates initialPreview and initialPreviewConfig arrays, loads it into widget and previously loaded files are displaying correctly, BUT, once I add new file into it, all files, loaded on server side disappear. Can you, please, check this?

SY, Kirill.

**Comment by kartik-v** [comment]
Read [plugin documentation](http://plugins.krajee.com/file-input). You need to set [overwriteInitial property](http://plugins.krajee.com/file-input#option-overwriteinitial) to `false` to not overwrite the initial server generated preview.
