### ISSUE TITLE
SyntaxError: Unexpected token <.

### ISSUE THREAD

**Issue by mgk89** [kartik-v/bootstrap-fileinput#622]
When I try it on localhost I always get the message:

SyntaxError: Unexpected token <.

and the files are not uploaded although the local folder exists.

any ideas that this could mean?

thanks!

**Comment by Focushift** [comment]
I receive this error when js cannot parse server response.

**Comment by BenTech2** [comment]
i also have this issue, does anyone know how to fix this.

**Comment by Focushift** [comment]
check server response with Postman or other utils. Maybe server response formatted in xml instead json.

**Comment by kartik-v** [comment]
You need to send/receive right JSON format from server - else you will face the parse errors.

Read this [query answered](http://webtips.krajee.com/question/json-syntax-error-bootstrap-fileinput/)
