### ISSUE TITLE
Add more images without override

### ISSUE THREAD

**Issue by kamov** [kartik-v/bootstrap-fileinput#623]
Hi,
I would like to allow to add more images without override already existing images.

Plus add remove single image.

Thanks

**Comment by miyasita1958** [comment]
Did you try with `multiple` option ?

**Comment by kamov** [comment]
Hi, thanks for your reply.

Yes I have multiple and add multiple file work fine.

What I am trying to do is not to override already added file, but to append more when click again on file input.

**Comment by kartik-v** [comment]
@kamov you may want to read the [plugin documentation](http://plugins.krajee.com/file-input) and the [plugin demos](http://plugins.krajee.com/file-input/demo) where the use cases are covered.

Basically your above use case will only work when using the ajax mode with uploadUrl and not with form submission mode. Go through the doc sections to understand.

**Comment by kamov** [comment]
Hi, thanks for your reply. I was worry that only with ajax upload work this. But why? Why use can't remove selected file before upload? I don't mean file already uploaded but just file selected. The same to append more to selected files, for example for another folder?

**Comment by castilloedwin** [comment]
Estoy presentando el mismo inconveniente. Quiero subir múltiples imágenes pero si una vez seleccionadas quiero agregar otras el input sobreescribe lo que ya estaba. Si alguien lo logra solucionar no duden en avisarme. Un abrazo.

**Comment by allofapiece** [comment]
I have the same problem. I want to be able to sort, delete and add new files without using ajax. That would be logical.

**Comment by castilloedwin** [comment]
Well, after a long time I recall I made a little video explaining this. Here the link. I hope be able help you. https://youtu.be/5ra_EjQMxcg

**Comment by castilloedwin** [comment]
Well, after a long time I recall I made a little video explaining this. Here the link. I hope be able help you. https://youtu.be/5ra_EjQMxcg

Repository: https://github.com/castilloedwin/upload-images-easily
