### ISSUE TITLE
how to set height if "allowedPreviewTypes: false"

### ISSUE THREAD

**Issue by mgk89** [kartik-v/bootstrap-fileinput#628]
How can I set the height of the box if the PreviewTypes is set to false and the glyphicon box is shown instead of the image preview box? It is always set to height and width of 160px, no matter what I change.

Thank you 

![image](https://cloud.githubusercontent.com/assets/11804601/15108335/b237d7c0-15d5-11e6-85cd-3fd3ab2a3686.png)

**Comment by kartik-v** [comment]
You may want to check documentation for various options. You can control preview thumbnail heights through [previewSettings](http://plugins.krajee.com/file-input#option-previewsettings) for various file types.
