### ISSUE TITLE
Adding an option to fileinput dynamically

### ISSUE THREAD

**Issue by msedatgungor** [kartik-v/bootstrap-fileinput#629]
Hello! First and foremost, great job with the plugin!

My question is about language actually and my case is like this: I initialize fileinput without the language property, then server returns me the language option of user and if it is different than English, I want to add that corresponded language as option. I import language file dynamically and I can see that it is added to fileinputLocales but I couldn't dynamically add the corresponding "language" option to fileinput object. I tried to extend the defaults as following but it did not work:

```
$.extend($.fn.fileinput.defaults, {
    language: 'tr'
});
```

I'm not sure if this is doable, but if it is, how can I add a new option to fileinput initialization object?

Thanks in advance...

**Comment by kartik-v** [comment]
You just need to set the `language` property of the plugin directly when initializing the plugin OR when refreshing the language via any server validation... 

```js
$("#file-input-id").fileinput({
   language: '<your-lang-code-from-server>'
});
```
