### ISSUE TITLE
Cant read errors?

### ISSUE THREAD

**Issue by AlexioVay** [kartik-v/bootstrap-fileinput#630]
I'm trying to upload an image and it just says "filename.png: [object Object]". How can I read the error?

Best Regards, Alex

**Comment by kartik-v** [comment]
Debug your code both on client and the server code and JSON responses (input and output).

Understand the formats in which you must send and receive data as mentioned in [ajax uploads section of the documentation](http://plugins.krajee.com/file-input#ajax-uploads).
