### ISSUE TITLE
'self.id' is incorrect when using AngularJS and multiple fileinputs

### ISSUE THREAD

**Issue by raydawg2000** [kartik-v/bootstrap-fileinput#631]
`<div ng-repeat="config in [1,2]">`
`    <input type="file" name="upload" id="file_appAttach_{{config}}" />`
`</div>`

Will generate the following when I view source
`<input type="file" name="upload" id="file_appAttach_1" />`
`<input type="file" name="upload" id="file_appAttach_2" />`

The issue is that in the code, 
`self.id = file_appAttach_{{config}}`

when it should be 
`self.id = file_appAttach_1` 
or
`self.id = file_appAttach_2`

For a single fileinput this has no consequence but for multiple it causes issues because `self.id` is the key for the previewCache.  What ends up happening is whenever a preview refresh happens for one of the elements it will basically copy the other element preview data on the UI.

1.  Upload into file_appAttach_1
2.  Preview is generated in file_appAttach_1 for file MyDoc
3.  Upload into file_appAttach_2
4.  Preview is genreated in file_appAttach_2 for MyDoc and MyOtherDoc
5.  file_appAttach_2 now has 2 file previews attached to it.

I have tried all sorts of things to try and manipulate the `self.id` in the constructor code as well as modify the previewCache code but can't seem to get it.  Any help would be appreciated.

![fileinput_error](https://cloud.githubusercontent.com/assets/14985776/15166446/adab613c-16d3-11e6-887c-485cab5f6d76.jpg)

**Comment by kartik-v** [comment]
You need to write code accordingly to ensure the plugin gets the angular parsed ID before init.

If it is not easy for you, then one alternative is to not set the ID attribute... The plugin will autogenerate one.

**Comment by raydawg2000** [comment]
Great got it thanks
