### ISSUE TITLE
Multiple Ajax Upload does not resend the file after an error

### ISSUE THREAD

**Issue by florianmuellerCH** [kartik-v/bootstrap-fileinput#637]
Firstly, I want to thank you for the really nice library, it looks awesome!

However, with my Ajax Uploading form, I'm not getting something done:

I'm Using Fileinput to submit a file (e.g. PDF) and two fields using uploadExtraData. I recieve the file nicely and do my validations on the serverside. However, if there is an error in the two text fields, I output simply {'error':'Blabla'}. This message gets displayed nicely and works. But when I correct the field value and re-upload the image, it is not sent again - only the uploadExtraData comes along. How can I achieve that in case of an obvious error, he recognizes that he has to re-send the file to the server?

Thanks very much for you help in advance!

Sincerely,
Florian

**Comment by kartik-v** [comment]
For any validation error message shown after upload, User has to reupload the file by selecting from client again.

**Comment by florianmuellerCH** [comment]
I wrote a small workaround with the help of StackOverflow. For details see [this answer](http://stackoverflow.com/a/37374692/496965)

**Comment by JCMais** [comment]
@kartik-v what is the motivation behind having to reupload the file? Is that a browser limitation or something?

It's not a good solution from a UX point. Since it's like having an invalid value in a form being reset to nothing after validation. It should retain their value.

**Comment by kartik-v** [comment]
> @kartik-v what is the motivation behind having to reupload the file? Is that a browser limitation or something?

The reasons could be many depending on the validation error... you would not want to be accepting specific files on the server (based on type, content, size etc.). These files are thus cleaned up - for upload to run completely. 

I am open to any enhancement on this.

**Comment by x-yuri** [comment]
Let us probably continue here. From what I can see, the people complaining about `input` being reset (including myself) are those who use it in single upload mode. When you have a form with other fields, you submit it, some fields don't pass validation, and you expect all the fields to retain their values.

For multiple upload mode I can't tell what course of action would be better. It probably makes sense to reset the field.

I think I'll change behavior only for ajax uploads without `multiple` attribute set on `input`. What do you say?

**Comment by x-yuri** [comment]
...Actually, the more I think about it the more I lean to this plugin not being good for my use case. This plugin is best suited for uploading files. And I need a form containing file input. Uploading a file is not the thing of the form. The form allows to create a record in database, which happens to have file column. I can probably bend it to do as I want. But isn't it like going against the flow? And if I need more than one file input? I would be probably better off using [bootstrap-filestyle][1] + [jquery-form][2]...

Anyway, the [PR][3] has been started. Waiting for feedback (from you all)...

[1]: http://markusslima.github.io/bootstrap-filestyle/
[2]: https://github.com/jquery-form/form
[3]: https://github.com/kartik-v/bootstrap-fileinput/pull/985

**Comment by kartik-v** [comment]
@x-yuri if you are using it in a plain form based input mode for single file upload just like a native file input... without all other features, bells & whistles, queing, previewing or need to manage all the other file upload features ... then you should be able to configure and set the plugin that way... that enhancement should not be much of an issue.

**Comment by kartik-v** [comment]
Note that this issue raised in the first place is for an ajax mode upload... which means you use it primarily as a file uploader to manage and run through various files.

Have you checked uploading files/photos to some other common utilities - e.g. facebook in a bulk mode? Does it allow retry of the uploads that have failed OR does the user need to select and reupload again?

**Comment by kartik-v** [comment]
Refer [my comment in the PR](https://github.com/kartik-v/bootstrap-fileinput/pull/985#issuecomment-304486059).

For using this plugin just like a native file input - you do not need any changes and the plugin should give what you want like any other native file input. You do not then set `uploadUrl` and just proceed to reading the data just like any other native file input and handling the form submission to return error. File input will not be reset unless the form is reset in that case.

**Comment by kartik-v** [comment]
@JCMais @x-yuri and others

Refer [my comment in the PR](https://github.com/kartik-v/bootstrap-fileinput/pull/985#issuecomment-304486059).

For using this plugin just like a native file input along with other fields in a form - you do not need any changes and the plugin should give what you want like any other native file input. You do not then set `uploadUrl` and just proceed to reading the data on your server via form submission just like any other native file input along with other inputs. You just then handle your form submission errors based on whatever method you have implemented at your end via javascript. File input in that case will not be reset unless the form is reset in that case.

**Comment by kartik-v** [comment]
This is solved for single file uploads via the PR # 985.
