### ISSUE TITLE
Glyphicon support dropped in bootstrap 4

### ISSUE THREAD

**Issue by NAThompson** [kartik-v/bootstrap-fileinput#638]
It appears that [bootstrap 4](http://v4-alpha.getbootstrap.com/migration/) will no longer ship with glyphicons, and hence the fileinput plugin is broken on top of it.

Will this plugin stay with glyphicons? Will pull requests onto a bootstrap 4 branch be accepted that replace the icons with font-awesome?

**Comment by kartik-v** [comment]
This plugin is currently built for bootstrap 3.x and not tested for any alpha releases of bootstrap. So till a stable release of future bootstrap versions, i do not see immediate development here. With regards glyphicons... Most of these markup are already configurable as properties in the plugin.
