### ISSUE TITLE
CLone issue

### ISSUE THREAD

**Issue by abhi143u11** [kartik-v/bootstrap-fileinput#645]
When i m cloing the input file its always replcaing the first images please let me with that

**Comment by kartik-v** [comment]
You need to ensure you have a unique way to identify your file input selector and cannot blindly clone it... (for example have different ID and initialize on them)

**Comment by abhi143u11** [comment]
hi i tried your way but still no luck can you please have a look on this [](http://jsfiddle.net/Abhi143u11/8cmgyfb7/)
