### ISSUE TITLE
Open "Choose File" click on drop zone

### ISSUE THREAD

**Issue by avesgit** [kartik-v/bootstrap-fileinput#650]
I want open "Choose File" dialog when user click on drop zone. Similar youtube upload form. Thanks

**Comment by kartik-v** [comment]
Refer #676 - this functionality will be enabled via that.

**Comment by kartik-v** [comment]
Refer new CLICK TO SELECT examples after enhancements:

- [Example for form based/non-ajax uploads](http://plugins.krajee.com/file-avatar-upload-demo#avatar-upload-2)
- [Example for ajax uploads](http://plugins.krajee.com/file-input-ajax-demo/12)
