### ISSUE TITLE
Progress Bar Animation Glitchy

### ISSUE THREAD

**Issue by Fyb3roptik** [kartik-v/bootstrap-fileinput#651]
Great plugin, I love it! One thing though that bugs me is the animation for the progress bar is glitchy. It is not a smooth animation.

**Comment by kartik-v** [comment]
The animation is stock bootstrap provided and controlled via default bootstrap CSS transitions. 

Could you clarify what you mean by _progress bar is glitchy_ and what is your expectation?

Have you tested it on the plugin demo pages e.g. [ajax demo 1](http://plugins.krajee.com/file-input-ajax-demo/1) and confirm if it is only on your environment you have some issues?
