### ISSUE TITLE
Sending multiple files with its title?

### ISSUE THREAD

**Issue by vtxmg** [kartik-v/bootstrap-fileinput#652]
I want to send multiple images with its title .. can we do this using existing feature or I need to customize myself?

**Comment by kartik-v** [comment]
Read and check the documentation and view the demos... you can set `multiple` property in the input for multiple upload.

You can read the multiple files on your server code just like how you would read data from a native HTML FILE input. It is available as a FILE object and you will get the name from within the FILE object.
