### ISSUE TITLE
can not ajust the position

### ISSUE THREAD

**Issue by wyzssw** [kartik-v/bootstrap-fileinput#658]
i want submit the uploaded image urls in array to the backend server,for example

i already have two pics in backend database

initialPreview: [

'http://mybackend.server/pic1.jpg',

'http://mybackend.server/pic2.jpg'

]

now i want add one pic names "pic3.jpg" and ajust the position in sequence with 
http://mybackend.server/pic2.jpg,http://mybackend.server/pic3.jpg,http://mybackend.server/pic1.jpg

how i can config krajee-fileupload to satisfy this situation

**Comment by kartik-v** [comment]
You need to set `initialPreview` accordingly to send the right sequence in the array format from the server.

**Comment by wyzssw** [comment]
thanks for your reply，
perhaps i  did not state clearly，

the pic3 is up to upload,after upload,
user want adjust the sequence ， and submit the whole form
so if kartik-fileinput supply adjust image sequence i will be happy
```html

 <form id="wholeForm" method="post" action="${ctx}/mis/item/item/doList.htm">
    <input name="someOtherValue" name="someOtherValue">
    <label class="control-label">Select File</label>
    <input id="input-44" name="input44[]" type="file" multiple class="file-loading">
    <div id="errorBlock" class="help-block"></div>
    <input description="i want this input store imag urls " name="myPics"  type="hidden" value="http://server.com/pic2,http://server.com/pic3,http://server.com/pic2" />
    <button type="submit" id="button1" class="btn btn-primary">submit the whole form</button>
 </form>
 <script>
$(document).on('ready', function() {
    $("#input-44").fileinput({
        uploadUrl: '/file-upload-batch/2',
        maxFilePreviewSize: 10240
    });
});
</script>
```

**Comment by kartik-v** [comment]
you can only rearrange initial preview... so you would need to design it accordingly and give this sorting feature to user after upload..

**Comment by kartik-v** [comment]
The user can rearrange initial preview...  [check the preview management demo](http://plugins.krajee.com/file-preview-management-demo)...  so you would need to design it accordingly and give this sorting feature to user after upload...
