### ISSUE TITLE
Two panel preview problem

### ISSUE THREAD

**Issue by zl341225** [kartik-v/bootstrap-fileinput#660]
I can only preview the first fileinput in the first panel when I put this fileinput in two panels.
`

		  <ul class="nav nav-tabs" role="tablist">
			<li role="presentation" class="active"><a href="#tab-input1" aria-controls="home" role="tab" data-toggle="tab">身份证</a></li>
			<li role="presentation"><a href="#tab-input2" aria-controls="profile" role="tab" data-toggle="tab">银行卡</a></li>
		  </ul>

		  
		  <div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="tab-input1">
                <input id="file-zh1" name="file-zh1[]" type="file" multiple data-show-caption="false" data-show-upload="false"
                        data-language="zh" data-allowed-file-extensions='["jpg", "png","gif"]' resizeImage="true" resizeQuality="0.4"
                        show-upload=false>
            </div>
			<div role="tabpanel" class="tab-pane" id="tab-input2">
				<input id="file-zh" name="file-zh[]" type="file" multiple data-show-caption="false" data-show-upload="false"
                        data-language="zh" data-allowed-file-extensions='["jpg", "png","gif"]' resizeImage="true" resizeQuality="0.4"
                        show-upload=false>

			</div>
          </div>`

**Comment by kartik-v** [comment]
Cannot reproduce your use case. Check if you have the correct latest code from the repo.

Multiple file inputs on same page do work well as can be seen in [advanced usage demo](http://plugins.krajee.com/file-advanced-usage-demo).
