### ISSUE TITLE
SyntaxError: Unexpected end of input.

### ISSUE THREAD

**Issue by CarlosJavier81** [kartik-v/bootstrap-fileinput#661]
Hello kartik-v. I have this msg when i try to upload an image on the server
SyntaxError: Unexpected end of input.

when im working on my laptop (xampp apache server) everything works ok. U can check it in this link
http://www.itravel2peru.com/en/imageinput.php that calls to upload.php

**Comment by kartik-v** [comment]
You need to debug your code - as it looks like an issue with upload code, the data sent/received, and configuration/accesses to your server.
