### ISSUE TITLE
multiple select one file can autoreplace (without uploadUrl)

### ISSUE THREAD

**Issue by zyz** [kartik-v/bootstrap-fileinput#663]
<label>Preview File Icon</label>
<input id="file-3" type="file" multiple>
Method 1:
<input id="file-3" type="file" multiple data-upload-url="#">
Method 2:
$('#file-3').fileinput({
            uploadUrl: '#'
});

Why  need "uploadUrl" does not automatically replaced?

**Comment by kartik-v** [comment]
Read documentation and [understand restrictions on usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes).
