### ISSUE TITLE
Popup file preview, can be used independently?

### ISSUE THREAD

**Issue by zyz** [kartik-v/bootstrap-fileinput#664]
Or have an independent plugin?
How to use?

**Comment by kartik-v** [comment]
Yes...  can write your own code for the same. You may want to read docs on controlling plugin settings

You can disable the default zoom functionality by setting `showZoom` to `false` within [fileActionSettings](http://plugins.krajee.com/file-input#option-fileactionsettings). You can add your own custom buttons using [otherActionButtons](http://plugins.krajee.com/file-input#option-otheractionbuttons).
