### ISSUE TITLE
multiple without uploadUrl many times click Browse select one file replace not add preview

### ISSUE THREAD

**Issue by zyz** [kartik-v/bootstrap-fileinput#665]

**Comment by kartik-v** [comment]
Not clear with the issue... request to raise your query correctly and give the steps to reproduce any issue.

It seems you may need to read documentation before posting an issue. 

Using with or without uploadUrl has some pre-requisites for you to understand.

Read the [usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes) and the other sections of the docs in general to understand usage.
