### ISSUE TITLE
Two issues with Chinese language(zh)

### ISSUE THREAD

**Issue by Philo217** [kartik-v/bootstrap-fileinput#667]
1. After uploading a text contains Chinese characters, the preview contains many unreadable symbols.
2. when I select two files, the input says '2 多个文件选中', it should be '2个文件被选中'. Maybe I should have a pull request for this later.

**Comment by kartik-v** [comment]
Please submit a PR.

**Comment by kartik-v** [comment]
Closing this - will await a PR for your Chinese translations (not sure on point no. 1)..
