### ISSUE TITLE
Alert on file selected

### ISSUE THREAD

**Issue by Aifz** [kartik-v/bootstrap-fileinput#668]
Hi man,

First of all, gratz for your amazing job on this plugin that is so usefull and elegant.
I'm using the following initialization : 
$("input:file").fileinput({ dropZoneEnabled: false, showRemove: false, showUpload: false, showCancel: false, language: 'fr' });

When I select files using the browse button, once I click "Open" from the browse window it does show two alert messages for each file selected.
I wonder how I can have them removed ?

Thanks.

**Comment by kartik-v** [comment]
Are you running the latest code from this repo or its a customized code.

It seems your code specific issue. You need to check where you have placed the alerts in your code?

**Comment by Aifz** [comment]
I'm not running any specific code, I downloaded the latest zip from github and initialized the fileinput as I said, nothing more.
When I have no uploadUrl or showUpload to false, I have that alerts on each files posted.
Still no idea ?

**Comment by kartik-v** [comment]
Please share a JSfiddle to reproduce and check your use case.

**Comment by Aifz** [comment]
Building the JSfiddle showed me you were right, it is working properly, I searched my code and found some obsolete debug code that generates alert on fileselect /:. My bad, thanks for you help !
