### ISSUE TITLE
How can I put base64 images and keep delete button?

### ISSUE THREAD

**Issue by talespadua** [kartik-v/bootstrap-fileinput#669]
I am using the plugin on my project, but I am not using filesystem, I am using base64 images. I have managed to preview the images passing an image tag to the initialPreview: 

```
$("#input-br").fileinput({
    initialPreview: [
        "<img style=\"width:auto;height:160px;\" class=\"file-preview-image\" id=\"thumbnail_profile\" src=\"data:image/png;base64,"+bin_data+"\"/>"
    ],
    initialPreviewAsData: true,
    deleteUrl: "/api/delete_pic",
    overwriteInitial: false,
    maxFileSize: 1000
});
```

However, this method does not show the delete button and dont accept the initiaPreviewlConfig.
Is there a way to make this work with base64 images without the need to put all the html in the initialPreview?

**Comment by kartik-v** [comment]
- You must set `initialPreviewData` as false when setting raw markup.
- You must set `initialPreviewData` as `true` if you wish to pass data.
- If you just wish to pass the data... then 
    - you must also set `initialPreview` to be an array of image links OR 
    - you must also set `initialPreview` to be an array of data url which can be read by `img src` attribute

Refer [demo example](http://plugins.krajee.com/file-preview-management-demo#preview-data)

**Comment by kartik-v** [comment]
- You must set `initialPreviewAsData` as `false` when setting raw markup.
- You must set `initialPreviewAsData` as `true` if you wish to pass data.
- If you just wish to pass the data (i.e.  `initialPreviewAsData` as `true`)... then 
    - you can set `initialPreview` to be an array of image links OR 
    - you can set `initialPreview` to be an array of `base64 data url data` which can be read by `img src` attribute

Refer [demo example](http://plugins.krajee.com/file-preview-management-demo#preview-data)
