### ISSUE TITLE
Upload button is not removed in Bootstrap File Input

### ISSUE THREAD

**Issue by tc2070** [kartik-v/bootstrap-fileinput#670]
I have tried to set 'showUpload' to false in fileinput.js, the upload button is still showing. Another method i have tried is: 

$('#input-id').fileinput({ 
      'showUpload': false 
});

its not working too. The upload button is still there. I would like to hide this button because i already have a "save" button at bottom of a form.

**Comment by kartik-v** [comment]
Read the note in the [usage section](http://plugins.krajee.com/file-input#usage) of the documentation
