### ISSUE TITLE
I want to upload my Files to another domain.

### ISSUE THREAD

**Issue by WeiChienHsing** [kartik-v/bootstrap-fileinput#671]
When I tried to upload my file to another domain,I get 403 response.
How can I upload my file to another domain?

**Comment by kartik-v** [comment]
This should be handled your server code environment and client code configuration. You need to read about cross domain upload requirements in general. 

Typically you should set your server headers (called via upload URL) to allow cross domain/origin requests. You may also need to configure [the ajaxSettings property of the plugin](http://plugins.krajee.com/file-input#option-ajaxsettings) to allow cross domain requests :

```js
ajaxSettings: {
    dataType: 'jsonp',
    crossDomain: true
}
```

**Comment by WeiChienHsing** [comment]
I have set my server headers.
And I tested my upload api with a normal ajax request like this.it worked.
`	$.ajax({
   	  type: "POST",
   	  url:"localhost:8081/ndasec/product/info/pass/image/upload.do",
   	  crossDomain:true,
   	  success:function(result){
   		  
   		  console.log(result);
   	  }
   	});`

but not with the plugins
`           language: "zh",
   	    uploadUrl: "localhost:8081/ndasec/product/info/pass/image/upload.do?test=121",
   	    allowedFileExtensions: ["jpg", "png", "gif"],
	   	ajaxSettings: {
	   		dataType:'jsonp',
	   	    crossDomain: true
   		}`

I don't know where it went wrong.

**Comment by zquancai** [comment]
if you want to upload file to another domain, you should configure [ajaxSettings](http://plugins.krajee.com/file-input#option-ajaxsettings) like this:
```js
ajaxSettings: {
  xhrFields: {
    withCredentials: true
  }
}
```
don't forget to configure your server, just like this:
```
header('Access-Control-Allow-Origin:*');
// or and other
header('Access-Control-Allow-Methods:POST'); 
```
