### ISSUE TITLE
zoom modal

### ISSUE THREAD

**Issue by HKhedr** [kartik-v/bootstrap-fileinput#672]
My file input show in modal when I upload file I get zoom icon on click it's open new modal to show file..
when I close the zoom modal all modal is close "container modal".. 
How can I handle that !!!?

Regards.

**Comment by kartik-v** [comment]
refer #662

**Comment by HKhedr** [comment]
thank you. I wrote that code
`        $("input:file").fileinput({
            showRemove: false,
            showUpload: false,
            showCaption: false,
            showZoom: false
        });
`
but zoom icon still appear.. How can I hide zoom icon at all..

Regards.

**Comment by kartik-v** [comment]
There is no showZoom property at plugin level. Read the docs in detail. Individual thumbnail buttons are controlled via [fileActionSettings] property(http://plugins.krajee.com/file-input#option-fileactionsettings) within which you can set `showZoom` property.

**Comment by kartik-v** [comment]
[Read the docs](http://plugins.krajee.com/file-input) in detail. 

There is no `showZoom` property at plugin level. Individual thumbnail buttons are controlled via [fileActionSettings property](http://plugins.krajee.com/file-input#option-fileactionsettings) within which you can set `showZoom` property.
