### ISSUE TITLE
Upload audio file and how to get blob data?

### ISSUE THREAD

**Issue by dungphanxuan** [kartik-v/bootstrap-fileinput#673]
Hello, somebody can help me, how to get blob data for file upload.
blob example: blob:http%3A//demos.krajee.com/c6c54b2f-7e7f-4571-bcb4-7092e33c3272
Thank!

**Comment by kartik-v** [comment]
Did you read the docs properly and understand [the plugin usage modes](http://plugins.krajee.com/file-input#usage-modes)?

If you are using form based submission, the HTML FILE INPUT submitted to the server will contain the file blob.

If you are using ajax based submission, the plugin will automatically send the file blob via POST in the variable identified by the FILE INPUT name attribute.

**Comment by dungphanxuan** [comment]
That my mind is what is code/script for generate/ or created blob data. 
Thank for you help!

**Comment by dungphanxuan** [comment]
i found solution: 
https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications#Example_Using_object_URLs_to_display_images
