### ISSUE TITLE
How to send and access the data-fileindex?

### ISSUE THREAD

**Issue by mgk89** [kartik-v/bootstrap-fileinput#675]
Hi,

first of all: thanks for your great plugin!

I know it already has been discussed a lot of times, but I just can't figure out how it works:

how can I send the data-fileindex in async mode to my upload.php so that I know what is the right order of the uploaded pics? how can the data-fileindex number be accessed in the upload.php?

thank you for your answer (I really tried to figure out, but I fear my JS knowledge is not good enough ...)!

**Comment by kartik-v** [comment]
You may want to [read documentation about the plugin events](http://plugins.krajee.com/file-input#events).

You can use the [fileuploaded event](http://plugins.krajee.com/file-input#event-fileuploaded) for your use case (check the `index` parameter and `previewId` parameter available).

**Comment by mgk89** [comment]
thank you for your answer.

on('filepreupload', function(event, data, previewId) {
		var form = data.form, files = data.files, extra = data.extra,
                response = data.response, reader = data.reader;
		prevId = previewId;
		console.log('File upload triggered');
		console.log('ID lautet: '+previewId);

make me have the previewId in the console log, but please tell me how I can access to it in the upload.php just like I can access uploadExtraData variables.

how do I have to define that I can use $_POST['previewId'] in the upload.php?
thank you very much and sorry for keep asking!

**Comment by kartik-v** [comment]
Many such use cases like yours are possible by handling via events and writing your javascript. Its entirely upto the developer to code and program for their use case.

For example you can in the `filepreupload` event store the previewId in a hidden Input and return that via uploadExtraData. Note that you can [set uploadExtraData as a callback as well](http://plugins.krajee.com/file-input#option-uploadextradata) - so that it will dynamically send the data.

**Comment by mgk89** [comment]
hi,
thank you for your answer. I hope I am getting closer to understand it.

i have:

```
 $("#images").fileinput({
		uploadUrl: "upload.php",
		allowedFileExtensions: ["jpg"],
		maxImageHeight: 900,
		maxFileCount: 300,
		resizeImage: true,
		uploadExtraData: {prevId: prev()},
		})

 function prev(){
	       return 'here has to be the id';}
```

is that principle correct?

how can that be combined with the suggested function so that I can access on $_POST['prevId']?

```
function (previewId, index) {
    var obj = {};
    $('.your-form-class').find('input').each(function() {
        var id = $(this).attr('id'), val = $(this).val();
        obj[id] = val;
    });
    return obj;
}

```

Thank you so much for your help and your patience!

**Comment by mgk89** [comment]
hi, 
unfortunately I can't make it work. Maybe you would be so nice as to help me with passing the PreviewID to the form?

thanks in advance!!!

**Comment by praveenakah** [comment]
wwww
