### ISSUE TITLE
HttpRequest.files uploads same file when uploading multiple files

### ISSUE THREAD

**Issue by digglek** [kartik-v/bootstrap-fileinput#678]
I am trying to use this to upload multiple files but when I try to process the files posted to the server the HttpRequest.files is just duplaicated file so if I select 4 different images the preview shows the correct images but the posted data is always the first selected file

**Comment by kartik-v** [comment]
This should be addressed as part of your HTML input markup and server code configuration.

For example for PHP the file input markup name must use array naming convention to be read as an array of files by the server - e.g. [related web tip for PHP](http://webtips.krajee.com/read-html5-multiple-file-input-php/).
