### ISSUE TITLE
Jquery validation on fileinput bootstrap plugin

### ISSUE THREAD

**Issue by prafulbagai** [kartik-v/bootstrap-fileinput#679]
Upon submitting the form, it still shows the error of saying `Atleast 1 field is required` when an image is already provided in the first input box as initial preview? If I browse a file separately, it wont show any error.

**HTML**

    <input id="input-upload-img1" type="file" class="file" data-preview-file-type="text" name="img1" accept='image/*,video/*'>
    <input id="input-upload-img2" type="file" class="file" data-preview-file-type="text" name="img2" accept='image/*,video/*'>

**Javascript**

    <script>
    	$('#input-upload-img1').fileinput({
    		initialPreview: [
    		    "<img src='img1' class='file-preview-image' alt='Desert'>",
    		]
    	});
    </script>

So, now I've an initial preview on one of my input field having id `input-upload-img1` and no preview on the other input field.

Now I apply jQuery validation of the input field

    img1: {
        require_from_group: [1, '.file'],
        accept: "image/*"
    },
    img2: {
        require_from_group: [1, '.file'],
        accept: "image/*"
    }

Why jQuery validation is showing error when initial preview field has already been provided.?

**Comment by kartik-v** [comment]
Initial preview is just a display ... It does not populate the file input. Quite a few folks are making this mistake. Note that HTML file inputs are read only and one cannot set a value to these via JavaScript or via markup. The plugin just gives an ability similar to feel like this but the developers need to handle these in the code.

**Comment by prafulbagai** [comment]
Hi Kartik,

Thanks for providing valuable input on the above issue. Since, I need to
handle the above issue in my code, what would be the best way of going
forward with this? How should I handle these things in JS code?

Regards

On Wed, Jun 8, 2016 at 6:31 AM, Kartik Visweswaran <notifications@github.com

**Comment by kartik-v** [comment]
You need to write the code in your third party jquery validation plugin to skip file input **required validation** when you have set an initial preview.

**Comment by prafulbagai** [comment]
Hi Kartik,

Thanks for replying. I was looking into the same, but was stuck upon
something. Since triggering validation programmatically depends on the
methods provided by the Fileinput plugin. *Is there a Fileinput method that
fires when the "initial preview is set"?*
