### ISSUE TITLE
Change filename and files order before upload

### ISSUE THREAD

**Issue by ryslana** [kartik-v/bootstrap-fileinput#681]
Hi, guys!
Awesome plugin. It saves me a lot of time for my case, but I have to be able to change upload order and filenames before upload it to server. 
Please advise how can I do this?

**Comment by kartik-v** [comment]
You need to do a bit of coding yourself to achieve your use cases.

A [demo example of having a text input to change the file names is mentioned here](http://plugins.krajee.com/file-input-ajax-demo/7). Use this to extend your case for reordering by capturing that order in another input as well.

**Comment by raphaelmichl** [comment]
@ryslana 
I am facing the same issue. It would be nice to be able to change the order of the files (the selected ones - not the initial files) beforehand.
Did you solve it somehow?
