### ISSUE TITLE
Image deletion

### ISSUE THREAD

**Issue by johnnyhello** [kartik-v/bootstrap-fileinput#682]
Hello,

So i want to upload images automatically. I did like this:

            }).on("filebatchselected", function(event, files) {
                    // trigger upload method immediately after files are selected
                $("#input-pl").fileinput("upload");

It works really nice.
But right now i want to have a possibility to delete this image as well without refreshing the site.
How to do it ?

I configured preview for images, and it works with deletion but only when i refresh the site.
it is because preview initialization. 

but i want to load and remove image without refreshing site automatically

**Comment by kartik-v** [comment]
Check [an example of how you can setup the initial preview immediately after upload](http://plugins.krajee.com/file-input-ajax-demo/4). This should show the delete button.
