### ISSUE TITLE
Blob src not found or "minImageWidth, minImageHeight" not working 

### ISSUE THREAD

**Issue by kashmirIvan** [kartik-v/bootstrap-fileinput#684]
If i use options like this: `previewTemplates: { image: '<div class="file-preview-frame" ><img src="{data}" title="{caption}" id="{previewId}" alt="{caption}" style="max-width:100%"></div>' }` not working "minImageWidth, minImageHeight". But if i use options like this: `previewTemplates: {image: '<div class="file-preview-frame" id="{previewId}"><img src="{data}" title="{caption}" alt="{caption}" style="max-width:100%"></div>' }`, or default, "minImageWidth, minImageHeight" working fine but image attribute "src" (blob) has link 404.
How do I get worked option "minImageWidth, minImageHeight" and a link to the image opens the image.
Sorry for my english.

**Comment by kartik-v** [comment]
You already have a zoom functionality in the latest release to open the preview image.
