### ISSUE TITLE
After custom 'previewTemplates', BF cannot Move/Rearrange/Sort

### ISSUE THREAD

**Issue by liuxue0905** [kartik-v/bootstrap-fileinput#686]
After custom 'previewTemplates',even copy code of previewTemplates from doc,
BF cannot Move/Rearrange/Sort By (Touch down and move) (Move/Rearrange button) Any More.

**Comment by liuxue0905** [comment]
$("#file-1").fileinput({
        uploadUrl: 'http:localhost:3000/file-upload-single/1',
        allowedFileExtensions : ['jpg', 'png','gif'],
        overwriteInitial: false,
        maxFileSize: 1000,
        maxFilesNum: 10,
        //allowedFileTypes: ['image', 'video', 'flash'],
       initialPreview: [
                        "http://lorempixel.com/800/460/people/1",
                        "http://lorempixel.com/800/460/people/2"
                        ],
       initialPreviewAsData: false, // identify if you are sending preview data only and not the raw markup
       initialPreviewFileType: 'image', // image is the default and can be overridden in config below
       initialPreviewConfig: [
                              {caption: "People-1.jpg", size: 576237, width: "120px", url: "/site/file-delete", key: 1},
                              {caption: "People-2.jpg", size: 932882, width: "120px", url: "/site/file-delete", key: 2},
                              ],
       previewTemplates: {
           generic: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}">\n' +
           '   {content}\n' +
           '   {footer}\n' +
           '</div>\n',
           image: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}">\n' +
           '   <div class="kv-file-content">' +
           '       <img src="{data}" class="kv-preview-data file-preview-image" title="{caption}" alt="{caption}" ' + STYLE_SETTING + '>\n' +
           '   </div>\n' +
           '   {footer}\n' +
           '</div>\n',
           text: '<div class="file-preview-frame{frameClass}" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}">\n' +
           '   <div class="kv-file-content">' +
           '       <textarea class="kv-preview-data file-preview-text" title="{caption}" readonly '
           + STYLE_SETTING + '>{data}</textarea>' +
           '   </div>\n' +
           '   {footer}\n' +
           '</div>',
           html: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}">\n' +
           '   <div class="kv-file-content">' +
           '       <div class="kv-preview-data file-preview-html" title="{caption}" ' + STYLE_SETTING + '>{data}</div>\n' +
           '   </div>\n' +
           '   {footer}\n' +
           '</div>',
           pdf: '<div class="file-preview-frame{frameClass}" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}">\n' +
           '   <div class="kv-file-content">' +
           '       <embed class="kv-preview-data" src="{data}" width="{width}" height="{height}" type="application/pdf">\n'+
           '   </div>\n' +
           '   {footer}\n' +
           '</div>',
           video: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}" title="{caption}" '
           + STYLE_SETTING + '>\n' +
           '   <div class="kv-file-content">' +
           '       <video class="kv-preview-data" width="{width}" height="{height}" controls>\n' +
           '           <source src="{data}" type="{type}">\n' + DEFAULT_PREVIEW + '\n' +
           '       </video>\n' +
           '   </div>\n' +
           '   {footer}\n' +
           '</div>\n',
           audio: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}" title="{caption}" '
           + STYLE_SETTING + '>\n' +
           '   <div class="kv-file-content">' +
           '        <audio class="kv-preview-data" controls>\n' +
           '            <source src="{data}" type="{type}">\n' + DEFAULT_PREVIEW + '\n' +
           '        </audio>\n' +
           '   </div>\n' +
           '   {footer}\n' +
           '</div>\n',
           flash: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}" title="{caption}" '
           + STYLE_SETTING + '>\n' +
           '   <div class="kv-file-content">' +
           '       <object type="application/x-shockwave-flash" width="{width}" height="{height}" data="{data}">\n' +
           OBJECT_PARAMS + '\n' + DEFAULT_PREVIEW + '\n' +
           '       </object>\n' +
           '   </div>\n' +
           '   {footer}\n' +
           '</div>\n',
           object: '<div class="file-preview-frame" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}" title="{caption}" ' + STYLE_SETTING + '>\n' +
           '   <div class="kv-file-content">' +
           '       <object class="kv-preview-data" data="{data}" type="{type}" width="{width}" height="{height}">\n' +
           '          <param name="movie" value="{caption}" />\n' + OBJECT_PARAMS + '\n' + DEFAULT_PREVIEW + '\n' +
           '       </object>\n' + 
           '   </div>\n' +
           '   {footer}\n' +
           '</div>',
           other: '<div class="file-preview-frame{frameClass}" id="{previewId}" data-fileindex="{fileindex}" data-template="{template}"' +
           ' title="{caption}" ' + STYLE_SETTING + '>\n' +
           '   <div class="kv-file-content">' +
           '       <div class="kv-preview-data file-preview-other-frame">\n' + DEFAULT_PREVIEW + '\n' +
           '       </div>\n' +
           '   </div>\n' +
           '   <div class="file-preview-other-footer">{footer}</div>\n' +
           '</div>'
       }           
	});

**Comment by kartik-v** [comment]
Not sure about this as cannot reproduce. You may need to ensure you have the latest code and update.
