### ISSUE TITLE
Displaying *.tif files

### ISSUE THREAD

**Issue by MrGorki** [kartik-v/bootstrap-fileinput#688]
Is it possible to show tif files for preview

**Comment by kartik-v** [comment]
Not natively supported by browsers (except safari) - so it needs additional plugins to convert and view.

**Comment by kartik-v** [comment]
Refer enhancement #1110. This now covers display of various file formats including TIFF files. But this is applicable ONLY for files displayed from a public server via `initialPreview`. 

To preview TIFF files on CLIENT before upload - you need an external TIFF JS plugin - OR alternatively you can code your app to upload this file to server immediately on selection and return `initialPreview` to show the display of the file from server.
