### ISSUE TITLE
During the record update scenarios video preview not working.

### ISSUE THREAD

**Issue by chaitenyay** [kartik-v/bootstrap-fileinput#689]
First of all Kartik, I would like to thank you for your such a wonderful plugin. Its working perfectly fine.
We are facing two issue, It would be great if you can give some hint on this.
1. Once video file uploaded, if we visit the page for record update, we notice that video preview not working whereas video file is uploaded properly.
2. How can we shuffle the image order. (Manage the order).
Thanks

**Comment by kartik-v** [comment]
Ensure you are on updated release of the plugin and read all docs and demos. Check [the preview management demo section](http://plugins.krajee.com/file-preview-management-demo) for examples of your use cases above.
