### ISSUE TITLE
initialPreviewFileType array of mulitple types

### ISSUE THREAD

**Issue by jonny-mipo** [kartik-v/bootstrap-fileinput#690]
Hi,

We wanted to display previews of our files with different preview types, ie if we have an array of files that include images and Excel/Word files, we want the images to show a thumbnail and the Excel/Word files to show a file extension logo. When we made initialPreviewFileType = 'image', the image thumbnails were displayed, but the Excel/Word files showed empty images. When we made initialPreviewFileType = 'object', we saw the Excel/Word extension logo, but the images also showed such a logo instead of a preview thumbnail. We changed your code a little to allow for an array of initialPreviewFileType - lines 139-151 of fileinput.js - as follows:

if (asData) {
                cat = data.previewAsData ? ifSet('type', config, **(isArray(data.previewFileType) ? data.previewFileType[i] : data.previewFileType) || 'generic')** : 'generic';
                cap = ifSet('caption', config);
                ftr = previewCache.footer(id, i, isDisabled, (config && config.size || null));
                ftype = ifSet('filetype', config, cat);
                out = data.parseTemplate(cat, content, cap, ftype, previewId, ftr, ind, null);
            } else {
                out = data.template
                    .replace(/\{previewId}/g, previewId).replace(/\{frameClass}/g, frameClass)
                    .replace(/\{fileindex}/g, ind).replace(/\{content}/g, data.content[i])
                    .replace(/\{template}/g, ifSet('type', config, **(isArray(data.previewFileType) ? data.previewFileType[i] : data.previewFileType)**))
                    .replace(/\{footer}/g, previewCache.footer(id, i, isDisabled, (config && config.size || null)));
            }

We were wondering if you could add such support, perhaps differently than we did it but along those lines.

Thank you!

**Comment by kartik-v** [comment]
The plugin already has the capability and it is simple to achieve your configuration. Check the [file preview icons demo in the plugin docs](http://plugins.krajee.com/file-preview-icons-demo). You need to control `allowedPreviewTypes` and `previewFileIconSettings` as shown to achieve above.
