### ISSUE TITLE
Upload file (ajax)- then delete without page reload (using preview images)

### ISSUE THREAD

**Issue by neal-gurtam1** [kartik-v/bootstrap-fileinput#691]
I upload file by ajax then i want to delete it (by ajax too- small button at file's preview) without page reloading. In what format i should give ajax answer after file uploading to do this (shoud i give the answer withfile's key and url and in what format )?

**Comment by kartik-v** [comment]
Read [this doc section and the note below](http://plugins.krajee.com/file-input#option-deleteextradata) on what the server expects from the ajax POST delete action.
