### ISSUE TITLE
Hide small "Update button" in image preview

### ISSUE THREAD

**Issue by neal-gurtam1** [kartik-v/bootstrap-fileinput#692]
How can i hide "Upload button" in image preview

![777](https://cloud.githubusercontent.com/assets/19798687/16273279/a72221fa-38a9-11e6-8c35-b56419d9caa7.jpg)

I use 
.kv-file-upload {display: none}
but may be i can do it by widget config?

**Comment by kartik-v** [comment]
Duplicate to #694. [Read this](https://github.com/kartik-v/bootstrap-fileinput/issues/694#issuecomment-229287795).
