### ISSUE TITLE
Add reference to file's downloading at file preview

### ISSUE THREAD

**Issue by neal-gurtam1** [kartik-v/bootstrap-fileinput#693]
How can i add reference to file download at file preview?

![777](https://cloud.githubusercontent.com/assets/19798687/16273557/c2944d72-38aa-11e6-9ed0-e8656f7156ab.jpg)

**Comment by kartik-v** [comment]
Duplicate to #694. [Read this](https://github.com/kartik-v/bootstrap-fileinput/issues/694#issuecomment-229287795).
