### ISSUE TITLE
How to use sort button at page preview and how hide any button from page preview?

### ISSUE THREAD

**Issue by neal-gurtam1** [kartik-v/bootstrap-fileinput#694]
How to use sort button at page preview and how hide any button from page preview (sort,  preview delete, upload)?

**Comment by kartik-v** [comment]
By reading [documentation](http://plugins.krajee.com/file-input) and understanding options to set this.
You can control the buttons in the preview thumbnails within [fileActionSettings](http://plugins.krajee.com/file-input#option-fileactionsettings) as mentioned in the docs.
