### ISSUE TITLE
View Details (File Preview) does not work(hangs) for the last rendered fileinput plugin in bootstrap tabs

### ISSUE THREAD

**Issue by biswadippaul** [kartik-v/bootstrap-fileinput#697]
When the ajax plugin is used with bootstrap tabs. The File Preview only works for the first rendered fileinput object. For a different tab the file view details does not work at all and freezes the page, the only way out is a refresh of the page. There are no errors or anything. I am attaching a html file which will exhibit the same problem. I used a csv file. U can see the problem coming in the tab marker "Red" and not coming in the tab marked "Orange".
[fileinput-test2.html.zip](https://github.com/kartik-v/bootstrap-fileinput/files/338677/fileinput-test2.html.zip)

**Comment by kartik-v** [comment]
This is more a coding issue that each developer needs to handle.

For example for your use case, you may need to code in such a way probably that the plugin is initialized and file input widget is rendered ONLY after the tab is clicked and the tab is shown.
