### ISSUE TITLE
Drag and Drop not supported on Microsoft Edge

### ISSUE THREAD

**Issue by nick-beers** [kartik-v/bootstrap-fileinput#698]
After reading the fileinput.js it seems there is a rule to avoid running the file upload for Microsoft Edge. This was originally an issue on the earlier iterations of Edge, but it appears that Edge does support Drag and Drop now and after removing the Edge logic I was able to use the drag and drop.

I was hoping you would look into not blocking Drag and Drop for Microsoft Edge if it is no longer an issue.

Thanks!

**Comment by kartik-v** [comment]
Sure will check and update

**Comment by kartik-v** [comment]
Fixed via a7c8bc0.
