### ISSUE TITLE
Special characters getting converted

### ISSUE THREAD

**Issue by friek108** [kartik-v/bootstrap-fileinput#699]
Some characters such as dashes - , brackets () and parenthesis ' get converted when you upload to the widget. They then get sent to the server like this and make for very ugly filenames. For example:

> My File - Made Here (12 Sep 2016).pdf

ends up being

> My File _ Made Here _ 12 Sep 2016_.pdf

You can test this on the demo page to see it happening as well.

**Comment by kartik-v** [comment]
[Read this](https://github.com/kartik-v/bootstrap-fileinput/issues/536#issuecomment-170991656).
