### ISSUE TITLE
BUG of ZOOM BUTTON

### ISSUE THREAD

**Issue by edwinhuish** [kartik-v/bootstrap-fileinput#703]
Hi Krajee, I think there is a BUG with ZOOM.

When I click the zoom button, sometimes the zoom layer did no show, but with background black, and can not do anything until refresh the web page.

How can I fix it?

**Comment by edwinhuish** [comment]
Here is my code setting:

```
       $("input.products-picture").fileinput({
            showClose: false,
            showCaption: false,
            showBrowse: false,
            defaultPreviewContent: '<img src="./Upload/Default/default_pic.jpg" alt="Product Picture" style="width:160px">',
            previewSettings : {
                image: {width: "auto", height: "auto"}
            },
            initialPreviewAsData: true,
            initialPreview: '{$product.pic_directory}'?'{$product.pic_directory}':false,
            layoutTemplates: {main2: '{preview}'},
            fileActionSettings: {
                showDrag: false,
                showRemove: false,
            },
            previewZoomSettings:{
                image: {width: "auto", height: "auto", 'max-width': "100%",'max-height': "100%"},
            }
        });

```

**Comment by kartik-v** [comment]
Cannot reproduce this. You need to check your code and ensure there are no JS errors on your page OR CSS issues that can hide the bootstrap modal that is used for preview zoom.

**Comment by edwinhuish** [comment]
I found the notice as blew:

jQuery-2.2.0.min.js:2 Uncaught RangeError: Maximum call stack size exceeded

**Comment by aditya-singh-tomar** [comment]
fileinput.js:3458 Uncaught RangeError: Maximum call stack size exceeded
    at FileInput._getThumbFileId (fileinput.js:3458)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)
    at FileInput._getThumbFileId (fileinput.js:3460)

i am getting this error, please help
