### ISSUE TITLE
How to overwrite your uopload method

### ISSUE THREAD

**Issue by wpf1994** [kartik-v/bootstrap-fileinput#707]
I need upload picture to Cloud image server,give me a suggest，thanks

**Comment by kartik-v** [comment]
This is more a coding effort from your end. You do not need to overwrite the upload method.

You can search for ajax uploads to cloud servers on the web and how you can write your ajax call.

[For example this is how you can upload to Amazon S3 using ajax](http://stackoverflow.com/questions/11240127/uploading-image-to-amazon-s3-with-html-javascript-jquery-with-ajax-request-n).

Now within the plugin:

- You can use [uploadExtraData](http://plugins.krajee.com/file-input#option-uploadextradata) to pass 
additional data with your ajax call.
- You can use [ajaxSettings](http://plugins.krajee.com/file-input#option-ajaxsettings) to override the ajax settings for your use case.
