### ISSUE TITLE
Validation specific file extensions IE

### ISSUE THREAD

**Issue by gonzadev** [kartik-v/bootstrap-fileinput#708]
the validation specific file extensions in **Internet Explorer** 11 not show the invalid message like other browsers when I select a invalid file.

**Comment by kartik-v** [comment]
No cannot reproduce what you are saying. Not sure you have the right code.

Check for an example of file type validation in [advanced usage example # 8 of the plugin docs](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-8).

**Comment by gonzadev** [comment]
kartik, I send my screenshot for your help, the problem is at IE 11.
![capture1](https://cloud.githubusercontent.com/assets/20358304/16749696/7b91d78a-47a2-11e6-893a-40f14c7d710b.JPG)

![capture2](https://cloud.githubusercontent.com/assets/20358304/16749730/da15f1ce-47a2-11e6-8eea-bae1200c0b59.JPG)
