### ISSUE TITLE
The file upload error when enabled clipping image features

### ISSUE THREAD

**Issue by ykbj** [kartik-v/bootstrap-fileinput#711]
The file upload error when enabled clipping image features.
Multiple file upload when enabled clipping image features, The two picture is the same. And one be cut off, another not be cut off.

**Comment by kartik-v** [comment]
Cannot understand the query? What do you mean by clipping image features? Is it related to some third party plugin or your code that clips/crops the image?

**Comment by ykbj** [comment]
Image Resize (Width) 
    resizePreference: 'width',
    maxImageWidth: 480,
    resizeImage: true

Multiple file upload error when enabled this "Image Resize" function.

**Comment by ykbj** [comment]
hi, i has recorded this issus. please download and view the gif file from ["http://pan.baidu.com/s/1hr5YpvA"](http://pan.baidu.com/s/1hr5YpvA)

thanks a lot~~

**Comment by edwinhuish** [comment]
@kartik-v  @ykbj 

I saw the gif, I think the problem is the server part, no the bootstrap file-input.

@ykbj 这个明显是你的服务端代码问题。

**Comment by ykbj** [comment]
@edwinhuish 但是如果我不用Image Resize的话，是没有问题的。一加上resizeImage: true就不行了，图片就会重复，如果上传三张的话也是有两张会重复，我后台接收到的内容就是这样的，好像跟我后台的处理没有关系吧。希望能帮我解决一下这个问题，非常感谢！

**Comment by edwinhuish** [comment]
@ykbj  请先看一下network是否重复提交。

如果不用Image Resize没有问题。一加上resizeImage: true就不行的话，这个需要作者解决了。

**Comment by ykbj** [comment]
@kartik-v hi, I discussed with edwinhuish, we think this is a issus. i hope you fix this issus, thanks a lot.

**Comment by ykbj** [comment]
@kartik-v @edwinhuish hi, i fix this bug for simple.
function _validateAllImages : line2466
ind = config.ind; -> inde = config.pid.split('-')[2];

please check this fix. thanks!

**Comment by ykbj** [comment]
@edwinhuish 这个地方的问题在于如果单次选择图片文件，多次选择，这个ind都是0，那么在_getResizedImage的方法里面self.filestack[ind] = blob; 这ind也是0，剪裁后图片就会覆盖filestack[0]这个图片对象，那么除了ind为0的图片被剪裁了，其他的都不会被剪裁，也会产生一张重复的图片了。

**Comment by kartik-v** [comment]
I am sorry, I cannot understand Chinese... please post in English.

Share a JS Fiddle explaining your issue - and provide a link to reopen this.

**Comment by ykbj** [comment]
The problem is that if the single select an image file, multiple choice, the IND is 0, then in the _getResizedImage method self.filestack[ind] = blob; the IND is 0. After cutting the picture will be covered filestack[0] this picture object, then in addition to ind 0 pictures was tailored, the other will not be cut, also will produce a duplicate pictures the.
