### ISSUE TITLE
show only one file in initialPreview after ajax upload

### ISSUE THREAD

**Issue by islamw** [kartik-v/bootstrap-fileinput#712]
I have input (not multiple). If I upload photo first time it's ok - shown one file. and than if I at once upload another file, its show old file and new file in the same time in initialPreview. But if I reload page - it's ok - old file disappears. I want that in initalPreview will show only one file after upload. is it possible?

I return json initial preview from server (php)

**Comment by kartik-v** [comment]
Yes please read documentation. There are [many options](http://plugins.krajee.com/file-input#options) you can configure in the plugin. For example, you can set [overwriteInitial](http://plugins.krajee.com/file-input#option-overwriteinitial) property of the plugin to `true`.

**Comment by islamw** [comment]
1. it's didn't help.
2. my json that server return is `[
            'initialPreview' => [$guidePhotoDir],
            'initialPreviewConfig' => [
                [
                    'caption' => $guide->photo,
                    'url' => '/' . App::getLocale() . '/' . roleRootUrl() . '/guidePhoto/delete',
                    'extra' => [
                        '_token' => csrf_token(),
                        'guide_id' => $data['guide_id']
                    ]
                ]
            ]
        ]`
3. js:
`var input = $("#field_photo_id");
        input.fileinput({
            language: "{{App::getLocale()}}",
            uploadUrl: "@url('{{roleRootUrl()}}/guidePhoto/add')",
            browseClass: "btn btn-success",
            browseLabel: "{{trans('services-director.pick-photo')}}",
            browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i>",
            allowedFileExtensions: ["jpg", "png", "jpeg"],
            overwriteInitial: true,
            showUploadedThumbs: false,
            showUpload: false,
            showRemove: false,
            layoutTemplates: {
                actionZoom: "",
                actionDrag: ""
            },
            initialPreview:
                @if(!empty($guide->photo))
                    ['/website/guide-photos/guide-{{$guide->id}}/{{$guide->photo}}'],
                @else
                    [],
                @endif
            initialPreviewAsData: true,
            initialPreviewConfig: [
                {
                    caption: "{{$guide->photo}}",
                    url: "@url('{{roleRootUrl()}}/guidePhoto/delete')",
                    extra: {
                        _token: "{{csrf_token()}}",
                        guide_id: "{{$guide->id}}"
                    }
                }
            ],
            uploadExtraData: {
                _token: "{{csrf_token()}}",
                guide_id: "{{$guide->id}}"
            }
        }).on("filebatchselected", function() {
            input.fileinput("upload");
        })`
