### ISSUE TITLE
BUG in Preview Zoom for image

### ISSUE THREAD

**Issue by edwinhuish** [kartik-v/bootstrap-fileinput#713]
Sometimes will just show the black background without anything, without error also. Just like the gif blew:
![8](https://cloud.githubusercontent.com/assets/5207925/16772832/3b8c89fa-4888-11e6-957c-8fb27ea8790e.gif)

And... My code just like blew:
```
<div class="text-center">
    <div class="product-picture avatar-picture center-block" style="width:200px">
          <input name="picture" type="file" class="file-loading products-picture" data-id="{$product.id}">
    </div>
</div>
```````
JS: 
`````
$('input.products-picture[data-id="{$product.id}"]').fileinput({
            showClose: false,
            showCaption: false,
            showBrowse: false,
            elErrorContainer : '#picture-errors',
            defaultPreviewContent: '<img src="./Upload/Default/default_pic.jpg" alt="Product Picture" style="width:160px">',
            previewSettings : {
                image: {width: "auto", height: "auto"}
            },
            initialPreviewAsData: true,
            initialPreview: '{$product.pic_directory}'?'{$product.pic_directory}':false,
            layoutTemplates: {main2: '{preview}'},
            fileActionSettings: {
                showDrag: false,
                showRemove: false,
            },
            previewZoomSettings:{
                image: {width: "auto", height: "auto", 'max-width': "100%",'max-height': "100%"},
            }
        });
``````

**Comment by kartik-v** [comment]
It seems you are rendering content via ajax... ensure there are no javascript errors when you are doing this and ensure the jquery plugins are initialized properly. For example the preview zoom functionality depends on bootstrap modal to initialize correctly.

**Comment by kartik-v** [comment]
Do one more check on your page...

Search for the markup containing `<div id ="kvFileinputModal"` on your page and compare if there are some issues in this (e.g. duplicate id content OR this container has no children due to some reason OR a broken markup).

**Comment by edwinhuish** [comment]
@kartik-v 
I think the problem is I'm using multi instances, always hay same problem when I try to zoom the second picture.

Any way, it have no error with another js, and jquery, bootstrap work well.
![9](https://cloud.githubusercontent.com/assets/5207925/16797001/0e101704-4918-11e6-9b7b-967b5a35a710.gif)

**Comment by edwinhuish** [comment]
@kartik-v do you have solution of multi instances? Thx a lot.

**Comment by kartik-v** [comment]
Ensure you have unique different identifiers for your HTML file inputs when using multiple instances on the same page.

**Comment by kartik-v** [comment]
I can only give pointers--- basically you need to debug your code:

- Ensure your `bootstrap.js` is not loading multiple times thereby causing the loaded bootstrap modal (for earlier fileinput) to break
- Ensure you have unique different identifiers for your HTML file inputs when using multiple instances on the same page.

**Comment by kartik-v** [comment]
I can only give you pointers --- but it is basically upto you to debug your code and check.

- Ensure your `bootstrap.js` or a similar lib is not loading multiple times thereby causing the loaded bootstrap modal (for earlier fileinput) to break.
- Ensure your js files and scripts are being loaded in the right sequence (and without duplication) once you render content via ajax
- Ensure you have unique different identifiers for your HTML file inputs when using multiple instances on the same page.
- You may run this code from Chrome Debug Console when the black screen shows to check if the modal works:
```js
$('#kvFileinputModal').appendTo("body").modal('show');
```

**Comment by kartik-v** [comment]
Also check for your other javascript and widgets markup on the page that could be causing this.

For example [check this SFO post](http://stackoverflow.com/questions/21126617/bootstrap-3-modal-disappearing-below-backdrop-when-using-a-fixed-sidebar/21127348#21127348) on how the sidebar can cause the modal to be  hidden behind the modal backdrop.

To isolate the issue, you may want to try this out on a fresh blank page without other plugins/css to ensure multiple instances work. For example check this [on the plugin demo page](http://plugins.krajee.com/file-preview-management-demo) where multiple file input instances do work properly to render the zoom modal dialogs.

**Comment by edwinhuish** [comment]
Run the code in Console is worked! And just need to append, no show(); 

```
$('#kvFileinputModal').appendTo('body');
```

And I have check in the simple page, it work perfectly also...

Why??

**Comment by kartik-v** [comment]
Yes that is the reason i said you muat check your code and the above snippet is just to ensure modal is appended properly at the end to the body and not before. As I said it is because of other components in your page like tabs, menus which inject JavaScript and CSS and is pushing the modal behind the background. You need to ensure that.

**Comment by edwinhuish** [comment]
And if I add this code to the body, it work too. 

But I think it's not the solution, because when I click zoom button, your code may run again and try to add <div id="kvFileinputModal"   ?

```
<div id="kvFileinputModal" class="file-zoom-dialog modal fade" tabindex="-1" aria-labelledby="kvFileinputModalLabel" style="display: none;"></div>
```

**Comment by Simphiwe-tech** [comment]
Bro atleast your close button works mine does not
