### ISSUE TITLE
Caption not removed when close button is clicked

### ISSUE THREAD

**Issue by mxmauro** [kartik-v/bootstrap-fileinput#715]
Hi,

First, good job and very nice plugin.

I have an almost basic configuration using defaultPreviewContent to show a default image when none is selected. No initialPreview data.

I select a gif image, the preview appears correctly but when I press the close button, the image is removed BUT the caption at the left of the browse button remains.

Debugging the code I found `_setCaption` function exits because `isError==false` and `if (isEmpty(content)) == true` so the div is never cleared.

Regards.

**Comment by kartik-v** [comment]
You need to set [initialCaption property](http://plugins.krajee.com/file-input#option-initialcaption) for your use case if you need to show a specific initial caption on clear. Remember to set it to a blank space (and not an empty string) if you do not want anything displayed.

**Comment by kartik-v** [comment]
Ok I will provide a fix for this.

**Comment by mxmauro** [comment]
Hi Kartik,

Thanks for the answer and fix.

Regards,
Mauro.
