### ISSUE TITLE
Ajax upload - Clear event logic confusion

### ISSUE THREAD

**Issue by salihklc** [kartik-v/bootstrap-fileinput#716]
Hello,
I have a little confusion about ajax upload fileclear event, I upload all files to my server with ajax sync or async doesn't matter. After create initialPreview for each other they shown to my page but I think I found a missing plugin method. After I click clear or "x" button for clear all file, it doesn't do anything. I search all documentation and there is no deleteall method for destroying uploaded files. Also found [THIS EXAMPLE](http://plugins.krajee.com/file-input-ajax-demo/4) exactly show my question. After you upload some file you can't remove them with clear or "x" button. Probably I trigger all "kv-file-remove" button for temporary solution but I just wanna ask am I misunderstood  the plugin and I'm just my dalliance  or is it a really missing method. Thanks :)

**Comment by kartik-v** [comment]
Fileclear is only applicable for files selected from client and not yet uploaded. So it had nothing to do with your content in initial preview. Since you already have control of files on server you can write your own code to delete all files on server.
