### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by vmtco** [kartik-v/bootstrap-fileinput#717]
Hi,
First, good job and very nice plugin.

I have an almost basic configuration and set allowedFileExtensions only jpg file and fileupload set multiple files support, when select any other file type like png, raise error in console
> Uncaught TypeError: Cannot read property 'name' of undefined

and show one error message in Error Container and stop uploading other valid file :(

**Comment by kartik-v** [comment]
I am not sure -- you need to update any other cases to reproduce your error.

Check this [demo example](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-5) that allows you to only select `text` files... but if you select other files it does not cause any such issue as described above.

**Comment by vmtco** [comment]
![image](https://cloud.githubusercontent.com/assets/2614015/17504943/9f17e574-5e12-11e6-9516-4eab80872637.png)

**Comment by ionvladescu** [comment]
i have still some issue
