### ISSUE TITLE
The  'previewId' with event 'fileuploaded' is NOT exist

### ISSUE THREAD

**Issue by hrwhat** [kartik-v/bootstrap-fileinput#719]
The previewId is overrode after the file is uploaded, so I can't select this element in the page,why provide a overrode previewId?And I think that producing a unique previewId is more conveniant.

**Comment by capqueen** [comment]
It does not fixed? I found dom id will change to 'uploaded-xxxx' after uploaded. so i still can not find dom by previewId?
