### ISSUE TITLE
How not to return a json value

### ISSUE THREAD

**Issue by yang3913** [kartik-v/bootstrap-fileinput#724]
## problems
hi,
I want to use the bootstrap-fileinput,but I do not want to return a json value.Can you help me?
I want to return a normal value to render the page of html with other values. So I can not return a json value.

**Comment by kartik-v** [comment]
Read [the docs](http://plugins.krajee.com/file-input) and plugin usage modes.

Also as mentioned in the guidelines [for contribution](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md) and [logging an issue](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/ISSUE_TEMPLATE.md), please use this repo issue tracker only for reporting bugs and issues. 

For queries on usage and coding/programming, [try the Q & A forum](http://webtips.krajee.com/questions).
