### ISSUE TITLE
FileStack size error

### ISSUE THREAD

**Issue by houzw** [kartik-v/bootstrap-fileinput#726]
Hello there, I have encountered a problem when I use fileinput: 
 if i use browse button to select more than 1 file ( 2 for example ) at once, there will be only one file in the filestack  and one file caption in the file-caption-name div, but if i add more files, the size of the filestack become correct ( 3 if i add 1 file again )
```
$fileUpload.on('change', function(event) {
            var files = $fileUpload.fileinput('getFileStack');
            console.log(files);   
        });
```
i used above code to check: the first time i select 2 files, i get `Array[ File ]`, and then  i add 1 file more, i get `Array[ File ,File ,File ]`

my options 
```
        uploadUrl: '../../ajaxUpload/video.do',
        allowedFileExtensions:['mp4', 'webm','ogg','flv'],
        maxFileSize: 1007000,//500mb
        theme: 'fa',
        showPreview:false,
        uploadAsync: true,
        maxFileCount: 5,
        minFileCount: 1,
        elErrorContainer:'#err',
        showUploadedThumbs: true,
        uploadExtraData: function ()
        {
            var obj = {};
            obj['fileclass'] = getSelectedTypes();
            var $open = $('#open');
            if ($open.attr('checked'))
                obj['open'] = $('#open').val();
            else
                obj['open'] = 0;
            return obj;
        }
```

**Comment by kartik-v** [comment]
Not sure or cannot reproduce this. Can you share a js fiddle?

You must have `multiple` attribute of your file input markup to be set to true to allow multiple file uploads.

**Comment by houzw** [comment]
here is  a js fiddle 
https://jsfiddle.net/houzw/Lo3cxp47/3/?utm_source=website&utm_medium=embed&utm_campaign=Lo3cxp47

**Comment by kartik-v** [comment]
You have used a wrong event - because that may not have the complete data in the plugin... use `filebatchselected` event instead for your use case...

Check the [updated fiddle](https://jsfiddle.net/jezdd76z/1/).
