### ISSUE TITLE
Method to count all current select files

### ISSUE THREAD

**Issue by fabioaccetta** [kartik-v/bootstrap-fileinput#731]
I'm using only ajax for upload and delete and I need a method to count all current selected files (both uploadable/deleteable and already uploaded but without errors). Upload is triggered with the `filebatchselected` event right after files are selected.

If I use `$input.fileinput("getFileStack")` I don't get the value I expect, as documentation says:

```
[...] This method will not return files [...] which have already been uploaded.
```

Shortly, I need a method similar to that one you already use to populate `initialCaption` inside the `<div class="file-caption-name"></div>` - `previewCache.count(self.id)` - to update the `div#stack-size` with the files count after every upload/delete action, but I can't find anything like that in documentation.

My config with yii2:
```php
[...]
'options' => [
	'multiple' => true,
],
'pluginOptions' => [
	'maxFileCount' => 10,
	'previewFileType' => 'any',
	'initialPreviewAsData' => true,
	'initialPreview' => $initialPreview,
	'initialPreviewConfig' => $initialPreviewConfig,
	'overwriteInitial' => false,
	'uploadUrl' => Url::toRoute(['ajax-file-upload', 'id' => $model->id]),
	'uploadAsync' => false,
],
'pluginEvents' => [
	'filebatchselected' => 'function() {
		$(this).fileinput("upload");
	}',
	'filebatchuploadsuccess' => 'function() {
		var stack = $(this).fileinput("getFileStack"); // <-- not as expected
		var value = stack.length;
		$("#stack-size").html(value);
	}',
	'filedeleted' => 'function() {
		var stack = $(this).fileinput("getFileStack"); // <-- not as expected
		var value = stack.length;
		$("#stack-size").html(value);
	}',
],
[...]
```

**Comment by kartik-v** [comment]
The plugin can only give you client side data... for server side uploaded files - you need to write your logic to calculate the count of files successfully uploaded.

**Comment by fabioaccetta** [comment]
Yes, I need only client side data, exactly like your `<div class="file-caption-name"></div>` that tells (client-side) the number of files currently handled by the plugin.

**Comment by kartik-v** [comment]
This is based on `initialPreviewCount` and `validateInitial` properties... that you can use... but will check on this.... because it can be changed...

**Comment by fabioaccetta** [comment]
The solution could be a sort of public method like this:
```js
var count = $("#input-id").fileinput("getFilesCount");
```
available inside the `filebatchuploadsuccess` and the `filedeleted` events.
