### ISSUE TITLE
Error messages don't match with the described in the official page

### ISSUE THREAD

**Issue by viaro-vinicio** [kartik-v/bootstrap-fileinput#732]
Hi All, I started to use this plugin, but the messages doesn't match with the plugin options, I mean I set just csv as allowed file extension and also I set a max file size, but the message always says " No files selected".

$("#input-file").fileinput({
        'allowedFileExtensions': ['csv'],
        'showUpload': false,
        'showPreview': false,
        'maxFileSize': 2000
    });
![upload](https://cloud.githubusercontent.com/assets/7935070/17375778/b23b56f6-596f-11e6-8e35-8d9725bd70cf.png)

**Comment by kartik-v** [comment]
Its obvious... the message shown is just the file caption message (identifying count/name of file selected). The error message by default is shown in the preview container and you have set `showPreview` to `false` and not seeing it.

If you are setting `showPreview` to `false` and you need to see error messages in a different place set the [elErrorContainer property](http://plugins.krajee.com/file-input#option-elerrorcontainer)
