### ISSUE TITLE
$thumb is undefined after uploaded 07.08.2016

### ISSUE THREAD

**Issue by nemozar** [kartik-v/bootstrap-fileinput#734]
in function (line 1795)
fnSuccess = function (data, textStatus, jqXHR) {
self._raise('fileuploaded', [outData, **$thumb**.attr('id'), i]);

after successful uploaded console write error
TypeError: $thumb is undefined

i am not set showPreview!

**Comment by nemozar** [comment]
How can i get this is commit from composer update? after update i have latest version without fix this bug.
In composer set version "dev-master" on "kartik-v/yii2-widgets"

**Comment by rvanginneken** [comment]
@kartik-v Can you please release this fix under a new version? thanks!

**Comment by mrbadaw** [comment]
I downloaded the latest version and still have this issue when using initial preview
how can I have this bug fixed ?

**Comment by mattymatty76** [comment]
Hi,
you have updated file input.js just now, but the problem is not fixed.
I receive this message after updating (and before) at your last modify
in fileinput.js: TypeError: $thumb is undefinedfileinput.js:3292:21

Thank you anyway

**Comment by kartik-v** [comment]
Fixed via #1475.
