### ISSUE TITLE
SyntaxError: Unexpected end of JSON input.

### ISSUE THREAD

**Issue by gmiguelr87** [kartik-v/bootstrap-fileinput#738]
Hello Kartik,

First of all, sorry for my english. I would like to congratulate you for this useful resource.
I found "bootstrap-fileinput" yesterday, I don't know about js, I only know something about html and php.
I want to use "bootstrap-fileinput" as a resource to upload images from my computer to a web server.
When I click on Upload button I call a php file that does all the work, but when the progress bar is complete, I obtain some warning or error messages (please, see attached file).

Can you help me please?
Thanks !!
![screen](https://cloud.githubusercontent.com/assets/20948392/17552971/82a78290-5f03-11e6-8a67-18843bd40e51.jpg)

**Comment by kartik-v** [comment]
Please [read the guidelines for posting issues](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md). 

You need to [read the documentation](http://plugins.krajee.com/file-input) for understanding configuration options of the plugin. 

Post [programming related queries on the webtips forum](http://webtips.krajee.com/questions). 

Your [programming related query is covered in a webtip here](http://webtips.krajee.com/question/json-syntax-error-bootstrap-fileinput/).

**Comment by igorek67** [comment]
Just make some changes in your UploadController - use `return '{}';` instead `return;`

```
        if (Yii::$app->request->isPost) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->upload()) {
                // file is uploaded successfully
                return '{}';
            }
        }
```

**Comment by yayanzhu** [comment]
Sorroy for my English. I have solved this issue. I discovered that the data returned from server must be json encode.
