### ISSUE TITLE
fileinput is not a function,can't init by <script>

### ISSUE THREAD

**Issue by JobanCai** [kartik-v/bootstrap-fileinput#740]
Hi~ I have a problem in my project.
I can init in the fileinput <script></script>,
![image](https://cloud.githubusercontent.com/assets/18718928/17576434/6412ba8c-5fa5-11e6-9f09-afa76f3d6cf2.png)

but I can init in
![image](https://cloud.githubusercontent.com/assets/18718928/17576472/d93c60ba-5fa5-11e6-8403-f7d596b781ed.png)

**Comment by kartik-v** [comment]
Please [read the guidelines for posting issues](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md).

You need to [read the documentation](http://plugins.krajee.com/file-input) for understanding configuration options of the plugin.
