### ISSUE TITLE
How to disable "View Details" button?

### ISSUE THREAD

**Issue by ramin-rp** [kartik-v/bootstrap-fileinput#744]
Hello,
How can i disable View Details button on image preview?
![untitled](https://cloud.githubusercontent.com/assets/1921240/17643582/b96fdca0-6183-11e6-8ed0-01c5a0619025.png)

**Comment by kartik-v** [comment]
Please [read the guidelines for posting issues](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md).

You need to [read the documentation](http://plugins.krajee.com/file-input) for understanding configuration options of the plugin.

You need to set [showZoom property within fileActionSettings](http://plugins.krajee.com/file-input#option-fileactionsettings).

**Comment by jhonatanquilca** [comment]
You can try with
layoutTemplates: {footer: ''},

**Comment by offboard** [comment]
I use 
$('button[type="button"].kv-file-zoom').remove();

after load fileinput plugin

**Comment by kartik-v** [comment]
Read my [previous comment](https://github.com/kartik-v/bootstrap-fileinput/issues/744#issuecomment-239623672)... Set showZoom to false within file ActionSettings.

**Comment by offboard** [comment]
I tried but not work, maybe bootstrap version

**Comment by bremg** [comment]
None of the settings work anymore on the krajee version

**Comment by rajjanorkar** [comment]
@kartik-v "showZoom" does not work. i tried setting it false but still show that button.

**Comment by rjanorkar** [comment]
`$("#files").fileinput({ fileActionSettings: {showZoom: false} });`

This is how you ned to add it and it works.

**Comment by kartik-v** [comment]
Yes as highlighted in comment earlier...please [read the documentation](http://plugins.krajee.com/file-input/plugin-options) for understanding configuration options of the plugin.

You need to set [showZoom property within fileActionSettings](http://plugins.krajee.com/file-input/plugin-options#fileActionSettings).
