### ISSUE TITLE
How to enable textarea the same in the picture?

### ISSUE THREAD

**Issue by anhtu211** [kartik-v/bootstrap-fileinput#749]
i cant upload image here, so i upload to photobucket
[image](http://s9.photobucket.com/user/gautruc211/media/fileinput1_zps2adljwrn.jpg.html)

**Comment by kartik-v** [comment]
Not clear with your query. Have you gone through docs and demos?

An example of capturing additional data through text box is [highlighted in this demo here](http://plugins.krajee.com/file-input-ajax-demo/7).
