### ISSUE TITLE
problem with disabling file preview

### ISSUE THREAD

**Issue by TheAliAbbasi** [kartik-v/bootstrap-fileinput#750]
so I installed this plugin a few weeks back, and it was working perfect, then suddenly it started showing exceptions. I had show preview turned off at first and the exception showed that $thumb is undefined, and when I looked it up in the source the problem was on line 1795 - raising of fileuploaded event - and it only works when I turn on file preview
I searched the web for hours and it seems no one had the same problem.
One more thing that might be helpful. I'm using `r.js` and update my packages through `bower`. I don't know if you pushed something along the way or it's a dependency problem.
Any help would be so much appreciated.

**Comment by kazazes** [comment]
This and #246 are related, I think. The `fnSuccess` method fails if file previews are hidden because, as @TheAliAbbasi said, `$thumb` is undefined. I was putting together a PR but it looks like it's fixed in the 4.3.5 version in the master repo. Hopefully the packages will be updated soon.

**Comment by TheAliAbbasi** [comment]
Good to know, it gave me a real headeche, lol

**Comment by kazazes** [comment]
@kartik-v, could you create a new release for 4.3.5 so that CDNs are updated? Thanks.
