### ISSUE TITLE
File Gets Removed even after returning False in "filesuccessremove" Event

### ISSUE THREAD

**Issue by faiz2rock** [kartik-v/bootstrap-fileinput#751]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

This is Code,
```js
$("[id$=File]").on('filesuccessremove', function(event, id) {                    
    $.get('@Url.Action("DeleteFile","File")?id='+FileId[id],'',function(data,status){
        if (status=="success") {
            FileId.splice(id,1);
            return true;
        }else {                            
            return false;
        }
    });                      
});
```
## Steps to reproduce the issue

1.After Setting Listener on filesuccessremove  Upload Any File and Hit Upload Button
2.Now Delete The File Using Delete Icon
3.File gets Deleted

## Expected behavior and actual behavior

When I follow those steps, I see...
File gets Deleted Even if False Was Returned.
I was expecting...
Any Error Message.
## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is expected. The `filesuccessremove` event fires only after a file has been successfully removed.

**Comment by faiz2rock** [comment]
Ok then how can i prevent a file from bieng removed?

**Comment by kartik-v** [comment]
Handle it as part server code that is fired via the deleteUrl ajax call and return an error message...

**Comment by kartik-v** [comment]
So your server code must return a json object with error key set and it will be displayed by the plugin and the file will not be removed.. something like...

```
{
   error: 'This file cannot be deleted'
}
```

**Comment by faiz2rock** [comment]
Ok Thanks. I'll try.
