### ISSUE TITLE
Access Denied when open a pdf file via Visual Studio 2013

### ISSUE THREAD

**Issue by uhutch** [kartik-v/bootstrap-fileinput#752]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. I downloaded the zip file and opened it in Visual Studio 2013.
2. When I run the index.html file, and tried to open a pdf file it said "Access denied" (I successfully open images files).
3. P.S. it successfully opened a pdf file when I ran the index.html outside Visual Studio.

## Expected behavior and actual behavior

When I follow those steps, I see... "Access Denied"

I was expecting... to see and able to zoom in the pdf file and/or other file format

## Environment

Browsers

- [x ] Google Chrome
- [x ] Mozilla Firefox
- [x ] Internet Explorer
- [ ] Safari

Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: release v4.3.5

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by uhutch** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21316988/18064560/f693dc5e-6dfd-11e6-9f19-9eade9bc9452.png)

**Comment by uhutch** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21316988/18064877/5b43ddec-6dff-11e6-9742-3df7c149c93b.png)

**Comment by kartik-v** [comment]
This is more to do with configuring your dev environment, your browser's preview capability and IDE capability etc. Do let know what is needed to be done from plugin end and will reopen it.
