### ISSUE TITLE
resizeImage not working in tablet Photo

### ISSUE THREAD

**Issue by canq** [kartik-v/bootstrap-fileinput#755]
The problem occurs when I take a picture with my tablet android, and treated with all browsers but the result is the same.
I need to resize the picture when you select it from a tablet .

resizeImage: true,
maxImageWidth: 100,
resizePreference: 'width',

**Comment by kartik-v** [comment]
You need to check if the browser supports HTML5 canvas for resize as mentioned in the docs.

Most modern browsers support HTML5 canvas and will work.
