### ISSUE TITLE
[Enhancement] use the options only available for ajax with normal file upload

### ISSUE THREAD

**Issue by ctf0** [kartik-v/bootstrap-fileinput#756]
this is not a bug , rather its a way on how we can use the options only available for ajax with normal file upload , hopefully most of those `file preview, Drag & Drop Files using drop zone, Ability to append files to already selected list` will be available for normal usage and not just ajax.

here is a gist with all the code with some personal changes/edits , using laravel but u can use the code with any framework or even plain php if u want.

https://gist.github.com/ctf0/8cdad76b8b8a0c80f2241d47ab430402

**Comment by qinxiaowen** [comment]
hello, some question about  how use the params in this  plug?
```
 xhrFields: {
                            withCredentials: true
                        },
                        crossDomain: true
 
```

**Comment by ctf0** [comment]
sorry, where is that code ?

**Comment by qinxiaowen** [comment]
i got it. use the  ajaxSettings options

**Comment by ctf0** [comment]
@kartik-v yes sure, i just don't know where exactly to add the code ?
