### ISSUE TITLE
Caption does not display correctly when select multiple files

### ISSUE THREAD

**Issue by yaoman3** [kartik-v/bootstrap-fileinput#757]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Use the code in http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-10.
2. Select multiple files, the caption will show "X files selected" (work as expected)
3. Then add option "uploadUrl: url_to_upload" to the js code, after select multiple files, the caption will show one of the files' name.

## Expected behavior and actual behavior

When I follow those steps, I see one of the filename

I was expecting "X files selected"

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Not clear on this issue.

The plugin will display "X files selected" if more than one file is selected.

If only one file is selected it will display the file name of the file selected.

**Comment by onmotion** [comment]
I have same issue if set 

    'showPreview' => false, 

(yii2 widget). and in console I have 

    Uncaught TypeError: Cannot read property 'attr' of undefined(…) 
    fileinput.js:1795

This issue only in version kartik-v/bootstrap-fileinput v4.3.4, in v4.3.1 all is ok

**Comment by kartik-v** [comment]
@onmotion  you need to get updated release from dev-master... in either case for the main issue it is not reproducible... I am closing this unless you share a reproducible outcome... and will reopen it.
