### ISSUE TITLE
how to disable refresh the whole page when click the upload button

### ISSUE THREAD

**Issue by yangzhaohui89** [kartik-v/bootstrap-fileinput#759]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
You need to handle this in your programming code and configuration. If you are using a non ajax mode (without uploadUrl) ... then the Upload Button will default to Form SUBMIT ... which by default will typically refresh the page - unless you are writing your own code to trap this and do it differently. For AJAX Mode (with uploadUrl this is not mandatory).

In either case this is not an issue and expected outcome. If you need help on coding such scenarios please use the  [webtips Q & A forum](http://webtips.krajee.com).

**Comment by yangzhaohui89** [comment]
thank to your answer. I try to regitster  in your web but fail . I'd like to ask the questions that I just want to use the ajax mode,but I don't want to submit my data to server. I handle my data in the  filebatchpreupload,but I need a fake success to show.How could I can do to stop the ajax submit at the same time use the ajax mode.
