### ISSUE TITLE
Not Issuses But question about stop ajax mode

### ISSUE THREAD

**Issue by yangzhaohui89** [kartik-v/bootstrap-fileinput#762]
thank to your answer. I try to regitster in your web but fail . I'd like to ask the questions that I just want to use the ajax mode,but I don't want to submit my data to server. I handle my data in the filebatchpreupload,but I need a fake success to show.How could I can do to stop the ajax submit at the same time use the ajax mode.
By the way, I got 6 pieces of mails about wordpress password reset ,all failed. And I sent email to the address  bootstrap-fileinput@noreply.github.com failed,too.

**Comment by kartik-v** [comment]
For programming help, you can go through docs or post query in comments section of [plugin docs page](http://plugins.krajee.com/file-input) to get help from community or post it in [webtips forum](http://webtips.krajee.com) to get programming help.
