### ISSUE TITLE
initialPreview parameter makes problem with open file dialouge

### ISSUE THREAD

**Issue by Arashz22** [kartik-v/bootstrap-fileinput#763]
myCode are these

```
<div id="kv-avatar-errors-2" class="center-block" style="width:800px;display:none"></div>
<div class="kv-avatar center-block" style="width:200px">
    <input id="avatarAjax" name="avatar" type="file" class="file-loading">
</div>
<script>
 $("#avatarAjax").fileinput({
        language: 'fa',
        uploadUrl: '@Url.Action("UploadProfPicUp", "User")',
        overwriteInitial: true,
        maxFileSize: 3000,
        showClose: false,
        showCaption: false,
        showBrowse: false,
        browseOnZoneClick: true,
        elErrorContainer: '#kv-avatar-errors-2',
        msgErrorClass: 'alert alert-block alert-danger',
        defaultPreviewContent: '<img id="AvImg" src="/Content/Images/profileImg/defaultUser.png" alt="Your Avatar" style="height:150px;width:150px"><h6 class="text-muted">select new picture</h6>',
        layoutTemplates: { main2: '{preview}' },
        allowedFileExtensions: ['png', 'jpg', 'jpeg', '.gif', 'bmp']
    });
</script>
```

every thing is OK and  i can upload picture by clicking on default picture or `<h6>` tag
but when i add this parameter 

`initialPreview: ['<img id="AvImg" class="file-default-preview" src="/Content/Images/profileImg/@ViewBag.Avatar" alt="Your Avatar" style="height:150px;width:150px"><h6 class="text-muted">select new picture</h6>']`

i must only click on the border of div tag which has class like this `file-drop-zone clickable` to show open file dialouge.
and clicking on `img` or `h6` tag does not open file dialouge.

**Comment by kartik-v** [comment]
Yes your markup is not entirely correct... you can rather set `initialPreviewAsData` to `true` and just pass the image src location as `initialPreview` and the plugin will auto render the markup correctly.
