### ISSUE TITLE
How to delete a initPreview image ,that no uploda url? 

### ISSUE THREAD

**Issue by strongant** [kartik-v/bootstrap-fileinput#766]
## I use this plugin in angular that not set upload url ,how to delete a single file?

**Comment by kartik-v** [comment]
Read the documentation.

You can set the `url` within [initialPreviewConfig](http://plugins.krajee.com/file-input#option-initialpreviewconfig) to point to your webservice to delete for each file...

OR

You can set the [deleteUrl](http://plugins.krajee.com/file-input#option-deleteurl) as a single webservice for all files in initialpreview.

**Comment by strongant** [comment]
Threse images not in server,they are in localStorage.I don't upload image when user selected file.

**Comment by kartik-v** [comment]
Then you need to write your own javascript logic to delete these files - you can embed your own custom delete action button markup in thumbnails by setting [otherActionButtons](http://plugins.krajee.com/file-input#option-otheractionbuttons).

**Comment by strongant** [comment]
Thank you,let me try.

**Comment by strongant** [comment]
File remove button no provide a event ?
