### ISSUE TITLE
Weird Message on Image Upload [object Object]

### ISSUE THREAD

**Issue by ashishkgupta11** [kartik-v/bootstrap-fileinput#767]
We have been using this plugin in our application and it works like a charm. However when we upload an image file and hit upload, image starts uploading and on completion a message apears underneath the file uploaded _see screenshot_. Is this something coming from the library?
If it is, is there any workaround for that?

Thanks a lot.

<img width="604" alt="screen shot 2016-09-28 at 1 05 46 pm" src="https://cloud.githubusercontent.com/assets/17623256/18924203/4176d85c-857d-11e6-99ab-49aac6b554a4.png">

**Comment by kartik-v** [comment]
Yes you need to [read the documentation](http://plugins.krajee.com/file-input#usage) to understand how to use the plugin and configure it for ajax uploads. For ajax uploads your server action (identified in uploadUrl) must return a valid JSON object (if you do not have an initial preview to return - at least just a empty JSON object `{}`).
