### ISSUE TITLE
fileimagesresized triggered prematurely

### ISSUE THREAD

**Issue by edwh** [kartik-v/bootstrap-fileinput#769]
Thanks for a nice plugin.

The fileimagesresized event can be triggered before the files have actually been resized.  This is because it is triggered when the toBlob() call has been started, but this will often be before it has completed.  

In my case I was triggering an upload on this event - which meant that it was uploading the image data before the resize.  

fileimageresized is correctly triggered in the toBlob() callback, but should be triggered after the blob has been stored away in the array rather than before.

**Comment by pedhenrique** [comment]
Hi @edwh! How could we tackle this? I moved the raise line of fileimageresized after the blob storage, and it seems to correct the problem for this specific event, but I don't know how to correct for the fileimagesresized event. Maybe using promisses or a counter that will raise it after all images have been resized? Could you help me with a temporary solution? Thanks in advance.

**Comment by pedhenrique** [comment]
Well, as a temporary solution for anyone with the same problem as edwh, I did the following:

Set a counter with value 0 before the for loop that call _getResizedImage for each image in the stack. Then, for each iteration, I increment the counter. Then, in the toBlob() callback function, I decrement the counter and check if it's equal to zero. If so, I raise the fileimagesresized event, because all images have been resized. Maybe this isn't the best solution, but I'm a beginner in JS and it was the solution I could think of. I also change the raise of fileimageresized event to happen after blob storage. The altered code:

```javascript
_validateAllImages: function () {
    var self = this, i, config, $img, $thumb, pid, ind, params = {}, errFunc;
    if (self.loadedImages.length !== self.totalImagesCount) {
        return;
    }
    self._raise('fileimagesloaded');
    if (!self.resizeImage) {
        return;
    }
    errFunc = self.isUploadable ? self._showUploadError : self._showError;
    var counter = {val: 0};
    for (i = 0; i < self.loadedImages.length; i++) {
        config = self.loadedImages[i];
        $img = config.img;
        $thumb = config.thumb;
        pid = config.pid;
        ind = config.ind;
        params = {id: pid, 'index': ind};
        counter.val++;
        if (!self._getResizedImage($img[0], config.typ, pid, ind, counter)) {
            errFunc(self.msgImageResizeError, params, 'fileimageresizeerror');
            self._setPreviewError($thumb, ind);
        }
    }

},
_getResizedImage: function (image, type, pid, ind, counter) {
    var self = this, width = image.naturalWidth, height = image.naturalHeight, ratio = 1,
        maxWidth = self.maxImageWidth || width, maxHeight = self.maxImageHeight || height,
        isValidImage = (width && height), chkWidth, chkHeight,
        canvas = self.imageCanvas, context = self.imageCanvasContext;
    if (!isValidImage) {
        return false;
    }
    if (width === maxWidth && height === maxHeight) {
        return true;
    }
    type = type || self.resizeDefaultImageType;
    chkWidth = width > maxWidth;
    chkHeight = height > maxHeight;
    if (self.resizePreference === 'width') {
        ratio = chkWidth ? maxWidth / width : (chkHeight ? maxHeight / height : 1);
    } else {
        ratio = chkHeight ? maxHeight / height : (chkWidth ? maxWidth / width : 1);
    }
    self._resetCanvas();
    width *= ratio;
    height *= ratio;
    canvas.width = width;
    canvas.height = height;
    try {
        context.drawImage(image, 0, 0, width, height);
        canvas.toBlob(function (blob) {
            self.filestack[ind] = blob;
            self._raise('fileimageresized', [pid, ind]);
            counter.val--;
            if (counter.val == 0) {
                self._raise('fileimagesresized');
            }
        }, type, self.resizeQuality);
        return true;
    }
    catch (err) {
        return false;
    }
}        
```

**Comment by chriscant** [comment]
I found that raising fileimageresized in _getResizedImage() seems to fix the extra case when no resize needed:

```
            if (width === maxWidth && height === maxHeight) {
                self._raise('fileimageresized', [pid, ind]);
                return true;
            }
```

**Comment by chriscant** [comment]
Incidentally, the resize process happens even if the image is smaller than the maximum ie when the ratio is 1. The resize could be avoided in this case - don't forget to fire fileimageresized.
