### ISSUE TITLE
Sending files with maxFileSize is long

### ISSUE THREAD

**Issue by andrelimeira** [kartik-v/bootstrap-fileinput#770]
I'm using the MaxFileSize option, it does not display the files and generates the exception in view, but even so it sends the files to php and I need to validate in php and wait for the uplaod time of files, there is a way to remove these the 'input file =' html file before sending to php?

$("#input_id").fileinput({
        showUpload: false,
        showCaption: false,
        language: 'pt-BR',
        browseClass: 'btn btn-warning btn-lg',
        allowedFileExtensions : extensoes_ged,
        previewFileIcon: '<i class="fa fa-king"></i>',
        overwriteInitial: false,
        removeFromPreviewOnError : true,
        dropZoneEnabled: false,
        uploadUrl: _base_url,
        maxFileSize: 1024,
        slugCallback: function(filename) {
            return filename.replace('(', '_').replace(']', '_');
        }
    });

I'm testing in Google Chrome, Mozilla Firefox with OS Windows and Linux.

jQuery version: v2.1.4
bootstrap-fileinput version: v4.3.5

Thank's

**Comment by kartik-v** [comment]
Can you share a working example to test this (a jsfiddle or similar).

**Comment by kartik-v** [comment]
Not sure I can reproduce this. So closing this. In case you can share a working scenario where this issue occurs - will reopen.
