### ISSUE TITLE
autochanges dash to underscore in filename 

### ISSUE THREAD

**Issue by lkseoqkr** [kartik-v/bootstrap-fileinput#777]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. index.html on web-brower
2. upload any files which have dash mark in their names  ex) filename-1.txt
3. check the dash mark is converted to underscore ex) filename_1.txt

## Expected behavior and actual behavior

When I follow those steps, I see dash mark in filename is changed to underscore.

I was expecting the filename is shown on the screen. But  
The bug doesn't make any problem during uploading, but I retrieve filenames from
{caption} variable by input tag, so it is some issue to me.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 4.2.1
- bootstrap-fileinput version: 4.3.5

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by lkseoqkr** [comment]
This is minor issue. And most bootstrap file upload samples have the same issue as long as I test samples on the internet.

**Comment by kartik-v** [comment]
You may want to go through the docs. The plugin uses a default slug routine that escapes unwanted characters which may break HTML. You can control this through the [slugCallback](http://plugins.krajee.com/file-input#option-slugcallback) property of the plugin and give your own callback
