### ISSUE TITLE
http://plugins.krajee.com/file-input-ajax-demo/5  Not image format Preview question?

### ISSUE THREAD

**Issue by zyz** [kartik-v/bootstrap-fileinput#778]
http://plugins.krajee.com/file-input-ajax-demo/5
if upload file is not image format
Server return data preview url not image

**Comment by kartik-v** [comment]
Cannot understand this query and closing. Please follow [the guidelines](https://github.com/kartik-v/bootstrap-fileinput/blob/master/.github/CONTRIBUTING.md) for issues and contributions in this repo.
