### ISSUE TITLE
Error message is not displayed using IE11, "choose" button

### ISSUE THREAD

**Issue by pavv** [kartik-v/bootstrap-fileinput#780]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).
## Steps to reproduce the issue
1. Configure the plugin to use ajax uploads (asynchronous/synchronous, it doesn't matter) - the problem exists using both batch and single file uploads
2. Using IE11 open the web page
3. Click the "choose file" button to pick a file (or multiple files), such that the backend will return an error
4. Click upload - the upload starts and finishes with an error - the preview tile will have an exclamation point, but the error message returned by the service is not display
## Expected behavior and actual behavior

When I follow those steps, I see no error message. I was expecting to see an error message.
## Environment

Browsers
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer 11
- [ ] Safari

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.12.0
- bootstrap-fileinput version: 4.3.5
## Isolating the problem
- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by pavv** [comment]
I don't know if this is the best way to solve this issue, but it does work: it seems to me that the problem is that the file input is reset after setting the error message, which triggers the change event, which removes the error message. Using drag-and-drop there is no problem, because the value of the fileinput is always "". If I add self._clearFileInput(); after tfiles = e.target.files; (line 2769), then the error message is displayed after trying to upload the file. This is because reset doesn't trigger change, because the value of the fileinput is already "".

**Comment by kartik-v** [comment]
This looks related to #753.

There is already a [special handling for IE-11 here](https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js#L2733) to not allow file reset in IE causing undesirable effect as it also triggers change.

**Comment by pavv** [comment]
The trouble is that the special handling doesn't get executed in this case - the conditon `isEmpty($el.val())` is not met (using the button sets the value of the file input to the chosen file path, whereas drag-and-drop leaves the value empty). Reproducing this problem requires at least a mockup of a service - unfortunately I work on an internal application and I don't have anywhere to host something like that, or else I'd set something up to demonstrate this.

**Comment by kartik-v** [comment]
The reset should clear the native file input value so `isEmpty($el.val())` must return true.

**Comment by pavv** [comment]
From what I remember when I was trying to fix this yesterday, reset is run after upload completion. At that point the native file input is not yet cleared, so `isEmpty($el.val())` returns false (maybe that's the problem - should the native file input be cleared before completion?).

**Comment by kartik-v** [comment]
Yes reset indeed should be run after upload completion... and even if change is triggered.... the condition [as mentioned for IE 11 special case](https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js#L2733) should do nothing.

**Comment by kartik-v** [comment]
Reset indeed should be run after upload completion... and change is triggered only at that point for IE11. The condition [as mentioned for IE 11 special case](https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js#L2733) should do nothing and hence your error messages should be retained (error validation messages from your server are shown as any ajax request completes).

**Comment by davepgrant** [comment]
Hi, I just wanted to confirm that I am also experiencing this same issue in the latest version. Thanks pavv for the "fix"!

**Comment by kartik-v** [comment]
I am not able to reproduce this issue. Can you please reconfirm with a code/JS Fiddle and the plugin release (hope you have the latest one)? I can then reopen this.
