### ISSUE TITLE
File empty error message in Google Chrome

### ISSUE THREAD

**Issue by meventi-stephan** [kartik-v/bootstrap-fileinput#788]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Go to page http://plugins.krajee.com/file-multi-lang-demo#portugese-br-input
2. Uploading an empty file (0 KB) in Google Chrome
3. An error "GET data: net::ERR_INVALID_URL" is visible in Console (in Developer Tools)

## Expected behavior and actual behavior

I was expecting no such error in Google Chrome. Perhaps an additional error handling for empty files makes also sense.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: 4.3.5

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Resolved via 5edbd4d and [documented in the change log](https://github.com/kartik-v/bootstrap-fileinput/blob/master/CHANGE.md).
