### ISSUE TITLE
previewSettings not work

### ISSUE THREAD

**Issue by ybratukhin** [kartik-v/bootstrap-fileinput#792]
## Steps to reproduce the issue

            "name": "kartik-v/bootstrap-fileinput",
            "version": "v4.3.1",
setting cusum previewSettings parameters work, in latest version - not 

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: latest
- bootstrap-fileinput version: latest

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
latest release is v4.3.6
