### ISSUE TITLE
Edit Image via Initial Preview

### ISSUE THREAD

**Issue by AbdurRehman26** [kartik-v/bootstrap-fileinput#793]
Hi Awesome plugin.
I did not know where to ask this. I spent my whole day figuring out how to edit an image via this plugin. 
The problem is i used InitialPreview to view image what i previously uploaded in database. But now when i submit the form it shows that image Input is empty it does not contain the image.. Is this feature not added or am i making a mistake ?

**Comment by manoelcalixto** [comment]
+1

**Comment by kartik-v** [comment]
Initial Preview depends on data that you maintain and manage on the server. So to clarify, there is no physical file that you are sending to the client or something. So not clear when you mean you are not receiving the edited initial preview file.

You can supply additional data from your server for each initial preview file via `initialPreviewConfig` (e.g. `key`) and also use `initialPreviewThumbTags`, `uploadExtraData` and `layoutTemplates` to configure your own markup to render for initialPreview with relevant server attributes for you to receive back. Refer [ajax scenario 7](http://plugins.krajee.com/file-input-ajax-demo/7) to see an example of how you can edit the file name for example in initial Preview.
