### ISSUE TITLE
For big images, bigger than 5M, with limits set well, $_FILES in php is empty.

### ISSUE THREAD

**Issue by yourchoice** [kartik-v/bootstrap-fileinput#794]
For big images, bigger than 5M, with limits set well, $_FILES in php is empty.

```
minImageWidth: 100,
minImageHeight: 100,
maxImageWidth: 8000,
maxImageHeight: 8000,
			
maxFileSize: 0,
maxFileCount: 20,
```

And on the server I have set well the limits:
post_max_size	2048M
max_file_uploads	20
upload_max_filesize 	256M

With small sizes working well. Maybe somewhere in js code is a limit even maxFileSize: 0. Or something display the input file before send to server.

Can you help me to understand?

Recently I saw that random in console.log i have:

fileinput.js:1844 Uncaught TypeError: Cannot read property 'name' of null(…)
fnError @ fileinput.js:1844i @ jquery.min.js:2fireWith @ jquery.min.js:2A @ jquery.min.js:4(anonymous function) @ jquery.min.js:4
 ...

I use jquery 3.1.1 and bootstrap-fileinput v4.3.6

!!! Seems that this behavior is random.

**Comment by f0nt4** [comment]
Maybe just remove "maxFileSize: 0,"?

**Comment by kartik-v** [comment]
Suggest you check with latest updated code and confirm if you are facing the issue as cannot reproduce your issue. If you are facing the issue please share a JS Fiddle to reproduce and will reopen this issue.
