### ISSUE TITLE
How to change the option the file uploading

### ISSUE THREAD

**Issue by haijiandong** [kartik-v/bootstrap-fileinput#795]
I'm sorry, but I can not find the answer.
My usage scenario is to send an extra parameter to the server when the user clicks the upload button.
But before that, all the parameters have been initialized, can not be changed, the problem is very troubled me, hoping to get help, very grateful!

**Comment by kartik-v** [comment]
You may want to read the documentation again.

You can send extra parameters via [uploadExtraData](http://plugins.krajee.com/file-input#option-uploadextradata) to the server.

Sending dynamic data at runtime can be achieved by setting [uploadExtraData](http://plugins.krajee.com/file-input#option-uploadextradata) as a JS callback function as explained in the doc example.

**Comment by haijiandong** [comment]
@kartik-v 
Thank you very much!
The problem has been solved.
