### ISSUE TITLE
Image uploader, formats file names when sending files to the server. Removes/replaces spaces and other special characters

### ISSUE THREAD

**Issue by avukonke** [kartik-v/bootstrap-fileinput#796]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Try to initiate upload of a file to the server
2. When receiving the file on the server, check if the filename (as per user uploaded file) is the same as the filename as received in the request "FileData/FileData[]" parameter.
3. The uploader inadvertently formats the image name. Removes spaces and other special characters, such as dashes and replaces them with the underscore character
4. This behaviour is unexpected and causes consistency issues as the filename changes it's naming convention, without allowing the user any level of customisation.
5. This causes an issue with referencing the saved images later as when user submits the form for further processing, the file_inputs values are equal to the filenames without any formatting rules implemented.

## Expected behavior and actual behavior

When I follow those steps, I see that the filename as sent to the server for ajax uploads is different from the file input values filename as received when a form submit is submitted.

I was expecting that the filename as sent for AJAX uploads is consistent with the filename (input value) when doing form submissions. Or at  least consistent set of rules between the 2 upload steps.

Rather I was expecting that the plugin respects user filename conventions and only removes special characters that are necessary for system functionality. An alternate solution is the url encoding of the filename and letting the user decode the filename on the server side and do their own filename processing. It seems that a consistent system/set of rules has not been implemented in this regard.

## Environment

Fedora 23, File Input v4.3.2, Pylons server v1.0

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: v2.0.3]
- bootstrap-fileinput version: v4.3.2

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is not an issue. You may read this in the documentation to understand all the options to control this. The plugin uses a slug callback to slugify the file name to remove special characters and prevent HTML markup being broken because of that OR script being injected.

You can override it by setting the `slugCallback` property to what you need but you need to manage these risks yourself.

Check for the [http://plugins.krajee.com/file-input#option-slugcallback] property in the plugin documentation.

**Comment by avukonke** [comment]
Noted. It's a bit hard to find in the documentation, there's lot's of options. But your answer solves my issue.

Thanks.
