### ISSUE TITLE
Access to response data in fileuploaded event

### ISSUE THREAD

**Issue by zebub** [kartik-v/bootstrap-fileinput#80]
Being able to send extra data from the server aside from errors would be useful.

**Comment by deepubrandoitte** [comment]
i adding some extra text field when uploading a image like http://doitte.com/test/bootstrap-fileinput-master/examples/index.php how can get the value of all field when we click upload button....please reply fast.

**Comment by maulanayusuf** [comment]
On uploadUrl i want to print a string like.

1. 001-success
2. 002-Success

i want to display that message when uploaded finished, i dont understand about event "fileUploaded" to get the message response.

Help me please, thank.

**Comment by matosjoao** [comment]
How can i access the data.response outside this function?

$('#input-id').on('filebatchuploadsuccess', function(event, data) {
    var formdata = data.form, files = data.files, 
        extradata = data.extra, responsedata = data.response;
    console.log('File batch upload success');
   /*Here i can access the data*/
});
/*Here i can't access the data*/ why?

**Comment by anandphulwani** [comment]
@matosjoao please read about `use` method and `&` operator which passes variable by reference.

$testvar = "";
$('#input-id').on('filebatchuploadsuccess', function(event, data) use (&$testvar) {
       $testvar = "hello";
}
echo $testvar //will print hello
