### ISSUE TITLE
Upload button clear errors

### ISSUE THREAD

**Issue by koxu1996** [kartik-v/bootstrap-fileinput#801]
This is not bug, rather unexpected behaviour. Reproduce:
1. Go to http://plugins.krajee.com/file-image-dimensions-demo#max-image-dimensions
2. Upload correct image and incorrect either:
![1](https://i.snag.gy/Zx8p4c.jpg)
3. Upload validated one and see that error disappeared:
![2](https://snag.gy/iVY4eI.jpg)

Additionally consider situation when somebody is using auto upload like [here](http://plugins.krajee.com/file-input-ajax-demo/6). Uploading incorrect files in no errors and no images, because `upload()` is immediately erasing them. What about changing this behaviour or adding property to disable it? If you want I would try to make PR, but this will be hard task for me.

**Comment by kartik-v** [comment]
This is an expected design... that the plugin only marks the thumbnails for the files that have faced validation error but allows successful upload of files that are good to go (when multiple file upload is enabled). Error messages are displayed though and errors will be appended in case more than one file faces errors. 

If you need error messages to persist you can try preventing the async upload and use `uploadAsync = false`.

**Comment by koxu1996** [comment]
Ok, if I create PR with property which disable this behaviour, will you merge it or I should create other workaround?

**Comment by kartik-v** [comment]
You can submit a PR... it should be generic and tested for all scenarios for it to work.

**Comment by kartik-v** [comment]
Closing this issue... you can open a new PR.
