### ISSUE TITLE
loading .msi files seems to hang / takes really long

### ISSUE THREAD

**Issue by f0nt4** [kartik-v/bootstrap-fileinput#806]
My upload works fine, but if someone selects a .msi file, it is really really slow.
It looks like it hangs on loading the file.
Is this because of the preview creation?
How can I prevent the creation of just .msi files?
Like this file, it's only 6MB and it takes minutes to process:
http://i.imgur.com/UAnamkk.png http://i.imgur.com/jpKI2eI.png
http://i.imgur.com/KlI0M0C.png
Finally uploaded: http://i.imgur.com/Sd2V2sa.png

This is plugin configuration I'm using:
http://i.imgur.com/yfCZFkk.png

**Comment by kartik-v** [comment]
You need to control display of preview using [showPreview](http://plugins.krajee.com/file-input#option-showpreview), if you do not need preview.

To selectively control preview for certain files. Configure [allowedPreviewTypes](http://plugins.krajee.com/file-input#option-allowedpreviewtypes). Check docs.

**Comment by f0nt4** [comment]
Hi Kartik,

Thanks for your fast answer.

I tried both of those settings, but showPreview just disables the whole preview area.
Using allowedPreviewTypes, I removed object from the list but this doesn't help.
Thing is, everything is working great, except for .msi files you can test this on the demo page by simply selecting a .msi file. You can even rename a .exe file to .msi to test it.

Also, is there an event which takes place after selecting a file and checking if it's extension/type is allowed?
I'm using filebatchselected right now, but this triggers before checking if it's allowed.
