### ISSUE TITLE
how can I get the response from the Server?

### ISSUE THREAD

**Issue by KeZhimin** [kartik-v/bootstrap-fileinput#807]
when i upload the image through this way,
![image](https://cloud.githubusercontent.com/assets/7068010/20619318/d8a233dc-b32e-11e6-951f-2d5ab4043d6f.png)
how can i get the response from the server? Is there a callback functon?

**Comment by kartik-v** [comment]
You may want to read the docs. This button just uses the same logic as for an asynchronous upload. [Here is how you can receive the response](http://plugins.krajee.com/file-input#async-receive) from the server for such a mode.
