### ISSUE TITLE
Images files duplicates, depends of select way of the images.

### ISSUE THREAD

**Issue by adrien-quillivic** [kartik-v/bootstrap-fileinput#811]
Hi,

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a input file multiple with fileinput option uploadAsync to true
2. Click on "Browse" and select one image file
3. Click again on "Browse" and select a second image file
4. Click on "Upload" and then go to the directory where files are saved.

## Expected behavior and actual behavior

When I follow those steps, I see my two files in my directory but they are the same.

I was expecting to see my two distinct files.

The weird part that make me think it's a bug is that when I select both files at first click on "Browse" and then hit "Upload", in my upload directory the two files are distinct, as expected in the first place.

My code sample is very brief. I work on ASP.NET Framework 3.5, VB language with VS 2008.
I have got two files Default.aspx and manageImage.aspx.

In Default.aspx I have : 

`<input id="inputImage" type="file" multiple />`

Followed by : 

```javascript
var extradata = {};
extradata["action"] = "upload";
$("#inputImage").fileinput({
    initialPreview: [],
    initialPreviewAsData: true,
    initialPreviewConfig: [],
    uploadUrl: "./ajax/manageImage.aspx",
    deleteUrl: "./ajax/manageImage.aspx",
    uploadAsync: true,
    maxFileCount: 6,
    validateInitialCount: true,
    overwriteInitial: false,
    language: "fr",
    previewFileType: "image",
    browseClass: "btn btn-info",
    browseLabel: "Sélection Image",
    browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
    removeClass: "btn btn-danger",
    removeLabel: "Supprimer",
    removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
    uploadClass: "btn btn-success",
    uploadLabel: "Importer",
    uploadIcon: "<i class=\"glyphicon glyphicon-upload\"></i> ",
    allowedFileExtensions: ["jpg","jpeg", "png", "gif", "bmp","JPG", "JPEG", "PNG", "GIF", "BMP"],
    maxImageWidth: 800,
    maxImageHeight: 600,
    resizePreference: "height",
    resizeImage: true,
    uploadExtraData: extradata,
    fileActionSettings: {
        dragIcon:"<i class=\"glyphicon glyphicon-move\" aria-hidden=\"true\"></i>"
    }
});
```

And my manageImage.aspx look like this : 

```VB
<%@ Page Language="VB" %>
<script runat="server">
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs)
        If Not String.IsNullOrEmpty(Request.Form("action")) Then
            If Request.Form("action") = "upload" Then
                PL_upload()
            End If
        End If
    End Sub
    
    Sub PL_upload()
        Dim vl_h_files As HttpFileCollection = Request.Files
        If vl_h_files.Count() = 1 Then
            Dim vl_s_files_key_name As String = vl_h_files.AllKeys(0)
            If vl_s_files_key_name = "file_data" Then
                Dim vl_h_image As HttpPostedFile = vl_h_files(0)
                vl_h_image.SaveAs("C:\Users\adrien.quillivic\Desktop\test_dev_asp\upload\image\" & CLng(DateTime.UtcNow.Subtract(New DateTime(1970, 1, 1)).TotalMilliseconds) & ".jpg")
            End If
        End If
        Response.AddHeader("Content-type", "application/json")
        Response.Write("{}")
    End Sub
</script>
```

It's been several weeks I work with this plugin and I wouldn't post this here if i wasn't that stuck. 

I hope I was clear despite that english is not my mother tongue.

Thanks.

## Environment

Browsers

- [x] Google Chrome (Version 55.0.2883.75 m)
- [x] Mozilla Firefox ( Version 50.0.2)
- [ ] Internet Explorer (Version 11.0.9600.18524)
- [ ] Safari

Operating System

- [x] Windows  (7 professional service pack 1)
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- bootstrap-fileinput version : 3.3.7

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by adrien-quillivic** [comment]
Hi,

```javascript
var extradata = {};
extradata["action"] = "upload";
$("#inputImage").fileinput({
    initialPreview: [],
    initialPreviewAsData: true,
    initialPreviewConfig: [],
    uploadUrl: "./ajax/manageImage.aspx",
    deleteUrl: "./ajax/manageImage.aspx",
    uploadAsync: true,
    maxFileCount: 6,
    validateInitialCount: true,
    overwriteInitial: false,
    language: "fr",
    previewFileType: "image",
    browseClass: "btn btn-info",
    browseLabel: "Sélection Image",
    browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
    removeClass: "btn btn-danger",
    removeLabel: "Supprimer",
    removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
    uploadClass: "btn btn-success",
    uploadLabel: "Importer",
    uploadIcon: "<i class=\"glyphicon glyphicon-upload\"></i> ",
    allowedFileExtensions: ["jpg","jpeg", "png", "gif", "bmp","JPG", "JPEG", "PNG", "GIF", "BMP"],
    //maxImageWidth: 800,
    //maxImageHeight: 600,
    //resizePreference: "height",
    //resizeImage: true,
    uploadExtraData: extradata,
    fileActionSettings: {
        dragIcon:"<i class=\"glyphicon glyphicon-move\" aria-hidden=\"true\"></i>"
    }
});
```

By commenting those configuration line in declaration of the plugin, the issue doesn't seem to occur again.

I still think it's a plugin bug probably located in the resize.

Anyway, this has solved my issue.

Thanks again for that great plugin.

**Comment by kartik-v** [comment]
Can you check with the latest release v4.3.9 from dev-master branch and confirm?

**Comment by blacko2017** [comment]
@kartik-v  i tested 4.3.9 and it still has duplicates, it seems like Multiple Upload button fires the InitReplace twice

**Comment by kartik-v** [comment]
Ok I think this is duplicate to #890 and I will try to address it through a fix there. Closing this.
