### ISSUE TITLE
Document error for maxFilePreviewSize!

### ISSUE THREAD

**Issue by yxkemiya** [kartik-v/bootstrap-fileinput#813]
I think the option to control max preview size should be `maxFilePreviewSize`, I found it from the [code](https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js#L3242) instead of `maxPreviewFileSize` in the  [document](http://plugins.krajee.com/file-input#option-maxfilesize).

I have tested both options in my project, `maxPreviewFileSize` don't work at all, but `maxFilePreviewSize` works as expected.

**Comment by kartik-v** [comment]
This is been corrected in docs.
