### ISSUE TITLE
initialPreview and Tabs

### ISSUE THREAD

**Issue by cgi-cgi** [kartik-v/bootstrap-fileinput#815]
Hi. Thanks to you for the plugin :)
But I have a problem with latest 4.3.6 version when using it with tabs (for example bootstrap). 
For example, fileupload plugin initialized with **initial preview files** and **in element** which **_currently_** hidden in tab. But jquery with :visible selector seems can't to catch preview elements for attaching some event handlers. 

Tab inactive - https://jsfiddle.net/bjdomn08/11/ - not working (click on "delete" file, nothing happens)
Tab active - https://jsfiddle.net/bjdomn08/12/ - working (click on "delete file, request for deletion happens)

If I remove only **:visible** selector from **.file-preview-frame, .kv-file-remove, .file-preview-success, .kv-file-upload** classes - it works fine (as it was in previous versions <4.3.6)
(temporarily) 
https://github.com/cgi-cgi/bootstrap-fileinput/commit/9a1cd71768fc470d586757875532704bd6b59e42
https://github.com/cgi-cgi/bootstrap-fileinput/commit/c2ac1c4d73021f8917bb3feae9359b52d837f87e

**Comment by kartik-v** [comment]
Try to initialize the plugin on click / show of the tab - rather than on document ready.

**Comment by wat4dog** [comment]
First of all: thanks for all your plugins :) @kartik-v 

IMHO, it's better to remove `:visible` from this line. It worked okay in version 4.3.5, and in version 4.3.6 `:visible` selector added, and of course, if fileinput is not visible on document loading, it won't work. 

To re-init plugin, required to setup additional hooks (tab switching, etc), but w/o `:visible` selector it's not required at all. I'm not lazy, just surprised, when it stopped to work after months. Any real purpose to use visibility check here?

https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js#L1375

**Comment by kartik-v** [comment]
Enhanced to include this ability now to render in tabs.
