### ISSUE TITLE
Localization of fileTypeSettings

### ISSUE THREAD

**Issue by kikonen** [kartik-v/bootstrap-fileinput#816]
Q: How to localize fileTypeSettings?

Thus when file type doesn't match, it seems that widget is showing internal name (ex. "image") for mismatch. Is there way to specify localized names for file types?

**Comment by kartik-v** [comment]
Potential enhancement.

**Comment by kartik-v** [comment]
Resolved via [this commit](https://github.com/kartik-v/bootstrap-fileinput/commit/0965a25f5593c1cd8e4e2c310a22ec15e774f208). New property `msgFileTypes` controls the user friendly description or localized version for file types.
