### ISSUE TITLE
Help for filecustomerror, if possible.

### ISSUE THREAD

**Issue by luizeduardots** [kartik-v/bootstrap-fileinput#817]
Good afternoon Kartik,

At first, congratulations for this amazing plugin. (and i´m sorry for bad english)

Well, i´m trying do make use of filecustomerror on this situation.. on filepreupload function i do a search
on db verifying if there´s a number x of photos saved.

If yes, so i return a message to the user to choose which does he want delete

I´ve tried to put some jquery code within the example from github but with no success.
I´m also making use of codeigniter mvc framework.

Oh and i´m doing an "async false" upload
Here it is...

$('#input-pt-br').on('filepreupload', function(event, data) {
        $.ajax({
            url : 'controller/method', 
            dataType : 'json',
            type : 'post',
            success : function(data){                
                if(data === 'more than 5 photos'){
                    return {
                        message: 'You´re already on limit',
                        data: {key1: 'Key 1', detail1: 'Detail 1'}
                    };
                }else{
                    alert('erro');
                }
            }
        });
    });

$("#input-pt-br").on('filecustomerror', function(event, params, msg) {
        //here goes 3 tries to show up the message
        $('#div to return').html(params.data);
        $('#div to return').html(msg);
        alert(params.abortData);
    });

Please Mr. Krajee, if you or any friend from github can help me, i´ll be very pleased.
Since now, thanks.

**Comment by kartik-v** [comment]
Your `filepreupload` event must directly return some data to be processed by `filecustomerror` and not within another ajax op

```js
$('#input-pt-br').on('filepreupload', function(event, data) {
if (data === 'more than 5 photos'){
    return {
        message: 'You´re already on limit',
        data: {key1: 'Key 1', detail1: 'Detail 1'}
    };
});
```
