### ISSUE TITLE
Allow drag & drop without ajax.

### ISSUE THREAD

**Issue by SamMousa** [kartik-v/bootstrap-fileinput#818]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Use a file input widget (i'm using this via the yii2 widget), without AJAX.
2. Try drag & drop.

## Expected behavior and actual behavior

The expected behavior is that drag * drop does not work since it requires AJAX.

## Desired behavior

I do not see how drag & drop as a method for file selection has anything to do with AJAX (which is in this case a method for the file transfer).
Is there a reason to not allow drag & drop when using regular file uploads via the form?

**Comment by SamMousa** [comment]
Did some more research; the primary reasons for using AJAX seems to be allowing the removal of individual files from the upload and appending files to the form.


## Scenario 1: Unselecting files.
- Dropping 10 files.
- Unselecting 1 file.
This is not possible currently via the API, it is also not technically what happens with AJAX, since all files are uploaded.

Workaround is to simply upload them all but mark the deleted ones as irrelevant. This would not be visible to the user.

## Scenario 2: 
- Drop  5 files.
- Drop 5 more files.

Workaround is to add a new (hidden) file input for each drop action. Again this does not have to be visible for the user.


Scenario 2 does not require any changes to the server side code; scenario 1 does require the server side code to ignore some files.

**Comment by kartik-v** [comment]
No... the above are just secondary reasons.

The primary reason for using AJAX mode for drag and drop is that you cannot manipulate or populate native HTML file input using external script or javascript. So any dragged and dropped files into the zone cannot be populated in the file input and hence you will not receive any data on your HTML form submit.

**Comment by SamMousa** [comment]
@kartik-v You can actually set the file input to the result of the drag and drop operation.

https://jsfiddle.net/w4rrkrdL/7/

**Comment by kartik-v** [comment]
Do not think the above is a browser standard (since assigning value to a native HTML file input is blocked by browsers for security reasons) - have you tried it on IE for example?

**Comment by kartik-v** [comment]
I am opening this issue for any enhancement suggestions though.

**Comment by SamMousa** [comment]
Will do!

**Comment by kartik-v** [comment]
Currently closing this as not fixable.
