### ISSUE TITLE
Doubled image when uploading by clicking icon button

### ISSUE THREAD

**Issue by koxu1996** [kartik-v/bootstrap-fileinput#819]
## Reproducing issue

1. Create fileinput with upload: `$("#input-id").fileinput({'uploadUrl':'/event/upload-image2'});`
2. Select image: 
![](https://i.snag.gy/OJozdH.jpg "1")
3. Upload by clicking icon beyond image preview: 
![](https://i.snag.gy/2YJ4Rq.jpg "2")
4. Image appear twice: 
![](https://i.snag.gy/VCmgBN.jpg "3")

This issue is caused because of this commit https://github.com/kartik-v/bootstrap-fileinput/commit/01482ac4bedcc4b3ecdfda804ca8085557a7b912

**Comment by kartik-v** [comment]
Cannot reproduce the issue.

Hope you have the correct version of the assets (JS/CSS) and you are not having caching issues? Also if you are writing your own javascript or third party plugins to tweak the output - you may need to check your code.

You can cross check with demos page like [this example](http://plugins.krajee.com/file-input-ajax-demo/1) to upload a file by clicking on the icons.

**Comment by koxu1996** [comment]
I forgot to mention that server must return `initialPreview` with `initialPreviewConfig`. Check this [https://jsfiddle.net/LL5250dc/1/](fiddle)

**Comment by stuartcusackie** [comment]
I am getting this problem today. Using version 4.3.6 (4.3.7 is not available on npm)

Many thanks for the package!
