### ISSUE TITLE
Cannot rearrange files uploaded by clicking upload icons.

### ISSUE THREAD

**Issue by koxu1996** [kartik-v/bootstrap-fileinput#828]
## Steps to reproduce the issue

1. Select images
2. Upload by clicking upload icon under each thumbnail
3. You cannot rearrange image, although drag icon is avaliable.

## Cause
sortable.js is looking for $(".file-preview-thumbnails .file-initial-thumbs"), but single uploaded images are in $(".file-preview-thumbnails .file-initial-thumbs"). I think they should be moved to `div.file-initial-thumbs`.

**Comment by kartik-v** [comment]
Yes the problem will be that all such images need to be in ONE single container with `file-initial-thumbs` class.

It will cause some UI problems. This means with the above change when clicking upload the uploaded images derived in initial preview will move to one container and that will cause a UI problem as if you have 5 thumbnails and you upload IMAGE_1 and IMAGE_5 via single upload button, then IMAGE_1 and IMAGE_5 will be moved to beginning within `file-initial-thumbs` with init preview, while IMAGE_2, IMAGE_3, and IMAGE_4 will appear after that.

I presume, that the sortable for such case should not be enabled until someone refreshes the page and the initial preview is derived based on the way the server sends it.

**Comment by kartik-v** [comment]
I think I will solve this with another workaround code. Will update.
