### ISSUE TITLE
preview overwrite

### ISSUE THREAD

**Issue by mohammad6006** [kartik-v/bootstrap-fileinput#832]
I have a problem in that, suppose I have to upload 4 files from 4 different folder in one go, so I have to select files one by one from 4 different folders and it is overwriting the old image when I select image from other folder. Can you please tell me how to do that?

its like this demo
http://plugins.krajee.com/file-basic-usage-demo#basic-example-3

**Comment by kartik-v** [comment]
You have to use ajax mode for that ... read about [plugin usage modes in docs](http://plugins.krajee.com/file-input#usage-modes).
