### ISSUE TITLE
The image zoom has not updated when chose for another image.

### ISSUE THREAD

**Issue by pompeina** [kartik-v/bootstrap-fileinput#834]
Hi,
I faced a problem when using the fileinput today. First time I chose a image by clicked on Browse button, then clicked on zoom icon, the modal popup displayed with the image and its info. But after that when I chose for another image, clicked on zoom icon, the old image still appeared, not the new one.
Of course you can remove the old image before choosing a new one, then zoom image will be ok. But I want the user just only need to browse for it. So Can you please tell me how to do that?
Any help or suggestions would be appreciate.

P.S: this is single image file input situation.

**Comment by kartik-v** [comment]
Confirmed for single file upload... will check and update.
