### ISSUE TITLE
Fixed Polish translation v1.0.

### ISSUE THREAD

**Issue by Lesenus** [kartik-v/bootstrap-fileinput#835]
## Prerequisites

- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.

## Steps to reproduce the issue

1. Translation like translate.google.com

## Expected behavior and actual behavior

Operating System
- [x] Windows

**Fix file for js/locales/pl.js**
[pl.zip](https://github.com/kartik-v/bootstrap-fileinput/files/693720/pl.zip)

**Comment by kartik-v** [comment]
Please submit a PR.
