### ISSUE TITLE
upload file to upload url "error"

### ISSUE THREAD

**Issue by B1LIE** [kartik-v/bootstrap-fileinput#842]
please help me,... i am struggling with this plugin.
i have tried many times to follow the instruction in ajax upload.
i always get the message : "SyntaxError: Unexpected token < in JSON at position 0." when i press upload file button. 
probably i didn't guite get that. 

thank you

**Comment by kartik-v** [comment]
Yes you need to go through the [documentation and usage](http://plugins.krajee.com/file-input#usage) to understand how to use the plugin for ajax mode and what the server must send and receive data (as JSON format).

You can also [refer this webtip](http://webtips.krajee.com/question/json-syntax-error-bootstrap-fileinput/) on why developers face this issue.
