### ISSUE TITLE
Need to get all files in upload URL function

### ISSUE THREAD

**Issue by mohammadsj** [kartik-v/bootstrap-fileinput#853]
If I use initialPreview to show existing images and then add a new image, when uploading, I get only one file (the new one I just added) in the upload function. 
I like to get all images in the upload function, because in my scenario, I want to delete all images from database and add them all when user saves the form 
I believe this might be a common case.

**Comment by kartik-v** [comment]
You need to set uploadExtraData to pass any extra data to your upload server action. You can read this in docs and it can be passed as an object of key val pairs or as JS callback function also to send dynamic data.
