### ISSUE TITLE
Audio file duration

### ISSUE THREAD

**Issue by Pauldic** [kartik-v/bootstrap-fileinput#855]
It will be nice to have feature adding a method that can read the file duration for audio/video upload. HTML5 already has this feature with js `canplaythrough ` event. However, I could not access this event while I am using this plugin even though the plugin is aware of the file duration

**Comment by kartik-v** [comment]
You can use the `fileloaded` event and call the above `canplaythrough` event within that - check the docs for `fileloaded` event parameters.
