### ISSUE TITLE
hope to use only preview function

### ISSUE THREAD

**Issue by wenbaofu** [kartik-v/bootstrap-fileinput#863]
@kartik-v :+1:  At first, thanks for your great component, I had used it in my demo (bootstrap-fileinput + nodeJS + Angular2),now it work fine.

I want to use preview function of fileinput in Angular2(because I had upload into server,user can check the file in new page,then they can preview the video and PDF),like below

![image](https://cloud.githubusercontent.com/assets/20511885/22627029/08c9be78-ebf5-11e6-8d66-925a03a6eae8.png)

for PDF, I want to use preview in red part,and like what show in file-input
![image](https://cloud.githubusercontent.com/assets/20511885/22627035/3cc3f2b6-ebf5-11e6-86f1-72b6e85f03ab.png)

so if there is any simple way to just use this function,pls tell me,thank you...

**Comment by wenbaofu** [comment]
I had red source code,I find below function will handle the click event,and the create the page of preview
```
_initZoomButton: function () {
            var self = this;
            self.$preview.find('._initZoomButton: function () {
            var self = this;
            self.$preview.find('.kv-file-zoom').each(function () {
                var $el = $(this);
                handler($el, 'click', function () {
                    self._zoomPreview($el);
                });
            });
        },').each(function () {
                var $el = $(this);
                handler($el, 'click', function () {
                    self._zoomPreview($el);
                });
            });
        },
```

if Ｉshould add a button in my page with class "kv-file-zoom" ?

**Comment by kartik-v** [comment]
It must be a button inside each preview thumbnail with class `.kv-file-zoom` currently. Will update later if there is a enhanced method to do this.

**Comment by kartik-v** [comment]
New plugin method [`zoom`](http://plugins.krajee.com/file-input#method-zoom) is available to preview content for a specified frame id.
