### ISSUE TITLE
How to remove button "Upload" from bar?

### ISSUE THREAD

**Issue by Ron60** [kartik-v/bootstrap-fileinput#866]
Great module; working fine.
I want to use it in a form with additional (text) fields. The button "Upload" in the bar of the file-selector, might than be confusing. Therefore I want to remove this button and at the bottom of the form just showing the regular 'submit' button.
How can I disable or remove the button "Upload"?
![bar](https://cloud.githubusercontent.com/assets/25707335/22854556/6d7b3d08-f071-11e6-9ec9-e88fcbe45673.png)

**Comment by kartik-v** [comment]
Have you read the docs? All plugin options are covered there.

You can configure display of the upload button for example by setting the [showUpload](http://plugins.krajee.com/file-input#option-showupload) property.
