### ISSUE TITLE
Txt file is not loading in Initial Preview Data

### ISSUE THREAD

**Issue by roberto910907** [kartik-v/bootstrap-fileinput#867]
First of all sorry for my english, I'll try to be concise in order to solve my doubt.

I'm trying to show an uploaded txt file and I'm getting the url instead of the file content, it works with any other filetype(video, pdf, image).

What's wrong in my code?
First of all sorry for my english, I'll try to be concise in order to solve my doubt.

I'm trying to show an uploaded txt file and I'm getting the url instead of the file content, it works with any other filetype(video, pdf, image).

What's wrong in my code?
![script](https://cloud.githubusercontent.com/assets/12180771/22858730/b4241028-f093-11e6-9895-c0fcce9c941b.png)

And the txt is reachable if I paste the url in the browser, if I change the url of the txt for a pdf or image url for example it works fine.

![imagen](https://cloud.githubusercontent.com/assets/12180771/22858716/69694dbe-f093-11e6-9b64-e669ea32c482.png)

Any help will be appreciated. Thanks.

**Comment by kartik-v** [comment]
For text you have to add the content of the text file itself (Not the URL).
