### ISSUE TITLE
bootstrap-fileinput with django framework

### ISSUE THREAD

**Issue by sandeshnaroju** [kartik-v/bootstrap-fileinput#868]
I am trying to use this library with Django python framework. I need to pass csrf_token via headers to submit the file via ajax to the server. Where should I put csrf_token? In general I used to pass as a header in ajax method in jquery. Now I don't understand where should I have include csrf_token. Do I have to put in `fileinput`?

**Comment by kartik-v** [comment]
You can include it in `uploadExtraData` that can be received via the POST to your `uploadUrl` server action.

**Comment by wdcxc** [comment]
I found these code work out
`
$("#uploadImage").fileinput({
            ajaxSettings:{
                beforeSend: function(xhr, settings) {
                    if (!this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken-cookie);
                    }
                }
            },
        });
`

**Comment by pt12lol** [comment]
@wdcxc even not getting it from cookie, calling `$('[name="csrfmiddlewaretoken"]').val()` is all we need.

**Comment by AlexXiong97** [comment]
@pt12lol Could you please elaborate a bit more on your solution please? what should I include in my jQuery to pass the csrf_token validation? Thanks!

**Comment by pushpashu** [comment]
@wdcxc @pt12lol @kartik-v i am also trying this way mentioned 
$("#uploadImage").fileinput({
            ajaxSettings:{
                beforeSend: function(xhr, settings) {
                    if (!this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken-cookie);
                    }
                }
            },
});

but not able to see the header in the request. rather strange div class="file-loading">
                <input id="fileUpload" class="file" type="file" multiple data-preview-file-type="any" data-upload-url="http://127.0.0.1/apis/upload">
            </div> 
is not calling $(#"fileupload") function...

can you help with an example here...
