### ISSUE TITLE
How to save multiple files

### ISSUE THREAD

**Issue by Ron60** [kartik-v/bootstrap-fileinput#869]
I'm sorry. I studied the manual, but couldn't find the answer to my problem (or looked over it).
I have a form with the Krajee bootstrap-fileinput.

Parts of my form page:
<head>
		<link href="./css/fileinput.css" media="all" rel="stylesheet" type="text/css"/>
		<script src="./js/canvas-to-blob.js" type="text/javascript"></script>
		<script src="./js/fileinput.js" type="text/javascript"></script>
		<script src="./js/nl.js" type="text/javascript"></script>
</head>
And as part of the form:
	<input id="images" name="files[]" class="file file-loading" accept="image/*" type="file" multiple="multiple" data-min-file-count="1">
						<script>
							$("#images").fileinput({
								 language: "nl",
								 showUpload: false,
								 resizeImage: true,
								 maxImageWidth: 200,
								 maxImageHeight: 200,
								 resizePreference: 'width',
								 maxFileCount: 4,
								 validateInitialCount: true,
								 overwriteInitial: false,
								 initialPreviewAsData: true,
								 allowedFileExtensions: ["jpg", "png", "gif"]
							});
						</script>

In my 'action page' I get the names of the selected files with:
      print_r(array_values($_POST['files'])).'</br>';
However, when I try to save the files with 'move_uploaded_file(), I have no response.
Testing, I noticed that with
      if(isset($_FILES['files'])){ }
there is no response; no files found.

PS: A regular multiple file upload as described in http://php.net is working.
Question: how to setup the receiving page to save the files to a defined folder?

**Comment by kartik-v** [comment]
This is entirely to do with your server code... in PHP you would typically receive the files in `$_FILES` based on the name of the native file input in your markup. So for multiple files if your input markup is:

```html
<input type="file" name="myInput[]" multiple> 
```

then in PHP server code you would get the list of files under `$_FILES['myInput']`  ... 

PS: Please post such programming queries and generic help in future outside this repo on the [webtips forum](http://webtips.krajee.com) OR in comments section of the plugin
