### ISSUE TITLE
maxFileCount doesn't add files already uploaded

### ISSUE THREAD

**Issue by Lin510** [kartik-v/bootstrap-fileinput#871]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.goto http://plugins.krajee.com/file-input-ajax-demo/3
2.click browse and add 5 images
3.click upload

## Expected behavior and actual behavior

I was expecting Number of files selected for upload (7) exceeds maximum allowed limit of 5.
Or maybe i am wrong about what maxFileCount should do.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Yes your understanding of maxFileCount is not correct.

`maxFileCount` validates maximum number of files from client that you can select from the uploader before upload. It does not understand or validate files you have previously uploaded

**Comment by kartik-v** [comment]
If you need to include the previously uploaded files in validation of `maxFileCount` and `minFileCount` as well.. you need to set [validateInitialCount](http://plugins.krajee.com/file-input#option-validateinitialcount) property to `true` and then supply these files as data in `initialPreviewConfig`.

**Comment by Lin510** [comment]
validateInitialCount did the job.
Number of files selected for upload (5) exceeds maximum allowed limit of 4.
Thank you
