### ISSUE TITLE
error in fileinput.min.css

### ISSUE THREAD

**Issue by ramakrishnamundru** [kartik-v/bootstrap-fileinput#872]
it's not an issue with the file input but the min.css file has a mistake.

there is a word  
`.btn-file ::-ms-browse{width:100%;height:100%}owed}`

the `owed}` is not in the main css file but it is in the min.css file. can you please take a look at it..

**Comment by kartik-v** [comment]
Not sure this is correct. The [file looks good here](https://github.com/kartik-v/bootstrap-fileinput/blob/master/css/fileinput.min.css).

**Comment by ramakrishnamundru** [comment]
It is there. try searcing for owed once in the min file.

![issue](https://cloud.githubusercontent.com/assets/23165864/22929742/2f02d36e-f2e3-11e6-984b-72ebff148086.png)
