### ISSUE TITLE
Files Count with initialPreview

### ISSUE THREAD

**Issue by ruchisheth** [kartik-v/bootstrap-fileinput#880]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Show 2 files as initialPreview
2. $("#invoice_attachments").fileinput("getFilesCount");
3. it returns 0 as count of files instead 2

## Expected behavior and actual behavior

When I follow those steps, I see... count of total files selected 0

I was expecting... it will going to show 2

same issue with $("#invoice_attachments").fileinput("getFileStack");
it returns blank array instead of array of two

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is expected... - `getFileStack` will only return blobs uploaded from client as well as `getFilesCount`

Since you as a developer is setting `initialPreview` from your server code yourself -- you should have the data with you including the file count and files. You just need to add this data to the `getFilesCount` to get total files for example.

**Comment by xtremescorpio** [comment]
i have an issue, i have 2 files in initial preview, then add 1 file
getFilesCount = 1
then delete 1 file fromo initial preview
and then getFilesCount = 0
when i do ajax upload $_FILES have 0 files
What can i do ?
