### ISSUE TITLE
Local video preview

### ISSUE THREAD

**Issue by zxy198717** [kartik-v/bootstrap-fileinput#883]
1. Open Url `http://plugins.krajee.com/file-preview-management-demo`.
2. Select one local mp4 file.
3. Cannot preview(play) this video file.

Does it support local mp4 preview?
Just like: `http://jsfiddle.net/dsbonev/cCCZ2/presentation/`

**Comment by kartik-v** [comment]
Yes depending on the browser's HTML5 video playback support and capability - local videos playback will be supported.

**Comment by pawansgi92** [comment]
I am uploading the video i am able to play the video but no preview is showing

**Comment by juanAFernandez** [comment]
I have the same issue yet.
