### ISSUE TITLE
Bootstrap-FileInput inside modal with problem event of shown.bs.modal

### ISSUE THREAD

**Issue by matmiranda** [kartik-v/bootstrap-fileinput#886]
I am facing the modal problem. Event Type of shown.bs.modal passes 2 times on line:

```
$('#myModal').on('shown.bs.modal', function(e) {   <----- Pass 2 times
  alert("alert");
})
```
Here it is in jsfiddle: https://jsfiddle.net/DTcHh/30285/

Removing bootstrap-file input plugin works fine and passes 1 time on line:

```
$('#myModal').on('shown.bs.modal', function(e) { <-----Pass 1  time
  alert("alert");
})
```

Any solution ?

**Comment by kartik-v** [comment]
This is because of the duplicate modal dialog also generated by bootstrap file input for modal preview... will provide an enhancement fix and solution.

**Comment by matmiranda** [comment]
@kartik-v When does the new improvement come out? It has forecast ?

**Comment by kartik-v** [comment]
In this week

**Comment by matmiranda** [comment]
@kartik-v I'm using version v4.3.9 and problem continues
