### ISSUE TITLE
Setting delete button with no initialPreviewConfig setting

### ISSUE THREAD

**Issue by carlos0202** [kartik-v/bootstrap-fileinput#889]
Not able to configure fileinput to show remove button using simple form submission mode and multiple fileupload.

**Comment by kartik-v** [comment]
Yes that is expected for client files not yet uploaded for form based uploads. Read the [usage modes section](http://plugins.krajee.com/file-input#usage-modes) in the documentation on what is possible in form based mode and ajax based mode.
