### ISSUE TITLE
Images are doubled again..

### ISSUE THREAD

**Issue by koxu1996** [kartik-v/bootstrap-fileinput#890]
**Simple reproduce:**
1. Open [fiddle](https://jsfiddle.net/xtckz3jz/ )
2. Select one image or more
3. Click main upload button
4. You will see 2x more images than you selected

**Comment by kartik-v** [comment]
Can you check with latest release v4.3.9 and submit a fiddle if its not working?

**Comment by koxu1996** [comment]
Still not working: [fiddle](https://jsfiddle.net/andrzej1_1/rdxbyr5a/)

**Comment by blacko2017** [comment]
Same problem here with 4.3.9

**Comment by blacko2017** [comment]
@kartik-v  I don't know if this can help you but I fixed it using this on the input element:

$(this).closest('.file-input').find('.fileinput-upload').unbind('click').click(function(e){
                    e.preventDefault();
                    
                    $(this).closest('.file-input').find('.file-preview .kv-file-upload').click();
                });

Which simple clicks each upload button

**Comment by koxu1996** [comment]
@blacko2017 this is temporary workaround and wont help. I will find commit which caused this problem and let know.

**Comment by kartik-v** [comment]
This is resolved now.... you may check and update.

**Comment by blacko2017** [comment]
I confirm, it works.

2017-03-07 12:17 GMT+01:00 Kartik Visweswaran <notifications@github.com>:

**Comment by blacko2017** [comment]
@kartik-v  Now there is a new problem. If you click Multiple upload button on a non-multiple file, the removeInitial does not work.
1. You have an image for initialPreview and you set removeInitial true;
2. You select another image, the initialPreview disappears;
3. You press Upload and the first initial preview appears again.
