### ISSUE TITLE
Cannot read property '$errorContainer' of undefined

### ISSUE THREAD

**Issue by koxu1996** [kartik-v/bootstrap-fileinput#891]
**Simple reproduce:**
1. Open [fiddle](https://jsfiddle.net/zrdmg30u/)
2. Select one image or more
3. In console you will see error:
```Uncaught TypeError: Cannot read property '$errorContainer' of undefined```

**Comment by kartik-v** [comment]
This is fixed in v4.3.9 of plugin (take it from the master branch).
