### ISSUE TITLE
No validation error raised when using allowedFileTypes

### ISSUE THREAD

**Issue by daryllukas** [kartik-v/bootstrap-fileinput#897]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Specify plugin option `allowedFileTypes`
```js
<script>
        $("#song-file").fileinput({
            allowedFileTypes: ['audio']
        });
</script>
```
2. Upload a file which doesn't belong to the specified `allowedFileTypes`

## Expected behavior and actual behavior

When I follow those steps, I see no errors

I was expecting the default error message `msgInvalidFileType`:
```
Invalid type for file "{name}". Only "{types}" files are supported.
```
However, when I use the option `allowedFileExtensions` instead, I get the `msgInvalidFileExtension` as expected. I'm not sure why it doesn't behave the same way with `allowedFileTypes`.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- bootstrap-fileinput version: 4.3.8

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is fixed in v4.3.9 ... get this release from master branch currently - it will be tagged later.
