### ISSUE TITLE
server return json data {error: "message"}, the preview‘s style and word is true?

### ISSUE THREAD

**Issue by joker-pper** [kartik-v/bootstrap-fileinput#904]
![error-file-input](https://cloud.githubusercontent.com/assets/20161452/23933350/f652d59e-0978-11e7-9c13-a991c92d7dbc.png)

server return json data {error: "message"}, the preview‘s style and word is true?

**Comment by dtkper** [comment]
why i can't find history version in http://plugins.krajee.com/file-input

**Comment by kartik-v** [comment]
Not sure if I can understand or reproduce your issue. Ensure you have updated to the latest plugin version, and then retry. If still facing an issue - please share a JS Fiddle to reproduce your issue and will reopen this issue (currently closing this).
