### ISSUE TITLE
Can I remove the upload icon of the selected pic's thumbnail?

### ISSUE THREAD

**Issue by yqgz** [kartik-v/bootstrap-fileinput#907]
I use ajax method to upload pictures, so I give the "uploadUrl" in fileinput(). 
Then, after I selected a picture, the preview has upload icon below. But I don't want user to upload files,because I'll upload them later, by using fileinput('upload'). 
How can I keep the upload icon on thumbnail not show?

**Comment by kartik-v** [comment]
Read plugin documentation and about [fileActionSettings](http://plugins.krajee.com/file-input#option-fileactionsettings).

You can prevent upload icon display in thumbnail by setting `fileActionSettings['showUpload']` to `false`.
