### ISSUE TITLE
When my file size is greater than a certain value, only resize, how to set up, thanks

### ISSUE THREAD

**Issue by 298029lkk** [kartik-v/bootstrap-fileinput#910]

**Comment by 298029lkk** [comment]
.on("filebatchselected", function (event, files) {
            console.log(files);
            if (files[0].size < 1024 * 1000) {
                $(this).fileinput({
                    resizeImage: false,
                });
                $(this).fileinput("upload");
            } else {
                $(this).fileinput({
                    resizeImage: true,
                });
            }
}).on('fileimageresized', function (event, previewId, index) {
            $(this).fileinput("upload");
})
---------------------------------------
Is there any advice?

**Comment by 298029lkk** [comment]
`.on("filebatchselected", function (event, files) {
console.log(files);
if (files[0].size < 1024 * 1000) {
$(this).fileinput({
resizeImage: false,
});
$(this).fileinput("upload");
} else {
$(this).fileinput({
resizeImage: true,
});
}
}).on('fileimageresized', function (event, previewId, index) {
$(this).fileinput("upload");
})`

------------------------------
Is there any advice?

**Comment by kartik-v** [comment]
New property [resizeIfMoreThan](http://plugins.krajee.com/file-input#option-resizeifmorethan) added. Set this value in KB and the plugin will automatically skip the resizing of these image files less than this size value.

Check the [image resize (conditional) demo](http://plugins.krajee.com/file-image-management-demo#image-resize-conditional) for understanding.

**Comment by 298029lkk** [comment]
cool! thank you!
