### ISSUE TITLE
Image didn't resized after uploaded once

### ISSUE THREAD

**Issue by Sharuru** [kartik-v/bootstrap-fileinput#912]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Setting fileinput with:
```json
resizeImage: true,
maxImageWidth:150,
resizeOreferebce: 'width',
resizeImageQuality: 0.7
```

2. Upload an image(A.jpg).
3. After `Done`, keep the page open, add another image(B.jpg) using `Browse` button and press `Upload`.

## Expected behavior and actual behavior

When I follow those steps, I see the second image(B.jpg) isn't resized.
Also, the `fileimageresized` event isn't triggered when adding the second image.

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.0
- bootstrap-fileinput version: 4.3.9

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-fileinput without other plugins
- [X] I can reproduce this bug in [my repo](https://github.com/Sharuru/simple-file-hosting/tree/0d155bf6e63cc0a58f8d8dd0b09d29bd095c48f6)
- Detail file link is [here](https://github.com/Sharuru/simple-file-hosting/blob/0d155bf6e63cc0a58f8d8dd0b09d29bd095c48f6/src/main/resources/templates/index.html#L55-L70)

**Comment by kartik-v** [comment]
Cannot reproduce your issue.

Can you cross check the [image management and resize handling demo](http://plugins.krajee.com/file-image-management-demo) on the plugins page and try to upload various images and check the resized images.

**Comment by Sharuru** [comment]
All right, after investigating, I found the answer.

A little change was made to `fileinput.js` just one day ago.
Link is here: https://github.com/kartik-v/bootstrap-fileinput/commit/5515c0fca85a8f2637243272f740ab1d0c67a8ab

I've confirmed that this change fixed the problem.

What coincidence 🥂
