### ISSUE TITLE
bootstrap-fileinput exception handling

### ISSUE THREAD

**Issue by hitesh279** [kartik-v/bootstrap-fileinput#916]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.I am using fileinput.js for file uploading process I am stuck in a place. I am trying to upload a file but in my java side it gives exception but in UI side it still shows in running condition ,so my question is how to handle this situation where to show user that exception occurred and show the progress bar as failed.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Read the [ajax uploads](http://plugins.krajee.com/file-input#ajax-uploads) section of the documentation.

You can send an error from your server via a json response as described in these sections

- For [async uploads](http://plugins.krajee.com/file-input#async-send)
- For [sync uploads](http://plugins.krajee.com/file-input#sync-send)

**Comment by hitesh279** [comment]
Hi Kartik ,
     Thanks for the reply.My only concern is in the response I got error as
an attribute. But it is not catch by the filebatchuploaderror and fileerror
and also I did change uploadAsync as false and true accordingly.It does not
work can you please suggest something on this.

Regards,
Hitesh

On Tue, Apr 4, 2017 at 2:26 PM, Kartik Visweswaran <notifications@github.com

**Comment by hitesh279** [comment]
![filebatchupload](https://cloud.githubusercontent.com/assets/25635355/24708372/42085218-1a34-11e7-99e1-4f5d8671ff2a.png)

**Comment by kartik-v** [comment]
No it should trigger `filebatchuploaderror` or `fileuploaderror` depending on from where you triggered upload when you receive an `error` data in JSON response from server. You may need to check your code and config. Please share a JS fiddle or something to reproduce and will open this issue.
