### ISSUE TITLE
upate to 4.3.9 ,when select 2 or more files,Previews duplication after uploading images

### ISSUE THREAD

**Issue by chnpassion** [kartik-v/bootstrap-fileinput#918]
upate to 4.3.9 ,when select **## 2 or more** files,Previews duplication after uploading images!
when select **one** file,It's ok . before  4.3.9 one file selected have this problem,now this problem have been solved,but occure new problem.
thanks!

**Comment by kartik-v** [comment]
Not sure you have the right code ... cannot reproduce your use case. Can you share a JS Fiddle to check your use case?

You can cross check the [ajax scenario # 5 demo](http://plugins.krajee.com/file-input-ajax-demo/5) where you would find it works fine.

**Comment by chnpassion** [comment]
thanks a lot ,I go study and check！

**Comment by chnpassion** [comment]
from demo,chang my code ,It's ok!
thanks a lot again!
