### ISSUE TITLE
how can i custom a operate button 

### ISSUE THREAD

**Issue by lllito** [kartik-v/bootstrap-fileinput#922]
12

**Comment by lllito** [comment]
`layoutTemplates:{
        	   
        	    actions: '<div class="file-actions">\n' +
        	        '    <div class="file-footer-buttons">\n' +
        	        '        {upload} {delete} {zoom} {other}' +
        	        '    </div>\n' +
        	        '    {drag}\n' +
        	        '    <div class="file-upload-indicator" title="{indicatorTitle}">{indicator}</div>\n' +
        	        '    <div class="clearfix"></div>\n' +
        	        '</div>',
        	    actionDelete: '<button type="button" class="kv-file-remove btn-primary {removeClass}" title="{removeTitle}"{dataUrl}{dataKey}>{removeIcon}</button>\n',
        	    actionUpload: '<button type="button" class="kv-file-upload {uploadClass}" title="{uploadTitle}">{uploadIcon}</button>\n',
        	    actionZoom: '<button type="button" class="kv-file-zoom {zoomClass}" title="{zoomTitle}">{zoomIcon}</button>',
        	    actionDrag: '<span class="file-drag-handle {dragClass}" title="{dragTitle}">{dragIcon}</span>'
        	
        }`

Like this

**Comment by lllito** [comment]
`layoutTemplates:{
        	    actions: '<div class="file-actions">\n' +
        	        '    <div class="file-footer-buttons">\n' +
        	        '        {upload} {delete} {zoom} {other}' +
        	        '    </div>\n' +
        	        '    {drag}\n' +
        	        '    <div class="file-upload-indicator" title="{indicatorTitle}">{indicator}</div>\n' +
        	        '    <div class="clearfix"></div>\n' +
        	        '</div>',
        	    actionDelete: '<button type="button" class="kv-file-remove btn-primary {removeClass}" title="{removeTitle}"{dataUrl}{dataKey}>{removeIcon}</button>\n',
        	    actionUpload: '<button type="button" class="kv-file-upload {uploadClass}" title="{uploadTitle}">{uploadIcon}</button>\n',
        	    actionZoom: '<button type="button" class="kv-file-zoom {zoomClass}" title="{zoomTitle}">{zoomIcon}</button>',
        	    actionDrag: '<span class="file-drag-handle {dragClass}" title="{dragTitle}">{dragIcon}</span>'
        }`

**Comment by kartik-v** [comment]
Please read the docs ->

Just set the html markup for <a href="http://plugins.krajee.com/file-input#option-otheractionbuttons">otherActionButtons</a>

**Comment by sagittaracc** [comment]
I haven't found it in the docs :(
