### ISSUE TITLE
Sending initialPreview Response From Server Side Alternative

### ISSUE THREAD

**Issue by devocodes** [kartik-v/bootstrap-fileinput#923]
Hi @kartik-v, is there a way to update initialPreview without modifying the json Response from the server, I mean from the client(broswer) side if there is a function where I could modify the json response to suit initialPreview before appending it?
Best of luck.

**Comment by kartik-v** [comment]
You can always set initialPreview dynamically from client side and call the plugin's <a href="http://plugins.krajee.com/file-input#method-refresh">refresh method</a> to refresh the plugin and or for advanced scenarios call the plugin's <a href="http://plugins.krajee.com/file-input#method-destroy">destroy method</a> and reinitialize the plugin with new settings (including its initialPreview).
