### ISSUE TITLE
¿How disable kv-file-upload?

### ISSUE THREAD

**Issue by pablogrela** [kartik-v/bootstrap-fileinput#925]
¿How disable kv-file-upload?
	$("#file-input").fileinput({
		language : 'en',
		uploadUrl : '#', // you must set a valid URL here else you will get an error
		maxFilesNum : 10,
              
               // Disables...
		actionUpload: false,
		btnUpload : false,

		slugCallback : function(filename) {
			return filename.replace('(', '_').replace(']', '_');
		}
	})

![image](https://cloud.githubusercontent.com/assets/11063006/24876235/4260a0ee-1e2b-11e7-9a30-26f9e6d721e2.png)

**Comment by kartik-v** [comment]
Read the [documentation and all the plugin options](http://plugins.krajee.com/file-input#options).

You can control this by setting `showUpload` to `false` within [fileActionSettings](http://plugins.krajee.com/file-input#option-fileactionsettings).

**Comment by pablogrela** [comment]
Thanks
`$("#file-input").fileinput({
language : 'en',
uploadUrl : '#', // you must set a valid URL here else you will get an error
maxFilesNum : 10,

           // Disables...
        fileActionSettings : {
			showUpload : false,
		},

	slugCallback : function(filename) {
		return filename.replace('(', '_').replace(']', '_');
	}
})`
