### ISSUE TITLE
How do i remove it?

### ISSUE THREAD

**Issue by czmchen** [kartik-v/bootstrap-fileinput#932]
Project Scenario: Upload is complete, save to the database, delete an image, and also trigger the update database.

Component implementation: filepreupload package previewId and data, filebatchuploadcomplete implementation of the preservation of the database, this step is OK. But the implementation of the delete operation filesuccessremove, function return id for the uploadId, can not match

**Comment by kartik-v** [comment]
For deleting server uploaded files - you just need to set the `deleteUrl` to the server delete action and set a `key` for each file thumb within `initialPreviewConfig`. The plugin automatically sends this `key` via POST to the `deleteUrl` when you click the `delete` button.

Read about this in docs and also you can set [deleteExtraData](http://plugins.krajee.com/file-input#option-deleteextradata) to set additional params to be passed to the deleteUrl.

The `filesuccessremove` event is typically used only for deleting thumbnails not yet uploaded to server... however I can enhance it later to pass the initialpreviewconfig key as well.
