### ISSUE TITLE
Audio file as initial preview

### ISSUE THREAD

**Issue by ruchisheth** [kartik-v/bootstrap-fileinput#935]
Can't find a way to display a audio file as initail preview and play it in Zoom preview
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
You need to set your initialPreviewAsData to true to achieve this easier. Check the [initial preview management demo as data](http://plugins.krajee.com/file-preview-management-demo#preview-data)

**Comment by ruchisheth** [comment]
Its already set to true. Able to display preview icon. but in zoom view its not playing audio

**Comment by ruchisheth** [comment]
![lc2 edit employee](https://cloud.githubusercontent.com/assets/20935380/25229763/2f64a23a-25ef-11e7-9775-74c2072925cf.png)
![lc2 edit employee 1](https://cloud.githubusercontent.com/assets/20935380/25229834/6d004630-25ef-11e7-860a-eb169f51acb1.png)

**Comment by ruchisheth** [comment]
This is my output but it displaying control only. Song is not getting played. and also it shows song length 0

**Comment by Remax-Malta** [comment]
I am having the same problem. I have an audio file in initial preview, and when setting the url to call the controller the audio wont play. However when calling the controller manually it works. 

Is this issue fixed?

**Comment by SteveGrixti** [comment]
I am having the same problem. I have an audio file in initial preview, and when setting the url to call the controller the audio wont play. However when calling the controller manually it works. 

Is this issue fixed?

**Comment by bharatmalhotra84** [comment]
There is same problem with **.zip** files. it does not show preview. see attachment. what is the right property?
below is code
$(".import-file-input").fileinput(
        {
            'showUpload': false,
            'previewFileType': 'any',
            'initialPreviewAsData': true,
            'allowedFileExtensions': ['TIFF', 'PNG', 'BMP', 'JPEG, 'ZIP''])
![zip](https://user-images.githubusercontent.com/31948676/78169968-883c1280-7452-11ea-8e0e-a9e4577b6a43.PNG)
  
            
        });

**Comment by aa-aahmed** [comment]
Zip, rar pre-view issue? any update on this?

**Comment by Tahiaji** [comment]
If I understood correctly, there is a missing type in the audio tag.

Generated code:
```
<audio class="kv-preview-data file-preview-audio" controls="" style="width:100%;height:30px;">
    <source src="file.mp3" type="audio">
    <div class="file-preview-other">
        <span class="file-other-icon"><i class="glyphicon glyphicon-file"></i></span>
    </div>
</audio>
```


Here is template :  https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js
```
tAudio = '<!--suppress ALL --><audio class="kv-preview-data file-preview-audio" controls' + tStyle + '>\n<source src="{data}" ' +
                'type="{type}">\n' + $h.DEFAULT_PREVIEW + '\n</audio>\n';
```

And if I change to  `type="{type}/mpeg"` audio starts playing. So I update audio layout template in pluginOptions. (In my case I have only mp3 files)
```
'layoutTemplates' => [
     'audio' => '<audio class="kv-preview-data file-preview-audio" controls {style}>\n<source src="{data}" type="{type}/mpeg"></audio>'
],
```
