### ISSUE TITLE
maxFileCount not works after one file uploaded

### ISSUE THREAD

**Issue by twinh** [kartik-v/bootstrap-fileinput#937]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Visit the Max Files (Ajax) demo http://plugins.krajee.com/file-count-validation-demo 
2. Browse and upload one file
![image](https://cloud.githubusercontent.com/assets/594436/25282119/1edf349a-26e2-11e7-916f-427041938993.png)
![image](https://cloud.githubusercontent.com/assets/594436/25282153/4030e09e-26e2-11e7-8466-1d59eff24bf8.png)
3. Repeat previous step, then you can upload more than maxFileCount files
![image](https://cloud.githubusercontent.com/assets/594436/25282265/893ca5fc-26e2-11e7-949f-30e3e495451c.png)
![image](https://cloud.githubusercontent.com/assets/594436/25282400/ec0eb5e4-26e2-11e7-8709-645ff48e1c5f.png)

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is expected behavior.

Unless you update the uploaded file on server back to the `initialPreview` configuration in the plugin, this  file will not be possible for plugin to check in maxFileCount... the example just considers an use case where there are only 3 files in the `initialPreview`.

So if you need any new file uploaded to be included in file count validation with `validateInitialCount`, then after upload of a file you need to update the initialPreview of the plugin. You can check how you can do it using the [ajax example # 5 demo](http://plugins.krajee.com/file-input-ajax-demo/5).

Or you can use the plugin `refresh` method to update initialPreview on the  `fileuploaded` and `filebatchuploadsuccess` events.

**Comment by mecheri** [comment]
@kartik-v it's i fixed the error by adding this 
` $object->initialPreviewThumbTags = [new \stdClass()];`  
instead of
` $object->initialPreviewThumbTags = [];`  

Thanks a lot your are doing a very good job

**Comment by naveenvanga7177** [comment]
Multiple files Uploaded but request goes to multiple times 
i am uploading Multiple files but every request only one file getting 
I want get all files at a time (single request)
var httpRequest = HttpContext.Current.Request;
            var count=httpRequest.Files.Count

only count =1 every time

**Comment by kartik-v** [comment]
@naveenvanga7177  read the plugin documentation to understand the various configuration options... for your use case you need to set [`uploadAsync`](http://plugins.krajee.com/file-input/plugin-options#uploadAsync] to `false` which will send all files in ONE GO.

**Comment by kartik-v** [comment]
@naveenvanga7177  read the plugin documentation to understand the various configuration options... for your use case you need to set [`uploadAsync`](http://plugins.krajee.com/file-input/plugin-options#uploadAsync) to `false` which will send all files in ONE GO.

The details are mentioned in the ajax uploads section of the documentation. For your use case read the [synchronous ajax uploads](https://plugins.krajee.com/file-input#ajax-sync).

**Comment by naveenvanga7177** [comment]
> @naveenvanga7177 read the plugin documentation to understand the various configuration options... for your use case you need to set [`uploadAsync`](http://plugins.krajee.com/file-input/plugin-options#uploadAsync) to `false` which will send all files in ONE GO.
> 
> The details are mentioned in the ajax uploads section of the documentation. For your use case read the [synchronous ajax uploads](https://plugins.krajee.com/file-input#ajax-sync).

@kartik-v  Thank you

**Comment by naveenvanga7177** [comment]
my requirement is   upload files are stored in one object and 
after click on Final submit button then goes to server

**Comment by kartik-v** [comment]
This is a coding question which needs to be handled from the developer's side. Please post programming help related queries in the forums or on the demos comments pages for others to help. Use this repo to only report bugs and issues.
