### ISSUE TITLE
delete file

### ISSUE THREAD

**Issue by hezhongjie** [kartik-v/bootstrap-fileinput#938]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.this is my options: var defaultObj = {
            language: 'zh',                      //语言格式
            theme: 'explorer',                //
            uploadUrl: '/iouuser/iouUserAttachementNew',
            allowedFileExtensions: [],//接收的文件后缀
            showUpload: true, //是否显示上传按钮
            showCaption: true,                 //是否显示标题(即文件名称)
            browseClass: "btn btn-primary",   //按钮样式
            overwriteInitial: false,            //
            initialPreviewAsData: true,
            maxFileCount: 10, //表示允许同时上传的最大文件个数
            uploadExtraData: obj.data,
            showAjaxErrorDetails: false,         //上传失败后,是否显示返回的信息
            showPreview: false,
        }
2. when i click deleteButton to delete a image that i just uploaded (not the initialPreview images),i can't get the image's data, so i can't tell the backend which one i deleted, why be that??
3. when i uploaded one file, the result of  getFileStack length is always 1,why? 

4.what is  the correct option of delete files that just uploaded ?

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by hezhongjie** [comment]
i am waiting . . .

**Comment by willisaway** [comment]
$('#kv-explorer').on('filesuccessremove', function(event, previewId, index) {
            var url = '/attachment/delete';
    	    $.ajax({
    			type: "post",
    			url: url,
    			data: {file_id:previewId},
    			//dataType: "json",
    			success: function (result) {
    				if(result.returnValue>0){
    					alert("删除成功");
    				}else{
    					alert(result.returnMessage);
    				}
    			},
    			error:function(response){
    				alert("删除失败");
    				console.log("更新失败");
    			}
    		});
        });

**Comment by hezhongjie** [comment]
but ,in my app , the callback's previewIds are always same,so i can't tell which file i delete  .
their Id  all are the 'preload' + timestamp. this is  the question

**Comment by hezhongjie** [comment]
但是,在我的项目中,上传图片成功后,stackFile中的文件数量不变,始终只有一个,而且自动生成的预览图的文件的父级元素的id 每个都是 preload + 时间戳 ,他们的ID都一样,所以我在回调函数中拿到的previewid 根本无法确认被删除的图片是哪个?

**Comment by kunl** [comment]
@hezhongjie 我也是，不能确定删除的是哪个

**Comment by willisaway** [comment]
我改了一下源码，你在源码里搜一下file_id,
我改成这样了formdata.append('file_id', previewId);

**Comment by wzhenhang** [comment]
既然都是中国人我就说中文了：
这是因为在源码中存在以下代码：
        _resetFileStack: function () {
            var self = this, i = 0, newstack = [], newnames = [];
            self._getThumbs().each(function () {
                var $thumb = $(this), ind = $thumb.attr('data-fileindex'),
                    file = self.filestack[ind];
                if (ind === -1) {
                    return;
                }
                if (file !== undefined) {
                    newstack[i] = file;
                    newnames[i] = self._getFileName(file);
                    $thumb.attr({
                        'id': self.previewInitId + '-' + i,
                        'data-fileindex': i
                    });
                    i++;
                } else {
                    $thumb.attr({
                        'id': 'uploaded-' + uniqId(),
                        'data-fileindex': '-1'
                    });
                }
            });
            self.filestack = newstack;
            self.filenames = newnames;
        },

这段代码在mutiple模式下必定会执行，只上传一个文件时有时会执行，一旦执行，会将previewId修改为一个新得id，且丢失序号，导致删除时获取到得是新的id，如果对以上代码进行修改为如下：

        _resetFileStack: function () {
            var self = this, i = 0, newstack = [], newnames = [];
            self._getThumbs().each(function () {
                var $thumb = $(this), ind = $thumb.attr('data-fileindex'),
                    file = self.filestack[ind];
                if (ind === -1) {
                    return;
                }
                //if (file !== undefined) {
                    newstack[i] = file;
                    newnames[i] = self._getFileName(file);
                    $thumb.attr({
                        'id': self.previewInitId + '-' + i,
                        'data-fileindex': i
                    });
                    i++;
                //} else {
                //    $thumb.attr({
                //        'id': 'uploaded-' + uniqId(),
                //        'data-fileindex': '-1'
                //    });
                //}
            });
            self.filestack = newstack;
            self.filenames = newnames;
        },

则可以做到删除指定对象，但这种方式为侵入式的，所以我的问题是：1.这样修改会不会导致新的bug；2.是否有非侵入式的修改方法；3.为什么源码中会有这种替换掉id的逻辑，起什么作用？
有人能回答吗？

**Comment by feeee** [comment]
替换掉id是因为每次重复点击选择文件时，用preview做前缀的这个id会重复，导致上传成功时动画处理响应异常，最终仍然无法确认删除的到底是哪个文件，无力吐槽。
