### ISSUE TITLE
when deleting the third picture,it will also delete the fourth pictures in the preview area.

### ISSUE THREAD

**Issue by guangxuanliu** [kartik-v/bootstrap-fileinput#941]
Hi,I am a newbie at github,this is my first time to submit a new issue,if there are something unclear,please tell me,thanks a lot.

the problem is:

1. select 4 pictures
2. batch upload to the server(in ajax async mode)
3. delete in order in preview area (first,second,third)
4. when deleting the third one ,the fourth will disappear also,but it didn't delete in the server

the initial code is:
```
$("#filesrc").fileinput({
                'language': 'zh',
                theme: 'explorer',
                uploadUrl: data.urls.upload,    //MembersData/Image/upload
                uploadExtraData: {
                    id: data.dataSource.pageData.scrollKeys.current
                },
                showRemove: false,
                showClose: false,
                fileActionSettings: {
                    showUpload: false
                },
                overwriteInitial: false,
                allowedFileTypes: ['image']
            })
```
![1](https://cloud.githubusercontent.com/assets/6881660/25365478/8a0b36b8-299b-11e7-87f4-e154b676b965.png)

then,select four pictures,and uploading them.the server returns are here:
```
{
  "error": "",
  "initialPreview": [
    "<img src='http://here-are-our-server.com/10000131375574675246405223851a4.jpg' class='file-preview-image' alt='10000131375574675246405223851a4.jpg' title='10000131375574675246405223851a4.jpg'style='width: auto; height: 60px; '>"
  ],
  "initialPreviewConfig": [
    {
      "caption": "1.jpg",
      "url": "/MembersData/Image/delpic",
      "key": "10000131375574675246405223851a4.jpg",
      "extra": {
        "id": 12
      }
    }
  ],
  "initialPreviewThumbTags": [
    {}
  ],
  "append": true
}
```
![2](https://cloud.githubusercontent.com/assets/6881660/25365488/a907e020-299b-11e7-996c-5e4868ce8568.png)

then delete first,then second,each one the server response is
```
{
  "success": "True"
}
```
![5](https://cloud.githubusercontent.com/assets/6881660/25365567/2f38314a-299c-11e7-89f5-6c3ce11a1f26.png)

When deleting the third one,the server also return like above,but the fourth one disappear in the preview too,it also disappear in the dom,but it didn't send ajax request,the fourth also didn't delete on the server,I don't know the reason?

**Comment by guangxuanliu** [comment]
on the server,my colleague use the key and extra id to delete the picture.

**Comment by guangxuanliu** [comment]
I find where is the problem,at the line 2207 in the source code(fileinput.js),just change 

> index = parseInt(($frame.data('fileindex')).replace('init_', ''));

to

> index = parseInt(($frame.attr('data-fileindex')).replace('init_', ''));

I guess maybe in the line 2087 of the function '_deleteFileIndex', the author use $frame.attr to set the attribute,but use data to get the value.so the dom tree can't refresh.

I also find this is [so:](http://stackoverflow.com/questions/15247168/html5-data-doms-change-isnt-seen-by-jquery)

**Comment by kartik-v** [comment]
Will check this.
