### ISSUE TITLE
Fileinput file-upload-indicator is visible when actionDrag is empty

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/bootstrap-fileinput#942]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Hi I wanted to disable the drag/sort possibility completely of the Fileinput and set `'actionDrag' => '',`  (empty)

## Expected behavior and actual behavior

When I follow those steps, I see...
this yellow bulb in the lower left instead of the drag handle.

![image](https://cloud.githubusercontent.com/assets/1777147/25387222/61713e62-29ca-11e7-8d0a-7ac33918c14e.png)

I was expecting...
to just disable the drag handle and see nothing ;)

Is there another way to remove the drag handle?

The small Bulb is coming from the css by
.krajee-default .file-drag-handle, .krajee-default .file-upload-indicator {
 padding: 8px 8px 1px 3px;
}

The indicator is just isn't overlapped by the missing file-drag-handle.
I couldn't find another possibility to remove the re-order possibility.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: master

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Read about [fileActionSettings](http://plugins.krajee.com/file-input#option-fileactionsettings) in docs.

For your use case just set `fileActionSettings.showDrag` to `false`...

**Comment by Bhoft** [comment]
The issue is still there I have created a jsfiddle

https://jsfiddle.net/7z01jb07/1/

used some demo code from here
http://plugins.krajee.com/file-count-validation-demo

**Comment by Bhoft** [comment]
Another issue if I use the explorer theme the upload indicator is also removed when I set 
fileActionSettings.showDrag to false
together with
fileActionSettings.showZoom to false

Maybe a independent showIndicator setting would  be better instead of checking for fileActions.
I have no ajax upload enabled for my widget and using just the normal form post method.
So there is also no upload button for each preview item. And therefore no fileActions and because of this no upload indicator.

**Comment by Bhoft** [comment]
Sry to disturb,
Now the upload indicator isn't shown at all.
I guess you have forgot to add the `{indicator}` in the default / explorer template in the footer part.

e.g. for the explorer theme instead of 
`
 footer: '<td class="file-details-cell"><div class="explorer-caption" title="{caption}">{caption}</div> ' +
            '{size}{progress}</td><td class="file-actions-cell">{actions}</td>',
`
this:
`
 footer: '<td class="file-details-cell"><div class="explorer-caption" title="{caption}">{caption}</div> ' +
            '{size}{progress}</td><td class="file-actions-cell">{actions}{indicator}</td>',
`

Or you wanted to render the {indicator} in the actions which looks like more possible because you have the {indicator}  in the  `tActions = '{indicator}\n' + '{drag}\n' +`

But then you shouldn't do the replace the tag in the footer template inside `_renderFileFooter` but instead in the `_renderFileActions` function.

**Comment by kartik-v** [comment]
Please share a fiddle and the scenario where it does not work... not able to reproduce...

**Comment by Bhoft** [comment]
It was working the the fiddle above, when you have disabled showDrag and showZoom.
but not when you also disabled the ajax upload (e.g. when using form post to upload). Then the indicator is again not visible.

See here:
https://jsfiddle.net/7z01jb07/2/

**Comment by kartik-v** [comment]
No it cannot be added to footer template directly... will update.

**Comment by Bhoft** [comment]
looks like it is working now.
I found 2 other issues but for them i will open new issues.

**Comment by ralphdev22** [comment]
Hi. How to remove file indicator? I read your documents but i couldn't find how to remove file indicator. I only found the ff:

showUpload: boolean, whether to show the upload button in the thumbnail

showRemove: boolean, whether to show the remove button in the thumbnail

showZoom: boolean, whether to show the zoom button in the thumbnail

showDrag: boolean, whether to show the drag button in the thumbnail (applicable only for initial preview content)

Please help me.

**Comment by kartik-v** [comment]
Read [`fileActionSettings`](http://plugins.krajee.com/file-input#option-fileactionsettings) in documentation and set the markup for -- `indicatorNew`, `indicatorSuccess`, `indicatorError` to the value you need which in  your case will be a blank space `&nbsp;`

**Comment by ralphdev22** [comment]
Thank you for the response. I'll check it.

**Comment by ralphdev22** [comment]
Yeah! It works!. Thanks.

I have another one. How to remove delete button in action bar? 
I tried this

fileActionSettings : {
				showRemove: false,
				showDrag: false,
				indicatorNew: "",
				indicatorSuccess: "",
				indicatorError: ""
			},

but remove button still displayed.... Please help me again.
