### ISSUE TITLE
How can I hidden the upload button in the small preview frame, please?

### ISSUE THREAD

**Issue by davy2495** [kartik-v/bootstrap-fileinput#943]
There are two upload button,
first one, behind the select file button, we can set [showUpload : false] to disable this button,
and the second one at the bottom of image preview frame, 
so, how can i disable the second upload button, please?
thanks!

**Comment by kartik-v** [comment]
By reading the documentation completely and carefully. Please read all options available and other issues posted before logging an issue.

Duplicate to #907 and #925.

Read plugin documentation and about [fileActionSettings](http://plugins.krajee.com/file-input#option-fileactionsettings).

You can prevent upload icon display in thumbnail by setting `fileActionSettings['showUpload']` to `false`.

**Comment by davy2495** [comment]
oh，thank you so much!
