### ISSUE TITLE
Show more detailed error message instead of generic one ('filebatchuploaderror')

### ISSUE THREAD

**Issue by Roluc** [kartik-v/bootstrap-fileinput#945]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.

1. Added custom Event on 'filebatchuploaderror'
$('#input-id').on('filebatchuploaderror', function(event, data, msg) {
    var form = data.form, files = data.files, extra = data.extra,
        response = data.response, reader = data.reader;
    console.log('File batch upload error');
   // get message
   alert(msg);
});
2. Change the permission of a file to non-readable (for uploading)
3. Add the non-readable file via drag and drop to the uploader
4. Submit form

As soon as i submit, the page shows me the popup with the error message defined in the setting 'msgAjaxError'. My question here: is there a possibility to show more detailed error messages instead of the generic "Something went wrong with the {operation} operation. Please try again later!", something like "permission denied"?

btw: Thanks for the plugin, i am a huge fan of it. ;D

Libraries

- jQuery version: v1.11.4
- bootstrap-fileinput version: v4.4.0

**Comment by kartik-v** [comment]
You can set `msgAjaxError` to what you need for your use case. It still will be a generic message for all scenarios - unless you want to trap server errors - you can trap and return your own exception messages

**Comment by mariopaisa** [comment]
Hello @kartik-v, I get the same problem, I'm going crazy ... I do not know how to solve this error, because I can not replicate it and I do not identify what the root cause is. Please help me

![error_fileupload](https://user-images.githubusercontent.com/976984/52052822-9d06d880-2525-11e9-8c60-6726edf2ffed.png)

**Comment by haidir-achmad** [comment]
![image](https://user-images.githubusercontent.com/40346436/61936280-975eec80-afb6-11e9-9ab7-3153c51a231a.png)
 have solution

**Comment by abduqodirkhojiyev** [comment]
me too !
