### ISSUE TITLE
Upload feature not getting triggered when user leaves avatar instead of choosing a file from device

### ISSUE THREAD

**Issue by kanumuri9593** [kartik-v/bootstrap-fileinput#948]
I am using this framework to upload a profile image in while sign-up using 

`$("#avatar").fileinput({
		overwriteInitial: true,
		uploadUrl: Posturl,
		uploadAsync: true,
		maxFileCount: 1,
		showBrowse: false,
		browseOnZoneClick: true,
		allowedFileTypes: ["image"],
		maxFilePreviewSize: 1024000,
		showCaption: false,
		showRemove: false,
		showUpload: false,
		showUploadedThumbs: false,
		initialPreview: ['<img src="/assets/avatars/s8.png" class="file-preview-image">'],
		dropZoneTitle: '<img src="/assets/profile_image.svg" style="width:80px"> <br>',
		previewSettings: {
			image: {
				width: "250px",
				height: "250px"
			}
		},
		resizeImage: true,
		maxImageWidth: 1600, //used for resizing Image
		maxImageHeight: 1600, // used for resizing Image
		resizeImageQuality: 0.92
	});`

I am setting the Post url later when I gather other details of the user and trying to upload the image by triggering 
`$('#avatar').fileinput('upload');`

this works perfect if I select some file from the device but not when user leaves the Initial avatar
I don't even see any Ajax call even after firing 
`$('#avatar').fileinput('upload');`
Can anyone please suggest me why this is happening and suggest me a solution

**Comment by kartik-v** [comment]
You have the reason and answer in your query itself. You mentioned you are not selecting the file on the device and still trying to upload something to your server.

Unless you select a file on a device what will the plugin upload to your server? The plugin only uploads files selected from device/client.
