### ISSUE TITLE
Can't find a way to display a audio file as initail preview and play it in Zoom preview

### ISSUE THREAD

**Issue by ruchisheth** [kartik-v/bootstrap-fileinput#953]
initialPreviewAsData   ##is already set to true. Able to display preview icon. but in zoom view its not playing audio

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by ruchisheth** [comment]
This is my output but it displaying control only. Song is not getting played. and also it shows song length 0

![2f64a23a-25ef-11e7-9775-74c2072925cf](https://cloud.githubusercontent.com/assets/20935380/25605811/3b6bb9ca-2f2b-11e7-89b0-15fff2afacc1.png)
![6d004630-25ef-11e7-860a-eb169f51acb1](https://cloud.githubusercontent.com/assets/20935380/25605812/3b6cef70-2f2b-11e7-9c83-328eb77c10b7.png)

**Comment by kartik-v** [comment]
This is more a HTML5 audio playback support issue. The file you are selecting for playback has to be supported by HTML5 audio tag.
