### ISSUE TITLE
Not removing last preview before inserting new (ajax)

### ISSUE THREAD

**Issue by leandro-mnc** [kartik-v/bootstrap-fileinput#957]
I'm using ajax upload, with an initial image. 
When I upload a new image, the first time is ok. But when I try to upload a second image the first one is not removed.

In the fileinput.js I see that is because the **_clearPreview** function will remove thumbs that doesn't have the **.file-preview-success** class. 

But the function responsible to remove that class(**_setThumbStatus**), didn't worked as expect (tries to remove it _before_ _adding_ _the_ _class_), see image below:
 
![bug](https://cloud.githubusercontent.com/assets/20569143/25662647/a3d02a1c-2feb-11e7-9509-74624ebdbd09.png)

**Comment by kartik-v** [comment]
Not sure if I understand your issue.

If you do not want the uploaded successful thumbnails to be shown then set [showUploadedThumbs](http://plugins.krajee.com/file-input#option-showuploadedthumbs) property to `false`.
