### ISSUE TITLE
attach global data for every ajax requests

### ISSUE THREAD

**Issue by jcyuan** [kartik-v/bootstrap-fileinput#959]
I just have a requirement.
Is there a way to always attach some data to ajax request? although I could use uploadExtraData or deleteExtraData or 'extra' config for each preview items but for my case:
I need to attach an Anti-Forgery token for every ajax reuqests to prevent my site from CSRF attacking.
uploadExtraData is useful for uploading, I can attach the token.
but I think there is no way to put the token into the 'extra' config which generated from the serverside.
because the token cannot be generated by server (client cookie is involved). so I need a way to modify the 'extra' config to add my token variable while deleting.
temporarily I inserted a new line:
extraData = $.extend({}, myCustomGlobalData, extraData);
at line 2249 of the source code and it works fine.
or actually there is already a way to do this but I dont know?

**Comment by kartik-v** [comment]
For ajax requests (delete) - set either `deleteExtraData` or `initialPreviewConfig.extra`. You can set it as a JS Function Callback so that it returns data dynamically.. for example you can set it to:

```js
'deleteExtraData': function() {
    return {'_csrfToken': $('#some-csrf-hidden-input').val()};
}
```

**Comment by jcyuan** [comment]
thanks man, but I have read your source code, .extra and deleteExtraData only one data will be adopted to submit.
from your source code:
`extraData = isEmpty(config) || isEmpty(config.extra) ? deleteExtraData : config.extra;`
my extra config generated by server looks like:
`extra : {  id: image-server-id }`
if I set deleteExtraData as your code above, only .extra will be submit.

**Comment by kartik-v** [comment]
Yes that is expected `config.extra` will over-ride the `deleteExtraData` set.

For your use case you can configure [ajaxDeleteSettings](http://plugins.krajee.com/file-input#option-ajaxdeletesettings) to add additional ajax settings that will be merged. So `ajaxDeleteSettings.data` can contain the common `_csrf` key.

**Comment by jcyuan** [comment]
wow! got it, many thanks for the support!
