### ISSUE TITLE
Asp.net mvc asyn ajax custom error from server

### ISSUE THREAD

**Issue by hasbimuharip** [kartik-v/bootstrap-fileinput#960]
I'm using asp.net mvc and trying to send custom error as Json in my controller and i am able to succceed on it but my output looks weird. 

It seems to be successfully done and still processing even if it is error.

> My Return code from mvc:

`return Json(new { error = "Oops an error been occurred!" });`

> I tried to use **fileuploaderror** method to control this but didnt figure it out.
`on('fileuploaderror', function (event, data, msg) { 
                    // tried to show that process has failed
                });`

> My Output

![err](https://cloud.githubusercontent.com/assets/27810645/25696403/bc719202-30bf-11e7-8a51-a6ca40e596f7.png)

**Comment by kartik-v** [comment]
Noting an enhancement

**Comment by kartik-v** [comment]
This has been resolved with v4.4.0.
