### ISSUE TITLE
view pre image

### ISSUE THREAD

**Issue by ingenuous67** [kartik-v/bootstrap-fileinput#961]
hi
i have a form for my user profile in yii2
when user open this form:
-  i want to show previous uploaded image of user.
- show an upload button and when user click on this button upload image to special folder
- show upload progress bar to user
- save image name to database.
can you help me?
thanks a lot.

**Comment by kartik-v** [comment]
Each of the above needs to be achieved via code programmed from your end. You may wish to request programming help in [the webtips forum](http://webtips.krajee.com) or in the comments section as this repo is not the appropriate place for requesting for programming help.

Go through the various [plugin docs](http://plugins.krajee.com/file-input/) and [plugin demos](http://plugins.krajee.com/file-input/demo) to understand how to do this via javascript.

Check some of the [webtips on bootstrap-fileinput](http://webtips.krajee.com/tag/bootstrap-fileinput/) usage including yii2 to understand.
