### ISSUE TITLE
how can I know the ajax is success, and do some other things

### ISSUE THREAD

**Issue by robert7git** [kartik-v/bootstrap-fileinput#962]
Hello there ~ ~
First of all, this is the greatest jquery upload plugin.
Also thank the author to share such a good plugin.

But I encountered some problems in the use, and I hope you can help me.

I tried to set the <input type = "hiden"> field with the data of the ajax response after the upload operation was complete.

The issue is:
How to know that the ajax request is successful
And how can I do something else through callbacks?

hello～
At First, this is the greatest upload plugin. 
I have tried to set <input type="hiden"> field with the ajax responsed data when the upload action is done.

The question is:
how can I know the ajax request is success and do something else with ajaxSetting success callback .

here is my code
```html
    div(class="field")
        label thumb
        div(id="kv-avatar-errors", class="center-block", style="width:800px;display:none")
        div(class="kv-avatar center-block", style="width:200px")
            input(id="fileupload", name="thumb", class="file-loading", type="file", multiple, data-min-file-count="1")
            input(type="hidden", name="_thumb", value=`${ article.thumb || '' }`)
```
```javascript
uploadImg: function (formElement, uploadFileType) {
        $("#fileupload").fileinput({
            uploadUrl: '/api/upload/',
            ajaxSettings: {
                complete: function(res){
                    if(res.status.code === 0){
                        res.data[uploadFileType].forEach(function(val){
                            $('#' + formElement).find('input[name="_' + uploadFileType + '"]').val(val)
                        })
                    }
                }
            },
        });
```

thank you~

**Comment by kartik-v** [comment]
> How to know that the ajax request is successful

You can read about the [various events](plugins.krajee.com/file-input#events) available with the plugin to handle your use case. For example for your use case you can use the [filebatchuploadcomplete](http://plugins.krajee.com/file-input#event-filebatchuploadcomplete) event or the [filebatchuploadsuccess](http://plugins.krajee.com/file-input#event-filebatchuploadsuccess) events.

Or if firing upload via the small upload button in the thumbnail you can use [fileuploaded](http://plugins.krajee.com/file-input#event-fileuploaded) event.

**Comment by robert7git** [comment]
wow~
thank you~
thanks for help.
I will read api document seriously next time.
