### ISSUE TITLE
Problem deleting penultimate image (from server)

### ISSUE THREAD

**Issue by rkmgralpaz** [kartik-v/bootstrap-fileinput#963]
I have set up initialPreview and initialPreviewConfig in such a way that it shows me the images I have loaded. When you delete them, it makes it excellent, except in the penultimate image that I press "delete", for some error erases the last image as well (only the preview, it does not eliminate it physically). When I refresh the page, this image is still there, it has not really been deleted. This only happens when I have more than 4 pictures. Has someone ever happened to you?

**Comment by xahidsana** [comment]
plz share delete section code ...  urgently require//
i done the upload section that properly upload files on  server directory
but not delete the upload files from server directory ....
i try to do this , to  setup initialPreview and initialPreviewConfig .... but it not working

**Comment by kartik-v** [comment]
Can you check with the latest plugin code release and update if this occurs? I am not able to reproduce your issue... however if you can reproduce that with the latest plugin release --- please share a JS Fiddle.
