### ISSUE TITLE
Issue with reset feature

### ISSUE THREAD

**Issue by bluesun3k1** [kartik-v/bootstrap-fileinput#964]
Hello,
 
I am having an issue with the ‘reset’ event and the . I’m using bootstrap-fileinput v4.4.0.
 
1.       When used as $(‘#input-id’).fileinput(‘reset’);  the whole file-input DIV vanishes and does not restart unless I refresh the page.
2.       When I click on the Remove Button found (.kv-file-remove) in .file-footer-buttons, It does the same thing. i.e. Say I load an image but I don’t want to upload it and I decide to remove it from the .file-preview, clicking the .kv-file-remove class button simply removes the entire frame.
 
I browsed through the code and I noticed that the reset event adds a new class to the container (file-input-new) so I decided to remove the entire line just to test what it would do and the reset event actually worked as intended. It reloads the .file-input with the previously uploaded image.
 
Here’s the line I removed. $h.addCss(self.$container, 'file-input-new');
 
Any idea why this happens?
 
Note: I’m using this for profile picture (kv-avatar) purposes.
 
Thanks in advance,

**Comment by kartik-v** [comment]
Yes this is expected... as the preview will be cleared once your reset.

You need to ideally have a default preview content for avatar upload. Go through the [avatar upload demo](http://plugins.krajee.com/file-avatar-upload-demo) ... you can set the `defaultPreviewContent` property to a default image or any HTML markup so that this is displayed always even when file input is cleared/reset.

**Comment by bluesun3k1** [comment]
Bit i do have a default image loaded. This issue occurs when I already have a profile image loaded and I intend to change it. Once the new image is loaded onto the preview frame, if i hit the remove button, the entire frame gets removed rather than defaulting back to the previous image.

**Comment by kartik-v** [comment]
Go through the [avatar upload demo](http://plugins.krajee.com/file-avatar-upload-demo) - and confirm if the behavior is as you intend... and configure similarly...
