### ISSUE TITLE
Ctrl select multifile 

### ISSUE THREAD

**Issue by delo2016** [kartik-v/bootstrap-fileinput#967]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.showPreview:false;
2.when I select two or more img by ctrl shows img's filename
3.if I borwser one img then browser one img ,it shows two selected

## Expected behavior and actual behavior
I expected step2 shows img's count  'two files selected'  NOT filename 'XXX.jpg'
## Environment

Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [X] Internet Explorer
- [ ] Safari

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version 1.12.3:
- bootstrap-fileinput version v3.3.2:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Cannot reproduce this. Can you share the details on when and how or a JS Bin code.

Suggest you to cross check [advanced demo example # 10](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-10) ... where preview is hidden... and depending on your file selection the caption changes automatically.

**Comment by delo2016** [comment]
Thanks for your reply which helped me find the problem. I have read the advance demo example#10 and find the key point.
`uploadUrl: "AjaxHandler/myHandler.ashx",` if I commented out this code,the problem is solved.
As you see my IDE is vs2012 ，C# language.
Look forward to your reply.

**Comment by kartik-v** [comment]
Yes you can use that way without ajax (i.e. form submit mode - refer docs for [usage modes](http://plugins.krajee.com/file-input#usage-modes)).

But seems to be a count issue when using with ajax mode with `uploadUrl`... and reopening this issue for correction.
