### ISSUE TITLE
Dropzone around file input without Preview

### ISSUE THREAD

**Issue by tsdogs** [kartik-v/bootstrap-fileinput#969]
This is a feature request.
I often have the need to upload files attached to a model, thought the Drag & Drop feature is very nice, I don't want the preview to be there.
I'd like to have something like github is using (a single row which permits me to select files or drop them there).

**Comment by tsdogs** [comment]
I've been able to implement something similar using the templatePreview and the pluginOptions.

**Comment by kartik-v** [comment]
Yes you need to configure [`previewTemplates`](http://plugins.krajee.com/file-input#option-previewtemplates) and/or  [`layoutTemplates`](http://plugins.krajee.com/file-input#option-layouttemplates) with CSS styling to achieve your use case.

**Comment by Nagendra080389** [comment]
@tsdogs  Can you please show an example how did you achieve this.

I tried this :

`            $(document).ready(function() {
                $("#input-b6").fileinput({
                    showUpload: false,
                    dropZoneEnabled: true,
                    maxFileCount: 10,
                    previewTemplates: {
                        generic: '',
                        image: '',
                        text: '',
                        office: '',
                        gdocs: '',
                        html: '',
                        video: '',
                        audio: '',
                        pdf: '',
                        flash: '',
                        object: '',
                        other: ''
                    }
                });
            });`

but its not working

**Comment by jabernalv** [comment]
> @tsdogs Can you please show an example how did you achieve this.
> 
> I tried this :
> 
> ` $(document).ready(function() { $("#input-b6").fileinput({ showUpload: false, dropZoneEnabled: true, maxFileCount: 10, previewTemplates: { generic: '', image: '', text: '', office: '', gdocs: '', html: '', video: '', audio: '', pdf: '', flash: '', object: '', other: '' } }); });`
> 
> but its not working

How do you resolve the issue. Kartik did not provide one good solution.
