### ISSUE TITLE
How to Bind Image Dynamically from Server

### ISSUE THREAD

**Issue by kmkesavan** [kartik-v/bootstrap-fileinput#970]
hello, How to bind image dynamically from server using jquery for edit view.can you give any example code?

**Comment by kartik-v** [comment]
Sorry cannot help with your programming or a code here. This is not the right forum.

You can study about `initialPreview`, `initialPreviewConfig` and `otherActionButtons` or `fileActionSettings` in [the docs](http://plugins.krajee.com/file-input) to achieve your use case.
