### ISSUE TITLE
Turkish character problem on text inside fileinput button

### ISSUE THREAD

**Issue by famace** [kartik-v/bootstrap-fileinput#972]
Hello, 
I research some issues about turkish character problems but they are all about the file name problem. My issue is about the text inside the button for the fileinput. I use   "browselabel" in "tr.js" .  when I customize it as turkish characters like browselabel: 'gözat' , it converts this special characters like "ö". I will be very thankfull if you give me some idea to fix it.
 Thanks

**Comment by kartik-v** [comment]
Read about [slugCallback](http://plugins.krajee.com/file-input#option-slugcallback) and configure it with your regexp to return your own filename characters. You may submit it as a PR to correct it for Turkish locale
