### ISSUE TITLE
Exif data on jpeg images is lost before sending images to the server

### ISSUE THREAD

**Issue by dam2k** [kartik-v/bootstrap-fileinput#974]
Hi there.
I setup HTML, CSS and JS on my static page and all is very cool! The problem occurs when I upload one or more jpeg images to the server.

After I catch the images server side with PHP I realize that the images are smaller (may be ok due to the client auto resize) and they lost all EXIF metadata, so I cannot rotate them, for example, based on their orientation on my server app.

The rotation works perfectly client side on the thumbnail so the image exif data is not a problem.

I think this is a feature request, but it could also be a bug.

I have this problem with mobile (android) or desktop (firefox or chrome on linux). I also tested it on Windows (firefox and ie11) with the same problem.

Is there a way to keep all (or just Orientation) EXIF data on jpeg images?
Thank you.

**Comment by aperla** [comment]
I have the same problem

**Comment by kartik-v** [comment]
Actually if you are resizing the image - the plugin uses HTML5 canvas to resize and the HTML5 canvas does not store exif data.

Seems some enhancement needs to be done to auto orient these images via the canvas itself... before they are sent to the server. Waiting for any other suggestions to enhance.
