### ISSUE TITLE
What's the difference between clear and reset methods?

### ISSUE THREAD

**Issue by x-yuri** [kartik-v/bootstrap-fileinput#975]
Yep, that's the usage question, but I've searched in issues, read documentation, looked in the code. I don't know where else I can find the answer.

**Comment by kartik-v** [comment]
`clear` is a deep advanced reset - which cleans up everything selected (except `initialPreview`) and clears any files selected within the native input

`reset` only resets the content in the preview and resets filestack in ajax mode... does not alter the file input

The difference is noticeable more in the non-ajax (native form submission) mode.

**Comment by kartik-v** [comment]
This has been updated in the docs more correctly:

- [`reset`](http://plugins.krajee.com/file-input#option-reset)
- [`clear`](http://plugins.krajee.com/file-input#option-clear)
