### ISSUE TITLE
uploadExtraData with any custom input

### ISSUE THREAD

**Issue by M-Husein** [kartik-v/bootstrap-fileinput#976]
Thanks For Share Your Work, This is Awesome Plugin ;)

But I'm having trouble with my case.
I want to use your demo sample http://plugins.krajee.com/file-input-ajax-demo/7

In addition to taking the input values of each .kv-input, I also want to retrieve the input values I created myself. How to do it, Please Help me

**Comment by kartik-v** [comment]
You can send all inputs as additional keys to the `uploadExtraData` object by setting it as a callback - very similar to the ajax demo 7  example.

**Comment by M-Husein** [comment]
I don't understand clearly :(

How to combine or add more input, example if I use your demo 7 example:
`	    uploadExtraData:function(){
        var out = {},key,i = 0;
        $('.kv-input:visible').each(function(){
          $el = $(this);
          key = $el.hasClass('kv-new') ? 'new_'+i : 'init_'+i;
          out[key] = $el.val();
          i++;
        });
        return out;
	    }`

So, how to add my custom input, like This:
`			,uploadExtraData:function(){
				return {
					album_title:$('input[name="title_album"]').val(),
					album_desc:$('textarea[name="desc_album"]').val()
				};
			}`

Please Guide me more, Thanks

**Comment by kartik-v** [comment]
yes.. that is correct

**Comment by M-Husein** [comment]
So, I just use double uploadExtraData to add my custom input?

I mean first uploadExtraData I follow with your example 7 and
Above I just add uploadExtraData with my custom input.

Have I got it right??

**Comment by kartik-v** [comment]
No.. I mentioned the second part is right... you need to combine and send only one `uploadExtraData`... not sure what the problem is .. are you having a problem in writing the code to combine it...

**Comment by M-Husein** [comment]
Yes, I having a problem in writing the code to combine it.
I mean combine your demo 7 example with my custom input

**Comment by kartik-v** [comment]
Normally I do not respond on programming help and code ... (suggest you to post it in the forums and comments to get help)... but not sure why it is difficult... something like below

```js
uploadExtraData:function(){ 
    var out = {},key,i = 0; $('.kv-input:visible').each(
         function(){ $el = $(this); key = $el.hasClass('kv-new') ? 'new_'+i : 'init_'+i; out[key] = $el.val(); i++; }
    ); 
    out['album_title'] = $('input[name="title_album"]').val();
    out['album_desc'] = $('input[name="desc_album"]').val();
    return out;
 }
```

You may want to expand on the above.

**Comment by M-Husein** [comment]
Sorry I was so troublesome you.

I have post in your plugin forum with discuss before here. but not respon.
Really Thanks.
