### ISSUE TITLE
why preview box display two same pictures?

### ISSUE THREAD

**Issue by froginfrog** [kartik-v/bootstrap-fileinput#984]
I use bootstrap-fileinput4.3.8.
my fileinput config is
`$("#xxxxx").fileinput({ 

            uploadUrl: "/carouselupload",
            deleteUrl: "/xxxxxx",
            uploadAsync: true,
            showCaption: false,
            maxFileSize: 1000,
            allowedFileExtensions: ["jpg", "png", "gif"],
            initialPreviewAsData: true,
            overwriteInitial: true
        }).on("fileuploaded", function (event, data, previewId, index) {
            console.log(data);
        });`
my backend sending data:
`{"initialPreview":"..\/uploads\/img\/11.jpg"}`

but the preview box display two same pictures.why? Can someone help me? thanks

**Comment by kartik-v** [comment]
Cannot reproduce. Ensure you are using the latest plugin version v4.4.1 and if you have an issue update over this and will reopen.
