### ISSUE TITLE
Typical form submit - file's "not coming"

### ISSUE THREAD

**Issue by vertisan** [kartik-v/bootstrap-fileinput#988]
Hi,

I want to upload my files not via ajax, but with other fields on the form, but the file itself is skipped.
How to do this? I have basic configuration:
```html
<input type="file" class="file-input" data-show-caption="false" data-show-upload="false" name="thumbnail">
```
```javascript
$('.file-input').fileinput();
```

**Comment by vertisan** [comment]
@kartik-v ?

**Comment by kartik-v** [comment]
You need to check your form markup (e.g. `enctype` should be set to `multipart/form-data`)... and the file input name should be of [array format for multiple uploads as mentioned here](http://webtips.krajee.com/read-html5-multiple-file-input-php/)
