### ISSUE TITLE
Hide thumbnail and show only file name

### ISSUE THREAD

**Issue by m3ldro** [kartik-v/bootstrap-fileinput#990]
I'm wandering for a couple of hour but i didn't found a way to show only files name (whit delete icon) without any preview. I'd like to have a simple list of files to upload without any preview. 
Is it possibile? 
Thanks a lot.

**Comment by kartik-v** [comment]
It is possible by modifying the layoutTemplates to hide the thumbnail content... however I am noting an enhancement to include an option to do this.

**Comment by m3ldro** [comment]
Thanks for your reply. Actually I read about layoutTemplates but i didn't understood how to use it.

**Comment by marco1486** [comment]
do you have a demo on how to do this?. Thanks
