### ISSUE TITLE
When the initialPreview is deleted, the count of initialPreview  is wrong bug

### ISSUE THREAD

**Issue by AggerChen** [kartik-v/bootstrap-fileinput#992]
## Prerequisites

- [ y] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ y] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ y] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ y] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ y] I have attempted to find the simplest possible steps to reproduce the issue.
- [ y] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
validateInitialCount : true,
maxFileCount: 5,
2.
When I click the delete button on the preview picture, go back to the background to delete the picture, and the preview will also delete the picture, this is OK.(当我点击预览区域图片的删除按钮时，会到后台删除此图片，预览中也会删除，这个没有问题。)
3.
But when I try to re select another picture, even if the total number of pictures does not reach the 5 I set, it will also make a mistake. The number of files is exceeded.(但是当我重新选择其他图片时，即便我的图片总数没有达到我配置的5个，也会报错提示超出个数限制)
4.
By querying the source code fileinput.js in Ajax, the success method is found,
“n = self.previewCache.count();” n is not change,or it won't change all the time.(当我查看源码fileinput.js时，当删除文件的ajax成功后，success方法中有一句话获取文件数量“n = self.previewCache.count();” n一直没有变或者是不会随着删除后改变)
5.
This leads me to retrieve the file when the _getFileCount method gets the count without changing, and all of them will go wrong（这导致我在重新选择文件的时候，_getFileCount方法获取count也没有改变，所有就会爆出超出个数错误）

I don't know how to solve it,

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: v4.4.1

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Cannot reproduce your use case... 

You may want to cross check your code with [the example for `maxFileCount` in the demos here](http://plugins.krajee.com/file-count-validation-demo#max-ajax).
