### ISSUE TITLE
Load initialPreview by Server

### ISSUE THREAD

**Issue by ggaj** [kartik-v/bootstrap-fileinput#994]
Hi Expert...

Can you help with an example to load initialPreview photo by server PHP....
![capturar1](https://cloud.githubusercontent.com/assets/3385678/26757851/fddfca2e-4898-11e7-87c1-18df8953a146.PNG)
For the btn blue into the box I would like to load file are there inside that folder in server side.... or can you help to do this with other way..

Thanks & Regards,

**Comment by kartik-v** [comment]
You need to set the `initialPreview` and `initialPreviewConfig` for the plugin via your server code (basically you should render the javascript needed for the plugin with parameters from your server/db.

Sorry this is not a forum for programming help and queries... you may try for help in the [plugin comments and discussion section](http://plugins.krajee.com/file-input#comments) or the [webtips forum](http://webtips.krajee.com).

**Comment by JessicaPuebla** [comment]
Just tell us the method of your plugin to render the initialPreview.

Please.
