### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by CharlesJu1** [kartik-v/bootstrap-fileinput#995]
After I choose a file to upload, I got this error message from Chrome Dev console.

![capture](https://user-images.githubusercontent.com/1816882/26838544-01604332-4b13-11e7-9719-a7145381f70e.JPG)

At the end of _validateImage function, there is this block of code:

```
each(function () {
       if (this.complete) {
              $(this).load();
        } else {
              if (this.error) {
                    $(this).error();
              }
        }
```

In Jquery 3.1.1, the load() function is defined as:

```
jQuery.fn.load = function( url, params, callback ) {
	var selector, type, response,
		self = this,
		off = url.indexOf( " " );

	if ( off > -1 ) {
		selector = stripAndCollapse( url.slice( off ) );
		url = url.slice( 0, off );
	}

```
Since no url is passed in, it is causing the javascript error. 

I am using JQuery 3.1.1.

**Comment by meteorlxy** [comment]
Looking forward to the next release
