### ISSUE TITLE
Support Series Uploading

### ISSUE THREAD

**Issue by devocodes** [kartik-v/bootstrap-fileinput#996]
hi @kartik-v, I know that `bootstrap-fileinput` support parallel uploading I do like to know if it also does support series uploading?, if it is not supported and you see it fitting could it be in the next enhancement?

**Comment by kartik-v** [comment]
Have you read and looked into the [two types of ajax uploads in the documentation](http://plugins.krajee.com/file-input#ajax-uploads). 

The [synchronous upload](http://plugins.krajee.com/file-input#ajax-sync) with [uploadAsync](http://plugins.krajee.com/file-input#option-uploadasync) set to `false` does a bulk upload of all files at one go on the server.

Whereas the  [asynchronous upload](http://plugins.krajee.com/file-input#ajax-async) does a parallel asynchronous upload of each file separately.

Not sure what you mean by series uploading. You can program it accordingly on your frontend and trigger each single thumbnail upload after each file upload is completed using `fileuploaded` event.

**Comment by devocodes** [comment]
What I am suggesting is auto uploading a single file at a time without the need of a client to push any buttons, this is a achieved by adding trigger to upload the next file when the previous file has finish uploading, this come in handy with big size files and helps when something goes wrong on the client side like connection loss.

if its already implemented could you kindly provide the code of how it is done.

**Comment by devocodes** [comment]
@kartik-v have a look pls?

**Comment by kartik-v** [comment]
As mentioned in my comment before:

> You can program it accordingly on your frontend and trigger each single thumbnail upload using a separate button. Then trigger the next thumbnail upload and so on after each file upload is completed using `fileuploadcomplete` event.

**Comment by kartik-v** [comment]
As mentioned in my comment before:

> You can program it accordingly on your frontend and trigger each single thumbnail upload using a separate button. Then trigger the next thumbnail upload and so on after each file upload is completed using `fileuploadcomplete` event.

When I get time I may think of a potential enhancement for this and will reopen this.
