### ISSUE TITLE
How to edit preview caption? 

### ISSUE THREAD

**Issue by laics1984** [kartik-v/bootstrap-fileinput#997]
Hi sorry all, this might not be appropriate here, but may i know how can i edit preview caption? As i would like to have more than just the file name in the preview caption. For example, instead of just file name, i would like to add the title File Name: abcs.png

Thanks.

**Comment by kartik-v** [comment]
Read the documentation for all options. You can check the [`layoutTemplates`](http://plugins.krajee.com/file-input#option-layouttemplates) property and set the following for your use case:

```js
'layoutTemplates': {
    'footer': '<div class="file-thumbnail-footer">\n' +
                '    <div class="file-footer-caption" title="{caption}">File Name: {caption}<br>{size}</div>\n' +
                '    {progress} {indicator} {actions}\n' +
                '</div>'
}
```

**Comment by BI7PRK** [comment]
I have the same problem.  and how to add a checkbox in the file item?
