### ISSUE TITLE
Cant able to use fileinput.js in electron app

### ISSUE THREAD

**Issue by arkyminds-vasikarans** [kartik-v/bootstrap-fileinput#999]
Works fine on normal browser environments.
But while moving to electron app its always throwing Uncaught Error: cant find module jquery.
But jQuery working fine in the same project.
error screenshot [https://ibb.co/i7vwiQ](https://ibb.co/i7vwiQ)

**Comment by arkyminds-vasikarans** [comment]
![2017-06-16](https://user-images.githubusercontent.com/20276714/27216710-77a593ca-5294-11e7-911f-0f1d4fc57bf5.png)

**Comment by kartik-v** [comment]
Sorry beyond the scope of this plugin. Would suggest you to check how you register jQuery and other dependent modules in your app framework.
